title = {
	tag = C001
	tier = county
	liege = ICEL
	holder = { character = { type = 10 id = 20580 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C002
	tier = county
	liege = ICEL
	holder = { character = { type = 10 id = 20579 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C003
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20048 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90017 } character = { type = 10 id = 929 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C004
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 929 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90018 } character = { type = 10 id = 20048 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 90019 } character = { type = 10 id = 6180 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C005
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 6180 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90020 } character = { type = 10 id = 929 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C006
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20011 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90002 } character = { type = 10 id = 100525 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C007
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 1000 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C008
	tier = county
	liege = CONN
	holder = { character = { type = 10 id = 910 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C009
	tier = county
	liege = CONN
	holder = { character = { type = 10 id = 1015 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C010
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 6120 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C011
	tier = county
	liege = LEIN
	holder = { character = { type = 10 id = 924 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90016 } character = { type = 10 id = 5788 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C012
	tier = county
	liege = LEIN
	holder = { character = { type = 10 id = 1020 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C013
	tier = county
	liege = MUNS
	holder = { character = { type = 10 id = 906 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C014
	tier = county
	liege = MUNS
	holder = { character = { type = 10 id = 906 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C015
	tier = county
	liege = MUNS
	holder = { character = { type = 10 id = 1010 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C016
	tier = county
	liege = LEIN
	holder = { character = { type = 10 id = 922 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C017
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 6806 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 86116 } character = { type = 10 id = 81841 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 86117 } character = { type = 10 id = 81856 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C018
	tier = county
	liege = DEHE
	holder = { character = { type = 10 id = 81814 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 86131 } character = { type = 10 id = 6362 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 86132 } character = { type = 10 id = 81846 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 86133 } character = { type = 10 id = 81031 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C019
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 6362 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 95033 } character = { type = 10 id = 281704 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 95034 } character = { type = 10 id = 81846 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C020
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 81846 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 86118 } character = { type = 10 id = 281704 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 86119 } character = { type = 10 id = 6362 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C021
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 6806 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C022
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 140 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C023
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 140 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C024
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 172 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C025
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 152 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C026
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 140 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C027
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 140 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C028
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 20090 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C029
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 41260 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C030
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 150 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C031
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 354 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C032
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 140 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C033
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 102574 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C034
	tier = county
	liege = ORKN
	holder = { character = { type = 10 id = 20018 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C035
	tier = county
	liege = WEIS
	holder = { character = { type = 10 id = 5788 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C036
	tier = county
	liege = ORKN
	holder = { character = { type = 10 id = 102538 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C037
	tier = county
	liege = ORKN
	holder = { character = { type = 10 id = 102539 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 91407 } character = { type = 10 id = 984 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 91408 } character = { type = 10 id = 6008 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C038
	tier = county
	liege = MARA
	holder = { character = { type = 10 id = 6008 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C039
	tier = county
	liege = MARA
	holder = { character = { type = 10 id = 6008 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C040
	tier = county
	liege = MARA
	holder = { character = { type = 10 id = 6008 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C041
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 281006 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C042
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 20071 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C043
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 984 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C044
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 984 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C045
	tier = county
	liege = WEIS
	holder = { character = { type = 10 id = 281104 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C046
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 281002 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C047
	tier = county
	liege = LOTH
	holder = { character = { type = 10 id = 281111 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 91401 } character = { type = 10 id = 984 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 91402 } character = { type = 10 id = 281104 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C048
	tier = county
	liege = LOTH
	holder = { character = { type = 10 id = 85018 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 91403 } character = { type = 10 id = 984 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C049
	tier = county
	liege = WEIS
	holder = { character = { type = 10 id = 281526 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 91405 } character = { type = 10 id = 281105 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C050
	tier = county
	liege = WEIS
	holder = { character = { type = 10 id = 281525 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 91406 } character = { type = 10 id = 281105 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C051
	tier = county
	liege = LOTH
	holder = { character = { type = 10 id = 85018 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C052
	tier = county
	liege = LOTH
	holder = { character = { type = 10 id = 85018 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 91410 } character = { type = 10 id = 140 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C053
	tier = county
	liege = LOTH
	holder = { character = { type = 10 id = 963 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C054
	tier = county
	liege = LEIN
	holder = { character = { type = 10 id = 281524 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90015 } character = { type = 10 id = 5788 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C055
	tier = county
	liege = CUMB
	holder = { character = { type = 10 id = 5660 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C056
	tier = county
	liege = CUMB
	holder = { character = { type = 10 id = 281601 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C057
	tier = county
	liege = CUMB
	holder = { character = { type = 10 id = 5660 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C058
	tier = county
	liege = LANC
	holder = { character = { type = 10 id = 5644 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C059
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 90027 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90343 } character = { type = 10 id = 41010 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C060
	tier = county
	liege = GWYN
	holder = { character = { type = 10 id = 40508 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 86121 } character = { type = 10 id = 81841 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 95100 } character = { type = 10 id = 81031 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C061
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 170 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92046 } character = { type = 10 id = 90028 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C062
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 444 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C063
	tier = county
	liege = LANC
	holder = { character = { type = 10 id = 5644 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C064
	tier = county
	liege = GWYN
	holder = { character = { type = 10 id = 6358 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 86125 } character = { type = 10 id = 81841 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 95002 } character = { type = 10 id = 81031 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C065
	tier = county
	liege = GWYN
	holder = { character = { type = 10 id = 40504 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 86126 } character = { type = 10 id = 81841 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 95022 } character = { type = 10 id = 81031 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C066
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 90027 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C067
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 41009 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C068
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 198 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C069
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 140 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C070
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 5650 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C071
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 41011 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C072
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 140 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C073
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 148 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C074
	tier = county
	liege = FLAN
	holder = { character = { type = 10 id = 40900 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C075
	tier = county
	liege = FLAN
	holder = { character = { type = 10 id = 20142 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C076
	tier = county
	liege = FLAN
	holder = { character = { type = 10 id = 364 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C077
	tier = county
	liege = FLAN
	holder = { character = { type = 10 id = 364 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C078
	tier = county
	liege = FLAN
	holder = { character = { type = 10 id = 364 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C079
	tier = county
	liege = HAIN
	holder = { character = { type = 10 id = 106520 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92044 } character = { type = 10 id = 106530 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C080
	tier = county
	liege = HAIN
	holder = { character = { type = 10 id = 106520 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C081
	tier = county
	liege = HAIN
	holder = { character = { type = 10 id = 106520 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92045 } character = { type = 10 id = 106530 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C082
	tier = county
	liege = LOLO
	holder = { character = { type = 10 id = 106530 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C083
	tier = county
	liege = LOLO
	holder = { character = { type = 10 id = 106540 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C084
	tier = county
	liege = LOLO
	holder = { character = { type = 10 id = 106510 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C085
	tier = county
	liege = SAXO
	holder = { character = { type = 10 id = 106510 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C086
	tier = county
	liege = SAXO
	holder = { character = { type = 10 id = 20223 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C087
	tier = county
	liege = SAXO
	holder = { character = { type = 10 id = 20224 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C088
	tier = county
	liege = SAXO
	holder = { character = { type = 10 id = 20218 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C089
	tier = county
	liege = SAXO
	holder = { character = { type = 10 id = 1416 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C090
	tier = county
	liege = LOLO
	holder = { character = { type = 10 id = 20253 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C091
	tier = county
	liege = LOLO
	holder = { character = { type = 10 id = 106570 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C092
	tier = county
	liege = LOLO
	holder = { character = { type = 10 id = 11030 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C093
	tier = county
	liege = FLAN
	holder = { character = { type = 10 id = 364 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C094
	tier = county
	liege = LOLO
	holder = { character = { type = 10 id = 106643 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C095
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 40406 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C096
	tier = county
	liege = NORM
	holder = { character = { type = 10 id = 6820 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90345 } character = { type = 10 id = 41260 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C097
	tier = county
	liege = NORM
	holder = { character = { type = 10 id = 140 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C098
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 40406 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C099
	tier = county
	liege = NORM
	holder = { character = { type = 10 id = 20112 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C100
	tier = county
	liege = NORM
	holder = { character = { type = 10 id = 41250 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 95003 } character = { type = 10 id = 347 } date = { year = 1066 month = december day = 25 } } #BRIT
}
title = {
	tag = C101
	tier = county
	liege = BRIT
	holder = { character = { type = 10 id = 347 } startdate = { year = 1066 month = january day = 0 } } #BRIT
}
title = {
	tag = C102
	tier = county
	liege = BRIT
	holder = { character = { type = 10 id = 346 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C103
	tier = county
	liege = BRIT
	holder = { character = { type = 10 id = 10059 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C104
	tier = county
	liege = BRIT
	holder = { character = { type = 10 id = 178 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C105
	tier = county
	liege = BRIT
	holder = { character = { type = 10 id = 40908 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C106
	tier = county
	liege = BRIT
	holder = { character = { type = 10 id = 178 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C107
	tier = county
	liege = ANJO
	holder = { character = { type = 10 id = 378 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C108
	tier = county
	liege = NORM
	holder = { character = { type = 10 id = 142 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92009 } character = { type = 10 id = 40406 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92010 } character = { type = 10 id = 378 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92011 } character = { type = 10 id = 20298 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 95004 } character = { type = 10 id = 347 } date = { year = 1066 month = december day = 25 } } #BRIT
}
title = {
	tag = C109
	tier = county
	liege = ANJO
	holder = { character = { type = 10 id = 40376 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C110
	tier = county
	liege = CHAM
	holder = { character = { type = 10 id = 394 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C111
	tier = county
	liege = CHAM
	holder = { character = { type = 10 id = 90061 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C112
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 214 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C113
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 418 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C114
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 20132 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C115
	tier = county
	liege = LUXE
	holder = { character = { type = 10 id = 106650 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C116
	tier = county
	liege = LOLO
	holder = { character = { type = 10 id = 106610 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C117
	tier = county
	liege = LOLO
	holder = { character = { type = 10 id = 106600 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C118
	tier = county
	liege = LOLO
	holder = { character = { type = 10 id = 11030 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C119
	tier = county
	liege = LOLO
	holder = { character = { type = 10 id = 20228 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C120
	tier = county
	liege = SAXO
	holder = { character = { type = 10 id = 1416 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C121
	tier = county
	liege = FRAC
	holder = { character = { type = 10 id = 1316 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C122
	tier = county
	liege = FRAC
	holder = { character = { type = 10 id = 1316 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C123
	tier = county
	liege = UPLO
	holder = { character = { type = 10 id = 20256 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C124
	tier = county
	liege = UPLO
	holder = { character = { type = 10 id = 20217 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C125
	tier = county
	liege = SWAB
	holder = { character = { type = 10 id = 20237 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C126
	tier = county
	liege = SWAB
	holder = { character = { type = 10 id = 1342 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C127
	tier = county
	liege = UPLO
	holder = { character = { type = 10 id = 6642 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C128
	tier = county
	liege = UPLO
	holder = { character = { type = 10 id = 20249 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C129
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 11000 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C130
	tier = county
	liege = CHAM
	holder = { character = { type = 10 id = 394 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 95501 } character = { type = 10 id = 391 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C131
	tier = county
	liege = CHAM
	holder = { character = { type = 10 id = 40444 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C132
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 20176 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C133
	tier = county
	liege = UPLO
	holder = { character = { type = 10 id = 6642 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C134
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 11000 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C135
	tier = county
	liege = BURG
	holder = { character = { type = 10 id = 280 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C136
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 210 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C137
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 20176 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C138
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 214 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C139
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 40168 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C140
	tier = county
	liege = ANJO
	holder = { character = { type = 10 id = 380 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C141
	tier = county
	liege = POIT
	holder = { character = { type = 10 id = 240 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C142
	tier = county
	liege = POIT
	holder = { character = { type = 10 id = 40026 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C143
	tier = county
	liege = POIT
	holder = { character = { type = 10 id = 240 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C144
	tier = county
	liege = POIT
	holder = { character = { type = 10 id = 40054 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C145
	tier = county
	liege = POIT
	holder = { character = { type = 10 id = 324 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C146
	tier = county
	liege = POIT
	holder = { character = { type = 10 id = 40160 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C147
	tier = county
	liege = POIT
	holder = { character = { type = 10 id = 40300 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C148
	tier = county
	liege = POIT
	holder = { character = { type = 10 id = 40102 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C149
	tier = county
	liege = BORD
	holder = { character = { type = 10 id = 240 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C150
	tier = county
	liege = ARMA
	holder = { character = { type = 10 id = 40541 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C151
	tier = county
	liege = ARMA
	holder = { character = { type = 10 id = 40902 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C152
	tier = county
	liege = NAVA
	holder = { character = { type = 10 id = 106000 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C153
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 107520 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C154
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 107560 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C155
	tier = county
	liege = LEON
	holder = { character = { type = 10 id = 108510 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C156
	tier = county
	liege = GALC
	holder = { character = { type = 10 id = 85026 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C157
	tier = county
	liege = GALC
	holder = { character = { type = 10 id = 109500 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C158
	tier = county
	liege = BRAG
	holder = { character = { type = 10 id = 109607 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C159
	tier = county
	liege = BRAG
	holder = { character = { type = 10 id = 109610 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C160
	tier = county
	liege = BADA
	holder = { character = { type = 10 id = 20897 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C161
	tier = county
	liege = BADA
	holder = { character = { type = 10 id = 20896 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C162
	tier = county
	liege = SEVI
	holder = { character = { type = 10 id = 20890 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C163
	tier = county
	liege = SEVI
	holder = { character = { type = 10 id = 20889 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C164
	tier = county
	liege = SEVI
	holder = { character = { type = 10 id = 20888 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C165
	tier = county
	liege = SEVI
	holder = { character = { type = 10 id = 3212 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C166
	tier = county
	liege = GRAN
	holder = { character = { type = 10 id = 20882 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C167
	tier = county
	liege = GRAN
	holder = { character = { type = 10 id = 3210 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C168
	tier = county
	liege = ALME
	holder = { character = { type = 10 id = 20876 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C169
	tier = county
	liege = MURC
	holder = { character = { type = 10 id = 3910 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C170
	tier = county
	liege = BALE
	holder = { character = { type = 10 id = 20869 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C171
	tier = county
	liege = VALE
	holder = { character = { type = 10 id = 3928 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C172
	tier = county
	liege = VALE
	holder = { character = { type = 10 id = 3928 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C173
	tier = county
	liege = UGRI
	holder = { character = { type = 10 id = 3934 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C174
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20883 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C175
	tier = county
	liege = UGRI
	holder = { character = { type = 10 id = 3938 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C176
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20855 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C177
	tier = county
	liege = TOLE
	holder = { character = { type = 10 id = 20856 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C178
	tier = county
	liege = TOLE
	holder = { character = { type = 10 id = 3928 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C179
	tier = county
	liege = BALE
	holder = { character = { type = 10 id = 20869 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C180
	tier = county
	liege = GRAN
	holder = { character = { type = 10 id = 3210 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C181
	tier = county
	liege = CORD
	holder = { character = { type = 10 id = 20852 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C182
	tier = county
	liege = SEVI
	holder = { character = { type = 10 id = 3212 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C183
	tier = county
	liege = SEVI
	holder = { character = { type = 10 id = 3212 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C184
	tier = county
	liege = BADA
	holder = { character = { type = 10 id = 3900 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C185
	tier = county
	liege = BADA
	holder = { character = { type = 10 id = 20894 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C186
	tier = county
	liege = BADA
	holder = { character = { type = 10 id = 20895 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C187
	tier = county
	liege = BRAG
	holder = { character = { type = 10 id = 109500 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C188
	tier = county
	liege = BRAG
	holder = { character = { type = 10 id = 109628 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C189
	tier = county
	liege = LEON
	holder = { character = { type = 10 id = 108515 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C190
	tier = county
	liege = LEON
	holder = { character = { type = 10 id = 108500 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C191
	tier = county
	liege = LEON
	holder = { character = { type = 10 id = 108501 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C192
	tier = county
	liege = LEON
	holder = { character = { type = 10 id = 108500 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C193
	tier = county
	liege = BADA
	holder = { character = { type = 10 id = 20898 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C194
	tier = county
	liege = TOLE
	holder = { character = { type = 10 id = 20858 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C195
	tier = county
	liege = BADA
	holder = { character = { type = 10 id = 3900 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C196
	tier = county
	liege = TOLE
	holder = { character = { type = 10 id = 3924 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C197
	tier = county
	liege = TOLE
	holder = { character = { type = 10 id = 3924 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C198
	tier = county
	liege = LEON
	holder = { character = { type = 10 id = 107640 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C199
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 107500 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C200
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 107500 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C201
	tier = county
	liege = NAVA
	holder = { character = { type = 10 id = 106011 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 91003 } character = { type = 10 id = 107500 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C202
	tier = county
	liege = UGRI
	holder = { character = { type = 10 id = 3934 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C203
	tier = county
	liege = UGRI
	holder = { character = { type = 10 id = 3934 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C204
	tier = county
	liege = CATA
	holder = { character = { type = 10 id = 110520 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C205
	tier = county
	liege = CATA
	holder = { character = { type = 10 id = 110580 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C206
	tier = county
	liege = CATA
	holder = { character = { type = 10 id = 110550 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C207
	tier = county
	liege = ARAG
	holder = { character = { type = 10 id = 110500 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C208
	tier = county
	liege = ARMA
	holder = { character = { type = 10 id = 40003 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C209
	tier = county
	liege = ARMA
	holder = { character = { type = 10 id = 40014 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C210
	tier = county
	liege = TOUL
	holder = { character = { type = 10 id = 6620 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C211
	tier = county
	liege = CATA
	holder = { character = { type = 10 id = 110610 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C212
	tier = county
	liege = TOUL
	holder = { character = { type = 10 id = 40212 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C213
	tier = county
	liege = TOUL
	holder = { character = { type = 10 id = 40204 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C214
	tier = county
	liege = TOUL
	holder = { character = { type = 10 id = 336 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C215
	tier = county
	liege = BORD
	holder = { character = { type = 10 id = 240 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C216
	tier = county
	liege = BORD
	holder = { character = { type = 10 id = 40074 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C217
	tier = county
	liege = BORD
	holder = { character = { type = 10 id = 306 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C218
	tier = county
	liege = TOUL
	holder = { character = { type = 10 id = 338 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C219
	tier = county
	liege = TOUL
	holder = { character = { type = 10 id = 10034 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C220
	tier = county
	liege = TOUL
	holder = { character = { type = 10 id = 40204 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 95000 } character = { type = 10 id = 110520 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C221
	tier = county
	liege = PROV
	holder = { character = { type = 10 id = 420 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C222
	tier = county
	liege = PROV
	holder = { character = { type = 10 id = 20283 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C223
	tier = county
	liege = PROV
	holder = { character = { type = 10 id = 20291 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C224
	tier = county
	liege = BURG
	holder = { character = { type = 10 id = 20290 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C225
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 288 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C226
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 210 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C227
	tier = county
	liege = BURG
	holder = { character = { type = 10 id = 20290 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C228
	tier = county
	liege = PROV
	holder = { character = { type = 10 id = 40464 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C229
	tier = county
	liege = PROV
	holder = { character = { type = 10 id = 40802 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C230
	tier = county
	liege = GENO
	holder = { character = { type = 10 id = 20315 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C231
	tier = county
	liege = ITAL
	holder = { character = { type = 10 id = 7735 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C232
	tier = county
	liege = ITAL
	holder = { character = { type = 10 id = 7730 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C233
	tier = county
	liege = GENO
	holder = { character = { type = 10 id = 20314 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C234
	tier = county
	liege = MILA
	holder = { character = { type = 10 id = 1118 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C235
	tier = county
	liege = MILA
	holder = { character = { type = 10 id = 1118 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C236
	tier = county
	liege = ITAL
	holder = { character = { type = 10 id = 1182 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C237
	tier = county
	liege = BURG
	holder = { character = { type = 10 id = 1182 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C238
	tier = county
	liege = BURG
	holder = { character = { type = 10 id = 20284 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C239
	tier = county
	liege = BURG
	holder = { character = { type = 10 id = 20292 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C240
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 40364 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C241
	tier = county
	liege = BURG
	holder = { character = { type = 10 id = 20288 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C242
	tier = county
	liege = BURG
	holder = { character = { type = 10 id = 20289 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C244
	tier = county
	liege = BURG
	holder = { character = { type = 10 id = 20287 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C245
	tier = county
	liege = SWAB
	holder = { character = { type = 10 id = 20286 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C246
	tier = county
	liege = MILA
	holder = { character = { type = 10 id = 20299 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C247
	tier = county
	liege = SWAB
	holder = { character = { type = 10 id = 20247 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C248
	tier = county
	liege = SWAB
	holder = { character = { type = 10 id = 1388 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C249
	tier = county
	liege = SWAB
	holder = { character = { type = 10 id = 40550 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C250
	tier = county
	liege = KARN
	holder = { character = { type = 10 id = 1610 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C251
	tier = county
	liege = SWAB
	holder = { character = { type = 10 id = 7054 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C252
	tier = county
	liege = SWAB
	holder = { character = { type = 10 id = 1388 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C253
	tier = county
	liege = SWAB
	holder = { character = { type = 10 id = 1388 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C254
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 1316 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C255
	tier = county
	liege = THUR
	holder = { character = { type = 10 id = 20234 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C256
	tier = county
	liege = THUR
	holder = { character = { type = 10 id = 20235 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C257
	tier = county
	liege = SAXO
	holder = { character = { type = 10 id = 1416 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C258
	tier = county
	liege = SAXO
	holder = { character = { type = 10 id = 1416 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C259
	tier = county
	liege = SAXO
	holder = { character = { type = 10 id = 1416 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C260
	tier = county
	liege = MECK
	holder = { character = { type = 10 id = 20584 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90348 } character = { type = 10 id = 8400 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 90349 } character = { type = 10 id = 8402 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C261
	tier = county
	liege = SAXO
	holder = { character = { type = 10 id = 20251 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C262
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 8400 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C263
	tier = county
	liege = SVIG
	holder = { character = { type = 10 id = 101517 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C264
	tier = county
	liege = SVIG
	holder = { character = { type = 10 id = 101517 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C265
	tier = county
	liege = DENM
	holder = { character = { type = 10 id = 101515 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C266
	tier = county
	liege = DENM
	holder = { character = { type = 10 id = 101540 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C267
	tier = county
	liege = DENM
	holder = { character = { type = 10 id = 101541 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C268
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 20016 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C269
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 102567 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C270
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 20017 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C271
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 102534 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C272
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 102534 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C273
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 102534 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C274
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 102563 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C275
	tier = county
	liege = TRON
	holder = { character = { type = 10 id = 102553 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C276
	tier = county
	liege = TRON
	holder = { character = { type = 10 id = 102547 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C277
	tier = county
	liege = TRON
	holder = { character = { type = 10 id = 102532 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C278
	tier = county
	liege = TRON
	holder = { character = { type = 10 id = 102532 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C279
	tier = county
	liege = WSAM
	holder = { character = { type = 10 id = 20617 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C280
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20015 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C281
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20014 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C282
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 102575 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C283
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20013 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C284
	tier = county
	liege = TRON
	holder = { character = { type = 10 id = 20019 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C285
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 100527 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90004 } character = { type = 10 id = 100525 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C286
	tier = county
	liege = UPPL
	holder = { character = { type = 10 id = 100544 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C287
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 20005 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C288
	tier = county
	liege = VAST
	holder = { character = { type = 10 id = 102523 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C289
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 100546 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C290
	tier = county
	liege = UPPL
	holder = { character = { type = 10 id = 100516 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C291
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20006 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C292
	tier = county
	liege = UPPL
	holder = { character = { type = 10 id = 100516 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C293
	tier = county
	liege = OSTR
	holder = { character = { type = 10 id = 100530 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C294
	tier = county
	liege = VAST
	holder = { character = { type = 10 id = 20009 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C295
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20008 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C296
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 102534 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C297
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 100525 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C298
	tier = county
	liege = OSTR
	holder = { character = { type = 10 id = 20010 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C299
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20012 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90003 } character = { type = 10 id = 100525 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C300
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 20007 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C301
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 100532 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C302
	tier = county
	liege = DENM
	holder = { character = { type = 10 id = 101515 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C303
	tier = county
	liege = DENM
	holder = { character = { type = 10 id = 101515 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C304
	tier = county
	liege = MECK
	holder = { character = { type = 10 id = 8420 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C305
	tier = county
	liege = DENM
	holder = { character = { type = 10 id = 101546 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C306
	tier = county
	liege = MECK
	holder = { character = { type = 10 id = 20584 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90350 } character = { type = 10 id = 8400 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 90351 } character = { type = 10 id = 8402 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C307
	tier = county
	liege = MECK
	holder = { character = { type = 10 id = 20584 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C308
	tier = county
	liege = MECK
	holder = { character = { type = 10 id = 20625 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C309
	tier = county
	liege = BRAN
	holder = { character = { type = 10 id = 20263 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C310
	tier = county
	liege = BRAN
	holder = { character = { type = 10 id = 20262 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C311
	tier = county
	liege = THUR
	holder = { character = { type = 10 id = 20266 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C312
	tier = county
	liege = MEIS
	holder = { character = { type = 10 id = 7060 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C313
	tier = county
	liege = FRAC
	holder = { character = { type = 10 id = 20239 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C314
	tier = county
	liege = BAVA
	holder = { character = { type = 10 id = 20258 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C315
	tier = county
	liege = BAVA
	holder = { character = { type = 10 id = 112600 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C316
	tier = county
	liege = BAVA
	holder = { character = { type = 10 id = 1614 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C317
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 20312 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C318
	tier = county
	liege = TOSC
	holder = { character = { type = 10 id = 7757 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C319
	tier = county
	liege = KARN
	holder = { character = { type = 10 id = 1610 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C320
	tier = county
	liege = TOSC
	holder = { character = { type = 10 id = 20305 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C321
	tier = county
	liege = ITAL
	holder = { character = { type = 10 id = 2009 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C322
	tier = county
	liege = TOSC
	holder = { character = { type = 10 id = 7757 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C323
	tier = county
	liege = TOSC
	holder = { character = { type = 10 id = 2022 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C324
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20324 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90007 } character = { type = 10 id = 20314 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92002 } character = { type = 10 id = 20323 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C325
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20325 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92003 } character = { type = 10 id = 20323 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92005 } character = { type = 10 id = 20314 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C326
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20326 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92004 } character = { type = 10 id = 20324 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92006 } character = { type = 10 id = 20314 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C327
	tier = county
	liege = LANG
	holder = { character = { type = 10 id = 20323 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C328
	tier = county
	liege = TOSC
	holder = { character = { type = 10 id = 2006 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C329
	tier = county
	liege = ITAL
	holder = { character = { type = 10 id = 20331 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90010 } character = { type = 10 id = 2008 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C330
	tier = county
	liege = TOSC
	holder = { character = { type = 10 id = 20321 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C331
	tier = county
	liege = LANG
	holder = { character = { type = 10 id = 20320 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C332
	tier = county
	liege = PAPA
	holder = { character = { type = 10 id = 2010 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C333
	tier = county
	liege = PAPA
	holder = { character = { type = 10 id = 2008 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C334
	tier = county
	liege = CAMP
	holder = { character = { type = 10 id = 20498 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92007 } character = { type = 10 id = 1128 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C335
	tier = county
	liege = APUL
	holder = { character = { type = 10 id = 1130 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92000 } character = { type = 10 id = 2008 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C336
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 1119 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C337
	tier = county
	liege = APUL
	holder = { character = { type = 10 id = 1128 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C338
	tier = county
	liege = APUL
	holder = { character = { type = 10 id = 1132 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C339
	tier = county
	liege = APUL
	holder = { character = { type = 10 id = 1132 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C340
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20832 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C341
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20831 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C342
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20832 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C343
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20829 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C344
	tier = county
	liege = APUL
	holder = { character = { type = 10 id = 1134 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C345
	tier = county
	liege = APUL
	holder = { character = { type = 10 id = 19111155 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C346
	tier = county
	liege = APUL
	holder = { character = { type = 10 id = 1128 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C347
	tier = county
	liege = APUL
	holder = { character = { type = 10 id = 1128 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C348
	tier = county
	liege = APUL
	holder = { character = { type = 10 id = 85003 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C349
	tier = county
	liege = SPOL
	holder = { character = { type = 10 id = 7757 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C350
	tier = county
	liege = ITAL
	holder = { character = { type = 10 id = 20332 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90009 } character = { type = 10 id = 2008 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C351
	tier = county
	liege = ROMA
	holder = { character = { type = 10 id = 7740 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90011 } character = { type = 10 id = 2008 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C352
	tier = county
	liege = ITAL
	holder = { character = { type = 10 id = 20335 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90008 } character = { type = 10 id = 2008 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C353
	tier = county
	liege = TOSC
	holder = { character = { type = 10 id = 7757 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C354
	tier = county
	liege = TOSC
	holder = { character = { type = 10 id = 7757 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C355
	tier = county
	liege = VERO
	holder = { character = { type = 10 id = 20307 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C356
	tier = county
	liege = VENI
	holder = { character = { type = 10 id = 7800 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C357
	tier = county
	liege = VERO
	holder = { character = { type = 10 id = 20352 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C358
	tier = county
	liege = VERO
	holder = { character = { type = 10 id = 7700 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C359
	tier = county
	liege = BAVA
	holder = { character = { type = 10 id = 40717 } startdate = { year = 1054 month = january day = 0 } }
}
title = {
	tag = C360
	tier = county
	liege = BAVA
	holder = { character = { type = 10 id = 112600 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C361
	tier = county
	liege = BAVA
	holder = { character = { type = 10 id = 20257 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C362
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 522 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C363
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 522 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C364
	tier = county
	liege = MEIS
	holder = { character = { type = 10 id = 20265 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C365
	tier = county
	liege = BRAN
	holder = { character = { type = 10 id = 7032 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C366
	tier = county
	liege = POMM
	holder = { character = { type = 10 id = 20623 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C367
	tier = county
	liege = POMM
	holder = { character = { type = 10 id = 20623 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C368
	tier = county
	liege = POMM
	holder = { character = { type = 10 id = 20626 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C369
	tier = county
	liege = PRUT
	holder = { character = { type = 10 id = 28015 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C370
	tier = county
	liege = PRUT
	holder = { character = { type = 10 id = 28015 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C371
	tier = county
	liege = PRUT
	holder = { character = { type = 10 id = 28016 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C372
	tier = county
	liege = CURO
	holder = { character = { type = 10 id = 28075 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C373
	tier = county
	liege = CURO
	holder = { character = { type = 10 id = 28075 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C374
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20603 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C375
	tier = county
	liege = LETT
	holder = { character = { type = 10 id = 28020 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C376
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 28021 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C377
	tier = county
	liege = LIVO
	holder = { character = { type = 10 id = 28023 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C378
	tier = county
	liege = ESTS
	holder = { character = { type = 10 id = 28026 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C379
	tier = county
	liege = ESTS
	holder = { character = { type = 10 id = 28025 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C380
	tier = county
	liege = ESTS
	holder = { character = { type = 10 id = 28026 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C381
	tier = county
	liege = TAVA
	holder = { character = { type = 10 id = 28003 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C382
	tier = county
	liege = FINL
	holder = { character = { type = 10 id = 20612 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C383
	tier = county
	liege = TAVA
	holder = { character = { type = 10 id = 28003 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C384
	tier = county
	liege = SATA
	holder = { character = { type = 10 id = 28011 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C385
	tier = county
	liege = KAJA
	holder = { character = { type = 10 id = 28010 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C386
	tier = county
	liege = ESAM
	holder = { character = { type = 10 id = 20618 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C387
	tier = county
	liege = KOLA
	holder = { character = { type = 10 id = 28009 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C388
	tier = county
	liege = KARE
	holder = { character = { type = 10 id = 28004 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C389
	tier = county
	liege = KAJA
	holder = { character = { type = 10 id = 28010 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C390
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 28005 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C391
	tier = county
	liege = VOTE
	holder = { character = { type = 10 id = 28006 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C392
	tier = county
	liege = KEXH
	holder = { character = { type = 10 id = 28035 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C393
	tier = county
	liege = KARE
	holder = { character = { type = 10 id = 28004 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C394
	tier = county
	liege = BJAR
	holder = { character = { type = 10 id = 20620 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C395
	tier = county
	liege = BJAR
	holder = { character = { type = 10 id = 20620 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C396
	tier = county
	liege = BJAR
	holder = { character = { type = 10 id = 20620 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C397
	tier = county
	liege = SAME
	holder = { character = { type = 10 id = 20619 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C398
	tier = county
	liege = SAME
	holder = { character = { type = 10 id = 20619 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C399
	tier = county
	liege = SAME
	holder = { character = { type = 10 id = 20619 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C400
	tier = county
	liege = URAL
	holder = { character = { type = 10 id = 3504 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C401
	tier = county
	liege = SAME
	holder = { character = { type = 10 id = 20619 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C402
	tier = county
	liege = SAME
	holder = { character = { type = 10 id = 20619 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C403
	tier = county
	liege = BJAR
	holder = { character = { type = 10 id = 20620 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C404
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 686 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C405
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 686 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C406
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 686 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C407
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 630 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C408
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 20419 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C409
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 686 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C410
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 686 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C411
	tier = county
	liege = INGE
	holder = { character = { type = 10 id = 28007 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C412
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 686 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C413
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 20446 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C414
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 20445 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C415
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 686 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C416
	tier = county
	liege = POLO
	holder = { character = { type = 10 id = 650 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C417
	tier = county
	liege = POLO
	holder = { character = { type = 10 id = 20449 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C418
	tier = county
	liege = POLO
	holder = { character = { type = 10 id = 20468 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C419
	tier = county
	liege = POLO
	holder = { character = { type = 10 id = 650 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C420
	tier = county
	liege = LITT
	holder = { character = { type = 10 id = 28012 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C421
	tier = county
	liege = LITT
	holder = { character = { type = 10 id = 28022 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C422
	tier = county
	liege = YATV
	holder = { character = { type = 10 id = 28017 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C423
	tier = county
	liege = YATV
	holder = { character = { type = 10 id = 28017 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C424
	tier = county
	liege = POLO
	holder = { character = { type = 10 id = 650 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C425
	tier = county
	liege = GALI
	holder = { character = { type = 10 id = 20460 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C426
	tier = county
	liege = YATV
	holder = { character = { type = 10 id = 28017 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C427
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 28019 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C428
	tier = county
	liege = MAZO
	holder = { character = { type = 10 id = 764 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C429
	tier = county
	liege = WIEL
	holder = { character = { type = 10 id = 20393 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C430
	tier = county
	liege = WIEL
	holder = { character = { type = 10 id = 20390 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C431
	tier = county
	liege = WIEL
	holder = { character = { type = 10 id = 20393 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C432
	tier = county
	liege = SAND
	holder = { character = { type = 10 id = 20388 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C433
	tier = county
	liege = SILE
	holder = { character = { type = 10 id = 20396 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C434
	tier = county
	liege = SILE
	holder = { character = { type = 10 id = 20396 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90021 } character = { type = 10 id = 522 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C435
	tier = county
	liege = SILE
	holder = { character = { type = 10 id = 20396 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90022 } character = { type = 10 id = 522 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C436
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 522 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C437
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 522 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C438
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 526 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C439
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 522 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C440
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 524 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C441
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 535 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C442
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 472 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C443
	tier = county
	liege = SLOV
	holder = { character = { type = 10 id = 20369 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C444
	tier = county
	liege = PRES
	holder = { character = { type = 10 id = 4431 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C445
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 476 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C446
	tier = county
	liege = OSTE
	holder = { character = { type = 10 id = 7200 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C447
	tier = county
	liege = OSTE
	holder = { character = { type = 10 id = 20260 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C448
	tier = county
	liege = BAVA
	holder = { character = { type = 10 id = 20259 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C449
	tier = county
	liege = OSTE
	holder = { character = { type = 10 id = 7200 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C450
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 476 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C451
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 20356 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C452
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 20362 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C453
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 20360 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C454
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 1621 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C455
	tier = county
	liege = KARN
	holder = { character = { type = 10 id = 1620 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C456
	tier = county
	liege = KARN
	holder = { character = { type = 10 id = 1610 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C457
	tier = county
	liege = KARN
	holder = { character = { type = 10 id = 1616 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C458
	tier = county
	liege = KARN
	holder = { character = { type = 10 id = 1616 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C459
	tier = county
	liege = CROA
	holder = { character = { type = 10 id = 20380 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C460
	tier = county
	liege = SLAV
	holder = { character = { type = 10 id = 8628 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92041 } character = { type = 10 id = 476 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C461
	tier = county
	liege = SLAV
	holder = { character = { type = 10 id = 8628 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92042 } character = { type = 10 id = 476 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C462
	tier = county
	liege = SLAV
	holder = { character = { type = 10 id = 8628 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92043 } character = { type = 10 id = 476 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C463
	tier = county
	liege = CROA
	holder = { character = { type = 10 id = 20381 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C464
	tier = county
	liege = CROA
	holder = { character = { type = 10 id = 8622 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C465
	tier = county
	liege = ZARB
	holder = { character = { type = 10 id = 8622 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92038 } character = { type = 10 id = 7800 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C466
	tier = county
	liege = CROA
	holder = { character = { type = 10 id = 20382 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C467
	tier = county
	liege = ZARB
	holder = { character = { type = 10 id = 8622 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92039 } character = { type = 10 id = 7800 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C468
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20497 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C469
	tier = county
	liege = BELG
	holder = { character = { type = 10 id = 20491 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C470
	tier = county
	liege = DYRR
	holder = { character = { type = 10 id = 20499 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C471
	tier = county
	liege = DYRR
	holder = { character = { type = 10 id = 20487 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C472
	tier = county
	liege = BUTR
	holder = { character = { type = 10 id = 90093 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C473
	tier = county
	liege = BUTR
	holder = { character = { type = 10 id = 1764 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C474
	tier = county
	liege = BUTR
	holder = { character = { type = 10 id = 20502 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C475
	tier = county
	liege = HELL
	holder = { character = { type = 10 id = 20509 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C476
	tier = county
	liege = ACHA
	holder = { character = { type = 10 id = 1766 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C477
	tier = county
	liege = ACHA
	holder = { character = { type = 10 id = 20506 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C478
	tier = county
	liege = ACHA
	holder = { character = { type = 10 id = 20505 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C479
	tier = county
	liege = KRET
	holder = { character = { type = 10 id = 20517 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C480
	tier = county
	liege = KRET
	holder = { character = { type = 10 id = 20516 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C481
	tier = county
	liege = ACHA
	holder = { character = { type = 10 id = 20504 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C482
	tier = county
	liege = HELL
	holder = { character = { type = 10 id = 20507 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C483
	tier = county
	liege = LYKI
	holder = { character = { type = 10 id = 20519 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C484
	tier = county
	liege = AEGE
	holder = { character = { type = 10 id = 20514 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C485
	tier = county
	liege = AEGE
	holder = { character = { type = 10 id = 20513 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C486
	tier = county
	liege = SAMS
	holder = { character = { type = 10 id = 42003 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C487
	tier = county
	liege = AEGE
	holder = { character = { type = 10 id = 20515 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C488
	tier = county
	liege = HELL
	holder = { character = { type = 10 id = 20508 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C489
	tier = county
	liege = HELL
	holder = { character = { type = 10 id = 20510 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C490
	tier = county
	liege = THES
	holder = { character = { type = 10 id = 1732 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C491
	tier = county
	liege = ADRI
	holder = { character = { type = 10 id = 20512 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C492
	tier = county
	liege = DYRR
	holder = { character = { type = 10 id = 20484 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C493
	tier = county
	liege = ADRI
	holder = { character = { type = 10 id = 20476 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C494
	tier = county
	liege = ADRI
	holder = { character = { type = 10 id = 1736 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 91000 } character = { type = 10 id = 20502 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C495
	tier = county
	liege = ADRI
	holder = { character = { type = 10 id = 20475 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C496
	tier = county
	liege = BYZA
	holder = { character = { type = 10 id = 1732 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C497
	tier = county
	liege = BYZA
	holder = { character = { type = 10 id = 1732 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C498
	tier = county
	liege = VARN
	holder = { character = { type = 10 id = 85011 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C499
	tier = county
	liege = DORO
	holder = { character = { type = 10 id = 20478 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C500
	tier = county
	liege = DORO
	holder = { character = { type = 10 id = 1740 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C501
	tier = county
	liege = VIDI
	holder = { character = { type = 10 id = 20486 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C502
	tier = county
	liege = BELG
	holder = { character = { type = 10 id = 20529 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C503
	tier = county
	liege = BELG
	holder = { character = { type = 10 id = 20529 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C504
	tier = county
	liege = CROA
	holder = { character = { type = 10 id = 8622 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C505
	tier = county
	liege = VIDI
	holder = { character = { type = 10 id = 20488 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C506
	tier = county
	liege = VIDI
	holder = { character = { type = 10 id = 20489 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C507
	tier = county
	liege = DORO
	holder = { character = { type = 10 id = 20485 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C508
	tier = county
	liege = DORO
	holder = { character = { type = 10 id = 20479 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C509
	tier = county
	liege = VARN
	holder = { character = { type = 10 id = 20480 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C510
	tier = county
	liege = VARN
	holder = { character = { type = 10 id = 20481 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C511
	tier = county
	liege = VARN
	holder = { character = { type = 10 id = 20482 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C512
	tier = county
	liege = PECH
	holder = { character = { type = 10 id = 20635 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C513
	tier = county
	liege = PECH
	holder = { character = { type = 10 id = 20636 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C514
	tier = county
	liege = PECH
	holder = { character = { type = 10 id = 20637 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C515
	tier = county
	liege = PECH
	holder = { character = { type = 10 id = 20638 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C516
	tier = county
	liege = PECH
	holder = { character = { type = 10 id = 20639 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C517
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 20364 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C518
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 20363 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C519
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 20365 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C520
	tier = county
	liege = SLOV
	holder = { character = { type = 10 id = 474 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C521
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 20357 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C522
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 4435 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C523
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 20366 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C524
	tier = county
	liege = SLOV
	holder = { character = { type = 10 id = 20367 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C525
	tier = county
	liege = SLOV
	holder = { character = { type = 10 id = 20370 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C526
	tier = county
	liege = POLA
	holder = { character = { type = 10 id = 762 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C527
	tier = county
	liege = POLA
	holder = { character = { type = 10 id = 762 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C528
	tier = county
	liege = SAND
	holder = { character = { type = 10 id = 20388 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C529
	tier = county
	liege = MAZO
	holder = { character = { type = 10 id = 764 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C530
	tier = county
	liege = MAZO
	holder = { character = { type = 10 id = 20395 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C531
	tier = county
	liege = POLA
	holder = { character = { type = 10 id = 762 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C532
	tier = county
	liege = POLA
	holder = { character = { type = 10 id = 762 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C533
	tier = county
	liege = SLOV
	holder = { character = { type = 10 id = 20366 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C534
	tier = county
	liege = KIEV
	holder = { character = { type = 10 id = 626 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C535
	tier = county
	liege = KIEV
	holder = { character = { type = 10 id = 20458 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C536
	tier = county
	liege = KIEV
	holder = { character = { type = 10 id = 626 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C537
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 20373 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C538
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 20372 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C539
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 476 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C540
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 476 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C541
	tier = county
	liege = PECH
	holder = { character = { type = 10 id = 20640 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C542
	tier = county
	liege = PECH
	holder = { character = { type = 10 id = 20641 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C543
	tier = county
	liege = PECH
	holder = { character = { type = 10 id = 20642 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C544
	tier = county
	liege = KIEV
	holder = { character = { type = 10 id = 626 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C545
	tier = county
	liege = KIEV
	holder = { character = { type = 10 id = 626 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C546
	tier = county
	liege = KIEV
	holder = { character = { type = 10 id = 626 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C547
	tier = county
	liege = KIEV
	holder = { character = { type = 10 id = 626 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C548
	tier = county
	liege = KIEV
	holder = { character = { type = 10 id = 626 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C549
	tier = county
	liege = GALI
	holder = { character = { type = 10 id = 20459 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C550
	tier = county
	liege = POLO
	holder = { character = { type = 10 id = 650 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C551
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 20448 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C552
	tier = county
	liege = KIEV
	holder = { character = { type = 10 id = 626 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C553
	tier = county
	liege = KIEV
	holder = { character = { type = 10 id = 626 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C554
	tier = county
	liege = SUZD
	holder = { character = { type = 10 id = 628 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C555
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 630 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C556
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 20648 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C557
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 20650 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C558
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 20646 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C559
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 20647 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C560
	tier = county
	liege = CHER
	holder = { character = { type = 10 id = 20463 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C561
	tier = county
	liege = CHER
	holder = { character = { type = 10 id = 20463 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C562
	tier = county
	liege = SUZD
	holder = { character = { type = 10 id = 654 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C563
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 806 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C564
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 806 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C565
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 20648 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C566
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 20651 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C567
	tier = county
	liege = SUZD
	holder = { character = { type = 10 id = 628 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C568
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 630 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C569
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 630 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C570
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 20423 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C571
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 20420 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C572
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 20421 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C573
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 666 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C574
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 666 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C575
	tier = county
	liege = MINS
	holder = { character = { type = 10 id = 90149 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C576
	tier = county
	liege = MINS
	holder = { character = { type = 10 id = 90149 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C577
	tier = county
	liege = SUZD
	holder = { character = { type = 10 id = 20453 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C578
	tier = county
	liege = MINS
	holder = { character = { type = 10 id = 90149 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C579
	tier = county
	liege = MORD
	holder = { character = { type = 10 id = 20629 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C580
	tier = county
	liege = MINS
	holder = { character = { type = 10 id = 90149 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C581
	tier = county
	liege = MINS
	holder = { character = { type = 10 id = 90149 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C582
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 630 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C583
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 20416 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C584
	tier = county
	liege = MINS
	holder = { character = { type = 10 id = 90149 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C585
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 630 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C586
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 630 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C587
	tier = county
	liege = SMOL
	holder = { character = { type = 10 id = 20450 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C588
	tier = county
	liege = MORD
	holder = { character = { type = 10 id = 20630 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C589
	tier = county
	liege = MORD
	holder = { character = { type = 10 id = 20631 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C590
	tier = county
	liege = MORD
	holder = { character = { type = 10 id = 20632 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C591
	tier = county
	liege = MORD
	holder = { character = { type = 10 id = 20633 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C592
	tier = county
	liege = MORD
	holder = { character = { type = 10 id = 20628 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C593
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 20651 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C594
	tier = county
	liege = DONA
	holder = { character = { type = 10 id = 20653 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C595
	tier = county
	liege = DONA
	holder = { character = { type = 10 id = 20653 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C596
	tier = county
	liege = AZOV
	holder = { character = { type = 10 id = 20655 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C597
	tier = county
	liege = AZOV
	holder = { character = { type = 10 id = 20656 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C598
	tier = county
	liege = SUZD
	holder = { character = { type = 10 id = 654 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90023 } character = { type = 10 id = 9126 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C599
	tier = county
	liege = AZOV
	holder = { character = { type = 10 id = 20657 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C600
	tier = county
	liege = GEOR
	holder = { character = { type = 10 id = 9952 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C601
	tier = county
	liege = GEOR
	holder = { character = { type = 10 id = 9952 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C602
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20664 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C603
	tier = county
	liege = ALAN
	holder = { character = { type = 10 id = 20662 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C604
	tier = county
	liege = ALAN
	holder = { character = { type = 10 id = 20662 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C605
	tier = county
	liege = ALAN
	holder = { character = { type = 10 id = 20665 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C606
	tier = county
	liege = ALAN
	holder = { character = { type = 10 id = 20666 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C607
	tier = county
	liege = AZOV
	holder = { character = { type = 10 id = 20658 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C608
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 806 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C609
	tier = county
	liege = URAL
	holder = { character = { type = 10 id = 3504 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C610
	tier = county
	liege = URAL
	holder = { character = { type = 10 id = 3504 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C611
	tier = county
	liege = URAL
	holder = { character = { type = 10 id = 3504 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C612
	tier = county
	liege = URAL
	holder = { character = { type = 10 id = 3504 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C613
	tier = county
	liege = URAL
	holder = { character = { type = 10 id = 3504 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C614
	tier = county
	liege = VOLG
	holder = { character = { type = 10 id = 20923 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C615
	tier = county
	liege = VOLG
	holder = { character = { type = 10 id = 20923 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C616
	tier = county
	liege = VOLG
	holder = { character = { type = 10 id = 20923 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C617
	tier = county
	liege = VOLG
	holder = { character = { type = 10 id = 20923 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C618
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 806 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C619
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 806 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C620
	tier = county
	liege = KHAZ
	holder = { character = { type = 10 id = 20663 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C621
	tier = county
	liege = TURK
	holder = { character = { type = 10 id = 3072 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C622
	tier = county
	liege = TURK
	holder = { character = { type = 10 id = 3072 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C623
	tier = county
	liege = MKHW
	holder = { character = { type = 10 id = 20713 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C624
	tier = county
	liege = TURK
	holder = { character = { type = 10 id = 3072 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C625
	tier = county
	liege = TURK
	holder = { character = { type = 10 id = 3072 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C626
	tier = county
	liege = QARA
	holder = { character = { type = 10 id = 3014 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C627
	tier = county
	liege = MKHW
	holder = { character = { type = 10 id = 20713 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C628
	tier = county
	liege = QARA
	holder = { character = { type = 10 id = 3014 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C629
	tier = county
	liege = MKHW
	holder = { character = { type = 10 id = 20702 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C630
	tier = county
	liege = QARA
	holder = { character = { type = 10 id = 20700 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C631
	tier = county
	liege = MKHW
	holder = { character = { type = 10 id = 20701 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C632
	tier = county
	liege = LUTA
	holder = { character = { type = 10 id = 20688 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C633
	tier = county
	liege = LUTA
	holder = { character = { type = 10 id = 20699 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C634
	tier = county
	liege = LUTA
	holder = { character = { type = 10 id = 20698 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C635
	tier = county
	liege = MSIS
	holder = { character = { type = 10 id = 20707 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C636
	tier = county
	liege = ESFA
	holder = { character = { type = 10 id = 20705 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C637
	tier = county
	liege = MSIS
	holder = { character = { type = 10 id = 20707 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C638
	tier = county
	liege = ESFA
	holder = { character = { type = 10 id = 20705 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C639
	tier = county
	liege = HORM
	holder = { character = { type = 10 id = 3041 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C640
	tier = county
	liege = HORM
	holder = { character = { type = 10 id = 20710 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C641
	tier = county
	liege = HORM
	holder = { character = { type = 10 id = 20711 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C642
	tier = county
	liege = HORM
	holder = { character = { type = 10 id = 20712 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C643
	tier = county
	liege = HORM
	holder = { character = { type = 10 id = 3854 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C644
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 3040 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C645
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 3040 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C646
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 3040 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C647
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 3040 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C648
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 3040 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C649
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 20670 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C650
	tier = county
	liege = MARB
	holder = { character = { type = 10 id = 20900 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C651
	tier = county
	liege = MARB
	holder = { character = { type = 10 id = 20900 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C652
	tier = county
	liege = MARB
	holder = { character = { type = 10 id = 20900 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C653
	tier = county
	liege = MARB
	holder = { character = { type = 10 id = 20900 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C654
	tier = county
	liege = MARB
	holder = { character = { type = 10 id = 20900 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C655
	tier = county
	liege = MARB
	holder = { character = { type = 10 id = 20900 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C656
	tier = county
	liege = LURI
	holder = { character = { type = 10 id = 3814 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C657
	tier = county
	liege = LURI
	holder = { character = { type = 10 id = 20691 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C658
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 3040 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C659
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 3040 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C660
	tier = county
	liege = LUTA
	holder = { character = { type = 10 id = 20697 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C661
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 20704 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C662
	tier = county
	liege = MMAZ
	holder = { character = { type = 10 id = 20703 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C663
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 3040 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C664
	tier = county
	liege = LURI
	holder = { character = { type = 10 id = 20690 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C665
	tier = county
	liege = MMAZ
	holder = { character = { type = 10 id = 20716 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C666
	tier = county
	liege = MMAZ
	holder = { character = { type = 10 id = 20716 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C667
	tier = county
	liege = AZER
	holder = { character = { type = 10 id = 20722 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C668
	tier = county
	liege = DERB
	holder = { character = { type = 10 id = 20734 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C669
	tier = county
	liege = DERB
	holder = { character = { type = 10 id = 20734 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C670
	tier = county
	liege = AZER
	holder = { character = { type = 10 id = 20722 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C671
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 41557 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C672
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 41600 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94002 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C673
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 41600 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C674
	tier = county
	liege = DERB
	holder = { character = { type = 10 id = 20734 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C675
	tier = county
	liege = DERB
	holder = { character = { type = 10 id = 20734 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C676
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 41515 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C677
	tier = county
	liege = GEOR
	holder = { character = { type = 10 id = 9952 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C678
	tier = county
	liege = TRAP
	holder = { character = { type = 10 id = 20544 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94006 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C679
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 41607 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C680
	tier = county
	liege = DGEO
	holder = { character = { type = 10 id = 85012 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C681
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 41513 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94000 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C682
	tier = county
	liege = ARME
	holder = { character = { type = 10 id = 41585 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94001 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C683
	tier = county
	liege = MEDE
	holder = { character = { type = 10 id = 20738 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C684
	tier = county
	liege = MMOS
	holder = { character = { type = 10 id = 20719 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C685
	tier = county
	liege = MMOS
	holder = { character = { type = 10 id = 20718 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C686
	tier = county
	liege = MMOS
	holder = { character = { type = 10 id = 20717 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C687
	tier = county
	liege = MMOS
	holder = { character = { type = 10 id = 20676 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C688
	tier = county
	liege = LURI
	holder = { character = { type = 10 id = 20677 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C689
	tier = county
	liege = LURI
	holder = { character = { type = 10 id = 20678 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C690
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 20671 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C691
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 20672 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C692
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 20673 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C693
	tier = county
	liege = ABBA
	holder = { character = { type = 10 id = 3084 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C694
	tier = county
	liege = ABBA
	holder = { character = { type = 10 id = 3084 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C695
	tier = county
	liege = MMOS
	holder = { character = { type = 10 id = 20727 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C696
	tier = county
	liege = MMOS
	holder = { character = { type = 10 id = 3822 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C697
	tier = county
	liege = MMOS
	holder = { character = { type = 10 id = 3822 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C698
	tier = county
	liege = MMOS
	holder = { character = { type = 10 id = 20732 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C699
	tier = county
	liege = MEDE
	holder = { character = { type = 10 id = 20738 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C700
	tier = county
	liege = MEDE
	holder = { character = { type = 10 id = 20738 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C701
	tier = county
	liege = DMES
	holder = { character = { type = 10 id = 7241 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94003 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C702
	tier = county
	liege = DMES
	holder = { character = { type = 10 id = 85001 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94004 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C703
	tier = county
	liege = DMES
	holder = { character = { type = 10 id = 85010 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94005 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C704
	tier = county
	liege = TRAP
	holder = { character = { type = 10 id = 7242 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94007 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C705
	tier = county
	liege = CHAL
	holder = { character = { type = 10 id = 20552 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94008 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C706
	tier = county
	liege = CHAL
	holder = { character = { type = 10 id = 20553 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94009 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C707
	tier = county
	liege = ARMI
	holder = { character = { type = 10 id = 20562 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94018 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C708
	tier = county
	liege = MEDE
	holder = { character = { type = 10 id = 20740 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C709
	tier = county
	liege = MEDE
	holder = { character = { type = 10 id = 20739 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C710
	tier = county
	liege = MMOS
	holder = { character = { type = 10 id = 20731 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C711
	tier = county
	liege = MMOS
	holder = { character = { type = 10 id = 20729 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C712
	tier = county
	liege = MMOS
	holder = { character = { type = 10 id = 20728 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C713
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 20761 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90037 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C714
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 20675 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C715
	tier = county
	liege = SELJ
	holder = { character = { type = 10 id = 20674 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C716
	tier = county
	liege = MMED
	holder = { character = { type = 10 id = 20796 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C717
	tier = county
	liege = MMED
	holder = { character = { type = 10 id = 20795 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C718
	tier = county
	liege = MMED
	holder = { character = { type = 10 id = 3826 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C719
	tier = county
	liege = MMED
	holder = { character = { type = 10 id = 3826 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C720
	tier = county
	liege = MMED
	holder = { character = { type = 10 id = 20793 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C721
	tier = county
	liege = MMED
	holder = { character = { type = 10 id = 20794 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C722
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 20762 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C723
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 20763 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C724
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 20764 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C725
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 20765 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90034 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C726
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 20766 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90038 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C727
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 20767 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90039 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C728
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 20768 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90035 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C729
	tier = county
	liege = MMOS
	holder = { character = { type = 10 id = 20730 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90042 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C730
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 20768 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90036 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C731
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 20746 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90040 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C732
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 20745 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90041 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C733
	tier = county
	liege = MALE
	holder = { character = { type = 10 id = 20743 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C734
	tier = county
	liege = MALE
	holder = { character = { type = 10 id = 20741 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C735
	tier = county
	liege = ANTI
	holder = { character = { type = 10 id = 20559 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94015 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C736
	tier = county
	liege = ARMI
	holder = { character = { type = 10 id = 20554 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94010 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C737
	tier = county
	liege = GALA
	holder = { character = { type = 10 id = 41578 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94021 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C738
	tier = county
	liege = SINO
	holder = { character = { type = 10 id = 1756 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94019 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C739
	tier = county
	liege = SINO
	holder = { character = { type = 10 id = 1752 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94020 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C740
	tier = county
	liege = NIKO
	holder = { character = { type = 10 id = 20537 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94023 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C741
	tier = county
	liege = BYZA
	holder = { character = { type = 10 id = 1746 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94030 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C742
	tier = county
	liege = NIKA
	holder = { character = { type = 10 id = 20527 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94032 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C743
	tier = county
	liege = NIKA
	holder = { character = { type = 10 id = 20528 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94031 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C744
	tier = county
	liege = ADRI
	holder = { character = { type = 10 id = 20524 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94035 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C745
	tier = county
	liege = SAMS
	holder = { character = { type = 10 id = 20511 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94036 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C746
	tier = county
	liege = SAMS
	holder = { character = { type = 10 id = 20511 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94037 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C747
	tier = county
	liege = LYKI
	holder = { character = { type = 10 id = 20518 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94039 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C748
	tier = county
	liege = LAOD
	holder = { character = { type = 10 id = 20525 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94034 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C749
	tier = county
	liege = IKON
	holder = { character = { type = 10 id = 20532 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94027 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C750
	tier = county
	liege = NIKA
	holder = { character = { type = 10 id = 20530 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94029 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C751
	tier = county
	liege = NIKO
	holder = { character = { type = 10 id = 1742 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94022 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C752
	tier = county
	liege = GALA
	holder = { character = { type = 10 id = 20536 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94024 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C753
	tier = county
	liege = NIKO
	holder = { character = { type = 10 id = 1742 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94026 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C754
	tier = county
	liege = LAOD
	holder = { character = { type = 10 id = 20526 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94033 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C755
	tier = county
	liege = IKON
	holder = { character = { type = 10 id = 20520 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94038 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C756
	tier = county
	liege = CYPR
	holder = { character = { type = 10 id = 20564 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C757
	tier = county
	liege = CYPR
	holder = { character = { type = 10 id = 20563 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C758
	tier = county
	liege = BYZA
	holder = { character = { type = 10 id = 41589 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94011 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C759
	tier = county
	liege = IKON
	holder = { character = { type = 10 id = 1734 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94028 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C760
	tier = county
	liege = IKON
	holder = { character = { type = 10 id = 20534 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94025 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C761
	tier = county
	liege = ARMI
	holder = { character = { type = 10 id = 41568 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94012 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C762
	tier = county
	liege = ARMI
	holder = { character = { type = 10 id = 20554 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94013 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C763
	tier = county
	liege = ANTI
	holder = { character = { type = 10 id = 1758 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94014 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C764
	tier = county
	liege = ANTI
	holder = { character = { type = 10 id = 1758 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94016 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C765
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 20747 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90032 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C766
	tier = county
	liege = ANTI
	holder = { character = { type = 10 id = 20561 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94017 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C767
	tier = county
	liege = MTRI
	holder = { character = { type = 10 id = 20769 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90033 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C768
	tier = county
	liege = MTRI
	holder = { character = { type = 10 id = 20770 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90026 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C769
	tier = county
	liege = MTRI
	holder = { character = { type = 10 id = 20771 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90027 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C770
	tier = county
	liege = MTRI
	holder = { character = { type = 10 id = 20772 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90028 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C771
	tier = county
	liege = MTRI
	holder = { character = { type = 10 id = 20773 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90029 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C772
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 20774 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90030 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C773
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 20775 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90031 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C774
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 20776 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C775
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 20777 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C776
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 20778 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C777
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 20779 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C778
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 20780 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C779
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 20781 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C780
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 20782 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C781
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 20783 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C782
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 20784 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C783
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 20785 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C784
	tier = county
	liege = MELA
	holder = { character = { type = 10 id = 20786 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C785
	tier = county
	liege = MELA
	holder = { character = { type = 10 id = 20787 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C786
	tier = county
	liege = MELA
	holder = { character = { type = 10 id = 20788 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C787
	tier = county
	liege = MELA
	holder = { character = { type = 10 id = 20789 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C788
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 20790 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C789
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 3096 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C790
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 3096 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C791
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 3096 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C792
	tier = county
	liege = NUBI
	holder = { character = { type = 10 id = 20572 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C793
	tier = county
	liege = NUBI
	holder = { character = { type = 10 id = 20572 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C794
	tier = county
	liege = NUBI
	holder = { character = { type = 10 id = 20572 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C795
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 3096 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C796
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 3096 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C797
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 3096 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C798
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 3096 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C799
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 3096 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C800
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 3096 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C801
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 3096 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C802
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 3096 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C803
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 20800 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C804
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 20799 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C805
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 20801 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C806
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 20802 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C807
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 20803 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C808
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 20798 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C809
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 20804 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C810
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 20806 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C811
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20805 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C812
	tier = county
	liege = ZIRI
	holder = { character = { type = 10 id = 20828 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C813
	tier = county
	liege = BENI
	holder = { character = { type = 10 id = 20807 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C814
	tier = county
	liege = BENI
	holder = { character = { type = 10 id = 20808 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C815
	tier = county
	liege = BENI
	holder = { character = { type = 10 id = 20809 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C816
	tier = county
	liege = ZIRI
	holder = { character = { type = 10 id = 20825 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C817
	tier = county
	liege = ZIRI
	holder = { character = { type = 10 id = 20825 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C818
	tier = county
	liege = ZIRI
	holder = { character = { type = 10 id = 20811 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C819
	tier = county
	liege = ZIRI
	holder = { character = { type = 10 id = 20825 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C820
	tier = county
	liege = ZIRI
	holder = { character = { type = 10 id = 20816 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C821
	tier = county
	liege = ZIRI
	holder = { character = { type = 10 id = 20815 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C822
	tier = county
	liege = HAMM
	holder = { character = { type = 10 id = 20834 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C823
	tier = county
	liege = HAMM
	holder = { character = { type = 10 id = 20814 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C824
	tier = county
	liege = HAMM
	holder = { character = { type = 10 id = 20834 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C825
	tier = county
	liege = HAMM
	holder = { character = { type = 10 id = 20834 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C826
	tier = county
	liege = BALE
	holder = { character = { type = 10 id = 20871 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C827
	tier = county
	liege = BALE
	holder = { character = { type = 10 id = 20870 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C828
	tier = county
	liege = HAMM
	holder = { character = { type = 10 id = 20838 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C829
	tier = county
	liege = HAMM
	holder = { character = { type = 10 id = 20837 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C830
	tier = county
	liege = HAMM
	holder = { character = { type = 10 id = 20836 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C831
	tier = county
	liege = HAMM
	holder = { character = { type = 10 id = 20834 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C832
	tier = county
	liege = HAMM
	holder = { character = { type = 10 id = 20840 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C833
	tier = county
	liege = HAMM
	holder = { character = { type = 10 id = 20819 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C834
	tier = county
	liege = ZENA
	holder = { character = { type = 10 id = 20822 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C835
	tier = county
	liege = ZENA
	holder = { character = { type = 10 id = 20820 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C836
	tier = county
	liege = ZENA
	holder = { character = { type = 10 id = 20821 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C837
	tier = county
	liege = ZENA
	holder = { character = { type = 10 id = 20818 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C838
	tier = county
	liege = ZENA
	holder = { character = { type = 10 id = 20823 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C839
	tier = county
	liege = TANG
	holder = { character = { type = 10 id = 20881 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90013 } character = { type = 10 id = 3853 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92017 } character = { type = 10 id = 3210 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C840
	tier = county
	liege = FESA
	holder = { character = { type = 10 id = 20850 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C841
	tier = county
	liege = TANG
	holder = { character = { type = 10 id = 20881 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90014 } character = { type = 10 id = 3853 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = C842
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20849 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C843
	tier = county
	liege = MURA
	holder = { character = { type = 10 id = 3853 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C844
	tier = county
	liege = MURA
	holder = { character = { type = 10 id = 3852 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C845
	tier = county
	liege = MURA
	holder = { character = { type = 10 id = 3853 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C846
	tier = county
	liege = MURA
	holder = { character = { type = 10 id = 3853 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C847
	tier = county
	liege = MURA
	holder = { character = { type = 10 id = 3853 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C848
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20842 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C898
	tier = county
	liege = PAPA
	holder = { character = { type = 10 id = 20330 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C995
	tier = county
	liege = SAXO
	holder = { character = { type = 10 id = 20251 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = C997
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 1152 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92008 } character = { type = 10 id = 1128 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = ADRI
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 1736 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = AEGE
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20513 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ALAN
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20662 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ALME
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20876 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ANJO
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 378 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ANTI
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20559 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = APUL
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 1128 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92001 } character = { type = 10 id = 1134 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = ARMA
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 240 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ARME
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 41585 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ARMI
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20554 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = AZER
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20722 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = AZOV
	tier = duchy
	liege = CUMA
	holder = { character = { type = 10 id = 20655 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = BADA
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 3900 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 93003 } character = { type = 10 id = 3212 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 93013 } character = { type = 10 id = 20852 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = BAVA
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 112600 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = BELG
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20491 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = BJAR
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20620 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = DBOH
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 522 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = BORD
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 240 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = BOUG
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 210 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = BRAG
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 109500 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 91006 } character = { type = 10 id = 107500 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 91007 } character = { type = 10 id = 108500 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = BRAN
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 7032 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = BRIT
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 347 } startdate = { year = 1066 month = january day = 0 } } #BRIT
}
title = {
	tag = BUTR
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 1764 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = CALA
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 1128 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = CAMP
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20498 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = CATA
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 110520 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = CHAL
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20552 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = CHAM
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 394 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = CHER
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20463 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = CONN
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 910 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = CORD
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20852 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 93008 } character = { type = 10 id = 3900 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 93009 } character = { type = 10 id = 3210 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 93010 } character = { type = 10 id = 3924 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = CUMB
	tier = duchy
	liege = ENGL
	holder = { character = { type = 10 id = 5660 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92022 } character = { type = 10 id = 125 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92023 } character = { type = 10 id = 126 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 95500 } character = { type = 10 id = 198 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = CYPR
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20563 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = CYRE
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20798 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = DEHE
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 81814 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 86128 } character = { type = 10 id = 81841 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 86129 } character = { type = 10 id = 6358 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 95023 } character = { type = 10 id = 81031 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = DONA
	tier = duchy
	liege = CUMA
	holder = { character = { type = 10 id = 20653 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = DORO
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 1740 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = DYRR
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20499 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ESFA
	tier = duchy
	liege = SELJ
	holder = { character = { type = 10 id = 20705 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = FESA
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20850 } startdate = { year = 1066 month = january day = 0 } }
}
title = { 
	tag = FINL 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 20612 } startdate = { year = 1066 month = january day = 0 } } 
} 
title = {
	tag = FLAN
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 364 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = FRAC
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 1316 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = GALA
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20536 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = GALI
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 626 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = GALC
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 109500 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 91004 } character = { type = 10 id = 107500 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 91005 } character = { type = 10 id = 108500 } date = { year = 1066 month = december day = 25 } } 
}
title = {
	tag = GENO
	tier = duchy
	liege = ITAL
	holder = { character = { type = 10 id = 20314 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = DGEO
	tier = duchy
	liege = GEOR
	holder = { character = { type = 10 id = 85012 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = GWYN
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 6358 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 86123 } character = { type = 10 id = 81841 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 95001 } character = { type = 10 id = 81031 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = HAIN
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 106520 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = HELL
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20507 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = HORM
	tier = duchy
	liege = SELJ
	holder = { character = { type = 10 id = 3041 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ICEL
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20579 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = IKON
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 1734 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = KARE
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28004 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = KIEV
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 626 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92029 } character = { type = 10 id = 628 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92030 } character = { type = 10 id = 630 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92031 } character = { type = 10 id = 650 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = KRET
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20516 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = KARN
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 1610 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = LANC
	tier = duchy
	liege = ENGL
	holder = { character = { type = 10 id = 5644 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = LANG
	tier = duchy
	liege = ITAL
	holder = { character = { type = 10 id = 20323 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = LAOD
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20525 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = LEIN
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 922 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = LIVO
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28023 } startdate = { year = 1066 month = january day = 0 } }
}

title = {
	tag = LOTH
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 85018 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 91404 } character = { type = 10 id = 984 } date = { year = 1066 month = december day = 25 } }
}

title = { 
	tag = LOLO 
	tier = duchy 
	liege = GERM 
	holder = { character = { type = 10 id = 11030 } startdate = { year = 1066 month = january day = 0 } } 
} 
title = {
	tag = LURI
	tier = duchy
	liege = SELJ
	holder = { character = { type = 10 id = 20691 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = LUTA
	tier = duchy
	liege = SELJ
	holder = { character = { type = 10 id = 20688 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = LUXE
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 106650 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = LYKI
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20518 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MARA
	tier = duchy
	liege = SCOT
	holder = { character = { type = 10 id = 6008 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MAZO
	tier = duchy
	liege = POLA
	holder = { character = { type = 10 id = 764 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MECK
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20584 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90346 } character = { type = 10 id = 8400 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 90347 } character = { type = 10 id = 8402 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = MEIS
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 7060 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = DMES
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 85001 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MILA
	tier = duchy
	liege = ITAL
	holder = { character = { type = 10 id = 1118 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MUNS
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 906 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = NIKA
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20527 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = NIKO
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 1742 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = NORM
	tier = duchy
	liege = ENGL
	holder = { character = { type = 10 id = 140 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = NOVG
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 686 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92032 } character = { type = 10 id = 628 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92033 } character = { type = 10 id = 650 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = ORKN
	tier = duchy
	liege = NORW
	holder = { character = { type = 10 id = 102538 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ACHA
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 1766 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = PERE
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 630 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = POIT
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 240 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = POLO
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 650 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92034 } character = { type = 10 id = 626 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = POMM
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20623 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = PRES
	tier = duchy
	liege = HUNG
	holder = { character = { type = 10 id = 4431 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = PROV
	tier = duchy
	liege = BURG
	holder = { character = { type = 10 id = 420 } startdate = { year = 1066 month = january day = 0 } }
}

title = {
	tag = ROMA
	tier = duchy
	liege = ITAL
	holder = { character = { type = 10 id = 7740 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ROST
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 630 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = RYAZ
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 628 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = SAND
	tier = duchy
	liege = POLA
	holder = { character = { type = 10 id = 20388 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = SAXO
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 1416 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = SEVI
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 3212 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 93002 } character = { type = 10 id = 3900 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 93005 } character = { type = 10 id = 3210 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 93007 } character = { type = 10 id = 3924 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = SILE
	tier = duchy
	liege = POLA
	holder = { character = { type = 10 id = 762 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = SINO
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 1752 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = SLOV
	tier = duchy
	liege = HUNG
	holder = { character = { type = 10 id = 472 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = SMOL
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 630 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92024 } character = { type = 10 id = 668 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92025 } character = { type = 10 id = 626 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92026 } character = { type = 10 id = 628 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92027 } character = { type = 10 id = 650 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92028 } character = { type = 10 id = 9134 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = SPOL
	tier = duchy
	liege = ITAL
	holder = { character = { type = 10 id = 7757 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = SUZD
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 628 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92035 } character = { type = 10 id = 630 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = SWAB
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 1388 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = TANG
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20881 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = THES
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 1732 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = THUR
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 20234 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = TOSC
	tier = duchy
	liege = ITAL
	holder = { character = { type = 10 id = 7757 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = TOUL
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 336 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = TRAP
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20544 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = TRON
	tier = duchy
	liege = NORW
	holder = { character = { type = 10 id = 102532 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = TURO
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 626 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = UPLO
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 6642 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 94040 } character = { type = 10 id = 11000 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92021 } character = { type = 10 id = 11030 } date = { year = 1066 month = january day = 0 } }
}
title = {
	tag = UPPL
	tier = duchy
	liege = SWED
	holder = { character = { type = 10 id = 100516 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = URAL
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 3504 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = VALE
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 3928 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 93000 } character = { type = 10 id = 20869 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = VARN
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 85011 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = VERO
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 1610 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = WEIS
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 5788 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 91409 } character = { type = 10 id = 102534 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = VIDI
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20489 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = WIEL
	tier = duchy
	liege = POLA
	holder = { character = { type = 10 id = 20393 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = VOLG
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20923 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = VAST
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 100525 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = YORK
	tier = duchy
	liege = ENGL
	holder = { character = { type = 10 id = 140 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90344 } character = { type = 10 id = 101515 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = ZARB
	tier = duchy
	liege = CROA
	holder = { character = { type = 10 id = 8622 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92037 } character = { type = 10 id = 7800 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = OSTE
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 7200 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = UGRI
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 3934 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 93001 } character = { type = 10 id = 20883 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = DERB
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20734 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = TURK
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 3072 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MURC
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 3910 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = SAMS
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 20511 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = SLAV
	tier = duchy
	liege = CROA
	holder = { character = { type = 10 id = 8628 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92040 } character = { type = 10 id = 476 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = SVIG
	tier = duchy
	liege = DENM
	holder = { character = { type = 10 id = 101517 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = TOLE
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 3924 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 93006 } character = { type = 10 id = 3212 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 93011 } character = { type = 10 id = 20852 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = OSTR
	tier = duchy
	liege = SWED
	holder = { character = { type = 10 id = 100530 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ARAG
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 110500 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92020 } character = { type = 10 id = 106000 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = BURG
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 1316 } startdate = { year = 1054 month = january day = 0 } }
}
title = {
	tag = BYZA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 1732 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = CAST
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 107500 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 91001 } character = { type = 10 id = 109500 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92018 } character = { type = 10 id = 108500 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = CROA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 8622 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92036 } character = { type = 10 id = 8628 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = CUMA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 806 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = DENM
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 101515 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ENGL
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 140 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92012 } character = { type = 10 id = 112 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92013 } character = { type = 10 id = 41002 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 92014 } character = { type = 10 id = 41003 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 90342 } character = { type = 10 id = 101515 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = FRAN
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 214 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = GEOR
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 9952 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = GERM
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 1316 } startdate = { year = 1054 month = january day = 0 } }
}
title = {
	tag = HUNG
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 476 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90001 } character = { type = 10 id = 472 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = ITAL
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 1316 } startdate = { year = 1054 month = january day = 0 } }
}
title = {
	tag = LEON
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 108500 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90403 } character = { type = 10 id = 107500 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 91002 } character = { type = 10 id = 109500 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 94041 } character = { type = 10 id = 107640 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = NAVA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 106000 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 92019 } character = { type = 10 id = 110500 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = NORW
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 102534 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = POLA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 762 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = SCOT
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 984 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90404 } character = { type = 10 id = 6008 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = SWED
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 100525 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90000 } character = { type = 10 id = 100516 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = PECH
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20635 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 95005 } character = { type = 10 id = 806 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = MJER
	tier = duchy
	liege = FATI
	holder = { character = { type = 10 id = 20776 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MAMM
	tier = duchy
	liege = FATI
	holder = { character = { type = 10 id = 20764 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MTRI
	tier = duchy
	liege = FATI
	holder = { character = { type = 10 id = 20769 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MDAM
	tier = duchy
	liege = FATI
	holder = { character = { type = 10 id = 20768 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MELA
	tier = duchy
	liege = FATI
	holder = { character = { type = 10 id = 20789 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MMOS
	tier = duchy
	liege = SELJ
	holder = { character = { type = 10 id = 3822 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MEDE
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20738 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90024 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = MMED
	tier = duchy
	liege = FATI
	holder = { character = { type = 10 id = 3826 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MKHW
	tier = duchy
	liege = SELJ
	holder = { character = { type = 10 id = 20713 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MALE
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20743 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90025 } character = { type = 10 id = 3040 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = MSIS
	tier = duchy
	liege = SELJ
	holder = { character = { type = 10 id = 20707 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MARB
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20900 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MMAZ
	tier = duchy
	liege = SELJ
	holder = { character = { type = 10 id = 20703 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = PAPA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 2008 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = VENI
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 7800 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ABBA
	tier = duchy
	liege = SELJ
	holder = { character = { type = 10 id = 3084 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = QARA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 3014 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = HAMM
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 20834 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ZIRI
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 20825 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = BALE
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20869 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 95006 } character = { type = 10 id = 3934 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = ZENA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 20818 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = BENI
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 20809 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = CURO
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28075 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ESTS
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28026 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = GRAN
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 3210 } startdate = { year = 1066 month = january day = 0 } }
	claim = { id = { type = 14712 id = 93004 } character = { type = 10 id = 3212 } date = { year = 1066 month = december day = 25 } }
	claim = { id = { type = 14712 id = 93012 } character = { type = 10 id = 20852 } date = { year = 1066 month = december day = 25 } }
}
title = {
	tag = LETT
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28020 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = PRUT
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28015 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = SAME
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20619 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = YATV
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28017 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = ESAM
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20618 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = INGE
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28007 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = KAJA
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28010 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = KEXH
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28035 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = KHAZ
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20663 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = KOLA
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28009 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = LITT
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28012 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MORD
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20628 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = SATA
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28011 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = TAVA
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28003 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = VOTE
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28006 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = WSAM
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 20617 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MINS 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 90149 } startdate = { year = 1066 month = january day = 0 } } 
} 
title = {
	tag = NUBI
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 20572 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = MURA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 3853 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = FATI
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 3096 } startdate = { year = 1066 month = january day = 0 } }
}
title = {
	tag = SELJ
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 3040 } startdate = { year = 1066 month = january day = 0 } }
}