relations = {
	alliance = {
		primary = { type = 10 id = 626 }
		secondary = { type = 10 id = 686 }
		startdate = { year = 1066 month = december day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 9952 }
		secondary = { type = 10 id = 20662 }
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 20852 }
		secondary = { type = 10 id = 20818 }
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 140 } #ENGL
		secondary = { type = 10 id = 347 } #BRIT
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 3096 }
		secondary = { type = 10 id = 20798 }
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 3212 }
		secondary = { type = 10 id = 20852 }
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 5644 }
		secondary = { type = 10 id = 5660 }
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 5644 }
		secondary = { type = 10 id = 6358 }
		startdate = { year = 1065 month = january day = 2 }
	}
	alliance = {
		primary = { type = 10 id = 5644 }
		secondary = { type = 10 id = 90027 }
		startdate = { year = 1065 month = january day = 3 }
	}
	alliance = {
		primary = { type = 10 id = 5660 }
		secondary = { type = 10 id = 6358 }
		startdate = { year = 1065 month = january day = 4 }
	}
	alliance = {
		primary = { type = 10 id = 5660 }
		secondary = { type = 10 id = 90027 }
		startdate = { year = 1065 month = january day = 5 }
	}
	alliance = {
		primary = { type = 10 id = 6358 }
		secondary = { type = 10 id = 90027 }
		startdate = { year = 1065 month = january day = 6 }
	}
	alliance = {
		primary = { type = 10 id = 28015 }
		secondary = { type = 10 id = 28019 }
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 28017 }
		secondary = { type = 10 id = 28012 }
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 28020 }
		secondary = { type = 10 id = 20603 }
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 106000 }
		secondary = { type = 10 id = 110500 }
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 3210 }
		secondary = { type = 10 id = 3910 }
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 3210 }
		secondary = { type = 10 id = 20876 }
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 3910 }
		secondary = { type = 10 id = 20876 }
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 3212 }
		secondary = { type = 10 id = 20881 }
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 628 } 
		secondary = { type = 10 id = 626 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 628 } 
		secondary = { type = 10 id = 630 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 626 } 
		secondary = { type = 10 id = 630 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	alliance = {
		primary = { type = 10 id = 109500 } 
		secondary = { type = 10 id = 108500 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	alliance = { #Bakt
		primary = { type = 10 id = 20572 } 
		secondary = { type = 10 id = 3096 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106 }
		secondary = { type = 10 id = 105 }
		startdate = { year = 985 month = january day = 1 }
		enddate = { year = 1002 month = august day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 108 }
		secondary = { type = 10 id = 107 }
		startdate = { year = 1015 month = january day = 1 }
		enddate = { year = 1016 month = august day = 9 }
	}
	marrige = {
		primary = { type = 10 id = 114 }
		secondary = { type = 10 id = 121 }
		startdate = { year = 1045 month = january day = 1 }
		enddate = { year = 1066 month = january day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 120 }
		secondary = { type = 10 id = 101534 }
		startdate = { year = 1019 month = january day = 1 }
		enddate = { year = 1053 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 122 }
		secondary = { type = 10 id = 123 }
		startdate = { year = 1054 month = january day = 1 }
		enddate = { year = 1066 month = october day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 124 }
		secondary = { type = 10 id = 363 }
		startdate = { year = 1051 month = january day = 1 }
		enddate = { year = 1066 month = september day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 140 }
		secondary = { type = 10 id = 367 }
		startdate = { year = 1053 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 150 }
		secondary = { type = 10 id = 149 }
		startdate = { year = 1056 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 152 }
		secondary = { type = 10 id = 449 }
		startdate = { year = 1048 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 178 }
		secondary = { type = 10 id = 347 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 196 }
		secondary = { type = 10 id = 193 }
		startdate = { year = 1046 month = january day = 1 }
		enddate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 200 }
		secondary = { type = 10 id = 233 }
		startdate = { year = 963 month = january day = 1 }
		enddate = { year = 996 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 206 }
		secondary = { type = 10 id = 333 }
		startdate = { year = 1002 month = january day = 1 }
		enddate = { year = 1031 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 208 }
		secondary = { type = 10 id = 627 }
		startdate = { year = 1051 month = january day = 1 }
		enddate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 210 }
		secondary = { type = 10 id = 209 }
		startdate = { year = 1033 month = january day = 1 }
		enddate = { year = 1046 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 210 }
		secondary = { type = 10 id = 375 }
		startdate = { year = 1048 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 218 }
		secondary = { type = 10 id = 110531 }
		startdate = { year = 1055 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 230 }
		secondary = { type = 10 id = 243 }
		startdate = { year = 935 month = january day = 1 }
		enddate = { year = 962 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 232 }
		secondary = { type = 10 id = 385 }
		startdate = { year = 968 month = january day = 1 }
		enddate = { year = 993 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 234 }
		secondary = { type = 10 id = 275 }
		startdate = { year = 1019 month = january day = 1 }
		enddate = { year = 1030 month = january day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 238 }
		secondary = { type = 10 id = 6639 }
		startdate = { year = 1042 month = january day = 1 }
		enddate = { year = 1058 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 240 }
		secondary = { type = 10 id = 327 }
		startdate = { year = 1059 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 242 }
		secondary = { type = 10 id = 241 }
		startdate = { year = 886 month = january day = 1 }
		enddate = { year = 932 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 246 }
		secondary = { type = 10 id = 6801 }
		startdate = { year = 965 month = january day = 1 }
		enddate = { year = 996 month = november day = 20 }
	}
	marrige = {
		primary = { type = 10 id = 248 }
		secondary = { type = 10 id = 343 }
		startdate = { year = 1000 month = january day = 1 }
		enddate = { year = 1017 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 250 }
		secondary = { type = 10 id = 213 }
		startdate = { year = 1027 month = march day = 1 }
		enddate = { year = 1027 month = august day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 259 }
		secondary = { type = 10 id = 106 }
		startdate = { year = 1002 month = january day = 1 }
		enddate = { year = 1016 month = april day = 23 }
	}
	marrige = {
		primary = { type = 10 id = 272 }
		secondary = { type = 10 id = 271 }
		startdate = { year = 974 month = january day = 1 }
		enddate = { year = 1015 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 274 }
		secondary = { type = 10 id = 281 }
		startdate = { year = 991 month = january day = 1 }
		enddate = { year = 1004 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 276 }
		secondary = { type = 10 id = 251 }
		startdate = { year = 1017 month = january day = 1 }
		enddate = { year = 1038 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 280 }
		secondary = { type = 10 id = 289 }
		startdate = { year = 1047 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 282 }
		secondary = { type = 10 id = 283 }
		startdate = { year = 1026 month = january day = 1 }
		enddate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 284 }
		secondary = { type = 10 id = 285 }
		startdate = { year = 1054 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 316 }
		secondary = { type = 10 id = 255 }
		startdate = { year = 1053 month = january day = 1 }
		enddate = { year = 1054 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 320 }
		secondary = { type = 10 id = 321 }
		startdate = { year = 982 month = march day = 11 }
		enddate = { year = 997 month = april day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 322 }
		secondary = { type = 10 id = 323 }
		startdate = { year = 1008 month = january day = 1 }
		enddate = { year = 1047 month = july day = 10 }
	}
	marrige = {
		primary = { type = 10 id = 332 }
		secondary = { type = 10 id = 371 }
		startdate = { year = 975 month = january day = 1 }
		enddate = { year = 988 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 332 }
		secondary = { type = 10 id = 401 }
		startdate = { year = 990 month = january day = 1 }
		enddate = { year = 994 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 334 }
		secondary = { type = 10 id = 325 }
		startdate = { year = 1039 month = january day = 1 }
		enddate = { year = 1046 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 340 }
		secondary = { type = 10 id = 379 }
		startdate = { year = 974 month = january day = 1 }
		enddate = { year = 992 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 342 }
		secondary = { type = 10 id = 257 }
		startdate = { year = 996 month = january day = 1 }
		enddate = { year = 1008 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 344 }
		secondary = { type = 10 id = 393 }
		startdate = { year = 1032 month = january day = 1 }
		enddate = { year = 1040 month = january day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 360 }
		secondary = { type = 10 id = 1411 }
		startdate = { year = 961 month = january day = 1 }
		enddate = { year = 962 month = november day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 361 }
		secondary = { type = 10 id = 1111 }
		startdate = { year = 968 month = january day = 1 }
		enddate = { year = 988 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 362 }
		secondary = { type = 10 id = 40710 }
		startdate = { year = 1012 month = january day = 1 }
		enddate = { year = 1030 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 362 }
		secondary = { type = 10 id = 253 }
		startdate = { year = 1030 month = january day = 1 }
		enddate = { year = 1048 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 364 }
		secondary = { type = 10 id = 213 }
		startdate = { year = 1028 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 372 }
		secondary = { type = 10 id = 413 }
		startdate = { year = 970 month = january day = 1 }
		enddate = { year = 974 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 376 }
		secondary = { type = 10 id = 275 }
		startdate = { year = 1032 month = january day = 1 }
		enddate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 377 }
		secondary = { type = 10 id = 375 }
		startdate = { year = 1038 month = january day = 1 }
		enddate = { year = 1046 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 380 }
		secondary = { type = 10 id = 6569 }
		startdate = { year = 1063 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 382 }
		secondary = { type = 10 id = 411 }
		startdate = { year = 948 month = january day = 1 }
		enddate = { year = 968 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 384 }
		secondary = { type = 10 id = 1147 }
		startdate = { year = 983 month = january day = 1 }
		enddate = { year = 996 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 390 }
		secondary = { type = 10 id = 40129 }
		startdate = { year = 1010 month = january day = 1 }
		enddate = { year = 1037 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 391 }
		secondary = { type = 10 id = 255 }
		startdate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 394 }
		secondary = { type = 10 id = 1359 }
		startdate = { year = 1040 month = january day = 1 }
		enddate = { year = 1047 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1118 }
		secondary = { type = 10 id = 1359 }
		startdate = { year = 1056 month = january day = 1 }
		enddate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 402 }
		secondary = { type = 10 id = 373 }
		startdate = { year = 978 month = january day = 1 }
		enddate = { year = 1018 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 404 }
		secondary = { type = 10 id = 273 }
		startdate = { year = 1002 month = january day = 1 }
		enddate = { year = 1030 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 406 }
		secondary = { type = 10 id = 335 }
		startdate = { year = 1030 month = january day = 1 }
		enddate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 408 }
		secondary = { type = 10 id = 405 }
		startdate = { year = 1053 month = january day = 1 }
		enddate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 410 }
		secondary = { type = 10 id = 403 }
		startdate = { year = 1056 month = january day = 1 }
		enddate = { year = 1063 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 412 }
		secondary = { type = 10 id = 423 }
		startdate = { year = 947 month = january day = 1 }
		enddate = { year = 985 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 414 }
		secondary = { type = 10 id = 415 }
		startdate = { year = 998 month = january day = 1 }
		enddate = { year = 1000 month = march day = 17 }
	}
	marrige = {
		primary = { type = 10 id = 420 }
		secondary = { type = 10 id = 421 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 432 }
		secondary = { type = 10 id = 431 }
		startdate = { year = 1018 month = january day = 1 }
		enddate = { year = 1044 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 434 }
		secondary = { type = 10 id = 255 }
		startdate = { year = 1048 month = january day = 1 }
		enddate = { year = 1053 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 462 }
		secondary = { type = 10 id = 759 }
		startdate = { year = 968 month = january day = 1 }
		enddate = { year = 978 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 492 }
		secondary = { type = 10 id = 730 }
		startdate = { year = 1003 month = january day = 1 }
		enddate = { year = 1008 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 460 }
		secondary = { type = 10 id = 483 }
		startdate = { year = 974 month = january day = 1 }
		enddate = { year = 972 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 496 }
		secondary = { type = 10 id = 495 }
		startdate = { year = 1009 month = january day = 1 }
		enddate = { year = 1026 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10093 }
		secondary = { type = 10 id = 498 }
		startdate = { year = 1041 month = january day = 1 }
		enddate = { year = 1053 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 464 }
		secondary = { type = 10 id = 753 }
		startdate = { year = 968 month = january day = 1 }
		enddate = { year = 987 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 466 }
		secondary = { type = 10 id = 484 }
		startdate = { year = 985 month = january day = 1 }
		enddate = { year = 997 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 468 }
		secondary = { type = 10 id = 637 }
		startdate = { year = 1038 month = january day = 1 }
		enddate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20366 }
		secondary = { type = 10 id = 20375 }
		startdate = { year = 1037 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20373 }
		secondary = { type = 10 id = 4366 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20364 }
		secondary = { type = 10 id = 4384 }
		startdate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20372 }
		secondary = { type = 10 id = 4444 }
		startdate = { year = 1048 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20378 }
		secondary = { type = 10 id = 4363 }
		startdate = { year = 1056 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4438 }
		secondary = { type = 10 id = 4439 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20360 }
		secondary = { type = 10 id = 4389 }
		startdate = { year = 1038 month = january day = 1 }
		enddate = { year = 1063 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4371 }
		secondary = { type = 10 id = 4443 }
		startdate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20365 }
		secondary = { type = 10 id = 4365 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20363 }
		secondary = { type = 10 id = 491 }
		startdate = { year = 1033 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1621 }
		secondary = { type = 10 id = 4411 }
		startdate = { year = 1049 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4410 }
		secondary = { type = 10 id = 4415 }
		startdate = { year = 1057 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4401 }
		secondary = { type = 10 id = 4404 }
		startdate = { year = 1057 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4435 }
		secondary = { type = 10 id = 4436 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20356 }
		secondary = { type = 10 id = 4434 }
		startdate = { year = 1045 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 470 }
		secondary = { type = 10 id = 763 }
		startdate = { year = 1039 month = january day = 1 }
		enddate = { year = 1052 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20371 }
		secondary = { type = 10 id = 499 }
		startdate = { year = 1005 month = january day = 1 }
		enddate = { year = 1044 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 476 }
		secondary = { type = 10 id = 1476 }
		startdate = { year = 1063 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 482 }
		secondary = { type = 10 id = 1297 }
		startdate = { year = 996 month = january day = 1 }
		enddate = { year = 1038 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 500 }
		secondary = { type = 10 id = 501 }
		startdate = { year = 874 month = january day = 1 }
		enddate = { year = 895 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 504 }
		secondary = { type = 10 id = 505 }
		startdate = { year = 905 month = january day = 1 }
		enddate = { year = 921 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 508 }
		secondary = { type = 10 id = 507 }
		startdate = { year = 931 month = january day = 1 }
		enddate = { year = 965 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 510 }
		secondary = { type = 10 id = 511 }
		startdate = { year = 951 month = january day = 1 }
		enddate = { year = 976 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 516 }
		secondary = { type = 10 id = 517 }
		startdate = { year = 1001 month = january day = 1 }
		enddate = { year = 1034 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 518 }
		secondary = { type = 10 id = 1437 }
		startdate = { year = 1028 month = january day = 1 }
		enddate = { year = 1055 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 520 }
		secondary = { type = 10 id = 532 }
		startdate = { year = 1050 month = january day = 1 }
		enddate = { year = 1061 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 522 }
		secondary = { type = 10 id = 477 }
		startdate = { year = 1057 month = january day = 1 }
		enddate = { year = 1062 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 522 }
		secondary = { type = 10 id = 765 }
		startdate = { year = 1062 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 526 }
		secondary = { type = 10 id = 531 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 600 }
		secondary = { type = 10 id = 601 }
		startdate = { year = 920 month = january day = 1 }
		enddate = { year = 945 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 602 }
		secondary = { type = 10 id = 599 }
		startdate = { year = 945 month = january day = 1 }
		enddate = { year = 960 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 602 }
		secondary = { type = 10 id = 603 }
		startdate = { year = 945 month = january day = 1 }
		enddate = { year = 972 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 608 }
		secondary = { type = 10 id = 609 }
		startdate = { year = 977 month = january day = 1 }
		enddate = { year = 986 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 612 }
		secondary = { type = 10 id = 100511 }
		startdate = { year = 1005 month = january day = 1 }
		enddate = { year = 1018 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 618 }
		secondary = { type = 10 id = 122502 }
		startdate = { year = 1020 month = january day = 1 }
		enddate = { year = 1036 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 626 }
		secondary = { type = 10 id = 761 }
		startdate = { year = 1043 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 628 }
		secondary = { type = 10 id = 1353 }
		startdate = { year = 1054 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 630 }
		secondary = { type = 10 id = 1727 }
		startdate = { year = 1046 month = january day = 1 }
		enddate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 650 }
		secondary = { type = 10 id = 40603 }
		startdate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 686 }
		secondary = { type = 10 id = 40601 }
		startdate = { year = 1062 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 754 }
		secondary = { type = 10 id = 509 }
		startdate = { year = 965 month = january day = 1 }
		enddate = { year = 977 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 756 }
		secondary = { type = 10 id = 463 }
		startdate = { year = 987 month = january day = 1 }
		enddate = { year = 989 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 756 }
		secondary = { type = 10 id = 757 }
		startdate = { year = 987 month = january day = 2 }
		enddate = { year = 1017 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 758 }
		secondary = { type = 10 id = 427 }
		startdate = { year = 1013 month = january day = 1 }
		enddate = { year = 1034 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 760 }
		secondary = { type = 10 id = 13501 }
		startdate = { year = 1041 month = january day = 1 }
		enddate = { year = 1058 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 906 }
		secondary = { type = 10 id = 908 }
		startdate = { year = 1038 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 910 }
		secondary = { type = 10 id = 914 }
		startdate = { year = 1038 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 922 }
		secondary = { type = 10 id = 901 }
		startdate = { year = 1020 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 924 }
		secondary = { type = 10 id = 925 }
		startdate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 962 }
		secondary = { type = 10 id = 981 }
		startdate = { year = 997 month = january day = 1 }
		enddate = { year = 1035 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 964 }
		secondary = { type = 10 id = 189 }
		startdate = { year = 1025 month = january day = 1 }
		enddate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 85018 }
		secondary = { type = 10 id = 967 }
		startdate = { year = 1059 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 982 }
		secondary = { type = 10 id = 193 }
		startdate = { year = 1030 month = january day = 1 }
		enddate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 984 }
		secondary = { type = 10 id = 102505 }
		startdate = { year = 1050 month = january day = 1 }
		enddate = { year = 1058 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 984 }
		secondary = { type = 10 id = 113 }
		startdate = { year = 1059 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1010 }
		secondary = { type = 10 id = 1011 }
		startdate = { year = 1049 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1015 }
		secondary = { type = 10 id = 1016 }
		startdate = { year = 1059 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1020 }
		secondary = { type = 10 id = 1021 }
		startdate = { year = 1048 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1025 }
		secondary = { type = 10 id = 1026 }
		startdate = { year = 1000 month = january day = 1 }
		enddate = { year = 1042 month = november day = 17 }
	}
	marrige = {
		primary = { type = 10 id = 1027 }
		secondary = { type = 10 id = 1028 }
		startdate = { year = 1015 month = january day = 1 }
		enddate = { year = 1034 month = november day = 17 }
	}
	marrige = {
		primary = { type = 10 id = 81030 }
		secondary = { type = 10 id = 1029 }
		startdate = { year = 1053 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110520 }
		secondary = { type = 10 id = 325 }
		startdate = { year = 1052 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1118 }
		secondary = { type = 10 id = 1529 }
		startdate = { year = 1039 month = january day = 1 }
		enddate = { year = 1044 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1164 }
		secondary = { type = 10 id = 1701 }
		startdate = { year = 900 month = january day = 1 }
		enddate = { year = 928 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1176 }
		secondary = { type = 10 id = 1177 }
		startdate = { year = 999 month = january day = 1 }
		enddate = { year = 1048 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10085 }
		secondary = { type = 10 id = 1115 }
		startdate = { year = 1035 month = january day = 1 }
		enddate = { year = 1038 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1180 }
		secondary = { type = 10 id = 1115 }
		startdate = { year = 1038 month = january day = 1 }
		enddate = { year = 1054 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1182 }
		secondary = { type = 10 id = 239 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1183 }
		secondary = { type = 10 id = 1316 }
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1250 }
		secondary = { type = 10 id = 1251 }
		startdate = { year = 969 month = january day = 1 }
		enddate = { year = 998 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1280 }
		secondary = { type = 10 id = 1281 }
		startdate = { year = 909 month = january day = 1 }
		enddate = { year = 936 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1282 }
		secondary = { type = 10 id = 101 }
		startdate = { year = 929 month = january day = 1 }
		enddate = { year = 949 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1286 }
		secondary = { type = 10 id = 1773 }
		startdate = { year = 972 month = january day = 1 }
		enddate = { year = 983 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1294 }
		secondary = { type = 10 id = 1149 }
		startdate = { year = 970 month = january day = 1 }
		enddate = { year = 995 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1296 }
		secondary = { type = 10 id = 1255 }
		startdate = { year = 994 month = january day = 1 }
		enddate = { year = 1012 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1310 }
		secondary = { type = 10 id = 1331 }
		startdate = { year = 988 month = january day = 1 }
		enddate = { year = 989 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1350 }
		secondary = { type = 10 id = 1394 }
		startdate = { year = 1030 month = january day = 1 }
		enddate = { year = 1057 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10082 }
		secondary = { type = 10 id = 1385 }
		startdate = { year = 1001 month = january day = 1 }
		enddate = { year = 1003 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10083 }
		secondary = { type = 10 id = 1385 }
		startdate = { year = 1004 month = january day = 1 }
		enddate = { year = 1015 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1312 }
		secondary = { type = 10 id = 1385 }
		startdate = { year = 1016 month = january day = 1 }
		enddate = { year = 1039 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1314 }
		secondary = { type = 10 id = 237 }
		startdate = { year = 1043 month = january day = 1 }
		enddate = { year = 1056 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1332 }
		secondary = { type = 10 id = 1333 }
		startdate = { year = 987 month = january day = 1 }
		enddate = { year = 1046 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1334 }
		secondary = { type = 10 id = 2803 }
		startdate = { year = 1010 month = january day = 1 }
		enddate = { year = 1022 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1336 }
		secondary = { type = 10 id = 1349 }
		startdate = { year = 1017 month = january day = 1 }
		enddate = { year = 1026 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1340 }
		secondary = { type = 10 id = 1423 }
		startdate = { year = 1049 month = january day = 1 }
		enddate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1354 }
		secondary = { type = 10 id = 1355 }
		startdate = { year = 995 month = january day = 1 }
		enddate = { year = 1038 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1356 }
		secondary = { type = 10 id = 393 }
		startdate = { year = 1041 month = january day = 1 }
		enddate = { year = 1051 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1384 }
		secondary = { type = 10 id = 1149 }
		startdate = { year = 996 month = january day = 1 }
		enddate = { year = 1006 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1388 }
		secondary = { type = 10 id = 1181 }
		startdate = { year = 1057 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1388 }
		secondary = { type = 10 id = 1315 }
		startdate = { year = 1059 month = january day = 1 }
		enddate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1412 }
		secondary = { type = 10 id = 1421 }
		startdate = { year = 995 month = january day = 1 }
		enddate = { year = 1011 month = january day = 9 }
	}
	marrige = {
		primary = { type = 10 id = 1414 }
		secondary = { type = 10 id = 1435 }
		startdate = { year = 1020 month = january day = 1 }
		enddate = { year = 1055 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1416 }
		secondary = { type = 10 id = 102528 }
		startdate = { year = 1042 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1616 }
		secondary = { type = 10 id = 471 }
		startdate = { year = 1062 month = june day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 1526 }
		secondary = { type = 10 id = 1525 }
		startdate = { year = 997 month = january day = 1 }
		enddate = { year = 1000 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1528 }
		secondary = { type = 10 id = 1257 }
		startdate = { year = 1019 month = january day = 1 }
		enddate = { year = 1030 month = march day = 10 }
	}
	marrige = {
		primary = { type = 10 id = 1530 }
		secondary = { type = 10 id = 112602 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1700 }
		secondary = { type = 10 id = 1761 }
		startdate = { year = 870 month = january day = 1 }
		enddate = { year = 886 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1702 }
		secondary = { type = 10 id = 1703 }
		startdate = { year = 901 month = january day = 1 }
		enddate = { year = 906 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1708 }
		secondary = { type = 10 id = 1709 }
		startdate = { year = 919 month = january day = 1 }
		enddate = { year = 959 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1710 }
		secondary = { type = 10 id = 1711 }
		startdate = { year = 956 month = january day = 1 }
		enddate = { year = 963 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1712 }
		secondary = { type = 10 id = 1711 }
		startdate = { year = 964 month = january day = 1 }
		enddate = { year = 969 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1714 }
		secondary = { type = 10 id = 1715 }
		startdate = { year = 970 month = january day = 1 }
		enddate = { year = 976 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1720 }
		secondary = { type = 10 id = 1717 }
		startdate = { year = 1028 month = january day = 1 }
		enddate = { year = 1034 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1722 }
		secondary = { type = 10 id = 1717 }
		startdate = { year = 1034 month = january day = 1 }
		enddate = { year = 1041 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1726 }
		secondary = { type = 10 id = 1717 }
		startdate = { year = 1042 month = january day = 1 }
		enddate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1730 }
		secondary = { type = 10 id = 729 }
		startdate = { year = 1035 month = january day = 1 }
		enddate = { year = 1059 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1732 }
		secondary = { type = 10 id = 1733 }
		startdate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1734 }
		secondary = { type = 10 id = 725 }
		startdate = { year = 1053 month = january day = 1 }
		enddate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1746 }
		secondary = { type = 10 id = 1783 }
		startdate = { year = 1036 month = january day = 1 }
		enddate = { year = 1062 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 3212 }
		secondary = { type = 10 id = 3213 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 3853 }
		secondary = { type = 10 id = 3856 }
		startdate = { year = 1055 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5788 }
		secondary = { type = 10 id = 102536 }
		startdate = { year = 1062 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6120 }
		secondary = { type = 10 id = 6121 }
		startdate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6358 }
		secondary = { type = 10 id = 40507 }
		startdate = { year = 1044 month = january day = 1 }
		enddate = { year = 1049 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6358 }
		secondary = { type = 10 id = 81849 }
		startdate = { year = 1051 month = january day = 1 }
		enddate = { year = 1052 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6358 }
		secondary = { type = 10 id = 81856 }
		startdate = { year = 1052 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6376 }
		secondary = { type = 10 id = 40516 }
		startdate = { year = 1061 month = january day = 1 }
		enddate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6384 }
		secondary = { type = 10 id = 40506 }
		startdate = { year = 1054 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6400 }
		secondary = { type = 10 id = 6449 }
		startdate = { year = 869 month = january day = 1 }
		enddate = { year = 902 month = november day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 6408 }
		secondary = { type = 10 id = 6409 }
		startdate = { year = 983 month = january day = 1 }
		enddate = { year = 989 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6442 }
		secondary = { type = 10 id = 6401 }
		startdate = { year = 886 month = january day = 1 }
		enddate = { year = 931 month = april day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6444 }
		secondary = { type = 10 id = 1283 }
		startdate = { year = 936 month = january day = 1 }
		enddate = { year = 956 month = june day = 16 }
	}
	marrige = {
		primary = { type = 10 id = 6506 }
		secondary = { type = 10 id = 6507 }
		startdate = { year = 976 month = march day = 14 }
		enddate = { year = 1002 month = september day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 6508 }
		secondary = { type = 10 id = 381 }
		startdate = { year = 1012 month = january day = 1 }
		enddate = { year = 1014 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6510 }
		secondary = { type = 10 id = 441 }
		startdate = { year = 1047 month = july day = 17 }
		enddate = { year = 1048 month = september day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 6804 }
		secondary = { type = 10 id = 6805 }
		startdate = { year = 1024 month = january day = 1 }
		enddate = { year = 1038 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6806 }
		secondary = { type = 10 id = 110639 }
		startdate = { year = 1053 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6817 }
		secondary = { type = 10 id = 258 }
		startdate = { year = 1022 month = january day = 1 }
		enddate = { year = 1057 month = january day = 26 }
	}
	marrige = {
		primary = { type = 10 id = 6820 }
		secondary = { type = 10 id = 6821 }
		startdate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 7032 }
		secondary = { type = 10 id = 7033 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 7200 }
		secondary = { type = 10 id = 7201 }
		startdate = { year = 1049 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 8410 }
		secondary = { type = 10 id = 101527 }
		startdate = { year = 1060 month = january day = 1 }
		enddate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 8628 }
		secondary = { type = 10 id = 475 }
		startdate = { year = 1063 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 9950 }
		secondary = { type = 10 id = 9951 }
		startdate = { year = 1018 month = january day = 1 }
		enddate = { year = 1048 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 9950 }
		secondary = { type = 10 id = 9956 }
		startdate = { year = 1016 month = january day = 1 }
		enddate = { year = 1017 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 9952 }
		secondary = { type = 10 id = 9953 }
		startdate = { year = 1039 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 9954 }
		secondary = { type = 10 id = 9955 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20267 }
		secondary = { type = 10 id = 20268 }
		startdate = { year = 1001 month = january day = 1 }
		enddate = { year = 1031 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 100503 }
		secondary = { type = 10 id = 101506 }
		startdate = { year = 973 month = january day = 1 }
		enddate = { year = 988 month = may day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 100504 }
		secondary = { type = 10 id = 100519 }
		startdate = { year = 972 month = january day = 1 }
		enddate = { year = 981 month = march day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 100504 }
		secondary = { type = 10 id = 755 }
		startdate = { year = 982 month = january day = 1 }
		enddate = { year = 995 month = march day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 100506 }
		secondary = { type = 10 id = 2801 }
		startdate = { year = 997 month = january day = 1 }
		enddate = { year = 1002 month = october day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 100508 }
		secondary = { type = 10 id = 102516 }
		startdate = { year = 1020 month = january day = 1 }
		enddate = { year = 1035 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 100509 }
		secondary = { type = 10 id = 100510 }
		startdate = { year = 1029 month = july day = 6 }
		enddate = { year = 1058 month = april day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 100518 }
		secondary = { type = 10 id = 100520 }
		startdate = { year = 975 month = january day = 1 }
		enddate = { year = 1000 month = august day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 100521 }
		secondary = { type = 10 id = 102545 }
		startdate = { year = 996 month = january day = 1 }
		enddate = { year = 1018 month = january day = 24 }
	}
	marrige = {
		primary = { type = 10 id = 100522 }
		secondary = { type = 10 id = 100514 }
		startdate = { year = 1040 month = january day = 1 }
		enddate = { year = 1066 month = august day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 100527 }
		secondary = { type = 10 id = 100528 }
		startdate = { year = 1080 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 100532 }
		secondary = { type = 10 id = 100543 }
		startdate = { year = 1001 month = january day = 1 }
		enddate = { year = 1031 month = june day = 17 }
	}
	marrige = {
		primary = { type = 10 id = 100533 }
		secondary = { type = 10 id = 100541 }
		startdate = { year = 1049 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 100538 }
		secondary = { type = 10 id = 100535 }
		startdate = { year = 1045 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 100539 }
		secondary = { type = 10 id = 100534 }
		startdate = { year = 1026 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 100544 }
		secondary = { type = 10 id = 100545 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 100546 }
		secondary = { type = 10 id = 100547 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 101500 }
		secondary = { type = 10 id = 101501 }
		startdate = { year = 899 month = january day = 1 }
		enddate = { year = 935 month = may day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 101502 }
		secondary = { type = 10 id = 101503 }
		startdate = { year = 940 month = january day = 1 }
		enddate = { year = 986 month = july day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 101505 }
		secondary = { type = 10 id = 755 }
		startdate = { year = 995 month = january day = 1 }
		enddate = { year = 1014 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 101505 }
		secondary = { type = 10 id = 100519 }
		startdate = { year = 996 month = january day = 1 }
		enddate = { year = 1000 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 101510 }
		secondary = { type = 10 id = 135 }
		startdate = { year = 1014 month = january day = 1 }
		enddate = { year = 1015 month = december day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 101515 }
		secondary = { type = 10 id = 102516 }
		startdate = { year = 1036 month = january day = 1 }
		enddate = { year = 1038 month = january day = 22 }
	}
	marrige = {
		primary = { type = 10 id = 101517 }
		secondary = { type = 10 id = 101518 }
		startdate = { year = 1061 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 101535 }
		secondary = { type = 10 id = 101509 }
		startdate = { year = 1018 month = january day = 1 }
		enddate = { year = 1026 month = may day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 101540 }
		secondary = { type = 10 id = 101537 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 101541 }
		secondary = { type = 10 id = 102519 }
		startdate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 101542 }
		secondary = { type = 10 id = 101545 }
		startdate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 101543 }
		secondary = { type = 10 id = 101544 }
		startdate = { year = 1025 month = january day = 1 }
		enddate = { year = 1050 month = april day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 102500 }
		secondary = { type = 10 id = 102501 }
		startdate = { year = 997 month = january day = 1 }
		enddate = { year = 1018 month = june day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 102504 }
		secondary = { type = 10 id = 102503 }
		startdate = { year = 1026 month = january day = 1 }
		enddate = { year = 1059 month = august day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 102507 }
		secondary = { type = 10 id = 101504 }
		startdate = { year = 933 month = january day = 1 }
		enddate = { year = 954 month = january day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 102510 }
		secondary = { type = 10 id = 102511 }
		startdate = { year = 960 month = january day = 1 }
		enddate = { year = 995 month = january day = 10 }
	}
	marrige = {
		primary = { type = 10 id = 102514 }
		secondary = { type = 10 id = 100505 }
		startdate = { year = 991 month = january day = 1 }
		enddate = { year = 1010 month = april day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 102517 }
		secondary = { type = 10 id = 101508 }
		startdate = { year = 996 month = january day = 1 }
		enddate = { year = 1024 month = june day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 102518 }
		secondary = { type = 10 id = 102520 }
		startdate = { year = 1013 month = january day = 1 }
		enddate = { year = 1030 month = june day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 102521 }
		secondary = { type = 10 id = 102513 }
		startdate = { year = 999 month = january day = 3 }
		enddate = { year = 1027 month = july day = 22 }
	}
	marrige = {
		primary = { type = 10 id = 102523 }
		secondary = { type = 10 id = 102530 }
		startdate = { year = 1056 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 102526 }
		secondary = { type = 10 id = 102501 }
		startdate = { year = 985 month = january day = 1 }
		enddate = { year = 995 month = november day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 102527 }
		secondary = { type = 10 id = 100512 }
		startdate = { year = 1019 month = january day = 7 }
		enddate = { year = 1030 month = august day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 102531 }
		secondary = { type = 10 id = 633 }
		startdate = { year = 1051 month = march day = 17 }
		enddate = { year = 1066 month = september day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 102537 }
		secondary = { type = 10 id = 102505 }
		startdate = { year = 1038 month = january day = 1 }
		enddate = { year = 1058 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 102539 }
		secondary = { type = 10 id = 102540 }
		startdate = { year = 1062 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 102542 }
		secondary = { type = 10 id = 102541 }
		startdate = { year = 950 month = january day = 1 }
		enddate = { year = 963 month = march day = 27 }
	}
	marrige = {
		primary = { type = 10 id = 102546 }
		secondary = { type = 10 id = 102513 }
		startdate = { year = 1028 month = january day = 1 }
		enddate = { year = 1050 month = april day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 102547 }
		secondary = { type = 10 id = 102506 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 102548 }
		secondary = { type = 10 id = 102549 }
		startdate = { year = 980 month = january day = 1 }
		enddate = { year = 1016 month = july day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 102550 }
		secondary = { type = 10 id = 102566 }
		startdate = { year = 1015 month = january day = 1 }
		enddate = { year = 1028 month = december day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 102553 }
		secondary = { type = 10 id = 102557 }
		startdate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 102554 }
		secondary = { type = 10 id = 102512 }
		startdate = { year = 997 month = january day = 1 }
		enddate = { year = 1050 month = june day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 102556 }
		secondary = { type = 10 id = 102555 }
		startdate = { year = 1020 month = january day = 1 }
		enddate = { year = 1029 month = august day = 26 }
	}
	marrige = {
		primary = { type = 10 id = 102565 }
		secondary = { type = 10 id = 102544 }
		startdate = { year = 987 month = january day = 1 }
		enddate = { year = 1028 month = december day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 102567 }
		secondary = { type = 10 id = 102515 }
		startdate = { year = 1021 month = january day = 1 }
		enddate = { year = 1052 month = april day = 9 }
	}
	marrige = {
		primary = { type = 10 id = 102568 }
		secondary = { type = 10 id = 101522 }
		startdate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106010 }
		secondary = { type = 10 id = 1079 }
		startdate = { year = 1038 month = january day = 1 }
		enddate = { year = 1054 month = september day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106018 }
		secondary = { type = 10 id = 106019 }
		startdate = { year = 1056 month = january day = 1 }
		enddate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106018 }
		secondary = { type = 10 id = 106020 }
		startdate = { year = 1060 month = january day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 106024 }
		secondary = { type = 10 id = 106023 }
		startdate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106030 }
		secondary = { type = 10 id = 107650 }
		startdate = { year = 1013 month = january day = 1 }
		enddate = { year = 1032 month = october day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 106040 }
		secondary = { type = 10 id = 106041 }
		startdate = { year = 981 month = january day = 1 }
		enddate = { year = 1004 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106060 }
		secondary = { type = 10 id = 106061 }
		startdate = { year = 1035 month = january day = 1 }
		enddate = { year = 1042 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106510 }
		secondary = { type = 10 id = 106513 }
		startdate = { year = 1058 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106512 }
		secondary = { type = 10 id = 106511 }
		startdate = { year = 1034 month = january day = 1 }
		enddate = { year = 1038 month = april day = 23 }
	}
	marrige = {
		primary = { type = 10 id = 106526 }
		secondary = { type = 10 id = 106525 }
		startdate = { year = 1040 month = january day = 1 }
		enddate = { year = 1053 month = april day = 23 }
	}
	marrige = {
		primary = { type = 10 id = 106522 }
		secondary = { type = 10 id = 106521 }
		startdate = { year = 1050 month = january day = 1 }
		enddate = { year = 1061 month = may day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 368 }
		secondary = { type = 10 id = 106521 }
		startdate = { year = 1063 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106540 }
		secondary = { type = 10 id = 106543 }
		startdate = { year = 1054 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106542 }
		secondary = { type = 10 id = 106541 }
		startdate = { year = 1033 month = january day = 1 }
		enddate = { year = 1053 month = june day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 106572 }
		secondary = { type = 10 id = 106571 }
		startdate = { year = 1018 month = january day = 1 }
		enddate = { year = 1044 month = march day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 106590 }
		secondary = { type = 10 id = 106593 }
		startdate = { year = 1049 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106592 }
		secondary = { type = 10 id = 106591 }
		startdate = { year = 1024 month = january day = 1 }
		enddate = { year = 1058 month = december day = 9 }
	}
	marrige = {
		primary = { type = 10 id = 106600 }
		secondary = { type = 10 id = 106603 }
		startdate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106602 }
		secondary = { type = 10 id = 106601 }
		startdate = { year = 1020 month = january day = 1 }
		enddate = { year = 1044 month = october day = 23 }
	}
	marrige = {
		primary = { type = 10 id = 106642 }
		secondary = { type = 10 id = 106641 }
		startdate = { year = 1124 month = january day = 1 }
		enddate = { year = 1039 month = july day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 106643 }
		secondary = { type = 10 id = 106640 }
		startdate = { year = 1055 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 107510 }
		secondary = { type = 10 id = 107511 }
		startdate = { year = 1032 month = january day = 1 }
		enddate = { year = 1065 month = december day = 27 }
	}
	marrige = {
		primary = { type = 10 id = 107520 }
		secondary = { type = 10 id = 107521 }
		startdate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 107530 }
		secondary = { type = 10 id = 107531 }
		startdate = { year = 1025 month = january day = 1 }
		enddate = { year = 1057 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 107560 }
		secondary = { type = 10 id = 107561 }
		startdate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 107570 }
		secondary = { type = 10 id = 107571 }
		startdate = { year = 1022 month = january day = 1 }
		enddate = { year = 1051 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 107580 }
		secondary = { type = 10 id = 107581 }
		startdate = { year = 990 month = january day = 1 }
		enddate = { year = 1016 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 107600 }
		secondary = { type = 10 id = 107601 }
		startdate = { year = 1042 month = january day = 1 }
		enddate = { year = 1058 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 107620 }
		secondary = { type = 10 id = 107621 }
		startdate = { year = 1004 month = january day = 1 }
		enddate = { year = 1035 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 107630 }
		secondary = { type = 10 id = 107631 }
		startdate = { year = 1016 month = january day = 1 }
		enddate = { year = 1059 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 107660 }
		secondary = { type = 10 id = 107689 }
		startdate = { year = 994 month = january day = 1 }
		enddate = { year = 1017 month = february day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 107670 }
		secondary = { type = 10 id = 107671 }
		startdate = { year = 958 month = january day = 1 }
		enddate = { year = 995 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 107673 }
		secondary = { type = 10 id = 108590 }
		startdate = { year = 991 month = january day = 1 }
		enddate = { year = 999 month = september day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 107680 }
		secondary = { type = 10 id = 107681 }
		startdate = { year = 932 month = january day = 1 }
		enddate = { year = 959 month = december day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 107680 }
		secondary = { type = 10 id = 107683 }
		startdate = { year = 960 month = january day = 1 }
		enddate = { year = 970 month = june day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 107686 }
		secondary = { type = 10 id = 107687 }
		startdate = { year = 1055 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 108510 }
		secondary = { type = 10 id = 108511 }
		startdate = { year = 1047 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 108520 }
		secondary = { type = 10 id = 108521 }
		startdate = { year = 1033 month = january day = 1 }
		enddate = { year = 1056 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 108530 }
		secondary = { type = 10 id = 108531 }
		startdate = { year = 1020 month = january day = 1 }
		enddate = { year = 1037 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 108540 }
		secondary = { type = 10 id = 108541 }
		startdate = { year = 1016 month = january day = 1 }
		enddate = { year = 1057 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 108550 }
		secondary = { type = 10 id = 108551 }
		startdate = { year = 1000 month = january day = 1 }
		enddate = { year = 1012 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 108560 }
		secondary = { type = 10 id = 108592 }
		startdate = { year = 999 month = january day = 1 }
		enddate = { year = 1032 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 108580 }
		secondary = { type = 10 id = 108581 }
		startdate = { year = 986 month = january day = 1 }
		enddate = { year = 1049 month = october day = 22 }
	}
	marrige = {
		primary = { type = 10 id = 108590 }
		secondary = { type = 10 id = 108591 }
		startdate = { year = 973 month = january day = 1 }
		enddate = { year = 988 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 108600 }
		secondary = { type = 10 id = 107682 }
		startdate = { year = 941 month = january day = 1 }
		enddate = { year = 955 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110500 }
		secondary = { type = 10 id = 110501 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110510 }
		secondary = { type = 10 id = 1077 }
		startdate = { year = 1036 month = august day = 22 }
		enddate = { year = 1054 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110510 }
		secondary = { type = 10 id = 239 }
		startdate = { year = 1054 month = august day = 22 }
		enddate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110520 }
		secondary = { type = 10 id = 110631 }
		startdate = { year = 1042 month = january day = 1 }
		enddate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110520 }
		secondary = { type = 10 id = 110633 }
		startdate = { year = 1027 month = january day = 2 }
		enddate = { year = 1035 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110530 }
		secondary = { type = 10 id = 110632 }
		startdate = { year = 1018 month = january day = 1 }
		enddate = { year = 1020 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110538 }
		secondary = { type = 10 id = 110537 }
		startdate = { year = 920 month = january day = 1 }
		enddate = { year = 950 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110538 }
		secondary = { type = 10 id = 110539 }
		startdate = { year = 968 month = january day = 1 }
		enddate = { year = 977 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110540 }
		secondary = { type = 10 id = 110634 }
		startdate = { year = 990 month = january day = 1 }
		enddate = { year = 1018 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110560 }
		secondary = { type = 10 id = 110653 }
		startdate = { year = 1050 month = january day = 1 }
		enddate = { year = 1055 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110570 }
		secondary = { type = 10 id = 110664 }
		startdate = { year = 1030 month = january day = 1 }
		enddate = { year = 1038 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110571 }
		secondary = { type = 10 id = 110572 }
		startdate = { year = 990 month = january day = 1 }
		enddate = { year = 1010 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110580 }
		secondary = { type = 10 id = 110663 }
		startdate = { year = 1032 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110581 }
		secondary = { type = 10 id = 110564 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110582 }
		secondary = { type = 10 id = 110583 }
		startdate = { year = 1056 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110590 }
		secondary = { type = 10 id = 110591 }
		startdate = { year = 999 month = january day = 1 }
		enddate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110600 }
		secondary = { type = 10 id = 110601 }
		startdate = { year = 959 month = january day = 1 }
		enddate = { year = 979 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110610 }
		secondary = { type = 10 id = 110611 }
		startdate = { year = 1030 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110612 }
		secondary = { type = 10 id = 110613 }
		startdate = { year = 1044 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110620 }
		secondary = { type = 10 id = 110621 }
		startdate = { year = 1000 month = january day = 1 }
		enddate = { year = 1014 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110630 }
		secondary = { type = 10 id = 110512 }
		startdate = { year = 1057 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110635 }
		secondary = { type = 10 id = 110541 }
		startdate = { year = 1036 month = january day = 1 }
		enddate = { year = 1040 month = may day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 110640 }
		secondary = { type = 10 id = 110641 }
		startdate = { year = 1046 month = january day = 1 }
		enddate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110650 }
		secondary = { type = 10 id = 110651 }
		startdate = { year = 1020 month = january day = 1 }
		enddate = { year = 1052 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110660 }
		secondary = { type = 10 id = 110661 }
		startdate = { year = 992 month = january day = 1 }
		enddate = { year = 1020 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 112600 }
		secondary = { type = 10 id = 112601 }
		startdate = { year = 1150 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1116 }
		secondary = { type = 10 id = 1117 }
		startdate = { year = 1128 month = january day = 1 }
		enddate = { year = 1052 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1120 }
		secondary = { type = 10 id = 10000 }
		startdate = { year = 1009 month = january day = 1 }
		enddate = { year = 1019 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1120 }
		secondary = { type = 10 id = 10008 }
		startdate = { year = 1019 month = january day = 1 }
		enddate = { year = 1041 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1128 }
		secondary = { type = 10 id = 10003 }
		startdate = { year = 1054 month = january day = 1 }
		enddate = { year = 1059 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1128 }
		secondary = { type = 10 id = 1123 }
		startdate = { year = 1059 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1130 }
		secondary = { type = 10 id = 1137 }
		startdate = { year = 1049 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1132 }
		secondary = { type = 10 id = 10014 }
		startdate = { year = 1061 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1152 }
		secondary = { type = 10 id = 1153 }
		startdate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20112 }
		secondary = { type = 10 id = 10015 }
		startdate = { year = 1029 month = january day = 1 }
		enddate = { year = 1034 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20112 }
		secondary = { type = 10 id = 10019 }
		startdate = { year = 1034 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10016 }
		secondary = { type = 10 id = 10017 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20176 }
		secondary = { type = 10 id = 10022 }
		startdate = { year = 1046 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10026 }
		secondary = { type = 10 id = 10027 }
		startdate = { year = 1023 month = january day = 1 }
		enddate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10028 }
		secondary = { type = 10 id = 10029 }
		startdate = { year = 1034 month = january day = 1 }
		enddate = { year = 1058 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10032 }
		secondary = { type = 10 id = 10033 }
		startdate = { year = 1039 month = january day = 1 }
		enddate = { year = 1051 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10034 }
		secondary = { type = 10 id = 10035 }
		startdate = { year = 1054 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20290 }
		secondary = { type = 10 id = 10039 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 346 }
		secondary = { type = 10 id = 10041 }
		startdate = { year = 1020 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10050 }
		secondary = { type = 10 id = 10051 }
		startdate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10042 }
		secondary = { type = 10 id = 10043 }
		startdate = { year = 1000 month = january day = 1 }
		enddate = { year = 1058 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10056 }
		secondary = { type = 10 id = 1357 }
		startdate = { year = 970 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20292 }
		secondary = { type = 10 id = 10077 }
		startdate = { year = 1053 month = january day = 1 }
		enddate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20292 }
		secondary = { type = 10 id = 10078 }
		startdate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10081 }
		secondary = { type = 10 id = 1113 }
		startdate = { year = 1000 month = january day = 1 }
		enddate = { year = 1035 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1610 }
		secondary = { type = 10 id = 10086 }
		startdate = { year = 1051 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10089 }
		secondary = { type = 10 id = 10090 }
		startdate = { year = 1057 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1326 }
		secondary = { type = 10 id = 1327 }
		startdate = { year = 901 month = january day = 1 }
		enddate = { year = 940 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1292 }
		secondary = { type = 10 id = 10096 }
		startdate = { year = 942 month = january day = 1 }
		enddate = { year = 955 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20216 }
		secondary = { type = 10 id = 20215 }
		startdate = { year = 1041 month = january day = 1 }
		enddate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20212 }
		secondary = { type = 10 id = 20213 }
		startdate = { year = 941 month = january day = 1 }
		enddate = { year = 987 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20210 }
		secondary = { type = 10 id = 20211 }
		startdate = { year = 926 month = january day = 1 }
		enddate = { year = 942 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10084 }
		secondary = { type = 10 id = 20209 }
		startdate = { year = 956 month = january day = 1 }
		enddate = { year = 994 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20208 }
		secondary = { type = 10 id = 20207 }
		startdate = { year = 994 month = january day = 1 }
		enddate = { year = 1025 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20206 }
		secondary = { type = 10 id = 1339 }
		startdate = { year = 1022 month = january day = 1 }
		enddate = { year = 1047 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 7053 }
		secondary = { type = 10 id = 7052 }
		startdate = { year = 1044 month = january day = 1 }
		enddate = { year = 1053 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6642 }
		secondary = { type = 10 id = 6643 }
		startdate = { year = 1046 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6640 }
		secondary = { type = 10 id = 6641 }
		startdate = { year = 1026 month = january day = 1 }
		enddate = { year = 1048 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6632 }
		secondary = { type = 10 id = 6633 }
		startdate = { year = 1007 month = january day = 1 }
		enddate = { year = 1044 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1328 }
		secondary = { type = 10 id = 1329 }
		startdate = { year = 941 month = january day = 1 }
		enddate = { year = 973 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11000 }
		secondary = { type = 10 id = 11001 }
		startdate = { year = 1032 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11002 }
		secondary = { type = 10 id = 11003 }
		startdate = { year = 1008 month = january day = 1 }
		enddate = { year = 1032 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 7735 }
		secondary = { type = 10 id = 7736 }
		startdate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 7755 }
		secondary = { type = 10 id = 7756 }
		startdate = { year = 1036 month = january day = 1 }
		enddate = { year = 1052 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11004 }
		secondary = { type = 10 id = 11005 }
		startdate = { year = 988 month = january day = 1 }
		enddate = { year = 1027 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11006 }
		secondary = { type = 10 id = 11007 }
		startdate = { year = 1011 month = january day = 1 }
		enddate = { year = 1035 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11008 }
		secondary = { type = 10 id = 11009 }
		startdate = { year = 955 month = january day = 1 }
		enddate = { year = 987 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20071 }
		secondary = { type = 10 id = 4071 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20249 }
		secondary = { type = 10 id = 4249 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20253 }
		secondary = { type = 10 id = 4253 }
		startdate = { year = 1057 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20257 }
		secondary = { type = 10 id = 4257 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20286 }
		secondary = { type = 10 id = 40571 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20287 }
		secondary = { type = 10 id = 11012 }
		startdate = { year = 1035 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20289 }
		secondary = { type = 10 id = 4289 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20362 }
		secondary = { type = 10 id = 4362 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20554 }
		secondary = { type = 10 id = 4554 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20876 }
		secondary = { type = 10 id = 4876 }
		startdate = { year = 1029 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20265 }
		secondary = { type = 10 id = 20264 }
		startdate = { year = 1031 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 11021 }
		secondary = { type = 10 id = 11022 }
		startdate = { year = 1009 month = january day = 0 }
		enddate = { year = 1030 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 7313 }
		secondary = { type = 10 id = 20264 }
		startdate = { year = 1027 month = january day = 0 }
		enddate = { year = 1030 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 7060 }
		secondary = { type = 10 id = 106605 }
		startdate = { year = 1059 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 20262 }
		secondary = { type = 10 id = 4262 }
		startdate = { year = 1055 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 7315 }
		secondary = { type = 10 id = 7314 }
		startdate = { year = 1000 month = january day = 0 }
		enddate = { year = 1030 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 11030 }
		secondary = { type = 10 id = 11031 }
		startdate = { year = 1021 month = january day = 0 }
		enddate = { year = 1054 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 11030 }
		secondary = { type = 10 id = 7755 }
		startdate = { year = 1055 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 20142 }
		secondary = { type = 10 id = 10070 }
		startdate = { year = 1054 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 11032 }
		secondary = { type = 10 id = 11033 }
		startdate = { year = 999 month = january day = 0 }
		enddate = { year = 1044 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 11036 }
		secondary = { type = 10 id = 1411 }
		startdate = { year = 964 month = january day = 0 }
		enddate = { year = 1005 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 109601 }
		secondary = { type = 10 id = 109602 }
		startdate = { year = 994 month = january day = 1 }
		enddate = { year = 1016 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 109606 }
		secondary = { type = 10 id = 109605 }
		startdate = { year = 1031 month = january day = 1 }
		enddate = { year = 1056 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 109607 }
		secondary = { type = 10 id = 109608 }
		startdate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 109610 }
		secondary = { type = 10 id = 109609 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 109620 }
		secondary = { type = 10 id = 109621 }
		startdate = { year = 956 month = january day = 1 }
		enddate = { year = 978 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 109622 }
		secondary = { type = 10 id = 109623 }
		startdate = { year = 985 month = january day = 1 }
		enddate = { year = 1012 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 108570 }
		secondary = { type = 10 id = 109624 }
		startdate = { year = 1010 month = january day = 1 }
		enddate = { year = 1022 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 109603 }
		secondary = { type = 10 id = 109625 }
		startdate = { year = 1026 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 109626 }
		secondary = { type = 10 id = 109627 }
		startdate = { year = 1000 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 109628 }
		secondary = { type = 10 id = 109629 }
		startdate = { year = 1046 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20233 }
		secondary = { type = 10 id = 20232 }
		startdate = { year = 1041 month = january day = 1 }
		enddate = { year = 1056 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20236 }
		secondary = { type = 10 id = 106519 }
		startdate = { year = 1021 month = january day = 1 }
		enddate = { year = 1027 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 394 }
		secondary = { type = 10 id = 40411 }
		startdate = { year = 1061 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6404 }
		secondary = { type = 10 id = 40323 }
		startdate = { year = 945 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40402 }
		secondary = { type = 10 id = 40431 }
		startdate = { year = 989 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 418 }
		secondary = { type = 10 id = 40409 }
		startdate = { year = 1049 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40102 }
		secondary = { type = 10 id = 40451 }
		startdate = { year = 1045 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40372 }
		secondary = { type = 10 id = 40461 }
		startdate = { year = 1010 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20240 }
		secondary = { type = 10 id = 1337 }
		startdate = { year = 1026 month = january day = 1 }
		enddate = { year = 1049 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20237 }
		secondary = { type = 10 id = 11038 }
		startdate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11051 }
		secondary = { type = 10 id = 11052 }
		startdate = { year = 990 month = january day = 1 }
		enddate = { year = 1039 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6009 }
		secondary = { type = 10 id = 6010 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6006 }
		secondary = { type = 10 id = 6007 }
		startdate = { year = 1048 month = january day = 1 }
		enddate = { year = 1058 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6002 }
		secondary = { type = 10 id = 6001 }
		startdate = { year = 1026 month = january day = 1 }
		enddate = { year = 1034 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5998 }
		secondary = { type = 10 id = 5997 }
		startdate = { year = 996 month = january day = 1 }
		enddate = { year = 1020 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5996 }
		secondary = { type = 10 id = 6001 }
		startdate = { year = 1032 month = january day = 1 }
		enddate = { year = 1057 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5994 }
		secondary = { type = 10 id = 5995 }
		startdate = { year = 998 month = january day = 1 }
		enddate = { year = 1014 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1748 }
		secondary = { type = 10 id = 727 }
		startdate = { year = 1043 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1752 }
		secondary = { type = 10 id = 4511 }
		startdate = { year = 1042 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11064 }
		secondary = { type = 10 id = 11063 }
		startdate = { year = 963 month = january day = 1 }
		enddate = { year = 986 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11066 }
		secondary = { type = 10 id = 11065 }
		startdate = { year = 1005 month = january day = 1 }
		enddate = { year = 1020 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11067 }
		secondary = { type = 10 id = 11068 }
		startdate = { year = 1005 month = january day = 1 }
		enddate = { year = 1020 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20490 }
		secondary = { type = 10 id = 4490 }
		startdate = { year = 1014 month = january day = 1 }
		enddate = { year = 1051 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20491 }
		secondary = { type = 10 id = 4491 }
		startdate = { year = 1024 month = january day = 1 }
		enddate = { year = 1034 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20491 }
		secondary = { type = 10 id = 4495 }
		startdate = { year = 1035 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20492 }
		secondary = { type = 10 id = 4493 }
		startdate = { year = 1049 month = january day = 1 }
		enddate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20529 }
		secondary = { type = 10 id = 4492 }
		startdate = { year = 1059 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 472 }
		secondary = { type = 10 id = 479 }
		startdate = { year = 1059 month = january day = 1 }
		enddate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 472 }
		secondary = { type = 10 id = 481 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1618 }
		secondary = { type = 10 id = 1619 }
		startdate = { year = 1022 month = january day = 1 }
		enddate = { year = 1025 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1620 }
		secondary = { type = 10 id = 1617 }
		startdate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20260 }
		secondary = { type = 10 id = 4260 }
		startdate = { year = 1063 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20223 }
		secondary = { type = 10 id = 4223 }
		startdate = { year = 1063 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40090 }
		secondary = { type = 10 id = 40097 }
		startdate = { year = 980 month = january day = 1 }
		enddate = { year = 1010 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40500 }
		secondary = { type = 10 id = 40501 }
		startdate = { year = 998 month = january day = 1 }
		enddate = { year = 1023 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40503 }
		secondary = { type = 10 id = 40501 }
		startdate = { year = 1024 month = january day = 1 }
		enddate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40508 }
		secondary = { type = 10 id = 40505 }
		startdate = { year = 1047 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40530 }
		secondary = { type = 10 id = 40531 }
		startdate = { year = 1000 month = january day = 1 }
		enddate = { year = 1016 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40541 }
		secondary = { type = 10 id = 40542 }
		startdate = { year = 1049 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40543 }
		secondary = { type = 10 id = 40544 }
		startdate = { year = 1047 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40555 }
		secondary = { type = 10 id = 40556 }
		startdate = { year = 1000 month = january day = 1 }
		enddate = { year = 1034 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40605 }
		secondary = { type = 10 id = 40606 }
		startdate = { year = 845 month = january day = 1 }
		enddate = { year = 879 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40610 }
		secondary = { type = 10 id = 40611 }
		startdate = { year = 1037 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40613 }
		secondary = { type = 10 id = 40614 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1614 }
		secondary = { type = 10 id = 40703 }
		startdate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40712 }
		secondary = { type = 10 id = 40709 }
		startdate = { year = 980 month = january day = 1 }
		enddate = { year = 993 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40370 }
		secondary = { type = 10 id = 277 }
		startdate = { year = 990 month = january day = 1 }
		enddate = { year = 1028 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6402 }
		secondary = { type = 10 id = 6445 }
		startdate = { year = 907 month = january day = 1 }
		enddate = { year = 931 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6440 }
		secondary = { type = 10 id = 6441 }
		startdate = { year = 850 month = january day = 1 }
		enddate = { year = 866 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110530 }
		secondary = { type = 10 id = 107661 }
		startdate = { year = 1021 month = january day = 1 }
		enddate = { year = 1026 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110536 }
		secondary = { type = 10 id = 110537 }
		startdate = { year = 920 month = january day = 1 }
		enddate = { year = 950 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110638 }
		secondary = { type = 10 id = 41210 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 108570 }
		secondary = { type = 10 id = 106042 }
		startdate = { year = 1023 month = january day = 1 }
		enddate = { year = 1028 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110560 }
		secondary = { type = 10 id = 110636 }
		startdate = { year = 1055 month = january day = 1 }
		enddate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 100521 }
		secondary = { type = 10 id = 100510 }
		startdate = { year = 1020 month = january day = 1 }
		enddate = { year = 1028 month = february day = 24 }
	}
	marrige = {
		primary = { type = 10 id = 608 }
		secondary = { type = 10 id = 41100 }
		startdate = { year = 988 month = january day = 1 }
		enddate = { year = 1011 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 110 }
		secondary = { type = 10 id = 41101 }
		startdate = { year = 1038 month = january day = 1 }
		enddate = { year = 1057 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 8622 }
		secondary = { type = 10 id = 8630 }
		startdate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40000 }
		secondary = { type = 10 id = 40001 }
		startdate = { year = 1020 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40901 }
		secondary = { type = 10 id = 40011 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40003 }
		secondary = { type = 10 id = 40015 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40010 }
		secondary = { type = 10 id = 40011 }
		startdate = { year = 1000 month = january day = 1 }
		enddate = { year = 1045 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40012 }
		secondary = { type = 10 id = 40013 }
		startdate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40014 }
		secondary = { type = 10 id = 40017 }
		startdate = { year = 1063 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40050 }
		secondary = { type = 10 id = 40037 }
		startdate = { year = 1011 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40024 }
		secondary = { type = 10 id = 40393 }
		startdate = { year = 1020 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40060 }
		secondary = { type = 10 id = 40055 }
		startdate = { year = 1061 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40052 }
		secondary = { type = 10 id = 325 }
		startdate = { year = 1036 month = january day = 1 }
		enddate = { year = 1045 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40070 }
		secondary = { type = 10 id = 40083 }
		startdate = { year = 935 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40128 }
		secondary = { type = 10 id = 40235 }
		startdate = { year = 1020 month = january day = 1 }
		enddate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40130 }
		secondary = { type = 10 id = 40261 }
		startdate = { year = 1015 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40154 }
		secondary = { type = 10 id = 40155 }
		startdate = { year = 955 month = january day = 1 }
		enddate = { year = 990 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40160 }
		secondary = { type = 10 id = 40131 }
		startdate = { year = 1048 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40186 }
		secondary = { type = 10 id = 40203 }
		startdate = { year = 1050 month = january day = 1 }
		enddate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40204 }
		secondary = { type = 10 id = 40187 }
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6630 }
		secondary = { type = 10 id = 40191 }
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40202 }
		secondary = { type = 10 id = 40071 }
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 330 }
		secondary = { type = 10 id = 40263 }
		startdate = { year = 940 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40216 }
		secondary = { type = 10 id = 40243 }
		startdate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40260 }
		secondary = { type = 10 id = 373 }
		startdate = { year = 979 month = january day = 1 }
		enddate = { year = 982 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40278 }
		secondary = { type = 10 id = 40279 }
		startdate = { year = 1001 month = january day = 1 }
		enddate = { year = 1007 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40284 }
		secondary = { type = 10 id = 40313 }
		startdate = { year = 1035 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40286 }
		secondary = { type = 10 id = 40303 }
		startdate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40296 }
		secondary = { type = 10 id = 40273 }
		startdate = { year = 980 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40072 }
		secondary = { type = 10 id = 40315 }
		startdate = { year = 990 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40080 }
		secondary = { type = 10 id = 40317 }
		startdate = { year = 863 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40142 }
		secondary = { type = 10 id = 40365 }
		startdate = { year = 1031 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40210 }
		secondary = { type = 10 id = 40255 }
		startdate = { year = 990 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40300 }
		secondary = { type = 10 id = 40111 }
		startdate = { year = 1040 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40308 }
		secondary = { type = 10 id = 40091 }
		startdate = { year = 999 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40330 }
		secondary = { type = 10 id = 40323 }
		startdate = { year = 968 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40340 }
		secondary = { type = 10 id = 40335 }
		startdate = { year = 979 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40346 }
		secondary = { type = 10 id = 40381 }
		startdate = { year = 1045 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40352 }
		secondary = { type = 10 id = 40363 }
		startdate = { year = 1038 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40362 }
		secondary = { type = 10 id = 40333 }
		startdate = { year = 1019 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41012 }
		secondary = { type = 10 id = 41235 }
		startdate = { year = 980 month = january day = 1 }
		enddate = { year = 1000 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41014 }
		secondary = { type = 10 id = 41015 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41220 }
		secondary = { type = 10 id = 41221 }
		startdate = { year = 1055 month = january day = 1 }
		enddate = { year = 1058 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41220 }
		secondary = { type = 10 id = 10018 }
		startdate = { year = 1058 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41230 }
		secondary = { type = 10 id = 41231 }
		startdate = { year = 1037 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41236 }
		secondary = { type = 10 id = 41237 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41239 }
		secondary = { type = 10 id = 41240 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41241 }
		secondary = { type = 10 id = 41242 }
		startdate = { year = 1053 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41250 }
		secondary = { type = 10 id = 156 }
		startdate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41260 }
		secondary = { type = 10 id = 41252 }
		startdate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1785 }
		secondary = { type = 10 id = 41300 }
		startdate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41303 }
		secondary = { type = 10 id = 4538 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 9952 }
		secondary = { type = 10 id = 41311 }
		startdate = { year = 1032 month = january day = 1 }
		enddate = { year = 1036 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1726 }
		secondary = { type = 10 id = 41553 }
		startdate = { year = 1050 month = january day = 1 }
		enddate = { year = 1055 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41514 }
		secondary = { type = 10 id = 41335 }
		startdate = { year = 1050 month = january day = 1 }
		enddate = { year = 1058 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41522 }
		secondary = { type = 10 id = 41579 }
		startdate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41537 }
		secondary = { type = 10 id = 4533 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41541 }
		secondary = { type = 10 id = 41528 }
		startdate = { year = 854 month = january day = 1 }
		enddate = { year = 878 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41542 }
		secondary = { type = 10 id = 41561 }
		startdate = { year = 877 month = january day = 1 }
		enddate = { year = 881 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41546 }
		secondary = { type = 10 id = 41582 }
		startdate = { year = 960 month = january day = 1 }
		enddate = { year = 1001 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41559 }
		secondary = { type = 10 id = 41503 }
		startdate = { year = 828 month = january day = 1 }
		enddate = { year = 860 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41562 }
		secondary = { type = 10 id = 41527 }
		startdate = { year = 873 month = january day = 1 }
		enddate = { year = 887 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41535 }
		secondary = { type = 10 id = 41323 }
		startdate = { year = 990 month = january day = 1 }
		enddate = { year = 1008 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41590 }
		secondary = { type = 10 id = 41569 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1714 }
		secondary = { type = 10 id = 1771 }
		startdate = { year = 945 month = january day = 1 }
		enddate = { year = 976 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 3040 }
		secondary = { type = 10 id = 41517 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20544 }
		secondary = { type = 10 id = 41593 }
		startdate = { year = 1050 month = january day = 1 }
		enddate = { year = 1055 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41000 }
		secondary = { type = 10 id = 41001 }
		startdate = { year = 1025 month = january day = 1 }
		enddate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41600 }
		secondary = { type = 10 id = 41518 }
		startdate = { year = 1042 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1124 }
		secondary = { type = 10 id = 1129 }
		startdate = { year = 1048 month = january day = 1 }
		enddate = { year = 1051 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1126 }
		secondary = { type = 10 id = 1129 }
		startdate = { year = 1053 month = january day = 1 }
		enddate = { year = 1057 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41707 }
		secondary = { type = 10 id = 41708 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41709 }
		secondary = { type = 10 id = 41710 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41711 }
		secondary = { type = 10 id = 41712 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41713 }
		secondary = { type = 10 id = 41714 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 41715 }
		secondary = { type = 10 id = 41716 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1736 }
		secondary = { type = 10 id = 41552 }
		startdate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 8608 }
		secondary = { type = 10 id = 538 }
		startdate = { year = 1015 month = january day = 1 }
		enddate = { year = 1043 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 8634 }
		secondary = { type = 10 id = 8635 }
		startdate = { year = 931 month = january day = 1 }
		enddate = { year = 969 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 539 }
		secondary = { type = 10 id = 540 }
		startdate = { year = 966 month = january day = 1 }
		enddate = { year = 981 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 537 }
		secondary = { type = 10 id = 541 }
		startdate = { year = 981 month = january day = 1 }
		enddate = { year = 1008 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 544 }
		secondary = { type = 10 id = 545 }
		startdate = { year = 1003 month = january day = 1 }
		enddate = { year = 1005 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 40502 }
		secondary = { type = 10 id = 123 }
		startdate = { year = 1038 month = january day = 1 }
		enddate = { year = 1063 month = august day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 81816 }
		secondary = { type = 10 id = 40506 }
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 81871 }
		secondary = { type = 10 id = 40522 }
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 81820 }
		secondary = { type = 10 id = 40501 }
		startdate = { year = 998 month = january day = 1 }
		enddate = { year = 1023 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 3935 }
		secondary = { type = 10 id = 85009 }
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 90028 }
		secondary = { type = 10 id = 90029 }
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 358 }
		secondary = { type = 10 id = 359 }
		startdate = { year = 950 month = january day = 1 }
		enddate = { year = 960 month = october day = 10 }
	}
	marrige = {
		primary = { type = 10 id = 40440 }
		secondary = { type = 10 id = 40441 }
		startdate = { year = 1017 month = january day = 1 }
		enddate = { year = 1023 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 90045 }
		secondary = { type = 10 id = 40441 }
		startdate = { year = 1006 month = january day = 1 } 
		enddate = { year = 1008 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 90047 }
		secondary = { type = 10 id = 90048 }
		startdate = { year = 1057 month = january day = 1 } 
	}
	marrige = { 
		primary = { type = 10 id = 90050 }
		secondary = { type = 10 id = 40447 } 
		startdate = { year = 1026 month = january day = 1 } 
		enddate = { year = 1027 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 90051 } 
		secondary = { type = 10 id = 90052 } 
		startdate = { year = 1042 month = january day = 1 } 
	}
	marrige = { 
		primary = { type = 10 id = 90054 } 
		secondary = { type = 10 id = 90055 } 
		startdate = { year = 1019 month = january day = 1 }
		enddate = { year = 1058 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 40404 } 
		secondary = { type = 10 id = 90057 } 
		startdate = { year = 1021 month = january day = 1 }
		enddate = { year = 1060 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 90080 } 
		secondary = { type = 10 id = 90081 } 
		startdate = { year = 1043 month = january day = 1 } 
		enddate = { year = 1055 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 90082 } 
		secondary = { type = 10 id = 90077 } 
		startdate = { year = 1065 month = january day = 1 } #hist 1075
	}
	marrige = { 
		primary = { type = 10 id = 90061 }
		secondary = { type = 10 id = 90078 }
		startdate = { year = 1064 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 90067 } 
		secondary = { type = 10 id = 90079 } 
		startdate = { year = 1059 month = january day = 1 }
		enddate = { year = 1060 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 90067 } 
		secondary = { type = 10 id = 90068 }
		startdate = { year = 1060 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 90053 } 
		secondary = { type = 10 id = 90069 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 40446 } 
		secondary = { type = 10 id = 90070 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 41006 } 
		secondary = { type = 10 id = 90065 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1764 } 
		secondary = { type = 10 id = 1765 } 
		startdate = { year = 1049 month = january day = 1 } 
	}
	marrige = {
		primary = { type = 10 id = 20488 } 
		secondary = { type = 10 id = 90034 } 
		startdate = { year = 1040 month = january day = 1 } 
	}
	marrige = {
		primary = { type = 10 id = 90110 }
		secondary = { type = 10 id = 90109 }
		startdate = { year = 860 month = january day = 1 }
		enddate = { year = 871 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 90115 }
		secondary = { type = 10 id = 90116 }
		startdate = { year = 966 month = january day = 1 }
		enddate = { year = 973 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1415 }
		secondary = { type = 10 id = 90119 }
		startdate = { year = 1060 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1289 }
		secondary = { type = 10 id = 90120 }
		startdate = { year = 940 month = january day = 1 }
		enddate = { year = 954 month = september day = 10 }
	}
	marrige = {
		primary = { type = 10 id = 90117 }
		secondary = { type = 10 id = 90122 }
		startdate = { year = 990 month = january day = 1 }
		enddate = { year = 1011 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 90124 }
		secondary = { type = 10 id = 90111 }
		startdate = { year = 918 month = january day = 1 }
		enddate = {  year = 929 month = october day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 90129 }
		secondary = { type = 10 id = 90130 }
		startdate = { year = 816 month = january day = 1 }
		enddate = {  year = 841 month = june day = 25 }
	}
	marrige = { 
		primary = { type = 10 id = 85026 } 
		secondary = { type = 10 id = 85028 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 1184 } 
		secondary = { type = 10 id = 10080 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 40406 } 
		secondary = { type = 10 id = 627 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 170 }
		secondary = { type = 10 id = 1100404 }
		startdate = { year = 1058 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 190111155  }
		secondary = { type = 10 id = 1129 }
		startdate = { year = 1052 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 281002  }
		secondary = { type = 10 id = 281003 }
		startdate = { year = 1052 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 281711 }
		secondary = { type = 10 id = 281712 }
		startdate = { year = 975 month = january day = 1 }
		enddate = { year = 992 month = may day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 40706 }
		secondary = { type = 10 id = 281713 }
		startdate = { year = 941 month = january day = 1 }
		enddate = { year = 943 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1772 } 
		secondary = { type = 10 id = 42000 } 
		startdate = { year = 950 month = january day = 1 }
		enddate = {  year = 972 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1780 } 
		secondary = { type = 10 id = 42002 } 
		startdate = { year = 1001 month = january day = 1 }
		enddate = {  year = 1037 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 41513 }
		secondary = { type = 10 id = 41334 }
		startdate = { year = 1050 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 19111154 }
		secondary = { type = 10 id = 19111153 }
		startdate = { year = 1025 month = january day = 1 }
		enddate = { year = 1055 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 42005 }
		secondary = { type = 10 id = 42006 }
		startdate = { year = 1066  month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 42007 }
		secondary = { type = 10 id = 42008 }
		startdate = { year = 1066  month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106570 }
		secondary = { type = 10 id = 106573 }
		startdate = { year = 1066  month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 106570 }
		secondary = { type = 10 id = 106573 }
		startdate = { year = 1066  month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 281511 }
		secondary = { type = 10 id = 281507 }
		startdate = { year = 900 month = january day = 1 }
		enddate = { year = 910 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 6807 }
		secondary = { type = 10 id = 198 }
		startdate = { year = 1066 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 198 }
		secondary = { type = 10 id = 5652 }
		startdate = { year = 1066 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 6807 }
		secondary = { type = 10 id = 5652 }
		startdate = { year = 1066 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 140 }
		secondary = { type = 10 id = 178 }
		startdate = { year = 1066 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 140 }
		secondary = { type = 10 id = 6806 }
		startdate = { year = 1066 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 140 }
		secondary = { type = 10 id = 152 }
		startdate = { year = 1066 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 5660 }
		secondary = { type = 10 id = 90028 }
		startdate = { year = 1066 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 85018 }
		secondary = { type = 10 id = 90027 }
		startdate = { year = 1066 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 108500 }
		secondary = { type = 10 id = 218 }
		startdate = { year = 1066 month = december day = 1 }
	}
	friend = {
		primary = { type = 10 id = 85020 }
		secondary = { type = 10 id = 85022 }
		startdate = { year = 1066 month = december day = 1 }
	}
	friend = {
		primary = { type = 10 id = 109500 }
		secondary = { type = 10 id = 85022 }
		startdate = { year = 1066 month = december day = 1 }
	}
	friend = {
		primary = { type = 10 id = 85024 }
		secondary = { type = 10 id = 85022 }
		startdate = { year = 1066 month = december day = 1 }
	}
	friend = {
		primary = { type = 10 id = 85024 }
		secondary = { type = 10 id = 85025 }
		startdate = { year = 1066 month = december day = 1 }
	}
	friend = {
		primary = { type = 10 id = 107640 }
		secondary = { type = 10 id = 108500 }
		startdate = { year = 1066 month = december day = 1 }
	}
	friend = {
		primary = { type = 10 id = 107640 }
		secondary = { type = 10 id = 108501 }
		startdate = { year = 1066 month = december day = 1 }
	}
	friend = {
		primary = { type = 10 id = 108501 }
		secondary = { type = 10 id = 108500 }
		startdate = { year = 1066 month = december day = 1 }
	}
	friend = {
		primary = { type = 10 id = 90139 }
		secondary = { type = 10 id = 90140 }
		startdate = { year = 1066 month = december day = 1 }
	}
	friend = {
		primary = { type = 10 id = 41702 }
		secondary = { type = 10 id = 3050 }
		startdate = { year = 1066 month = december day = 1 }
	}
	friend = {
		primary = { type = 10 id = 41703 }
		secondary = { type = 10 id = 3050 }
		startdate = { year = 1066 month = december day = 1 }
	}
	friend = {
		primary = { type = 10 id = 41703 }
		secondary = { type = 10 id = 41702 }
		startdate = { year = 1066 month = december day = 1 }
	}
	friend = {
		primary = { type = 10 id = 628 } 
		secondary = { type = 10 id = 626 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 628 } 
		secondary = { type = 10 id = 630 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 626 } 
		secondary = { type = 10 id = 630 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 3852 }
		secondary = { type = 10 id = 3853 }
		startdate = { year = 1065 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 281700 } 
		secondary = { type = 10 id = 81814 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 81031 } 
		secondary = { type = 10 id = 81814 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 1746 } 
		secondary = { type = 10 id = 41305 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 41305 } 
		secondary = { type = 10 id = 1733 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 41305 } 
		secondary = { type = 10 id = 1732 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 41305 } 
		secondary = { type = 10 id = 1736 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 1734 } 
		secondary = { type = 10 id = 1740 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 1764 } 
		secondary = { type = 10 id = 1740 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 1742 } 
		secondary = { type = 10 id = 85000 } 
		startdate = { year = 1065 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 1746 } 
		secondary = { type = 10 id = 1733 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 1746 }
		secondary = { type = 10 id = 1734 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 1746 } 
		secondary = { type = 10 id = 1740 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 41305 } 
		secondary = { type = 10 id = 1734 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 1764 } 
		secondary = { type = 10 id = 42014 } 
		startdate = { year = 1065 month = january day = 1 }
	}	
	rival = {
		primary = { type = 10 id = 5660 }
		secondary = { type = 10 id = 140 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 5644 }
		secondary = { type = 10 id = 140 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 198 }
		secondary = { type = 10 id = 140 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 984 }
		secondary = { type = 10 id = 6008 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 1316 }
		secondary = { type = 10 id = 1388 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 1316 }
		secondary = { type = 10 id = 7757 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 762 }
		secondary = { type = 10 id = 20388 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 107500 }
		secondary = { type = 10 id = 108500 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 107500 }
		secondary = { type = 10 id = 109500 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 9952 }
		secondary = { type = 10 id = 85012 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 90027 } 
		secondary = { type = 10 id = 140 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 81846 }
		secondary = { type = 10 id = 6362 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 81814 }
		secondary = { type = 10 id = 6362 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 8400 }
		secondary = { type = 10 id = 20584 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 100525 }
		secondary = { type = 10 id = 100516 }
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 140 } 
		secondary = { type = 10 id = 90028 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 3042 } 
		secondary = { type = 10 id = 3050 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 3040 } 
		secondary = { type = 10 id = 1736 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 109500 } 
		secondary = { type = 10 id = 108500 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 109500 } 
		secondary = { type = 10 id = 109607 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 81846 } 
		secondary = { type = 10 id = 81814 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 81846 } 
		secondary = { type = 10 id = 281704 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 281704 } 
		secondary = { type = 10 id = 81814 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 6806 } 
		secondary = { type = 10 id = 81846 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 6806 } 
		secondary = { type = 10 id = 281704 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 6806 } 
		secondary = { type = 10 id = 281702 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 146 } 
		secondary = { type = 10 id = 391 } 
		startdate = { year = 1066 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 146 } 
		secondary = { type = 10 id = 5662 } 
		startdate = { year = 1066 month = january day = 1 }
	}
}