country = {
	tag = C001
	form_of_goverment = ecclestical
	capital = 1
	ruler = { character = { type = 10 id = 20580 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 1 }
}
country = {
	tag = C003
	form_of_goverment = feudal
	capital = 3
	ruler = { character = { type = 10 id = 20048 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 3 }
}
country = {
	tag = C004
	form_of_goverment = feudal
	capital = 4
	ruler = { character = { type = 10 id = 929 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 4 }
}
country = {
	tag = C005
	form_of_goverment = feudal
	capital = 5
	ruler = { character = { type = 10 id = 6180 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 5 }
}
country = {
	tag = C006
	form_of_goverment = feudal
	capital = 6
	ruler = { character = { type = 10 id = 20011 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 6 }
}
country = {
	tag = C007
	form_of_goverment = feudal
	capital = 7
	ruler = { character = { type = 10 id = 1000 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 7 }
}
country = {
	tag = C009
	form_of_goverment = feudal
	capital = 9
	ruler = { character = { type = 10 id = 1015 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 9 }
}
country = {
	tag = C010
	form_of_goverment = feudal
	capital = 10
	ruler = { character = { type = 10 id = 6120 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 10 }
}
country = {
	tag = C011
	form_of_goverment = feudal
	capital = 11
	ruler = { character = { type = 10 id = 924 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 11 }
}
country = {
	tag = C012
	form_of_goverment = feudal
	capital = 12
	ruler = { character = { type = 10 id = 1020 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 12 }
}
country = {
	tag = C015
	form_of_goverment = feudal
	capital = 15
	ruler = { character = { type = 10 id = 1010 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 15 }
}
country = {
	tag = C017
	form_of_goverment = feudal
	capital = 17
	ruler = { character = { type = 10 id = 6806 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 17 21 }
}
country = {
	tag = C019
	form_of_goverment = feudal
	capital = 19
	ruler = { character = { type = 10 id = 6362 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 19 }
}
country = {
	tag = C020
	form_of_goverment = feudal
	capital = 20
	ruler = { character = { type = 10 id = 81846 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 20 }
}
country = {
	tag = C024
	form_of_goverment = feudal
	capital = 24
	ruler = { character = { type = 10 id = 172 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 24 }
}
country = {
	tag = C025
	form_of_goverment = feudal
	capital = 25
	ruler = { character = { type = 10 id = 152 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 25 }
}
country = {
	tag = C028
	form_of_goverment = feudal
	capital = 28
	ruler = { character = { type = 10 id = 20090 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 28 }
}
country = {
	tag = C029
	form_of_goverment = feudal
	capital = 29
	ruler = { character = { type = 10 id = 41260 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 29 }
}
country = {
	tag = C030
	form_of_goverment = feudal
	capital = 30
	ruler = { character = { type = 10 id = 150 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 30 }
}
country = {
	tag = C031
	form_of_goverment = feudal
	capital = 31
	ruler = { character = { type = 10 id = 354 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 31 }
}
country = {
	tag = C033
	form_of_goverment = feudal
	capital = 33
	ruler = { character = { type = 10 id = 102574 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 33 }
}
country = {
	tag = C034
	form_of_goverment = feudal
	capital = 34
	ruler = { character = { type = 10 id = 20018 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 34 }
}
country = {
	tag = C037
	form_of_goverment = feudal
	capital = 37
	ruler = { character = { type = 10 id = 102539 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 37 }
}
country = {
	tag = C041
	form_of_goverment = feudal
	capital = 41
	ruler = { character = { type = 10 id = 281006 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 41 }
}
country = {
	tag = C042
	form_of_goverment = feudal
	capital = 42
	ruler = { character = { type = 10 id = 20071 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 42 }
}
country = {
	tag = C045
	form_of_goverment = feudal
	capital = 45
	ruler = { character = { type = 10 id = 281104 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 45 }
}
country = {
	tag = C046
	form_of_goverment = feudal
	capital = 46
	ruler = { character = { type = 10 id = 281002 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 46 }
}
country = {
	tag = C047
	form_of_goverment = feudal
	capital = 47
	ruler = { character = { type = 10 id = 281111 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 47 }
}
country = {
	tag = C049
	form_of_goverment = feudal
	capital = 49
	ruler = { character = { type = 10 id = 281526 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 49 }
}
country = {
	tag = C050
	form_of_goverment = feudal
	capital = 50
	ruler = { character = { type = 10 id = 281525 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 50 }
}
country = {
	tag = C053
	form_of_goverment = feudal
	capital = 53
	ruler = { character = { type = 10 id = 963 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 53 }
}
country = {
	tag = C054
	form_of_goverment = feudal
	capital = 54
	ruler = { character = { type = 10 id = 281524 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 54 }
}
country = {
	tag = C056
	form_of_goverment = ecclestical
	capital = 56
	ruler = { character = { type = 10 id = 281601 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 56 }
}
country = {
	tag = C060
	form_of_goverment = feudal
	capital = 60
	ruler = { character = { type = 10 id = 40508 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 60 }
}
country = {
	tag = C061
	form_of_goverment = feudal
	capital = 61
	ruler = { character = { type = 10 id = 170 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 61 }
}
country = {
	tag = C062
	form_of_goverment = feudal
	capital = 62
	ruler = { character = { type = 10 id = 444 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 62 }
}
country = {
	tag = C065
	form_of_goverment = feudal
	capital = 65
	ruler = { character = { type = 10 id = 40504 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 65 }
}
country = {
	tag = C066
	form_of_goverment = feudal
	capital = 66
	ruler = { character = { type = 10 id = 90027 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 66 59 }
}
country = {
	tag = C067
	form_of_goverment = feudal
	capital = 67
	ruler = { character = { type = 10 id = 41009 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 67 }
}
country = {
	tag = C068
	form_of_goverment = feudal
	capital = 68
	ruler = { character = { type = 10 id = 198 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 68 }
}
country = {
	tag = C070
	form_of_goverment = feudal
	capital = 70
	ruler = { character = { type = 10 id = 5650 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 70 }
}
country = {
	tag = C071
	form_of_goverment = feudal
	capital = 71
	ruler = { character = { type = 10 id = 41011 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 71 }
}
country = {
	tag = C073
	form_of_goverment = feudal
	capital = 73
	ruler = { character = { type = 10 id = 148 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 73 }
}
country = {
	tag = C074
	form_of_goverment = feudal
	capital = 74
	ruler = { character = { type = 10 id = 40900 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 74 }
}
country = {
	tag = C075
	form_of_goverment = feudal
	capital = 75
	ruler = { character = { type = 10 id = 20142 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 75 }
}
country = {
	tag = C082
	form_of_goverment = ecclestical
	capital = 82
	ruler = { character = { type = 10 id = 106530 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 82 }
}
country = {
	tag = C083
	form_of_goverment = feudal
	capital = 83
	ruler = { character = { type = 10 id = 106540 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 83 }
}
country = {
	tag = C084
	form_of_goverment = feudal
	capital = 84
	ruler = { character = { type = 10 id = 106510 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 84 85 }
}
country = {
	tag = C086
	form_of_goverment = feudal
	capital = 86
	ruler = { character = { type = 10 id = 20223 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 86 }
}
country = {
	tag = C087
	form_of_goverment = ecclestical
	capital = 87
	ruler = { character = { type = 10 id = 20224 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 87 }
}
country = {
	tag = C088
	form_of_goverment = ecclestical
	capital = 88
	ruler = { character = { type = 10 id = 20218 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 88 }
}
country = {
	tag = C090
	form_of_goverment = feudal
	capital = 90
	ruler = { character = { type = 10 id = 20253 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 90 }
}
country = {
	tag = C091
	form_of_goverment = feudal
	capital = 91
	ruler = { character = { type = 10 id = 106570 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 91 }
}
country = {
	tag = C094
	form_of_goverment = feudal
	capital = 94
	ruler = { character = { type = 10 id = 106643 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 94 }
}
country = {
	tag = C095
	form_of_goverment = feudal
	capital = 95
	ruler = { character = { type = 10 id = 40406 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 95 98 }
}
country = {
	tag = C096
	form_of_goverment = feudal
	capital = 96
	ruler = { character = { type = 10 id = 6820 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 96 }
}
country = {
	tag = C099
	form_of_goverment = feudal
	capital = 99
	ruler = { character = { type = 10 id = 20112 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 99 }
}
country = {
	tag = C100
	form_of_goverment = feudal
	capital = 100
	ruler = { character = { type = 10 id = 41250 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 100 }
}
country = {
	tag = C102
	form_of_goverment = feudal
	capital = 102
	ruler = { character = { type = 10 id = 346 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 102 }
}
country = {
	tag = C103
	form_of_goverment = feudal
	capital = 103
	ruler = { character = { type = 10 id = 10059 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 103 }
}
country = { #BRIT
	tag = C104
	form_of_goverment = feudal
	capital = 104
	ruler = { character = { type = 10 id = 178 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 104 106 }
}
country = {
	tag = C105
	form_of_goverment = feudal
	capital = 105
	ruler = { character = { type = 10 id = 40908 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 105 }
}
country = {
	tag = C108
	form_of_goverment = feudal
	capital = 108
	ruler = { character = { type = 10 id = 142 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 108 }
}
country = {
	tag = C109
	form_of_goverment = feudal
	capital = 109
	ruler = { character = { type = 10 id = 40376 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 109 }
}
country = {
	tag = C111
	form_of_goverment = feudal
	capital = 111
	ruler = { character = { type = 10 id = 90061 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 111 }
}
country = {
	tag = C113
	form_of_goverment = feudal
	capital = 113
	ruler = { character = { type = 10 id = 418 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 113 }
}
country = {
	tag = C114
	form_of_goverment = ecclestical
	capital = 114
	ruler = { character = { type = 10 id = 20132 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 114 }
}
country = {
	tag = C116
	form_of_goverment = ecclestical
	capital = 116
	ruler = { character = { type = 10 id = 106610 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 116 }
}
country = {
	tag = C117
	form_of_goverment = feudal
	capital = 117
	ruler = { character = { type = 10 id = 106600 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 117 }
}
country = {
	tag = C119
	form_of_goverment = ecclestical
	capital = 119
	ruler = { character = { type = 10 id = 20228 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 119 }
}
country = {
	tag = C123
	form_of_goverment = ecclestical
	capital = 123
	ruler = { character = { type = 10 id = 20256 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 123 }
}
country = {
	tag = C124
	form_of_goverment = feudal
	capital = 124
	ruler = { character = { type = 10 id = 20217 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 124 }
}
country = {
	tag = C125
	form_of_goverment = feudal
	capital = 125
	ruler = { character = { type = 10 id = 20237 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 125 }
}
country = {
	tag = C126 
	form_of_goverment = feudal 
	capital = 126 
	ruler = { character = { type = 10 id = 1342 } startdate = { year = 1066 month = december day = 25 } } 
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes } 
	controlledprovinces = { 126 } 
}
country = {
	tag = C128
	form_of_goverment = feudal
	capital = 128
	ruler = { character = { type = 10 id = 20249 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 128 }
}
country = {
	tag = C129
	form_of_goverment = feudal
	capital = 129
	ruler = { character = { type = 10 id = 11000 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 129 134 }
}
country = {
	tag = C131
	form_of_goverment = feudal
	capital = 131
	ruler = { character = { type = 10 id = 40444 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 131 }
}

country = {
	tag = C135
	form_of_goverment = feudal
	capital = 135
	ruler = { character = { type = 10 id = 280 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 135 }
}
country = {
	tag = C137
	form_of_goverment = feudal
	capital = 137
	ruler = { character = { type = 10 id = 20176 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 137 132 }
}
country = {
	tag = C139
	form_of_goverment = ecclestical
	capital = 139
	ruler = { character = { type = 10 id = 40168 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 139 }
}
country = {
	tag = C140
	form_of_goverment = feudal
	capital = 140
	ruler = { character = { type = 10 id = 380 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 140 }
}
country = {
	tag = C142
	form_of_goverment = feudal
	capital = 142
	ruler = { character = { type = 10 id = 40026 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 142 }
}
country = {
	tag = C144
	form_of_goverment = feudal
	capital = 144
	ruler = { character = { type = 10 id = 40054 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 144 }
}
country = {
	tag = C145
	form_of_goverment = feudal
	capital = 145
	ruler = { character = { type = 10 id = 324 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 145 }
}
country = {
	tag = C146
	form_of_goverment = feudal
	capital = 146
	ruler = { character = { type = 10 id = 40160 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 146 }
}
country = {
	tag = C147
	form_of_goverment = feudal
	capital = 147
	ruler = { character = { type = 10 id = 40300 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 147 }
}
country = {
	tag = C148
	form_of_goverment = feudal
	capital = 148
	ruler = { character = { type = 10 id = 40102 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 148 }
}
country = {
	tag = C150
	form_of_goverment = feudal
	capital = 150
	ruler = { character = { type = 10 id = 40541 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 150 }
}
country = {
	tag = C151
	form_of_goverment = feudal
	capital = 151
	ruler = { character = { type = 10 id = 40902 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 151 }
}
country = {
	tag = C153
	form_of_goverment = feudal
	capital = 153
	ruler = { character = { type = 10 id = 107520 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 153 }
}
country = {
	tag = C154
	form_of_goverment = feudal
	capital = 154
	ruler = { character = { type = 10 id = 107560 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 154 }
}
country = {
	tag = C155
	form_of_goverment = feudal
	capital = 155
	ruler = { character = { type = 10 id = 108510 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 155 }
}
country = {
	tag = C156
	form_of_goverment = feudal
	capital = 156
	ruler = { character = { type = 10 id = 85026 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 156 }
}
country = {
	tag = C158 
	form_of_goverment = feudal 
	capital = 158 
	ruler = { character = { type = 10 id = 109607 } startdate = { year = 1066 month = december day = 25 } } 
	laws = { semisalic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes } 
	controlledprovinces = { 158 } 
}
country = {
	tag = C159
	form_of_goverment = feudal
	capital = 159
	ruler = { character = { type = 10 id = 109610 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 159 }
}
country = {
	tag = C160
	form_of_goverment = feudal
	capital = 160
	ruler = { character = { type = 10 id = 20897 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 160 }
}
country = {
	tag = C161
	form_of_goverment = feudal
	capital = 161
	ruler = { character = { type = 10 id = 20896 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 161 }
}
country = {
	tag = C162
	form_of_goverment = feudal
	capital = 162
	ruler = { character = { type = 10 id = 20890 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 162 }
}
country = {
	tag = C163
	form_of_goverment = feudal
	capital = 163
	ruler = { character = { type = 10 id = 20889 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 163 }
}
country = {
	tag = C164
	form_of_goverment = feudal
	capital = 164
	ruler = { character = { type = 10 id = 20888 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 164 }
}
country = {
	tag = C166
	form_of_goverment = feudal
	capital = 166
	ruler = { character = { type = 10 id = 20882 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 166 }
}

country = {
	tag = C174
	form_of_goverment = feudal
	capital = 174
	ruler = { character = { type = 10 id = 20883 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 174 }
}
country = {
	tag = C175
	form_of_goverment = feudal
	capital = 175
	ruler = { character = { type = 10 id = 3938 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 175 }
}
country = {
	tag = C176
	form_of_goverment = feudal
	capital = 176
	ruler = { character = { type = 10 id = 20855 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 176 }
}
country = {
	tag = C177
	form_of_goverment = feudal
	capital = 177
	ruler = { character = { type = 10 id = 20856 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 177 }
}
country = {
	tag = C185
	form_of_goverment = feudal
	capital = 185
	ruler = { character = { type = 10 id = 20894 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 185 }
}
country = {
	tag = C186
	form_of_goverment = feudal
	capital = 186
	ruler = { character = { type = 10 id = 20895 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 186 }
}
country = {
	tag = C188
	form_of_goverment = feudal
	capital = 188
	ruler = { character = { type = 10 id = 109628 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 188 }
}
country = {
	tag = C189
	form_of_goverment = feudal
	capital = 189
	ruler = { character = { type = 10 id = 108515 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 189 }
}
country = {
	tag = C191
	form_of_goverment = feudal
	capital = 191
	ruler = { character = { type = 10 id = 108501 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 191 }
}
country = {
	tag = C193
	form_of_goverment = feudal
	capital = 193
	ruler = { character = { type = 10 id = 20898 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 193 }
}
country = {
	tag = C194
	form_of_goverment = feudal
	capital = 194
	ruler = { character = { type = 10 id = 20858 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 194 }
}
country = {
	tag = C198
	form_of_goverment = feudal
	capital = 198
	ruler = { character = { type = 10 id = 107640 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 198 }
}
country = {
	tag = C201
	form_of_goverment = feudal
	capital = 201
	ruler = { character = { type = 10 id = 106011 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 201 }
}
country = {
	tag = C205
	form_of_goverment = feudal
	capital = 205
	ruler = { character = { type = 10 id = 110580 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 205 }
}
country = {
	tag = C206
	form_of_goverment = feudal
	capital = 206
	ruler = { character = { type = 10 id = 110550 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 206 }
}
country = {
	tag = C208
	form_of_goverment = feudal
	capital = 208
	ruler = { character = { type = 10 id = 40003 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 208 }
}
country = {
	tag = C209
	form_of_goverment = feudal
	capital = 209
	ruler = { character = { type = 10 id = 40014 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 209 }
}
country = {
	tag = C210
	form_of_goverment = feudal
	capital = 210
	ruler = { character = { type = 10 id = 6620 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 210 }
}
country = {
	tag = C211
	form_of_goverment = feudal
	capital = 211
	ruler = { character = { type = 10 id = 110610 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 211 }
}
country = {
	tag = C212
	form_of_goverment = feudal
	capital = 212
	ruler = { character = { type = 10 id = 40212 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 212 }
}
country = {
	tag = C213
	form_of_goverment = feudal
	capital = 213
	ruler = { character = { type = 10 id = 40204 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 213 220 }
}
country = {
	tag = C216
	form_of_goverment = feudal
	capital = 216
	ruler = { character = { type = 10 id = 40074 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 216 }
}
country = {
	tag = C217
	form_of_goverment = feudal
	capital = 217
	ruler = { character = { type = 10 id = 306 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 217 }
}
country = {
	tag = C218
	form_of_goverment = feudal
	capital = 218
	ruler = { character = { type = 10 id = 338 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 218 }
}
country = {
	tag = C219
	form_of_goverment = feudal
	capital = 219
	ruler = { character = { type = 10 id = 10034 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 219 }
}
country = {
	tag = C222
	form_of_goverment = feudal
	capital = 222
	ruler = { character = { type = 10 id = 20283 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 222 }
}
country = {
	tag = C223
	form_of_goverment = ecclestical
	capital = 223
	ruler = { character = { type = 10 id = 20291 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 223 }
}
country = {
	tag = C224
	form_of_goverment = feudal
	capital = 224
	ruler = { character = { type = 10 id = 20290 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 224 227 }
}
country = {
	tag = C225
	form_of_goverment = feudal
	capital = 225
	ruler = { character = { type = 10 id = 288 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 225 }
}
country = {
	tag = C228
	form_of_goverment = feudal
	capital = 228
	ruler = { character = { type = 10 id = 40464 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 228 }
}
country = {
	tag = C229
	form_of_goverment = feudal
	capital = 229
	ruler = { character = { type = 10 id = 40802 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 229 }
}
country = {
	tag = C230
	form_of_goverment = ecclestical
	capital = 230
	ruler = { character = { type = 10 id = 20315 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 230 }
}
country = {
	tag = C231
	form_of_goverment = feudal
	capital = 231
	ruler = { character = { type = 10 id = 7735 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 231 }
}
country = {
	tag = C232
	form_of_goverment = feudal
	capital = 232
	ruler = { character = { type = 10 id = 7730 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 232 }
}
country = {
	tag = C237
	form_of_goverment = feudal
	capital = 237
	ruler = { character = { type = 10 id = 1182 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 237 236 }
}
country = {
	tag = C238
	form_of_goverment = ecclestical
	capital = 238
	ruler = { character = { type = 10 id = 20284 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 238 }
}
country = {
	tag = C239
	form_of_goverment = feudal
	capital = 239
	ruler = { character = { type = 10 id = 20292 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 239 }
}
country = {
	tag = C240
	form_of_goverment = feudal
	capital = 240
	ruler = { character = { type = 10 id = 40364 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 240 }
}
country = {
	tag = C241
	form_of_goverment = feudal
	capital = 241
	ruler = { character = { type = 10 id = 20288 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 241 }
}
country = {
	tag = C242
	form_of_goverment = feudal
	capital = 242
	ruler = { character = { type = 10 id = 20289 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 242 }
}
country = {
	tag = C244
	form_of_goverment = feudal
	capital = 244
	ruler = { character = { type = 10 id = 20287 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 244 }
}
country = {
	tag = C245
	form_of_goverment = feudal
	capital = 245
	ruler = { character = { type = 10 id = 20286 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 245 }
}
country = {
	tag = C246
	form_of_goverment = feudal
	capital = 246
	ruler = { character = { type = 10 id = 20299 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 246 }
}
country = {
	tag = C247
	form_of_goverment = ecclestical
	capital = 247
	ruler = { character = { type = 10 id = 20247 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 247 }
}
country = {
	tag = C249
	form_of_goverment = feudal
	capital = 249
	ruler = { character = { type = 10 id = 40550 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 249 }
}
country = {
	tag = C251
	form_of_goverment = feudal
	capital = 251
	ruler = { character = { type = 10 id = 7054 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 251 }
}
country = {
	tag = C256
	form_of_goverment = feudal
	capital = 256
	ruler = { character = { type = 10 id = 20235 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 256 }
}
country = {
	tag = C262
	form_of_goverment = feudal
	capital = 262
	ruler = { character = { type = 10 id = 8400 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 262 }
}
country = {
	tag = C266
	form_of_goverment = feudal
	capital = 266
	ruler = { character = { type = 10 id = 101540 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 266 }
}
country = {
	tag = C267
	form_of_goverment = feudal
	capital = 267
	ruler = { character = { type = 10 id = 101541 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 267 }
}
country = {
	tag = C268
	form_of_goverment = feudal
	capital = 268
	ruler = { character = { type = 10 id = 20016 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 268 }
}
country = {
	tag = C269
	form_of_goverment = feudal
	capital = 269
	ruler = { character = { type = 10 id = 102567 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 269 }
}
country = {
	tag = C270
	form_of_goverment = feudal
	capital = 270
	ruler = { character = { type = 10 id = 20017 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 270 }
}
country = {
	tag = C274
	form_of_goverment = ecclestical
	capital = 274
	ruler = { character = { type = 10 id = 102563 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 274 }
}
country = {
	tag = C275
	form_of_goverment = feudal
	capital = 275
	ruler = { character = { type = 10 id = 102553 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 275 }
}
country = {
	tag = C276
	form_of_goverment = feudal
	capital = 276
	ruler = { character = { type = 10 id = 102547 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 276 }
}
country = {
	tag = C280
	form_of_goverment = feudal
	capital = 280
	ruler = { character = { type = 10 id = 20015 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 280 }
}
country = {
	tag = C281
	form_of_goverment = feudal
	capital = 281
	ruler = { character = { type = 10 id = 20014 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 281 }
}
country = {
	tag = C282
	form_of_goverment = republican
	capital = 282
	ruler = { character = { type = 10 id = 102575 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes popular_law = yes ecclesical_balance = yes }
	controlledprovinces = { 282 }
}
country = {
	tag = C283
	form_of_goverment = feudal
	capital = 283
	ruler = { character = { type = 10 id = 20013 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 283 }
}
country = {
	tag = C284
	form_of_goverment = feudal
	capital = 284
	ruler = { character = { type = 10 id = 20019 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 284 }
}
country = {
	tag = C285
	form_of_goverment = feudal
	capital = 285
	ruler = { character = { type = 10 id = 100527 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 285 }
}
country = {
	tag = C286
	form_of_goverment = feudal
	capital = 286
	ruler = { character = { type = 10 id = 100544 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 286 }
}
country = {
	tag = C287
	form_of_goverment = feudal
	capital = 287
	ruler = { character = { type = 10 id = 20005 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 287 }
}
country = {
	tag = C288
	form_of_goverment = feudal
	capital = 288
	ruler = { character = { type = 10 id = 102523 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 288 }
}
country = {
	tag = C289
	form_of_goverment = feudal
	capital = 289
	ruler = { character = { type = 10 id = 100546 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 289 }
}
country = {
	tag = C291
	form_of_goverment = feudal
	capital = 291
	ruler = { character = { type = 10 id = 20006 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 291 }
}
country = {
	tag = C294
	form_of_goverment = feudal
	capital = 294
	ruler = { character = { type = 10 id = 20009 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 294 }
}
country = {
	tag = C295
	form_of_goverment = feudal
	capital = 295
	ruler = { character = { type = 10 id = 20008 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 295 }
}
country = {
	tag = C298
	form_of_goverment = feudal
	capital = 298
	ruler = { character = { type = 10 id = 20010 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 298 }
}
country = {
	tag = C299
	form_of_goverment = feudal
	capital = 299
	ruler = { character = { type = 10 id = 20012 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 299 }
}
country = {
	tag = C300
	form_of_goverment = feudal
	capital = 300
	ruler = { character = { type = 10 id = 20007 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 300 }
}
country = {
	tag = C301
	form_of_goverment = republican
	capital = 301
	ruler = { character = { type = 10 id = 100532 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 301 }
}
country = {
	tag = C304
	form_of_goverment = feudal
	capital = 304
	ruler = { character = { type = 10 id = 8420 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 304 }
}
country = {
	tag = C305
	form_of_goverment = feudal
	capital = 305
	ruler = { character = { type = 10 id = 101546 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 305 }
}
country = {
	tag = C308
	form_of_goverment = feudal
	capital = 308
	ruler = { character = { type = 10 id = 20625 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 308 }
}
country = {
	tag = C309
	form_of_goverment = ecclestical
	capital = 309
	ruler = { character = { type = 10 id = 20263 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 309 }
}
country = {
	tag = C310
	form_of_goverment = feudal
	capital = 310
	ruler = { character = { type = 10 id = 20262 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 310 }
}
country = {
	tag = C311
	form_of_goverment = feudal
	capital = 311
	ruler = { character = { type = 10 id = 20266 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 311 }
}
country = {
	tag = C313
	form_of_goverment = ecclestical
	capital = 313
	ruler = { character = { type = 10 id = 20239 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 313 }
}
country = {
	tag = C314
	form_of_goverment = feudal
	capital = 314
	ruler = { character = { type = 10 id = 20258 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 314 }
}
country = {
	tag = C316
	form_of_goverment = feudal
	capital = 316
	ruler = { character = { type = 10 id = 1614 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 316 }
}
country = {
	tag = C317
	form_of_goverment = ecclestical
	capital = 317
	ruler = { character = { type = 10 id = 20312 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 317 }
}
country = {
	tag = C320
	form_of_goverment = ecclestical
	capital = 320
	ruler = { character = { type = 10 id = 20305 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 320 }
}
country = {
	tag = C321
	form_of_goverment = ecclestical
	capital = 321
	ruler = { character = { type = 10 id = 2009 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 321 }
}
country = {
	tag = C323
	form_of_goverment = ecclestical
	capital = 323
	ruler = { character = { type = 10 id = 2022 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 323 }
}
country = {
	tag = C324
	form_of_goverment = feudal
	capital = 324
	ruler = { character = { type = 10 id = 20324 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 324 }
}
country = {
	tag = C325
	form_of_goverment = feudal
	capital = 325
	ruler = { character = { type = 10 id = 20325 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 325 }
}
country = {
	tag = C326
	form_of_goverment = feudal
	capital = 326
	ruler = { character = { type = 10 id = 20326 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 326 }
}
country = {
	tag = C328
	form_of_goverment = ecclestical
	capital = 328
	ruler = { character = { type = 10 id = 2006 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 328 }
}
country = {
	tag = C329
	form_of_goverment = feudal
	capital = 329
	ruler = { character = { type = 10 id = 20331 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 329 }
}
country = {
	tag = C330
	form_of_goverment = ecclestical
	capital = 330
	ruler = { character = { type = 10 id = 20321 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 330 }
}
country = {
	tag = C331
	form_of_goverment = ecclestical
	capital = 331
	ruler = { character = { type = 10 id = 20320 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 331 }
}
country = {
	tag = C332
	form_of_goverment = ecclestical
	capital = 332
	ruler = { character = { type = 10 id = 2010 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 332 }
}
country = {
	tag = C335
	form_of_goverment = feudal
	capital = 335
	ruler = { character = { type = 10 id = 1130 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes feudal_contract_law = yes church_supremacy = yes }
	controlledprovinces = { 335 }
}
country = {
	tag = C336
	form_of_goverment = feudal
	capital = 336
	ruler = { character = { type = 10 id = 1119 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 336 }
}
country = {
	tag = C338
	form_of_goverment = feudal
	capital = 338
	ruler = { character = { type = 10 id = 1132 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 338 339 }
}
country = {
	tag = C340
	form_of_goverment = feudal
	capital = 340
	ruler = { character = { type = 10 id = 20832 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 340 342 }
}
country = {
	tag = C341
	form_of_goverment = feudal
	capital = 341
	ruler = { character = { type = 10 id = 20831 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 341 }
}
country = {
	tag = C343
	form_of_goverment = feudal
	capital = 343
	ruler = { character = { type = 10 id = 20829 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 343 }
}
country = {
	tag = C344
	form_of_goverment = feudal
	capital = 344
	ruler = { character = { type = 10 id = 1134 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes feudal_contract_law = yes church_supremacy = yes }
	controlledprovinces = { 344 }
}
country = {
	tag = C345
	form_of_goverment = feudal
	capital = 345
	ruler = { character = { type = 10 id = 19111155 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes feudal_contract_law = yes church_supremacy = yes }
	controlledprovinces = { 345 }
}
country = {
	tag = C348
	form_of_goverment = feudal
	capital = 348
	ruler = { character = { type = 10 id = 85003 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes feudal_contract_law = yes church_supremacy = yes }
	controlledprovinces = { 348 }
}
country = {
	tag = C350
	form_of_goverment = feudal
	capital = 350
	ruler = { character = { type = 10 id = 20332 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 350 }
}
country = {
	tag = C352
	form_of_goverment = republican
	capital = 352
	ruler = { character = { type = 10 id = 20335 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 352 }
}
country = {
	tag = C355
	form_of_goverment = ecclestical
	capital = 355
	ruler = { character = { type = 10 id = 20307 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 355 }
}
country = {
	tag = C357
	form_of_goverment = republican
	capital = 357
	ruler = { character = { type = 10 id = 20352 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 357 }
}
country = {
	tag = C358
	form_of_goverment = ecclestical
	capital = 358
	ruler = { character = { type = 10 id = 7700 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 358 }
}
country = {
	tag = C359
	form_of_goverment = feudal
	capital = 359
	ruler = { character = { type = 10 id = 40717 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 359 }
}
country = {
	tag = C361
	form_of_goverment = feudal
	capital = 361
	ruler = { character = { type = 10 id = 20257 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 361 }
}
country = {
	tag = C364
	form_of_goverment = feudal
	capital = 364
	ruler = { character = { type = 10 id = 20265 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 364 }
}
country = {
	tag = C368
	form_of_goverment = feudal
	capital = 368
	ruler = { character = { type = 10 id = 20626 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 368 }
}
country = {
	tag = C371
	form_of_goverment = feudal 
	capital = 371 
	ruler = { character = { type = 10 id = 28016 } startdate = { year = 1066 month = december day = 25 } } 
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes } 
	controlledprovinces = { 371 }
}
country = {
	tag = C374
	form_of_goverment = feudal
	capital = 374
	ruler = { character = { type = 10 id = 20603 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 374 }
}
country = {
	tag = C376
	form_of_goverment = feudal
	capital = 376
	ruler = { character = { type = 10 id = 28021 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 376 }
}
country = {
	tag = C379
	form_of_goverment = feudal
	capital = 379
	ruler = { character = { type = 10 id = 28025 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 379 }
}
country = {
	tag = C390
	form_of_goverment = feudal
	capital = 390
	ruler = { character = { type = 10 id = 28005 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 390 }
}
country = {
	tag = C408
	form_of_goverment = feudal
	capital = 408
	ruler = { character = { type = 10 id = 20419 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 408 }
}
country = {
	tag = C413
	form_of_goverment = feudal
	capital = 413
	ruler = { character = { type = 10 id = 20446 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 413 }
}
country = {
	tag = C414
	form_of_goverment = feudal
	capital = 414
	ruler = { character = { type = 10 id = 20445 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 414 }
}
country = {
	tag = C417
	form_of_goverment = feudal
	capital = 417
	ruler = { character = { type = 10 id = 20449 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 417 }
}
country = {
	tag = C418
	form_of_goverment = feudal
	capital = 418
	ruler = { character = { type = 10 id = 20468 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 418 }
}
country = {
	tag = C421
	form_of_goverment = feudal
	capital = 421
	ruler = { character = { type = 10 id = 28022 } startdate = { year = 1066 month = december day = 25 } } 
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes } 

	controlledprovinces = { 421 }
}
country = {
	tag = C425
	form_of_goverment = feudal
	capital = 425
	ruler = { character = { type = 10 id = 20460 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 425 }
}
country = {
	tag = C427
	form_of_goverment = feudal
	capital = 427
	ruler = { character = { type = 10 id = 28019 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 427 }
}
country = {
	tag = C430
	form_of_goverment = feudal
	capital = 430
	ruler = { character = { type = 10 id = 20390 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 430 }
}
country = {
	tag = C434
	form_of_goverment = feudal
	capital = 434
	ruler = { character = { type = 10 id = 20396 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 434 435 433 }
}
country = {
	tag = C438
	form_of_goverment = feudal
	capital = 438
	ruler = { character = { type = 10 id = 526 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 438 }
}
country = {
	tag = C440
	form_of_goverment = feudal
	capital = 440
	ruler = { character = { type = 10 id = 524 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 440 }
}
country = {
	tag = C441
	form_of_goverment = ecclestical
	capital = 441
	ruler = { character = { type = 10 id = 535 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 441 }
}
country = {
	tag = C443
	form_of_goverment = feudal
	capital = 443
	ruler = { character = { type = 10 id = 20369 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 443 }
}
country = {
	tag = C447
	form_of_goverment = feudal
	capital = 447
	ruler = { character = { type = 10 id = 20260 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 447 }
}
country = {
	tag = C448
	form_of_goverment = ecclestical
	capital = 448
	ruler = { character = { type = 10 id = 20259 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 448 }
}
country = {
	tag = C451
	form_of_goverment = feudal
	capital = 451
	ruler = { character = { type = 10 id = 20356 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 451 }
}
country = {
	tag = C452
	form_of_goverment = feudal
	capital = 452
	ruler = { character = { type = 10 id = 20362 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 452 }
}
country = {
	tag = C453
	form_of_goverment = feudal
	capital = 453
	ruler = { character = { type = 10 id = 20360 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 453 }
}
country = {
	tag = C454
	form_of_goverment = feudal
	capital = 454
	ruler = { character = { type = 10 id = 1621 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 454 }
}
country = {
	tag = C455
	form_of_goverment = feudal
	capital = 455
	ruler = { character = { type = 10 id = 1620 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 455 }
}
country = {
	tag = C457
	form_of_goverment = feudal
	capital = 457
	ruler = { character = { type = 10 id = 1616 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 457 458 }
}
country = {
	tag = C459
	form_of_goverment = feudal
	capital = 459
	ruler = { character = { type = 10 id = 20380 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 459 }
}
country = {
	tag = C463
	form_of_goverment = feudal
	capital = 463
	ruler = { character = { type = 10 id = 20381 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 463 }
}
country = {
	tag = C466
	form_of_goverment = feudal
	capital = 466
	ruler = { character = { type = 10 id = 20382 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 466 }
}
country = {
	tag = C468
	form_of_goverment = republican
	capital = 468
	ruler = { character = { type = 10 id = 20497 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes popular_law = yes ecclesical_balance = yes }
	controlledprovinces = { 468 }
}
country = {
	tag = C471
	form_of_goverment = ecclestical
	capital = 471
	ruler = { character = { type = 10 id = 20487 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 471 }
}
country = {
	tag = C472
	form_of_goverment = feudal
	capital = 472
	ruler = { character = { type = 10 id = 90093 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 472 }
}
country = {
	tag = C474
	form_of_goverment = feudal
	capital = 474
	ruler = { character = { type = 10 id = 42005 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 474 }
}
country = {
	tag = C475
	form_of_goverment = feudal
	capital = 475
	ruler = { character = { type = 10 id = 20509 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 475 }
}
country = {
	tag = C477
	form_of_goverment = feudal
	capital = 477
	ruler = { character = { type = 10 id = 20506 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 477 }
}
country = {
	tag = C478
	form_of_goverment = feudal
	capital = 478
	ruler = { character = { type = 10 id = 20505 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 478 }
}
country = {
	tag = C479
	form_of_goverment = feudal
	capital = 479
	ruler = { character = { type = 10 id = 20517 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 479 }
}
country = {
	tag = C481
	form_of_goverment = feudal
	capital = 481
	ruler = { character = { type = 10 id = 20504 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 481 }
}
country = {
	tag = C483
	form_of_goverment = feudal
	capital = 483
	ruler = { character = { type = 10 id = 20519 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 483 }
}
country = {
	tag = C484
	form_of_goverment = feudal
	capital = 484
	ruler = { character = { type = 10 id = 20514 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 484 }
}
country = {
	tag = C486
	form_of_goverment = feudal
	capital = 486
	ruler = { character = { type = 10 id = 42003 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 486 }
}
country = {
	tag = C487
	form_of_goverment = feudal
	capital = 487
	ruler = { character = { type = 10 id = 20515 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 487 }
}
country = {
	tag = C488
	form_of_goverment = ecclestical
	capital = 488
	ruler = { character = { type = 10 id = 20508 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes ecclesical_balance = yes }
	controlledprovinces = { 488 }
}
country = {
	tag = C489
	form_of_goverment = feudal
	capital = 489
	ruler = { character = { type = 10 id = 20510 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 489 }
}
country = {
	tag = C491
	form_of_goverment = ecclestical
	capital = 491
	ruler = { character = { type = 10 id = 20512 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 491 }
}
country = {
	tag = C492
	form_of_goverment = feudal
	capital = 492
	ruler = { character = { type = 10 id = 20484 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 492 }
}
country = {
	tag = C493
	form_of_goverment = feudal
	capital = 493
	ruler = { character = { type = 10 id = 20476 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 493 }
}
country = {
	tag = C495
	form_of_goverment = feudal
	capital = 495
	ruler = { character = { type = 10 id = 20475 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 495 }
}
country = {
	tag = C499
	form_of_goverment = feudal
	capital = 499
	ruler = { character = { type = 10 id = 20478 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 499 }
}
country = {
	tag = C501
	form_of_goverment = feudal
	capital = 501
	ruler = { character = { type = 10 id = 20486 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes ecclesical_balance = yes }
	controlledprovinces = { 501 }
}
country = {
	tag = C502
	form_of_goverment = feudal
	capital = 502
	ruler = { character = { type = 10 id = 20529 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 502 503 }
}
country = {
	tag = C505
	form_of_goverment = feudal
	capital = 505
	ruler = { character = { type = 10 id = 20488 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 505 }
}
country = {
	tag = C507
	form_of_goverment = feudal
	capital = 507
	ruler = { character = { type = 10 id = 20485 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 507 }
}
country = {
	tag = C508
	form_of_goverment = feudal
	capital = 508
	ruler = { character = { type = 10 id = 20479 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 508 }
}
country = {
	tag = C509
	form_of_goverment = feudal
	capital = 509
	ruler = { character = { type = 10 id = 20480 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 509 }
}
country = {
	tag = C510
	form_of_goverment = feudal
	capital = 510
	ruler = { character = { type = 10 id = 20481 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 510 }
}
country = {
	tag = C511
	form_of_goverment = feudal
	capital = 511
	ruler = { character = { type = 10 id = 20482 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 511 }
}
country = {
	tag = C513
	form_of_goverment = feudal
	capital = 513
	ruler = { character = { type = 10 id = 20636 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 513 }
}
country = {
	tag = C514
	form_of_goverment = feudal
	capital = 514
	ruler = { character = { type = 10 id = 20637 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 514 }
}
country = {
	tag = C515
	form_of_goverment = feudal
	capital = 515
	ruler = { character = { type = 10 id = 20638 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 515 }
}
country = {
	tag = C516
	form_of_goverment = feudal
	capital = 516
	ruler = { character = { type = 10 id = 20639 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 516 }
}
country = {
	tag = C517
	form_of_goverment = feudal
	capital = 517
	ruler = { character = { type = 10 id = 20364 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 517 }
}
country = {
	tag = C518
	form_of_goverment = feudal
	capital = 518
	ruler = { character = { type = 10 id = 20363 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 518 }
}
country = {
	tag = C519
	form_of_goverment = feudal
	capital = 519
	ruler = { character = { type = 10 id = 20365 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 519 }
}
country = {
	tag = C520
	form_of_goverment = feudal
	capital = 520
	ruler = { character = { type = 10 id = 474 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 520 }
}
country = {
	tag = C521
	form_of_goverment = ecclestical
	capital = 521
	ruler = { character = { type = 10 id = 20357 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 521 }
}
country = {
	tag = C522
	form_of_goverment = feudal
	capital = 522
	ruler = { character = { type = 10 id = 4435 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 522 }
}
country = {
	tag = C523
	form_of_goverment = feudal
	capital = 523
	ruler = { character = { type = 10 id = 20366 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 523 533 }
}
country = {
	tag = C524
	form_of_goverment = feudal
	capital = 524
	ruler = { character = { type = 10 id = 20367 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 524 }
}
country = {
	tag = C525
	form_of_goverment = feudal
	capital = 525
	ruler = { character = { type = 10 id = 20370 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 525 }
}
country = {
	tag = C530
	form_of_goverment = feudal
	capital = 530
	ruler = { character = { type = 10 id = 20395 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 530 }
}
country = {
	tag = C535
	form_of_goverment = feudal
	capital = 535
	ruler = { character = { type = 10 id = 20458 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 535 }
}
country = {
	tag = C537
	form_of_goverment = feudal
	capital = 537
	ruler = { character = { type = 10 id = 20373 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 537 }
}
country = {
	tag = C538
	form_of_goverment = feudal
	capital = 538
	ruler = { character = { type = 10 id = 20372 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 538 }
}
country = {
	tag = C541
	form_of_goverment = feudal
	capital = 541
	ruler = { character = { type = 10 id = 20640 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 541 }
}
country = {
	tag = C542
	form_of_goverment = feudal
	capital = 542
	ruler = { character = { type = 10 id = 20641 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 542 }
}
country = {
	tag = C543
	form_of_goverment = feudal
	capital = 543
	ruler = { character = { type = 10 id = 20642 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 543 }
}
country = {
	tag = C549
	form_of_goverment = feudal
	capital = 549
	ruler = { character = { type = 10 id = 20459 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 549 }
}
country = {
	tag = C551
	form_of_goverment = feudal
	capital = 551
	ruler = { character = { type = 10 id = 20448 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 551 }
}
country = {
	tag = C557
	form_of_goverment = feudal
	capital = 557
	ruler = { character = { type = 10 id = 20650 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 557 }
}
country = {
	tag = C558
	form_of_goverment = feudal
	capital = 558
	ruler = { character = { type = 10 id = 20646 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 558 }
}
country = {
	tag = C559
	form_of_goverment = feudal
	capital = 559
	ruler = { character = { type = 10 id = 20647 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 559 }
}
country = {
	tag = C565
	form_of_goverment = feudal
	capital = 565
	ruler = { character = { type = 10 id = 20648 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 565 556 }
}
country = {
	tag = C566
	form_of_goverment = feudal
	capital = 566
	ruler = { character = { type = 10 id = 20651 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 566 593 }
}
country = {
	tag = C570
	form_of_goverment = feudal
	capital = 570
	ruler = { character = { type = 10 id = 20423 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 570 }
}
country = {
	tag = C571
	form_of_goverment = feudal
	capital = 571
	ruler = { character = { type = 10 id = 20420 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 571 }
}
country = {
	tag = C572
	form_of_goverment = feudal
	capital = 572
	ruler = { character = { type = 10 id = 20421 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 572 }
}
country = {
	tag = C574
	form_of_goverment = feudal
	capital = 574
	ruler = { character = { type = 10 id = 666 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 574 573 }
}
country = {
	tag = C577
	form_of_goverment = feudal
	capital = 577
	ruler = { character = { type = 10 id = 20453 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 577 }
}
country = {
	tag = C579
	form_of_goverment = feudal
	capital = 579
	ruler = { character = { type = 10 id = 20629 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 579 }
}
country = {
	tag = C583
	form_of_goverment = feudal
	capital = 583
	ruler = { character = { type = 10 id = 20416 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 583 }
}
country = {
	tag = C587
	form_of_goverment = feudal
	capital = 587
	ruler = { character = { type = 10 id = 20450 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 587 }
}
country = {
	tag = C588
	form_of_goverment = feudal
	capital = 588
	ruler = { character = { type = 10 id = 20630 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 588 }
}
country = {
	tag = C589
	form_of_goverment = feudal
	capital = 589
	ruler = { character = { type = 10 id = 20631 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 589 }
}
country = {
	tag = C590
	form_of_goverment = feudal
	capital = 590
	ruler = { character = { type = 10 id = 20632 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 590 }
}
country = {
	tag = C591
	form_of_goverment = feudal
	capital = 591
	ruler = { character = { type = 10 id = 20633 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 591 }
}
country = {
	tag = C597
	form_of_goverment = feudal
	capital = 597
	ruler = { character = { type = 10 id = 20656 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 597 }
}
country = {
	tag = C598
	form_of_goverment = feudal
	capital = 598
	ruler = { character = { type = 10 id = 654 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 598 562 }
}
country = {
	tag = C599
	form_of_goverment = feudal
	capital = 599
	ruler = { character = { type = 10 id = 20657 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 599 }
}
country = {
	tag = C602
	form_of_goverment = feudal
	capital = 602
	ruler = { character = { type = 10 id = 20664 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 602 }
}
country = {
	tag = C605
	form_of_goverment = feudal
	capital = 605
	ruler = { character = { type = 10 id = 20665 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 605 }
}
country = {
	tag = C606
	form_of_goverment = feudal
	capital = 606
	ruler = { character = { type = 10 id = 20666 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 606 }
}
country = {
	tag = C607
	form_of_goverment = feudal
	capital = 607
	ruler = { character = { type = 10 id = 20658 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 607 }
}
country = {
	tag = C629
	form_of_goverment = feudal
	capital = 629
	ruler = { character = { type = 10 id = 20702 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 629 }
}
country = {
	tag = C630
	form_of_goverment = feudal
	capital = 630
	ruler = { character = { type = 10 id = 20700 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 630 }
}
country = {
	tag = C631
	form_of_goverment = feudal
	capital = 631
	ruler = { character = { type = 10 id = 20701 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 631 }
}
country = {
	tag = C633
	form_of_goverment = feudal
	capital = 633
	ruler = { character = { type = 10 id = 20699 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 633 }
}
country = {
	tag = C634
	form_of_goverment = feudal
	capital = 634
	ruler = { character = { type = 10 id = 20698 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 634 }
}
country = {
	tag = C640
	form_of_goverment = feudal
	capital = 640
	ruler = { character = { type = 10 id = 20710 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 640 }
}
country = {
	tag = C641
	form_of_goverment = feudal
	capital = 641
	ruler = { character = { type = 10 id = 20711 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 641 }
}
country = {
	tag = C642
	form_of_goverment = feudal
	capital = 642
	ruler = { character = { type = 10 id = 20712 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 642 }
}
country = {
	tag = C643
	form_of_goverment = feudal
	capital = 643
	ruler = { character = { type = 10 id = 3854 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 643 }
}
country = {
	tag = C649
	form_of_goverment = feudal
	capital = 649
	ruler = { character = { type = 10 id = 20670 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 649 }
}
country = {
	tag = C656
	form_of_goverment = feudal
	capital = 656
	ruler = { character = { type = 10 id = 3814 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 656 }
}
country = {
	tag = C660
	form_of_goverment = feudal
	capital = 660
	ruler = { character = { type = 10 id = 20697 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 660 }
}
country = {
	tag = C661
	form_of_goverment = feudal
	capital = 661
	ruler = { character = { type = 10 id = 20704 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 661 }
}
country = {
	tag = C664
	form_of_goverment = feudal
	capital = 664
	ruler = { character = { type = 10 id = 20690 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 664 }
}
country = {
	tag = C666
	form_of_goverment = feudal
	capital = 666
	ruler = { character = { type = 10 id = 20716 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 666 665 }
}
country = {
	tag = C671
	form_of_goverment = feudal
	capital = 671
	ruler = { character = { type = 10 id = 41557 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 671 }
}
country = {
	tag = C673
	form_of_goverment = feudal
	capital = 673
	ruler = { character = { type = 10 id = 41600 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 673 672 }
}
country = {
	tag = C676
	form_of_goverment = feudal
	capital = 676
	ruler = { character = { type = 10 id = 41515 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 676 }
}
country = {
	tag = C679
	form_of_goverment = feudal
	capital = 679
	ruler = { character = { type = 10 id = 41607 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 679 }
}
country = {
	tag = C681
	form_of_goverment = feudal
	capital = 681
	ruler = { character = { type = 10 id = 41513 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 681 }
}
country = {
	tag = C684
	form_of_goverment = feudal
	capital = 684
	ruler = { character = { type = 10 id = 20719 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 684 }
}
country = {
	tag = C685
	form_of_goverment = feudal
	capital = 685
	ruler = { character = { type = 10 id = 20718 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 685 }
}
country = {
	tag = C686
	form_of_goverment = feudal
	capital = 686
	ruler = { character = { type = 10 id = 20717 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 686 }
}
country = {
	tag = C687
	form_of_goverment = feudal
	capital = 687
	ruler = { character = { type = 10 id = 20676 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 687 }
}
country = {
	tag = C688
	form_of_goverment = feudal
	capital = 688
	ruler = { character = { type = 10 id = 20677 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 688 }
}
country = {
	tag = C689
	form_of_goverment = feudal
	capital = 689
	ruler = { character = { type = 10 id = 20678 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 689 }
}
country = {
	tag = C690
	form_of_goverment = feudal
	capital = 690
	ruler = { character = { type = 10 id = 20671 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 690 }
}
country = {
	tag = C691
	form_of_goverment = feudal
	capital = 691
	ruler = { character = { type = 10 id = 20672 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 691 }
}
country = {
	tag = C692
	form_of_goverment = feudal
	capital = 692
	ruler = { character = { type = 10 id = 20673 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 692 }
}
country = {
	tag = C695
	form_of_goverment = feudal
	capital = 695
	ruler = { character = { type = 10 id = 20727 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 695 }
}
country = {
	tag = C698
	form_of_goverment = feudal
	capital = 698
	ruler = { character = { type = 10 id = 20732 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 698 }
}
country = {
	tag = C701
	form_of_goverment = feudal
	capital = 701
	ruler = { character = { type = 10 id = 7241 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 701 }
}
country = {
	tag = C703
	form_of_goverment = feudal
	capital = 703
	ruler = { character = { type = 10 id = 85010 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 703 }
}
country = {
	tag = C704
	form_of_goverment = feudal
	capital = 704
	ruler = { character = { type = 10 id = 7242 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 704 }
}
country = {
	tag = C706
	form_of_goverment = feudal
	capital = 706
	ruler = { character = { type = 10 id = 20553 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 706 }
}
country = {
	tag = C707
	form_of_goverment = feudal
	capital = 707
	ruler = { character = { type = 10 id = 20562 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 707 }
}
country = {
	tag = C708
	form_of_goverment = feudal
	capital = 708
	ruler = { character = { type = 10 id = 20740 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 708 }
}
country = {
	tag = C709
	form_of_goverment = feudal
	capital = 709
	ruler = { character = { type = 10 id = 20739 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 709 }
}
country = {
	tag = C710
	form_of_goverment = feudal
	capital = 710
	ruler = { character = { type = 10 id = 20731 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 710 }
}
country = {
	tag = C711
	form_of_goverment = feudal
	capital = 711
	ruler = { character = { type = 10 id = 20729 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 711 }
}
country = {
	tag = C712
	form_of_goverment = feudal
	capital = 712
	ruler = { character = { type = 10 id = 20728 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 712 }
}
country = {
	tag = C713
	form_of_goverment = feudal
	capital = 713
	ruler = { character = { type = 10 id = 20761 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 713 }
}
country = {
	tag = C714
	form_of_goverment = feudal
	capital = 714
	ruler = { character = { type = 10 id = 20675 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 714 }
}
country = {
	tag = C715
	form_of_goverment = feudal
	capital = 715
	ruler = { character = { type = 10 id = 20674 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 715 }
}
country = {
	tag = C716
	form_of_goverment = feudal
	capital = 716
	ruler = { character = { type = 10 id = 20796 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 716 }
}
country = {
	tag = C717
	form_of_goverment = feudal
	capital = 717
	ruler = { character = { type = 10 id = 20795 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 717 }
}
country = {
	tag = C720
	form_of_goverment = feudal
	capital = 720
	ruler = { character = { type = 10 id = 20793 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 720 }
}
country = {
	tag = C721
	form_of_goverment = feudal
	capital = 721
	ruler = { character = { type = 10 id = 20794 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 721 }
}
country = {
	tag = C722
	form_of_goverment = feudal
	capital = 722
	ruler = { character = { type = 10 id = 20762 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 722 }
}
country = {
	tag = C723
	form_of_goverment = feudal
	capital = 723
	ruler = { character = { type = 10 id = 20763 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 723 }
}
country = {
	tag = C725
	form_of_goverment = feudal
	capital = 725
	ruler = { character = { type = 10 id = 20765 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 725 }
}
country = {
	tag = C726
	form_of_goverment = feudal
	capital = 726
	ruler = { character = { type = 10 id = 20766 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 726 }
}
country = {
	tag = C727
	form_of_goverment = feudal
	capital = 727
	ruler = { character = { type = 10 id = 20767 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 727 }
}
country = {
	tag = C729
	form_of_goverment = feudal
	capital = 729
	ruler = { character = { type = 10 id = 20730 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 729 }
}
country = {
	tag = C731
	form_of_goverment = feudal
	capital = 731
	ruler = { character = { type = 10 id = 20746 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 731 }
}
country = {
	tag = C732
	form_of_goverment = feudal
	capital = 732
	ruler = { character = { type = 10 id = 20745 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 732 }
}
country = {
	tag = C734
	form_of_goverment = feudal
	capital = 734
	ruler = { character = { type = 10 id = 20741 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 734 }
}
country = {
	tag = C737
	form_of_goverment = feudal
	capital = 737
	ruler = { character = { type = 10 id = 41578 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 737 }
}
country = {
	tag = C738
	form_of_goverment = feudal
	capital = 738
	ruler = { character = { type = 10 id = 1756 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 738 }
}
country = {
	tag = C740
	form_of_goverment = feudal
	capital = 740
	ruler = { character = { type = 10 id = 20537 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 740 }
}
country = {
	tag = C741
	form_of_goverment = feudal
	capital = 741
	ruler = { character = { type = 10 id = 1746 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 741 }
}
country = {
	tag = C743
	form_of_goverment = ecclestical
	capital = 743
	ruler = { character = { type = 10 id = 20528 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes ecclesical_balance = yes }
	controlledprovinces = { 743 }
}
country = {
	tag = C744
	form_of_goverment = feudal
	capital = 744
	ruler = { character = { type = 10 id = 20524 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 744 }
}
country = {
	tag = C749
	form_of_goverment = feudal
	capital = 749
	ruler = { character = { type = 10 id = 20532 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 749 }
}
country = {
	tag = C750
	form_of_goverment = feudal
	capital = 750
	ruler = { character = { type = 10 id = 20530 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 750 }
}
country = {
	tag = C754
	form_of_goverment = feudal
	capital = 754
	ruler = { character = { type = 10 id = 20526 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 754 }
}
country = {
	tag = C755
	form_of_goverment = feudal
	capital = 755
	ruler = { character = { type = 10 id = 20520 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 755 }
}
country = {
	tag = C756
	form_of_goverment = feudal
	capital = 756
	ruler = { character = { type = 10 id = 20564 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 756 }
}
country = {
	tag = C758
	form_of_goverment = feudal
	capital = 758
	ruler = { character = { type = 10 id = 41589 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 758 }
}
country = {
	tag = C760
	form_of_goverment = feudal
	capital = 760
	ruler = { character = { type = 10 id = 20534 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 760 }
}
country = {
	tag = C761
	form_of_goverment = feudal
	capital = 761
	ruler = { character = { type = 10 id = 41568 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 761 }
}
country = {
	tag = C764
	form_of_goverment = feudal
	capital = 764
	ruler = { character = { type = 10 id = 1758 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 764  763}
}
country = {
	tag = C765
	form_of_goverment = feudal
	capital = 765
	ruler = { character = { type = 10 id = 20747 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 765 }
}
country = {
	tag = C766
	form_of_goverment = feudal
	capital = 766
	ruler = { character = { type = 10 id = 20561 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 766 }
}
country = {
	tag = C768
	form_of_goverment = feudal
	capital = 768
	ruler = { character = { type = 10 id = 20770 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 768 }
}
country = {
	tag = C769
	form_of_goverment = feudal
	capital = 769
	ruler = { character = { type = 10 id = 20771 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 769 }
}
country = {
	tag = C770
	form_of_goverment = feudal
	capital = 770
	ruler = { character = { type = 10 id = 20772 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 770 }
}
country = {
	tag = C771
	form_of_goverment = feudal
	capital = 771
	ruler = { character = { type = 10 id = 20773 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 771 }
}
country = {
	tag = C772
	form_of_goverment = feudal
	capital = 772
	ruler = { character = { type = 10 id = 20774 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 772 }
}
country = {
	tag = C773
	form_of_goverment = feudal
	capital = 773
	ruler = { character = { type = 10 id = 20775 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 773 }
}
country = {
	tag = C775
	form_of_goverment = feudal
	capital = 775
	ruler = { character = { type = 10 id = 20777 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 775 }
}
country = {
	tag = C776
	form_of_goverment = feudal
	capital = 776
	ruler = { character = { type = 10 id = 20778 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 776 }
}
country = {
	tag = C777
	form_of_goverment = feudal
	capital = 777
	ruler = { character = { type = 10 id = 20779 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 777 }
}
country = {
	tag = C778
	form_of_goverment = feudal
	capital = 778
	ruler = { character = { type = 10 id = 20780 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 778 }
}
country = {
	tag = C779
	form_of_goverment = feudal
	capital = 779
	ruler = { character = { type = 10 id = 20781 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 779 }
}
country = {
	tag = C780
	form_of_goverment = feudal
	capital = 780
	ruler = { character = { type = 10 id = 20782 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 780 }
}
country = {
	tag = C781
	form_of_goverment = feudal
	capital = 781
	ruler = { character = { type = 10 id = 20783 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 781 }
}
country = {
	tag = C782
	form_of_goverment = feudal
	capital = 782
	ruler = { character = { type = 10 id = 20784 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 782 }
}
country = {
	tag = C783
	form_of_goverment = feudal
	capital = 783
	ruler = { character = { type = 10 id = 20785 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 783 }
}
country = {
	tag = C784
	form_of_goverment = feudal
	capital = 784
	ruler = { character = { type = 10 id = 20786 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 784 }
}
country = {
	tag = C785
	form_of_goverment = feudal
	capital = 785
	ruler = { character = { type = 10 id = 20787 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 785 }
}
country = {
	tag = C786
	form_of_goverment = feudal
	capital = 786
	ruler = { character = { type = 10 id = 20788 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 786 }
}
country = {
	tag = C788
	form_of_goverment = feudal
	capital = 788
	ruler = { character = { type = 10 id = 20790 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 788 }
}
country = {
	tag = C803
	form_of_goverment = feudal
	capital = 803
	ruler = { character = { type = 10 id = 20800 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 803 }
}
country = {
	tag = C804
	form_of_goverment = feudal
	capital = 804
	ruler = { character = { type = 10 id = 20799 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 804 }
}
country = {
	tag = C805
	form_of_goverment = feudal
	capital = 805
	ruler = { character = { type = 10 id = 20801 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 805 }
}
country = {
	tag = C806
	form_of_goverment = feudal
	capital = 806
	ruler = { character = { type = 10 id = 20802 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 806 }
}
country = {
	tag = C807
	form_of_goverment = feudal
	capital = 807
	ruler = { character = { type = 10 id = 20803 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 807 }
}
country = {
	tag = C809
	form_of_goverment = feudal
	capital = 809
	ruler = { character = { type = 10 id = 20804 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 809 }
}
country = {
	tag = C810
	form_of_goverment = feudal
	capital = 810
	ruler = { character = { type = 10 id = 20806 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 810 }
}
country = {
	tag = C811
	form_of_goverment = feudal
	capital = 811
	ruler = { character = { type = 10 id = 20805 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 811 }
}
country = {
	tag = C812
	form_of_goverment = feudal
	capital = 812
	ruler = { character = { type = 10 id = 20828 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 812 }
}
country = {
	tag = C813
	form_of_goverment = feudal
	capital = 813
	ruler = { character = { type = 10 id = 20807 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 813 }
}
country = {
	tag = C814
	form_of_goverment = feudal
	capital = 814
	ruler = { character = { type = 10 id = 20808 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 814 }
}
country = {
	tag = C818
	form_of_goverment = feudal
	capital = 818
	ruler = { character = { type = 10 id = 20811 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 818 }
}
country = {
	tag = C820
	form_of_goverment = feudal
	capital = 820
	ruler = { character = { type = 10 id = 20816 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 820 }
}
country = {
	tag = C821
	form_of_goverment = feudal
	capital = 821
	ruler = { character = { type = 10 id = 20815 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 821 }
}
country = {
	tag = C823
	form_of_goverment = feudal
	capital = 823
	ruler = { character = { type = 10 id = 20814 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 823 }
}
country = {
	tag = C826
	form_of_goverment = feudal
	capital = 826
	ruler = { character = { type = 10 id = 20871 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 826 }
}
country = {
	tag = C827
	form_of_goverment = feudal
	capital = 827
	ruler = { character = { type = 10 id = 20870 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 827 }
}
country = {
	tag = C828
	form_of_goverment = feudal
	capital = 828
	ruler = { character = { type = 10 id = 20838 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 828 }
}
country = {
	tag = C829
	form_of_goverment = feudal
	capital = 829
	ruler = { character = { type = 10 id = 20837 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 829 }
}
country = {
	tag = C830
	form_of_goverment = feudal
	capital = 830
	ruler = { character = { type = 10 id = 20836 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 830 }
}
country = {
	tag = C832
	form_of_goverment = feudal
	capital = 832
	ruler = { character = { type = 10 id = 20840 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 832 }
}
country = {
	tag = C833
	form_of_goverment = feudal
	capital = 833
	ruler = { character = { type = 10 id = 20819 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 833 }
}
country = {
	tag = C834
	form_of_goverment = feudal
	capital = 834
	ruler = { character = { type = 10 id = 20822 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 834 }
}
country = {
	tag = C835
	form_of_goverment = feudal
	capital = 835
	ruler = { character = { type = 10 id = 20820 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 835 }
}
country = {
	tag = C836
	form_of_goverment = feudal
	capital = 836
	ruler = { character = { type = 10 id = 20821 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 836 }
}
country = {
	tag = C838
	form_of_goverment = feudal
	capital = 838
	ruler = { character = { type = 10 id = 20823 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 838 }
}

country = {
	tag = C842
	form_of_goverment = feudal
	capital = 842
	ruler = { character = { type = 10 id = 20849 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 842 }
}
country = {
	tag = C844
	form_of_goverment = feudal
	capital = 844
	ruler = { character = { type = 10 id = 3852 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 844 }
}
country = {
	tag = C848
	form_of_goverment = feudal
	capital = 848
	ruler = { character = { type = 10 id = 20842 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 848 }
}
country = {
	tag = C898
	form_of_goverment = feudal
	capital = 898
	ruler = { character = { type = 10 id = 20330 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 898 }
}
country = {
	tag = C995
	form_of_goverment = ecclestical
	capital = 995
	ruler = { character = { type = 10 id = 20251 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 995 261 }
}
country = {
	tag = C997
	form_of_goverment = feudal
	capital = 997
	ruler = { character = { type = 10 id = 1152 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 997 }
}
country = {
	tag = ADRI
	form_of_goverment = feudal
	capital = 494
	tier = duchy 
	ruler = { character = { type = 10 id = 1736 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 494 }
}
country = {
	tag = AEGE
	form_of_goverment = feudal
	capital = 485
	tier = duchy 
	ruler = { character = { type = 10 id = 20513 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 485 }
}
country = {
	tag = ALAN
	form_of_goverment = feudal
	capital = 603
	tier = duchy 
	ruler = { character = { type = 10 id = 20662 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 603 604 }
}
country = {
	tag = ALME
	form_of_goverment = feudal
	capital = 168
	tier = duchy 
	ruler = { character = { type = 10 id = 20876 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 168 }
}
country = {
	tag = ANJO
	form_of_goverment = feudal
	capital = 107
	tier = duchy 
	ruler = { character = { type = 10 id = 378 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 107 }
}
country = {
	tag = ANTI
	form_of_goverment = feudal
	capital = 735
	tier = duchy 
	ruler = { character = { type = 10 id = 20559 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 735 }
}
country = {
	tag = APUL
	form_of_goverment = feudal
	capital = 347
	tier = duchy 
	ruler = { character = { type = 10 id = 1128 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 347 337 346 }
}
country = {
	tag = ARME
	form_of_goverment = ecclestical
	capital = 682
	tier = duchy 
	ruler = { character = { type = 10 id = 41585 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 682 }
}
country = {
	tag = ARMI
	form_of_goverment = feudal
	capital = 736
	tier = duchy 
	ruler = { character = { type = 10 id = 20554 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 736 762 }
}
country = {
	tag = AZER
	form_of_goverment = feudal
	capital = 670
	tier = duchy 
	ruler = { character = { type = 10 id = 20722 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 670 667 }
}
country = {
	tag = AZOV
	form_of_goverment = feudal
	capital = 596
	tier = duchy 
	ruler = { character = { type = 10 id = 20655 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 596 }
}
country = {
	tag = BADA
	form_of_goverment = feudal
	capital = 195
	tier = duchy 
	ruler = { character = { type = 10 id = 3900 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 195 184 }
}
country = {
	tag = BAVA
	form_of_goverment = feudal
	capital = 315
	tier = duchy 
	ruler = { character = { type = 10 id = 112600 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 315 360 }
}
country = {
	tag = BELG
	form_of_goverment = feudal
	capital = 469
	tier = duchy 
	ruler = { character = { type = 10 id = 20491 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 469 }
}
country = {
	tag = BJAR
	form_of_goverment = feudal
	capital = 394
	tier = duchy 
	ruler = { character = { type = 10 id = 20620 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 394 395 396 403 }
}
country = {
	tag = DBOH
	form_of_goverment = feudal
	capital = 437
	tier = duchy 
	ruler = { character = { type = 10 id = 522 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 437 439 363 436 362 }
}
country = {
	tag = BORD
	form_of_goverment = feudal
	capital = 149
	tier = duchy 
	ruler = { character = { type = 10 id = 240 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 141 143 149 215 }
}
country = {
	tag = BOUG
	form_of_goverment = feudal
	capital = 136
	tier = duchy 
	ruler = { character = { type = 10 id = 210 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 136 226 }
}

country = {
	tag = BRAN
	form_of_goverment = feudal
	capital = 365
	tier = duchy 
	ruler = { character = { type = 10 id = 7032 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 365 }
}
country = {
	tag = BRIT
	form_of_goverment = feudal
	capital = 101
	tier = duchy
	ruler = { character = { type = 10 id = 347 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 101 }
}
country = {
	tag = BUTR
	form_of_goverment = feudal
	capital = 473
	tier = duchy 
	ruler = { character = { type = 10 id = 1764 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 473 }
}
country = {
	tag = CAMP
	form_of_goverment = feudal
	capital = 334
	tier = duchy 
	ruler = { character = { type = 10 id = 20498 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 334 }
}
country = {
	tag = CATA
	form_of_goverment = feudal
	capital = 204
	tier = duchy 
	ruler = { character = { type = 10 id = 110520 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 204 }
}
country = {
	tag = CHAL
	form_of_goverment = feudal
	capital = 705
	tier = duchy 
	ruler = { character = { type = 10 id = 20552 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 705 }
}
country = {
	tag = CHAM
	form_of_goverment = feudal
	capital = 130
	tier = duchy 
	ruler = { character = { type = 10 id = 394 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 130 110 }
}
country = {
	tag = CHER
	form_of_goverment = feudal
	capital = 560
	tier = duchy 
	ruler = { character = { type = 10 id = 20463 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 560 561 }
}
country = {
	tag = CONN
	form_of_goverment = feudal
	capital = 8
	tier = duchy 
	ruler = { character = { type = 10 id = 910 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 8 }
}
country = {
	tag = CORD
	form_of_goverment = republican
	capital = 181
	tier = duchy 
	ruler = { character = { type = 10 id = 20852 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 181 }
}
country = {
	tag = CUMB
	form_of_goverment = feudal
	capital = 57
	tier = duchy 
	ruler = { character = { type = 10 id = 5660 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 55 57 }
}
country = {
	tag = CYPR
	form_of_goverment = feudal
	capital = 757
	tier = duchy 
	ruler = { character = { type = 10 id = 20563 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 757 }
}
country = {
	tag = CYRE
	form_of_goverment = feudal
	capital = 808
	tier = duchy 
	ruler = { character = { type = 10 id = 20798 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 808 }
}
country = {
	tag = DEHE
	form_of_goverment = feudal
	capital = 18
	tier = duchy 
	ruler = { character = { type = 10 id = 81814 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 18 }
}
country = {
	tag = DONA
	form_of_goverment = feudal
	capital = 594
	tier = duchy 
	ruler = { character = { type = 10 id = 20653 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 594 595 }
}
country = {
	tag = DORO
	form_of_goverment = feudal
	capital = 500
	tier = duchy 
	ruler = { character = { type = 10 id = 1740 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 500 }
}
country = {
	tag = DYRR
	form_of_goverment = feudal
	capital = 470
	tier = duchy 
	ruler = { character = { type = 10 id = 20499 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 470 }
}
country = {
	tag = ESFA
	form_of_goverment = feudal
	capital = 638
	tier = duchy 
	ruler = { character = { type = 10 id = 20705 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 638 636 }
}
country = {
	tag = FESA
	form_of_goverment = feudal
	capital = 840
	tier = duchy 
	ruler = { character = { type = 10 id = 20850 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 840 }
}
country = {
	tag = FINL
	form_of_goverment = feudal
	capital = 382
	tier = duchy
	ruler = { character = { type = 10 id = 20612 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 382 }
}
country = {
	tag = FLAN
	form_of_goverment = feudal
	capital = 78
	tier = duchy 
	ruler = { character = { type = 10 id = 364 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 78 76 77 93 }
}
country = {
	tag = GALA
	form_of_goverment = ecclestical
	capital = 752
	tier = duchy 
	ruler = { character = { type = 10 id = 20536 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes ecclesical_balance = yes }
	controlledprovinces = { 752 }
}
country = {
	tag = GALC
	form_of_goverment = feudal
	capital = 157
	tier = duchy 
	ruler = { character = { type = 10 id = 109500 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 157 187 }
}
country = {
	tag = GENO
	form_of_goverment = republican
	capital = 233
	tier = duchy 
	ruler = { character = { type = 10 id = 20314 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 233 }
}

country = { 
	tag = DGEO 
	form_of_goverment = feudal 
	capital = 680 
	tier = duchy 
	ruler = { character = { type = 10 id = 85012 } startdate = { year = 1066 month = december day = 25 } } 
	laws = { semisalic_primogeniture_law = yes royal_preorgatory_law = yes regal_supremacy = yes } 
	controlledprovinces = { 680 } 
}
country = {
	tag = GWYN
	form_of_goverment = feudal
	capital = 64
	tier = duchy 
	ruler = { character = { type = 10 id = 6358 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 64 }
}
country = {
	tag = HAIN
	form_of_goverment = feudal
	capital = 80
	tier = duchy 
	ruler = { character = { type = 10 id = 106520 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 79 80 81 }
}
country = {
	tag = HELL
	form_of_goverment = feudal
	capital = 482
	tier = duchy 
	ruler = { character = { type = 10 id = 20507 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 482 }
}
country = {
	tag = HORM
	form_of_goverment = feudal
	capital = 639
	tier = duchy 
	ruler = { character = { type = 10 id = 3041 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 639 }
}
country = {
	tag = ICEL
	form_of_goverment = republican
	capital = 2
	tier = duchy 
	ruler = { character = { type = 10 id = 20579 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes popular_law = yes ecclesical_balance = yes }
	controlledprovinces = { 2 }
}
country = {
	tag = IKON
	form_of_goverment = feudal
	capital = 759
	tier = duchy 
	ruler = { character = { type = 10 id = 1734 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 759 }
}
country = {
	tag = KARE
	form_of_goverment = feudal
	capital = 388
	tier = duchy 
	ruler = { character = { type = 10 id = 28004 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 388 393 }
}
country = {
	tag = KIEV
	form_of_goverment = feudal
	capital = 547
	tier = duchy 
	ruler = { character = { type = 10 id = 626 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 547 536 534 544 545 546 548 552 553 }
}
country = {
	tag = KRET
	form_of_goverment = feudal
	capital = 480
	tier = duchy 
	ruler = { character = { type = 10 id = 20516 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 480 }
}
country = {
	tag = KARN
	form_of_goverment = feudal
	capital = 456
	tier = duchy 
	ruler = { character = { type = 10 id = 1610 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 456 250 319 }
}
country = {
	tag = LANC
	form_of_goverment = feudal
	capital = 58
	tier = duchy 
	ruler = { character = { type = 10 id = 5644 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 58 63 }
}
country = {
	tag = LANG
	form_of_goverment = republican
	capital = 327
	tier = duchy 
	ruler = { character = { type = 10 id = 20323 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 327 }
}
country = {
	tag = LAOD
	form_of_goverment = feudal
	capital = 748
	tier = duchy 
	ruler = { character = { type = 10 id = 20525 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 748 }
}
country = {
	tag = LEIN
	form_of_goverment = feudal
	capital = 16
	tier = duchy 
	ruler = { character = { type = 10 id = 922 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 16 }
}
country = {
	tag = LIVO
	form_of_goverment = feudal
	capital = 377
	tier = duchy 
	ruler = { character = { type = 10 id = 28023 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 377 }
}
country = {
	tag = LOTH 
	form_of_goverment = feudal 
	capital = 51 
	tier = duchy 
	ruler = { character = { type = 10 id = 85018 } startdate = { year = 1066 month = december day = 25 } } 
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes } 
	controlledprovinces = { 48 51 52 } 
}
country = {
	tag = LOLO
	form_of_goverment = feudal
	capital = 118
	tier = duchy 
	ruler = { character = { type = 10 id = 11030 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 118 92 }
}

country = {
	tag = LURI
	form_of_goverment = feudal
	capital = 657
	tier = duchy 
	ruler = { character = { type = 10 id = 20691 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 657 }
}
country = {
	tag = LUTA
	form_of_goverment = feudal
	capital = 632
	tier = duchy 
	ruler = { character = { type = 10 id = 20688 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 632 }
}
country = {
	tag = LUXE
	form_of_goverment = feudal
	capital = 115
	tier = duchy 
	ruler = { character = { type = 10 id = 106650 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 115 }
}
country = {
	tag = LYKI
	form_of_goverment = feudal
	capital = 747
	tier = duchy 
	ruler = { character = { type = 10 id = 20518 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 747 }
}
country = {
	tag = MARA
	form_of_goverment = feudal
	capital = 40
	tier = duchy 
	ruler = { character = { type = 10 id = 6008 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 40 39 38 }
}
country = {
	tag = MAZO
	form_of_goverment = feudal
	capital = 529
	tier = duchy 
	ruler = { character = { type = 10 id = 764 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 529 428 }
}
country = {
	tag = MECK
	form_of_goverment = feudal
	capital = 260
	tier = duchy 
	ruler = { character = { type = 10 id = 20584 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 260 306 307 }
}
country = {
	tag = MEIS
	form_of_goverment = feudal
	capital = 312
	tier = duchy 
	ruler = { character = { type = 10 id = 7060 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 312 }
}
country = {
	tag = DMES
	form_of_goverment = feudal
	capital = 702
	tier = duchy 
	ruler = { character = { type = 10 id = 85001 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes ecclesical_balance = yes }
	controlledprovinces = { 702 }
}
country = {
	tag = MILA
	form_of_goverment = feudal
	capital = 235
	tier = duchy 
	ruler = { character = { type = 10 id = 1118 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 235 234 }
}
country = {
	tag = MUNS
	form_of_goverment = feudal
	capital = 14
	tier = duchy 
	ruler = { character = { type = 10 id = 906 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 14 13 }
}
country = {
	tag = NIKA
	form_of_goverment = feudal
	capital = 742
	tier = duchy 
	ruler = { character = { type = 10 id = 20527 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 742 }
}
country = {
	tag = NIKO
	form_of_goverment = feudal
	capital = 753
	tier = duchy 
	ruler = { character = { type = 10 id = 1742 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 753 751 }
}
country = {
	tag = NOVG
	form_of_goverment = feudal
	capital = 410
	tier = duchy 
	ruler = { character = { type = 10 id = 686 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 410 404 405 406 409 412 415 }
}
country = {
	tag = ORKN
	form_of_goverment = feudal
	capital = 36
	tier = duchy 
	ruler = { character = { type = 10 id = 102538 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 36 }
}
country = {
	tag = ACHA
	form_of_goverment = feudal
	capital = 476
	tier = duchy 
	ruler = { character = { type = 10 id = 1766 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 476 }
}
country = {
	tag = PERE
	form_of_goverment = feudal
	capital = 555
	tier = duchy 
	ruler = { character = { type = 10 id = 630 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 555 407 568 569 582 585 586 }
}
country = {
	tag = POLO
	form_of_goverment = feudal
	capital = 419
	tier = duchy 
	ruler = { character = { type = 10 id = 650 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 419 424 416 550 }
}
country = {
	tag = POMM
	form_of_goverment = feudal
	capital = 366
	tier = duchy 
	ruler = { character = { type = 10 id = 20623 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 366 367 }
}
country = {
	tag = PRES
	form_of_goverment = ecclestical
	capital = 444
	tier = duchy 
	ruler = { character = { type = 10 id = 4431 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 444 }
}
country = {
	tag = PROV
	form_of_goverment = feudal
	capital = 221
	tier = duchy 
	ruler = { character = { type = 10 id = 420 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 221 }
}

country = {
	tag = ROMA
	form_of_goverment = ecclestical
	capital = 351
	tier = duchy 
	ruler = { character = { type = 10 id = 7740 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 351 }
}

country = {
	tag = SAND
	form_of_goverment = ecclestical
	capital = 528
	tier = duchy 
	ruler = { character = { type = 10 id = 20388 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 432 528 }
}
country = {
	tag = SAXO
	form_of_goverment = feudal
	capital = 120
	tier = duchy 
	ruler = { character = { type = 10 id = 1416 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 89 120 257 258 259 }
}
country = {
	tag = SEVI
	form_of_goverment = feudal
	capital = 182
	tier = duchy 
	ruler = { character = { type = 10 id = 3212 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 182 183 165 }
}
country = {
	tag = SINO
	form_of_goverment = feudal
	capital = 739
	tier = duchy 
	ruler = { character = { type = 10 id = 1752 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 739 }
}
country = {
	tag = SLOV
	form_of_goverment = feudal
	capital = 442
	tier = duchy 
	ruler = { character = { type = 10 id = 472 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 442 }
}
country = {
	tag = SUZD
	form_of_goverment = feudal
	capital = 554
	tier = duchy 
	ruler = { character = { type = 10 id = 628 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 554 567 }
}
country = {
	tag = SWAB
	form_of_goverment = feudal
	capital = 252
	tier = duchy 
	ruler = { character = { type = 10 id = 1388 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 252 248 253 }
}
country = {
	tag = TANG
	form_of_goverment = feudal 
	capital = 841 
	tier = duchy 
	ruler = { character = { type = 10 id = 20881 } startdate = { year = 1066 month = december day = 25 } } 
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes } 
	controlledprovinces = { 841 839 }
}
country = {
	tag = THUR
	form_of_goverment = feudal
	capital = 255
	tier = duchy 
	ruler = { character = { type = 10 id = 20234 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 255 }
}
country = {
	tag = TOSC
	form_of_goverment = feudal
	capital = 322
	tier = duchy 
	ruler = { character = { type = 10 id = 7757 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 318 322 353 354 349 }
}
country = {
	tag = TOUL
	form_of_goverment = feudal
	capital = 214
	tier = duchy 
	ruler = { character = { type = 10 id = 336 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 214 }
}
country = {
	tag = TRAP
	form_of_goverment = feudal
	capital = 678
	tier = duchy 
	ruler = { character = { type = 10 id = 20544 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 678 }
}
country = {
	tag = TRON
	form_of_goverment = feudal
	capital = 277
	tier = duchy 
	ruler = { character = { type = 10 id = 102532 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 277 278 }
}
country = {
	tag = UPLO
	form_of_goverment = feudal
	capital = 127
	tier = duchy 
	ruler = { character = { type = 10 id = 6642 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 127 133 }
}
country = {
	tag = UPPL
	form_of_goverment = feudal
	capital = 290
	tier = duchy 
	ruler = { character = { type = 10 id = 100516 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 290 292 }
}
country = {
	tag = URAL
	form_of_goverment = feudal
	capital = 610
	tier = duchy 
	ruler = { character = { type = 10 id = 3504 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 610 400 612 611 613 609 }
}

country = { 
	tag = VALE
	form_of_goverment = feudal 
	capital = 171 
	tier = duchy 
	ruler = { character = { type = 10 id = 3928 } startdate = { year = 1066 month = december day = 25 } } 
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes } 
	controlledprovinces = { 171 172 178 } 
}
country = {
	tag = VARN
	form_of_goverment = feudal
	capital = 498
	tier = duchy 
	ruler = { character = { type = 10 id = 85011 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 498 }
}

country = {
	tag = WEIS
	form_of_goverment = feudal
	capital = 35
	tier = duchy 
	ruler = { character = { type = 10 id = 5788 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 35 }
}
country = {
	tag = VIDI
	form_of_goverment = feudal
	capital = 506
	tier = duchy 
	ruler = { character = { type = 10 id = 20489 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 506 }
}
country = {
	tag = WIEL
	form_of_goverment = ecclestical
	capital = 429
	tier = duchy 
	ruler = { character = { type = 10 id = 20393 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 429 431 }
}
country = {
	tag = VOLG
	form_of_goverment = feudal
	capital = 616
	tier = duchy 
	ruler = { character = { type = 10 id = 20923 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 615 616 617 614 }
}
country = {
	tag = OSTE
	form_of_goverment = feudal
	capital = 449
	tier = duchy 
	ruler = { character = { type = 10 id = 7200 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 449 446 }
}
country = {
	tag = UGRI
	form_of_goverment = feudal
	capital = 202
	tier = duchy 
	ruler = { character = { type = 10 id = 3934 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 173 202 203 }
}
country = {
	tag = DERB
	form_of_goverment = feudal
	capital = 674
	tier = duchy 
	ruler = { character = { type = 10 id = 20734 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 674 675 668 669 }
}
country = {
	tag = TURK
	form_of_goverment = feudal
	capital = 625
	tier = duchy 
	ruler = { character = { type = 10 id = 3072 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 625 624 621 622 }
}
country = {
	tag = MURC
	form_of_goverment = feudal
	capital = 169
	tier = duchy 
	ruler = { character = { type = 10 id = 3910 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 169 }
}
country = {
	tag = SAMS
	form_of_goverment = feudal
	capital = 745
	tier = duchy 
	ruler = { character = { type = 10 id = 20511 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 745 746 }
}
country = {
	tag = SLAV
	form_of_goverment = feudal
	capital = 461
	tier = duchy 
	ruler = { character = { type = 10 id = 8628 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 461 460 462 }
}
country = {
	tag = SVIG
	form_of_goverment = feudal
	capital = 264
	tier = duchy 
	ruler = { character = { type = 10 id = 101517 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 264 263 }
}
country = {
	tag = TOLE
	form_of_goverment = feudal
	capital = 197
	tier = duchy 
	ruler = { character = { type = 10 id = 3924 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 197 196 }
}
country = {
	tag = OSTR
	form_of_goverment = feudal
	capital = 293
	tier = duchy 
	ruler = { character = { type = 10 id = 100530 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 293 }
}
country = {
	tag = ARAG
	form_of_goverment = feudal
	capital = 207
	tier = kingdom 
	ruler = { character = { type = 10 id = 110500 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 207 }
}
country = {
	tag = BYZA
	form_of_goverment = feudal
	capital = 496
	tier = kingdom 
	ruler = { character = { type = 10 id = 1732 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 497 490 496 }
}
country = {
	tag = CAST
	form_of_goverment = feudal
	capital = 199
	tier = kingdom 
	ruler = { character = { type = 10 id = 107500 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 199 200 }
}
country = {
	tag = CROA
	form_of_goverment = feudal
	capital = 464
	tier = kingdom 
	ruler = { character = { type = 10 id = 8622 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 464 465 467 504 }
}
country = {
	tag = CUMA
	form_of_goverment = feudal
	capital = 564
	tier = kingdom 
	ruler = { character = { type = 10 id = 806 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 564 563 608 618 619 }
}
country = {
	tag = DENM
	form_of_goverment = feudal
	capital = 265
	tier = kingdom 
	ruler = { character = { type = 10 id = 101515 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 265 303 302 }
}
country = {
	tag = ENGL
	form_of_goverment = feudal
	capital = 72
	tier = kingdom 
	ruler = { character = { type = 10 id = 140 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 72 22 23 26 27 32 69 97 }
}
country = {
	tag = FRAN
	form_of_goverment = feudal
	capital = 112
	tier = kingdom 
	ruler = { character = { type = 10 id = 214 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 112 138 }
}
country = {
	tag = GEOR
	form_of_goverment = feudal
	capital = 677
	tier = kingdom 
	ruler = { character = { type = 10 id = 9952 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 600 601 677 }
}
country = {
	tag = GERM
	form_of_goverment = feudal
	capital = 254
	tier = kingdom 
	ruler = { character = { type = 10 id = 1316 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 254 121 122 }
}
country = {
	tag = HUNG
	form_of_goverment = feudal
	capital = 445
	tier = kingdom 
	ruler = { character = { type = 10 id = 476 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 539 445 450 540 }
}
country = {
	tag = LEON
	form_of_goverment = feudal
	capital = 190
	tier = kingdom 
	ruler = { character = { type = 10 id = 108500 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes regal_supremacy = yes }
	controlledprovinces = { 190 192 }
}
country = {
	tag = NAVA
	form_of_goverment = feudal
	capital = 152
	tier = kingdom 
	ruler = { character = { type = 10 id = 106000 } startdate = { year = 1066 month = december day = 25 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 152 }
}
country = {
	tag = NORW
	form_of_goverment = feudal
	capital = 272
	tier = kingdom 
	ruler = { character = { type = 10 id = 102534 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 272 271 273 296 }
}
country = {
	tag = POLA
	form_of_goverment = feudal
	capital = 527
	tier = kingdom 
	ruler = { character = { type = 10 id = 762 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 527 526 531 532 }
}
country = {
	tag = SCOT
	form_of_goverment = feudal
	capital = 44
	tier = kingdom 
	ruler = { character = { type = 10 id = 984 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 44 43 }
}
country = {
	tag = SWED
	form_of_goverment = feudal
	capital = 297
	tier = kingdom 
	ruler = { character = { type = 10 id = 100525 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 297 }
}
country = {
	tag = PECH
	form_of_goverment = feudal
	capital = 512
	tier = kingdom 
	ruler = { character = { type = 10 id = 20635 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 512 }
}
country = {
	tag = MJER
	form_of_goverment = feudal
	capital = 774
	tier = duchy 
	ruler = { character = { type = 10 id = 20776 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 774 }
}
country = {
	tag = MAMM
	form_of_goverment = feudal
	capital = 724
	tier = duchy 
	ruler = { character = { type = 10 id = 20764 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 724 }
}
country = {
	tag = MTRI
	form_of_goverment = feudal
	capital = 767
	tier = duchy 
	ruler = { character = { type = 10 id = 20769 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 767 }
}
country = {
	tag = MDAM
	form_of_goverment = feudal
	capital = 728
	tier = duchy 
	ruler = { character = { type = 10 id = 20768 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 728 730 }
}
country = {
	tag = MELA
	form_of_goverment = feudal
	capital = 787
	tier = duchy 
	ruler = { character = { type = 10 id = 20789 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 787 }
}
country = {
	tag = MMOS
	form_of_goverment = feudal
	capital = 697
	tier = duchy 
	ruler = { character = { type = 10 id = 3822 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 697 696 }
}
country = {
	tag = MEDE
	form_of_goverment = feudal
	capital = 683
	tier = duchy 
	ruler = { character = { type = 10 id = 20738 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 683 699 700 }
}
country = {
	tag = MMED
	form_of_goverment = feudal
	capital = 718
	tier = duchy 
	ruler = { character = { type = 10 id = 3826 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 718 719 }
}
country = {
	tag = MKHW
	form_of_goverment = feudal
	capital = 623
	tier = duchy 
	ruler = { character = { type = 10 id = 20713 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 623 627 }
}
country = {
	tag = MALE
	form_of_goverment = feudal
	capital = 733
	tier = duchy 
	ruler = { character = { type = 10 id = 20743 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 733 }
}
country = {
	tag = MSIS
	form_of_goverment = feudal
	capital = 637
	tier = duchy 
	ruler = { character = { type = 10 id = 20707 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 637 635 }
}
country = {
	tag = MARB
	form_of_goverment = feudal
	capital = 651
	tier = duchy 
	ruler = { character = { type = 10 id = 20900 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 651 650 652 653 654 655 }
}
country = {
	tag = MMAZ
	form_of_goverment = feudal
	capital = 662
	tier = duchy 
	ruler = { character = { type = 10 id = 20703 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 662 }
}
country = {
	tag = PAPA
	form_of_goverment = ecclestical
	capital = 333
	tier = kingdom 
	ruler = { character = { type = 10 id = 2008 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 333 }
}

country = { 
	tag = VENI
	form_of_goverment = republican 
	capital = 356 
	tier = kingdom 
	ruler = { character = { type = 10 id = 7800 } startdate = { year = 1066 month = december day = 25 } } 
	laws = { elective_law = yes popular_law = yes church_supremacy = yes } 
	controlledprovinces = { 356 } 
}
country = {
	tag = ABBA
	form_of_goverment = feudal
	capital = 693
	tier = duchy 
	ruler = { character = { type = 10 id = 3084 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 693 694 }
}
country = {
	tag = QARA
	form_of_goverment = feudal
	capital = 626
	tier = kingdom 
	ruler = { character = { type = 10 id = 3014 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 626 628 }
}
country = {
	tag = HAMM
	form_of_goverment = feudal
	capital = 831
	tier = kingdom 
	ruler = { character = { type = 10 id = 20834 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 831 822 824 825 }
}
country = {
	tag = ZIRI
	form_of_goverment = feudal
	capital = 816
	tier = kingdom 
	ruler = { character = { type = 10 id = 20825 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 816 817 819 }
}
country = {
	tag = BALE
	form_of_goverment = feudal
	capital = 170
	tier = duchy 
	ruler = { character = { type = 10 id = 20869 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 170 179 }
}
country = {
	tag = ZENA
	form_of_goverment = feudal
	capital = 837
	tier = kingdom 
	ruler = { character = { type = 10 id = 20818 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 837 }
}
country = {
	tag = BENI
	form_of_goverment = feudal
	capital = 815
	tier = kingdom 
	ruler = { character = { type = 10 id = 20809 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 815 }
}
country = {
	tag = CURO
	form_of_goverment = feudal
	capital = 373
	tier = duchy 
	ruler = { character = { type = 10 id = 28075 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 373 372 }
}
country = {
	tag = ESTS
	form_of_goverment = feudal
	capital = 380
	tier = duchy 
	ruler = { character = { type = 10 id = 28026 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 380 378 }
}
country = {
	tag = GRAN
	form_of_goverment = feudal
	capital = 180
	tier = duchy 
	ruler = { character = { type = 10 id = 3210 } startdate = { year = 1066 month = december day = 25 } } 
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 180 167 } 
}
country = {
	tag = LETT
	form_of_goverment = feudal
	capital = 375
	tier = duchy 
	ruler = { character = { type = 10 id = 28020 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 375 }
}
country = {
	tag = PRUT
	form_of_goverment = feudal
	capital = 370
	tier = duchy 
	ruler = { character = { type = 10 id = 28015 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 370 369 }
}
country = {
	tag = SAME
	form_of_goverment = feudal
	capital = 397
	tier = duchy 
	ruler = { character = { type = 10 id = 20619 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 397 398 399 401 402 }
}
country = {
	tag = YATV
	form_of_goverment = feudal
	capital = 426
	tier = duchy 
	ruler = { character = { type = 10 id = 28017 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 426 422 423}
}
country = {
	tag = ESAM
	form_of_goverment = feudal
	capital = 386
	tier = duchy 
	ruler = { character = { type = 10 id = 20618 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 386 }
}
country = {
	tag = INGE
	form_of_goverment = feudal
	capital = 411
	tier = duchy 
	ruler = { character = { type = 10 id = 28007 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 411 }
}
country = {
	tag = KAJA
	form_of_goverment = feudal
	capital = 389
	tier = duchy 
	ruler = { character = { type = 10 id = 28010 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 389 385 }
}
country = {
	tag = KEXH
	form_of_goverment = feudal
	capital = 392
	tier = duchy 
	ruler = { character = { type = 10 id = 28035 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 392 }
}
country = {
	tag = KHAZ
	form_of_goverment = feudal
	capital = 620
	tier = duchy 
	ruler = { character = { type = 10 id = 20663 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 620 }
}
country = {
	tag = KOLA
	form_of_goverment = feudal
	capital = 387
	tier = duchy 
	ruler = { character = { type = 10 id = 28009 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 387 }
}
country = {
	tag = LITT
	form_of_goverment = feudal
	capital = 420
	tier = duchy 
	ruler = { character = { type = 10 id = 28012 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 420 }
}
country = {
	tag = MORD
	form_of_goverment = feudal
	capital = 592
	tier = duchy 
	ruler = { character = { type = 10 id = 20628 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 592 }
}
country = {
	tag = SATA
	form_of_goverment = feudal
	capital = 384
	tier = duchy 
	ruler = { character = { type = 10 id = 28011 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 384 }
}
country = {
	tag = TAVA
	form_of_goverment = feudal
	capital = 383
	tier = duchy 
	ruler = { character = { type = 10 id = 28003 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 383 381 }
}
country = {
	tag = VOTE
	form_of_goverment = feudal
	capital = 391
	tier = duchy 
	ruler = { character = { type = 10 id = 28006 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 391 }
}
country = {
	tag = WSAM
	form_of_goverment = feudal
	capital = 279
	tier = duchy 
	ruler = { character = { type = 10 id = 20617 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 279 }
}
country  = {
	tag = MINS 
	form_of_goverment = republican 
	capital = 575 
	tier = duchy 
	ruler = { character = { type = 10 id = 90149 } startdate = { year = 1066 month = december day = 25 } } 
	laws = { elective_law = yes popular_law = yes ecclesical_balance = yes } 
	controlledprovinces = { 584 575 576 578 580 581 } 
}
country = {
	tag = NUBI
	form_of_goverment = feudal
	capital = 793
	tier = kingdom 
	ruler = { character = { type = 10 id = 20572 } startdate = { year = 1066 month = december day = 25 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 793 792 794 }
}
country = {
	tag = MURA
	form_of_goverment = feudal
	capital = 843
	tier = kingdom 
	ruler = { character = { type = 10 id = 3853 } startdate = { year = 1066 month = december day = 25 } }
	laws = { elective_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 843 845 846 847 }
}
country = {
	tag = FATI
	form_of_goverment = feudal
	capital = 796
	tier = kingdom 
	ruler = { character = { type = 10 id = 3096 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 796 802 797 799 798 789 790 791 795 800 801 }
}
country = {
	tag = SELJ
	form_of_goverment = feudal
	capital = 658
	tier = kingdom 
	ruler = { character = { type = 10 id = 3040 } startdate = { year = 1066 month = december day = 25 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 658 644 645 646 647 648 659 663 }
}
