relations = {
	alliance = {
		primary = { type = 10 id = 23500 }
		secondary = { type = 10 id = 31000 }
		startdate = { year = 1186 month = december day = 27 }
	}
	alliance = {
		primary = { type = 10 id = 2971 }
		secondary = { type = 10 id = 3003 }
		startdate = { year = 1186 month = december day = 27 }
	}
	alliance = { #Bakt
		primary = { type = 10 id = 20572 }
		secondary = { type = 10 id = 26000 }
		startdate = { year = 1186 month = december day = 27 }
	}
	marrige = {
		primary = { type = 10 id = 9 }
		secondary = { type = 10 id = 2506 }
		startdate = { year = 1180 month = january day = 1 }
		enddate = { year = 1183 month = march day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 490 }
		secondary = { type = 10 id = 491 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 492 }
		secondary = { type = 10 id = 493 }
		startdate = { year = 1120 month = january day = 1 }
		enddate = { year = 1134 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 500 }
		secondary = { type = 10 id = 520 }
		startdate = { year = 1168 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 521 }
		secondary = { type = 10 id = 522 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1164 month = march day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 523 }
		secondary = { type = 10 id = 2513 }
		startdate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 540 }
		secondary = { type = 10 id = 542 }
		startdate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 600 }
		secondary = { type = 10 id = 601 }
		startdate = { year = 1134 month = january day = 1 }
		enddate = { year = 1148 month = march day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 600 }
		secondary = { type = 10 id = 21511 }
		startdate = { year = 1148 month = january day = 1 }
		enddate = { year = 1153 month = march day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 602 }
		secondary = { type = 10 id = 603 }
		startdate = { year = 1160 month = january day = 1 }
		enddate = { year = 1167 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 604 }
		secondary = { type = 10 id = 605 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 999 }
		secondary = { type = 10 id = 21702 }
		startdate = { year = 1148 month = january day = 1 }
		enddate = { year = 1172 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1001 }
		secondary = { type = 10 id = 12610 }
		startdate = { year = 1178 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1500 }
		secondary = { type = 10 id = 12571 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1510 }
		secondary = { type = 10 id = 22797 }
		startdate = { year = 1157 month = january day = 1 }
		enddate = { year = 1184 month = may day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 1513 }
		secondary = { type = 10 id = 22593 }
		startdate = { year = 1116 month = january day = 1 }
		enddate = { year = 1131 month = may day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 1517 }
		secondary = { type = 10 id = 22594 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1137 month = september day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 1518 }
		secondary = { type = 10 id = 12056 }
		startdate = { year = 1152 month = january day = 1 }
		enddate = { year = 1157 month = september day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 1521 }
		secondary = { type = 10 id = 2045 }
		startdate = { year = 1178 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1523 }
		secondary = { type = 10 id = 1524 }
		startdate = { year = 1127 month = january day = 1 }
		enddate = { year = 1167 month = june day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 1534 }
		secondary = { type = 10 id = 1535 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1186 month = june day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 1537 }
		secondary = { type = 10 id = 1544 }
		startdate = { year = 1167 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 2020 }
		secondary = { type = 10 id = 2023 }
		startdate = { year = 1164 month = january day = 1 }
		enddate = { year = 1183 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 2024 }
		secondary = { type = 10 id = 2025 }
		startdate = { year = 1140 month = january day = 1 }
		enddate = { year = 1166 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 2026 }
		secondary = { type = 10 id = 2027 }
		startdate = { year = 1120 month = january day = 1 }
		enddate = { year = 1133 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 2030 }
		secondary = { type = 10 id = 2031 }
		startdate = { year = 1180 month = january day = 1 }
		enddate = { year = 1183 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 2030 }
		secondary = { type = 10 id = 2506 }
		startdate = { year = 1184 month = january day = 1 }
		enddate = { year = 1185 month = november day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 2030 }
		secondary = { type = 10 id = 2033 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 2040 }
		secondary = { type = 10 id = 2041 }
		startdate = { year = 1140 month = january day = 1 }
		enddate = { year = 1148 month = april day = 23 }
	}
	marrige = {
		primary = { type = 10 id = 2040 }
		secondary = { type = 10 id = 2042 }
		startdate = { year = 1148 month = april day = 24 }
		enddate = { year = 1150 month = april day = 23 }
	}
	marrige = {
		primary = { type = 10 id = 2044 }
		secondary = { type = 10 id = 2043 }
		startdate = { year = 1148 month = january day = 1 }
		enddate = { year = 1150 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 2050 }
		secondary = { type = 10 id = 22596 }
		startdate = { year = 1155 month = january day = 1 }
		enddate = { year = 1178 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 2500 }
		secondary = { type = 10 id = 2515 }
		startdate = { year = 1177 month = january day = 1 }
		enddate = { year = 1185 month = september day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 2500 }
		secondary = { type = 10 id = 506 }
		startdate = { year = 1185 month = september day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 2971 }
		secondary = { type = 10 id = 2972 }
		startdate = { year = 1174 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 2982 }
		secondary = { type = 10 id = 20037 }
		startdate = { year = 1120 month = january day = 0 }
		enddate = { year = 1147 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 2989 }
		secondary = { type = 10 id = 2990 }
		startdate = { year = 1135 month = january day = 0 }
		enddate = { year = 1170 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 2991 }
		secondary = { type = 10 id = 4506 }
		startdate = { year = 1128 month = may day = 22 }
		enddate = { year = 1151 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 2992 }
		secondary = { type = 10 id = 2995 }
		startdate = { year = 1100 month = january day = 1 }
		enddate = { year = 1118 month = may day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 2994 }
		secondary = { type = 10 id = 2993 }
		startdate = { year = 1053 month = january day = 1 }
		enddate = { year = 1083 month = november day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 2997 }
		secondary = { type = 10 id = 2996 }
		startdate = { year = 1069 month = january day = 1 }
		enddate = { year = 1093 month = november day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 2999 }
		secondary = { type = 10 id = 2987 }
		startdate = { year = 1186 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3007 }
		secondary = { type = 10 id = 3076 }
		startdate = { year = 1170 month = january day = 0 }
		enddate = { year = 1179 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3007 }
		secondary = { type = 10 id = 3077 }
		startdate = { year = 1179 month = october day = 0 }
		enddate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 3007 }
		secondary = { type = 10 id = 3078 }
		startdate = { year = 1183 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3010 }
		secondary = { type = 10 id = 3032 }
		startdate = { year = 1170 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3011 }
		secondary = { type = 10 id = 3012 }
		startdate = { year = 1166 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3014 }
		secondary = { type = 10 id = 3015 }
		startdate = { year = 1184 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3021 }
		secondary = { type = 10 id = 3020 }
		startdate = { year = 1140 month = january day = 0 }
		enddate = { year = 1146 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3027 }
		secondary = { type = 10 id = 3028 }
		startdate = { year = 1140 month = january day = 0 }
		enddate = { year = 1177 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3029 }
		secondary = { type = 10 id = 3030 }
		startdate = { year = 1156 month = january day = 0 }
		enddate = { year = 1182 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3031 }
		secondary = { type = 10 id = 2984 }
		startdate = { year = 1129 month = january day = 0 }
		enddate = { year = 1150 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3042 }
		secondary = { type = 10 id = 3043 }
		startdate = { year = 1155 month = january day = 0 }
		enddate = { year = 1160 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3044 }
		secondary = { type = 10 id = 4023 }
		startdate = { year = 1180 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3048 }
		secondary = { type = 10 id = 3043 }
		startdate = { year = 1172 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3060 }
		secondary = { type = 10 id = 3061 }
		startdate = { year = 1166 month = january day = 0 }
		enddate = { year = 1183 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 3511 }
		secondary = { type = 10 id = 3515 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1152 month = july day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 3555 }
		secondary = { type = 10 id = 3556 }
		startdate = { year = 1155 month = january day = 1 }
		enddate = { year = 1174 month = september day = 22 }
	}
	marrige = {
		primary = { type = 10 id = 3560 }
		secondary = { type = 10 id = 3561 }
		startdate = { year = 1125 month = january day = 1 }
		enddate = { year = 1161 month = may day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 3570 }
		secondary = { type = 10 id = 3571 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4000 }
		secondary = { type = 10 id = 4623 }
		startdate = { year = 1157 month = may day = 18 }
		enddate = { year = 1180 month = january day = 10 }
	}
	marrige = {
		primary = { type = 10 id = 4004 }
		secondary = { type = 10 id = 4005 }
		startdate = { year = 1176 month = may day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 4006 }
		secondary = { type = 10 id = 4007 }
		startdate = { year = 1186 month = may day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 4020 }
		secondary = { type = 10 id = 4014 }
		startdate = { year = 1185 month = may day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 4038 }
		secondary = { type = 10 id = 4040 }
		startdate = { year = 1175 month = may day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 4050 }
		secondary = { type = 10 id = 4051 }
		startdate = { year = 1142 month = may day = 18 }
		enddate = { year = 1160 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 4056 }
		secondary = { type = 10 id = 4057 }
		startdate = { year = 1095 month = may day = 18 }
		enddate = { year = 1136 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 4500 }
		secondary = { type = 10 id = 5730 }
		startdate = { year = 1152 month = may day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 4508 }
		secondary = { type = 10 id = 5515 }
		startdate = { year = 1172 month = january day = 1 }
		enddate = { year = 1183 month = june day = 11 }
	}
	marrige = {
		primary = { type = 10 id = 4511 }
		secondary = { type = 10 id = 5740 }
		startdate = { year = 1181 month = july day = 1 }
		enddate = { year = 1186 month = august day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 4530 }
		secondary = { type = 10 id = 4531 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4533 }
		secondary = { type = 10 id = 4534 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1168 month = august day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 4538 }
		secondary = { type = 10 id = 4536 }
		startdate = { year = 1155 month = january day = 1 }
		enddate = { year = 1166 month = august day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 4550 }
		secondary = { type = 10 id = 4575 }
		startdate = { year = 1163 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4560 }
		secondary = { type = 10 id = 4561 }
		startdate = { year = 1119 month = january day = 1 }
		enddate = { year = 1141 month = december day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 4580 }
		secondary = { type = 10 id = 4581 }
		startdate = { year = 1186 month = december day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4582 }
		secondary = { type = 10 id = 4593 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4590 }
		secondary = { type = 10 id = 4591 }
		startdate = { year = 1134 month = january day = 1 }
		enddate = { year = 1168 month = july day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 4595 }
		secondary = { type = 10 id = 4598 }
		startdate = { year = 1146 month = january day = 1 }
		enddate = { year = 1169 month = february day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 4596 }
		secondary = { type = 10 id = 4597 }
		startdate = { year = 1104 month = january day = 1 }
		enddate = { year = 1118 month = april day = 23 }
	}
	marrige = {
		primary = { type = 10 id = 4610 }
		secondary = { type = 10 id = 3510 }
		startdate = { year = 1172 month = january day = 1 }
		enddate = { year = 1182 month = november day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 4620 }
		secondary = { type = 10 id = 4621 }
		startdate = { year = 1148 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4630 }
		secondary = { type = 10 id = 4641 }
		startdate = { year = 1154 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4645 }
		secondary = { type = 10 id = 4646 }
		startdate = { year = 1135 month = january day = 1 }
		enddate = { year = 1148 month = december day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 4650 }
		secondary = { type = 10 id = 4651 }
		startdate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4655 }
		secondary = { type = 10 id = 4656 }
		startdate = { year = 1127 month = january day = 1 }
		enddate = { year = 1155 month = january day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 4657 }
		secondary = { type = 10 id = 4526 }
		startdate = { year = 1155 month = january day = 1 }
		enddate = { year = 1162 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4658 }
		secondary = { type = 10 id = 4659 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4660 }
		secondary = { type = 10 id = 4661 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4670 }
		secondary = { type = 10 id = 4592 }
		startdate = { year = 1167 month = january day = 1 }
		enddate = { year = 1183 month = may day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 4685 }
		secondary = { type = 10 id = 4686 }
		startdate = { year = 1170 month = january day = 1 }
		enddate = { year = 1181 month = august day = 27 }
	}
	marrige = {
		primary = { type = 10 id = 4687 }
		secondary = { type = 10 id = 4671 }
		startdate = { year = 1135 month = january day = 1 }
		enddate = { year = 1153 month = august day = 27 }
	}
	marrige = {
		primary = { type = 10 id = 4690 }
		secondary = { type = 10 id = 4692 }
		startdate = { year = 1161 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4700 }
		secondary = { type = 10 id = 4701 }
		startdate = { year = 1139 month = january day = 1 }
		enddate = { year = 1141 month = march day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 4715 }
		secondary = { type = 10 id = 4716 }
		startdate = { year = 1142 month = january day = 1 }
		enddate = { year = 1153 month = july day = 27 }
	}
	marrige = {
		primary = { type = 10 id = 4730 }
		secondary = { type = 10 id = 4515 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4735 }
		secondary = { type = 10 id = 4736 }
		startdate = { year = 1146 month = january day = 1 }
		enddate = { year = 1176 month = april day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 4740 }
		secondary = { type = 10 id = 4741 }
		startdate = { year = 1151 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4745 }
		secondary = { type = 10 id = 4563 }
		startdate = { year = 1124 month = january day = 1 }
		enddate = { year = 1144 month = august day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 4750 }
		secondary = { type = 10 id = 4751 }
		startdate = { year = 1174 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4755 }
		secondary = { type = 10 id = 6857 }
		startdate = { year = 1138 month = january day = 1 }
		enddate = { year = 1151 month = december day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 4770 }
		secondary = { type = 10 id = 14553 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1176 month = june day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 4780 }
		secondary = { type = 10 id = 4781 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4785 }
		secondary = { type = 10 id = 4786 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4790 }
		secondary = { type = 10 id = 4791 }
		startdate = { year = 1120 month = january day = 1 }
		enddate = { year = 1147 month = june day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 4795 }
		secondary = { type = 10 id = 4796 }
		startdate = { year = 1140 month = january day = 1 }
		enddate = { year = 1173 month = june day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 4797 }
		secondary = { type = 10 id = 4664 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4800 }
		secondary = { type = 10 id = 4799 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4980 }
		secondary = { type = 10 id = 5529 }
		startdate = { year = 1160 month = january day = 1 }
		enddate = { year = 1173 month = december day = 17 }
	}
	marrige = {
		primary = { type = 10 id = 4980 }
		secondary = { type = 10 id = 4986 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4987 }
		secondary = { type = 10 id = 4982 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5500 }
		secondary = { type = 10 id = 5730 }
		startdate = { year = 1137 month = january day = 1 }
		enddate = { year = 1152 month = march day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 5500 }
		secondary = { type = 10 id = 7503 }
		startdate = { year = 1154 month = january day = 1 }
		enddate = { year = 1160 month = august day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 5500 }
		secondary = { type = 10 id = 5505 }
		startdate = { year = 1160 month = january day = 1 }
		enddate = { year = 1180 month = february day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 5502 }
		secondary = { type = 10 id = 13118 }
		startdate = { year = 1115 month = january day = 1 }
		enddate = { year = 1137 month = march day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 5506 }
		secondary = { type = 10 id = 5522 }
		startdate = { year = 1180 month = april day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 5509 }
		secondary = { type = 10 id = 31017 }
		startdate = { year = 1150 month = april day = 28 }
		enddate = { year = 1183 month = february day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 5520 }
		secondary = { type = 10 id = 12589 }
		startdate = { year = 1169 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5521 }
		secondary = { type = 10 id = 5945 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1168 month = july day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 5523 }
		secondary = { type = 10 id = 5965 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5530 }
		secondary = { type = 10 id = 5503 }
		startdate = { year = 1153 month = january day = 1 }
		enddate = { year = 1176 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5531 }
		secondary = { type = 10 id = 12800 }
		startdate = { year = 1176 month = january day = 0 }
		enddate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5542 }
		secondary = { type = 10 id = 5541 }
		startdate = { year = 1172 month = january day = 1 }
		enddate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5550 }
		secondary = { type = 10 id = 5573 }
		startdate = { year = 1151 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5551 }
		secondary = { type = 10 id = 10512 }
		startdate = { year = 1129 month = january day = 1 }
		enddate = { year = 1160 month = november day = 11 }
	}
	marrige = {
		primary = { type = 10 id = 5560 }
		secondary = { type = 10 id = 5562 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5561 }
		secondary = { type = 10 id = 5535 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1160 month = december day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 5564 }
		secondary = { type = 10 id = 5555 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5570 }
		secondary = { type = 10 id = 5534 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5580 }
		secondary = { type = 10 id = 15505 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5581 }
		secondary = { type = 10 id = 5595 }
		startdate = { year = 1159 month = january day = 1 }
		enddate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5593 }
		secondary = { type = 10 id = 5692 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5600 }
		secondary = { type = 10 id = 5616 }
		startdate = { year = 1166 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5601 }
		secondary = { type = 10 id = 5556 }
		startdate = { year = 1140 month = january day = 1 }
		enddate = { year = 1144 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5605 }
		secondary = { type = 10 id = 5604 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1176 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5620 }
		secondary = { type = 10 id = 4525 }
		startdate = { year = 1158 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5621 }
		secondary = { type = 10 id = 5617 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1160 month = november day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 5630 }
		secondary = { type = 10 id = 5645 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5640 }
		secondary = { type = 10 id = 5729 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5641 }
		secondary = { type = 10 id = 5642 }
		startdate = { year = 1167 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5651 }
		secondary = { type = 10 id = 5596 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1170 month = september day = 9 }
	}
	marrige = {
		primary = { type = 10 id = 5660 }
		secondary = { type = 10 id = 5762 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5661 }
		secondary = { type = 10 id = 5662 }
		startdate = { year = 1159 month = january day = 1 }
		enddate = { year = 1165 month = august day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 5665 }
		secondary = { type = 10 id = 5666 }
		startdate = { year = 1162 month = january day = 1 }
		enddate = { year = 1169 month = february day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 5670 }
		secondary = { type = 10 id = 5675 }
		startdate = { year = 1154 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5671 }
		secondary = { type = 10 id = 5672 }
		startdate = { year = 1134 month = january day = 1 }
		enddate = { year = 1156 month = april day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 5680 }
		secondary = { type = 10 id = 5683 }
		startdate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5681 }
		secondary = { type = 10 id = 5682 }
		startdate = { year = 1129 month = january day = 1 }
		enddate = { year = 1150 month = april day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 5690 }
		secondary = { type = 10 id = 12509 }
		startdate = { year = 1173 month = january day = 1 }
		enddate = { year = 1181 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5700 }
		secondary = { type = 10 id = 5963 }
		startdate = { year = 1174 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5705 }
		secondary = { type = 10 id = 12582 }
		startdate = { year = 1170 month = january day = 1 }
		enddate = { year = 1174 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5711 }
		secondary = { type = 10 id = 5712 }
		startdate = { year = 1140 month = january day = 1 }
		enddate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5713 }
		secondary = { type = 10 id = 5714 }
		startdate = { year = 1168 month = january day = 1 }
		enddate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5725 }
		secondary = { type = 10 id = 5710 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5731 }
		secondary = { type = 10 id = 5732 }
		startdate = { year = 1120 month = january day = 1 }
		enddate = { year = 1130 month = february day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 5741 }
		secondary = { type = 10 id = 3510 }
		startdate = { year = 1164 month = january day = 1 }
		enddate = { year = 1171 month = february day = 20 }
	}
	marrige = {
		primary = { type = 10 id = 5743 }
		secondary = { type = 10 id = 5760 }
		startdate = { year = 1151 month = september day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 5744 }
		secondary = { type = 10 id = 5745 }
		startdate = { year = 1108 month = january day = 1 }
		enddate = { year = 1138 month = april day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 5761 }
		secondary = { type = 10 id = 5770 }
		startdate = { year = 1131 month = january day = 1 }
		enddate = { year = 1133 month = june day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 5780 }
		secondary = { type = 10 id = 5746 }
		startdate = { year = 1160 month = may day = 5 }
		enddate = { year = 1179 month = february day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 5781 }
		secondary = { type = 10 id = 5800 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5782 }
		secondary = { type = 10 id = 5801 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5802 }
		secondary = { type = 10 id = 5750 }
		startdate = { year = 1164 month = january day = 1 }
		enddate = { year = 1184 month = april day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 5803 }
		secondary = { type = 10 id = 5804 }
		startdate = { year = 1134 month = january day = 1 }
		enddate = { year = 1168 month = july day = 24 }
	}
	marrige = {
		primary = { type = 10 id = 5810 }
		secondary = { type = 10 id = 5783 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5814 }
		secondary = { type = 10 id = 5825 }
		startdate = { year = 1147 month = january day = 1 }
		enddate = { year = 1157 month = may day = 16 }
	}
	marrige = {
		primary = { type = 10 id = 5821 }
		secondary = { type = 10 id = 4666 }
		startdate = { year = 1170 month = january day = 1 }
		enddate = { year = 1182 month = may day = 16 }
	}
	marrige = {
		primary = { type = 10 id = 5822 }
		secondary = { type = 10 id = 5823 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1181 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5824 }
		secondary = { type = 10 id = 4584 }
		startdate = { year = 1169 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5830 }
		secondary = { type = 10 id = 5785 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5831 }
		secondary = { type = 10 id = 5840 }
		startdate = { year = 1148 month = january day = 1 }
		enddate = { year = 1173 month = march day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 5851 }
		secondary = { type = 10 id = 5860 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1150 month = april day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 5852 }
		secondary = { type = 10 id = 5850 }
		startdate = { year = 1159 month = january day = 1 }
		enddate = { year = 1173 month = april day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 5880 }
		secondary = { type = 10 id = 5890 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5881 }
		secondary = { type = 10 id = 4537 }
		startdate = { year = 1173 month = january day = 1 }
		enddate = { year = 1175 month = april day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 5891 }
		secondary = { type = 10 id = 5893 }
		startdate = { year = 1129 month = january day = 1 }
		enddate = { year = 1152 month = february day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 5892 }
		secondary = { type = 10 id = 5504 }
		startdate = { year = 1164 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5895 }
		secondary = { type = 10 id = 5896 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5897 }
		secondary = { type = 10 id = 5898 }
		startdate = { year = 1081 month = january day = 1 }
		enddate = { year = 1102 month = february day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 5920 }
		secondary = { type = 10 id = 4634 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5931 }
		secondary = { type = 10 id = 5668 }
		startdate = { year = 1144 month = january day = 1 }
		enddate = { year = 1176 month = february day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 5966 }
		secondary = { type = 10 id = 5512 }
		startdate = { year = 1173 month = january day = 1 }
		enddate = { year = 1181 month = may day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 5970 }
		secondary = { type = 10 id = 5971 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1176 month = may day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 5974 }
		secondary = { type = 10 id = 5973 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5980 }
		secondary = { type = 10 id = 5995 }
		startdate = { year = 1158 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5981 }
		secondary = { type = 10 id = 5990 }
		startdate = { year = 1135 month = january day = 1 }
		enddate = { year = 1150 month = june day = 16 }
	}
	marrige = {
		primary = { type = 10 id = 6000 }
		secondary = { type = 10 id = 12800 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6001 }
		secondary = { type = 10 id = 6002 }
		startdate = { year = 1145 month = january day = 1 }
		enddate = { year = 1162 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6030 }
		secondary = { type = 10 id = 6017 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6033 }
		secondary = { type = 10 id = 5716 }
		startdate = { year = 1140 month = january day = 1 }
		enddate = { year = 1182 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6034 }
		secondary = { type = 10 id = 11533 }
		startdate = { year = 1087 month = january day = 1 }
		enddate = { year = 1119 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6036 }
		secondary = { type = 10 id = 6037 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6038 }
		secondary = { type = 10 id = 6039 }
		startdate = { year = 1129 month = january day = 1 }
		enddate = { year = 1145 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6040 }
		secondary = { type = 10 id = 6041 }
		startdate = { year = 1145 month = january day = 1 }
		enddate = { year = 1169 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6042 }
		secondary = { type = 10 id = 5607 }
		startdate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6500 }
		secondary = { type = 10 id = 7502 }
		startdate = { year = 1153 month = july day = 20 }
		enddate = { year = 1179 month = august day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 6510 }
		secondary = { type = 10 id = 7501 }
		startdate = { year = 1139 month = january day = 1 }
		enddate = { year = 1150 month = november day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 6800 }
		secondary = { type = 10 id = 6820 }
		startdate = { year = 1166 month = january day = 1 }
		enddate = { year = 1178 month = october day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 6800 }
		secondary = { type = 10 id = 6830 }
		startdate = { year = 1178 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6801 }
		secondary = { type = 10 id = 6810 }
		startdate = { year = 1143 month = january day = 1 }
		enddate = { year = 1171 month = july day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 6831 }
		secondary = { type = 10 id = 12955 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6832 }
		secondary = { type = 10 id = 6833 }
		startdate = { year = 1163 month = april day = 11 }
		enddate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6840 }
		secondary = { type = 10 id = 3512 }
		startdate = { year = 1168 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6841 }
		secondary = { type = 10 id = 6845 }
		startdate = { year = 1138 month = january day = 1 }
		enddate = { year = 1157 month = november day = 17 }
	}
	marrige = {
		primary = { type = 10 id = 6842 }
		secondary = { type = 10 id = 12924 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6850 }
		secondary = { type = 10 id = 6870 }
		startdate = { year = 1155 month = january day = 1 }
		enddate = { year = 1172 month = august day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 6850 }
		secondary = { type = 10 id = 6806 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6851 }
		secondary = { type = 10 id = 6860 }
		startdate = { year = 1140 month = january day = 1 }
		enddate = { year = 1142 month = may day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 6852 }
		secondary = { type = 10 id = 5854 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6900 }
		secondary = { type = 10 id = 6910 }
		startdate = { year = 1167 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6911 }
		secondary = { type = 10 id = 6920 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1177 month = may day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 6930 }
		secondary = { type = 10 id = 6902 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 7500 }
		secondary = { type = 10 id = 10511 }
		startdate = { year = 1124 month = january day = 1 }
		enddate = { year = 1149 month = january day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 7510 }
		secondary = { type = 10 id = 4512 }
		startdate = { year = 1177 month = september day = 22 }
	}
	marrige = {
		primary = { type = 10 id = 7520 }
		secondary = { type = 10 id = 6513 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1156 month = august day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 7540 }
		secondary = { type = 10 id = 6511 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 7541 }
		secondary = { type = 10 id = 7550 }
		startdate = { year = 1138 month = january day = 1 }
		enddate = { year = 1156 month = august day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 7561 }
		secondary = { type = 10 id = 10575 }
		startdate = { year = 1170 month = january day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 7580 }
		secondary = { type = 10 id = 7590 }
		startdate = { year = 1128 month = january day = 1 }
		enddate = { year = 1156 month = august day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 7600 }
		secondary = { type = 10 id = 7610 }
		startdate = { year = 1119 month = january day = 1 }
		enddate = { year = 1124 month = may day = 23 }
	}
	marrige = {
		primary = { type = 10 id = 7650 }
		secondary = { type = 10 id = 7651 }
		startdate = { year = 1187 month = january day = 1 }
		enddate = { year = 1130 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 7652 }
		secondary = { type = 10 id = 7659 }
		startdate = { year = 1125 month = january day = 1 }
		enddate = { year = 1158 month = august day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 7656 }
		secondary = { type = 10 id = 7657 }
		startdate = { year = 1153 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 8500 }
		secondary = { type = 10 id = 9501 }
		startdate = { year = 1165 month = may day = 1 }
		enddate = { year = 1175 month = june day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 8500 }
		secondary = { type = 10 id = 8551 }
		startdate = { year = 1178 month = october day = 7 }
		enddate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 9500 }
		secondary = { type = 10 id = 10513 }
		startdate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 9503 }
		secondary = { type = 10 id = 12672 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1157 month = november day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 9530 }
		secondary = { type = 10 id = 9531 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 9542 }
		secondary = { type = 10 id = 9543 }
		startdate = { year = 1145 month = january day = 1 }
		enddate = { year = 1180 month = january day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 10500 }
		secondary = { type = 10 id = 7504 }
		startdate = { year = 1174 month = january day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 10506 }
		secondary = { type = 10 id = 10507 }
		startdate = { year = 1137 month = january day = 18 }
		enddate = { year = 1162 month = january day = 11 }
	}
	marrige = {
		primary = { type = 10 id = 10508 }
		secondary = { type = 10 id = 10509 }
		startdate = { year = 1100 month = january day = 18 }
		enddate = { year = 1106 month = july day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 10514 }
		secondary = { type = 10 id = 10515 }
		startdate = { year = 1183 month = january day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 10571 }
		secondary = { type = 10 id = 5557 }
		startdate = { year = 1183 month = january day = 18 }
		enddate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10572 }
		secondary = { type = 10 id = 10573 }
		startdate = { year = 1119 month = january day = 18 }
		enddate = { year = 1130 month = january day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 10572 }
		secondary = { type = 10 id = 10574 }
		startdate = { year = 1135 month = january day = 18 }
		enddate = { year = 1154 month = january day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 11500 }
		secondary = { type = 10 id = 4513 }
		startdate = { year = 1177 month = february day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 11501 }
		secondary = { type = 10 id = 6512 }
		startdate = { year = 1153 month = january day = 1 }
		enddate = { year = 1178 month = april day = 16 }
	}
	marrige = {
		primary = { type = 10 id = 11502 }
		secondary = { type = 10 id = 7662 }
		startdate = { year = 1118 month = january day = 1 }
		enddate = { year = 1135 month = april day = 16 }
	}
	marrige = {
		primary = { type = 10 id = 11502 }
		secondary = { type = 10 id = 11503 }
		startdate = { year = 1151 month = january day = 1 }
		enddate = { year = 1154 month = april day = 16 }
	}
	marrige = {
		primary = { type = 10 id = 11507 }
		secondary = { type = 10 id = 11508 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1148 month = april day = 16 }
	}
	marrige = {
		primary = { type = 10 id = 11509 }
		secondary = { type = 10 id = 11510 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11516 }
		secondary = { type = 10 id = 11517 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11519 }
		secondary = { type = 10 id = 11520 }
		startdate = { year = 1090 month = january day = 1 }
		enddate = { year = 1111 month = december day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 11521 }
		secondary = { type = 10 id = 11522 }
		startdate = { year = 1120 month = january day = 1 }
		enddate = { year = 1145 month = july day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 11523 }
		secondary = { type = 10 id = 11524 }
		startdate = { year = 1143 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11526 }
		secondary = { type = 10 id = 11527 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11531 }
		secondary = { type = 10 id = 11530 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12010 }
		secondary = { type = 10 id = 12011 }
		startdate = { year = 1150 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12012 }
		secondary = { type = 10 id = 12015 }
		startdate = { year = 1182 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12013 }
		secondary = { type = 10 id = 12016 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12030 }
		secondary = { type = 10 id = 21513 }
		startdate = { year = 1148 month = january day = 1 }
		enddate = { year = 1174 month = august day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 12030 }
		secondary = { type = 10 id = 6844 }
		startdate = { year = 1176 month = january day = 1 }
		enddate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12038 }
		secondary = { type = 10 id = 12039 }
		startdate = { year = 1148 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12041 }
		secondary = { type = 10 id = 12853 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12048 }
		secondary = { type = 10 id = 21512 }
		startdate = { year = 1142 month = january day = 1 }
		enddate = { year = 1165 month = october day = 26 }
	}
	marrige = {
		primary = { type = 10 id = 12057 }
		secondary = { type = 10 id = 12058 }
		startdate = { year = 1176 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12360 }
		secondary = { type = 10 id = 12361 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12366 }
		secondary = { type = 10 id = 12047 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12370 }
		secondary = { type = 10 id = 12371 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12380 }
		secondary = { type = 10 id = 12381 }
		startdate = { year = 1173 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12390 }
		secondary = { type = 10 id = 12391 }
		startdate = { year = 1163 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12393 }
		secondary = { type = 10 id = 12392 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12397 }
		secondary = { type = 10 id = 12386 }
		startdate = { year = 1165 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12400 }
		secondary = { type = 10 id = 12401 }
		startdate = { year = 1162 month = january day = 1 }
		enddate = { year = 1172 month = december day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 12410 }
		secondary = { type = 10 id = 12593 }
		startdate = { year = 1132 month = january day = 1 }
		enddate = { year = 1160 month = july day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 12421 }
		secondary = { type = 10 id = 12422 }
		startdate = { year = 1162 month = january day = 1 }
		enddate = { year = 1181 month = april day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 12430 }
		secondary = { type = 10 id = 12923 }
		startdate = { year = 1166 month = january day = 1 }
		enddate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12430 }
		secondary = { type = 10 id = 22797 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12431 }
		secondary = { type = 10 id = 12452 }
		startdate = { year = 1182 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12440 }
		secondary = { type = 10 id = 12497 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1172 month = september day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 12450 }
		secondary = { type = 10 id = 12451 }
		startdate = { year = 1156 month = january day = 1 }
		enddate = { year = 1162 month = july day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 12490 }
		secondary = { type = 10 id = 12491 }
		startdate = { year = 1159 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12493 }
		secondary = { type = 10 id = 12494 }
		startdate = { year = 1142 month = january day = 1 }
		enddate = { year = 1157 month = march day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 12495 }
		secondary = { type = 10 id = 12498 }
		startdate = { year = 1121 month = january day = 1 }
		enddate = { year = 1132 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12495 }
		secondary = { type = 10 id = 12496 }
		startdate = { year = 1138 month = january day = 1 }
		enddate = { year = 1147 month = june day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 12501 }
		secondary = { type = 10 id = 5599 }
		startdate = { year = 1156 month = june day = 16 }
		enddate = { year = 1184 month = november day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 12507 }
		secondary = { type = 10 id = 12508 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12530 }
		secondary = { type = 10 id = 19518 }
		startdate = { year = 1172 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12535 }
		secondary = { type = 10 id = 12860 }
		startdate = { year = 1177 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12540 }
		secondary = { type = 10 id = 12541 }
		startdate = { year = 1156 month = january day = 1 }
		enddate = { year = 1177 month = february day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12546 }
		secondary = { type = 10 id = 12547 }
		startdate = { year = 1110 month = january day = 1 }
		enddate = { year = 1136 month = may day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 12550 }
		secondary = { type = 10 id = 21563 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12560 }
		secondary = { type = 10 id = 21563 }
		startdate = { year = 1170 month = january day = 1 }
		enddate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12580 }
		secondary = { type = 10 id = 12615 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12581 }
		secondary = { type = 10 id = 12499 }
		startdate = { year = 1151 month = january day = 1 }
		enddate = { year = 1176 month = december day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 12583 }
		secondary = { type = 10 id = 21562 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12590 }
		secondary = { type = 10 id = 5955 }
		startdate = { year = 1144 month = january day = 1 }
		enddate = { year = 1165 month = september day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 12591 }
		secondary = { type = 10 id = 5517 }
		startdate = { year = 1160 month = january day = 1 }
		enddate = { year = 1183 month = january day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 12591 }
		secondary = { type = 10 id = 9510 }
		startdate = { year = 1183 month = january day = 26 }
	}
	marrige = {
		primary = { type = 10 id = 12600 }
		secondary = { type = 10 id = 12601 }
		startdate = { year = 1147 month = february day = 1 }
		enddate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12600 }
		secondary = { type = 10 id = 4509 }
		startdate = { year = 1168 month = february day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12602 }
		secondary = { type = 10 id = 12603 }
		startdate = { year = 1127 month = february day = 1 }
		enddate = { year = 1139 month = march day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 12630 }
		secondary = { type = 10 id = 12650 }
		startdate = { year = 1166 month = january day = 1 }
		enddate = { year = 1181 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12632 }
		secondary = { type = 10 id = 12662 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1155 month = may day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 12690 }
		secondary = { type = 10 id = 12592 }
		startdate = { year = 1154 month = april day = 12 }
		enddate = { year = 1163 month = january day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 12690 }
		secondary = { type = 10 id = 12720 }
		startdate = { year = 1186 month = april day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 12691 }
		secondary = { type = 10 id = 12700 }
		startdate = { year = 1112 month = january day = 1 }
		enddate = { year = 1139 month = november day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 12721 }
		secondary = { type = 10 id = 12730 }
		startdate = { year = 1157 month = january day = 1 }
		enddate = { year = 1179 month = may day = 26 }
	}
	marrige = {
		primary = { type = 10 id = 12740 }
		secondary = { type = 10 id = 12671 }
		startdate = { year = 1160 month = january day = 1 }
		enddate = { year = 1172 month = august day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 12741 }
		secondary = { type = 10 id = 12750 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1137 month = september day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 12761 }
		secondary = { type = 10 id = 12770 }
		startdate = { year = 1148 month = january day = 1 }
		enddate = { year = 1158 month = april day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 12780 }
		secondary = { type = 10 id = 13522 }
		startdate = { year = 1162 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12781 }
		secondary = { type = 10 id = 12790 }
		startdate = { year = 1143 month = january day = 1 }
		enddate = { year = 1182 month = september day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 12801 }
		secondary = { type = 10 id = 13522 }
		startdate = { year = 1155 month = january day = 1 }
		enddate = { year = 1162 month = july day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 12850 }
		secondary = { type = 10 id = 19512 }
		startdate = { year = 1157 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12851 }
		secondary = { type = 10 id = 12852 }
		startdate = { year = 1139 month = january day = 1 }
		enddate = { year = 1153 month = august day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 12851 }
		secondary = { type = 10 id = 12441 }
		startdate = { year = 1139 month = january day = 1 }
		enddate = { year = 1174 month = august day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 12861 }
		secondary = { type = 10 id = 12852 }
		startdate = { year = 1109 month = january day = 1 }
		enddate = { year = 1125 month = january day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 12863 }
		secondary = { type = 10 id = 12033 }
		startdate = { year = 1155 month = january day = 1 }
		enddate = { year = 1167 month = august day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 12864 }
		secondary = { type = 10 id = 21540 }
		startdate = { year = 1182 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12872 }
		secondary = { type = 10 id = 19533 }
		startdate = { year = 1123 month = january day = 1 }
		enddate = { year = 1140 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12873 }
		secondary = { type = 10 id = 12443 }
		startdate = { year = 1160 month = january day = 1 }
		enddate = { year = 1166 month = january day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 12873 }
		secondary = { type = 10 id = 12043 }
		startdate = { year = 1176 month = january day = 1 }
		enddate = { year = 1177 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12889 }
		secondary = { type = 10 id = 12890 }
		startdate = { year = 1110 month = january day = 1 }
		enddate = { year = 1112 month = january day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 12898 }
		secondary = { type = 10 id = 12899 }
		startdate = { year = 1030 month = january day = 1 }
		enddate = { year = 1055 month = january day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 12905 }
		secondary = { type = 10 id = 21564 }
		startdate = { year = 1173 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12908 }
		secondary = { type = 10 id = 12909 }
		startdate = { year = 1138 month = january day = 1 }
		enddate = { year = 1160 month = november day = 11 }
	}
	marrige = {
		primary = { type = 10 id = 12910 }
		secondary = { type = 10 id = 12911 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12915 }
		secondary = { type = 10 id = 12916 }
		startdate = { year = 1164 month = january day = 1 }
		enddate = { year = 1180 month = april day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12920 }
		secondary = { type = 10 id = 12921 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12925 }
		secondary = { type = 10 id = 12926 }
		startdate = { year = 1154 month = january day = 1 }
		enddate = { year = 1172 month = december day = 17 }
	}
	marrige = {
		primary = { type = 10 id = 12930 }
		secondary = { type = 10 id = 12931 }
		startdate = { year = 1144 month = january day = 1 }
		enddate = { year = 1174 month = december day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 12930 }
		secondary = { type = 10 id = 1519 }
		startdate = { year = 1177 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12932 }
		secondary = { type = 10 id = 12937 }
		startdate = { year = 1166 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12935 }
		secondary = { type = 10 id = 12936 }
		startdate = { year = 1103 month = january day = 1 }
		enddate = { year = 1128 month = march day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 12938 }
		secondary = { type = 10 id = 12939 }
		startdate = { year = 1150 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12940 }
		secondary = { type = 10 id = 12934 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12947 }
		secondary = { type = 10 id = 12933 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12949 }
		secondary = { type = 10 id = 12865 }
		startdate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12960 }
		secondary = { type = 10 id = 12970 }
		startdate = { year = 1172 month = january day = 1 }
		enddate = { year = 1183 month = july day = 11 }
	}
	marrige = {
		primary = { type = 10 id = 12962 }
		secondary = { type = 10 id = 12963 }
		startdate = { year = 1125 month = january day = 1 }
		enddate = { year = 1156 month = august day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 12964 }
		secondary = { type = 10 id = 12954 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12966 }
		secondary = { type = 10 id = 12967 }
		startdate = { year = 1140 month = january day = 1 }
		enddate = { year = 1161 month = september day = 20 }
	}
	marrige = {
		primary = { type = 10 id = 12980 }
		secondary = { type = 10 id = 12953 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12995 }
		secondary = { type = 10 id = 12542 }
		startdate = { year = 1175 month = january day = 1 }
		enddate = { year = 1181 month = june day = 27 }
	}
	marrige = {
		primary = { type = 10 id = 13100 }
		secondary = { type = 10 id = 13101 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13110 }
		secondary = { type = 10 id = 12601 }
		startdate = { year = 1164 month = january day = 1 }
		enddate = { year = 1167 month = april day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 13110 }
		secondary = { type = 10 id = 13114 }
		startdate = { year = 1177 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13111 }
		secondary = { type = 10 id = 13112 }
		startdate = { year = 1123 month = january day = 1 }
		enddate = { year = 1148 month = june day = 27 }
	}
	marrige = {
		primary = { type = 10 id = 13130 }
		secondary = { type = 10 id = 13134 }
		startdate = { year = 1150 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13135 }
		secondary = { type = 10 id = 13136 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13141 }
		secondary = { type = 10 id = 13142 }
		startdate = { year = 1155 month = january day = 1 }
		enddate = { year = 1183 month = october day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 13145 }
		secondary = { type = 10 id = 13144 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13146 }
		secondary = { type = 10 id = 12693 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1152 month = october day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 13149 }
		secondary = { type = 10 id = 13150 }
		startdate = { year = 1079 month = january day = 1 }
		enddate = { year = 1111 month = october day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 13160 }
		secondary = { type = 10 id = 13161 }
		startdate = { year = 1122 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13162 }
		secondary = { type = 10 id = 13143 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13520 }
		secondary = { type = 10 id = 13527 }
		startdate = { year = 1136 month = january day = 1 }
		enddate = { year = 1168 month = april day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 13521 }
		secondary = { type = 10 id = 15502 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13523 }
		secondary = { type = 10 id = 13540 }
		startdate = { year = 1169 month = january day = 1 }
		enddate = { year = 1180 month = april day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 13523 }
		secondary = { type = 10 id = 13116 }
		startdate = { year = 1181 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13550 }
		secondary = { type = 10 id = 13525 }
		startdate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13560 }
		secondary = { type = 10 id = 13561 }
		startdate = { year = 1187 month = january day = 1 }
		enddate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14000 }
		secondary = { type = 10 id = 14001 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14020 }
		secondary = { type = 10 id = 14029 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14022 }
		secondary = { type = 10 id = 14023 }
		startdate = { year = 1125 month = january day = 1 }
		enddate = { year = 1172 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14025 }
		secondary = { type = 10 id = 14026 }
		startdate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14550 }
		secondary = { type = 10 id = 14551 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1151 month = february day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 14580 }
		secondary = { type = 10 id = 14554 }
		startdate = { year = 1155 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14700 }
		secondary = { type = 10 id = 4499 }
		startdate = { year = 1173 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14710 }
		secondary = { type = 10 id = 14711 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1169 month = july day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 14720 }
		secondary = { type = 10 id = 14721 }
		startdate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14722 }
		secondary = { type = 10 id = 14723 }
		startdate = { year = 1100 month = january day = 1 }
		enddate = { year = 1128 month = july day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 14800 }
		secondary = { type = 10 id = 14801 }
		startdate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14803 }
		secondary = { type = 10 id = 4010 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14810 }
		secondary = { type = 10 id = 14811 }
		startdate = { year = 1120 month = january day = 1 }
		enddate = { year = 1137 month = july day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 15001 }
		secondary = { type = 10 id = 15527 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15004 }
		secondary = { type = 10 id = 17504 }
		startdate = { year = 1180 month = december day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 15500 }
		secondary = { type = 10 id = 19515 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15503 }
		secondary = { type = 10 id = 15535 }
		startdate = { year = 1169 month = january day = 1 }
		enddate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15504 }
		secondary = { type = 10 id = 15525 }
		startdate = { year = 1153 month = january day = 1 }
		enddate = { year = 1182 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15509 }
		secondary = { type = 10 id = 15555 }
		startdate = { year = 1120 month = january day = 1 }
		enddate = { year = 1166 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15518 }
		secondary = { type = 10 id = 16510 }
		startdate = { year = 1187 month = january day = 1 }
		enddate = { year = 1185 month = april day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 15545 }
		secondary = { type = 10 id = 15501 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15570 }
		secondary = { type = 10 id = 15571 }
		startdate = { year = 1152 month = january day = 1 }
		enddate = { year = 1161 month = february day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 15660 }
		secondary = { type = 10 id = 19519 }
		startdate = { year = 1180 month = january day = 1 }
		enddate = { year = 1182 month = may day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15670 }
		secondary = { type = 10 id = 15671 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 16515 }
		secondary = { type = 10 id = 16540 }
		startdate = { year = 1155 month = january day = 1 }
		enddate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 16525 }
		secondary = { type = 10 id = 16500 }
		startdate = { year = 1186 month = december day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 18500 }
		secondary = { type = 10 id = 18501 }
		startdate = { year = 1172 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 18510 }
		secondary = { type = 10 id = 15523 }
		startdate = { year = 1107 month = january day = 1 }
		enddate = { year = 1123 month = march day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 19500 }
		secondary = { type = 10 id = 19521 }
		startdate = { year = 1164 month = january day = 1 }
		enddate = { year = 1169 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 19500 }
		secondary = { type = 10 id = 5515 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 19510 }
		secondary = { type = 10 id = 22573 }
		startdate = { year = 1146 month = january day = 1 }
		enddate = { year = 1162 month = may day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 19530 }
		secondary = { type = 10 id = 18511 }
		startdate = { year = 1128 month = january day = 1 }
		enddate = { year = 1141 month = february day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 19531 }
		secondary = { type = 10 id = 19532 }
		startdate = { year = 1107 month = january day = 1 }
		enddate = { year = 1139 month = april day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 19550 }
		secondary = { type = 10 id = 19519 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20020 }
		secondary = { type = 10 id = 20039 }
		startdate = { year = 1150 month = january day = 0 }
		enddate = { year = 1153 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 20020 }
		secondary = { type = 10 id = 20038 }
		startdate = { year = 1135 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 20021 }
		secondary = { type = 10 id = 20045 }
		startdate = { year = 1155 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 20022 }
		secondary = { type = 10 id = 20047 }
		startdate = { year = 1185 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 20023 }
		secondary = { type = 10 id = 20024 }
		startdate = { year = 1135 month = january day = 0 }
		enddate = { year = 1153 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 20023 }
		secondary = { type = 10 id = 20025 }
		startdate = { year = 1112 month = january day = 0 }
		enddate = { year = 1119 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 20027 }
		secondary = { type = 10 id = 20026 }
		startdate = { year = 1137 month = january day = 0 }
		enddate = { year = 1164 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 20019 }
		secondary = { type = 10 id = 20028 }
		startdate = { year = 1170 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 20034 }
		secondary = { type = 10 id = 20035 }
		startdate = { year = 1076 month = january day = 0 }
		enddate = { year = 1097 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 21515 }
		secondary = { type = 10 id = 22781 }
		startdate = { year = 1102 month = january day = 1 }
		enddate = { year = 1110 month = may day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 21515 }
		secondary = { type = 10 id = 21519 }
		startdate = { year = 1115 month = january day = 1 }
		enddate = { year = 1138 month = may day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 21516 }
		secondary = { type = 10 id = 12881 }
		startdate = { year = 1084 month = january day = 1 }
		enddate = { year = 1086 month = december day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 21520 }
		secondary = { type = 10 id = 21521 }
		startdate = { year = 1163 month = january day = 1 }
		enddate = { year = 1185 month = march day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 21520 }
		secondary = { type = 10 id = 22824 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21522 }
		secondary = { type = 10 id = 18512 }
		startdate = { year = 1132 month = january day = 1 }
		enddate = { year = 1161 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21530 }
		secondary = { type = 10 id = 22823 }
		startdate = { year = 1144 month = january day = 1 }
		enddate = { year = 1158 month = april day = 16 }
	}
	marrige = {
		primary = { type = 10 id = 21530 }
		secondary = { type = 10 id = 21541 }
		startdate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21531 }
		secondary = { type = 10 id = 12545 }
		startdate = { year = 1123 month = january day = 1 }
		enddate = { year = 1157 month = november day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 21550 }
		secondary = { type = 10 id = 21551 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21560 }
		secondary = { type = 10 id = 19505 }
		startdate = { year = 1140 month = january day = 1 }
		enddate = { year = 1155 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21560 }
		secondary = { type = 10 id = 22826 }
		startdate = { year = 1155 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21561 }
		secondary = { type = 10 id = 22509 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21700 }
		secondary = { type = 10 id = 21701 }
		startdate = { year = 1129 month = january day = 1 }
		enddate = { year = 1148 month = january day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 21710 }
		secondary = { type = 10 id = 21711 }
		startdate = { year = 1159 month = january day = 1 }
		enddate = { year = 1177 month = april day = 26 }
	}
	marrige = {
		primary = { type = 10 id = 21710 }
		secondary = { type = 10 id = 21568 }
		startdate = { year = 1177 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21717 }
		secondary = { type = 10 id = 21569 }
		startdate = { year = 1180 month = january day = 1 }
		enddate = { year = 1183 month = april day = 26 }
	}
	marrige = {
		primary = { type = 10 id = 21718 }
		secondary = { type = 10 id = 22546 }
		startdate = { year = 1125 month = january day = 1 }
		enddate = { year = 1151 month = january day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 21735 }
		secondary = { type = 10 id = 1512 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21755 }
		secondary = { type = 10 id = 21567 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21760 }
		secondary = { type = 10 id = 21761 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1178 month = may day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 22000 }
		secondary = { type = 10 id = 22001 }
		startdate = { year = 850 month = january day = 1 }
		enddate = { year = 879 month = october day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22002 }
		secondary = { type = 10 id = 22003 }
		startdate = { year = 920 month = january day = 1 }
		enddate = { year = 945 month = october day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22004 }
		secondary = { type = 10 id = 22005 }
		startdate = { year = 955 month = january day = 1 }
		enddate = { year = 972 month = october day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22006 }
		secondary = { type = 10 id = 22007 }
		startdate = { year = 977 month = january day = 1 }
		enddate = { year = 986 month = october day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22500 }
		secondary = { type = 10 id = 22501 }
		startdate = { year = 1150 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22502 }
		secondary = { type = 10 id = 19525 }
		startdate = { year = 1117 month = january day = 1 }
		enddate = { year = 1153 month = february day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22504 }
		secondary = { type = 10 id = 22505 }
		startdate = { year = 1166 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22520 }
		secondary = { type = 10 id = 22521 }
		startdate = { year = 1178 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22522 }
		secondary = { type = 10 id = 21514 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1170 month = august day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 22542 }
		secondary = { type = 10 id = 22543 }
		startdate = { year = 1139 month = january day = 1 }
		enddate = { year = 1156 month = april day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 22552 }
		secondary = { type = 10 id = 22553 }
		startdate = { year = 1169 month = january day = 1 }
		enddate = { year = 1186 month = december day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 22574 }
		secondary = { type = 10 id = 22575 }
		startdate = { year = 1095 month = january day = 1 }
		enddate = { year = 1122 month = february day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 22574 }
		secondary = { type = 10 id = 22576 }
		startdate = { year = 1122 month = january day = 1 }
		enddate = { year = 1132 month = april day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 22577 }
		secondary = { type = 10 id = 22578 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1180 month = april day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 22579 }
		secondary = { type = 10 id = 22581 }
		startdate = { year = 1168 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22595 }
		secondary = { type = 10 id = 22594 }
		startdate = { year = 1113 month = january day = 1 }
		enddate = { year = 1130 month = april day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 22600 }
		secondary = { type = 10 id = 22601 }
		startdate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22602 }
		secondary = { type = 10 id = 22603 }
		startdate = { year = 1116 month = january day = 1 }
		enddate = { year = 1146 month = august day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22620 }
		secondary = { type = 10 id = 22621 }
		startdate = { year = 1166 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22622 }
		secondary = { type = 10 id = 22623 }
		startdate = { year = 1148 month = january day = 1 }
		enddate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22630 }
		secondary = { type = 10 id = 22631 }
		startdate = { year = 1169 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22632 }
		secondary = { type = 10 id = 22633 }
		startdate = { year = 1135 month = january day = 1 }
		enddate = { year = 1164 month = february day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 22640 }
		secondary = { type = 10 id = 22641 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22650 }
		secondary = { type = 10 id = 22651 }
		startdate = { year = 1143 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22652 }
		secondary = { type = 10 id = 21523 }
		startdate = { year = 1178 month = november day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22655 }
		secondary = { type = 10 id = 22656 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22658 }
		secondary = { type = 10 id = 22659 }
		startdate = { year = 1182 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22660 }
		secondary = { type = 10 id = 22661 }
		startdate = { year = 1178 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22670 }
		secondary = { type = 10 id = 22671 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22672 }
		secondary = { type = 10 id = 22673 }
		startdate = { year = 1108 month = january day = 1 }
		enddate = { year = 1124 month = september day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 22676 }
		secondary = { type = 10 id = 22677 }
		startdate = { year = 1147 month = january day = 1 }
		enddate = { year = 1174 month = june day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 22682 }
		secondary = { type = 10 id = 22683 }
		startdate = { year = 1175 month = january day = 1 }
		enddate = { year = 1176 month = june day = 20 }
	}
	marrige = {
		primary = { type = 10 id = 22730 }
		secondary = { type = 10 id = 22551 }
		startdate = { year = 1181 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22740 }
		secondary = { type = 10 id = 22741 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22792 }
		secondary = { type = 10 id = 21511 }
		startdate = { year = 1137 month = january day = 1 }
		enddate = { year = 1139 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22795 }
		secondary = { type = 10 id = 22796 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1158 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22693 }
		secondary = { type = 10 id = 22694 }
		startdate = { year = 1019 month = january day = 1 }
		enddate = { year = 1050 month = december day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23003 }
		secondary = { type = 10 id = 23004 }
		startdate = { year = 1181 month = january day = 1 }
		enddate = { year = 1186 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 23020 }
		secondary = { type = 10 id = 23015 }
		startdate = { year = 1175 month = january day = 1 }
		enddate = { year = 1185 month = january day = 0 }
	}
	marrige = {
		primary = { type = 10 id = 23026 }
		secondary = { type = 10 id = 23027 }
		startdate = { year = 1150 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23032 }
		secondary = { type = 10 id = 23033 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1170 month = december day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23034 }
		secondary = { type = 10 id = 23035 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23500 }
		secondary = { type = 10 id = 23522 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23505 }
		secondary = { type = 10 id = 23582 }
		startdate = { year = 1175 month = october day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 23540 }
		secondary = { type = 10 id = 23522 }
		startdate = { year = 1168 month = january day = 1 }
		enddate = { year = 1177 month = april day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 23520 }
		secondary = { type = 10 id = 15560 }
		startdate = { year = 1167 month = january day = 1 }
		enddate = { year = 1174 month = march day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 23520 }
		secondary = { type = 10 id = 23521 }
		startdate = { year = 1158 month = january day = 1 }
		enddate = { year = 1160 month = march day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 23560 }
		secondary = { type = 10 id = 23524 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23561 }
		secondary = { type = 10 id = 23592 }
		startdate = { year = 1163 month = january day = 1 }
		enddate = { year = 1172 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23570 }
		secondary = { type = 10 id = 15560 }
		startdate = { year = 1174 month = december day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 23580 }
		secondary = { type = 10 id = 23581 }
		startdate = { year = 1129 month = january day = 1 }
		enddate = { year = 1150 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23585 }
		secondary = { type = 10 id = 23586 }
		startdate = { year = 1158 month = january day = 1 }
		enddate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23590 }
		secondary = { type = 10 id = 23720 }
		startdate = { year = 1154 month = january day = 1 }
		enddate = { year = 1163 month = april day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 23590 }
		secondary = { type = 10 id = 23592 }
		startdate = { year = 1182 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23595 }
		secondary = { type = 10 id = 23594 }
		startdate = { year = 1169 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23600 }
		secondary = { type = 10 id = 23601 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1135 month = june day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 23650 }
		secondary = { type = 10 id = 23685 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23660 }
		secondary = { type = 10 id = 23661 }
		startdate = { year = 1139 month = january day = 1 }
		enddate = { year = 1152 month = march day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 23670 }
		secondary = { type = 10 id = 5513 }
		startdate = { year = 114 month = january day = 1 }
		enddate = { year = 1137 month = july day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 23700 }
		secondary = { type = 10 id = 23532 }
		startdate = { year = 1126 month = january day = 1 }
		enddate = { year = 1130 month = july day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 23710 }
		secondary = { type = 10 id = 5511 }
		startdate = { year = 1107 month = january day = 1 }
		enddate = { year = 1111 month = july day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 23740 }
		secondary = { type = 10 id = 23720 }
		startdate = { year = 1136 month = january day = 1 }
		enddate = { year = 1149 month = may day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 23750 }
		secondary = { type = 10 id = 23751 }
		startdate = { year = 1170 month = january day = 1 }
		enddate = { year = 1175 month = february day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 23750 }
		secondary = { type = 10 id = 23752 }
		startdate = { year = 1176 month = january day = 1 }
		enddate = { year = 1180 month = february day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 23750 }
		secondary = { type = 10 id = 23753 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 31013 }
		secondary = { type = 10 id = 31014 }
		startdate = { year = 1120 month = january day = 1 }
		enddate = { year = 1149 month = february day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 31027 }
		secondary = { type = 10 id = 12854 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 31053 }
		secondary = { type = 10 id = 31050 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15531 }
		secondary = { type = 10 id = 5519 }
		startdate = { year = 1160 month = january day = 1 }
		enddate = { year = 1183 month = october day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 15529 }
		secondary = { type = 10 id = 5519 }
		startdate = { year = 1183 month = january day = 1 }
		enddate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15530 }
		secondary = { type = 10 id = 23743 }
		startdate = { year = 1161 month = december day = 24 }
		enddate = { year = 1180 month = september day = 24 }
	}
	marrige = {
		primary = { type = 10 id = 31057 }
		secondary = { type = 10 id = 15533 }
		startdate = { year = 1122 month = january day = 1 }
		enddate = { year = 1144 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15060 }
		secondary = { type = 10 id = 15534 }
		startdate = { year = 1155 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23025 }
		secondary = { type = 10 id = 31058 }
		startdate = { year = 1078 month = january day = 1 }
		enddate = { year = 1118 month = august day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 23023 }
		secondary = { type = 10 id = 31060 }
		startdate = { year = 1104 month = january day = 1 }
		enddate = { year = 1134 month = august day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 31067 }
		secondary = { type = 10 id = 31066 }
		startdate = { year = 1158 month = september day = 1 }
		enddate = { year = 1162 month = february day = 10 }
	}
	marrige = {
		primary = { type = 10 id = 15513 }
		secondary = { type = 10 id = 31068 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23525 }
		secondary = { type = 10 id = 32009 }
		startdate = { year = 1110 month = january day = 1 }
		enddate = { year = 1126 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23525 }
		secondary = { type = 10 id = 32006 }
		startdate = { year = 1129 month = january day = 1 }
		enddate = { year = 1144 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 68311 }
		secondary = { type = 10 id = 5853 }
		startdate = { year = 1181 month = january day = 1 }
		enddate = { year = 1181 month = december day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 13141 }
		secondary = { type = 10 id = 5853 }
		startdate = { year = 1182 month = january day = 1 }
		enddate = { year = 1186 month = october day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 23012 }
		secondary = { type = 10 id = 23011 }
		startdate = { year = 1100 month = january day = 1 }
		enddate = { year = 1120 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32015 }
		secondary = { type = 10 id = 32014 }
		startdate = { year = 1124 month = january day = 1 }
		enddate = { year = 1151 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32019 }
		secondary = { type = 10 id = 32018 }
		startdate = { year = 1066 month = january day = 1 }
		enddate = { year = 1093 month = november day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 13526 }
		secondary = { type = 10 id = 13528 }
		startdate = { year = 1180 month = january day = 1 }
		enddate = { year = 1183 month = january day = 1}
	}
	marrige = {
		primary = { type = 10 id = 32512 }
		secondary = { type = 10 id = 32513 }
		startdate = { year = 1125 month = january day = 1 }
		enddate = { year = 1149 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15035 }
		secondary = { type = 10 id = 32505 }
		startdate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 25005 }
		secondary = { type = 10 id = 32517 }
		startdate = { year = 1162 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15014 }
		secondary = { type = 10 id = 32526 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32530 }
		secondary = { type = 10 id = 15534 } 
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1154 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32531 } 
		secondary = { type = 10 id = 15532 } 
		startdate = { year = 1097 month = january day = 1 }
		enddate = { year = 1136 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32533 } 
		secondary = { type = 10 id = 32516 } 
		startdate = { year = 1047 month = january day = 1 }
		enddate = { year = 1161 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15005 } 
		secondary = { type = 10 id = 32534 } 
		startdate = { year = 1172 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32535 } 
		secondary = { type = 10 id = 15511 } 
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15060 } 
		secondary = { type = 10 id = 32536 } 
		startdate = { year = 1169 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15009 } 
		secondary = { type = 10 id = 15510 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32542 } 
		secondary = { type = 10 id = 32543 } 
		startdate = { year = 1133 month = january day = 1 }
		enddate = { year = 1146 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32544 } 
		secondary = { type = 10 id = 32545 } 
		startdate = { year = 1152 month = january day = 1 }
		enddate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15500 } 
		secondary = { type = 10 id = 32548 } 
		startdate = { year = 1172 month = january day = 1 }
		enddate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32553 } 
		secondary = { type = 10 id = 32554 } 
		startdate = { year = 1136 month = january day = 1 }
		enddate = { year = 1156 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15503 }
		secondary = { type = 10 id = 15535 }
		startdate = { year = 1169 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13119 }
		secondary = { type = 10 id = 32558 }
		startdate = { year = 1090 month = january day = 1 }
		enddate = { year = 1103 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32559 }
		secondary = { type = 10 id = 32558 }
		startdate = { year = 1105 month = january day = 1 }
		enddate = { year = 1135 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32508 }
		secondary = { type = 10 id = 32511 }
		startdate = { year = 1145 month = january day = 1 }
		enddate = { year = 1167 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32561 }
		secondary = { type = 10 id = 32562 } 
		startdate = { year = 1058 month = january day = 1 }
		enddate = { year = 1089 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 31012 } 
		secondary = { type = 10 id = 32566 }
		startdate = { year = 1101 month = january day = 1 }
		enddate = { year = 1118 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23014 }
		secondary = { type = 10 id = 32567 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1159 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23010 }
		secondary = { type = 10 id = 23029 }
		startdate = { year = 1143 month = january day = 1 }
		enddate = { year = 1059 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32576 }
		secondary = { type = 10 id = 32577 }
		startdate = { year = 1099 month = january day = 1 }
		enddate = { year = 1113 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32578 }
		secondary = { type = 10 id = 32579 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1075 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32571 }
		secondary = { type = 10 id = 32581 }
		startdate = { year = 1151 month = january day = 1 }
		enddate = { year = 1075 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32591 }
		secondary = { type = 10 id = 32582 }
		startdate = { year = 1153 month = january day = 1 }
		enddate = { year = 1065 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32595 }
		secondary = { type = 10 id = 32590 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32597 }
		secondary = { type = 10 id = 32598 }
		startdate = { year = 1165 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32599 }
		secondary = { type = 10 id = 32601 }
		startdate = { year = 1165 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32698 }
		secondary = { type = 10 id = 32699 }
		startdate = { year = 1110 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32700 }
		secondary = { type = 10 id = 32701 }
		startdate = { year = 1140 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 31015 }
		secondary = { type = 10 id = 32704 }
		startdate = { year = 1176 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32703 }
		secondary = { type = 10 id = 32705 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32753 }
		secondary = { type = 10 id = 32750 }
		startdate = { year = 1116 month = january day = 1 }
		enddate = { year = 1154 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 16523 }
		secondary = { type = 10 id = 32751 }
		startdate = { year = 1116 month = january day = 1 }
		enddate = { year = 1133 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22525 }
		secondary = { type = 10 id = 32752 }
		startdate = { year = 1153 month = january day = 1 }
		enddate = { year = 1154 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4772 }
		secondary = { type = 10 id = 4540 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 32002 }
		secondary = { type = 10 id = 14802 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 101920 }
		secondary = { type = 10 id = 14711 }
		startdate = { year = 1120 month = january day = 1 }
		enddate = { year = 1133 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 101920 }
		secondary = { type = 10 id = 14806 }
		startdate = { year = 1134 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14709 }
		secondary = { type = 10 id = 14814 }
		startdate = { year = 1085 month = january day = 1 }
		enddate = { year = 1137 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 3005 }
		secondary = { type = 10 id = 282001 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14590 }
		secondary = { type = 10 id = 282038 }
		startdate = { year = 1135 month = january day = 1 }
		enddate = { year = 1168 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 32752 }
		secondary = { type = 10 id = 16525 }
		startdate = { year = 1186 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 13523 }
		secondary = { type = 10 id = 32560 }
		startdate = { year = 1186 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 4500 }
		secondary = { type = 10 id = 4514 }
		startdate = { year = 1186 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 12507 }
		secondary = { type = 10 id = 13100 }
		startdate = { year = 1186 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 1500 }
		secondary = { type = 10 id = 1520 }
		startdate = { year = 1186 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 2500 }
		secondary = { type = 10 id = 2030 }
		startdate = { year = 1186 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 23500 }
		secondary = { type = 10 id = 23560 }
		startdate = { year = 1186 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 32011 }
		secondary = { type = 10 id = 5853 }
		startdate = { year = 1186 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 5730 }
		secondary = { type = 10 id = 4510 }
		startdate = { year = 1186 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 5506 }
		secondary = { type = 10 id = 4510 }
		startdate = { year = 1186 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 2502 }
		secondary = { type = 10 id = 32686 }
		startdate = { year = 1186 month = january day = 1 }
	}
	friend = {
		primary = { type = 10 id = 14800 }
		secondary = { type = 10 id = 4500 }
		startdate = { year = 1186 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 4500 }
		secondary = { type = 10 id = 4510 }
		startdate = { year = 1186 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 4514 }
		secondary = { type = 10 id = 4510 }
		startdate = { year = 1186 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 12501 }
		secondary = { type = 10 id = 12600 }
		startdate = { year = 1186 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 12507 }
		secondary = { type = 10 id = 12600 }
		startdate = { year = 1186 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 2500 }
		secondary = { type = 10 id = 2005 }
		startdate = { year = 1186 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 15500 }
		secondary = { type = 10 id = 15060 }
		startdate = { year = 1186 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 15500 }
		secondary = { type = 10 id = 15503 }
		startdate = { year = 1186 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 20022 }
		secondary = { type = 10 id = 20046 }
		startdate = { year = 1186 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 32002 }
		secondary = { type = 10 id = 14700 }
		startdate = { year = 1186 month = january day = 1 }
	}
	rival = {
		primary = { type = 10 id = 4500 }
		secondary = { type = 10 id = 5730 }
		startdate = { year = 1152 month = may day = 18 }
	}
}