country = {
	tag = C001
	form_of_goverment = republican
	capital = 1
	ruler = { character = { type = 10 id = 2024 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes ecclesical_balance = yes }
	controlledprovinces = { 1 }
}
country = {
	tag = C003
	form_of_goverment = feudal
	capital = 3
	ruler = { character = { type = 10 id = 14006 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 3 }
}
country = {
	tag = C004
	form_of_goverment = feudal
	capital = 4
	ruler = { character = { type = 10 id = 14007 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 4 }
}
country = {
	tag = C005
	form_of_goverment = feudal
	capital = 5
	ruler = { character = { type = 10 id = 14000 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 5 }
}
country = {
	tag = C006
	form_of_goverment = feudal
	capital = 6
	ruler = { character = { type = 10 id = 14 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 6 }
}
country = {
	tag = C007
	form_of_goverment = feudal
	capital = 7
	ruler = { character = { type = 10 id = 14020 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 7 }
}
country = {
	tag = C012
	form_of_goverment = feudal
	capital = 12
	ruler = { character = { type = 10 id = 14580 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 12 }
}
country = {
	tag = C014
	form_of_goverment = feudal
	capital = 14
	ruler = { character = { type = 10 id = 14600 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 14 }
}
country = {
	tag = C015
	form_of_goverment = feudal
	capital = 15
	ruler = { character = { type = 10 id = 4038 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 15 }
}
country = {
	tag = C016
	form_of_goverment = feudal
	capital = 16
	ruler = { character = { type = 10 id = 14553 } startdate = { year = 1187 month = january day = 0 } }
	laws = { monastic_supremacy = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 16 }
}
country = {
	tag = C017
	form_of_goverment = feudal
	capital = 17
	ruler = { character = { type = 10 id = 4600 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 17 }
}
country = {
	tag = C018
	form_of_goverment = feudal
	capital = 18
	ruler = { character = { type = 10 id = 4772 } startdate = { year = 1187 month = january day = 0 } }
	laws = { traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 18 }
}
country = {
	tag = C020
	form_of_goverment = feudal
	capital = 20
	ruler = { character = { type = 10 id = 4004 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 20 }
}
country = {
	tag = C021
	form_of_goverment = feudal
	capital = 21
	ruler = { character = { type = 10 id = 4592 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 21 }
}
country = {
	tag = C022
	form_of_goverment = feudal
	capital = 22
	ruler = { character = { type = 10 id = 4550 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 22 }
}
country = {
	tag = C023
	form_of_goverment = feudal
	capital = 23
	ruler = { character = { type = 10 id = 4530 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 23 }
}
country = {
	tag = C024
	form_of_goverment = feudal
	capital = 24
	ruler = { character = { type = 10 id = 4630 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 24 }
}
country = {
	tag = C025
	form_of_goverment = feudal
	capital = 25
	ruler = { character = { type = 10 id = 4750 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 25 }
}
country = {
	tag = C026
	form_of_goverment = feudal
	capital = 26
	ruler = { character = { type = 10 id = 4780 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 26 }
}
country = {
	tag = C029
	form_of_goverment = feudal
	capital = 29
	ruler = { character = { type = 10 id = 4658 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 29 }
}
country = {
	tag = C033
	form_of_goverment = feudal
	capital = 33
	ruler = { character = { type = 10 id = 2013 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 33 }
}
country = {
	tag = C039
	form_of_goverment = feudal
	capital = 39
	ruler = { character = { type = 10 id = 3003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 39 38 }
}
country = {
	tag = C040
	form_of_goverment = feudal
	capital = 40
	ruler = { character = { type = 10 id = 2971 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 40 }
}
country = {
	tag = C041
	form_of_goverment = feudal
	capital = 41
	ruler = { character = { type = 10 id = 32602 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 41 }
}
country = {
	tag = C042
	form_of_goverment = feudal
	capital = 42
	ruler = { character = { type = 10 id = 3006 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 42 }
}
country = {
	tag = C043
	form_of_goverment = feudal
	capital = 43
	ruler = { character = { type = 10 id = 3021 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 43 }
}
country = {
	tag = C045
	form_of_goverment = feudal
	capital = 45
	ruler = { character = { type = 10 id = 32683 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 45 }
}
country = {
	tag = C046
	form_of_goverment = feudal
	capital = 46
	ruler = { character = { type = 10 id = 3010 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 46 }
}
country = {
	tag = C047
	form_of_goverment = feudal
	capital = 47
	ruler = { character = { type = 10 id = 3011 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 47 }
}
country = {
	tag = C049
	form_of_goverment = feudal
	capital = 49
	ruler = { character = { type = 10 id = 3540 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 49 }
}
country = {
	tag = C051
	form_of_goverment = feudal
	capital = 51
	ruler = { character = { type = 10 id = 3014 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 51 }
}
country = {
	tag = C052
	form_of_goverment = feudal
	capital = 52
	ruler = { character = { type = 10 id = 3520 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 52 }
}
country = {
	tag = C054
	form_of_goverment = feudal
	capital = 54
	ruler = { character = { type = 10 id = 20021 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 54 }
}
country = {
	tag = C056
	form_of_goverment = feudal
	capital = 56
	ruler = { character = { type = 10 id = 4520 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 56 }
}
country = {
	tag = C059
	form_of_goverment = feudal
	capital = 59
	ruler = { character = { type = 10 id = 4680 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 59 100 }
}
country = {
	tag = C062
	form_of_goverment = feudal
	capital = 62
	ruler = { character = { type = 10 id = 4580 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 62 }
}
country = {
	tag = C063
	form_of_goverment = feudal
	capital = 63
	ruler = { character = { type = 10 id = 4690 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 63 }
}
country = {
	tag = C064
	form_of_goverment = feudal
	capital = 64
	ruler = { character = { type = 10 id = 32002 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 64 }
}
country = {
	tag = C065
	form_of_goverment = feudal
	capital = 65
	ruler = { character = { type = 10 id = 14720 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 65 }
}
country = {
	tag = C066
	form_of_goverment = feudal
	capital = 66
	ruler = { character = { type = 10 id = 3044 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 66 }
}
country = {
	tag = C067
	form_of_goverment = feudal
	capital = 67
	ruler = { character = { type = 10 id = 4710 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 67 }
}
country = {
	tag = C069
	form_of_goverment = feudal
	capital = 69
	ruler = { character = { type = 10 id = 4595 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 69 }
}
country = {
	tag = C070
	form_of_goverment = feudal
	capital = 70
	ruler = { character = { type = 10 id = 4730 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 70 71 }
}
country = {
	tag = C072
	form_of_goverment = feudal
	capital = 72
	ruler = { character = { type = 10 id = 4740 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 72 }
}
country = {
	tag = C074
	form_of_goverment = feudal
	capital = 74
	ruler = { character = { type = 10 id = 32011 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 75 }
}
country = {
	tag = C075
	form_of_goverment = feudal
	capital = 75
	ruler = { character = { type = 10 id = 5853 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 75 }
}
country = {
	tag = C081
	form_of_goverment = republican
	capital = 81
	ruler = { character = { type = 10 id = 31003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 81 }
}
country = {
	tag = C082
	form_of_goverment = ecclestical
	capital = 82
	ruler = { character = { type = 10 id = 6847 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 82 }
}
country = {
	tag = C083
	form_of_goverment = feudal
	capital = 83
	ruler = { character = { type = 10 id = 6831 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 83 }
}
country = {
	tag = C085
	form_of_goverment = republican
	capital = 85
	ruler = { character = { type = 10 id = 31004 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 85 }
}
country = {
	tag = C086
	form_of_goverment = feudal
	capital = 86
	ruler = { character = { type = 10 id = 12910 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 86 }
}
country = {
	tag = C087
	form_of_goverment = ecclestical
	capital = 87
	ruler = { character = { type = 10 id = 31042 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 87 }
}
country = {
	tag = C088
	form_of_goverment = ecclestical
	capital = 88
	ruler = { character = { type = 10 id = 31041 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 88 }
}
country = {
	tag = C089
	form_of_goverment = feudal
	capital = 89
	ruler = { character = { type = 10 id = 12920 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 89 }
}
country = {
	tag = C090
	form_of_goverment = feudal
	capital = 90
	ruler = { character = { type = 10 id = 6900 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 90 }
}
country = {
	tag = C091
	form_of_goverment = feudal
	capital = 91
	ruler = { character = { type = 10 id = 6800 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 91 123 }
}
country = {
	tag = C094
	form_of_goverment = feudal
	capital = 94
	ruler = { character = { type = 10 id = 5520 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 94 }
}
country = {
	tag = C095
	form_of_goverment = feudal
	capital = 95
	ruler = { character = { type = 10 id = 4980 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 95 }
}
country = {
	tag = C096
	form_of_goverment = feudal
	capital = 96
	ruler = { character = { type = 10 id = 5920 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 96 }
}
country = {
	tag = C099
	form_of_goverment = feudal
	capital = 99
	ruler = { character = { type = 10 id = 5820 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 99 }
}
country = {
	tag = C102
	form_of_goverment = feudal
	capital = 102
	ruler = { character = { type = 10 id = 5742 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 102 }
}
country = {
	tag = C103
	form_of_goverment = feudal
	capital = 103
	ruler = { character = { type = 10 id = 5781 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 103 }
}
country = {
	tag = C109
	form_of_goverment = feudal
	capital = 109
	ruler = { character = { type = 10 id = 5970 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 109 107 }
}
country = {
	tag = C110
	form_of_goverment = feudal
	capital = 110
	ruler = { character = { type = 10 id = 5892 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 110 111 }
}
country = {
	tag = C114
	form_of_goverment = feudal
	capital = 114
	ruler = { character = { type = 10 id = 32017 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 114 }
}
country = {
	tag = C115
	form_of_goverment = feudal
	capital = 115
	ruler = { character = { type = 10 id = 12690 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 115 }
}
country = {
	tag = C116
	form_of_goverment = ecclestical
	capital = 116
	ruler = { character = { type = 10 id = 13148 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 116 }
}
country = {
	tag = C119
	form_of_goverment = ecclestical
	capital = 119
	ruler = { character = { type = 10 id = 13181 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 119 }
}
country = {
	tag = C121
	form_of_goverment = feudal
	capital = 121
	ruler = { character = { type = 10 id = 12370 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 121 }
}
country = {
	tag = C125
	form_of_goverment = feudal
	capital = 125
	ruler = { character = { type = 10 id = 12400 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 125 }
}
country = {
	tag = C128
	form_of_goverment = ecclestical
	capital = 128
	ruler = { character = { type = 10 id = 12001 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 128 }
}
country = {
	tag = C129
	form_of_goverment = ecclestical
	capital = 129
	ruler = { character = { type = 10 id = 12002 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 129 }
}
country = {
	tag = C133
	form_of_goverment = feudal
	capital = 133
	ruler = { character = { type = 10 id = 12630 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 133 }
}
country = {
	tag = C137
	form_of_goverment = feudal
	capital = 137
	ruler = { character = { type = 10 id = 5710 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 137 132 }
}
country = {
	tag = C142
	form_of_goverment = feudal
	capital = 142
	ruler = { character = { type = 10 id = 5930 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 142 }
}
country = {
	tag = C144
	form_of_goverment = feudal
	capital = 144
	ruler = { character = { type = 10 id = 5660 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 144 }
}
country = {
	tag = C147
	form_of_goverment = feudal
	capital = 147
	ruler = { character = { type = 10 id = 5620 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 147 }
}
country = {
	tag = C148
	form_of_goverment = feudal
	capital = 148
	ruler = { character = { type = 10 id = 5640 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 148 }
}
country = {
	tag = C150
	form_of_goverment = feudal
	capital = 150
	ruler = { character = { type = 10 id = 5630 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 150 }
}
country = {
	tag = C151
	form_of_goverment = feudal
	capital = 151
	ruler = { character = { type = 10 id = 5540 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 151 }
}
country = {
	tag = C153
	form_of_goverment = feudal
	capital = 153
	ruler = { character = { type = 10 id = 7560 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 153 }
}
country = {
	tag = C158
	form_of_goverment = ecclestical
	capital = 158
	ruler = { character = { type = 10 id = 9550 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 158 }
}
country = {
	tag = C162
	form_of_goverment = feudal
	capital = 162
	ruler = { character = { type = 10 id = 24009 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 162 }
}
country = {
	tag = C163
	form_of_goverment = feudal
	capital = 163
	ruler = { character = { type = 10 id = 24021 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 163 }
}
country = {
	tag = C164
	form_of_goverment = feudal
	capital = 164
	ruler = { character = { type = 10 id = 24022 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 164 }
}
country = {
	tag = C165
	form_of_goverment = feudal
	capital = 165
	ruler = { character = { type = 10 id = 24023 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 165 }
}
country = {
	tag = C166
	form_of_goverment = feudal
	capital = 166
	ruler = { character = { type = 10 id = 24024 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 166 }
}
country = {
	tag = C167
	form_of_goverment = feudal
	capital = 167
	ruler = { character = { type = 10 id = 24017 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 167 }
}
country = {
	tag = C169
	form_of_goverment = feudal
	capital = 169
	ruler = { character = { type = 10 id = 24012 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 169 }
}
country = {
	tag = C170
	form_of_goverment = feudal
	capital = 170
	ruler = { character = { type = 10 id = 24013 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 170 }
}
country = {
	tag = C172
	form_of_goverment = feudal
	capital = 172
	ruler = { character = { type = 10 id = 24007 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 172 }
}
country = {
	tag = C173
	form_of_goverment = feudal
	capital = 173
	ruler = { character = { type = 10 id = 10550 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 173 }
}
country = {
	tag = C178
	form_of_goverment = feudal
	capital = 178
	ruler = { character = { type = 10 id = 24002 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 178 }
}
country = {
	tag = C179
	form_of_goverment = feudal
	capital = 179
	ruler = { character = { type = 10 id = 24014 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 179 }
}
country = {
	tag = C180
	form_of_goverment = feudal
	capital = 180
	ruler = { character = { type = 10 id = 24016 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 180 }
}
country = {
	tag = C183
	form_of_goverment = feudal
	capital = 183
	ruler = { character = { type = 10 id = 24025 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 183 }
}
country = {
	tag = C184
	form_of_goverment = feudal
	capital = 184
	ruler = { character = { type = 10 id = 24010 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 184 }
}
country = {
	tag = C185
	form_of_goverment = feudal
	capital = 185
	ruler = { character = { type = 10 id = 24011 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 185 }
}
country = {
	tag = C188
	form_of_goverment = feudal
	capital = 188
	ruler = { character = { type = 10 id = 9530 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 188 }
}
country = {
	tag = C191
	form_of_goverment = ecclestical
	capital = 191
	ruler = { character = { type = 10 id = 8530 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 191 }
}
country = {
	tag = C196
	form_of_goverment = knight_order
	capital = 196
	ruler = { character = { type = 10 id = 24003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 196 }
}
country = {
	tag = C199
	form_of_goverment = feudal
	capital = 199
	ruler = { character = { type = 10 id = 7546 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 199 154 }
}
country = {
	tag = C205
	form_of_goverment = feudal
	capital = 205
	ruler = { character = { type = 10 id = 10560 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 205 }
}
country = {
	tag = C206
	form_of_goverment = feudal
	capital = 206
	ruler = { character = { type = 10 id = 10570 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 206 }
}
country = {
	tag = C208
	form_of_goverment = feudal
	capital = 208
	ruler = { character = { type = 10 id = 5560 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 208 }
}
country = {
	tag = C209
	form_of_goverment = feudal
	capital = 209
	ruler = { character = { type = 10 id = 5670 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 209 }
}
country = {
	tag = C210
	form_of_goverment = feudal
	capital = 210
	ruler = { character = { type = 10 id = 5550 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 210 }
}
country = {
	tag = C212
	form_of_goverment = feudal
	capital = 212
	ruler = { character = { type = 10 id = 7540 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 212 176 }
}
country = {
	tag = C213
	form_of_goverment = feudal
	capital = 213
	ruler = { character = { type = 10 id = 5570 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 213 }
}
country = {
	tag = C216
	form_of_goverment = feudal
	capital = 216
	ruler = { character = { type = 10 id = 5600 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 216 }
}
country = {
	tag = C217
	form_of_goverment = feudal
	capital = 217
	ruler = { character = { type = 10 id = 6030 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 217 }
}
country = {
	tag = C220
	form_of_goverment = feudal
	capital = 220
	ruler = { character = { type = 10 id = 5580 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 220 }
}
country = {
	tag = C224
	form_of_goverment = feudal
	capital = 224
	ruler = { character = { type = 10 id = 5680 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 224 }
}
country = {
	tag = C225
	form_of_goverment = feudal
	capital = 225
	ruler = { character = { type = 10 id = 5700 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 225 }
}
country = {
	tag = C226
	form_of_goverment = feudal
	capital = 226
	ruler = { character = { type = 10 id = 5690 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 226 }
}
country = {
	tag = C228
	form_of_goverment = feudal
	capital = 228
	ruler = { character = { type = 10 id = 12780 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 228 }
}
country = {
	tag = C229
	form_of_goverment = feudal
	capital = 229
	ruler = { character = { type = 10 id = 5983 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 229 }
}
country = {
	tag = C231
	form_of_goverment = feudal
	capital = 231
	ruler = { character = { type = 10 id = 13550 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 231 }
}
country = {
	tag = C232
	form_of_goverment = feudal
	capital = 232
	ruler = { character = { type = 10 id = 13520 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 232 }
}
country = {
	tag = C236
	form_of_goverment = feudal
	capital = 236
	ruler = { character = { type = 10 id = 20300 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 236 }
}
country = {
	tag = C238
	form_of_goverment = ecclestical
	capital = 238
	ruler = { character = { type = 10 id = 12020 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 238 }
}
country = {
	tag = C239
	form_of_goverment = feudal
	capital = 239
	ruler = { character = { type = 10 id = 12740 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 239 }
}
country = {
	tag = C240
	form_of_goverment = feudal
	capital = 240
	ruler = { character = { type = 10 id = 6008 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 240 }
}
country = {
	tag = C241
	form_of_goverment = feudal
	capital = 241
	ruler = { character = { type = 10 id = 12010 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 241 }
}
country = {
	tag = C242
	form_of_goverment = feudal
	capital = 242
	ruler = { character = { type = 10 id = 13160 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 242 }
}
country = {
	tag = C244
	form_of_goverment = feudal
	capital = 244
	ruler = { character = { type = 10 id = 13140 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 244 }
}
country = {
	tag = C245
	form_of_goverment = feudal
	capital = 245
	ruler = { character = { type = 10 id = 13130 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 245 }
}
country = {
	tag = C247
	form_of_goverment = ecclestical
	capital = 247
	ruler = { character = { type = 10 id = 13170 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 247 }
}
country = {
	tag = C248
	form_of_goverment = feudal
	capital = 248
	ruler = { character = { type = 10 id = 13180 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 248 }
}
country = {
	tag = C253
	form_of_goverment = feudal
	capital = 253
	ruler = { character = { type = 10 id = 12420 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 253 }
}
country = {
	tag = C255
	form_of_goverment = feudal
	capital = 255
	ruler = { character = { type = 10 id = 12430 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 255 }
}
country = {
	tag = C257
	form_of_goverment = feudal
	capital = 257
	ruler = { character = { type = 10 id = 12600 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 257 258 }
}
country = {
	tag = C260
	form_of_goverment = feudal
	capital = 260
	ruler = { character = { type = 10 id = 1001 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 260 307 }
}
country = {
	tag = C262
	form_of_goverment = feudal
	capital = 262
	ruler = { character = { type = 10 id = 12360 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 262 261 }
}
country = {
	tag = C265
	form_of_goverment = feudal
	capital = 265
	ruler = { character = { type = 10 id = 1537 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 265 }
}
country = {
	tag = C267
	form_of_goverment = feudal
	capital = 267
	ruler = { character = { type = 10 id = 1005 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 267 }
}
country = {
	tag = C268
	form_of_goverment = feudal
	capital = 268
	ruler = { character = { type = 10 id = 2001 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 268 }
}
country = {
	tag = C269
	form_of_goverment = feudal
	capital = 269
	ruler = { character = { type = 10 id = 2002 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 269 }
}
country = {
	tag = C270
	form_of_goverment = feudal
	capital = 270
	ruler = { character = { type = 10 id = 2003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 270 }
}
country = {
	tag = C271
	form_of_goverment = feudal
	capital = 271
	ruler = { character = { type = 10 id = 2004 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 271 }
}
country = {
	tag = C273
	form_of_goverment = feudal
	capital = 273
	ruler = { character = { type = 10 id = 2006 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 273 }
}
country = {
	tag = C275
	form_of_goverment = feudal
	capital = 275
	ruler = { character = { type = 10 id = 2007 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 275 }
}
country = {
	tag = C276
	form_of_goverment = feudal
	capital = 276
	ruler = { character = { type = 10 id = 2008 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 276 }
}
country = {
	tag = C278
	form_of_goverment = feudal
	capital = 278
	ruler = { character = { type = 10 id = 2010 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 278 }
}
country = {
	tag = C280
	form_of_goverment = feudal
	capital = 280
	ruler = { character = { type = 10 id = 1 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 280 }
}
country = {
	tag = C281
	form_of_goverment = feudal
	capital = 281
	ruler = { character = { type = 10 id = 2 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 281 }
}
country = {
	tag = C282
	form_of_goverment = republican
	capital = 282
	ruler = { character = { type = 10 id = 3 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes ecclesical_balance = yes }
	controlledprovinces = { 282 }
}
country = {
	tag = C283
	form_of_goverment = feudal
	capital = 283
	ruler = { character = { type = 10 id = 4 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 283 }
}
country = {
	tag = C284
	form_of_goverment = feudal
	capital = 284
	ruler = { character = { type = 10 id = 5 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 284 }
}
country = {
	tag = C285
	form_of_goverment = feudal
	capital = 285
	ruler = { character = { type = 10 id = 6 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 285 }
}
country = {
	tag = C286
	form_of_goverment = feudal
	capital = 286
	ruler = { character = { type = 10 id = 7 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 286 }
}
country = {
	tag = C287
	form_of_goverment = feudal
	capital = 287
	ruler = { character = { type = 10 id = 8 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 287 }
}
country = {
	tag = C288
	form_of_goverment = feudal
	capital = 288
	ruler = { character = { type = 10 id = 9 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 288 }
}
country = {
	tag = C289
	form_of_goverment = feudal
	capital = 289
	ruler = { character = { type = 10 id = 18 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 289 }
}
country = {
	tag = C291
	form_of_goverment = feudal
	capital = 291
	ruler = { character = { type = 10 id = 17 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 291 }
}
country = {
	tag = C295
	form_of_goverment = feudal
	capital = 295
	ruler = { character = { type = 10 id = 10 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 295 }
}
country = {
	tag = C296
	form_of_goverment = feudal
	capital = 296
	ruler = { character = { type = 10 id = 2021 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 296 }
}
country = {
	tag = C298
	form_of_goverment = feudal
	capital = 298
	ruler = { character = { type = 10 id = 11 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 298 }
}
country = {
	tag = C299
	form_of_goverment = feudal
	capital = 299
	ruler = { character = { type = 10 id = 12 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 299 }
}
country = {
	tag = C300
	form_of_goverment = feudal
	capital = 300
	ruler = { character = { type = 10 id = 13 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 300 }
}
country = {
	tag = C301
	form_of_goverment = republican
	capital = 301
	ruler = { character = { type = 10 id = 15 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes ecclesical_balance = yes }
	controlledprovinces = { 301 }
}
country = {
	tag = C304
	form_of_goverment = feudal
	capital = 304
	ruler = { character = { type = 10 id = 21735 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 304 }
}
country = {
	tag = C306
	form_of_goverment = feudal
	capital = 306
	ruler = { character = { type = 10 id = 1008 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 306 }
}
country = {
	tag = C311
	form_of_goverment = feudal
	capital = 311
	ruler = { character = { type = 10 id = 12366 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 311 }
}
country = {
	tag = C314
	form_of_goverment = feudal
	capital = 314
	ruler = { character = { type = 10 id = 12390 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 314 }
}
country = {
	tag = C315
	form_of_goverment = feudal
	capital = 315
	ruler = { character = { type = 10 id = 12964 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 315 }
}
country = {
	tag = C316
	form_of_goverment = feudal
	capital = 316
	ruler = { character = { type = 10 id = 12380 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 316 }
}
country = {
	tag = C318
	form_of_goverment = republican
	capital = 318
	ruler = { character = { type = 10 id = 13007 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 318 }
}
country = {
	tag = C320
	form_of_goverment = republican
	capital = 320
	ruler = { character = { type = 10 id = 13008 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 320 }
}
country = {
	tag = C322
	form_of_goverment = republican
	capital = 322
	ruler = { character = { type = 10 id = 13012 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 322 }
}
country = {
	tag = C328
	form_of_goverment = republican
	capital = 328
	ruler = { character = { type = 10 id = 13014 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 328 }
}
country = {
	tag = C329
	form_of_goverment = feudal
	capital = 329
	ruler = { character = { type = 10 id = 13026 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 329 }
}
country = {
	tag = C330
	form_of_goverment = republican
	capital = 330
	ruler = { character = { type = 10 id = 13017 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 330 }
}
country = {
	tag = C332
	form_of_goverment = republican
	capital = 332
	ruler = { character = { type = 10 id = 13016 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 332 }
}
country = {
	tag = C335
	form_of_goverment = feudal
	capital = 335
	ruler = { character = { type = 10 id = 11523 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 335 }
}
country = {
	tag = C344
	form_of_goverment = feudal
	capital = 344
	ruler = { character = { type = 10 id = 11516 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 344 }
}
country = {
	tag = C345
	form_of_goverment = feudal
	capital = 345
	ruler = { character = { type = 10 id = 11509 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 345 }
}
country = {
	tag = C350
	form_of_goverment = republican
	capital = 350
	ruler = { character = { type = 10 id = 13025 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes ecclesical_balance = yes }
	controlledprovinces = { 350 }
}
country = {
	tag = C351
	form_of_goverment = ecclestical
	capital = 351
	ruler = { character = { type = 10 id = 13010 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 351 }
}
country = {
	tag = C352
	form_of_goverment = republican
	capital = 352
	ruler = { character = { type = 10 id = 13011 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 352 }
}
country = {
	tag = C354
	form_of_goverment = republican
	capital = 354
	ruler = { character = { type = 10 id = 13024 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 354 }
}
country = {
	tag = C355
	form_of_goverment = republican
	capital = 355
	ruler = { character = { type = 10 id = 13022 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 355 }
}
country = {
	tag = C357
	form_of_goverment = feudal
	capital = 357
	ruler = { character = { type = 10 id = 13023 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 357 }
}
country = {
	tag = C358
	form_of_goverment = ecclestical
	capital = 358
	ruler = { character = { type = 10 id = 12070 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 358 }
}
country = {
	tag = C362
	form_of_goverment = feudal
	capital = 362
	ruler = { character = { type = 10 id = 12855 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 362 }
}
country = {
	tag = C364
	form_of_goverment = feudal
	capital = 364
	ruler = { character = { type = 10 id = 12938 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 364 }
}
country = {
	tag = C367
	form_of_goverment = feudal
	capital = 367
	ruler = { character = { type = 10 id = 21720 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 367 }
}
country = {
	tag = C376
	form_of_goverment = feudal
	capital = 376
	ruler = { character = { type = 10 id = 28021 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 376 }
}
country = {
	tag = C378
	form_of_goverment = feudal
	capital = 378
	ruler = { character = { type = 10 id = 28024 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 378 }
}
country = {
	tag = C379
	form_of_goverment = feudal
	capital = 379
	ruler = { character = { type = 10 id = 28025 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 379 }
}
country = {
	tag = C385
	form_of_goverment = feudal
	capital = 385
	ruler = { character = { type = 10 id = 28008 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 385 }
}
country = {
	tag = C390
	form_of_goverment = feudal
	capital = 390
	ruler = { character = { type = 10 id = 28005 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 390 }
}
country = {
	tag = C393
	form_of_goverment = feudal
	capital = 393
	ruler = { character = { type = 10 id = 22021 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 393 }
}
country = {
	tag = C394
	form_of_goverment = feudal
	capital = 394
	ruler = { character = { type = 10 id = 22022 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 394 }
}
country = {
	tag = C395
	form_of_goverment = feudal
	capital = 395
	ruler = { character = { type = 10 id = 22023 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 395 }
}
country = {
	tag = C396
	form_of_goverment = feudal
	capital = 396
	ruler = { character = { type = 10 id = 22024 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 396 }
}
country = {
	tag = C397
	form_of_goverment = feudal
	capital = 397
	ruler = { character = { type = 10 id = 22025 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 397 }
}
country = {
	tag = C398
	form_of_goverment = feudal
	capital = 398
	ruler = { character = { type = 10 id = 22026 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 398 }
}
country = {
	tag = C399
	form_of_goverment = feudal
	capital = 399
	ruler = { character = { type = 10 id = 22027 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 399 }
}
country = {
	tag = C400
	form_of_goverment = feudal
	capital = 400
	ruler = { character = { type = 10 id = 29001 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 400 }
}
country = {
	tag = C401
	form_of_goverment = feudal
	capital = 401
	ruler = { character = { type = 10 id = 29002 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 401 402 }
}
country = {
	tag = C403
	form_of_goverment = feudal
	capital = 403
	ruler = { character = { type = 10 id = 22029 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 403 }
}
country = {
	tag = C409
	form_of_goverment = feudal
	capital = 409
	ruler = { character = { type = 10 id = 22030 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 409 }
}
country = {
	tag = C410
	form_of_goverment = feudal
	capital = 0
	ruler = { character = { type = 10 id = 22020 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { }
}
country = {
	tag = C412
	form_of_goverment = feudal
	capital = 412
	ruler = { character = { type = 10 id = 22031 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 412 }
}
country = {
	tag = C413
	form_of_goverment = feudal
	capital = 413
	ruler = { character = { type = 10 id = 22610 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 413 }
}
country = {
	tag = C414
	form_of_goverment = feudal
	capital = 414
	ruler = { character = { type = 10 id = 22033 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 414 }
}
country = {
	tag = C415
	form_of_goverment = feudal
	capital = 415
	ruler = { character = { type = 10 id = 22034 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 415 }
}
country = {
	tag = C417
	form_of_goverment = feudal
	capital = 417
	ruler = { character = { type = 10 id = 22560 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 417 }
}
country = {
	tag = C418
	form_of_goverment = feudal
	capital = 418
	ruler = { character = { type = 10 id = 22810 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 418 }
}
country = {
	tag = C420
	form_of_goverment = feudal
	capital = 420
	ruler = { character = { type = 10 id = 28013 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 420 }
}
country = {
	tag = C421
	form_of_goverment = feudal
	capital = 421
	ruler = { character = { type = 10 id = 28014 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 421 423 }
}
country = {
	tag = C422
	form_of_goverment = feudal
	capital = 422
	ruler = { character = { type = 10 id = 28018 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 422 }
}
country = {
	tag = C427
	form_of_goverment = feudal
	capital = 427
	ruler = { character = { type = 10 id = 28019 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 427 }
}
country = {
	tag = C428
	form_of_goverment = feudal
	capital = 428
	ruler = { character = { type = 10 id = 21565 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 428 }
}
country = {
	tag = C430
	form_of_goverment = feudal
	capital = 430
	ruler = { character = { type = 10 id = 20390 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 430 }
}
country = {
	tag = C433
	form_of_goverment = feudal
	capital = 433
	ruler = { character = { type = 10 id = 21532 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 433 }
}
country = {
	tag = C442
	form_of_goverment = feudal
	capital = 442
	ruler = { character = { type = 10 id = 19001 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 442 443 }
}
country = {
	tag = C444
	form_of_goverment = feudal
	capital = 444
	ruler = { character = { type = 10 id = 19003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 444 }
}
country = {
	tag = C445
	form_of_goverment = feudal
	capital = 445
	ruler = { character = { type = 10 id = 19004 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 445 }
}
country = {
	tag = C448
	form_of_goverment = ecclestical
	capital = 448
	ruler = { character = { type = 10 id = 12858 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 448 }
}
country = {
	tag = C450
	form_of_goverment = feudal
	capital = 450
	ruler = { character = { type = 10 id = 19005 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 450 }
}
country = {
	tag = C451
	form_of_goverment = feudal
	capital = 451
	ruler = { character = { type = 10 id = 19006 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 451 }
}
country = {
	tag = C452
	form_of_goverment = feudal
	capital = 452
	ruler = { character = { type = 10 id = 19007 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 452 }
}
country = {
	tag = C453
	form_of_goverment = feudal
	capital = 453
	ruler = { character = { type = 10 id = 19008 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 453 }
}
country = {
	tag = C454
	form_of_goverment = feudal
	capital = 454
	ruler = { character = { type = 10 id = 19009 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 454 }
}
country = {
	tag = C457
	form_of_goverment = feudal
	capital = 457
	ruler = { character = { type = 10 id = 12930 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 457 }
}
country = {
	tag = C459
	form_of_goverment = feudal
	capital = 459
	ruler = { character = { type = 10 id = 19990 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 459 }
}
country = {
	tag = C460
	form_of_goverment = feudal
	capital = 460
	ruler = { character = { type = 10 id = 19010 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 460 }
}
country = {
	tag = C462
	form_of_goverment = feudal
	capital = 462
	ruler = { character = { type = 10 id = 19011 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 462 }
}
country = {
	tag = C463
	form_of_goverment = feudal
	capital = 463
	ruler = { character = { type = 10 id = 20001 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 463 }
}
country = {
	tag = C464
	form_of_goverment = feudal
	capital = 464
	ruler = { character = { type = 10 id = 20002 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 464 }
}
country = {
	tag = C465
	form_of_goverment = ecclestical
	capital = 465
	ruler = { character = { type = 10 id = 20496 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 465 }
}
country = {
	tag = C466
	form_of_goverment = feudal
	capital = 466
	ruler = { character = { type = 10 id = 20003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 466 }
}
country = {
	tag = C468
	form_of_goverment = feudal
	capital = 468
	ruler = { character = { type = 10 id = 18003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 468 }
}
country = {
	tag = C471
	form_of_goverment = ecclesiastical
	capital = 471
	ruler = { character = { type = 10 id = 15006 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes feudal_contract_law = yes church_supremacy = yes }
	controlledprovinces = { 471 }
}
country = {
	tag = C472
	form_of_goverment = feudal
	capital = 472
	ruler = { character = { type = 10 id = 15008 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 472 }
}
country = {
	tag = C474
	form_of_goverment = feudal
	capital = 474
	ruler = { character = { type = 10 id = 20502 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 474 }
}
country = {
	tag = C475
	form_of_goverment = feudal
	capital = 475
	ruler = { character = { type = 10 id = 15014 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 475 }
}
country = {
	tag = C477
	form_of_goverment = feudal
	capital = 477
	ruler = { character = { type = 10 id = 15010 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 477 }
}
country = {
	tag = C478
	form_of_goverment = feudal
	capital = 478
	ruler = { character = { type = 10 id = 15011 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 478 }
}
country = {
	tag = C479
	form_of_goverment = feudal
	capital = 479
	ruler = { character = { type = 10 id = 15023 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 479 }
}
country = {
	tag = C481
	form_of_goverment = feudal
	capital = 481
	ruler = { character = { type = 10 id = 15012 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 481 }
}
country = {
	tag = C483
	form_of_goverment = feudal
	capital = 483
	ruler = { character = { type = 10 id = 15025 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 483 }
}
country = {
	tag = C484
	form_of_goverment = feudal
	capital = 484
	ruler = { character = { type = 10 id = 15020 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 484 }
}
country = {
	tag = C486
	form_of_goverment = feudal
	capital = 486
	ruler = { character = { type = 10 id = 15027 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 486 }
}
country = {
	tag = C487
	form_of_goverment = feudal
	capital = 487
	ruler = { character = { type = 10 id = 15021 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 487 }
}
country = {
	tag = C488
	form_of_goverment = feudal
	capital = 488
	ruler = { character = { type = 10 id = 15015 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 488 }
}
country = {
	tag = C489
	form_of_goverment = feudal
	capital = 489
	ruler = { character = { type = 10 id = 15016 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 489 }
}
country = {
	tag = C491
	form_of_goverment = feudal
	capital = 491
	ruler = { character = { type = 10 id = 15018 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 491 }
}
country = {
	tag = C492
	form_of_goverment = feudal
	capital = 492
	ruler = { character = { type = 10 id = 15004 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 492 }
}
country = {
	tag = C493
	form_of_goverment = feudal
	capital = 493
	ruler = { character = { type = 10 id = 15003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 493 }
}
country = {
	tag = C495
	form_of_goverment = feudal
	capital = 495
	ruler = { character = { type = 10 id = 15002 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 495 }
}
country = {
	tag = C501
	form_of_goverment = feudal
	capital = 501
	ruler = { character = { type = 10 id = 17009 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 501 }
}
country = {
	tag = C505
	form_of_goverment = feudal
	capital = 505
	ruler = { character = { type = 10 id = 19012 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 505 }
}
country = {
	tag = C506
	form_of_goverment = feudal
	capital = 506
	ruler = { character = { type = 10 id = 17003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 506 }
}
country = {
	tag = C510
	form_of_goverment = feudal
	capital = 510
	ruler = { character = { type = 10 id = 17007 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 510 511 }
}
country = {
	tag = C512
	form_of_goverment = feudal
	capital = 512
	ruler = { character = { type = 10 id = 22579 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 512 }
}
country = {
	tag = C514
	form_of_goverment = feudal
	capital = 514
	ruler = { character = { type = 10 id = 28028 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 514 }
}
country = {
	tag = C516
	form_of_goverment = feudal
	capital = 516
	ruler = { character = { type = 10 id = 28029 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 516 }
}
country = {
	tag = C517
	form_of_goverment = feudal
	capital = 517
	ruler = { character = { type = 10 id = 19013 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 517 }
}
country = {
	tag = C518
	form_of_goverment = feudal
	capital = 518
	ruler = { character = { type = 10 id = 19014 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 518 }
}
country = {
	tag = C519
	form_of_goverment = feudal
	capital = 519
	ruler = { character = { type = 10 id = 19015 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 519 }
}
country = {
	tag = C520
	form_of_goverment = feudal
	capital = 520
	ruler = { character = { type = 10 id = 19016 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 520 }
}
country = {
	tag = C521
	form_of_goverment = feudal
	capital = 521
	ruler = { character = { type = 10 id = 19017 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 521 }
}
country = {
	tag = C523
	form_of_goverment = feudal
	capital = 523
	ruler = { character = { type = 10 id = 19018 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 523 }
}
country = {
	tag = C524
	form_of_goverment = feudal
	capital = 524
	ruler = { character = { type = 10 id = 19019 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 524 }
}
country = {
	tag = C525
	form_of_goverment = feudal
	capital = 525
	ruler = { character = { type = 10 id = 19020 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 525 }
}
country = {
	tag = C526
	form_of_goverment = feudal
	capital = 526
	ruler = { character = { type = 10 id = 21550 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 526 }
}
country = {
	tag = C533
	form_of_goverment = feudal
	capital = 533
	ruler = { character = { type = 10 id = 19021 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 533 }
}
country = {
	tag = C534
	form_of_goverment = feudal
	capital = 534
	ruler = { character = { type = 10 id = 22510 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 534 }
}
country = {
	tag = C537
	form_of_goverment = feudal
	capital = 537
	ruler = { character = { type = 10 id = 19022 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 537 }
}
country = {
	tag = C538
	form_of_goverment = feudal
	capital = 538
	ruler = { character = { type = 10 id = 19023 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 538 }
}
country = {
	tag = C539
	form_of_goverment = feudal
	capital = 539
	ruler = { character = { type = 10 id = 19024 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 539 }
}
country = {
	tag = C540
	form_of_goverment = feudal
	capital = 540
	ruler = { character = { type = 10 id = 19025 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 540 }
}
country = {
	tag = C542
	form_of_goverment = feudal
	capital = 542
	ruler = { character = { type = 10 id = 28032 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 542 }
}
country = {
	tag = C543
	form_of_goverment = feudal
	capital = 543
	ruler = { character = { type = 10 id = 28033 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 543 }
}
country = {
	tag = C549
	form_of_goverment = feudal
	capital = 549
	ruler = { character = { type = 10 id = 22530 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 549 }
}
country = {
	tag = C556
	form_of_goverment = feudal
	capital = 556
	ruler = { character = { type = 10 id = 28034 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 556 }
}
country = {
	tag = C557
	form_of_goverment = feudal
	capital = 557
	ruler = { character = { type = 10 id = 28055 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 557 }
}
country = {
	tag = C558
	form_of_goverment = feudal
	capital = 558
	ruler = { character = { type = 10 id = 28056 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 558 }
}
country = {
	tag = C559
	form_of_goverment = feudal
	capital = 559
	ruler = { character = { type = 10 id = 28057 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 559 }
}
country = {
	tag = C561
	form_of_goverment = feudal
	capital = 561
	ruler = { character = { type = 10 id = 15040 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 561 }
}
country = {
	tag = C562
	form_of_goverment = feudal
	capital = 562
	ruler = { character = { type = 10 id = 15042 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 562 }
}
country = {
	tag = C563
	form_of_goverment = feudal
	capital = 563
	ruler = { character = { type = 10 id = 28058 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 563 }
}
country = {
	tag = C566
	form_of_goverment = feudal
	capital = 566
	ruler = { character = { type = 10 id = 28036 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 566 564 }
}
country = {
	tag = C569
	form_of_goverment = feudal
	capital = 569
	ruler = { character = { type = 10 id = 22590 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 569 }
}
country = {
	tag = C570
	form_of_goverment = feudal
	capital = 570
	tier = county 
	ruler = { character = { type = 10 id = 22710 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 570 }
}
country = {
	tag = C573
	form_of_goverment = feudal
	capital = 573
	ruler = { character = { type = 10 id = 22700 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 573 }
}
country = {
	tag = C574
	form_of_goverment = feudal
	capital = 574
	tier = county 
	ruler = { character = { type = 10 id = 22720 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 574 }
}
country = {
	tag = C577
	form_of_goverment = feudal
	capital = 577
	ruler = { character = { type = 10 id = 22760 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 577 }
}
country = {
	tag = C580
	form_of_goverment = feudal
	capital = 580
	ruler = { character = { type = 10 id = 22740 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 580 }
}
country = {
	tag = C583
	form_of_goverment = feudal
	capital = 583
	ruler = { character = { type = 10 id = 22730 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 583 }
}
country = {
	tag = C586
	form_of_goverment = feudal
	capital = 586
	ruler = { character = { type = 10 id = 29003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 586 }
}
country = {
	tag = C587
	form_of_goverment = feudal
	capital = 587
	ruler = { character = { type = 10 id = 29004 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 587 }
}
country = {
	tag = C588
	form_of_goverment = feudal
	capital = 588
	ruler = { character = { type = 10 id = 29005 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 588 }
}
country = {
	tag = C589
	form_of_goverment = feudal
	capital = 589
	ruler = { character = { type = 10 id = 29006 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 589 }
}
country = {
	tag = C590
	form_of_goverment = feudal
	capital = 590
	ruler = { character = { type = 10 id = 29007 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 590 }
}
country = {
	tag = C591
	form_of_goverment = feudal
	capital = 591
	ruler = { character = { type = 10 id = 29008 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 591 }
}
country = {
	tag = C592
	form_of_goverment = feudal
	capital = 592
	ruler = { character = { type = 10 id = 28071 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 592 }
}
country = {
	tag = C593
	form_of_goverment = feudal
	capital = 593
	ruler = { character = { type = 10 id = 28072 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 593 }
}
country = {
	tag = C594
	form_of_goverment = feudal
	capital = 594
	ruler = { character = { type = 10 id = 28037 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 594 }
}
country = {
	tag = C595
	form_of_goverment = feudal
	capital = 595
	ruler = { character = { type = 10 id = 28038 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 595 }
}
country = {
	tag = C596
	form_of_goverment = feudal
	capital = 596
	ruler = { character = { type = 10 id = 28059 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 596 }
}
country = {
	tag = C597
	form_of_goverment = feudal
	capital = 597
	ruler = { character = { type = 10 id = 28061 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 597 }
}
country = {
	tag = C598
	form_of_goverment = feudal
	capital = 598
	ruler = { character = { type = 10 id = 15041 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 598 }
}
country = {
	tag = C599
	form_of_goverment = feudal
	capital = 599
	ruler = { character = { type = 10 id = 28062 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 599 }
}
country = {
	tag = C600
	form_of_goverment = feudal
	capital = 600
	ruler = { character = { type = 10 id = 28069 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 600 601 }
}
country = {
	tag = C602
	form_of_goverment = feudal
	capital = 602
	ruler = { character = { type = 10 id = 28067 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 602 }
}
country = {
	tag = C604
	form_of_goverment = feudal
	capital = 604
	ruler = { character = { type = 10 id = 28063 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 604 }
}
country = {
	tag = C605
	form_of_goverment = feudal
	capital = 605
	ruler = { character = { type = 10 id = 28064 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 605 }
}
country = {
	tag = C606
	form_of_goverment = feudal
	capital = 606
	ruler = { character = { type = 10 id = 28065 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 606 }
}
country = {
	tag = C607
	form_of_goverment = feudal
	capital = 607
	ruler = { character = { type = 10 id = 28066 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 607 }
}
country = {
	tag = C608
	form_of_goverment = feudal
	capital = 608
	ruler = { character = { type = 10 id = 28039 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 608 }
}
country = {
	tag = C609
	form_of_goverment = feudal
	capital = 609
	ruler = { character = { type = 10 id = 28040 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 609 }
}
country = {
	tag = C610
	form_of_goverment = feudal
	capital = 610
	ruler = { character = { type = 10 id = 29009 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 610 }
}
country = {
	tag = C612
	form_of_goverment = feudal
	capital = 612
	ruler = { character = { type = 10 id = 29010 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 612 }
}
country = {
	tag = C613
	form_of_goverment = feudal
	capital = 613
	ruler = { character = { type = 10 id = 29011 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 613 }
}
country = {
	tag = C614
	form_of_goverment = feudal
	capital = 614
	ruler = { character = { type = 10 id = 28041 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 614 }
}
country = {
	tag = C615
	form_of_goverment = feudal
	capital = 615
	ruler = { character = { type = 10 id = 28042 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 615 }
}
country = {
	tag = C616
	form_of_goverment = feudal
	capital = 616
	ruler = { character = { type = 10 id = 28043 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 616 }
}
country = {
	tag = C617
	form_of_goverment = feudal
	capital = 617
	ruler = { character = { type = 10 id = 28044 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 617 }
}
country = {
	tag = C618
	form_of_goverment = feudal
	capital = 618
	ruler = { character = { type = 10 id = 28045 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 618 }
}
country = {
	tag = C619
	form_of_goverment = feudal
	capital = 619
	ruler = { character = { type = 10 id = 28046 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 619 }
}
country = {
	tag = C620
	form_of_goverment = feudal
	capital = 620
	ruler = { character = { type = 10 id = 28047 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 620 }
}
country = {
	tag = C621
	form_of_goverment = feudal
	capital = 621
	ruler = { character = { type = 10 id = 28048 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 621 }
}
country = {
	tag = C622
	form_of_goverment = feudal
	capital = 622
	ruler = { character = { type = 10 id = 28049 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 622 }
}
country = {
	tag = C623
	form_of_goverment = feudal
	capital = 623
	ruler = { character = { type = 10 id = 28050 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 623 }
}
country = {
	tag = C624
	form_of_goverment = feudal
	capital = 624
	ruler = { character = { type = 10 id = 28051 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 624 }
}
country = {
	tag = C625
	form_of_goverment = feudal
	capital = 625
	ruler = { character = { type = 10 id = 28052 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 625 }
}
country = {
	tag = C626
	form_of_goverment = feudal
	capital = 626
	ruler = { character = { type = 10 id = 28053 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 626 }
}
country = {
	tag = C627
	form_of_goverment = feudal
	capital = 627
	ruler = { character = { type = 10 id = 28054 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 627 }
}
country = {
	tag = C649
	form_of_goverment = feudal
	capital = 649
	ruler = { character = { type = 10 id = 27001 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 649 }
}
country = {
	tag = C650
	form_of_goverment = feudal
	capital = 650
	ruler = { character = { type = 10 id = 27101 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 650 }
}
country = {
	tag = C651
	form_of_goverment = feudal
	capital = 651
	ruler = { character = { type = 10 id = 27102 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 651 }
}
country = {
	tag = C652
	form_of_goverment = feudal
	capital = 652
	ruler = { character = { type = 10 id = 27103 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 652 }
}
country = {
	tag = C653
	form_of_goverment = feudal
	capital = 653
	ruler = { character = { type = 10 id = 27104 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 653 }
}
country = {
	tag = C654
	form_of_goverment = feudal
	capital = 654
	ruler = { character = { type = 10 id = 27105 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 654 }
}
country = {
	tag = C655
	form_of_goverment = feudal
	capital = 655
	ruler = { character = { type = 10 id = 27002 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 655 }
}
country = {
	tag = C656
	form_of_goverment = feudal
	capital = 656
	ruler = { character = { type = 10 id = 27003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 656 }
}
country = {
	tag = C657
	form_of_goverment = feudal
	capital = 657
	ruler = { character = { type = 10 id = 25016 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 657 }
}
country = {
	tag = C658
	form_of_goverment = feudal
	capital = 658
	ruler = { character = { type = 10 id = 25017 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 658 }
}
country = {
	tag = C664
	form_of_goverment = feudal
	capital = 664
	ruler = { character = { type = 10 id = 25012 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 664 }
}
country = {
	tag = C666
	form_of_goverment = feudal
	capital = 666
	ruler = { character = { type = 10 id = 25018 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 666 }
}
country = {
	tag = C668
	form_of_goverment = feudal
	capital = 668
	ruler = { character = { type = 10 id = 25019 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 668 }
}
country = {
	tag = C669
	form_of_goverment = feudal
	capital = 669
	ruler = { character = { type = 10 id = 25020 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 669 }
}
country = {
	tag = C670
	form_of_goverment = feudal
	capital = 670
	ruler = { character = { type = 10 id = 25021 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 670 }
}
country = {
	tag = C671
	form_of_goverment = feudal
	capital = 671
	ruler = { character = { type = 10 id = 25022 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 671 }
}
country = {
	tag = C672
	form_of_goverment = feudal
	capital = 672
	ruler = { character = { type = 10 id = 25023 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 672 }
}
country = {
	tag = C673
	form_of_goverment = feudal
	capital = 673
	ruler = { character = { type = 10 id = 25024 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 673 }
}
country = {
	tag = C674
	form_of_goverment = feudal
	capital = 674
	ruler = { character = { type = 10 id = 28073 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 674 }
}
country = {
	tag = C675
	form_of_goverment = feudal
	capital = 675
	ruler = { character = { type = 10 id = 28074 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 675 }
}
country = {
	tag = C681
	form_of_goverment = feudal
	capital = 681
	ruler = { character = { type = 10 id = 25027 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 681 }
}
country = {
	tag = C682
	form_of_goverment = feudal
	capital = 682
	ruler = { character = { type = 10 id = 25028 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 682 }
}
country = {
	tag = C684
	form_of_goverment = feudal
	capital = 684
	ruler = { character = { type = 10 id = 26002 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 684 }
}
country = {
	tag = C685
	form_of_goverment = feudal
	capital = 685
	ruler = { character = { type = 10 id = 26014 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 685 }
}
country = {
	tag = C686
	form_of_goverment = feudal
	capital = 686
	ruler = { character = { type = 10 id = 25013 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 686 }
}
country = {
	tag = C688
	form_of_goverment = feudal
	capital = 688
	ruler = { character = { type = 10 id = 27004 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 688 }
}
country = {
	tag = C689
	form_of_goverment = feudal
	capital = 689
	ruler = { character = { type = 10 id = 27005 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 689 }
}
country = {
	tag = C690
	form_of_goverment = feudal
	capital = 690
	ruler = { character = { type = 10 id = 27006 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 690 }
}
country = {
	tag = C691
	form_of_goverment = feudal
	capital = 691
	ruler = { character = { type = 10 id = 27007 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 691 }
}
country = {
	tag = C692
	form_of_goverment = feudal
	capital = 692
	ruler = { character = { type = 10 id = 27008 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 692 }
}
country = {
	tag = C694
	form_of_goverment = feudal
	capital = 694
	ruler = { character = { type = 10 id = 27009 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 694 }
}
country = {
	tag = C695
	form_of_goverment = feudal
	capital = 695
	ruler = { character = { type = 10 id = 27010 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 695 }
}
country = {
	tag = C696
	form_of_goverment = feudal
	capital = 696
	ruler = { character = { type = 10 id = 25014 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 696 }
}
country = {
	tag = C698
	form_of_goverment = feudal
	capital = 698
	ruler = { character = { type = 10 id = 26015 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 698 }
}
country = {
	tag = C699
	form_of_goverment = feudal
	capital = 699
	ruler = { character = { type = 10 id = 26003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 699 }
}
country = {
	tag = C700
	form_of_goverment = feudal
	capital = 700
	ruler = { character = { type = 10 id = 26004 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 700 }
}
country = {
	tag = C701
	form_of_goverment = feudal
	capital = 701
	ruler = { character = { type = 10 id = 25010 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 701 }
}
country = {
	tag = C703
	form_of_goverment = feudal
	capital = 703
	ruler = { character = { type = 10 id = 25029 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 703 }
}
country = {
	tag = C704
	form_of_goverment = feudal
	capital = 704
	ruler = { character = { type = 10 id = 25026 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 704 }
}
country = {
	tag = C705
	form_of_goverment = feudal
	capital = 705
	ruler = { character = { type = 10 id = 15043 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 705 }
}
country = {
	tag = C707
	form_of_goverment = feudal
	capital = 707
	ruler = { character = { type = 10 id = 26005 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 707 }
}
country = {
	tag = C708
	form_of_goverment = feudal
	capital = 708
	ruler = { character = { type = 10 id = 26006 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 708 }
}
country = {
	tag = C709
	form_of_goverment = feudal
	capital = 709
	ruler = { character = { type = 10 id = 26009 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 709 }
}
country = {
	tag = C710
	form_of_goverment = feudal
	capital = 710
	ruler = { character = { type = 10 id = 26016 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 710 }
}
country = {
	tag = C711
	form_of_goverment = feudal
	capital = 711
	ruler = { character = { type = 10 id = 26017 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 711 }
}
country = {
	tag = C712
	form_of_goverment = feudal
	capital = 712
	ruler = { character = { type = 10 id = 26018 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 712 }
}
country = {
	tag = C713
	form_of_goverment = feudal
	capital = 713
	ruler = { character = { type = 10 id = 26021 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 713 }
}
country = {
	tag = C714
	form_of_goverment = feudal
	capital = 714
	ruler = { character = { type = 10 id = 26022 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 714 }
}
country = {
	tag = C715
	form_of_goverment = feudal
	capital = 715
	ruler = { character = { type = 10 id = 27011 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 715 }
}
country = {
	tag = C716
	form_of_goverment = feudal
	capital = 716
	ruler = { character = { type = 10 id = 26034 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 716 }
}
country = {
	tag = C717
	form_of_goverment = feudal
	capital = 717
	ruler = { character = { type = 10 id = 26035 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 717 }
}
country = {
	tag = C719
	form_of_goverment = feudal
	capital = 719
	ruler = { character = { type = 10 id = 26033 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 719 }
}
country = {
	tag = C720
	form_of_goverment = feudal
	capital = 720
	ruler = { character = { type = 10 id = 26037 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 720 }
}
country = {
	tag = C721
	form_of_goverment = feudal
	capital = 721
	ruler = { character = { type = 10 id = 26038 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 721 }
}
country = {
	tag = C722
	form_of_goverment = feudal
	capital = 722
	ruler = { character = { type = 10 id = 26023 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 722 }
}
country = {
	tag = C723
	form_of_goverment = feudal
	capital = 723
	ruler = { character = { type = 10 id = 26024 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 723 }
}
country = {
	tag = C726
	form_of_goverment = feudal
	capital = 726
	ruler = { character = { type = 10 id = 26025 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 726 }
}
country = {
	tag = C728
	form_of_goverment = feudal
	capital = 728
	ruler = { character = { type = 10 id = 26026 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 728 }
}
country = {
	tag = C729
	form_of_goverment = feudal
	capital = 729
	ruler = { character = { type = 10 id = 26019 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 729 }
}
country = {
	tag = C730
	form_of_goverment = feudal
	capital = 730
	ruler = { character = { type = 10 id = 26010 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 730 }
}
country = {
	tag = C731
	form_of_goverment = feudal
	capital = 731
	ruler = { character = { type = 10 id = 26011 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 731 }
}
country = {
	tag = C732
	form_of_goverment = feudal
	capital = 732
	ruler = { character = { type = 10 id = 26012 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 732 }
}
country = {
	tag = C734
	form_of_goverment = feudal
	capital = 734
	ruler = { character = { type = 10 id = 26008 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 734 }
}
country = {
	tag = ARMI
	form_of_goverment = ecclestical #feudal
	capital = 735
	ruler = { character = { type = 10 id = 32580 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 735 }
}
country = {
	tag = C738
	form_of_goverment = feudal
	capital = 738
	ruler = { character = { type = 10 id = 15038 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 738 }
}
country = {
	tag = C740
	form_of_goverment = feudal
	capital = 740
	ruler = { character = { type = 10 id = 15036 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 740 }
}
country = {
	tag = C742
	form_of_goverment = feudal
	capital = 742
	ruler = { character = { type = 10 id = 15033 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 742 }
}
country = {
	tag = C743
	form_of_goverment = feudal
	capital = 743
	ruler = { character = { type = 10 id = 15034 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 743 }
}
country = {
	tag = C744
	form_of_goverment = feudal
	capital = 744
	ruler = { character = { type = 10 id = 15030 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 744 }
}
country = {
	tag = C745
	form_of_goverment = feudal
	capital = 745
	ruler = { character = { type = 10 id = 15028 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 745 }
}
country = {
	tag = C746
	form_of_goverment = feudal
	capital = 746
	ruler = { character = { type = 10 id = 15029 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 746 }
}
country = {
	tag = C749
	form_of_goverment = feudal
	capital = 749
	ruler = { character = { type = 10 id = 25005 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 749 }
}
country = {
	tag = C751
	form_of_goverment = feudal
	capital = 751
	ruler = { character = { type = 10 id = 25007 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 751 }
}
country = {
	tag = C752
	form_of_goverment = feudal
	capital = 752
	ruler = { character = { type = 10 id = 25001 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 752 }
}
country = {
	tag = C754
	form_of_goverment = feudal
	capital = 754
	ruler = { character = { type = 10 id = 15032 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 754 }
}
country = {
	tag = C755
	form_of_goverment = feudal
	capital = 755
	ruler = { character = { type = 10 id = 15026 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 755 }
}
country = {
	tag = C758
	form_of_goverment = feudal
	capital = 758
	ruler = { character = { type = 10 id = 32592 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 758 }
}
country = {
	tag = C760
	form_of_goverment = feudal
	capital = 760
	ruler = { character = { type = 10 id = 25003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 760 }
}
country = { #was 23034
	tag = C761
	form_of_goverment = feudal
	capital = 761
	ruler = { character = { type = 10 id = 23026 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 761 }
}
country = { #was 23026
	tag = C762
	form_of_goverment = feudal
	capital = 762
	ruler = { character = { type = 10 id = 32594 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 762 }
}
country = {
	tag = C769
	form_of_goverment = feudal
	capital = 769
	ruler = { character = { type = 10 id = 31015 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 769 }
}
country = {
	tag = C770
	form_of_goverment = feudal
	capital = 770
	ruler = { character = { type = 10 id = 32705 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 770 }
}
country = {
	tag = C779
	form_of_goverment = feudal
	capital = 779
	ruler = { character = { type = 10 id = 23570 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 779 }
}
country = {
	tag = C781
	form_of_goverment = feudal
	capital = 781
	ruler = { character = { type = 10 id = 26099 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 781 }
}
country = {
	tag = C783
	form_of_goverment = feudal
	capital = 783
	ruler = { character = { type = 10 id = 26028 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 783 }
}
country = {
	tag = C784
	form_of_goverment = feudal
	capital = 784
	ruler = { character = { type = 10 id = 26029 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 784 }
}
country = {
	tag = C785
	form_of_goverment = feudal
	capital = 785
	ruler = { character = { type = 10 id = 26031 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 785 }
}
country = {
	tag = C788
	form_of_goverment = feudal
	capital = 788
	ruler = { character = { type = 10 id = 26032 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 788 }
}
country = {
	tag = C803
	form_of_goverment = feudal
	capital = 803
	ruler = { character = { type = 10 id = 26040 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 803 }
}
country = {
	tag = C804
	form_of_goverment = feudal
	capital = 804
	ruler = { character = { type = 10 id = 26041 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 804 }
}
country = {
	tag = C805
	form_of_goverment = feudal
	capital = 805
	ruler = { character = { type = 10 id = 26042 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 805 }
}
country = {
	tag = C806
	form_of_goverment = feudal
	capital = 806
	ruler = { character = { type = 10 id = 26043 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 806 }
}
country = {
	tag = C807
	form_of_goverment = feudal
	capital = 807
	ruler = { character = { type = 10 id = 26044 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 807 }
}
country = {
	tag = C809
	form_of_goverment = feudal
	capital = 809
	ruler = { character = { type = 10 id = 26046 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 809 }
}
country = {
	tag = C810
	form_of_goverment = feudal
	capital = 810
	ruler = { character = { type = 10 id = 26047 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 810 }
}
country = {
	tag = C811
	form_of_goverment = feudal
	capital = 811
	ruler = { character = { type = 10 id = 26048 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 811 }
}
country = {
	tag = C813
	form_of_goverment = feudal
	capital = 813
	ruler = { character = { type = 10 id = 26049 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 813 }
}
country = {
	tag = C815
	form_of_goverment = feudal
	capital = 815
	ruler = { character = { type = 10 id = 24027 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 815 }
}
country = {
	tag = C816
	form_of_goverment = feudal
	capital = 816
	ruler = { character = { type = 10 id = 24028 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 816 }
}
country = {
	tag = C818
	form_of_goverment = feudal
	capital = 818
	ruler = { character = { type = 10 id = 24031 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 818 }
}
country = {
	tag = C819
	form_of_goverment = feudal
	capital = 819
	ruler = { character = { type = 10 id = 24029 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 819 }
}
country = {
	tag = C820
	form_of_goverment = feudal
	capital = 820
	ruler = { character = { type = 10 id = 24030 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 820 }
}
country = {
	tag = C821
	form_of_goverment = feudal
	capital = 821
	ruler = { character = { type = 10 id = 24032 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 821 }
}
country = {
	tag = C822
	form_of_goverment = feudal
	capital = 822
	ruler = { character = { type = 10 id = 24033 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 822 }
}
country = {
	tag = C823
	form_of_goverment = feudal
	capital = 823
	ruler = { character = { type = 10 id = 24034 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 823 }
}
country = {
	tag = C824
	form_of_goverment = feudal
	capital = 824
	ruler = { character = { type = 10 id = 24036 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 824 }
}
country = {
	tag = C826
	form_of_goverment = feudal
	capital = 826
	ruler = { character = { type = 10 id = 24049 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 826 }
}
country = {
	tag = C828
	form_of_goverment = feudal
	capital = 828
	ruler = { character = { type = 10 id = 24037 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 828 }
}
country = {
	tag = C829
	form_of_goverment = feudal
	capital = 829
	ruler = { character = { type = 10 id = 24038 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 829 }
}
country = {
	tag = C830
	form_of_goverment = feudal
	capital = 830
	ruler = { character = { type = 10 id = 24039 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 830 }
}
country = {
	tag = C831
	form_of_goverment = feudal
	capital = 831
	ruler = { character = { type = 10 id = 24040 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 831 }
}
country = {
	tag = C833
	form_of_goverment = feudal
	capital = 833
	ruler = { character = { type = 10 id = 24042 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 833 }
}
country = {
	tag = C834
	form_of_goverment = feudal
	capital = 834
	ruler = { character = { type = 10 id = 24043 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 834 }
}
country = {
	tag = C835
	form_of_goverment = feudal
	capital = 835
	ruler = { character = { type = 10 id = 24044 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 835 }
}
country = {
	tag = C836
	form_of_goverment = feudal
	capital = 836
	ruler = { character = { type = 10 id = 24045 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 836 }
}
country = {
	tag = C837
	form_of_goverment = feudal
	capital = 837
	ruler = { character = { type = 10 id = 24046 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 837 }
}
country = {
	tag = C838
	form_of_goverment = feudal
	capital = 838
	ruler = { character = { type = 10 id = 24047 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 838 }
}
country = {
	tag = C839
	form_of_goverment = feudal
	capital = 839
	ruler = { character = { type = 10 id = 24018 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 839 }
}
country = {
	tag = C841
	form_of_goverment = feudal
	capital = 841
	ruler = { character = { type = 10 id = 24019 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 841 }
}
country = {
	tag = C848
	form_of_goverment = feudal
	capital = 848
	ruler = { character = { type = 10 id = 20842 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 848 }
}
country = {
	tag = C898
	form_of_goverment = ecclestical
	capital = 898
	ruler = { character = { type = 10 id = 20330 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 898 }
}
country = {
	tag = C995
	form_of_goverment = ecclestical
	capital = 995
	ruler = { character = { type = 10 id = 31040 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 995 259 }
}
country = {
	tag = ADRI
	form_of_goverment = feudal
	capital = 494
	tier = duchy 
	ruler = { character = { type = 10 id = 15060 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 494 }
}
country = {
	tag = AEGE
	form_of_goverment = feudal
	capital = 485
	tier = duchy 
	ruler = { character = { type = 10 id = 15019 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 485 }
}
country = {
	tag = AKER
	form_of_goverment = feudal
	capital = 272
	tier = duchy 
	ruler = { character = { type = 10 id = 2005 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 272 }
}
country = {
	tag = ALAN
	form_of_goverment = feudal
	capital = 603
	tier = duchy 
	ruler = { character = { type = 10 id = 28060 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 603 }
}
country = {
	tag = ALGE
	form_of_goverment = feudal
	capital = 832
	tier = duchy 
	ruler = { character = { type = 10 id = 24041 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 832 }
}
country = {
	tag = ALME
	form_of_goverment = feudal
	capital = 168
	tier = duchy 
	ruler = { character = { type = 10 id = 24015 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 168 }
}
country = {
	tag = ANTI
	form_of_goverment = feudal
	capital = 764
	tier = duchy 
	ruler = { character = { type = 10 id = 23750 } startdate = { year = 1187 month = january day = 0 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 764 763 }
}
country = {
	tag = ARMA 
	form_of_goverment = feudal 
	capital = 149 
	tier = duchy 
	ruler = { character = { type = 10 id = 4510 } startdate = { year = 1187 month = january day = 0 } } 
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes } 
	controlledprovinces = { 149 143 215 } 
}
country = { 
	tag = ARMI 
	form_of_goverment = ecclestical 
	capital = 735 
	tier = duchy 
	ruler = { character = { type = 10 id = 32580 } startdate = { year = 1187 month = january day = 0 } } 
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes } 
	controlledprovinces = { 735 } 
}
country = {
	tag = AZER
	form_of_goverment = feudal
	capital = 667
	tier = duchy 
	ruler = { character = { type = 10 id = 25015 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 667 }
}
country = {
	tag = BADA
	form_of_goverment = feudal
	capital = 195
	tier = duchy 
	ruler = { character = { type = 10 id = 24008 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 195 }
}
country = {
	tag = BAVA
	form_of_goverment = feudal
	capital = 360
	tier = duchy 
	ruler = { character = { type = 10 id = 12950 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 360 317 361 447 }
}
country = {
	tag = BENE
	form_of_goverment = ecclestical
	capital = 997
	tier = duchy 
	ruler = { character = { type = 10 id = 20331 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 997 }
}
country = {
	tag = DBOH
	form_of_goverment = feudal
	capital = 437
	tier = duchy 
	ruler = { character = { type = 10 id = 12850 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 437 363 436 439 }
}

country = {
	tag = BORD
	form_of_goverment = feudal
	capital = 141
	tier = duchy 
	ruler = { character = { type = 10 id = 5730 } startdate = { year = 1187 month = january day = 0 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 141 }
}
country = {
	tag = BOUG
	form_of_goverment = feudal
	capital = 136
	tier = duchy 
	ruler = { character = { type = 10 id = 6000 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 136 227 }
}
country = {
	tag = BOUR
	form_of_goverment = feudal
	capital = 146
	tier = duchy 
	ruler = { character = { type = 10 id = 5650 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 146 }
}
country = {
	tag = BRAB
	form_of_goverment = feudal
	capital = 117
	tier = duchy 
	ruler = { character = { type = 10 id = 6850 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 117 92 }
}
country = {
	tag = BRAN
	form_of_goverment = feudal
	capital = 365
	tier = duchy 
	ruler = { character = { type = 10 id = 12037 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 365 }
}
country = {
	tag = BRIT
	form_of_goverment = feudal
	capital = 105 
	tier = duchy 
	ruler = { character = { type = 10 id = 5740 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 106 101 104 105 }
}
country = {
	tag = BUTR
	form_of_goverment = feudal
	capital = 473
	tier = duchy 
	ruler = { character = { type = 10 id = 15508 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 473 }
}
country = {
	tag = CHAL
	form_of_goverment = feudal
	capital = 706
	tier = duchy 
	ruler = { character = { type = 10 id = 25008 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 706 }
}
country = {
	tag = CHAM
	form_of_goverment = feudal
	capital = 130
	tier = duchy 
	ruler = { character = { type = 10 id = 5960 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 130 }
}
country = {
	tag = CHER
	form_of_goverment = feudal
	capital = 560
	tier = duchy 
	ruler = { character = { type = 10 id = 15039 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 560 }
}
country = {
	tag = CONN
	form_of_goverment = feudal
	capital = 9
	tier = duchy 
	ruler = { character = { type = 10 id = 14500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 9 8 13 }
}
country = {
	tag = CONS
	form_of_goverment = feudal
	capital = 825
	tier = duchy 
	ruler = { character = { type = 10 id = 24035 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 825 }
}
country = {
	tag = CORD
	form_of_goverment = feudal
	capital = 181
	tier = duchy 
	ruler = { character = { type = 10 id = 24001 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 181 }
}
country = {
	tag = DCRO
	form_of_goverment = feudal
	capital = 461
	tier = duchy 
	ruler = { character = { type = 10 id = 20000 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 461 }
}
country = {
	tag = CYPR
	form_of_goverment = feudal
	capital = 757
	tier = duchy 
	ruler = { character = { type = 10 id = 23020 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 757 756 }
}
country = {
	tag = CYRE
	form_of_goverment = feudal
	capital = 808
	tier = duchy 
	ruler = { character = { type = 10 id = 26039 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 808 }
}
country = {
	tag = DEHE
	form_of_goverment = feudal
	capital = 19
	tier = duchy 
	ruler = { character = { type = 10 id = 14800 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 19 }
}
country = {
	tag = DYRR
	form_of_goverment = feudal
	capital = 470
	tier = duchy 
	ruler = { character = { type = 10 id = 15005 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 470 }
}
country = {
	tag = FLAN
	form_of_goverment = feudal
	capital = 78
	tier = duchy 
	ruler = { character = { type = 10 id = 12591 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 78 76 93 }
}
country = {
	tag = FRAC
	form_of_goverment = feudal
	capital = 254
	tier = duchy 
	ruler = { character = { type = 10 id = 12490 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 254 122 313 }
}
country = {
	tag = GALI
	form_of_goverment = feudal
	capital = 536
	tier = duchy 
	ruler = { character = { type = 10 id = 22500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 536 425 541 545 }
}
country = {
	tag = GALC
	form_of_goverment = ecclestical
	capital = 157
	tier = duchy 
	ruler = { character = { type = 10 id = 8520 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 157 }
}
country = {
	tag = GALL
	form_of_goverment = feudal
	capital = 50
	tier = duchy 
	ruler = { character = { type = 10 id = 3570 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 50 }
}
country = {
	tag = GENO
	form_of_goverment = republican
	capital = 233
	tier = duchy 
	ruler = { character = { type = 10 id = 13015 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 233 230 325 }
}
country = {
	tag = DGEO 
	form_of_goverment = feudal 
	capital = 677 
	tier = duchy 
	ruler = { character = { type = 10 id = 32764 } startdate = { year = 1187 month = january day = 0 } } 
	laws = { semisalic_gavelkind_law = yes traditional_custom_law = yes regal_supremacy = yes } 
	controlledprovinces = { 677 } 
}
country = {
	tag = GWYN
	form_of_goverment = feudal
	capital = 60
	tier = duchy 
	ruler = { character = { type = 10 id = 14700 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 60 }
}
country = {
	tag = HAIN
	form_of_goverment = feudal
	capital = 80
	tier = duchy 
	ruler = { character = { type = 10 id = 6840 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 80 79 }
}
country = {
	tag = HELL
	form_of_goverment = feudal 
	capital = 482
	tier = duchy 
	ruler = { character = { type = 10 id = 15013 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes feudal_contract_law = yes church_supremacy = yes }
	controlledprovinces = { 482 }
}
country = {
	tag = ICEL
	form_of_goverment = republican
	capital = 2
	tier = duchy 
	ruler = { character = { type = 10 id = 2011 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes ecclesical_balance = yes }
	controlledprovinces = { 2 }
}
country = {
	tag = IKON
	form_of_goverment = feudal
	capital = 759
	tier = duchy 
	ruler = { character = { type = 10 id = 25004 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 759 }
}
country = {
	tag = IMER 
	form_of_goverment = feudal
	capital = 601 
	tier = duchy 
	ruler = { character = { type = 10 id = 32762 } startdate = { year = 1187 month = january day = 0 } } 
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 601 } 
}
country = {
	tag = KAIR
	form_of_goverment = feudal
	capital = 814
	tier = duchy 
	ruler = { character = { type = 10 id = 26045 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 814 }
}
country = {
	tag = KAPP
	form_of_goverment = feudal
	capital = 753
	tier = duchy 
	ruler = { character = { type = 10 id = 25002 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 753 }
}
country = {
	tag = KARE
	form_of_goverment = feudal
	capital = 388
	tier = duchy 
	ruler = { character = { type = 10 id = 28004 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 388 }
}
country = {
	tag = KIEV
	form_of_goverment = feudal
	capital = 547
	tier = duchy 
	ruler = { character = { type = 10 id = 22650 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 547 544 546 }
}
country = {
	tag = KRET
	form_of_goverment = feudal
	capital = 480
	tier = duchy 
	ruler = { character = { type = 10 id = 15022 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 480 }
}
country = {
	tag = KARN
	form_of_goverment = feudal
	capital = 456
	tier = duchy 
	ruler = { character = { type = 10 id = 12990 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 456 455 }
}
country = {
	tag = LANG
	form_of_goverment = republican
	capital = 323
	tier = duchy 
	ruler = { character = { type = 10 id = 13018 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 323 324 326 }
}
country = {
	tag = LAOD
	form_of_goverment = feudal
	capital = 748
	tier = duchy 
	ruler = { character = { type = 10 id = 15031 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 748 }
}
country = {
	tag = LIVO
	form_of_goverment = feudal
	capital = 377
	tier = duchy 
	ruler = { character = { type = 10 id = 28023 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 377 }
}
country = {
	tag = LYKI
	form_of_goverment = feudal
	capital = 747
	tier = duchy 
	ruler = { character = { type = 10 id = 15024 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 747 }
}
country = {
	tag = MEAT
	form_of_goverment = feudal
	capital = 11
	tier = duchy 
	ruler = { character = { type = 10 id = 4514 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 11 10 31 }
}
country = {
	tag = MEIS
	form_of_goverment = feudal
	capital = 312
	tier = duchy 
	ruler = { character = { type = 10 id = 12038 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 312 }
}
country = {
	tag = MILA
	form_of_goverment = republican
	capital = 235
	tier = duchy 
	ruler = { character = { type = 10 id = 13020 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 235 246 }
}
country = {
	tag = MORA
	form_of_goverment = feudal
	capital = 441
	tier = duchy 
	ruler = { character = { type = 10 id = 12057 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 441 438 440 }
}
country = {
	tag = DNAV
	form_of_goverment = feudal
	capital = 201
	tier = duchy 
	ruler = { character = { type = 10 id = 6520 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 201 }
}
country = {
	tag = NIKA
	form_of_goverment = feudal
	capital = 750
	tier = duchy 
	ruler = { character = { type = 10 id = 15670 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 750 }
}
country = {
	tag = NIKO
	form_of_goverment = feudal
	capital = 741
	tier = duchy 
	ruler = { character = { type = 10 id = 15035 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 741 }
}
country = {
	tag = NOVG
	form_of_goverment = feudal
	capital = 410
	tier = duchy 
	ruler = { character = { type = 10 id = 22020 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 410 }
}
country = {
	tag = ORKN
	form_of_goverment = feudal
	capital = 36
	tier = duchy 
	ruler = { character = { type = 10 id = 20020 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 36 34 37 }
}
country = {
	tag = OULT
	form_of_goverment = feudal
	capital = 777
	tier = duchy 
	ruler = { character = { type = 10 id = 23592 } startdate = { year = 1187 month = january day = 0 } }
	laws = { feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 777 778 724 776 782 786 }
}
country = {
	tag = ACHA
	form_of_goverment = feudal
	capital = 476
	tier = duchy 
	ruler = { character = { type = 10 id = 15009 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 476 }
}
country = {
	tag = PERE
	form_of_goverment = feudal
	capital = 555
	tier = duchy 
	ruler = { character = { type = 10 id = 22660 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 555 565 }
}
country = {
	tag = POLO
	form_of_goverment = feudal
	capital = 419
	tier = duchy 
	ruler = { character = { type = 10 id = 22550 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 419 424 }
}
country = {
	tag = POMM
	form_of_goverment = feudal
	capital = 366
	tier = duchy 
	ruler = { character = { type = 10 id = 21710 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 366 308 }
}
country = {
	tag = PRON
	form_of_goverment = feudal
	capital = 567
	tier = duchy 
	ruler = { character = { type = 10 id = 22630 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 567 }
}
country = {
	tag = PRUS
	form_of_goverment = feudal
	capital = 370
	tier = duchy 
	ruler = { character = { type = 10 id = 28015 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 370 369 }
}
country = {
	tag = PSKO
	form_of_goverment = feudal
	capital = 535
	tier = duchy 
	ruler = { character = { type = 10 id = 22520 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 535 }
}
country = {
	tag = ROMA
	form_of_goverment = republican
	capital = 353
	tier = duchy 
	ruler = { character = { type = 10 id = 13009 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 321 353 }
}
country = {
	tag = RYAZ
	form_of_goverment = feudal
	capital = 581
	tier = duchy 
	ruler = { character = { type = 10 id = 22770 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 581 584 585 }
}
country = {
	tag = SAMO
	form_of_goverment = feudal
	capital = 372
	tier = duchy 
	ruler = { character = { type = 10 id = 28022 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 372 }
}
country = {
	tag = SAVO
	form_of_goverment = feudal
	capital = 237
	tier = duchy 
	ruler = { character = { type = 10 id = 13110 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 237 }
}
country = {
	tag = SAXO
	form_of_goverment = feudal
	capital = 120
	tier = duchy 
	ruler = { character = { type = 10 id = 12905 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 310 256 120 309 }
}
country = {
	tag = SEVI
	form_of_goverment = feudal
	capital = 182
	tier = duchy 
	ruler = { character = { type = 10 id = 24020 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 182 }
}
country = {
	tag = SILE
	form_of_goverment = feudal
	capital = 434
	tier = duchy 
	ruler = { character = { type = 10 id = 21530 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 434 435 }
}
country = {
	tag = SINO
	form_of_goverment = feudal
	capital = 739
	tier = duchy 
	ruler = { character = { type = 10 id = 15037 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 739 }
}
country = {
	tag = SKAN
	form_of_goverment = ecclestical
	capital = 303
	tier = duchy 
	ruler = { character = { type = 10 id = 1520 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 303 302 305 }
}
country = {
	tag = SMOL
	form_of_goverment = feudal
	capital = 568
	tier = duchy 
	ruler = { character = { type = 10 id = 22570 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 568 }
}
country = {
	tag = SPMA
	form_of_goverment = feudal
	capital = 368
	tier = duchy 
	ruler = { character = { type = 10 id = 21750 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 368 }
}
country = {
	tag = SPOL
	form_of_goverment = feudal
	capital = 349
	tier = duchy 
	ruler = { character = { type = 10 id = 13100 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 349 }
}
country = {
	tag = SUZD
	form_of_goverment = feudal
	capital = 554
	tier = duchy 
	ruler = { character = { type = 10 id = 22600 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 554 551 553 576 }
}
country = {
	tag = SWAB
	form_of_goverment = feudal
	capital = 249
	tier = duchy 
	ruler = { character = { type = 10 id = 12500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 249 126 134 250 251 252 }
}
country = {
	tag = THES
	form_of_goverment = feudal
	capital = 490
	tier = duchy 
	ruler = { character = { type = 10 id = 15503 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 490 }
}
country = {
	tag = TOSC
	form_of_goverment = republican
	capital = 327
	tier = duchy 
	ruler = { character = { type = 10 id = 13013 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 327 331 }
}
country = {
	tag = TOUL
	form_of_goverment = feudal
	capital = 214
	tier = duchy 
	ruler = { character = { type = 10 id = 5530 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 214 218 219 223 }
}
country = {
	tag = TRAP
	form_of_goverment = feudal
	capital = 678
	tier = duchy 
	ruler = { character = { type = 10 id = 15519 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 678 }
}
country = {
	tag = TRIP
	form_of_goverment = feudal
	capital = 767
	tier = duchy 
	ruler = { character = { type = 10 id = 23650 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 767 766 } 
}
country = {
	tag = TRON
	form_of_goverment = feudal
	capital = 277
	tier = duchy 
	ruler = { character = { type = 10 id = 2030 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 277 }
}
country = {
	tag = DTUN
	form_of_goverment = feudal
	capital = 817
	tier = duchy 
	ruler = { character = { type = 10 id = 24026 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 817 }
}
country = {
	tag = TURO
	form_of_goverment = feudal
	capital = 552
	tier = duchy 
	ruler = { character = { type = 10 id = 22540 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 552 548 }
}
country = {
	tag = UPLO
	form_of_goverment = feudal
	capital = 127
	tier = duchy 
	ruler = { character = { type = 10 id = 12580 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 127 118 124 }
}
country = {
	tag = UPPL
	form_of_goverment = ecclestical
	capital = 290
	tier = duchy 
	ruler = { character = { type = 10 id = 16 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 290 }
}
country = {
	tag = VALE
	form_of_goverment = feudal
	capital = 171
	tier = duchy 
	ruler = { character = { type = 10 id = 24006 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 171 }
}
country = {
	tag = VARN
	form_of_goverment = feudal
	capital = 509
	tier = duchy 
	ruler = { character = { type = 10 id = 17501 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 509 }
}

country = {
	tag = VERO
	form_of_goverment = republican
	capital = 319
	tier = duchy 
	ruler = { character = { type = 10 id = 12072 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 319 }
}
country = {
	tag = WIEL
	form_of_goverment = feudal
	capital = 432
	tier = duchy 
	ruler = { character = { type = 10 id = 21560 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 432 431 429 }
}
country = {
	tag = VISE
	form_of_goverment = feudal
	capital = 550
	tier = duchy 
	ruler = { character = { type = 10 id = 22790 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 550 }
}
country = {
	tag = VLAD
	form_of_goverment = feudal
	capital = 582
	tier = duchy 
	ruler = { character = { type = 10 id = 22670 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 582 572 575 578 404 405 406 407 408 571 }
}
country = {
	tag = VOLG
	form_of_goverment = feudal
	capital = 611
	tier = duchy 
	ruler = { character = { type = 10 id = 29000 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 611 }
}
country = {
	tag = YORK
	form_of_goverment = ecclestical
	capital = 57
	tier = duchy 
	ruler = { character = { type = 10 id = 4516 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 57 }
}
country = {
	tag = ZARB
	form_of_goverment = feudal
	capital = 467
	tier = duchy 
	ruler = { character = { type = 10 id = 20495 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 467 }
}
country = {
	tag = OSTE
	form_of_goverment = feudal
	capital = 449
	tier = duchy 
	ruler = { character = { type = 10 id = 12530 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 449 446 }
}
country = {
	tag = SVIG
	form_of_goverment = feudal
	capital = 264
	tier = duchy 
	ruler = { character = { type = 10 id = 1501 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 264 263 }
}
country = {
	tag = THRA
	form_of_goverment = feudal
	capital = 497
	tier = duchy 
	ruler = { character = { type = 10 id = 15001 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 497 }
}
country = {
	tag = OSTR
	form_of_goverment = feudal
	capital = 293
	tier = duchy 
	ruler = { character = { type = 10 id = 540 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 293 292 }
}
country = {
	tag = ARAG
	form_of_goverment = feudal
	capital = 204
	tier = kingdom 
	ruler = { character = { type = 10 id = 10500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 204 207 174 175 202 203 211 221 }
}
country = {
	tag = BULG
	form_of_goverment = feudal
	capital = 499
	tier = kingdom 
	ruler = { character = { type = 10 id = 17500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_gavelkind_law = yes traditional_custom_law = yes regal_supremacy = yes }
	controlledprovinces = { 499 498 500 507 508 }
}
country = {
	tag = BYZA
	form_of_goverment = feudal
	capital = 496
	tier = kingdom 
	ruler = { character = { type = 10 id = 15500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 496 }
}
country = {
	tag = CAST
	form_of_goverment = feudal
	capital = 197
	tier = kingdom 
	ruler = { character = { type = 10 id = 7510 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 197 198 200 }
}
country = {
	tag = CUMA
	form_of_goverment = feudal
	capital = 513
	tier = kingdom 
	ruler = { character = { type = 10 id = 28030 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 513 }
}
country = {
	tag = DENM
	form_of_goverment = feudal
	capital = 266
	tier = kingdom 
	ruler = { character = { type = 10 id = 1500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 266 }
}
country = {
	tag = ENGL
	form_of_goverment = feudal
	capital = 27
	tier = kingdom 
	ruler = { character = { type = 10 id = 4500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 27 28 30 32 53 55 58 61 68 73 108 140 97 98 }
}
country = {
	tag = FRAN
	form_of_goverment = feudal
	capital = 112
	tier = kingdom 
	ruler = { character = { type = 10 id = 5506 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 112 77 113 131 138 139 145 }
}

country = {
	tag = GEOR
	form_of_goverment = feudal
	capital = 676
	tier = kingdom 
	ruler = { character = { type = 10 id = 16500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_gavelkind_law = yes traditional_custom_law = yes regal_supremacy = yes }
	controlledprovinces = { 676 679 680 } 
}

country = {
	tag = GERM
	form_of_goverment = feudal
	capital = 359
	tier = kingdom 
	ruler = { character = { type = 10 id = 12501 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 359 135 222 }
}
country = {
	tag = HUNG
	form_of_goverment = feudal
	capital = 522
	tier = kingdom 
	ruler = { character = { type = 10 id = 19500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 522 }
}
country = {
	tag = ITAL
	form_of_goverment = feudal
	capital = 234
	tier = kingdom 
	ruler = { character = { type = 10 id = 12507 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 234 }
}
country = {
	tag = JERU
	form_of_goverment = feudal
	capital = 774
	tier = kingdom 
	ruler = { character = { type = 10 id = 23522 } startdate = { year = 1187 month = january day = 0 } }
	laws = { monastic_supremacy = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 774 771 772 725 780 775 }
}
country = {
	tag = LEON
	form_of_goverment = feudal
	capital = 190
	tier = kingdom 
	ruler = { character = { type = 10 id = 8500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 190 155 156 189 192 193 194 }
}
country = {
	tag = NAPL
	form_of_goverment = feudal
	capital = 339
	tier = kingdom 
	ruler = { character = { type = 10 id = 11500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 339 334 336 337 338 340 341 342 343 346 347 348 812 }
}
country = {
	tag = NAVA
	form_of_goverment = feudal
	capital = 152
	tier = kingdom 
	ruler = { character = { type = 10 id = 6500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 152 }
}
country = {
	tag = NORW
	form_of_goverment = feudal
	capital = 274
	tier = kingdom 
	ruler = { character = { type = 10 id = 2500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 274 }
}
country = {
	tag = POLA
	form_of_goverment = feudal
	capital = 527
	tier = kingdom 
	ruler = { character = { type = 10 id = 21520 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 527 531 528 529 530 532 }
}
country = {
	tag = PORT
	form_of_goverment = feudal
	capital = 160
	tier = kingdom 
	ruler = { character = { type = 10 id = 9500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 160 159 161 186 187 }
}
country = {
	tag = SCOT
	form_of_goverment = feudal
	capital = 46
	tier = kingdom 
	ruler = { character = { type = 10 id = 2999 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 44 48 }
}
country = {
	tag = SERB
	form_of_goverment = feudal
	capital = 502
	tier = kingdom 
	ruler = { character = { type = 10 id = 18500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes regal_supremacy = yes }
	controlledprovinces = { 502 469 }
}
country = {
	tag = SWED
	form_of_goverment = feudal
	capital = 297
	tier = kingdom 
	ruler = { character = { type = 10 id = 500 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 297 294 382 }
}
country = {
	tag = MDAM
	form_of_goverment = feudal
	capital = 727
	tier = duchy 
	ruler = { character = { type = 10 id = 26020 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 727 }
}
country = {
	tag = MELA
	form_of_goverment = feudal
	capital = 787
	tier = duchy 
	ruler = { character = { type = 10 id = 26030 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 787 }
}
country = {
	tag = MMOS
	form_of_goverment = feudal
	capital = 697
	tier = duchy 
	ruler = { character = { type = 10 id = 26013 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 697 }
}
country = {
	tag = MEDE
	form_of_goverment = feudal
	capital = 683
	tier = duchy 
	ruler = { character = { type = 10 id = 26001 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 683 }
}
country = {
	tag = MMED
	form_of_goverment = feudal
	capital = 718
	tier = duchy 
	ruler = { character = { type = 10 id = 26036 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 718 }
}
country = {
	tag = MKHW
	form_of_goverment = feudal
	capital = 646
	tier = kingdom 
	ruler = { character = { type = 10 id = 30000 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 646 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 647 648 659 660 661 662 663 665 }
}
country = {
	tag = MALE
	form_of_goverment = feudal
	capital = 733
	tier = duchy 
	ruler = { character = { type = 10 id = 26007 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 733 }
}
country = {
	tag = PAPA
	form_of_goverment = ecclestical
	capital = 333
	tier = kingdom 
	ruler = { character = { type = 10 id = 23754 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 333 }
}

country = { 
	tag = VENI 
	form_of_goverment = republican 
	capital = 356 
	tier = kingdom 
	ruler = { character = { type = 10 id = 13600 } startdate = { year = 1187 month = january day = 0 } } 
	laws = { elective_law = yes popular_law = yes church_supremacy = yes } 
	church = 0.700 
	controlledprovinces = { 356 458 } 
} 

country = {
	tag = CILI
	form_of_goverment = feudal
	capital = 736
	tier = kingdom 
	ruler = { character = { type = 10 id = 23000 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 736 }
}
country = {
	tag = ABBA
	form_of_goverment = feudal
	capital = 693
	tier = kingdom 
	ruler = { character = { type = 10 id = 27000 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes ecclesical_balance = yes }
	controlledprovinces = { 693 }
}
country = {
	tag = ALMO
	form_of_goverment = feudal
	capital = 843
	tier = kingdom 
	ruler = { character = { type = 10 id = 24000 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 843 840 842 844 845 846 847 }
}
country = {
	tag = ASSA
	form_of_goverment = feudal
	capital = 765
	tier = duchy 
	ruler = { character = { type = 10 id = 27012 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 765 }
}
country = {
	tag = BALE
	form_of_goverment = feudal
	capital = 827
	tier = duchy 
	ruler = { character = { type = 10 id = 24048 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 827 }
}
country = {
	tag = RUMS
	form_of_goverment = feudal
	capital = 737
	tier = kingdom 
	ruler = { character = { type = 10 id = 25000 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 737 }
}
country = {
	tag = NOSE
	form_of_goverment = feudal
	capital = 503
	tier = kingdom 
	ruler = { character = { type = 10 id = 18800 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes regal_supremacy = yes }
	controlledprovinces = { 503 504 }
}
country = {
	tag = CURO
	form_of_goverment = feudal
	capital = 373
	tier = duchy 
	ruler = { character = { type = 10 id = 28075 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 373 }
}
country = {
	tag = ESTS
	form_of_goverment = feudal
	capital = 380
	tier = duchy 
	ruler = { character = { type = 10 id = 28026 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 380 }
}
country = {
	tag = HOSP
	form_of_goverment = knight_order
	capital = 768
	tier = duchy 
	ruler = { character = { type = 10 id = 31000 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 768 }
}

country = {
	tag = LETT
	form_of_goverment = feudal
	capital = 375
	tier = duchy 
	ruler = { character = { type = 10 id = 28020 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 375 }
}

country = {
	tag = MANN
	form_of_goverment = feudal
	capital = 35
	tier = kingdom 
	ruler = { character = { type = 10 id = 20019 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 35 }
}
country = {
	tag = PRUT
	form_of_goverment = feudal
	capital = 371
	tier = duchy 
	ruler = { character = { type = 10 id = 28016 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 371 }
}
country = {
	tag = YATV
	form_of_goverment = feudal
	capital = 426
	tier = duchy 
	ruler = { character = { type = 10 id = 28017 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 426 }
}
country = {
	tag = ZEMI
	form_of_goverment = feudal
	capital = 374
	tier = duchy 
	ruler = { character = { type = 10 id = 20603 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 374 }
}
country = {
	tag = ERZE
	form_of_goverment = feudal
	capital = 702
	tier = kingdom 
	ruler = { character = { type = 10 id = 25025 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 702 }
}
country = {
	tag = ESAM
	form_of_goverment = feudal
	capital = 386
	tier = duchy 
	ruler = { character = { type = 10 id = 28001 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 386 }
}
country = {
	tag = INGE
	form_of_goverment = feudal
	capital = 411
	tier = duchy 
	ruler = { character = { type = 10 id = 28007 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 411 }
}
country = {
	tag = KAJA
	form_of_goverment = feudal
	capital = 389
	tier = duchy 
	ruler = { character = { type = 10 id = 28010 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 389 }
}
country = {
	tag = KEXH
	form_of_goverment = feudal
	capital = 392
	tier = duchy 
	ruler = { character = { type = 10 id = 28035 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 392 }
}
country = {
	tag = KIRK
	form_of_goverment = feudal
	capital = 687
	tier = duchy 
	ruler = { character = { type = 10 id = 25011 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 687 }
}
country = {
	tag = KOLA
	form_of_goverment = feudal
	capital = 387
	tier = duchy 
	ruler = { character = { type = 10 id = 28009 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 387 }
}
country = {
	tag = LITT
	form_of_goverment = feudal
	capital = 416
	tier = duchy 
	ruler = { character = { type = 10 id = 28012 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 416 }
}
country = {
	tag = MORD
	form_of_goverment = feudal
	capital = 579
	tier = duchy 
	ruler = { character = { type = 10 id = 28070 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 579 }
}
country = {
	tag = SATA
	form_of_goverment = feudal
	capital = 384
	tier = duchy 
	ruler = { character = { type = 10 id = 28011 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 384 }
}
country = {
	tag = FINL
	form_of_goverment = feudal
	capital = 381
	tier = duchy 
	ruler = { character = { type = 10 id = 28002 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 381 }
}
country = {
	tag = TAVA
	form_of_goverment = feudal
	capital = 383
	tier = duchy 
	ruler = { character = { type = 10 id = 28003 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 383 }
}
country = {
	tag = VOTE
	form_of_goverment = feudal
	capital = 391
	tier = duchy 
	ruler = { character = { type = 10 id = 28006 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 391 }
}
country = {
	tag = WSAM
	form_of_goverment = feudal
	capital = 279
	tier = duchy 
	ruler = { character = { type = 10 id = 28000 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 279 }
}
country = {
	tag = VLAC
	form_of_goverment = feudal
	capital = 515
	tier = duchy 
	ruler = { character = { type = 10 id = 28027 } startdate = { year = 1187 month = january day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 515 }
}
country = {
	tag = SGAL
	form_of_goverment = republican
	capital = 84
	tier = kingdom 
	ruler = { character = { type = 10 id = 31002 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 84 }
}
country = {
	tag = NUBI
	form_of_goverment = feudal
	capital = 793
	tier = kingdom 
	ruler = { character = { type = 10 id = 20572 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 793 792 }
}
country = {
	tag = FATI
	form_of_goverment = feudal
	capital = 797
	tier = kingdom 
	ruler = { character = { type = 10 id = 26000 } startdate = { year = 1187 month = january day = 0 } }
	laws = { semisalic_gavelkind_law = yes royal_preorgatory_law = yes ecclesical_balance = yes }
	controlledprovinces = { 797 790 791 794 795 796 789 798 799 800 801 802 }
}
country = {
	tag = TEMP 
	form_of_goverment = knight_order 
	capital = 773 
	tier = duchy 
	ruler = { character = { type = 10 id = 31001 } startdate = { year = 1187 month = january day = 0 } } 
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes } 
	church = 0.700 
	controlledprovinces = { 773 } 
}
country = {
	tag = U000
	form_of_goverment = knight_order
	capital = 177
	tier = duchy 
	ruler = { character = { type = 10 id = 32021 } startdate = { year = 1187 month = january day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 177 }
}
