title = { 
	tag = C001 
	tier = county 
	liege = ICEL 
	holder = { character = { type = 10 id = 2011 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C002 
	tier = county 
	liege = ICEL 
	holder = { character = { type = 10 id = 2011 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C003 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 14006 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C004 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 14007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C005 
	tier = county 
	liege = ULST 
	holder = { character = { type = 10 id = 14000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C006 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 14 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C007 
	tier = county 
	liege = CONN 
	holder = { character = { type = 10 id = 14505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C008 
	tier = county 
	liege = CONN 
	holder = { character = { type = 10 id = 14505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C009 
	tier = county 
	liege = CONN 
	holder = { character = { type = 10 id = 14505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C010 
	tier = county 
	liege = MEAT 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C011 
	tier = county 
	liege = MEAT 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C012 
	tier = county 
	liege = MEAT 
	holder = { character = { type = 10 id = 14581 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C013 
	tier = county 
	liege = CONN 
	holder = { character = { type = 10 id = 14505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C014 
	tier = county 
	liege = MEAT 
	holder = { character = { type = 10 id = 14600 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C015 
	tier = county 
	liege = MEAT 
	holder = { character = { type = 10 id = 4038 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C016 
	tier = county 
	liege = LEIN 
	holder = { character = { type = 10 id = 14553 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C017 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4600 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C018 
	tier = county 
	liege = GWYN 
	holder = { character = { type = 10 id = 14804 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C019 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C020 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4004 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C021 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 30109 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C022 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4551 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C023 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 30141 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C024 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4635 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C025 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 30138 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C026 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C027 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C028 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C029 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4760 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C030 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C031 
	tier = county 
	liege = MEAT 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C032 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C033 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 2013 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C034 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 20018 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C035 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 20019 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C036 
	tier = county 
	liege = ORKN 
	holder = { character = { type = 10 id = 20020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C037 
	tier = county 
	liege = ORKN 
	holder = { character = { type = 10 id = 20020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C038 
	tier = county 
	liege = SCOT 
	holder = { character = { type = 10 id = 3002 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C039 
	tier = county 
	liege = SCOT 
	holder = { character = { type = 10 id = 3000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C040 
	tier = county 
	liege = SCOT 
	holder = { character = { type = 10 id = 3000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C041 
	tier = county 
	liege = SCOT 
	holder = { character = { type = 10 id = 3005 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C042 
	tier = county 
	liege = SCOT 
	holder = { character = { type = 10 id = 3006 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C043 
	tier = county 
	liege = SCOT 
	holder = { character = { type = 10 id = 3007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C044 
	tier = county 
	liege = SCOT 
	holder = { character = { type = 10 id = 3000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C045 
	tier = county 
	liege = SCOT 
	holder = { character = { type = 10 id = 3000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C046 
	tier = county 
	liege = SCOT 
	holder = { character = { type = 10 id = 3010 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C047 
	tier = county 
	liege = SCOT 
	holder = { character = { type = 10 id = 3000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C048 
	tier = county 
	liege = SCOT 
	holder = { character = { type = 10 id = 3009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C049 
	tier = county 
	liege = GALL 
	holder = { character = { type = 10 id = 3540 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C050 
	tier = county 
	liege = GALL 
	holder = { character = { type = 10 id = 3570 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C051 
	tier = county 
	liege = SCOT 
	holder = { character = { type = 10 id = 3014 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C052 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 3520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C053 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C054 
	tier = county 
	liege = WEIS 
	holder = { character = { type = 10 id = 20021 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C055 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C056 
	tier = county 
	liege = YORK 
	holder = { character = { type = 10 id = 30127 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C057 
	tier = county 
	liege = YORK 
	holder = { character = { type = 10 id = 30125 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C058 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C059 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4680 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C060 
	tier = county 
	liege = GWYN 
	holder = { character = { type = 10 id = 14714 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C061 
	tier = county 
	liege = YORK 
	holder = { character = { type = 10 id = 30143 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C062 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 30015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C063 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4694 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C064 
	tier = county 
	liege = GWYN 
	holder = { character = { type = 10 id = 14714 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C065 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 14724 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C066 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C067 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4711 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C068 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C069 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 30142 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C070 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4730 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C071 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4730 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C072 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 30139 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C073 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C074 
	tier = county 
	liege = FRAN 
	holder = { character = { type = 10 id = 30051 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C075 
	tier = county 
	liege = FRAN 
	holder = { character = { type = 10 id = 30097 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C076 
	tier = county 
	liege = FLAN 
	holder = { character = { type = 10 id = 5523 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C077 
	tier = county 
	liege = FRAN 
	holder = { character = { type = 10 id = 5506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C078 
	tier = county 
	liege = FLAN 
	holder = { character = { type = 10 id = 5523 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C079 
	tier = county 
	liege = BRAB 
	holder = { character = { type = 10 id = 6852 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C080 
	tier = county 
	liege = BRAB 
	holder = { character = { type = 10 id = 6843 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C081 
	tier = county 
	liege = BRAB 
	holder = { character = { type = 10 id = 6852 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C082 
	tier = county 
	liege = BRAB 
	holder = { character = { type = 10 id = 6852 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C083 
	tier = county 
	liege = BRAB 
	holder = { character = { type = 10 id = 6831 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C084 
	tier = county 
	liege = BRAB 
	holder = { character = { type = 10 id = 6843 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C085 
	tier = county 
	liege = BRAB 
	holder = { character = { type = 10 id = 6852 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C086 
	tier = county 
	liege = SAXO 
	holder = { character = { type = 10 id = 12910 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C087 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 30258 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C088 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 30257 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C089 
	tier = county 
	liege = SAXO 
	holder = { character = { type = 10 id = 12922 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C090 
	tier = county 
	liege = BRAB 
	holder = { character = { type = 10 id = 6900 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C091 
	tier = county 
	liege = BRAB 
	holder = { character = { type = 10 id = 6802 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C092 
	tier = county 
	liege = BRAB 
	holder = { character = { type = 10 id = 6852 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C093 
	tier = county 
	liege = FLAN 
	holder = { character = { type = 10 id = 5523 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C094 
	tier = county 
	liege = FLAN 
	holder = { character = { type = 10 id = 5523 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C095 
	tier = county 
	liege = FRAN 
	holder = { character = { type = 10 id = 4981 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C096 
	tier = county 
	liege = NORM 
	holder = { character = { type = 10 id = 5659 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C097 
	tier = county 
	liege = NORM 
	holder = { character = { type = 10 id = 5506 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80006 } character = { type = 10 id = 4514 } } 
} 
title = { 
	tag = C098 
	tier = county 
	liege = NORM 
	holder = { character = { type = 10 id = 5506 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80007 } character = { type = 10 id = 4514 } } 
} 
title = { 
	tag = C099 
	tier = county 
	liege = NORM 
	holder = { character = { type = 10 id = 5506 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80008 } character = { type = 10 id = 4514 } } 
} 
title = { 
	tag = C100 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4680 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C101 
	tier = county 
	liege = BRIT 
	holder = { character = { type = 10 id = 30133 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C102 
	tier = county 
	liege = BRIT 
	holder = { character = { type = 10 id = 5742 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C103 
	tier = county 
	liege = BRIT 
	holder = { character = { type = 10 id = 5781 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C104 
	tier = county 
	liege = BRIT 
	holder = { character = { type = 10 id = 30133 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C105 
	tier = county 
	liege = BRIT 
	holder = { character = { type = 10 id = 30133 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C106 
	tier = county 
	liege = BRIT 
	holder = { character = { type = 10 id = 30133 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C107 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80000 } character = { type = 10 id = 5506 } } 
} 
title = { 
	tag = C108 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 5506 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80009 } character = { type = 10 id = 4514 } } 
} 
title = { 
	tag = C109 
	tier = county 
	liege = ANJO 
	holder = { character = { type = 10 id = 30073 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C110 
	tier = county 
	liege = CHAM 
	holder = { character = { type = 10 id = 5895 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C111 
	tier = county 
	liege = CHAM 
	holder = { character = { type = 10 id = 5884 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C112 
	tier = county 
	liege = FRAN 
	holder = { character = { type = 10 id = 5506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C113 
	tier = county 
	liege = FRAN 
	holder = { character = { type = 10 id = 5506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C114 
	tier = county 
	liege = FRAN 
	holder = { character = { type = 10 id = 30126 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C115 
	tier = county 
	liege = UPLO 
	holder = { character = { type = 10 id = 12692 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C116 
	tier = county 
	liege = BRAB 
	holder = { character = { type = 10 id = 30253 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C117 
	tier = county 
	liege = BRAB 
	holder = { character = { type = 10 id = 6852 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C118 
	tier = county 
	liege = UPLO 
	holder = { character = { type = 10 id = 12580 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C119 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 30136 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C120 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 12572 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C121 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 12371 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C122 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 30259 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C123 
	tier = county 
	liege = SWAB 
	holder = { character = { type = 10 id = 30135 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C124 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 30265 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C125 
	tier = county 
	liege = SWAB 
	holder = { character = { type = 10 id = 12402 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C126 
	tier = county 
	liege = SWAB 
	holder = { character = { type = 10 id = 12506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C127 
	tier = county 
	liege = UPLO 
	holder = { character = { type = 10 id = 12580 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C128 
	tier = county 
	liege = UPLO 
	holder = { character = { type = 10 id = 12001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C129 
	tier = county 
	liege = UPLO 
	holder = { character = { type = 10 id = 12002 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C130 
	tier = county 
	liege = CHAM 
	holder = { character = { type = 10 id = 30128 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C131 
	tier = county 
	liege = BOUG 
	holder = { character = { type = 10 id = 5726 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C132 
	tier = county 
	liege = BOUG 
	holder = { character = { type = 10 id = 5726 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C133 
	tier = county 
	liege = UPLO 
	holder = { character = { type = 10 id = 12633 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C134 
	tier = county 
	liege = SWAB 
	holder = { character = { type = 10 id = 12506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C135 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 30134 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C136 
	tier = county 
	liege = FRAN 
	holder = { character = { type = 10 id = 12782 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C137 
	tier = county 
	liege = BOUG 
	holder = { character = { type = 10 id = 5726 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C138 
	tier = county 
	liege = FRAN 
	holder = { character = { type = 10 id = 5506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C139 
	tier = county 
	liege = FRAN 
	holder = { character = { type = 10 id = 5506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C140 
	tier = county 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80001 } character = { type = 10 id = 5506 } } 
} 
title = { 
	tag = C141 
	tier = county 
	liege = POIT 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80005 } character = { type = 10 id = 5506 } } 
} 
title = { 
	tag = C142 
	tier = county 
	liege = POIT 
	holder = { character = { type = 10 id = 5930 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C143 
	tier = county 
	liege = POIT 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C144 
	tier = county 
	liege = POIT 
	holder = { character = { type = 10 id = 5660 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C145 
	tier = county 
	liege = FRAN 
	holder = { character = { type = 10 id = 5660 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C146 
	tier = county 
	liege = BOUG 
	holder = { character = { type = 10 id = 30131 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C147 
	tier = county 
	liege = BORD 
	holder = { character = { type = 10 id = 5622 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C148 
	tier = county 
	liege = BORD 
	holder = { character = { type = 10 id = 5640 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C149 
	tier = county 
	liege = BORD 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C150 
	tier = county 
	liege = BORD 
	holder = { character = { type = 10 id = 5630 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C151 
	tier = county 
	liege = BORD 
	holder = { character = { type = 10 id = 5540 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C152 
	tier = county 
	liege = NAVA 
	holder = { character = { type = 10 id = 6502 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C153 
	tier = county 
	liege = CAST 
	holder = { character = { type = 10 id = 7560 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C154 
	tier = county 
	liege = CAST 
	holder = { character = { type = 10 id = 7546 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C155 
	tier = county 
	liege = LEON 
	holder = { character = { type = 10 id = 30235 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C156 
	tier = county 
	liege = LEON 
	holder = { character = { type = 10 id = 30235 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C157 
	tier = county 
	liege = LEON 
	holder = { character = { type = 10 id = 8520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C158 
	tier = county 
	liege = PORT 
	holder = { character = { type = 10 id = 9500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C159 
	tier = county 
	liege = PORT 
	holder = { character = { type = 10 id = 9500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C160 
	tier = county 
	liege = PORT 
	holder = { character = { type = 10 id = 9500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C161 
	tier = county 
	liege = PORT 
	holder = { character = { type = 10 id = 9500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C162 
	tier = county 
	liege = BADA 
	holder = { character = { type = 10 id = 24009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C163 
	tier = county 
	liege = SEVI 
	holder = { character = { type = 10 id = 24021 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C164 
	tier = county 
	liege = SEVI 
	holder = { character = { type = 10 id = 24022 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C165 
	tier = county 
	liege = SEVI 
	holder = { character = { type = 10 id = 24023 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C166 
	tier = county 
	liege = SEVI 
	holder = { character = { type = 10 id = 24024 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C167 
	tier = county 
	liege = ALME 
	holder = { character = { type = 10 id = 24017 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C168 
	tier = county 
	liege = ALME 
	holder = { character = { type = 10 id = 24015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C169 
	tier = county 
	liege = VALE 
	holder = { character = { type = 10 id = 24012 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C170 
	tier = county 
	liege = VALE 
	holder = { character = { type = 10 id = 24013 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C171 
	tier = county 
	liege = VALE 
	holder = { character = { type = 10 id = 24006 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C172 
	tier = county 
	liege = VALE 
	holder = { character = { type = 10 id = 24007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C173 
	tier = county 
	liege = ARAG 
	holder = { character = { type = 10 id = 10550 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C174 
	tier = county 
	liege = VALE 
	holder = { character = { type = 10 id = 30245 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C175 
	tier = county 
	liege = ARAG 
	holder = { character = { type = 10 id = 10500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C176 
	tier = county 
	liege = CAST 
	holder = { character = { type = 10 id = 7540 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C177 
	tier = county 
	liege = CAST 
	holder = { character = { type = 10 id = 7510 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C178 
	tier = county 
	liege = CORD 
	holder = { character = { type = 10 id = 24002 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C179 
	tier = county 
	liege = VALE 
	holder = { character = { type = 10 id = 24014 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C180 
	tier = county 
	liege = ALME 
	holder = { character = { type = 10 id = 24016 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C181 
	tier = county 
	liege = CORD 
	holder = { character = { type = 10 id = 24001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C182 
	tier = county 
	liege = SEVI 
	holder = { character = { type = 10 id = 24020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C183 
	tier = county 
	liege = SEVI 
	holder = { character = { type = 10 id = 24025 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C184 
	tier = county 
	liege = BADA 
	holder = { character = { type = 10 id = 24010 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C185 
	tier = county 
	liege = BADA 
	holder = { character = { type = 10 id = 24011 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C186 
	tier = county 
	liege = PORT 
	holder = { character = { type = 10 id = 9500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C187 
	tier = county 
	liege = PORT 
	holder = { character = { type = 10 id = 9500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C188 
	tier = county 
	liege = PORT 
	holder = { character = { type = 10 id = 9530 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C189 
	tier = county 
	liege = LEON 
	holder = { character = { type = 10 id = 30235 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C190 
	tier = county 
	liege = LEON 
	holder = { character = { type = 10 id = 30235 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C191 
	tier = county 
	liege = LEON 
	holder = { character = { type = 10 id = 30235 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C192 
	tier = county 
	liege = LEON 
	holder = { character = { type = 10 id = 30235 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C193 
	tier = county 
	liege = CORD 
	holder = { character = { type = 10 id = 24005 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C194 
	tier = county 
	liege = CORD 
	holder = { character = { type = 10 id = 24004 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C195 
	tier = county 
	liege = BADA 
	holder = { character = { type = 10 id = 24008 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C196 
	tier = county 
	liege = CORD 
	holder = { character = { type = 10 id = 24003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C197 
	tier = county 
	liege = CAST 
	holder = { character = { type = 10 id = 7510 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C198 
	tier = county 
	liege = CAST 
	holder = { character = { type = 10 id = 7510 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C199 
	tier = county 
	liege = CAST 
	holder = { character = { type = 10 id = 7546 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C200 
	tier = county 
	liege = CAST 
	holder = { character = { type = 10 id = 7510 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C201 
	tier = county 
	liege = DNAV 
	holder = { character = { type = 10 id = 6520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C202 
	tier = county 
	liege = ARAG 
	holder = { character = { type = 10 id = 10500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C203 
	tier = county 
	liege = ARAG 
	holder = { character = { type = 10 id = 10500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C204 
	tier = county 
	liege = ARAG 
	holder = { character = { type = 10 id = 10500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C205 
	tier = county 
	liege = ARAG 
	holder = { character = { type = 10 id = 10560 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C206 
	tier = county 
	liege = ARAG 
	holder = { character = { type = 10 id = 10570 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C207 
	tier = county 
	liege = ARAG 
	holder = { character = { type = 10 id = 10500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C208 
	tier = county 
	liege = TOUL 
	holder = { character = { type = 10 id = 5560 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C209 
	tier = county 
	liege = BORD 
	holder = { character = { type = 10 id = 5673 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C210 
	tier = county 
	liege = TOUL 
	holder = { character = { type = 10 id = 5554 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C211 
	tier = county 
	liege = TOUL 
	holder = { character = { type = 10 id = 5532 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C212 
	tier = county 
	liege = CAST 
	holder = { character = { type = 10 id = 7540 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C213 
	tier = county 
	liege = TOUL 
	holder = { character = { type = 10 id = 5572 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C214 
	tier = county 
	liege = TOUL 
	holder = { character = { type = 10 id = 5532 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C215 
	tier = county 
	liege = BORD 
	holder = { character = { type = 10 id = 5532 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C216 
	tier = county 
	liege = BORD 
	holder = { character = { type = 10 id = 5600 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C217 
	tier = county 
	liege = BORD 
	holder = { character = { type = 10 id = 30124 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C218 
	tier = county 
	liege = TOUL 
	holder = { character = { type = 10 id = 5532 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C219 
	tier = county 
	liege = TOUL 
	holder = { character = { type = 10 id = 5532 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C220 
	tier = county 
	liege = TOUL 
	holder = { character = { type = 10 id = 5580 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80010 } character = { type = 10 id = 10500 } } 
} 
title = { 
	tag = C221 
	tier = county 
	liege = TOUL 
	holder = { character = { type = 10 id = 5532 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C222 
	tier = county 
	liege = DAUP 
	holder = { character = { type = 10 id = 30039 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C223 
	tier = county 
	liege = TOUL 
	holder = { character = { type = 10 id = 5532 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C224 
	tier = county 
	liege = FRAN 
	holder = { character = { type = 10 id = 5680 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C225 
	tier = county 
	liege = BOUG 
	holder = { character = { type = 10 id = 5700 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C226 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 30079 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C227 
	tier = county 
	liege = FRAN 
	holder = { character = { type = 10 id = 12782 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C228 
	tier = county 
	liege = DAUP 
	holder = { character = { type = 10 id = 30039 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C229 
	tier = county 
	liege = ARAG 
	holder = { character = { type = 10 id = 5980 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C230 
	tier = county 
	liege = GENO 
	holder = { character = { type = 10 id = 13015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C231 
	tier = county 
	liege = SAVO 
	holder = { character = { type = 10 id = 13550 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C232 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13523 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C233 
	tier = county 
	liege = GENO 
	holder = { character = { type = 10 id = 13015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C234 
	tier = county 
	liege = MILA 
	holder = { character = { type = 10 id = 13019 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C235 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13019 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C236 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30102 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C237 
	tier = county 
	liege = SAVO 
	holder = { character = { type = 10 id = 30102 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C238 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30267 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C239 
	tier = county 
	liege = SAVO 
	holder = { character = { type = 10 id = 12742 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C240 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 30079 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C241 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30271 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C242 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30270 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C244 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30266 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C245 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30269 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C246 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30272 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C247 
	tier = county 
	liege = SWAB 
	holder = { character = { type = 10 id = 30264 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C248 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30268 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C249 
	tier = county 
	liege = SWAB 
	holder = { character = { type = 10 id = 12506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C250 
	tier = county 
	liege = SWAB 
	holder = { character = { type = 10 id = 12506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C251 
	tier = county 
	liege = SWAB 
	holder = { character = { type = 10 id = 12506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C252 
	tier = county 
	liege = SWAB 
	holder = { character = { type = 10 id = 12506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C253 
	tier = county 
	liege = SWAB 
	holder = { character = { type = 10 id = 12420 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C254 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 12506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C255 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 12431 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C256 
	tier = county 
	liege = SAXO 
	holder = { character = { type = 10 id = 12903 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C257 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 12572 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C258 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 12572 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C259 
	tier = county 
	liege = SAXO 
	holder = { character = { type = 10 id = 12905 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C260 
	tier = county 
	liege = DENM 
	holder = { character = { type = 10 id = 1001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C261 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30255 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C262 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 30256 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C263 
	tier = county 
	liege = DENM 
	holder = { character = { type = 10 id = 12360 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C264 
	tier = county 
	liege = DENM 
	holder = { character = { type = 10 id = 1003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C265 
	tier = county 
	liege = DENM 
	holder = { character = { type = 10 id = 1501 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C266 
	tier = county 
	liege = DENM 
	holder = { character = { type = 10 id = 1501 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C267 
	tier = county 
	liege = DENM 
	holder = { character = { type = 10 id = 1005 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C268 
	tier = county 
	liege = NORW 
	holder = { character = { type = 10 id = 2001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C269 
	tier = county 
	liege = NORW 
	holder = { character = { type = 10 id = 30221 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C270 
	tier = county 
	liege = NORW 
	holder = { character = { type = 10 id = 2003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C271 
	tier = county 
	liege = NORW 
	holder = { character = { type = 10 id = 2004 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C272 
	tier = county 
	liege = NORW 
	holder = { character = { type = 10 id = 2005 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C273 
	tier = county 
	liege = NORW 
	holder = { character = { type = 10 id = 2006 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C274 
	tier = county 
	liege = NORW 
	holder = { character = { type = 10 id = 30222 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C275 
	tier = county 
	liege = NORW 
	holder = { character = { type = 10 id = 2007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C276 
	tier = county 
	liege = NORW 
	holder = { character = { type = 10 id = 2008 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C277 
	tier = county 
	liege = NORW 
	holder = { character = { type = 10 id = 2009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C278 
	tier = county 
	liege = NORW 
	holder = { character = { type = 10 id = 2010 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C279 
	tier = county 
	liege = WSAM 
	holder = { character = { type = 10 id = 28000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C280 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 1 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C281 
	tier = county 
	liege = BERS 
	holder = { character = { type = 10 id = 2 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C282 
	tier = county 
	liege = NORW 
	holder = { character = { type = 10 id = 3 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C283 
	tier = county 
	liege = BERS 
	holder = { character = { type = 10 id = 4 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C284 
	tier = county 
	liege = BERS 
	holder = { character = { type = 10 id = 5 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C285 
	tier = county 
	liege = BERS 
	holder = { character = { type = 10 id = 6 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C286 
	tier = county 
	liege = BERS 
	holder = { character = { type = 10 id = 7 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C287 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 504 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C288 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 504 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C289 
	tier = county 
	liege = SWED 
	holder = { character = { type = 10 id = 30226 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C290 
	tier = county 
	liege = SWED 
	holder = { character = { type = 10 id = 30226 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C291 
	tier = county 
	liege = DENM 
	holder = { character = { type = 10 id = 1501 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C292 
	tier = county 
	liege = SWED 
	holder = { character = { type = 10 id = 30226 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C293 
	tier = county 
	liege = SWED 
	holder = { character = { type = 10 id = 30226 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C294 
	tier = county 
	liege = SWED 
	holder = { character = { type = 10 id = 30226 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C295 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 504 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C296 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30222 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C297 
	tier = county 
	liege = SWED 
	holder = { character = { type = 10 id = 30226 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C298 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 11 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C299 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 12 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C300 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C301 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 15 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C302 
	tier = county 
	liege = SKAN 
	holder = { character = { type = 10 id = 1520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C303 
	tier = county 
	liege = SKAN 
	holder = { character = { type = 10 id = 1520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C304 
	tier = county 
	liege = SKAN 
	holder = { character = { type = 10 id = 21730 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C305 
	tier = county 
	liege = SKAN 
	holder = { character = { type = 10 id = 1520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C306 
	tier = county 
	liege = SKAN 
	holder = { character = { type = 10 id = 1008 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C307 
	tier = county 
	liege = SKAN 
	holder = { character = { type = 10 id = 1009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C308 
	tier = county 
	liege = POMM 
	holder = { character = { type = 10 id = 21712 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C309 
	tier = county 
	liege = SAXO 
	holder = { character = { type = 10 id = 12905 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C310 
	tier = county 
	liege = SAXO 
	holder = { character = { type = 10 id = 12905 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C311 
	tier = county 
	liege = SAXO 
	holder = { character = { type = 10 id = 12905 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C312 
	tier = county 
	liege = MEIS 
	holder = { character = { type = 10 id = 12038 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C313 
	tier = county 
	liege = BAVA 
	holder = { character = { type = 10 id = 12390 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C314 
	tier = county 
	liege = BAVA 
	holder = { character = { type = 10 id = 12390 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C315 
	tier = county 
	liege = BAVA 
	holder = { character = { type = 10 id = 12964 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C316 
	tier = county 
	liege = BAVA 
	holder = { character = { type = 10 id = 12380 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C317 
	tier = county 
	liege = BAVA 
	holder = { character = { type = 10 id = 30261 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C318 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C319 
	tier = county 
	liege = VERO 
	holder = { character = { type = 10 id = 12072 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C320 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13008 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C321 
	tier = county 
	liege = ROMA 
	holder = { character = { type = 10 id = 13009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C322 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13012 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C323 
	tier = county 
	liege = LANG 
	holder = { character = { type = 10 id = 13018 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C324 
	tier = county 
	liege = LANG 
	holder = { character = { type = 10 id = 13018 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C325 
	tier = county 
	liege = GENO 
	holder = { character = { type = 10 id = 30248 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C326 
	tier = county 
	liege = LANG 
	holder = { character = { type = 10 id = 30247 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C327 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13013 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C328 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13014 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C329 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30251 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C330 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13017 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C331 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13018 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C332 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13016 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C333 
	tier = county 
	liege = PAPA 
	holder = { character = { type = 10 id = 23754 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C334 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C335 
	tier = county 
	liege = PAPA 
	holder = { character = { type = 10 id = 23754 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C336 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C337 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C338 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C339 
	tier = county 
	liege = NAPL 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C340 
	tier = county 
	liege = NAPL 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C341 
	tier = county 
	liege = NAPL 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C342 
	tier = county 
	liege = NAPL 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C343 
	tier = county 
	liege = NAPL 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C344 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30305 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80041 } character = { type = 10 id = 30282 } } 
} 
title = { 
	tag = C345 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C346 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C347 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C348 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C349 
	tier = county 
	liege = PAPA 
	holder = { character = { type = 10 id = 23754 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C350 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30250 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C351 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13010 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C352 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13011 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C353 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C354 
	tier = county 
	liege = VENE 
	holder = { character = { type = 10 id = 13024 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C355 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13022 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C356 
	tier = county 
	liege = VENI 
	holder = { character = { type = 10 id = 13600 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C357 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13023 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C358 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30249 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C359 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 12572 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C360 
	tier = county 
	liege = BAVA 
	holder = { character = { type = 10 id = 12950 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C361 
	tier = county 
	liege = BAVA 
	holder = { character = { type = 10 id = 12950 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C362 
	tier = county 
	liege = BAVA 
	holder = { character = { type = 10 id = 12950 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C363 
	tier = county 
	liege = DBOH 
	holder = { character = { type = 10 id = 12855 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C364 
	tier = county 
	liege = MEIS 
	holder = { character = { type = 10 id = 12038 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C365 
	tier = county 
	liege = BRAN 
	holder = { character = { type = 10 id = 12037 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C366 
	tier = county 
	liege = POMM 
	holder = { character = { type = 10 id = 21713 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C367 
	tier = county 
	liege = POMM 
	holder = { character = { type = 10 id = 21712 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C368 
	tier = county 
	liege = POLA 
	holder = { character = { type = 10 id = 21750 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C369 
	tier = county 
	liege = POLA 
	holder = { character = { type = 10 id = 21524 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C370 
	tier = county 
	liege = PRUS 
	holder = { character = { type = 10 id = 28015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C371 
	tier = county 
	liege = PRUT 
	holder = { character = { type = 10 id = 28016 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C372 
	tier = county 
	liege = SAMO 
	holder = { character = { type = 10 id = 28022 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C373 
	tier = county 
	liege = CURO 
	holder = { character = { type = 10 id = 28075 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C374 
	tier = county 
	liege = ZEMI 
	holder = { character = { type = 10 id = 20603 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C375 
	tier = county 
	liege = LIVO 
	holder = { character = { type = 10 id = 28023 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C376 
	tier = county 
	liege = ESTS 
	holder = { character = { type = 10 id = 28021 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C377 
	tier = county 
	liege = LIVO 
	holder = { character = { type = 10 id = 28023 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C378 
	tier = county 
	liege = ESTS 
	holder = { character = { type = 10 id = 28024 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C379 
	tier = county 
	liege = ESTS 
	holder = { character = { type = 10 id = 28025 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C380 
	tier = county 
	liege = ESTS 
	holder = { character = { type = 10 id = 28026 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C381 
	tier = county 
	liege = FINL 
	holder = { character = { type = 10 id = 28002 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C382 
	tier = county 
	liege = SWED 
	holder = { character = { type = 10 id = 30226 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C383 
	tier = county 
	liege = TAVA 
	holder = { character = { type = 10 id = 28003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C384 
	tier = county 
	liege = SATA 
	holder = { character = { type = 10 id = 28011 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C385 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 28008 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C386 
	tier = county 
	liege = ESAM 
	holder = { character = { type = 10 id = 28001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C387 
	tier = county 
	liege = KOLA 
	holder = { character = { type = 10 id = 28009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C388 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 28004 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C389 
	tier = county 
	liege = KAJA 
	holder = { character = { type = 10 id = 28010 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C390 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 28005 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C391 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 28006 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C392 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 28035 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C393 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 22020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C394 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 22020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C395 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 22020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C396 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 22020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C397 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 22025 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C398 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 22026 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C399 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 22027 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C400 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 29001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C401 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 29002 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C402 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C403 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 22020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C404 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C405 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 22020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C406 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 22020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C407 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C408 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C409 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 22030 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C410 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 22020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C411 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 28007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C412 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 28007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C413 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 22029 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C414 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 22020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C415 
	tier = county 
	liege = NOVG 
	holder = { character = { type = 10 id = 22034 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C416 
	tier = county 
	liege = POLO 
	holder = { character = { type = 10 id = 22560 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C417 
	tier = county 
	liege = POLO 
	holder = { character = { type = 10 id = 22550 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C418 
	tier = county 
	liege = POLO 
	holder = { character = { type = 10 id = 22550 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C419 
	tier = county 
	liege = POLO 
	holder = { character = { type = 10 id = 22550 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C420 
	tier = county 
	liege = LITT 
	holder = { character = { type = 10 id = 28012 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C421 
	tier = county 
	liege = LITT 
	holder = { character = { type = 10 id = 28014 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C422 
	tier = county 
	liege = YATV 
	holder = { character = { type = 10 id = 28017 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C423 
	tier = county 
	liege = LITT 
	holder = { character = { type = 10 id = 28014 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C424 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 22810 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C425 
	tier = county 
	liege = GALI 
	holder = { character = { type = 10 id = 22520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C426 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 22033 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C427 
	tier = county 
	liege = YATV 
	holder = { character = { type = 10 id = 28019 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C428 
	tier = county 
	liege = SILE 
	holder = { character = { type = 10 id = 21525 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C429 
	tier = county 
	liege = WIEL 
	holder = { character = { type = 10 id = 30530 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C430 
	tier = county 
	liege = WIEL 
	holder = { character = { type = 10 id = 30530 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C431 
	tier = county 
	liege = WIEL 
	holder = { character = { type = 10 id = 30545 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C432 
	tier = county 
	liege = WIEL 
	holder = { character = { type = 10 id = 30530 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C433 
	tier = county 
	liege = SILE 
	holder = { character = { type = 10 id = 21550 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C434 
	tier = county 
	liege = SILE 
	holder = { character = { type = 10 id = 21537 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C435 
	tier = county 
	liege = SILE 
	holder = { character = { type = 10 id = 21537 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C436 
	tier = county 
	liege = DBOH 
	holder = { character = { type = 10 id = 12855 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C437 
	tier = county 
	liege = DBOH 
	holder = { character = { type = 10 id = 12855 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C438 
	tier = county 
	liege = DBOH 
	holder = { character = { type = 10 id = 12855 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C439 
	tier = county 
	liege = DBOH 
	holder = { character = { type = 10 id = 12855 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C440 
	tier = county 
	liege = MORA 
	holder = { character = { type = 10 id = 12856 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C441 
	tier = county 
	liege = MORA 
	holder = { character = { type = 10 id = 12856 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C442 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C443 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C444 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C445 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19004 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C446 
	tier = county 
	liege = OSTE 
	holder = { character = { type = 10 id = 12533 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C447 
	tier = county 
	liege = BAVA 
	holder = { character = { type = 10 id = 30262 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C448 
	tier = county 
	liege = BAVA 
	holder = { character = { type = 10 id = 30260 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C449 
	tier = county 
	liege = OSTE 
	holder = { character = { type = 10 id = 12533 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C450 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19005 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C451 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19006 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C452 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C453 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19008 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C454 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C455 
	tier = county 
	liege = KARN 
	holder = { character = { type = 10 id = 30263 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C456 
	tier = county 
	liege = KARN 
	holder = { character = { type = 10 id = 30263 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C457 
	tier = county 
	liege = KARN 
	holder = { character = { type = 10 id = 12932 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C458 
	tier = county 
	liege = VENI 
	holder = { character = { type = 10 id = 13600 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C459 
	tier = county 
	liege = KARN 
	holder = { character = { type = 10 id = 12932 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C460 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19010 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C461 
	tier = county 
	liege = CROA 
	holder = { character = { type = 10 id = 20000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C462 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19011 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C463 
	tier = county 
	liege = CROA 
	holder = { character = { type = 10 id = 20001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C464 
	tier = county 
	liege = CROA 
	holder = { character = { type = 10 id = 20002 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C465 
	tier = county 
	liege = VENI 
	holder = { character = { type = 10 id = 20496 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C466 
	tier = county 
	liege = CROA 
	holder = { character = { type = 10 id = 20003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C467 
	tier = county 
	liege = ZARB 
	holder = { character = { type = 10 id = 20495 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C468 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 18003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C469 
	tier = county 
	liege = SERB 
	holder = { character = { type = 10 id = 18507 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C470 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13600 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C471 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 15006 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C472 
	tier = county 
	liege = BUTR 
	holder = { character = { type = 10 id = 15517 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C473 
	tier = county 
	liege = BUTR 
	holder = { character = { type = 10 id = 15517 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C474 
	tier = county 
	liege = VENI 
	holder = { character = { type = 10 id = 20502 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80033 } character = { type = 10 id = 15517 } } 
} 
title = { 
	tag = C475 
	tier = county 
	liege = HELL 
	holder = { character = { type = 10 id = 15014 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C476 
	tier = county 
	liege = ACHA 
	holder = { character = { type = 10 id = 30285 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C477 
	tier = county 
	liege = ACHA 
	holder = { character = { type = 10 id = 15010 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C478 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30286 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C479 
	tier = county 
	liege = KRET 
	holder = { character = { type = 10 id = 15022 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80014 } character = { type = 10 id = 13015 } } 
} 
title = { 
	tag = C480 
	tier = county 
	liege = KRET 
	holder = { character = { type = 10 id = 15022 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80013 } character = { type = 10 id = 13015 } } 
} 
title = { 
	tag = C481 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 15012 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80020 } character = { type = 10 id = 30285 } } 
	claim = { id = { type = 14712 id = 80032 } character = { type = 10 id = 15013 } } 
} 
title = { 
	tag = C482 
	tier = county 
	liege = HELL 
	holder = { character = { type = 10 id = 15013 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C483 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 15025 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80021 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = C484 
	tier = county 
	liege = AEGE 
	holder = { character = { type = 10 id = 15020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C485 
	tier = county 
	liege = THES 
	holder = { character = { type = 10 id = 15019 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C486 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C487 
	tier = county 
	liege = AEGE 
	holder = { character = { type = 10 id = 15021 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80027 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = C488 
	tier = county 
	liege = HELL 
	holder = { character = { type = 10 id = 15015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C489 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 15016 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80036 } character = { type = 10 id = 15517 } } 
	claim = { id = { type = 14712 id = 80038 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = C490 
	tier = county 
	liege = U014 
	holder = { character = { type = 10 id = 13523 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80034 } character = { type = 10 id = 15517 } } 
	claim = { id = { type = 14712 id = 80039 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = C491 
	tier = county 
	liege = U014 
	holder = { character = { type = 10 id = 13523 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80035 } character = { type = 10 id = 15517 } } 
	claim = { id = { type = 14712 id = 80040 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = C492 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 15004 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C493 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 15003 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80022 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = C494 
	tier = county 
	liege = ADRI 
	holder = { character = { type = 10 id = 15001 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80023 } character = { type = 10 id = 30286 } } 
	claim = { id = { type = 14712 id = 80037 } character = { type = 10 id = 17502 } } 
} 
title = { 
	tag = C495 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 5523 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80024 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = C496 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 5523 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80025 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = C497 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 5523 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80026 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = C498 
	tier = county 
	liege = BULG 
	holder = { character = { type = 10 id = 17001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C499 
	tier = county 
	liege = BULG 
	holder = { character = { type = 10 id = 17502 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C500 
	tier = county 
	liege = BULG 
	holder = { character = { type = 10 id = 17002 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C501 
	tier = county 
	liege = BULG 
	holder = { character = { type = 10 id = 17009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C502 
	tier = county 
	liege = SERB 
	holder = { character = { type = 10 id = 18507 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C503 
	tier = county 
	liege = NOSE 
	holder = { character = { type = 10 id = 18801 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C504 
	tier = county 
	liege = NOSE 
	holder = { character = { type = 10 id = 18801 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C505 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19012 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C506 
	tier = county 
	liege = BULG 
	holder = { character = { type = 10 id = 17003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C507 
	tier = county 
	liege = BULG 
	holder = { character = { type = 10 id = 17004 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C508 
	tier = county 
	liege = BULG 
	holder = { character = { type = 10 id = 17005 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C509 
	tier = county 
	liege = BULG 
	holder = { character = { type = 10 id = 17006 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C510 
	tier = county 
	liege = BULG 
	holder = { character = { type = 10 id = 17007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C511 
	tier = county 
	liege = BULG 
	holder = { character = { type = 10 id = 17007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C512 
	tier = county 
	liege = GALI 
	holder = { character = { type = 10 id = 22520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C513 
	tier = county 
	liege = VLAC 
	holder = { character = { type = 10 id = 28027 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C514 
	tier = county 
	liege = VLAC 
	holder = { character = { type = 10 id = 28028 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C515 
	tier = county 
	liege = VLAC 
	holder = { character = { type = 10 id = 28027 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C516 
	tier = county 
	liege = VLAC 
	holder = { character = { type = 10 id = 28029 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C517 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19013 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C518 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19014 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C519 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C520 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19016 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C521 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19017 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C522 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 30246 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C523 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19018 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C524 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19019 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C525 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C526 
	tier = county 
	liege = KRAK 
	holder = { character = { type = 10 id = 21524 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C527 
	tier = county 
	liege = POLA 
	holder = { character = { type = 10 id = 21524 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C528 
	tier = county 
	liege = KRAK 
	holder = { character = { type = 10 id = 21524 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C529 
	tier = county 
	liege = MAZO 
	holder = { character = { type = 10 id = 21525 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C530 
	tier = county 
	liege = MAZO 
	holder = { character = { type = 10 id = 21525 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C531 
	tier = county 
	liege = SAND 
	holder = { character = { type = 10 id = 21524 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C532 
	tier = county 
	liege = KRAK 
	holder = { character = { type = 10 id = 21524 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C533 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19021 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C534 
	tier = county 
	liege = GALI 
	holder = { character = { type = 10 id = 22510 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C535 
	tier = county 
	liege = GALI 
	holder = { character = { type = 10 id = 22520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C536 
	tier = county 
	liege = GALI 
	holder = { character = { type = 10 id = 22520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C537 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19022 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C538 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19023 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C539 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19024 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C540 
	tier = county 
	liege = HUNG 
	holder = { character = { type = 10 id = 19025 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C541 
	tier = county 
	liege = GALI 
	holder = { character = { type = 10 id = 22520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C542 
	tier = county 
	liege = GALI 
	holder = { character = { type = 10 id = 22520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C543 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28033 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C544 
	tier = county 
	liege = GALI 
	holder = { character = { type = 10 id = 22520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C545 
	tier = county 
	liege = GALI 
	holder = { character = { type = 10 id = 22520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C546 
	tier = county 
	liege = GALI 
	holder = { character = { type = 10 id = 22650 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C547 
	tier = county 
	liege = GALI 
	holder = { character = { type = 10 id = 22520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C548 
	tier = county 
	liege = TURO 
	holder = { character = { type = 10 id = 22540 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C549 
	tier = county 
	liege = GALI 
	holder = { character = { type = 10 id = 22520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C550 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 22790 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C551 
	tier = county 
	liege = SMOL 
	holder = { character = { type = 10 id = 22610 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C552 
	tier = county 
	liege = TURO 
	holder = { character = { type = 10 id = 22540 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C553 
	tier = county 
	liege = PRON 
	holder = { character = { type = 10 id = 22600 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C554 
	tier = county 
	liege = PRON 
	holder = { character = { type = 10 id = 22600 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C555 
	tier = county 
	liege = PERE 
	holder = { character = { type = 10 id = 22660 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C556 
	tier = county 
	liege = PERE 
	holder = { character = { type = 10 id = 22660 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C557 
	tier = county 
	liege = CRIM 
	holder = { character = { type = 10 id = 28055 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C558 
	tier = county 
	liege = CRIM 
	holder = { character = { type = 10 id = 28056 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C559 
	tier = county 
	liege = CRIM 
	holder = { character = { type = 10 id = 28057 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C560 
	tier = county 
	liege = CHER 
	holder = { character = { type = 10 id = 15039 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C561 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 13015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C562 
	tier = county 
	liege = CRIM 
	holder = { character = { type = 10 id = 15042 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C563 
	tier = county 
	liege = CRIM 
	holder = { character = { type = 10 id = 28058 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C564 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28030 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C565 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 28034 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C566 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28036 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C567 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 22630 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C568 
	tier = county 
	liege = SMOL 
	holder = { character = { type = 10 id = 22610 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C569 
	tier = county 
	liege = SMOL 
	holder = { character = { type = 10 id = 22610 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C570 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C571 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C572 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C573 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22686 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C574 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C575 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C576 
	tier = county 
	liege = PRON 
	holder = { character = { type = 10 id = 22031 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C577 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22760 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C578 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22740 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C579 
	tier = county 
	liege = MORD 
	holder = { character = { type = 10 id = 28070 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C580 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22740 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C581 
	tier = county 
	liege = RYAZ 
	holder = { character = { type = 10 id = 22770 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C582 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C583 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C584 
	tier = county 
	liege = RYAZ 
	holder = { character = { type = 10 id = 22770 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C585 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C586 
	tier = county 
	liege = VLAD 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C587 
	tier = county 
	liege = VOLG 
	holder = { character = { type = 10 id = 29004 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C588 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 29005 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C589 
	tier = county 
	liege = VOLG 
	holder = { character = { type = 10 id = 29006 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C590 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 29007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C591 
	tier = county 
	liege = VOLG 
	holder = { character = { type = 10 id = 29008 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C592 
	tier = county 
	liege = MORD 
	holder = { character = { type = 10 id = 28071 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C593 
	tier = county 
	liege = MORD 
	holder = { character = { type = 10 id = 28072 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C594 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28037 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C595 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28038 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C596 
	tier = county 
	liege = CRIM 
	holder = { character = { type = 10 id = 28059 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C597 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28061 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C598 
	tier = county 
	liege = CRIM 
	holder = { character = { type = 10 id = 15041 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C599 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28062 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C600 
	tier = county 
	liege = GEOR 
	holder = { character = { type = 10 id = 28069 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C601 
	tier = county 
	liege = GEOR 
	holder = { character = { type = 10 id = 28069 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C602 
	tier = county 
	liege = ALAN 
	holder = { character = { type = 10 id = 28067 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C603 
	tier = county 
	liege = ALAN 
	holder = { character = { type = 10 id = 28060 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C604 
	tier = county 
	liege = ALAN 
	holder = { character = { type = 10 id = 28063 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C605 
	tier = county 
	liege = ALAN 
	holder = { character = { type = 10 id = 28064 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C606 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28065 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C607 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28066 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C608 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28039 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C609 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28040 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C610 
	tier = county 
	liege = VOLG 
	holder = { character = { type = 10 id = 29009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C611 
	tier = county 
	liege = VOLG 
	holder = { character = { type = 10 id = 29000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C612 
	tier = county 
	liege = VOLG 
	holder = { character = { type = 10 id = 29010 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C613 
	tier = county 
	liege = VOLG 
	holder = { character = { type = 10 id = 29011 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C614 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28041 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C615 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28042 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C616 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28043 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C617 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28044 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C618 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28045 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C619 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28046 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C620 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28047 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C621 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28048 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C622 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28049 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C623 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28050 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C624 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28051 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C625 
	tier = county 
	liege = CUMA 
	holder = { character = { type = 10 id = 28052 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C626 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 28053 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C627 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 28054 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C628 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C629 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C630 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C631 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C632 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C633 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C634 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C635 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C636 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C637 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C638 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C639 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C640 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C641 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C642 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C643 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C644 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C645 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C646 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C647 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C648 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C649 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C650 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27101 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C651 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27102 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C652 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27103 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C653 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27104 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C654 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27105 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C655 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27002 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C656 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C657 
	tier = county 
	liege = AZER 
	holder = { character = { type = 10 id = 25016 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C658 
	tier = county 
	liege = AZER 
	holder = { character = { type = 10 id = 25017 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C659 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C660 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C661 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C662 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C663 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C664 
	tier = county 
	liege = KIRK 
	holder = { character = { type = 10 id = 25012 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C665 
	tier = county 
	liege = MKHW 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C666 
	tier = county 
	liege = AZER 
	holder = { character = { type = 10 id = 25018 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C667 
	tier = county 
	liege = AZER 
	holder = { character = { type = 10 id = 25015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C668 
	tier = county 
	liege = AZER 
	holder = { character = { type = 10 id = 25019 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C669 
	tier = county 
	liege = AZER 
	holder = { character = { type = 10 id = 25020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C670 
	tier = county 
	liege = AZER 
	holder = { character = { type = 10 id = 25021 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C671 
	tier = county 
	liege = AZER 
	holder = { character = { type = 10 id = 25022 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C672 
	tier = county 
	liege = AZER 
	holder = { character = { type = 10 id = 25023 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C673 
	tier = county 
	liege = AZER 
	holder = { character = { type = 10 id = 25024 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C674 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 28073 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C675 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 28074 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C676 
	tier = county 
	liege = GEOR 
	holder = { character = { type = 10 id = 16500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C677 
	tier = county 
	liege = GEOR 
	holder = { character = { type = 10 id = 16500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C678 
	tier = county 
	liege = TREB 
	holder = { character = { type = 10 id = 15519 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C679 
	tier = county 
	liege = GEOR 
	holder = { character = { type = 10 id = 16500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C680 
	tier = county 
	liege = GEOR 
	holder = { character = { type = 10 id = 16500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C681 
	tier = county 
	liege = ERZE 
	holder = { character = { type = 10 id = 25027 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C682 
	tier = county 
	liege = ERZE 
	holder = { character = { type = 10 id = 25028 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C683 
	tier = county 
	liege = MEDE 
	holder = { character = { type = 10 id = 26001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C684 
	tier = county 
	liege = MEDE 
	holder = { character = { type = 10 id = 26002 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C685 
	tier = county 
	liege = MMOS 
	holder = { character = { type = 10 id = 26014 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C686 
	tier = county 
	liege = KIRK 
	holder = { character = { type = 10 id = 25013 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C687 
	tier = county 
	liege = KIRK 
	holder = { character = { type = 10 id = 25011 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C688 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27004 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C689 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27005 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C690 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27006 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C691 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C692 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27008 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C693 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C694 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C695 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27010 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C696 
	tier = county 
	liege = KIRK 
	holder = { character = { type = 10 id = 25014 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C697 
	tier = county 
	liege = MMOS 
	holder = { character = { type = 10 id = 26013 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C698 
	tier = county 
	liege = MMOS 
	holder = { character = { type = 10 id = 26015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C699 
	tier = county 
	liege = MEDE 
	holder = { character = { type = 10 id = 26003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C700 
	tier = county 
	liege = MEDE 
	holder = { character = { type = 10 id = 26004 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C701 
	tier = county 
	liege = RUMS 
	holder = { character = { type = 10 id = 25010 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C702 
	tier = county 
	liege = ERZE 
	holder = { character = { type = 10 id = 25025 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C703 
	tier = county 
	liege = ERZE 
	holder = { character = { type = 10 id = 25029 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C704 
	tier = county 
	liege = CHAL 
	holder = { character = { type = 10 id = 15043 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C705 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 15519 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C706 
	tier = county 
	liege = RUMS 
	holder = { character = { type = 10 id = 25009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C707 
	tier = county 
	liege = MEDE 
	holder = { character = { type = 10 id = 26005 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C708 
	tier = county 
	liege = MEDE 
	holder = { character = { type = 10 id = 26006 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C709 
	tier = county 
	liege = MALE 
	holder = { character = { type = 10 id = 26009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C710 
	tier = county 
	liege = MMOS 
	holder = { character = { type = 10 id = 26016 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C711 
	tier = county 
	liege = MMOS 
	holder = { character = { type = 10 id = 26017 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C712 
	tier = county 
	liege = MMOS 
	holder = { character = { type = 10 id = 26018 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C713 
	tier = county 
	liege = MDAM 
	holder = { character = { type = 10 id = 26021 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C714 
	tier = county 
	liege = MDAM 
	holder = { character = { type = 10 id = 26022 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C715 
	tier = county 
	liege = ABBA 
	holder = { character = { type = 10 id = 27011 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C716 
	tier = county 
	liege = MMED 
	holder = { character = { type = 10 id = 26034 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C717 
	tier = county 
	liege = MMED 
	holder = { character = { type = 10 id = 26035 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C718 
	tier = county 
	liege = MMED 
	holder = { character = { type = 10 id = 26036 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C719 
	tier = county 
	liege = MMED 
	holder = { character = { type = 10 id = 26033 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C720 
	tier = county 
	liege = MMED 
	holder = { character = { type = 10 id = 26037 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C721 
	tier = county 
	liege = MMED 
	holder = { character = { type = 10 id = 26038 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C722 
	tier = county 
	liege = MDAM 
	holder = { character = { type = 10 id = 26023 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C723 
	tier = county 
	liege = MDAM 
	holder = { character = { type = 10 id = 26024 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C724 
	tier = county 
	liege = MJER 
	holder = { character = { type = 10 id = 30137 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C725 
	tier = county 
	liege = MJER 
	holder = { character = { type = 10 id = 30137 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C726 
	tier = county 
	liege = MDAM 
	holder = { character = { type = 10 id = 26025 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C727 
	tier = county 
	liege = MDAM 
	holder = { character = { type = 10 id = 26020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C728 
	tier = county 
	liege = MDAM 
	holder = { character = { type = 10 id = 26026 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C729 
	tier = county 
	liege = MMOS 
	holder = { character = { type = 10 id = 26019 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C730 
	tier = county 
	liege = MALE 
	holder = { character = { type = 10 id = 26010 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C731 
	tier = county 
	liege = MALE 
	holder = { character = { type = 10 id = 26011 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C732 
	tier = county 
	liege = MALE 
	holder = { character = { type = 10 id = 26012 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C733 
	tier = county 
	liege = MALE 
	holder = { character = { type = 10 id = 26007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C734 
	tier = county 
	liege = MEDE 
	holder = { character = { type = 10 id = 26008 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C735 
	tier = county 
	liege = CILI 
	holder = { character = { type = 10 id = 23023 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C736 
	tier = county 
	liege = CILI 
	holder = { character = { type = 10 id = 23024 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C737 
	tier = county 
	liege = RUMS 
	holder = { character = { type = 10 id = 25000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C738 
	tier = county 
	liege = TREB 
	holder = { character = { type = 10 id = 15519 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C739 
	tier = county 
	liege = TREB 
	holder = { character = { type = 10 id = 15519 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C740 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30286 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C741 
	tier = county 
	liege = NIKA 
	holder = { character = { type = 10 id = 15035 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80028 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = C742 
	tier = county 
	liege = NIKA 
	holder = { character = { type = 10 id = 5895 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80029 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = C743 
	tier = county 
	liege = NIKA 
	holder = { character = { type = 10 id = 5895 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80030 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = C744 
	tier = county 
	liege = SAMS 
	holder = { character = { type = 10 id = 15030 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80031 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = C745 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30286 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C746 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30286 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C747 
	tier = county 
	liege = IKON 
	holder = { character = { type = 10 id = 15036 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C748 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30286 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C749 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30286 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C750 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30286 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C751 
	tier = county 
	liege = KAPP 
	holder = { character = { type = 10 id = 25007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C752 
	tier = county 
	liege = RUMS 
	holder = { character = { type = 10 id = 25001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C753 
	tier = county 
	liege = KAPP 
	holder = { character = { type = 10 id = 25002 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C754 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30286 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C755 
	tier = county 
	liege = IKON 
	holder = { character = { type = 10 id = 25005 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C756 
	tier = county 
	liege = BASR 
	holder = { character = { type = 10 id = 23505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C757 
	tier = county 
	liege = BASR 
	holder = { character = { type = 10 id = 23505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C758 
	tier = county 
	liege = CILI 
	holder = { character = { type = 10 id = 23022 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C759 
	tier = county 
	liege = IKON 
	holder = { character = { type = 10 id = 25004 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C760 
	tier = county 
	liege = KAPP 
	holder = { character = { type = 10 id = 25003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C761 
	tier = county 
	liege = CILI 
	holder = { character = { type = 10 id = 23022 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C762 
	tier = county 
	liege = CILI 
	holder = { character = { type = 10 id = 23022 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C763 
	tier = county 
	liege = ANTI 
	holder = { character = { type = 10 id = 23651 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C764 
	tier = county 
	liege = ANTI 
	holder = { character = { type = 10 id = 23651 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C765 
	tier = county 
	liege = ASSA 
	holder = { character = { type = 10 id = 27012 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C766 
	tier = county 
	liege = MALE 
	holder = { character = { type = 10 id = 26007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C767 
	tier = county 
	liege = TRIP 
	holder = { character = { type = 10 id = 23651 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C768 
	tier = county 
	liege = MALE 
	holder = { character = { type = 10 id = 26007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C769 
	tier = county 
	liege = MJER 
	holder = { character = { type = 10 id = 30137 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C770 
	tier = county 
	liege = JERU 
	holder = { character = { type = 10 id = 23571 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C771 
	tier = county 
	liege = JERU 
	holder = { character = { type = 10 id = 23505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C772 
	tier = county 
	liege = JERU 
	holder = { character = { type = 10 id = 23505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C773 
	tier = county 
	liege = MJER 
	holder = { character = { type = 10 id = 30137 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C774 
	tier = county 
	liege = MJER 
	holder = { character = { type = 10 id = 30137 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C775 
	tier = county 
	liege = ASCA 
	holder = { character = { type = 10 id = 23505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C776 
	tier = county 
	liege = MJER 
	holder = { character = { type = 10 id = 30137 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C777 
	tier = county 
	liege = MJER 
	holder = { character = { type = 10 id = 30137 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C778 
	tier = county 
	liege = MJER 
	holder = { character = { type = 10 id = 30137 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C779 
	tier = county 
	liege = MJER 
	holder = { character = { type = 10 id = 30137 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C780 
	tier = county 
	liege = ASCA 
	holder = { character = { type = 10 id = 23505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C781 
	tier = county 
	liege = MELA 
	holder = { character = { type = 10 id = 26099 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C782 
	tier = county 
	liege = MJER 
	holder = { character = { type = 10 id = 30137 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C783 
	tier = county 
	liege = MDAM 
	holder = { character = { type = 10 id = 26028 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C784 
	tier = county 
	liege = MDAM 
	holder = { character = { type = 10 id = 26029 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C785 
	tier = county 
	liege = MELA 
	holder = { character = { type = 10 id = 26031 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C786 
	tier = county 
	liege = MELA 
	holder = { character = { type = 10 id = 26030 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C787 
	tier = county 
	liege = MELA 
	holder = { character = { type = 10 id = 26030 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C788 
	tier = county 
	liege = MELA 
	holder = { character = { type = 10 id = 26032 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C789 
	tier = county 
	liege = FATI 
	holder = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C790 
	tier = county 
	liege = FATI 
	holder = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C791 
	tier = county 
	liege = FATI 
	holder = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C792 
	tier = county 
	liege = NUBI 
	holder = { character = { type = 10 id = 20572 } startdate = { year = 1204 month = january day = 0 } } 
} 
title = { 
	tag = C793 
	tier = county 
	liege = NUBI 
	holder = { character = { type = 10 id = 20572 } startdate = { year = 1204 month = january day = 0 } } 
} 
title = { 
	tag = C794 
	tier = county 
	liege = FATI 
	holder = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C795 
	tier = county 
	liege = FATI 
	holder = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C796 
	tier = county 
	liege = FATI 
	holder = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C797 
	tier = county 
	liege = FATI 
	holder = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C798 
	tier = county 
	liege = FATI 
	holder = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C799 
	tier = county 
	liege = FATI 
	holder = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C800 
	tier = county 
	liege = FATI 
	holder = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C801 
	tier = county 
	liege = FATI 
	holder = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C802 
	tier = county 
	liege = FATI 
	holder = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C803 
	tier = county 
	liege = CYRE 
	holder = { character = { type = 10 id = 26040 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C804 
	tier = county 
	liege = CYRE 
	holder = { character = { type = 10 id = 26041 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C805 
	tier = county 
	liege = CYRE 
	holder = { character = { type = 10 id = 26042 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C806 
	tier = county 
	liege = CYRE 
	holder = { character = { type = 10 id = 26043 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C807 
	tier = county 
	liege = CYRE 
	holder = { character = { type = 10 id = 26044 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C808 
	tier = county 
	liege = CYRE 
	holder = { character = { type = 10 id = 26039 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C809 
	tier = county 
	liege = KAIR 
	holder = { character = { type = 10 id = 26046 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C810 
	tier = county 
	liege = KAIR 
	holder = { character = { type = 10 id = 26047 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C811 
	tier = county 
	liege = KAIR 
	holder = { character = { type = 10 id = 26048 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C812 
	tier = county 
	liege = NAPL 
	holder = { character = { type = 10 id = 30252 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C813 
	tier = county 
	liege = KAIR 
	holder = { character = { type = 10 id = 26049 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C814 
	tier = county 
	liege = KAIR 
	holder = { character = { type = 10 id = 26045 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C815 
	tier = county 
	liege = KAIR 
	holder = { character = { type = 10 id = 24027 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C816 
	tier = county 
	liege = KAIR 
	holder = { character = { type = 10 id = 24028 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C817 
	tier = county 
	liege = TUNI 
	holder = { character = { type = 10 id = 24026 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C818 
	tier = county 
	liege = DTUN 
	holder = { character = { type = 10 id = 24031 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C819 
	tier = county 
	liege = TUNI 
	holder = { character = { type = 10 id = 24029 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C820 
	tier = county 
	liege = DTUN 
	holder = { character = { type = 10 id = 24030 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C821 
	tier = county 
	liege = DTUN 
	holder = { character = { type = 10 id = 24032 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C822 
	tier = county 
	liege = DTUN 
	holder = { character = { type = 10 id = 24033 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C823 
	tier = county 
	liege = DTUN 
	holder = { character = { type = 10 id = 24034 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C824 
	tier = county 
	liege = CONS 
	holder = { character = { type = 10 id = 24036 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C825 
	tier = county 
	liege = CONS 
	holder = { character = { type = 10 id = 24035 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C826 
	tier = county 
	liege = BALE 
	holder = { character = { type = 10 id = 24049 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C827 
	tier = county 
	liege = BALE 
	holder = { character = { type = 10 id = 24048 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C828 
	tier = county 
	liege = CONS 
	holder = { character = { type = 10 id = 24037 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C829 
	tier = county 
	liege = CONS 
	holder = { character = { type = 10 id = 24038 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C830 
	tier = county 
	liege = CONS 
	holder = { character = { type = 10 id = 24039 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C831 
	tier = county 
	liege = CONS 
	holder = { character = { type = 10 id = 24040 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C832 
	tier = county 
	liege = ALGE 
	holder = { character = { type = 10 id = 24041 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C833 
	tier = county 
	liege = ALGE 
	holder = { character = { type = 10 id = 24042 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C834 
	tier = county 
	liege = ALGE 
	holder = { character = { type = 10 id = 24043 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C835 
	tier = county 
	liege = ALGE 
	holder = { character = { type = 10 id = 24044 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C836 
	tier = county 
	liege = ALGE 
	holder = { character = { type = 10 id = 24045 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C837 
	tier = county 
	liege = ALGE 
	holder = { character = { type = 10 id = 24046 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C838 
	tier = county 
	liege = ALGE 
	holder = { character = { type = 10 id = 24047 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C839 
	tier = county 
	liege = ALME 
	holder = { character = { type = 10 id = 24018 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C840 
	tier = county 
	liege = ALMO 
	holder = { character = { type = 10 id = 24000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C841 
	tier = county 
	liege = ALME 
	holder = { character = { type = 10 id = 24019 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C842 
	tier = county 
	liege = ALMO 
	holder = { character = { type = 10 id = 24000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C843 
	tier = county 
	liege = ALMO 
	holder = { character = { type = 10 id = 24000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C844 
	tier = county 
	liege = ALMO 
	holder = { character = { type = 10 id = 24000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C845 
	tier = county 
	liege = ALMO 
	holder = { character = { type = 10 id = 24000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C846 
	tier = county 
	liege = ALMO 
	holder = { character = { type = 10 id = 24000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C847 
	tier = county 
	liege = ALMO 
	holder = { character = { type = 10 id = 24000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C848 
	tier = county 
	liege = ALMO 
	holder = { character = { type = 10 id = 20842 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C898 
	tier = county 
	liege = PAPA 
	holder = { character = { type = 10 id = 20330 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C995 
	tier = county 
	liege = GERM 
	holder = { character = { type = 10 id = 30254 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = C997 
	tier = county 
	liege = ---- 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ADRI 
	tier = duchy 
	liege = U016 
	holder = { character = { type = 10 id = 15001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = AEGE 
	tier = duchy 
	liege = THES 
	holder = { character = { type = 10 id = 15020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ALAN 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28060 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ALGE 
	tier = duchy 
	liege = ALMO 
	holder = { character = { type = 10 id = 24041 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ALME 
	tier = duchy 
	liege = ALMO 
	holder = { character = { type = 10 id = 24015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ANJO 
	tier = duchy 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80002 } character = { type = 10 id = 5506 } } 
} 
title = { 
	tag = ANTI 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 23651 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ARTO 
	tier = duchy 
	liege = FRAN 
	holder = { character = { type = 10 id = 5506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ASCA 
	tier = duchy 
	liege = JERU 
	holder = { character = { type = 10 id = 23505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = AZER 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 25015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = BADA 
	tier = duchy 
	liege = ALMO 
	holder = { character = { type = 10 id = 24008 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = BAVA 
	tier = duchy 
	liege = GERM 
	holder = { character = { type = 10 id = 12950 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80017 } character = { type = 10 id = 12572 } } 
} 
title = { 
	tag = BERS 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 504 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = DBOH 
	tier = duchy 
	liege = GERM 
	holder = { character = { type = 10 id = 12855 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = BORD 
	tier = duchy 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = BOUG 
	tier = duchy 
	liege = FRAN 
	holder = { character = { type = 10 id = 12782 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = BRAB 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 6852 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = BRAN 
	tier = duchy 
	liege = GERM 
	holder = { character = { type = 10 id = 12037 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = BRIT 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 30133 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = BUTR 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 15517 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = CHAL 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 15043 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = CHAM 
	tier = duchy 
	liege = FRAN 
	holder = { character = { type = 10 id = 30128 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = CHER 
	tier = duchy 
	liege = TREB 
	holder = { character = { type = 10 id = 15039 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = CONN 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 14505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = CONS 
	tier = duchy 
	liege = ALMO 
	holder = { character = { type = 10 id = 24035 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = CORD 
	tier = duchy 
	liege = ALMO 
	holder = { character = { type = 10 id = 24001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = CRIM 
	tier = duchy 
	liege = CUMA 
	holder = { character = { type = 10 id = 28055 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = CYRE 
	tier = duchy 
	liege = FATI 
	holder = { character = { type = 10 id = 26039 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = DAUP 
	tier = duchy 
	liege = FRAN 
	holder = { character = { type = 10 id = 30039 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = DYRR 
	tier = duchy 
	liege = U016 
	holder = { character = { type = 10 id = 15003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = FLAN 
	tier = duchy 
	liege = FRAN 
	holder = { character = { type = 10 id = 5523 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = GALI 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 22520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = GALL 
	tier = duchy 
	liege = SCOT 
	holder = { character = { type = 10 id = 3570 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = GENO 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 13015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = GWYN 
	tier = duchy 
	liege = ENGL 
	holder = { character = { type = 10 id = 14714 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = HELL 
	tier = duchy 
	liege = U014 
	holder = { character = { type = 10 id = 15013 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ICEL 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 2011 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = IKON 
	tier = duchy 
	liege = RUMS 
	holder = { character = { type = 10 id = 25004 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = KAIR 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 26045 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = KAPP 
	tier = duchy 
	liege = RUMS 
	holder = { character = { type = 10 id = 25002 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = KRAK 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 21524 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = KRET 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 15022 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80012 } character = { type = 10 id = 13015 } } 
} 
title = { 
	tag = KARN 
	tier = duchy 
	liege = GERM 
	holder = { character = { type = 10 id = 30263 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = LANG 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 13018 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = LEIN 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 14553 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = LIVO 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28023 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MAZO 
	tier = duchy 
	liege = POLA 
	holder = { character = { type = 10 id = 21525 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MEAT 
	tier = duchy 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MEIS 
	tier = duchy 
	liege = GERM 
	holder = { character = { type = 10 id = 12038 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MILA 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 13019 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MORA 
	tier = duchy 
	liege = GERM 
	holder = { character = { type = 10 id = 12856 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = DNAV 
	tier = duchy 
	liege = NAVA 
	holder = { character = { type = 10 id = 6520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = NIKA 
	tier = duchy 
	liege = U016 
	holder = { character = { type = 10 id = 5895 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80043 } character = { type = 10 id = 30286 } } 
} 
title = { 
	tag = NORM 
	tier = duchy 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80004 } character = { type = 10 id = 5506 } } 
} 
title = { 
	tag = NOVG 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 22020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ORKN 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 20020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = PERE 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 22660 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = POIT 
	tier = duchy 
	liege = ENGL 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80003 } character = { type = 10 id = 5506 } } 
} 
title = { 
	tag = POLO 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 22550 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = POMM 
	tier = duchy 
	liege = POLA 
	holder = { character = { type = 10 id = 21712 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = PRON 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 22600 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = PRUS 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28015 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ROMA 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 13009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = RYAZ 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 22770 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = SAMO 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28022 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = SAND 
	tier = duchy 
	liege = POLA 
	holder = { character = { type = 10 id = 21524 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = SAVO 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 30102 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = SAXO 
	tier = duchy 
	liege = GERM 
	holder = { character = { type = 10 id = 12905 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80018 } character = { type = 10 id = 12572 } } 
} 
title = { 
	tag = SEVI 
	tier = duchy 
	liege = ALMO 
	holder = { character = { type = 10 id = 24020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = SILE 
	tier = duchy 
	liege = POLA 
	holder = { character = { type = 10 id = 21537 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = SKAN 
	tier = duchy 
	liege = DENM 
	holder = { character = { type = 10 id = 1520 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = SMOL 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 22610 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = SWAB 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 12506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = THES 
	tier = duchy 
	liege = U016 
	holder = { character = { type = 10 id = 15016 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = TOSC 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 13014 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = TOUL 
	tier = duchy 
	liege = FRAN 
	holder = { character = { type = 10 id = 5532 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = TRIP 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 23651 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = DTUN 
	tier = duchy 
	liege = ALMO 
	holder = { character = { type = 10 id = 24030 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = TURO 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 22540 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ULST 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 14000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = UPLO 
	tier = duchy 
	liege = GERM 
	holder = { character = { type = 10 id = 12580 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = VALE 
	tier = duchy 
	liege = ALMO 
	holder = { character = { type = 10 id = 24006 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = VENE 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 13024 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = VERO 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 12072 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = WEIS 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 20021 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = WIEL 
	tier = duchy 
	liege = POLA 
	holder = { character = { type = 10 id = 30530 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = VLAD 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = VOLG 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 29000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = YORK 
	tier = duchy 
	liege = ENGL 
	holder = { character = { type = 10 id = 30125 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ZARB 
	tier = duchy 
	liege = HUNG 
	holder = { character = { type = 10 id = 20495 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = OSTE 
	tier = duchy 
	liege = GERM 
	holder = { character = { type = 10 id = 12533 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = DFRA 
	tier = duchy 
	liege = FRAN 
	holder = { character = { type = 10 id = 5506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = SAMS 
	tier = duchy 
	liege = U016 
	holder = { character = { type = 10 id = 15030 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ARAG 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 10500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = BASR 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 23505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = BULG 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 17502 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = CAST 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 7510 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = CROA 
	tier = duchy 
	liege = HUNG 
	holder = { character = { type = 10 id = 20000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = CUMA 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 28030 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = DENM 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 1501 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ENGL 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = FRAN 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 5506 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = GEOR 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 16500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = GERM 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 12572 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80015 } character = { type = 10 id = 12506 } } 
	claim = { id = { type = 14712 id = 80016 } character = { type = 10 id = 30282 } } 
} 
title = { 
	tag = HUNG 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 30246 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = JERU 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 23505 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = LEON 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 30235 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = NAPL 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80042 } character = { type = 10 id = 30305 } } 
} 
title = { 
	tag = NAVA 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 6502 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = NORW 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 30222 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = POLA 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 21524 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80019 } character = { type = 10 id = 21525 } } 
} 
title = { 
	tag = PORT 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 9500 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = SCOT 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 3000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = SERB 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 18507 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = SWED 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 30226 } startdate = { year = 1204 month = september day = 0 } } 
	claim = { id = { type = 14712 id = 80011 } character = { type = 10 id = 504 } } 
} 
title = { 
	tag = TUNI 
	tier = duchy 
	liege = ALMO 
	holder = { character = { type = 10 id = 24026 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MJER 
	tier = duchy 
	liege = FATI 
	holder = { character = { type = 10 id = 30137 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MDAM 
	tier = duchy 
	liege = FATI 
	holder = { character = { type = 10 id = 26020 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MELA 
	tier = duchy 
	liege = FATI 
	holder = { character = { type = 10 id = 26030 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MMOS 
	tier = duchy 
	liege = FATI 
	holder = { character = { type = 10 id = 26013 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MEDE 
	tier = duchy 
	liege = FATI 
	holder = { character = { type = 10 id = 26001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MMED 
	tier = duchy 
	liege = FATI 
	holder = { character = { type = 10 id = 26036 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MKHW 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MALE 
	tier = duchy 
	liege = FATI 
	holder = { character = { type = 10 id = 26007 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = PAPA 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 23754 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = VENI 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 13600 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = CILI 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 23022 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ABBA 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 27000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = NUBI 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 20572 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = FATI 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ALMO 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 24000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ASSA 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 27012 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = BALE 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 24048 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = RUMS 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 25000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = NOSE 
	tier = kingdom 
	liege = ----- 
	holder = { character = { type = 10 id = 18801 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ACHA 
	tier = duchy 
	liege = U014 
	holder = { character = { type = 10 id = 30285 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = CURO 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28075 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ESTS 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28026 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = PRUT 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28016 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = TREB 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 15519 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = YATV 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28017 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ZEMI 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 20603 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ERZE 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 25025 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = ESAM 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28001 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = KAJA 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28010 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = KIRK 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 25011 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = KOLA 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28009 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = LITT 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28012 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = MORD 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28070 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = SATA 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28011 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = FINL 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28002 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = TAVA 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28003 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = WSAM 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28000 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = VLAC 
	tier = duchy 
	liege = ---- 
	holder = { character = { type = 10 id = 28027 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = U014 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 13523 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = U015 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 30286 } startdate = { year = 1204 month = september day = 0 } } 
} 
title = { 
	tag = U016 
	tier = kingdom 
	liege = ---- 
	holder = { character = { type = 10 id = 5523 } startdate = { year = 1204 month = september day = 0 } } 
} 
