country = {
	tag = C003
	form_of_goverment = feudal
	capital = 3
	tier = county
	ruler = { character = { type = 10 id = 14006 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 3 }
}
country = {
	tag = C004
	form_of_goverment = feudal
	capital = 4
	tier = county
	ruler = { character = { type = 10 id = 14007 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 4 }
}
country = {
	tag = C006
	form_of_goverment = feudal
	capital = 6
	tier = county
	ruler = { character = { type = 10 id = 14 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 6 }
}
country = {
	tag = C012
	form_of_goverment = feudal
	capital = 12
	tier = county
	ruler = { character = { type = 10 id = 14581 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 12 }
}
country = {
	tag = C014
	form_of_goverment = feudal
	capital = 14
	tier = county
	ruler = { character = { type = 10 id = 14600 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 14 }
}
country = {
	tag = C015
	form_of_goverment = feudal
	capital = 15
	tier = county
	ruler = { character = { type = 10 id = 4038 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 15 }
}
country = {
	tag = C017
	form_of_goverment = feudal
	capital = 17
	tier = county
	ruler = { character = { type = 10 id = 4600 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 17 }
}
country = {
	tag = C018
	form_of_goverment = feudal
	capital = 18
	tier = county
	ruler = { character = { type = 10 id = 14804 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 18 }
}
country = {
	tag = C019
	form_of_goverment = feudal
	capital = 19
	tier = county
	ruler = { character = { type = 10 id = 4003 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 19 }
}
country = {
	tag = C020
	form_of_goverment = feudal
	capital = 20
	tier = county
	ruler = { character = { type = 10 id = 4004 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 20 }
}
country = {
	tag = C021
	form_of_goverment = feudal
	capital = 21
	tier = county
	ruler = { character = { type = 10 id = 30109 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 21 }
}
country = {
	tag = C022
	form_of_goverment = feudal
	capital = 22
	tier = county
	ruler = { character = { type = 10 id = 4551 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 22 }
}
country = {
	tag = C023
	form_of_goverment = feudal
	capital = 23
	tier = county
	ruler = { character = { type = 10 id = 30141 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 23 }
}
country = {
	tag = C024
	form_of_goverment = feudal
	capital = 24
	tier = county
	ruler = { character = { type = 10 id = 4635 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 24 }
}
country = {
	tag = C025
	form_of_goverment = feudal
	capital = 25
	tier = county
	ruler = { character = { type = 10 id = 30138 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 25 }
}
country = {
	tag = C029
	form_of_goverment = feudal
	capital = 29
	tier = county
	ruler = { character = { type = 10 id = 4760 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 29 }
}
country = {
	tag = C033
	form_of_goverment = feudal
	capital = 33
	tier = county
	ruler = { character = { type = 10 id = 2013 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes ecclesical_balance = yes }
	controlledprovinces = { 33 }
}
country = {
	tag = C034
	form_of_goverment = republican
	capital = 34
	tier = county
	ruler = { character = { type = 10 id = 20018 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 34 }
}
country = {
	tag = C035
	form_of_goverment = feudal
	capital = 35
	tier = county
	ruler = { character = { type = 10 id = 20019 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 35 }
}
country = {
	tag = C038
	form_of_goverment = feudal
	capital = 38
	tier = county
	ruler = { character = { type = 10 id = 3002 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 38 }
}
country = {
	tag = C041
	form_of_goverment = feudal
	capital = 41
	tier = county
	ruler = { character = { type = 10 id = 3005 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 41 }
}
country = {
	tag = C042
	form_of_goverment = feudal
	capital = 42
	tier = county
	ruler = { character = { type = 10 id = 3006 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 42 }
}
country = {
	tag = C043
	form_of_goverment = feudal
	capital = 43
	tier = county
	ruler = { character = { type = 10 id = 3007 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 43 }
}
country = {
	tag = C046
	form_of_goverment = feudal
	capital = 46
	tier = county
	ruler = { character = { type = 10 id = 3010 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 46 }
}
country = {
	tag = C048
	form_of_goverment = feudal
	capital = 48
	tier = county
	ruler = { character = { type = 10 id = 3009 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 48 }
}
country = {
	tag = C049
	form_of_goverment = feudal
	capital = 49
	tier = county
	ruler = { character = { type = 10 id = 3540 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 49 }
}
country = {
	tag = C051
	form_of_goverment = feudal
	capital = 51
	tier = county
	ruler = { character = { type = 10 id = 3014 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 51 }
}
country = {
	tag = C052
	form_of_goverment = feudal
	capital = 52
	tier = county
	ruler = { character = { type = 10 id = 3520 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 52 }
}
country = {
	tag = C056
	form_of_goverment = ecclestical
	capital = 56
	tier = county
	ruler = { character = { type = 10 id = 30127 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 56 }
}
country = {
	tag = C059
	form_of_goverment = feudal
	capital = 59
	tier = county
	ruler = { character = { type = 10 id = 4680 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 59 100 }
}
country = {
	tag = C061
	form_of_goverment = ecclestical
	capital = 61
	tier = county
	ruler = { character = { type = 10 id = 30143 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 61 }
}
country = {
	tag = C062
	form_of_goverment = feudal
	capital = 62
	tier = county
	ruler = { character = { type = 10 id = 30015 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 62 }
}
country = {
	tag = C063
	form_of_goverment = feudal
	capital = 63
	tier = county
	ruler = { character = { type = 10 id = 4694 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 63 }
}
country = {
	tag = C065
	form_of_goverment = feudal
	capital = 65
	tier = county
	ruler = { character = { type = 10 id = 14724 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 65 }
}
country = {
	tag = C067
	form_of_goverment = feudal
	capital = 67
	tier = county
	ruler = { character = { type = 10 id = 4711 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 67 }
}
country = {
	tag = C069
	form_of_goverment = feudal
	capital = 69
	tier = county
	ruler = { character = { type = 10 id = 30142 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 69 }
}
country = {
	tag = C070
	form_of_goverment = feudal
	capital = 70
	tier = county
	ruler = { character = { type = 10 id = 4730 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 70 71 }
}
country = {
	tag = C072
	form_of_goverment = feudal
	capital = 72
	tier = county
	ruler = { character = { type = 10 id = 30139 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 72 }
}
country = {
	tag = C074
	form_of_goverment = feudal
	capital = 74
	tier = county
	ruler = { character = { type = 10 id = 30051 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 74 }
}
country = {
	tag = C075
	form_of_goverment = feudal
	capital = 75
	tier = county
	ruler = { character = { type = 10 id = 30097 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 75 }
}
country = {
	tag = C080
	form_of_goverment = feudal
	capital = 80
	tier = county
	ruler = { character = { type = 10 id = 6843 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 80 84 }
}
country = {
	tag = C083
	form_of_goverment = feudal
	capital = 83
	tier = county
	ruler = { character = { type = 10 id = 6831 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 83 }
}
country = {
	tag = C086
	form_of_goverment = feudal
	capital = 86
	tier = county
	ruler = { character = { type = 10 id = 12910 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 86 }
}
country = {
	tag = C087
	form_of_goverment = ecclestical
	capital = 87
	tier = county
	ruler = { character = { type = 10 id = 30258 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 87 }
}
country = {
	tag = C088
	form_of_goverment = ecclestical
	capital = 88
	tier = county
	ruler = { character = { type = 10 id = 30257 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 88 }
}
country = {
	tag = C089
	form_of_goverment = feudal
	capital = 89
	tier = county
	ruler = { character = { type = 10 id = 12922 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 89 }
}
country = {
	tag = C090
	form_of_goverment = feudal
	capital = 90
	tier = county
	ruler = { character = { type = 10 id = 6900 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 90 }
}
country = {
	tag = C091
	form_of_goverment = feudal
	capital = 91
	tier = county
	ruler = { character = { type = 10 id = 6802 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 91 }
}
country = {
	tag = C095
	form_of_goverment = feudal
	capital = 95
	tier = county
	ruler = { character = { type = 10 id = 4981 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 95 }
}
country = {
	tag = C096
	form_of_goverment = feudal
	capital = 96
	tier = county
	ruler = { character = { type = 10 id = 5659 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 96 }
}
country = {
	tag = C102
	form_of_goverment = feudal
	capital = 102
	tier = county
	ruler = { character = { type = 10 id = 5742 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 102 }
}
country = {
	tag = C103
	form_of_goverment = feudal
	capital = 103
	tier = county
	ruler = { character = { type = 10 id = 5781 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 103 }
}
country = {
	tag = C109
	form_of_goverment = feudal
	capital = 109
	tier = county
	ruler = { character = { type = 10 id = 30073 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 109 }
}
country = {
	tag = C111
	form_of_goverment = feudal
	capital = 111
	tier = county
	ruler = { character = { type = 10 id = 5884 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 111 }
}
country = {
	tag = C114
	form_of_goverment = ecclestical
	capital = 114
	tier = county
	ruler = { character = { type = 10 id = 30126 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 114 }
}
country = {
	tag = C115
	form_of_goverment = feudal
	capital = 115
	tier = county
	ruler = { character = { type = 10 id = 12692 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 115 }
}
country = {
	tag = C116
	form_of_goverment = ecclestical
	capital = 116
	tier = county
	ruler = { character = { type = 10 id = 30253 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 116 }
}
country = {
	tag = C119
	form_of_goverment = ecclestical
	capital = 119
	tier = county
	ruler = { character = { type = 10 id = 30136 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 119 }
}
country = {
	tag = C121
	form_of_goverment = feudal
	capital = 121
	tier = county
	ruler = { character = { type = 10 id = 12371 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 121 }
}
country = {
	tag = C122
	form_of_goverment = feudal
	capital = 122
	tier = county
	ruler = { character = { type = 10 id = 30259 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 122 }
}
country = {
	tag = C123
	form_of_goverment = ecclestical
	capital = 123
	tier = county
	ruler = { character = { type = 10 id = 30135 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 123 }
}
country = {
	tag = C124
	form_of_goverment = feudal
	capital = 124
	tier = county
	ruler = { character = { type = 10 id = 30265 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 124 }
}
country = {
	tag = C125
	form_of_goverment = feudal
	capital = 125
	tier = county
	ruler = { character = { type = 10 id = 12402 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 125 }
}
country = {
	tag = C128
	form_of_goverment = ecclestical
	capital = 128
	tier = county
	ruler = { character = { type = 10 id = 12001 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 128 }
}
country = {
	tag = C129
	form_of_goverment = ecclestical
	capital = 129
	tier = county
	ruler = { character = { type = 10 id = 12002 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 129 }
}
country = {
	tag = C132
	form_of_goverment = feudal
	capital = 132
	tier = county
	ruler = { character = { type = 10 id = 5726 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 132 131 137 }
}
country = {
	tag = C133
	form_of_goverment = feudal
	capital = 133
	tier = county
	ruler = { character = { type = 10 id = 12633 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 133 }
}
country = {
	tag = C135
	form_of_goverment = ecclestical
	capital = 135
	tier = county
	ruler = { character = { type = 10 id = 30134 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 135 }
}
country = {
	tag = C142
	form_of_goverment = feudal
	capital = 142
	tier = county
	ruler = { character = { type = 10 id = 5930 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 142 }
}
country = {
	tag = C144
	form_of_goverment = feudal
	capital = 144
	tier = county
	ruler = { character = { type = 10 id = 5660 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 144 145 }
}
country = {
	tag = C146
	form_of_goverment = feudal
	capital = 146
	tier = county
	ruler = { character = { type = 10 id = 30131 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 146 }
}
country = {
	tag = C147
	form_of_goverment = feudal
	capital = 147
	tier = county
	ruler = { character = { type = 10 id = 5622 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 147 }
}
country = {
	tag = C148
	form_of_goverment = feudal
	capital = 148
	tier = county
	ruler = { character = { type = 10 id = 5640 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 148 }
}
country = {
	tag = C150
	form_of_goverment = feudal
	capital = 150
	tier = county
	ruler = { character = { type = 10 id = 5630 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 150 }
}
country = {
	tag = C151
	form_of_goverment = feudal
	capital = 151
	tier = county
	ruler = { character = { type = 10 id = 5540 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 151 }
}
country = {
	tag = C153
	form_of_goverment = feudal
	capital = 153
	tier = county
	ruler = { character = { type = 10 id = 7560 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 153 }
}
country = {
	tag = C157
	form_of_goverment = feudal
	capital = 157
	tier = county
	ruler = { character = { type = 10 id = 8520 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 157 }
}
country = {
	tag = C162
	form_of_goverment = feudal
	capital = 162
	tier = county
	ruler = { character = { type = 10 id = 24009 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 162 }
}
country = {
	tag = C163
	form_of_goverment = feudal
	capital = 163
	tier = county
	ruler = { character = { type = 10 id = 24021 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 163 }
}
country = {
	tag = C164
	form_of_goverment = feudal
	capital = 164
	tier = county
	ruler = { character = { type = 10 id = 24022 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 164 }
}
country = {
	tag = C165
	form_of_goverment = feudal
	capital = 165
	tier = county
	ruler = { character = { type = 10 id = 24023 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 165 }
}
country = {
	tag = C166
	form_of_goverment = feudal
	capital = 166
	tier = county
	ruler = { character = { type = 10 id = 24024 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 166 }
}
country = {
	tag = C167
	form_of_goverment = feudal
	capital = 167
	tier = county
	ruler = { character = { type = 10 id = 24017 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 167 }
}
country = {
	tag = C169
	form_of_goverment = feudal
	capital = 169
	tier = county
	ruler = { character = { type = 10 id = 24012 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 169 }
}
country = {
	tag = C170
	form_of_goverment = feudal
	capital = 170
	tier = county
	ruler = { character = { type = 10 id = 24013 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 170 }
}
country = {
	tag = C172
	form_of_goverment = feudal
	capital = 172
	tier = county
	ruler = { character = { type = 10 id = 24007 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 172 }
}
country = {
	tag = C173
	form_of_goverment = feudal
	capital = 173
	tier = county
	ruler = { character = { type = 10 id = 10550 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 173 }
}
country = {
	tag = C174
	form_of_goverment = feudal
	capital = 174
	tier = county
	ruler = { character = { type = 10 id = 30245 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 174 }
}
country = {
	tag = C176
	form_of_goverment = feudal
	capital = 176
	tier = county
	ruler = { character = { type = 10 id = 7540 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 176 212 }
}
country = {
	tag = C178
	form_of_goverment = feudal
	capital = 178
	tier = county
	ruler = { character = { type = 10 id = 24002 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 178 }
}
country = {
	tag = C179
	form_of_goverment = feudal
	capital = 179
	tier = county
	ruler = { character = { type = 10 id = 24014 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 179 }
}
country = {
	tag = C180
	form_of_goverment = feudal
	capital = 180
	tier = county
	ruler = { character = { type = 10 id = 24016 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 180 }
}
country = {
	tag = C183
	form_of_goverment = feudal
	capital = 183
	tier = county
	ruler = { character = { type = 10 id = 24025 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 183 }
}
country = {
	tag = C184
	form_of_goverment = feudal
	capital = 184
	tier = county
	ruler = { character = { type = 10 id = 24010 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 184 }
}
country = {
	tag = C185
	form_of_goverment = feudal
	capital = 185
	tier = county
	ruler = { character = { type = 10 id = 24011 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 185 }
}
country = {
	tag = C188
	form_of_goverment = feudal
	capital = 188
	tier = county
	ruler = { character = { type = 10 id = 9530 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 188 }
}
country = {
	tag = C193
	form_of_goverment = feudal
	capital = 193
	tier = county
	ruler = { character = { type = 10 id = 24005 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 193 }
}
country = {
	tag = C194
	form_of_goverment = feudal
	capital = 194
	tier = county
	ruler = { character = { type = 10 id = 24004 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 194 }
}
country = {
	tag = C196
	form_of_goverment = feudal
	capital = 196
	tier = county
	ruler = { character = { type = 10 id = 24003 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 196 }
}
country = {
	tag = C199
	form_of_goverment = feudal
	capital = 199
	tier = county
	ruler = { character = { type = 10 id = 7546 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 199 154 }
}
country = {
	tag = C205
	form_of_goverment = feudal
	capital = 205
	tier = county
	ruler = { character = { type = 10 id = 10560 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 205 }
}
country = {
	tag = C206
	form_of_goverment = feudal
	capital = 206
	tier = county
	ruler = { character = { type = 10 id = 10570 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 206 }
}
country = {
	tag = C208
	form_of_goverment = feudal
	capital = 208
	tier = county
	ruler = { character = { type = 10 id = 5560 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 208 }
}
country = {
	tag = C209
	form_of_goverment = feudal
	capital = 209
	tier = county
	ruler = { character = { type = 10 id = 5673 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 209 }
}
country = {
	tag = C210
	form_of_goverment = feudal
	capital = 210
	tier = county
	ruler = { character = { type = 10 id = 5554 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 210 }
}
country = {
	tag = C213
	form_of_goverment = feudal
	capital = 213
	tier = county
	ruler = { character = { type = 10 id = 5572 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 213 }
}
country = {
	tag = C216
	form_of_goverment = feudal
	capital = 216
	tier = county
	ruler = { character = { type = 10 id = 5600 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 216 }
}
country = {
	tag = C217
	form_of_goverment = feudal
	capital = 217
	tier = county
	ruler = { character = { type = 10 id = 30124 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 217 }
}
country = {
	tag = C220
	form_of_goverment = feudal
	capital = 220
	tier = county
	ruler = { character = { type = 10 id = 5580 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 220 }
}
country = {
	tag = C224
	form_of_goverment = feudal
	capital = 224
	tier = county
	ruler = { character = { type = 10 id = 5680 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 224 }
}
country = {
	tag = C225
	form_of_goverment = feudal
	capital = 225
	tier = county
	ruler = { character = { type = 10 id = 5700 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 225 }
}
country = {
	tag = C229
	form_of_goverment = feudal
	capital = 229
	tier = county
	ruler = { character = { type = 10 id = 5980 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 229 }
}
country = {
	tag = C231
	form_of_goverment = feudal
	capital = 231
	tier = county
	ruler = { character = { type = 10 id = 13550 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 231 }
}
country = {
	tag = C238
	form_of_goverment = ecclestical
	capital = 238
	tier = county
	ruler = { character = { type = 10 id = 30267 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 238 }
}
country = {
	tag = C239
	form_of_goverment = feudal
	capital = 239
	tier = county
	ruler = { character = { type = 10 id = 12742 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 239 }
}
country = {
	tag = C240
	form_of_goverment = feudal
	capital = 240
	tier = county
	ruler = { character = { type = 10 id = 30079 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 240 226 }
}
country = {
	tag = C241
	form_of_goverment = feudal
	capital = 241
	tier = county
	ruler = { character = { type = 10 id = 30271 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 241 }
}
country = {
	tag = C242
	form_of_goverment = republican
	capital = 242
	tier = county
	ruler = { character = { type = 10 id = 30270 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 242 }
}
country = {
	tag = C244
	form_of_goverment = republican
	capital = 244
	tier = county
	ruler = { character = { type = 10 id = 30266 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 244 }
}
country = {
	tag = C245
	form_of_goverment = republican
	capital = 245
	tier = county
	ruler = { character = { type = 10 id = 30269 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 245 }
}
country = {
	tag = C246
	form_of_goverment = republican
	capital = 246
	tier = county
	ruler = { character = { type = 10 id = 30272 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 246 }
}
country = {
	tag = C247
	form_of_goverment = ecclestical
	capital = 247
	tier = county
	ruler = { character = { type = 10 id = 30264 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 247 }
}
country = {
	tag = C248
	form_of_goverment = ecclestical
	capital = 248
	tier = county
	ruler = { character = { type = 10 id = 30268 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 248 }
}
country = {
	tag = C253
	form_of_goverment = feudal
	capital = 253
	tier = county
	ruler = { character = { type = 10 id = 12420 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 253 }
}
country = {
	tag = C255
	form_of_goverment = feudal
	capital = 255
	tier = county
	ruler = { character = { type = 10 id = 12431 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 255 }
}
country = {
	tag = C256
	form_of_goverment = feudal
	capital = 256
	tier = county
	ruler = { character = { type = 10 id = 12903 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 256 }
}
country = {
	tag = C260
	form_of_goverment = feudal
	capital = 260
	tier = county
	ruler = { character = { type = 10 id = 1001 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 260 }
}
country = {
	tag = C261
	form_of_goverment = republican
	capital = 261
	tier = county
	ruler = { character = { type = 10 id = 30255 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 261 }
}
country = {
	tag = C262
	form_of_goverment = ecclestical
	capital = 262
	tier = county
	ruler = { character = { type = 10 id = 30256 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 262 }
}
country = {
	tag = C263
	form_of_goverment = feudal
	capital = 263
	tier = county
	ruler = { character = { type = 10 id = 12360 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 263 }
}
country = {
	tag = C264
	form_of_goverment = feudal
	capital = 264
	tier = county
	ruler = { character = { type = 10 id = 1003 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 264 }
}
country = {
	tag = C267
	form_of_goverment = feudal
	capital = 267
	tier = county
	ruler = { character = { type = 10 id = 1005 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 267 }
}
country = {
	tag = C268
	form_of_goverment = feudal
	capital = 268
	tier = county
	ruler = { character = { type = 10 id = 2001 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 268 }
}
country = {
	tag = C269
	form_of_goverment = feudal
	capital = 269
	tier = county
	ruler = { character = { type = 10 id = 30221 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 269 }
}
country = {
	tag = C270
	form_of_goverment = feudal
	capital = 270
	tier = county
	ruler = { character = { type = 10 id = 2003 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 270 }
}
country = {
	tag = C271
	form_of_goverment = feudal
	capital = 271
	tier = county
	ruler = { character = { type = 10 id = 2004 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 271 }
}
country = {
	tag = C272
	form_of_goverment = feudal
	capital = 272
	tier = county
	ruler = { character = { type = 10 id = 2005 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 272 }
}
country = {
	tag = C273
	form_of_goverment = feudal
	capital = 273
	tier = county
	ruler = { character = { type = 10 id = 2006 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 273 }
}
country = {
	tag = C275
	form_of_goverment = feudal
	capital = 275
	tier = county
	ruler = { character = { type = 10 id = 2007 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 275 }
}
country = {
	tag = C276
	form_of_goverment = feudal
	capital = 276
	tier = county
	ruler = { character = { type = 10 id = 2008 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 276 }
}
country = {
	tag = C277
	form_of_goverment = feudal
	capital = 277
	tier = county
	ruler = { character = { type = 10 id = 2009 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 277 }
}
country = {
	tag = C278
	form_of_goverment = feudal
	capital = 278
	tier = county
	ruler = { character = { type = 10 id = 2010 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 278 }
}
country = {
	tag = C280
	form_of_goverment = feudal
	capital = 280
	tier = county
	ruler = { character = { type = 10 id = 1 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 280 }
}
country = {
	tag = C281
	form_of_goverment = feudal
	capital = 281
	tier = county
	ruler = { character = { type = 10 id = 2 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 281 }
}
country = {
	tag = C282
	form_of_goverment = feudal
	capital = 282
	tier = county
	ruler = { character = { type = 10 id = 3 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes ecclesical_balance = yes }
	controlledprovinces = { 282 }
}
country = {
	tag = C283
	form_of_goverment = feudal
	capital = 283
	tier = county
	ruler = { character = { type = 10 id = 4 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 283 }
}
country = {
	tag = C284
	form_of_goverment = feudal
	capital = 284
	tier = county
	ruler = { character = { type = 10 id = 5 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 284 }
}
country = {
	tag = C285
	form_of_goverment = feudal
	capital = 285
	tier = county
	ruler = { character = { type = 10 id = 6 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 285 }
}
country = {
	tag = C286
	form_of_goverment = feudal
	capital = 286
	tier = county
	ruler = { character = { type = 10 id = 7 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 286 }
}
country = {
	tag = C298
	form_of_goverment = feudal
	capital = 298
	tier = county
	ruler = { character = { type = 10 id = 11 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 298 }
}
country = {
	tag = C299
	form_of_goverment = feudal
	capital = 299
	tier = county
	ruler = { character = { type = 10 id = 12 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 299 }
}
country = {
	tag = C300
	form_of_goverment = feudal
	capital = 300
	tier = county
	ruler = { character = { type = 10 id = 13 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 300 }
}
country = {
	tag = C301
	form_of_goverment = republican
	capital = 301
	tier = county
	ruler = { character = { type = 10 id = 15 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes ecclesical_balance = yes }
	controlledprovinces = { 301 }
}
country = {
	tag = C304
	form_of_goverment = feudal
	capital = 304
	tier = county
	ruler = { character = { type = 10 id = 21730 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 304 }
}
country = {
	tag = C306
	form_of_goverment = feudal
	capital = 306
	tier = county
	ruler = { character = { type = 10 id = 1008 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 306 }
}
country = {
	tag = C307
	form_of_goverment = feudal
	capital = 307
	tier = county
	ruler = { character = { type = 10 id = 1009 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 307 }
}
country = {
	tag = C314
	form_of_goverment = feudal
	capital = 314
	tier = county
	ruler = { character = { type = 10 id = 12390 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 314 313 }
}
country = {
	tag = C315
	form_of_goverment = feudal
	capital = 315
	tier = county
	ruler = { character = { type = 10 id = 12964 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 315 }
}
country = {
	tag = C316
	form_of_goverment = feudal
	capital = 316
	tier = county
	ruler = { character = { type = 10 id = 12380 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 316 }
}
country = {
	tag = C317
	form_of_goverment = ecclestical
	capital = 317
	tier = county
	ruler = { character = { type = 10 id = 30261 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 317 }
}
country = {
	tag = C320
	form_of_goverment = republican
	capital = 320
	tier = county
	ruler = { character = { type = 10 id = 13008 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 320 }
}
country = {
	tag = C322
	form_of_goverment = republican
	capital = 322
	tier = county
	ruler = { character = { type = 10 id = 13012 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 322 }
}
country = {
	tag = C325
	form_of_goverment = feudal
	capital = 325
	tier = county
	ruler = { character = { type = 10 id = 30248 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 325 }
}
country = {
	tag = C326
	form_of_goverment = feudal
	capital = 326
	tier = county
	ruler = { character = { type = 10 id = 30247 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 326 }
}
country = {
	tag = C327
	form_of_goverment = republican
	capital = 327
	tier = county
	ruler = { character = { type = 10 id = 13013 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 327 }
}
country = {
	tag = C329
	form_of_goverment = republican
	capital = 329
	tier = county
	ruler = { character = { type = 10 id = 30251 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 329 }
}
country = {
	tag = C330
	form_of_goverment = republican
	capital = 330
	tier = county
	ruler = { character = { type = 10 id = 13017 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 330 }
}
country = {
	tag = C332
	form_of_goverment = republican
	capital = 332
	tier = county
	ruler = { character = { type = 10 id = 13016 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 332 }
}
country = {
	tag = C344
	form_of_goverment = feudal
	capital = 344
	tier = county
	ruler = { character = { type = 10 id = 30305 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 344 }
}
country = {
	tag = C350
	form_of_goverment = republican
	capital = 350
	tier = county
	ruler = { character = { type = 10 id = 30250 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 350 }
}
country = {
	tag = C351
	form_of_goverment = ecclestical
	capital = 351
	tier = county
	ruler = { character = { type = 10 id = 13010 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 351 }
}
country = {
	tag = C352
	form_of_goverment = republican
	capital = 352
	tier = county
	ruler = { character = { type = 10 id = 13011 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 352 }
}
country = {
	tag = C355
	form_of_goverment = republican
	capital = 355
	tier = county
	ruler = { character = { type = 10 id = 13022 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 355 }
}
country = {
	tag = C357
	form_of_goverment = republican
	capital = 357
	tier = county
	ruler = { character = { type = 10 id = 13023 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 357 }
}
country = {
	tag = C358
	form_of_goverment = ecclestical
	capital = 358
	tier = county
	ruler = { character = { type = 10 id = 30249 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 358 }
}
country = {
	tag = C366
	form_of_goverment = feudal
	capital = 366
	tier = county
	ruler = { character = { type = 10 id = 21713 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 366 }
}
country = {
	tag = C368
	form_of_goverment = feudal
	capital = 368
	tier = county
	ruler = { character = { type = 10 id = 21750 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 368 }
}
country = {
	tag = C376
	form_of_goverment = feudal
	capital = 376
	tier = county
	ruler = { character = { type = 10 id = 28021 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 376 }
}
country = {
	tag = C378
	form_of_goverment = feudal
	capital = 378
	tier = county
	ruler = { character = { type = 10 id = 28024 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 378 }
}
country = {
	tag = C379
	form_of_goverment = feudal
	capital = 379
	tier = county
	ruler = { character = { type = 10 id = 28025 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 379 }
}
country = {
	tag = C385
	form_of_goverment = feudal
	capital = 385
	tier = county
	ruler = { character = { type = 10 id = 28008 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 385 }
}
country = {
	tag = C388
	form_of_goverment = feudal
	capital = 388
	tier = county
	ruler = { character = { type = 10 id = 28004 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 388 }
}
country = {
	tag = C390
	form_of_goverment = feudal
	capital = 390
	tier = county
	ruler = { character = { type = 10 id = 28005 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 390 }
}
country = {
	tag = C391
	form_of_goverment = feudal
	capital = 391
	tier = county
	ruler = { character = { type = 10 id = 28006 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 391 }
}
country = {
	tag = C392
	form_of_goverment = feudal
	capital = 392
	tier = county
	ruler = { character = { type = 10 id = 28035 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 392 }
}
country = {
	tag = C397
	form_of_goverment = feudal
	capital = 397
	tier = county
	ruler = { character = { type = 10 id = 22025 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 397 }
}
country = {
	tag = C398
	form_of_goverment = feudal
	capital = 398
	tier = county
	ruler = { character = { type = 10 id = 22026 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 398 }
}
country = {
	tag = C399
	form_of_goverment = feudal
	capital = 399
	tier = county
	ruler = { character = { type = 10 id = 22027 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 399 }
}
country = {
	tag = C400
	form_of_goverment = feudal
	capital = 400
	tier = county
	ruler = { character = { type = 10 id = 29001 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 400 }
}
country = {
	tag = C401
	form_of_goverment = feudal
	capital = 401
	tier = county
	ruler = { character = { type = 10 id = 29002 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 401 }
}
country = {
	tag = C409
	form_of_goverment = feudal
	capital = 409
	tier = county
	ruler = { character = { type = 10 id = 22030 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 409 }
}
country = {
	tag = C411
	form_of_goverment = feudal
	capital = 411
	tier = county
	ruler = { character = { type = 10 id = 28007 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 411 412 }
}
country = {
	tag = C413
	form_of_goverment = feudal
	capital = 413
	tier = county
	ruler = { character = { type = 10 id = 22029 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 413 }
}
country = {
	tag = C415
	form_of_goverment = feudal
	capital = 415
	tier = county
	ruler = { character = { type = 10 id = 22034 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 415 }
}
country = {
	tag = C416
	form_of_goverment = feudal
	capital = 416
	tier = county
	ruler = { character = { type = 10 id = 22560 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 416 }
}
country = {
	tag = C421
	form_of_goverment = feudal
	capital = 421
	tier = county
	ruler = { character = { type = 10 id = 28014 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 421 423 }
}
country = {
	tag = C424
	form_of_goverment = feudal
	capital = 424
	tier = county
	ruler = { character = { type = 10 id = 22810 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 424 }
}
country = {
	tag = C426
	form_of_goverment = feudal
	capital = 426
	tier = county
	ruler = { character = { type = 10 id = 22033 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 426 }
}
country = {
	tag = C427
	form_of_goverment = feudal
	capital = 427
	tier = county
	ruler = { character = { type = 10 id = 28019 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 427 }
}
country = {
	tag = C431
	form_of_goverment = feudal
	capital = 431
	tier = county
	ruler = { character = { type = 10 id = 30545 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 431 }
}
country = {
	tag = C433
	form_of_goverment = feudal
	capital = 433
	tier = county
	ruler = { character = { type = 10 id = 21550 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 433 }
}
country = {
	tag = C442
	form_of_goverment = feudal
	capital = 442
	tier = county
	ruler = { character = { type = 10 id = 19001 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 442 443 }
}
country = {
	tag = C444
	form_of_goverment = feudal
	capital = 444
	tier = county
	ruler = { character = { type = 10 id = 19003 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 444 }
}
country = {
	tag = C445
	form_of_goverment = feudal
	capital = 445
	tier = county
	ruler = { character = { type = 10 id = 19004 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 445 }
}
country = {
	tag = C447
	form_of_goverment = ecclestical
	capital = 447
	tier = county
	ruler = { character = { type = 10 id = 30262 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 447 }
}
country = {
	tag = C448
	form_of_goverment = ecclestical
	capital = 448
	tier = county
	ruler = { character = { type = 10 id = 30260 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 448 }
}
country = {
	tag = C450
	form_of_goverment = feudal
	capital = 450
	tier = county
	ruler = { character = { type = 10 id = 19005 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 450 }
}
country = {
	tag = C451
	form_of_goverment = feudal
	capital = 451
	tier = county
	ruler = { character = { type = 10 id = 19006 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 451 }
}
country = {
	tag = C452
	form_of_goverment = feudal
	capital = 452
	tier = county
	ruler = { character = { type = 10 id = 19007 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 452 }
}
country = {
	tag = C453
	form_of_goverment = feudal
	capital = 453
	tier = county
	ruler = { character = { type = 10 id = 19008 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 453 }
}
country = {
	tag = C454
	form_of_goverment = feudal
	capital = 454
	tier = county
	ruler = { character = { type = 10 id = 19009 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 454 }
}
country = {
	tag = C457
	form_of_goverment = feudal
	capital = 457
	tier = county
	ruler = { character = { type = 10 id = 12932 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 457 459 }
}
country = {
	tag = C460
	form_of_goverment = feudal
	capital = 460
	tier = county
	ruler = { character = { type = 10 id = 19010 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 460 }
}
country = {
	tag = C462
	form_of_goverment = feudal
	capital = 462
	tier = county
	ruler = { character = { type = 10 id = 19011 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 462 }
}
country = {
	tag = C463
	form_of_goverment = feudal
	capital = 463
	tier = county
	ruler = { character = { type = 10 id = 20001 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 463 }
}
country = {
	tag = C464
	form_of_goverment = feudal
	capital = 464
	tier = county
	ruler = { character = { type = 10 id = 20002 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 464 }
}
country = {
	tag = C465
	form_of_goverment = ecclestical
	capital = 465
	tier = county
	ruler = { character = { type = 10 id = 20496 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 465 }
}
country = {
	tag = C466
	form_of_goverment = feudal
	capital = 466
	tier = county
	ruler = { character = { type = 10 id = 20003 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 466 }
}
country = {
	tag = C468
	form_of_goverment = republican
	capital = 468
	tier = county
	ruler = { character = { type = 10 id = 18003 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 468 }
}
country = {
	tag = C471
	form_of_goverment = feudal
	capital = 471
	tier = county
	ruler = { character = { type = 10 id = 15006 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 471 }
}
country = {
	tag = C474
	form_of_goverment = feudal
	capital = 474
	tier = county
	ruler = { character = { type = 10 id = 20502 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 474 }
}
country = {
	tag = C475
	form_of_goverment = feudal
	capital = 475
	tier = county
	ruler = { character = { type = 10 id = 15014 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 475 }
}
country = {
	tag = C477
	form_of_goverment = feudal
	capital = 477
	tier = county
	ruler = { character = { type = 10 id = 15010 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 477 }
}
country = {
	tag = C481
	form_of_goverment = feudal
	capital = 481
	tier = county
	ruler = { character = { type = 10 id = 15012 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 481 }
}
country = {
	tag = C483
	form_of_goverment = feudal
	capital = 483
	tier = county
	ruler = { character = { type = 10 id = 15025 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 483 }
}
country = {
	tag = C485
	form_of_goverment = feudal
	capital = 485
	tier = county
	ruler = { character = { type = 10 id = 15019 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 485 }
}
country = {
	tag = C487
	form_of_goverment = feudal
	capital = 487
	tier = county
	ruler = { character = { type = 10 id = 15021 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 487 }
}
country = {
	tag = C488
	form_of_goverment = feudal
	capital = 488
	tier = county
	ruler = { character = { type = 10 id = 15015 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 488 }
}
country = {
	tag = C492
	form_of_goverment = feudal
	capital = 492
	tier = county
	ruler = { character = { type = 10 id = 15004 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 492 }
}
country = {
	tag = C498
	form_of_goverment = feudal
	capital = 498
	tier = county
	ruler = { character = { type = 10 id = 17001 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 498 }
}
country = {
	tag = C500
	form_of_goverment = feudal
	capital = 500
	tier = county
	ruler = { character = { type = 10 id = 17002 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 500 }
}
country = {
	tag = C501
	form_of_goverment = feudal
	capital = 501
	tier = county
	ruler = { character = { type = 10 id = 17009 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 501 }
}
country = {
	tag = C505
	form_of_goverment = feudal
	capital = 505
	tier = county
	ruler = { character = { type = 10 id = 19012 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 505 }
}
country = {
	tag = C506
	form_of_goverment = feudal
	capital = 506
	tier = county
	ruler = { character = { type = 10 id = 17003 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 506 }
}
country = {
	tag = C507
	form_of_goverment = feudal
	capital = 507
	tier = county
	ruler = { character = { type = 10 id = 17004 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 507 }
}
country = {
	tag = C508
	form_of_goverment = feudal
	capital = 508
	tier = county
	ruler = { character = { type = 10 id = 17005 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 508 }
}
country = {
	tag = C509
	form_of_goverment = feudal
	capital = 509
	tier = county
	ruler = { character = { type = 10 id = 17006 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 509 }
}
country = {
	tag = C510
	form_of_goverment = feudal
	capital = 510
	tier = county
	ruler = { character = { type = 10 id = 17007 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 510 511 }
}
country = {
	tag = C514
	form_of_goverment = feudal
	capital = 514
	tier = county
	ruler = { character = { type = 10 id = 28028 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 514 }
}
country = {
	tag = C516
	form_of_goverment = feudal
	capital = 516
	tier = county
	ruler = { character = { type = 10 id = 28029 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 516 }
}
country = {
	tag = C517
	form_of_goverment = feudal
	capital = 517
	tier = county
	ruler = { character = { type = 10 id = 19013 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 517 }
}
country = {
	tag = C518
	form_of_goverment = feudal
	capital = 518
	tier = county
	ruler = { character = { type = 10 id = 19014 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 518 }
}
country = {
	tag = C519
	form_of_goverment = feudal
	capital = 519
	tier = county
	ruler = { character = { type = 10 id = 19015 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 519 }
}
country = {
	tag = C520
	form_of_goverment = feudal
	capital = 520
	tier = county
	ruler = { character = { type = 10 id = 19016 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 520 }
}
country = {
	tag = C521
	form_of_goverment = feudal
	capital = 521
	tier = county
	ruler = { character = { type = 10 id = 19017 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 521 }
}
country = {
	tag = C523
	form_of_goverment = feudal
	capital = 523
	tier = county
	ruler = { character = { type = 10 id = 19018 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 523 }
}
country = {
	tag = C524
	form_of_goverment = feudal
	capital = 524
	tier = county
	ruler = { character = { type = 10 id = 19019 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 524 }
}
country = {
	tag = C525
	form_of_goverment = feudal
	capital = 525
	tier = county
	ruler = { character = { type = 10 id = 19020 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 525 }
}
country = {
	tag = C533
	form_of_goverment = feudal
	capital = 533
	tier = county
	ruler = { character = { type = 10 id = 19021 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 533 }
}
country = {
	tag = C534
	form_of_goverment = feudal
	capital = 534
	tier = county
	ruler = { character = { type = 10 id = 22510 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 534 }
}
country = {
	tag = C537
	form_of_goverment = feudal
	capital = 537
	tier = county
	ruler = { character = { type = 10 id = 19022 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 537 }
}
country = {
	tag = C538
	form_of_goverment = feudal
	capital = 538
	tier = county
	ruler = { character = { type = 10 id = 19023 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 538 }
}
country = {
	tag = C539
	form_of_goverment = feudal
	capital = 539
	tier = county
	ruler = { character = { type = 10 id = 19024 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 539 }
}
country = {
	tag = C540
	form_of_goverment = feudal
	capital = 540
	tier = county
	ruler = { character = { type = 10 id = 19025 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 540 }
}
country = {
	tag = C543
	form_of_goverment = feudal
	capital = 543
	tier = county
	ruler = { character = { type = 10 id = 28033 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 543 }
}
country = {
	tag = C546
	form_of_goverment = feudal
	capital = 546
	tier = county
	ruler = { character = { type = 10 id = 22650 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 546 }
}
country = {
	tag = C550
	form_of_goverment = feudal
	capital = 550
	tier = county
	ruler = { character = { type = 10 id = 22790 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 550 }
}
country = {
	tag = C558
	form_of_goverment = feudal
	capital = 558
	tier = county
	ruler = { character = { type = 10 id = 28056 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 558 }
}
country = {
	tag = C559
	form_of_goverment = feudal
	capital = 559
	tier = county
	ruler = { character = { type = 10 id = 28057 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 559 }
}
country = {
	tag = C562
	form_of_goverment = feudal
	capital = 562
	tier = county
	ruler = { character = { type = 10 id = 15042 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 562 }
}
country = {
	tag = C563
	form_of_goverment = feudal
	capital = 563
	tier = county
	ruler = { character = { type = 10 id = 28058 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 563 }
}
country = {
	tag = C565
	form_of_goverment = feudal
	capital = 565
	tier = county
	ruler = { character = { type = 10 id = 28034 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 565 }
}
country = {
	tag = C566
	form_of_goverment = feudal
	capital = 566
	tier = county
	ruler = { character = { type = 10 id = 28036 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 566 }
}
country = {
	tag = C567
	form_of_goverment = feudal
	capital = 567
	tier = county
	ruler = { character = { type = 10 id = 22630 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 567 }
}
country = {
	tag = C573
	form_of_goverment = feudal
	capital = 573
	tier = county
	ruler = { character = { type = 10 id = 22686 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 573 }
}
country = {
	tag = C576
	form_of_goverment = feudal
	capital = 576
	tier = county
	ruler = { character = { type = 10 id = 22031 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 576 }
}
country = {
	tag = C577
	form_of_goverment = feudal
	capital = 577
	tier = county
	ruler = { character = { type = 10 id = 22760 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 577 }
}
country = {
	tag = C580
	form_of_goverment = feudal
	capital = 580
	tier = county
	ruler = { character = { type = 10 id = 22740 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 580 578 }
}
country = {
	tag = C587
	form_of_goverment = feudal
	capital = 587
	tier = county
	ruler = { character = { type = 10 id = 29004 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 587 }
}
country = {
	tag = C588
	form_of_goverment = feudal
	capital = 588
	tier = county
	ruler = { character = { type = 10 id = 29005 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 588 }
}
country = {
	tag = C589
	form_of_goverment = feudal
	capital = 589
	tier = county
	ruler = { character = { type = 10 id = 29006 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 589 }
}
country = {
	tag = C590
	form_of_goverment = feudal
	capital = 590
	tier = county
	ruler = { character = { type = 10 id = 29007 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 590 }
}
country = {
	tag = C591
	form_of_goverment = feudal
	capital = 591
	tier = county
	ruler = { character = { type = 10 id = 29008 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 591 }
}
country = {
	tag = C592
	form_of_goverment = feudal
	capital = 592
	tier = county
	ruler = { character = { type = 10 id = 28071 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 592 }
}
country = {
	tag = C593
	form_of_goverment = feudal
	capital = 593
	tier = county
	ruler = { character = { type = 10 id = 28072 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 593 }
}
country = {
	tag = C594
	form_of_goverment = feudal
	capital = 594
	tier = county
	ruler = { character = { type = 10 id = 28037 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 594 }
}
country = {
	tag = C595
	form_of_goverment = feudal
	capital = 595
	tier = county
	ruler = { character = { type = 10 id = 28038 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 595 }
}
country = {
	tag = C596
	form_of_goverment = feudal
	capital = 596
	tier = county
	ruler = { character = { type = 10 id = 28059 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 596 }
}
country = {
	tag = C597
	form_of_goverment = feudal
	capital = 597
	tier = county
	ruler = { character = { type = 10 id = 28061 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 597 }
}
country = {
	tag = C598
	form_of_goverment = feudal
	capital = 598
	tier = county
	ruler = { character = { type = 10 id = 15041 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 598 }
}
country = {
	tag = C599
	form_of_goverment = feudal
	capital = 599
	tier = county
	ruler = { character = { type = 10 id = 28062 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 599 }
}
country = {
	tag = C600
	form_of_goverment = feudal
	capital = 600
	tier = county
	ruler = { character = { type = 10 id = 28069 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 600 601 }
}
country = {
	tag = C602
	form_of_goverment = feudal
	capital = 602
	tier = county
	ruler = { character = { type = 10 id = 28067 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 602 }
}
country = {
	tag = C604
	form_of_goverment = feudal
	capital = 604
	tier = county
	ruler = { character = { type = 10 id = 28063 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 604 }
}
country = {
	tag = C605
	form_of_goverment = feudal
	capital = 605
	tier = county
	ruler = { character = { type = 10 id = 28064 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 605 }
}
country = {
	tag = C606
	form_of_goverment = feudal
	capital = 606
	tier = county
	ruler = { character = { type = 10 id = 28065 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 606 }
}
country = {
	tag = C607
	form_of_goverment = feudal
	capital = 607
	tier = county
	ruler = { character = { type = 10 id = 28066 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 607 }
}
country = {
	tag = C608
	form_of_goverment = feudal
	capital = 608
	tier = county
	ruler = { character = { type = 10 id = 28039 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 608 }
}
country = {
	tag = C609
	form_of_goverment = feudal
	capital = 609
	tier = county
	ruler = { character = { type = 10 id = 28040 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 609 }
}
country = {
	tag = C610
	form_of_goverment = feudal
	capital = 610
	tier = county
	ruler = { character = { type = 10 id = 29009 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 610 }
}
country = {
	tag = C612
	form_of_goverment = feudal
	capital = 612
	tier = county
	ruler = { character = { type = 10 id = 29010 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 612 }
}
country = {
	tag = C613
	form_of_goverment = feudal
	capital = 613
	tier = county
	ruler = { character = { type = 10 id = 29011 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 613 }
}
country = {
	tag = C614
	form_of_goverment = feudal
	capital = 614
	tier = county
	ruler = { character = { type = 10 id = 28041 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 614 }
}
country = {
	tag = C615
	form_of_goverment = feudal
	capital = 615
	tier = county
	ruler = { character = { type = 10 id = 28042 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 615 }
}
country = {
	tag = C616
	form_of_goverment = feudal
	capital = 616
	tier = county
	ruler = { character = { type = 10 id = 28043 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 616 }
}
country = {
	tag = C617
	form_of_goverment = feudal
	capital = 617
	tier = county
	ruler = { character = { type = 10 id = 28044 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 617 }
}
country = {
	tag = C618
	form_of_goverment = feudal
	capital = 618
	tier = county
	ruler = { character = { type = 10 id = 28045 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 618 }
}
country = {
	tag = C619
	form_of_goverment = feudal
	capital = 619
	tier = county
	ruler = { character = { type = 10 id = 28046 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 619 }
}
country = {
	tag = C620
	form_of_goverment = feudal
	capital = 620
	tier = county
	ruler = { character = { type = 10 id = 28047 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 620 }
}
country = {
	tag = C621
	form_of_goverment = feudal
	capital = 621
	tier = county
	ruler = { character = { type = 10 id = 28048 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 621 }
}
country = {
	tag = C622
	form_of_goverment = feudal
	capital = 622
	tier = county
	ruler = { character = { type = 10 id = 28049 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 622 }
}
country = {
	tag = C623
	form_of_goverment = feudal
	capital = 623
	tier = county
	ruler = { character = { type = 10 id = 28050 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 623 }
}
country = {
	tag = C624
	form_of_goverment = feudal
	capital = 624
	tier = county
	ruler = { character = { type = 10 id = 28051 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 624 }
}
country = {
	tag = C625
	form_of_goverment = feudal
	capital = 625
	tier = county
	ruler = { character = { type = 10 id = 28052 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 625 }
}
country = {
	tag = C626
	form_of_goverment = feudal
	capital = 626
	tier = county
	ruler = { character = { type = 10 id = 28053 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 626 }
}
country = {
	tag = C627
	form_of_goverment = feudal
	capital = 627
	tier = county
	ruler = { character = { type = 10 id = 28054 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 627 }
}
country = {
	tag = C649
	form_of_goverment = feudal
	capital = 649
	tier = county
	ruler = { character = { type = 10 id = 27001 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 649 }
}
country = {
	tag = C650
	form_of_goverment = feudal
	capital = 650
	tier = county
	ruler = { character = { type = 10 id = 27101 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 650 }
}
country = {
	tag = C651
	form_of_goverment = feudal
	capital = 651
	tier = county
	ruler = { character = { type = 10 id = 27102 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 651 }
}
country = {
	tag = C652
	form_of_goverment = feudal
	capital = 652
	tier = county
	ruler = { character = { type = 10 id = 27103 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 652 }
}
country = {
	tag = C653
	form_of_goverment = feudal
	capital = 653
	tier = county
	ruler = { character = { type = 10 id = 27104 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 653 }
}
country = {
	tag = C654
	form_of_goverment = feudal
	capital = 654
	tier = county
	ruler = { character = { type = 10 id = 27105 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 654 }
}
country = {
	tag = C655
	form_of_goverment = feudal
	capital = 655
	tier = county
	ruler = { character = { type = 10 id = 27002 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 655 }
}
country = {
	tag = C656
	form_of_goverment = feudal
	capital = 656
	tier = county
	ruler = { character = { type = 10 id = 27003 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 656 }
}
country = {
	tag = C657
	form_of_goverment = feudal
	capital = 657
	tier = county
	ruler = { character = { type = 10 id = 25016 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 657 }
}
country = {
	tag = C658
	form_of_goverment = feudal
	capital = 658
	tier = county
	ruler = { character = { type = 10 id = 25017 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 658 }
}
country = {
	tag = C664
	form_of_goverment = feudal
	capital = 664
	tier = county
	ruler = { character = { type = 10 id = 25012 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 664 }
}
country = {
	tag = C666
	form_of_goverment = feudal
	capital = 666
	tier = county
	ruler = { character = { type = 10 id = 25018 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 666 }
}
country = {
	tag = C668
	form_of_goverment = feudal
	capital = 668
	tier = county
	ruler = { character = { type = 10 id = 25019 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 668 }
}
country = {
	tag = C669
	form_of_goverment = feudal
	capital = 669
	tier = county
	ruler = { character = { type = 10 id = 25020 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 669 }
}
country = {
	tag = C670
	form_of_goverment = feudal
	capital = 670
	tier = county
	ruler = { character = { type = 10 id = 25021 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 670 }
}
country = {
	tag = C671
	form_of_goverment = feudal
	capital = 671
	tier = county
	ruler = { character = { type = 10 id = 25022 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 671 }
}
country = {
	tag = C672
	form_of_goverment = feudal
	capital = 672
	tier = county
	ruler = { character = { type = 10 id = 25023 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 672 }
}
country = {
	tag = C673
	form_of_goverment = feudal
	capital = 673
	tier = county
	ruler = { character = { type = 10 id = 25024 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 673 }
}
country = {
	tag = C674
	form_of_goverment = feudal
	capital = 674
	tier = county
	ruler = { character = { type = 10 id = 28073 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 674 }
}
country = {
	tag = C675
	form_of_goverment = feudal
	capital = 675
	tier = county
	ruler = { character = { type = 10 id = 28074 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 675 }
}
country = {
	tag = C681
	form_of_goverment = feudal
	capital = 681
	tier = county
	ruler = { character = { type = 10 id = 25027 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 681 }
}
country = {
	tag = C682
	form_of_goverment = feudal
	capital = 682
	tier = county
	ruler = { character = { type = 10 id = 25028 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 682 }
}
country = {
	tag = C684
	form_of_goverment = feudal
	capital = 684
	tier = county
	ruler = { character = { type = 10 id = 26002 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 684 }
}
country = {
	tag = C685
	form_of_goverment = feudal
	capital = 685
	tier = county
	ruler = { character = { type = 10 id = 26014 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 685 }
}
country = {
	tag = C686
	form_of_goverment = feudal
	capital = 686
	tier = county
	ruler = { character = { type = 10 id = 25013 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 686 }
}
country = {
	tag = C688
	form_of_goverment = feudal
	capital = 688
	tier = county
	ruler = { character = { type = 10 id = 27004 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 688 }
}
country = {
	tag = C689
	form_of_goverment = feudal
	capital = 689
	tier = county
	ruler = { character = { type = 10 id = 27005 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 689 }
}
country = {
	tag = C690
	form_of_goverment = feudal
	capital = 690
	tier = county
	ruler = { character = { type = 10 id = 27006 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 690 }
}
country = {
	tag = C691
	form_of_goverment = feudal
	capital = 691
	tier = county
	ruler = { character = { type = 10 id = 27007 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 691 }
}
country = {
	tag = C692
	form_of_goverment = feudal
	capital = 692
	tier = county
	ruler = { character = { type = 10 id = 27008 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 692 }
}
country = {
	tag = C694
	form_of_goverment = feudal
	capital = 694
	tier = county
	ruler = { character = { type = 10 id = 27009 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 694 }
}
country = {
	tag = C695
	form_of_goverment = feudal
	capital = 695
	tier = county
	ruler = { character = { type = 10 id = 27010 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 695 }
}
country = {
	tag = C696
	form_of_goverment = feudal
	capital = 696
	tier = county
	ruler = { character = { type = 10 id = 25014 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 696 }
}
country = {
	tag = C698
	form_of_goverment = feudal
	capital = 698
	tier = county
	ruler = { character = { type = 10 id = 26015 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 698 }
}
country = {
	tag = C699
	form_of_goverment = feudal
	capital = 699
	tier = county
	ruler = { character = { type = 10 id = 26003 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 699 }
}
country = {
	tag = C700
	form_of_goverment = feudal
	capital = 700
	tier = county
	ruler = { character = { type = 10 id = 26004 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 700 }
}
country = {
	tag = C701
	form_of_goverment = feudal
	capital = 701
	tier = county
	ruler = { character = { type = 10 id = 25010 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 701 }
}
country = {
	tag = C703
	form_of_goverment = feudal
	capital = 703
	tier = county
	ruler = { character = { type = 10 id = 25029 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 703 }
}
country = {
	tag = C706
	form_of_goverment = feudal
	capital = 706
	tier = county
	ruler = { character = { type = 10 id = 25009 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 706 }
}
country = {
	tag = C707
	form_of_goverment = feudal
	capital = 707
	tier = county
	ruler = { character = { type = 10 id = 26005 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 707 }
}
country = {
	tag = C708
	form_of_goverment = feudal
	capital = 708
	tier = county
	ruler = { character = { type = 10 id = 26006 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 708 }
}
country = {
	tag = C709
	form_of_goverment = feudal
	capital = 709
	tier = county
	ruler = { character = { type = 10 id = 26009 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 709 }
}
country = {
	tag = C710
	form_of_goverment = feudal
	capital = 710
	tier = county
	ruler = { character = { type = 10 id = 26016 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 710 }
}
country = {
	tag = C711
	form_of_goverment = feudal
	capital = 711
	tier = county
	ruler = { character = { type = 10 id = 26017 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 711 }
}
country = {
	tag = C712
	form_of_goverment = feudal
	capital = 712
	tier = county
	ruler = { character = { type = 10 id = 26018 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 712 }
}
country = {
	tag = C713
	form_of_goverment = feudal
	capital = 713
	tier = county
	ruler = { character = { type = 10 id = 26021 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 713 }
}
country = {
	tag = C714
	form_of_goverment = feudal
	capital = 714
	tier = county
	ruler = { character = { type = 10 id = 26022 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 714 }
}
country = {
	tag = C715
	form_of_goverment = feudal
	capital = 715
	tier = county
	ruler = { character = { type = 10 id = 27011 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 715 }
}
country = {
	tag = C716
	form_of_goverment = feudal
	capital = 716
	tier = county
	ruler = { character = { type = 10 id = 26034 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 716 }
}
country = {
	tag = C717
	form_of_goverment = feudal
	capital = 717
	tier = county
	ruler = { character = { type = 10 id = 26035 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 717 }
}
country = {
	tag = C719
	form_of_goverment = feudal
	capital = 719
	tier = county
	ruler = { character = { type = 10 id = 26033 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 719 }
}
country = {
	tag = C720
	form_of_goverment = feudal
	capital = 720
	tier = county
	ruler = { character = { type = 10 id = 26037 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 720 }
}
country = {
	tag = C721
	form_of_goverment = feudal
	capital = 721
	tier = county
	ruler = { character = { type = 10 id = 26038 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 721 }
}
country = {
	tag = C722
	form_of_goverment = feudal
	capital = 722
	tier = county
	ruler = { character = { type = 10 id = 26023 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 722 }
}
country = {
	tag = C723
	form_of_goverment = feudal
	capital = 723
	tier = county
	ruler = { character = { type = 10 id = 26024 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 723 }
}
country = {
	tag = C726
	form_of_goverment = feudal
	capital = 726
	tier = county
	ruler = { character = { type = 10 id = 26025 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 726 }
}
country = {
	tag = C728
	form_of_goverment = feudal
	capital = 728
	tier = county
	ruler = { character = { type = 10 id = 26026 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 728 }
}
country = {
	tag = C729
	form_of_goverment = feudal
	capital = 729
	tier = county
	ruler = { character = { type = 10 id = 26019 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 729 }
}
country = {
	tag = C730
	form_of_goverment = feudal
	capital = 730
	tier = county
	ruler = { character = { type = 10 id = 26010 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 730 }
}
country = {
	tag = C731
	form_of_goverment = feudal
	capital = 731
	tier = county
	ruler = { character = { type = 10 id = 26011 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 731 }
}
country = {
	tag = C732
	form_of_goverment = feudal
	capital = 732
	tier = county
	ruler = { character = { type = 10 id = 26012 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 732 }
}
country = {
	tag = C734
	form_of_goverment = feudal
	capital = 734
	tier = county
	ruler = { character = { type = 10 id = 26008 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 734 }
}
country = {
	tag = C735
	form_of_goverment = feudal
	capital = 735
	tier = county
	ruler = { character = { type = 10 id = 23023 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 735 }
}
country = {
	tag = C736
	form_of_goverment = feudal
	capital = 736
	tier = county
	ruler = { character = { type = 10 id = 23024 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 736 }
}
country = {
	tag = C741
	form_of_goverment = feudal
	capital = 741
	tier = county
	ruler = { character = { type = 10 id = 15035 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 741 }
}
country = {
	tag = C747
	form_of_goverment = feudal
	capital = 747
	tier = county
	ruler = { character = { type = 10 id = 15036 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 747 }
}
country = {
	tag = C751
	form_of_goverment = feudal
	capital = 751
	tier = county
	ruler = { character = { type = 10 id = 25007 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 751 }
}
country = {
	tag = C752
	form_of_goverment = feudal
	capital = 752
	tier = county
	ruler = { character = { type = 10 id = 25001 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 752 }
}
country = {
	tag = C755
	form_of_goverment = feudal
	capital = 755
	tier = county
	ruler = { character = { type = 10 id = 25005 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 755 }
}
country = {
	tag = C760
	form_of_goverment = feudal
	capital = 760
	tier = county
	ruler = { character = { type = 10 id = 25003 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 760 }
}
country = {
	tag = C770
	form_of_goverment = feudal
	capital = 770
	tier = county
	ruler = { character = { type = 10 id = 23571 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 770 }
}
country = {
	tag = C781
	form_of_goverment = feudal
	capital = 781
	tier = county
	ruler = { character = { type = 10 id = 26099 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 781 }
}
country = {
	tag = C783
	form_of_goverment = feudal
	capital = 783
	tier = county
	ruler = { character = { type = 10 id = 26028 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 783 }
}
country = {
	tag = C784
	form_of_goverment = feudal
	capital = 784
	tier = county
	ruler = { character = { type = 10 id = 26029 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 784 }
}
country = {
	tag = C785
	form_of_goverment = feudal
	capital = 785
	tier = county
	ruler = { character = { type = 10 id = 26031 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 785 }
}
country = {
	tag = C788
	form_of_goverment = feudal
	capital = 788
	tier = county
	ruler = { character = { type = 10 id = 26032 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 788 }
}
country = {
	tag = C803
	form_of_goverment = feudal
	capital = 803
	tier = county
	ruler = { character = { type = 10 id = 26040 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 803 }
}
country = {
	tag = C804
	form_of_goverment = feudal
	capital = 804
	tier = county
	ruler = { character = { type = 10 id = 26041 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 804 }
}
country = {
	tag = C805
	form_of_goverment = feudal
	capital = 805
	tier = county
	ruler = { character = { type = 10 id = 26042 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 805 }
}
country = {
	tag = C806
	form_of_goverment = feudal
	capital = 806
	tier = county
	ruler = { character = { type = 10 id = 26043 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 806 }
}
country = {
	tag = C807
	form_of_goverment = feudal
	capital = 807
	tier = county
	ruler = { character = { type = 10 id = 26044 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 807 }
}
country = {
	tag = C809
	form_of_goverment = feudal
	capital = 809
	tier = county
	ruler = { character = { type = 10 id = 26046 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 809 }
}
country = {
	tag = C810
	form_of_goverment = feudal
	capital = 810
	tier = county
	ruler = { character = { type = 10 id = 26047 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 810 }
}
country = {
	tag = C811
	form_of_goverment = feudal
	capital = 811
	tier = county
	ruler = { character = { type = 10 id = 26048 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 811 }
}
country = {
	tag = C812
	form_of_goverment = feudal
	capital = 812
	tier = county
	ruler = { character = { type = 10 id = 30252 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 812 }
}
country = {
	tag = C813
	form_of_goverment = feudal
	capital = 813
	tier = county
	ruler = { character = { type = 10 id = 26049 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 813 }
}
country = {
	tag = C815
	form_of_goverment = feudal
	capital = 815
	tier = county
	ruler = { character = { type = 10 id = 24027 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 815 }
}
country = {
	tag = C816
	form_of_goverment = feudal
	capital = 816
	tier = county
	ruler = { character = { type = 10 id = 24028 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 816 }
}
country = {
	tag = C818
	form_of_goverment = feudal
	capital = 818
	tier = county
	ruler = { character = { type = 10 id = 24031 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 818 }
}
country = {
	tag = C819
	form_of_goverment = feudal
	capital = 819
	tier = county
	ruler = { character = { type = 10 id = 24029 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 819 }
}
country = {
	tag = C821
	form_of_goverment = feudal
	capital = 821
	tier = county
	ruler = { character = { type = 10 id = 24032 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 821 }
}
country = {
	tag = C822
	form_of_goverment = feudal
	capital = 822
	tier = county
	ruler = { character = { type = 10 id = 24033 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 822 }
}
country = {
	tag = C823
	form_of_goverment = feudal
	capital = 823
	tier = county
	ruler = { character = { type = 10 id = 24034 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 823 }
}
country = {
	tag = C824
	form_of_goverment = feudal
	capital = 824
	tier = county
	ruler = { character = { type = 10 id = 24036 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 824 }
}
country = {
	tag = C826
	form_of_goverment = feudal
	capital = 826
	tier = county
	ruler = { character = { type = 10 id = 24049 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 826 }
}
country = {
	tag = C828
	form_of_goverment = feudal
	capital = 828
	tier = county
	ruler = { character = { type = 10 id = 24037 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 828 }
}
country = {
	tag = C829
	form_of_goverment = feudal
	capital = 829
	tier = county
	ruler = { character = { type = 10 id = 24038 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 829 }
}
country = {
	tag = C830
	form_of_goverment = feudal
	capital = 830
	tier = county
	ruler = { character = { type = 10 id = 24039 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 830 }
}
country = {
	tag = C831
	form_of_goverment = feudal
	capital = 831
	tier = county
	ruler = { character = { type = 10 id = 24040 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 831 }
}
country = {
	tag = C833
	form_of_goverment = feudal
	capital = 833
	tier = county
	ruler = { character = { type = 10 id = 24042 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 833 }
}
country = {
	tag = C834
	form_of_goverment = feudal
	capital = 834
	tier = county
	ruler = { character = { type = 10 id = 24043 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 834 }
}
country = {
	tag = C835
	form_of_goverment = feudal
	capital = 835
	tier = county
	ruler = { character = { type = 10 id = 24044 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 835 }
}
country = {
	tag = C836
	form_of_goverment = feudal
	capital = 836
	tier = county
	ruler = { character = { type = 10 id = 24045 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 836 }
}
country = {
	tag = C837
	form_of_goverment = feudal
	capital = 837
	tier = county
	ruler = { character = { type = 10 id = 24046 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 837 }
}
country = {
	tag = C838
	form_of_goverment = feudal
	capital = 838
	tier = county
	ruler = { character = { type = 10 id = 24047 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 838 }
}
country = {
	tag = C839
	form_of_goverment = feudal
	capital = 839
	tier = county
	ruler = { character = { type = 10 id = 24018 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 839 }
}
country = {
	tag = C841
	form_of_goverment = feudal
	capital = 841
	tier = county
	ruler = { character = { type = 10 id = 24019 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 841 }
}
country = {
	tag = C848
	form_of_goverment = feudal
	capital = 848
	tier = county
	ruler = { character = { type = 10 id = 20842 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 848 }
}
country = {
	tag = C898
	form_of_goverment = ecclestical
	capital = 898
	tier = county
	ruler = { character = { type = 10 id = 20330 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 898 }
}
country = {
	tag = C995
	form_of_goverment = ecclestical
	capital = 995
	tier = county
	ruler = { character = { type = 10 id = 30254 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 995 }
}
country = {
	tag = ADRI
	form_of_goverment = feudal
	capital = 494
	tier = duchy
	ruler = { character = { type = 10 id = 15001 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 494 }
}
country = {
	tag = AEGE
	form_of_goverment = feudal
	capital = 484
	tier = duchy
	ruler = { character = { type = 10 id = 15020 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 484 }
}
country = {
	tag = ALAN
	form_of_goverment = feudal
	capital = 603
	tier = duchy
	ruler = { character = { type = 10 id = 28060 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 603 }
}
country = {
	tag = ALGE
	form_of_goverment = feudal
	capital = 832
	tier = duchy
	ruler = { character = { type = 10 id = 24041 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 832 }
}
country = {
	tag = ALME
	form_of_goverment = feudal
	capital = 168
	tier = duchy
	ruler = { character = { type = 10 id = 24015 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 168 }
}
country = {
	tag = ANTI
	form_of_goverment = feudal
	capital = 764
	tier = duchy
	ruler = { character = { type = 10 id = 23651 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 764 763 767 }
}
country = {
	tag = AZER
	form_of_goverment = feudal
	capital = 667
	tier = duchy
	ruler = { character = { type = 10 id = 25015 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 667 }
}
country = {
	tag = BADA
	form_of_goverment = feudal
	capital = 195
	tier = duchy
	ruler = { character = { type = 10 id = 24008 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 195 }
}
country = {
	tag = BAVA
	form_of_goverment = feudal
	capital = 360
	tier = duchy
	ruler = { character = { type = 10 id = 12950 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 360 361 362 }
}
country = {
	tag = BERS
	form_of_goverment = feudal
	capital = 287
	tier = duchy
	ruler = { character = { type = 10 id = 504 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 287 288 295 }
}
country = {
	tag = DBOH
	form_of_goverment = feudal
	capital = 437
	tier = duchy
	ruler = { character = { type = 10 id = 12855 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 437 363 436 438 439 }
}
country = {
	tag = BOUG
	form_of_goverment = feudal
	capital = 136
	tier = duchy
	ruler = { character = { type = 10 id = 12782 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 136 227 }
}
country = {
	tag = BRAB
	form_of_goverment = feudal
	capital = 117
	tier = duchy
	ruler = { character = { type = 10 id = 6852 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 117 79 81 82 85 92 }
}
country = {
	tag = BRAN
	form_of_goverment = feudal
	capital = 365
	tier = duchy
	ruler = { character = { type = 10 id = 12037 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 365 }
}
country = {
	tag = BRIT
	form_of_goverment = feudal
	capital = 106
	tier = duchy
	ruler = { character = { type = 10 id = 30133 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 106 101 104 105 }
}
country = {
	tag = BUTR
	form_of_goverment = feudal
	capital = 472
	tier = duchy
	ruler = { character = { type = 10 id = 15517 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 472 473 }
}
country = {
	tag = CHAL
	form_of_goverment = feudal
	capital = 704
	tier = duchy
	ruler = { character = { type = 10 id = 15043 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 704 }
}
country = {
	tag = CHAM
	form_of_goverment = feudal
	capital = 130
	tier = duchy
	ruler = { character = { type = 10 id = 30128 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 130 }
}
country = {
	tag = CHER
	form_of_goverment = feudal
	capital = 560
	tier = duchy
	ruler = { character = { type = 10 id = 15039 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 560 }
}
country = {
	tag = CONN
	form_of_goverment = feudal
	capital = 9
	tier = duchy
	ruler = { character = { type = 10 id = 14505 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 9 7 8 13 }
}
country = {
	tag = CONS
	form_of_goverment = feudal
	capital = 825
	tier = duchy
	ruler = { character = { type = 10 id = 24035 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 825 }
}
country = {
	tag = CORD
	form_of_goverment = feudal
	capital = 181
	tier = duchy
	ruler = { character = { type = 10 id = 24001 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 181 }
}
country = {
	tag = CRIM
	form_of_goverment = feudal
	capital = 557
	tier = duchy
	ruler = { character = { type = 10 id = 28055 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 557 }
}
country = {
	tag = CYRE
	form_of_goverment = feudal
	capital = 808
	tier = duchy
	ruler = { character = { type = 10 id = 26039 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 808 }
}
country = {
	tag = DAUP
	form_of_goverment = feudal
	capital = 228
	tier = duchy
	ruler = { character = { type = 10 id = 30039 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 228 222 }
}
country = {
	tag = DYRR
	form_of_goverment = feudal
	capital = 493
	tier = duchy
	ruler = { character = { type = 10 id = 15003 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 493 }
}
country = {
	tag = GALI
	form_of_goverment = feudal
	capital = 536
	tier = duchy
	ruler = { character = { type = 10 id = 22520 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 536 535 425 541 545 544 547 549 542 512 }
}
country = {
	tag = GALL
	form_of_goverment = feudal
	capital = 50
	tier = duchy
	ruler = { character = { type = 10 id = 3570 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 50 }
}
country = {
	tag = GENO
	form_of_goverment = republican
	capital = 233
	tier = duchy
	ruler = { character = { type = 10 id = 13015 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 233 230 486 561 }
}
country = {
	tag = GWYN
	form_of_goverment = feudal
	capital = 64
	tier = duchy
	ruler = { character = { type = 10 id = 14714 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 64 60 }
}
country = {
	tag = HELL
	form_of_goverment = feudal
	capital = 482
	tier = duchy
	ruler = { character = { type = 10 id = 15013 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 482 }
}
country = {
	tag = ICEL
	form_of_goverment = republican
	capital = 1
	tier = duchy
	ruler = { character = { type = 10 id = 2011 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes ecclesical_balance = yes }
	controlledprovinces = { 1 2 }
}
country = {
	tag = IKON
	form_of_goverment = feudal
	capital = 759
	tier = duchy
	ruler = { character = { type = 10 id = 25004 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 759 }
}
country = {
	tag = KAIR
	form_of_goverment = feudal
	capital = 814
	tier = duchy
	ruler = { character = { type = 10 id = 26045 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 814 }
}
country = {
	tag = KAPP
	form_of_goverment = feudal
	capital = 753
	tier = duchy
	ruler = { character = { type = 10 id = 25002 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 753 }
}
country = {
	tag = KRET
	form_of_goverment = feudal
	capital = 480
	tier = duchy
	ruler = { character = { type = 10 id = 15022 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes regal_supremacy = yes }
	controlledprovinces = { 480 479 }
}
country = {
	tag = KARN
	form_of_goverment = feudal
	capital = 456
	tier = duchy
	ruler = { character = { type = 10 id = 30263 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 456 455 }
}
country = {
	tag = LANG
	form_of_goverment = republican
	capital = 323
	tier = duchy
	ruler = { character = { type = 10 id = 13018 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 323 324 331 }
}
country = {
	tag = LEIN
	form_of_goverment = feudal
	capital = 16
	tier = duchy
	ruler = { character = { type = 10 id = 14553 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 16 }
}
country = {
	tag = LIVO
	form_of_goverment = ecclestical
	capital = 377
	tier = duchy
	ruler = { character = { type = 10 id = 28023 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 377 375 }
}
country = {
	tag = MAZO
	form_of_goverment = feudal
	capital = 529
	tier = duchy
	ruler = { character = { type = 10 id = 21525 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 428 529 530 }
}
country = {
	tag = MEIS
	form_of_goverment = feudal
	capital = 312
	tier = duchy
	ruler = { character = { type = 10 id = 12038 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 312 364 }
}
country = {
	tag = MILA
	form_of_goverment = republican
	capital = 235
	tier = duchy
	ruler = { character = { type = 10 id = 13019 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 234 235 }
}
country = {
	tag = MORA
	form_of_goverment = feudal
	capital = 441
	tier = duchy
	ruler = { character = { type = 10 id = 12856 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 441 440 }
}
country = {
	tag = DNAV
	form_of_goverment = feudal
	capital = 201
	tier = duchy
	ruler = { character = { type = 10 id = 6520 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 201 }
}
country = {
	tag = NIKA
	form_of_goverment = feudal
	capital = 743
	tier = duchy
	ruler = { character = { type = 10 id = 5895 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 110 742 743 }
}
country = {
	tag = NOVG
	form_of_goverment = feudal
	capital = 410
	tier = duchy
	ruler = { character = { type = 10 id = 22020 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 410 393 394 395 396 403 405 406 414 }
}
country = {
	tag = ORKN
	form_of_goverment = feudal
	capital = 36
	tier = duchy
	ruler = { character = { type = 10 id = 20020 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 36 37 }
}
country = {
	tag = PERE
	form_of_goverment = feudal
	capital = 555
	tier = duchy
	ruler = { character = { type = 10 id = 22660 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 555 556 }
}
country = {
	tag = POLO
	form_of_goverment = feudal
	capital = 419
	tier = duchy
	ruler = { character = { type = 10 id = 22550 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 419 418 417 }
}
country = {
	tag = POMM
	form_of_goverment = feudal
	capital = 367
	tier = duchy
	ruler = { character = { type = 10 id = 21712 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 367 308 }
}
country = {
	tag = PRON
	form_of_goverment = feudal
	capital = 554
	tier = duchy
	ruler = { character = { type = 10 id = 22600 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 554 553 }
}
country = {
	tag = PRUS
	form_of_goverment = feudal
	capital = 370
	tier = duchy
	ruler = { character = { type = 10 id = 28015 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 370 }
}
country = {
	tag = ROMA
	form_of_goverment = republican
	capital = 321
	tier = duchy
	ruler = { character = { type = 10 id = 13009 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 321 353 }
}
country = {
	tag = RYAZ
	form_of_goverment = feudal
	capital = 581
	tier = duchy
	ruler = { character = { type = 10 id = 22770 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 581 584 }
}
country = {
	tag = SAMO
	form_of_goverment = feudal
	capital = 372
	tier = duchy
	ruler = { character = { type = 10 id = 28022 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 372 }
}
country = {
	tag = SAVO
	form_of_goverment = feudal
	capital = 237
	tier = duchy
	ruler = { character = { type = 10 id = 30102 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 236 237 }
}
country = {
	tag = SAXO
	form_of_goverment = feudal
	capital = 259
	tier = duchy
	ruler = { character = { type = 10 id = 12905 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 310 259 309 311 }
}
country = {
	tag = SEVI
	form_of_goverment = feudal
	capital = 182
	tier = duchy
	ruler = { character = { type = 10 id = 24020 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 182 }
}
country = {
	tag = SILE
	form_of_goverment = feudal
	capital = 434
	tier = duchy
	ruler = { character = { type = 10 id = 21537 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 434 435 }
}
country = {
	tag = SKAN
	form_of_goverment = ecclestical
	capital = 303
	tier = duchy
	ruler = { character = { type = 10 id = 1520 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 303 302 305 }
}
country = {
	tag = SMOL
	form_of_goverment = feudal
	capital = 568
	tier = duchy
	ruler = { character = { type = 10 id = 22610 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 568 551 569 }
}
country = {
	tag = SWAB
	form_of_goverment = feudal
	capital = 249
	tier = duchy
	ruler = { character = { type = 10 id = 12506 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 249 126 134 250 251 252 254 }
}
country = {
	tag = THES
	form_of_goverment = feudal
	capital = 489
	tier = duchy
	ruler = { character = { type = 10 id = 15016 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 489 }
}
country = {
	tag = TOSC
	form_of_goverment = republican
	capital = 328
	tier = duchy
	ruler = { character = { type = 10 id = 13014 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 328 }
}
country = {
	tag = TOUL
	form_of_goverment = feudal
	capital = 214
	tier = duchy
	ruler = { character = { type = 10 id = 5532 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 214 215 211 218 219 221 223 }
}
country = {
	tag = DTUN
	form_of_goverment = feudal
	capital = 820
	tier = duchy
	ruler = { character = { type = 10 id = 24030 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 820 }
}
country = {
	tag = TURO
	form_of_goverment = feudal
	capital = 548
	tier = duchy
	ruler = { character = { type = 10 id = 22540 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 552 548 }
}
country = {
	tag = ULST
	form_of_goverment = feudal
	capital = 5
	tier = duchy
	ruler = { character = { type = 10 id = 14000 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 5 }
}
country = {
	tag = UPLO
	form_of_goverment = feudal
	capital = 127
	tier = duchy
	ruler = { character = { type = 10 id = 12580 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 127 118 }
}
country = {
	tag = VALE
	form_of_goverment = feudal
	capital = 171
	tier = duchy
	ruler = { character = { type = 10 id = 24006 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 171 }
}
country = {
	tag = VENE
	form_of_goverment = republican
	capital = 354
	tier = duchy
	ruler = { character = { type = 10 id = 13024 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 354 }
}
country = {
	tag = VERO
	form_of_goverment = republican
	capital = 319
	tier = duchy
	ruler = { character = { type = 10 id = 12072 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 319 }
}
country = {
	tag = WEIS
	form_of_goverment = feudal
	capital = 54
	tier = duchy
	ruler = { character = { type = 10 id = 20021 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 54 }
}
country = {
	tag = WIEL
	form_of_goverment = feudal
	capital = 430
	tier = duchy
	ruler = { character = { type = 10 id = 30530 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 432 430 429 }
}
country = {
	tag = VLAD
	form_of_goverment = feudal
	capital = 582
	tier = duchy
	ruler = { character = { type = 10 id = 22670 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 582 572 404 407 408 571 583 574 575 570 402 586 585 }
}
country = {
	tag = VOLG
	form_of_goverment = feudal
	capital = 611
	tier = duchy
	ruler = { character = { type = 10 id = 29000 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 611 }
}
country = {
	tag = YORK
	form_of_goverment = ecclestical
	capital = 57
	tier = duchy
	ruler = { character = { type = 10 id = 30125 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 57 }
}
country = {
	tag = ZARB
	form_of_goverment = feudal
	capital = 467
	tier = duchy
	ruler = { character = { type = 10 id = 20495 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 467 }
}
country = {
	tag = OSTE
	form_of_goverment = feudal
	capital = 449
	tier = duchy
	ruler = { character = { type = 10 id = 12533 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 449 446 }
}
country = {
	tag = SAMS
	form_of_goverment = feudal
	capital = 744
	tier = duchy
	ruler = { character = { type = 10 id = 15030 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 744 }
}
country = {
	tag = ARAG
	form_of_goverment = feudal
	capital = 204
	tier = kingdom
	ruler = { character = { type = 10 id = 10500 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 204 207 175 202 203 }
}
country = {
	tag = BULG
	form_of_goverment = feudal
	capital = 499
	tier = kingdom
	ruler = { character = { type = 10 id = 17502 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes regal_supremacy = yes }
	controlledprovinces = { 499 }
}
country = {
	tag = CAST
	form_of_goverment = feudal
	capital = 197
	tier = kingdom
	ruler = { character = { type = 10 id = 7510 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 197 177 198 200 }
}
country = {
	tag = CROA
	form_of_goverment = feudal
	capital = 461
	tier = kingdom
	ruler = { character = { type = 10 id = 20000 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 461 }
}
country = {
	tag = CUMA
	form_of_goverment = feudal
	capital = 564
	tier = kingdom
	ruler = { character = { type = 10 id = 28030 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 564 }
}
country = {
	tag = DENM
	form_of_goverment = feudal
	capital = 266
	tier = kingdom
	ruler = { character = { type = 10 id = 1501 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 266 265 291 }
}
country = {
	tag = ENGL
	form_of_goverment = feudal
	capital = 73
	tier = kingdom
	ruler = { character = { type = 10 id = 4514 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 107 26 27 28 30 32 53 55 58 66 68 73 140 149 141 143 11 10 31 }
}
country = {
	tag = FRAN
	form_of_goverment = feudal
	capital = 112
	tier = kingdom
	ruler = { character = { type = 10 id = 5506 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 112 77 113 138 139 97 98 108 99 }
}
country = {
	tag = GEOR
	form_of_goverment = feudal
	capital = 676
	tier = kingdom
	ruler = { character = { type = 10 id = 16500 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes regal_supremacy = yes }
	controlledprovinces = { 676 677 679 680 }
}
country = {
	tag = GERM
	form_of_goverment = feudal
	capital = 257
	tier = kingdom
	ruler = { character = { type = 10 id = 12572 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 359 258 257 120 }
}
country = {
	tag = HUNG
	form_of_goverment = feudal
	capital = 522
	tier = kingdom
	ruler = { character = { type = 10 id = 30246 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 522 }
}
country = {
	tag = JERU
	form_of_goverment = feudal
	capital = 772
	tier = kingdom
	ruler = { character = { type = 10 id = 23505 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_consanguinity_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 771 772 780 775 756 757 }
}
country = {
	tag = LEON
	form_of_goverment = feudal
	capital = 190
	tier = kingdom
	ruler = { character = { type = 10 id = 30235 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 190 155 156 189 191 192 }
}
country = {
	tag = NAPL
	form_of_goverment = feudal
	capital = 339
	tier = kingdom
	ruler = { character = { type = 10 id = 30282 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 339 340 341 342 343 334 336 337 338 345 346 347 348 318 997 }
}
country = {
	tag = NAVA
	form_of_goverment = feudal
	capital = 152
	tier = kingdom
	ruler = { character = { type = 10 id = 6502 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 152 }
}
country = {
	tag = NORW
	form_of_goverment = feudal
	capital = 274
	tier = kingdom
	ruler = { character = { type = 10 id = 30222 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 274 296 }
}
country = {
	tag = POLA
	form_of_goverment = feudal
	capital = 527
	tier = kingdom
	ruler = { character = { type = 10 id = 21524 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 527 369 531 526 532 528 }
}
country = {
	tag = PORT
	form_of_goverment = feudal
	capital = 160
	tier = kingdom
	ruler = { character = { type = 10 id = 9500 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 160 159 158 161 186 187 }
}
country = {
	tag = SCOT
	form_of_goverment = feudal
	capital = 39
	tier = kingdom
	ruler = { character = { type = 10 id = 3000 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 39 40 44 45 47 }
}
country = {
	tag = SERB
	form_of_goverment = feudal
	capital = 502
	tier = kingdom
	ruler = { character = { type = 10 id = 18507 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes regal_supremacy = yes }
	controlledprovinces = { 502 469 }
}
country = {
	tag = SWED
	form_of_goverment = feudal
	capital = 289
	tier = kingdom
	ruler = { character = { type = 10 id = 30226 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 289 290 292 297 294 293 382 }
}
country = {
	tag = TUNI
	form_of_goverment = feudal
	capital = 817
	tier = kingdom
	ruler = { character = { type = 10 id = 24026 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 817 }
}
country = {
	tag = MJER
	form_of_goverment = feudal
	capital = 774
	tier = duchy
	ruler = { character = { type = 10 id = 30137 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 774 725 769 779 773 777 724 776 782 778 }
}
country = {
	tag = MDAM
	form_of_goverment = feudal
	capital = 727
	tier = duchy
	ruler = { character = { type = 10 id = 26020 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 727 }
}
country = {
	tag = MELA
	form_of_goverment = feudal
	capital = 787
	tier = duchy
	ruler = { character = { type = 10 id = 26030 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 787 786 }
}
country = {
	tag = MMOS
	form_of_goverment = feudal
	capital = 697
	tier = duchy
	ruler = { character = { type = 10 id = 26013 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 697 }
}
country = {
	tag = MEDE
	form_of_goverment = feudal
	capital = 683
	tier = duchy
	ruler = { character = { type = 10 id = 26001 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 683 }
}
country = {
	tag = MMED
	form_of_goverment = feudal
	capital = 718
	tier = duchy
	ruler = { character = { type = 10 id = 26036 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 718 }
}
country = {
	tag = MKHW
	form_of_goverment = feudal
	capital = 646
	tier = kingdom
	ruler = { character = { type = 10 id = 30000 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 646 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 647 648 659 660 661 662 663 665 }
}
country = {
	tag = MALE
	form_of_goverment = feudal
	capital = 733
	tier = duchy
	ruler = { character = { type = 10 id = 26007 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 733 766 768 }
}
country = {
	tag = PAPA
	form_of_goverment = ecclestical
	capital = 333
	tier = kingdom
	ruler = { character = { type = 10 id = 23754 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes royal_preorgatory_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 333 335 349 }
}
country = {
	tag = VENI
	form_of_goverment = republican
	capital = 356
	tier = kingdom
	ruler = { character = { type = 10 id = 13600 } startdate = { year = 1204 month = september day = 0 } }
	laws = { elective_law = yes popular_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 356 458 470 }
}
country = {
	tag = CILI
	form_of_goverment = feudal
	capital = 758
	tier = kingdom
	ruler = { character = { type = 10 id = 23022 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_primogeniture_law = yes feudal_contract_law = yes ecclesical_balance = yes }
	controlledprovinces = { 758 761 762 }
}
country = {
	tag = ABBA
	form_of_goverment = feudal
	capital = 693
	tier = kingdom
	ruler = { character = { type = 10 id = 27000 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes ecclesical_balance = yes }
	controlledprovinces = { 693 }
}
country = {
	tag = NUBI
	form_of_goverment = feudal
	capital = 793
	tier = kingdom 
	ruler = { character = { type = 10 id = 20572 } startdate = { year = 1204 month = january day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes church_supremacy = yes }
	church = 0.700
	controlledprovinces = { 793 792 }
}
country = {
	tag = FATI
	form_of_goverment = feudal
	capital = 797
	tier = kingdom
	ruler = { character = { type = 10 id = 26000 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes ecclesical_balance = yes }
	controlledprovinces = { 797 790 791 794 795 796 789 798 799 800 801 802 }
}
country = {
	tag = ALMO
	form_of_goverment = feudal
	capital = 843
	tier = kingdom
	ruler = { character = { type = 10 id = 24000 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 843 840 842 844 845 846 847 }
}
country = {
	tag = ASSA
	form_of_goverment = feudal
	capital = 765
	tier = kingdom
	ruler = { character = { type = 10 id = 27012 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 765 }
}
country = {
	tag = BALE
	form_of_goverment = feudal
	capital = 827
	tier = kingdom
	ruler = { character = { type = 10 id = 24048 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_consanguinity_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 827 }
}
country = {
	tag = RUMS
	form_of_goverment = feudal
	capital = 737
	tier = kingdom
	ruler = { character = { type = 10 id = 25000 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 737 }
}
country = {
	tag = NOSE
	form_of_goverment = feudal
	capital = 503
	tier = kingdom
	ruler = { character = { type = 10 id = 18801 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_gavelkind_law = yes traditional_custom_law = yes regal_supremacy = yes }
	controlledprovinces = { 503 504 }
}
country = {
	tag = ACHA
	form_of_goverment = feudal
	capital = 476
	tier = duchy
	ruler = { character = { type = 10 id = 30285 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 476 }
}
country = {
	tag = CURO
	form_of_goverment = feudal
	capital = 373
	tier = duchy
	ruler = { character = { type = 10 id = 28075 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 373 }
}
country = {
	tag = ESTS
	form_of_goverment = feudal
	capital = 380
	tier = kingdom
	ruler = { character = { type = 10 id = 28026 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 380 }
}
country = {
	tag = PRUT
	form_of_goverment = feudal
	capital = 371
	tier = duchy
	ruler = { character = { type = 10 id = 28016 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 371 }
}
country = {
	tag = TREB
	form_of_goverment = feudal
	capital = 739
	tier = kingdom
	ruler = { character = { type = 10 id = 15519 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 739 738 678 705 }
}
country = {
	tag = YATV
	form_of_goverment = feudal
	capital = 422
	tier = duchy
	ruler = { character = { type = 10 id = 28017 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 422 }
}
country = {
	tag = ZEMI
	form_of_goverment = feudal
	capital = 374
	tier = duchy
	ruler = { character = { type = 10 id = 20603 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 374 }
}
country = {
	tag = ERZE
	form_of_goverment = feudal
	capital = 702
	tier = duchy
	ruler = { character = { type = 10 id = 25025 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 702 }
}
country = {
	tag = ESAM
	form_of_goverment = feudal
	capital = 386
	tier = duchy
	ruler = { character = { type = 10 id = 28001 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 386 }
}
country = {
	tag = KAJA
	form_of_goverment = feudal
	capital = 389
	tier = duchy
	ruler = { character = { type = 10 id = 28010 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 389 }
}
country = {
	tag = KIRK
	form_of_goverment = feudal
	capital = 687
	tier = duchy
	ruler = { character = { type = 10 id = 25011 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 687 }
}
country = {
	tag = KOLA
	form_of_goverment = feudal
	capital = 387
	tier = duchy
	ruler = { character = { type = 10 id = 28009 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 387 }
}
country = {
	tag = LITT
	form_of_goverment = feudal
	capital = 420
	tier = duchy
	ruler = { character = { type = 10 id = 28012 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 420 }
}
country = {
	tag = MORD
	form_of_goverment = feudal
	capital = 579
	tier = duchy
	ruler = { character = { type = 10 id = 28070 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 579 }
}
country = {
	tag = SATA
	form_of_goverment = feudal
	capital = 384
	tier = duchy
	ruler = { character = { type = 10 id = 28011 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 384 }
}
country = {
	tag = FINL
	form_of_goverment = feudal
	capital = 381
	tier = duchy
	ruler = { character = { type = 10 id = 28002 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 381 }
}
country = {
	tag = TAVA
	form_of_goverment = feudal
	capital = 383
	tier = duchy
	ruler = { character = { type = 10 id = 28003 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 383 }
}
country = {
	tag = WSAM
	form_of_goverment = feudal
	capital = 279
	tier = duchy
	ruler = { character = { type = 10 id = 28000 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 279 }
}
country = {
	tag = VLAC
	form_of_goverment = feudal
	capital = 513
	tier = duchy
	ruler = { character = { type = 10 id = 28027 } startdate = { year = 1204 month = september day = 0 } }
	laws = { salic_consanguinity_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 515 513 }
}
country = {
	tag = U014
	form_of_goverment = feudal
	capital = 490
	tier = kingdom
	ruler = { character = { type = 10 id = 13523 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 232 490 491 }
}
country = {
	tag = U015
	form_of_goverment = feudal
	capital = 745
	tier = kingdom
	ruler = { character = { type = 10 id = 30286 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes royal_preorgatory_law = yes regal_supremacy = yes }
	controlledprovinces = { 750 745 746 749 740 748 478 754 }
}
country = {
	tag = U016
	form_of_goverment = feudal
	capital = 496
	tier = kingdom
	ruler = { character = { type = 10 id = 5523 } startdate = { year = 1204 month = september day = 0 } }
	laws = { semisalic_primogeniture_law = yes traditional_custom_law = yes ecclesical_balance = yes }
	controlledprovinces = { 78 76 93 94 495 496 497 }
}
