relations = {
	alliance = { 
		primary = { type = 10 id = 5523 } 
		secondary = { type = 10 id = 13523 } 
		startdate = { year = 1204 month = january day = 1 } 
	} 
	alliance = { #Bakt
		primary = { type = 10 id = 20572 } #NUBI
		secondary = { type = 10 id = 26000 } #FATI
		startdate = { year = 1186 month = december day = 27 }
	}
	truce = { 
		primary = { type = 10 id = 5506 } 
		secondary = { type = 10 id = 4514 } 
		startdate = { year = 1204 month = may day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 500 }
		secondary = { type = 10 id = 520 }
		startdate = { year = 1168 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 521 }
		secondary = { type = 10 id = 522 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1164 month = march day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 523 }
		secondary = { type = 10 id = 505 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1500 }
		secondary = { type = 10 id = 12571 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 1510 }
		secondary = { type = 10 id = 22797 }
		startdate = { year = 1157 month = january day = 1 }
		enddate = { year = 1179 month = may day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 1523 }
		secondary = { type = 10 id = 1524 }
		startdate = { year = 1127 month = january day = 1 }
		enddate = { year = 1167 month = june day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 2500 }
		secondary = { type = 10 id = 2515 }
		startdate = { year = 1187 month = january day = 1 }
		enddate = { year = 1185 month = september day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 3511 }
		secondary = { type = 10 id = 3515 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1152 month = july day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 3540 }
		secondary = { type = 10 id = 3541 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 3555 }
		secondary = { type = 10 id = 3556 }
		startdate = { year = 1155 month = january day = 1 }
		enddate = { year = 1174 month = september day = 22 }
	}
	marrige = {
		primary = { type = 10 id = 3560 }
		secondary = { type = 10 id = 3561 }
		startdate = { year = 1125 month = january day = 1 }
		enddate = { year = 1161 month = may day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 3570 }
		secondary = { type = 10 id = 3571 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4500 }
		secondary = { type = 10 id = 5730 }
		startdate = { year = 1152 month = may day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 4501 }
		secondary = { type = 10 id = 5515 }
		startdate = { year = 1172 month = january day = 1 }
		enddate = { year = 1183 month = july day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 4511 }
		secondary = { type = 10 id = 5740 }
		startdate = { year = 1181 month = july day = 1 }
		enddate = { year = 1187 month = august day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 4550 }
		secondary = { type = 10 id = 4575 }
		startdate = { year = 1163 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4560 }
		secondary = { type = 10 id = 4561 }
		startdate = { year = 1119 month = january day = 1 }
		enddate = { year = 1141 month = december day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 4580 }
		secondary = { type = 10 id = 4581 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4590 }
		secondary = { type = 10 id = 4591 }
		startdate = { year = 1134 month = january day = 1 }
		enddate = { year = 1168 month = july day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 4595 }
		secondary = { type = 10 id = 4598 }
		startdate = { year = 1146 month = january day = 1 }
		enddate = { year = 1169 month = febuary day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 4596 }
		secondary = { type = 10 id = 4597 }
		startdate = { year = 1104 month = january day = 1 }
		enddate = { year = 1118 month = april day = 23 }
	}
	marrige = {
		primary = { type = 10 id = 4610 }
		secondary = { type = 10 id = 3510 }
		startdate = { year = 1172 month = january day = 1 }
		enddate = { year = 1182 month = november day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 4620 }
		secondary = { type = 10 id = 4621 }
		startdate = { year = 1148 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4630 }
		secondary = { type = 10 id = 4641 }
		startdate = { year = 1154 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4645 }
		secondary = { type = 10 id = 4646 }
		startdate = { year = 1135 month = january day = 1 }
		enddate = { year = 1148 month = december day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 4655 }
		secondary = { type = 10 id = 4656 }
		startdate = { year = 1127 month = january day = 1 }
		enddate = { year = 1155 month = january day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 4670 }
		secondary = { type = 10 id = 4592 }
		startdate = { year = 1167 month = january day = 1 }
		enddate = { year = 1183 month = may day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 4685 }
		secondary = { type = 10 id = 4686 }
		startdate = { year = 1170 month = january day = 1 }
		enddate = { year = 1181 month = august day = 27 }
	}
	marrige = {
		primary = { type = 10 id = 4690 }
		secondary = { type = 10 id = 4691 }
		startdate = { year = 1161 month = january day = 1 }
		enddate = { year = 1162 month = may day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 4700 }
		secondary = { type = 10 id = 4701 }
		startdate = { year = 1139 month = january day = 1 }
		enddate = { year = 1141 month = march day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 4715 }
		secondary = { type = 10 id = 4716 }
		startdate = { year = 1142 month = january day = 1 }
		enddate = { year = 1153 month = july day = 27 }
	}
	marrige = {
		primary = { type = 10 id = 4730 }
		secondary = { type = 10 id = 4515 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4735 }
		secondary = { type = 10 id = 4736 }
		startdate = { year = 1146 month = january day = 1 }
		enddate = { year = 1176 month = april day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 4740 }
		secondary = { type = 10 id = 4741 }
		startdate = { year = 1151 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4745 }
		secondary = { type = 10 id = 4563 }
		startdate = { year = 1124 month = january day = 1 }
		enddate = { year = 1144 month = august day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 4750 }
		secondary = { type = 10 id = 4751 }
		startdate = { year = 1174 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4755 }
		secondary = { type = 10 id = 6857 }
		startdate = { year = 1138 month = january day = 1 }
		enddate = { year = 1151 month = december day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 4770 }
		secondary = { type = 10 id = 14553 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1176 month = june day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 5500 }
		secondary = { type = 10 id = 5730 }
		startdate = { year = 1137 month = january day = 1 }
		enddate = { year = 1152 month = march day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 5502 }
		secondary = { type = 10 id = 30019 }
		startdate = { year = 1115 month = january day = 1 }
		enddate = { year = 1137 month = march day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 5506 }
		secondary = { type = 10 id = 5522 }
		startdate = { year = 1180 month = april day = 28 }
		enddate = { year = 1190 month = march day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 5520 }
		secondary = { type = 10 id = 12589 }
		startdate = { year = 1169 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5521 }
		secondary = { type = 10 id = 5945 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1168 month = july day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 5523 }
		secondary = { type = 10 id = 5965 }
		startdate = { year = 1186 month = january day = 1 }
		enddate = { year = 1204 month = august day = 9 }
	}
	marrige = {
		primary = { type = 10 id = 5530 }
		secondary = { type = 10 id = 5503 }
		startdate = { year = 1153 month = january day = 1 }
		enddate = { year = 1169 month = october day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 5531 }
		secondary = { type = 10 id = 12800 }
		startdate = { year = 1180 month = january day = 0 }
		enddate = { year = 1183 month = october day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 5542 }
		secondary = { type = 10 id = 5541 }
		startdate = { year = 1172 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5550 }
		secondary = { type = 10 id = 5573 }
		startdate = { year = 1151 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5551 }
		secondary = { type = 10 id = 10521 }
		startdate = { year = 1129 month = january day = 1 }
		enddate = { year = 1160 month = november day = 11 }
	}
	marrige = {
		primary = { type = 10 id = 5560 }
		secondary = { type = 10 id = 5562 }
		startdate = { year = 1180 month = january day = 1 }
		enddate = { year = 1194 month = november day = 11 }
	}
	marrige = {
		primary = { type = 10 id = 5561 }
		secondary = { type = 10 id = 5535 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1160 month = december day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 5570 }
		secondary = { type = 10 id = 5534 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5580 }
		secondary = { type = 10 id = 15505 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5600 }
		secondary = { type = 10 id = 5616 }
		startdate = { year = 1166 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5620 }
		secondary = { type = 10 id = 4525 }
		startdate = { year = 1158 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5621 }
		secondary = { type = 10 id = 5617 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1160 month = november day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 5630 }
		secondary = { type = 10 id = 5645 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5651 }
		secondary = { type = 10 id = 5596 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1170 month = september day = 9 }
	}
	marrige = {
		primary = { type = 10 id = 5660 }
		secondary = { type = 10 id = 5762 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5661 }
		secondary = { type = 10 id = 5662 }
		startdate = { year = 1159 month = january day = 1 }
		enddate = { year = 1165 month = august day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 5665 }
		secondary = { type = 10 id = 5666 }
		startdate = { year = 1162 month = january day = 1 }
		enddate = { year = 1169 month = febuary day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 5671 }
		secondary = { type = 10 id = 5672 }
		startdate = { year = 1134 month = january day = 1 }
		enddate = { year = 1156 month = april day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 5681 }
		secondary = { type = 10 id = 5682 }
		startdate = { year = 1129 month = january day = 1 }
		enddate = { year = 1150 month = april day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 5690 }
		secondary = { type = 10 id = 12509 }
		startdate = { year = 1173 month = january day = 1 }
		enddate = { year = 1181 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5700 }
		secondary = { type = 10 id = 5963 }
		startdate = { year = 1174 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5725 }
		secondary = { type = 10 id = 5710 }
		startdate = { year = 1184 month = january day = 1 }
		enddate = { year = 1192 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5731 }
		secondary = { type = 10 id = 5732 }
		startdate = { year = 1120 month = january day = 1 }
		enddate = { year = 1130 month = febuary day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 5741 }
		secondary = { type = 10 id = 3510 }
		startdate = { year = 1164 month = january day = 1 }
		enddate = { year = 1171 month = febuary day = 20 }
	}
	marrige = {
		primary = { type = 10 id = 5743 }
		secondary = { type = 10 id = 5760 }
		startdate = { year = 1151 month = september day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 5744 }
		secondary = { type = 10 id = 5745 }
		startdate = { year = 1108 month = january day = 1 }
		enddate = { year = 1138 month = april day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 5761 }
		secondary = { type = 10 id = 5770 }
		startdate = { year = 1131 month = january day = 1 }
		enddate = { year = 1133 month = june day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 5780 }
		secondary = { type = 10 id = 5746 }
		startdate = { year = 1160 month = may day = 5 }
		enddate = { year = 1179 month = febuary day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 5781 }
		secondary = { type = 10 id = 5800 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5782 }
		secondary = { type = 10 id = 5801 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5802 }
		secondary = { type = 10 id = 5750 }
		startdate = { year = 1164 month = january day = 1 }
		enddate = { year = 1184 month = april day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 5803 }
		secondary = { type = 10 id = 5804 }
		startdate = { year = 1134 month = january day = 1 }
		enddate = { year = 1168 month = july day = 24 }
	}
	marrige = {
		primary = { type = 10 id = 5810 }
		secondary = { type = 10 id = 5783 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5814 }
		secondary = { type = 10 id = 5825 }
		startdate = { year = 1147 month = january day = 1 }
		enddate = { year = 1157 month = may day = 16 }
	}
	marrige = {
		primary = { type = 10 id = 5830 }
		secondary = { type = 10 id = 5785 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5831 }
		secondary = { type = 10 id = 5840 }
		startdate = { year = 1148 month = january day = 1 }
		enddate = { year = 1173 month = march day = 30 }
	}
	marrige = {
		primary = { type = 10 id = 5851 }
		secondary = { type = 10 id = 5860 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1150 month = april day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 5852 }
		secondary = { type = 10 id = 5850 }
		startdate = { year = 1159 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5870 }
		secondary = { type = 10 id = 5854 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5880 }
		secondary = { type = 10 id = 5890 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5881 }
		secondary = { type = 10 id = 4535 }
		startdate = { year = 1173 month = january day = 1 }
		enddate = { year = 1175 month = april day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 5891 }
		secondary = { type = 10 id = 5893 }
		startdate = { year = 1129 month = january day = 1 }
		enddate = { year = 1152 month = febuary day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 5892 }
		secondary = { type = 10 id = 5504 }
		startdate = { year = 1164 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5910 }
		secondary = { type = 10 id = 12587 }
		startdate = { year = 1165 month = january day = 1 }
		enddate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5920 }
		secondary = { type = 10 id = 4634 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5966 }
		secondary = { type = 10 id = 5512 }
		startdate = { year = 1173 month = january day = 1 }
		enddate = { year = 1181 month = may day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 5980 }
		secondary = { type = 10 id = 5995 }
		startdate = { year = 1158 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5981 }
		secondary = { type = 10 id = 5990 }
		startdate = { year = 1135 month = january day = 1 }
		enddate = { year = 1150 month = june day = 16 }
	}
	marrige = {
		primary = { type = 10 id = 6500 }
		secondary = { type = 10 id = 7502 }
		startdate = { year = 1153 month = july day = 20 }
	}
	marrige = {
		primary = { type = 10 id = 6510 }
		secondary = { type = 10 id = 7501 }
		startdate = { year = 1139 month = january day = 1 }
		enddate = { year = 1144 month = november day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 6800 }
		secondary = { type = 10 id = 6820 }
		startdate = { year = 1166 month = january day = 1 }
		enddate = { year = 1178 month = october day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 6801 }
		secondary = { type = 10 id = 6810 }
		startdate = { year = 1143 month = january day = 1 }
		enddate = { year = 1171 month = july day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 6831 }
		secondary = { type = 10 id = 12955 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6832 }
		secondary = { type = 10 id = 12592 }
		startdate = { year = 1163 month = april day = 11 }
		enddate = { year = 1175 month = march day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 6841 }
		secondary = { type = 10 id = 6845 }
		startdate = { year = 1138 month = january day = 1 }
		enddate = { year = 1157 month = november day = 17 }
	}
	marrige = {
		primary = { type = 10 id = 6850 }
		secondary = { type = 10 id = 6870 }
		startdate = { year = 1155 month = january day = 1 }
		enddate = { year = 1172 month = august day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 6851 }
		secondary = { type = 10 id = 6860 }
		startdate = { year = 1140 month = january day = 1 }
		enddate = { year = 1142 month = may day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 6852 }
		secondary = { type = 10 id = 6880 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6900 }
		secondary = { type = 10 id = 6910 }
		startdate = { year = 1167 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 6911 }
		secondary = { type = 10 id = 6920 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1177 month = may day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 6930 }
		secondary = { type = 10 id = 6902 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 7500 }
		secondary = { type = 10 id = 10510 }
		startdate = { year = 1124 month = january day = 1 }
		enddate = { year = 1149 month = january day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 7510 }
		secondary = { type = 10 id = 4512 }
		startdate = { year = 1177 month = september day = 22 }
	}
	marrige = {
		primary = { type = 10 id = 7520 }
		secondary = { type = 10 id = 6513 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1158 month = august day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 7540 }
		secondary = { type = 10 id = 6511 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 7541 }
		secondary = { type = 10 id = 7550 }
		startdate = { year = 1138 month = january day = 1 }
		enddate = { year = 1156 month = august day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 7580 }
		secondary = { type = 10 id = 7590 }
		startdate = { year = 1128 month = january day = 1 }
		enddate = { year = 1156 month = august day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 7600 }
		secondary = { type = 10 id = 7610 }
		startdate = { year = 1119 month = january day = 1 }
		enddate = { year = 1124 month = may day = 23 }
	}
	marrige = {
		primary = { type = 10 id = 7650 }
		secondary = { type = 10 id = 7651 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 7652 }
		secondary = { type = 10 id = 7659 }
		startdate = { year = 1125 month = january day = 1 }
		enddate = { year = 1158 month = august day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 7656 }
		secondary = { type = 10 id = 7657 }
		startdate = { year = 1153 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 9500 }
		secondary = { type = 10 id = 10522 }
		startdate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 9503 }
		secondary = { type = 10 id = 12672 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1185 month = december day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 9530 }
		secondary = { type = 10 id = 9531 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 10515 }
		secondary = { type = 10 id = 7504 }
		startdate = { year = 1174 month = january day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 10520 }
		secondary = { type = 10 id = 10521 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 11500 }
		secondary = { type = 10 id = 4513 }
		startdate = { year = 1177 month = febuary day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 11510 }
		secondary = { type = 10 id = 6512 }
		startdate = { year = 1153 month = january day = 1 }
		enddate = { year = 1178 month = april day = 16 }
	}
	marrige = {
		primary = { type = 10 id = 12400 }
		secondary = { type = 10 id = 12401 }
		startdate = { year = 1162 month = january day = 1 }
		enddate = { year = 1172 month = december day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 12410 }
		secondary = { type = 10 id = 12593 }
		startdate = { year = 1132 month = january day = 1 }
		enddate = { year = 1160 month = july day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 12421 }
		secondary = { type = 10 id = 12422 }
		startdate = { year = 1162 month = january day = 1 }
		enddate = { year = 1181 month = april day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 12430 }
		secondary = { type = 10 id = 22797 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12431 }
		secondary = { type = 10 id = 12452 }
		startdate = { year = 1182 month = january day = 1 }
		enddate = { year = 1189 month = april day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 12440 }
		secondary = { type = 10 id = 12497 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1172 month = september day = 30 }
	}
	marrige = {
		primary = { type = 10 id = 12450 }
		secondary = { type = 10 id = 12451 }
		startdate = { year = 1156 month = january day = 1 }
		enddate = { year = 1162 month = july day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 12490 }
		secondary = { type = 10 id = 12491 }
		startdate = { year = 1159 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12493 }
		secondary = { type = 10 id = 12494 }
		startdate = { year = 1142 month = january day = 1 }
		enddate = { year = 1157 month = march day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 12495 }
		secondary = { type = 10 id = 12496 }
		startdate = { year = 1138 month = january day = 1 }
		enddate = { year = 1147 month = june day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 12500 }
		secondary = { type = 10 id = 12502 }
		startdate = { year = 1121 month = january day = 1 }
		enddate = { year = 1125 month = febuary day = 22 }
	}
	marrige = {
		primary = { type = 10 id = 12501 }
		secondary = { type = 10 id = 5599 }
		startdate = { year = 1156 month = june day = 16 }
		enddate = { year = 1184 month = november day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 12507 }
		secondary = { type = 10 id = 12508 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12530 }
		secondary = { type = 10 id = 19518 }
		startdate = { year = 1172 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12540 }
		secondary = { type = 10 id = 12541 }
		startdate = { year = 1156 month = january day = 1 }
		enddate = { year = 1177 month = febuary day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12546 }
		secondary = { type = 10 id = 12547 }
		startdate = { year = 1110 month = january day = 1 }
		enddate = { year = 1136 month = may day = 30 }
	}
	marrige = {
		primary = { type = 10 id = 12550 }
		secondary = { type = 10 id = 21563 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12560 }
		secondary = { type = 10 id = 21563 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12580 }
		secondary = { type = 10 id = 12615 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12581 }
		secondary = { type = 10 id = 12601 }
		startdate = { year = 1151 month = january day = 1 }
		enddate = { year = 1176 month = december day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 12583 }
		secondary = { type = 10 id = 21562 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12590 }
		secondary = { type = 10 id = 5955 }
		startdate = { year = 1144 month = january day = 1 }
		enddate = { year = 1165 month = september day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 12591 }
		secondary = { type = 10 id = 5517 }
		startdate = { year = 1160 month = january day = 1 }
		enddate = { year = 1183 month = january day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 12630 }
		secondary = { type = 10 id = 12650 }
		startdate = { year = 1166 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12632 }
		secondary = { type = 10 id = 12662 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1155 month = may day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 12690 }
		secondary = { type = 10 id = 12592 }
		startdate = { year = 1154 month = april day = 12 }
		enddate = { year = 1163 month = january day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 12691 }
		secondary = { type = 10 id = 12700 }
		startdate = { year = 1112 month = january day = 1 }
		enddate = { year = 1139 month = november day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 12721 }
		secondary = { type = 10 id = 12730 }
		startdate = { year = 1157 month = january day = 1 }
		enddate = { year = 1179 month = may day = 26 }
	}
	marrige = {
		primary = { type = 10 id = 12740 }
		secondary = { type = 10 id = 12671 }
		startdate = { year = 1160 month = january day = 1 }
		enddate = { year = 1172 month = august day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 12741 }
		secondary = { type = 10 id = 12750 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1137 month = september day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 12761 }
		secondary = { type = 10 id = 12770 }
		startdate = { year = 1148 month = january day = 1 }
		enddate = { year = 1158 month = april day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 5910 }
		secondary = { type = 10 id = 12800 }
		startdate = { year = 1183 month = january day = 1 }
		enddate = { year = 1200 month = september day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 12781 }
		secondary = { type = 10 id = 12790 }
		startdate = { year = 1143 month = january day = 1 }
		enddate = { year = 1182 month = september day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 12801 }
		secondary = { type = 10 id = 13522 }
		startdate = { year = 1155 month = january day = 1 }
		enddate = { year = 1162 month = july day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 12850 }
		secondary = { type = 10 id = 19512 }
		startdate = { year = 1157 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12851 }
		secondary = { type = 10 id = 12852 }
		startdate = { year = 1139 month = january day = 1 }
		enddate = { year = 1153 month = august day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 12855 }
		secondary = { type = 10 id = 12861 }
		startdate = { year = 1182 month = january day = 1 }
		enddate = { year = 1202 month = november day = 11 }
	}
	marrige = {
		primary = { type = 10 id = 12860 }
		secondary = { type = 10 id = 12853 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12865 }
		secondary = { type = 10 id = 12854 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12900 }
		secondary = { type = 10 id = 4509 }
		startdate = { year = 1168 month = febuary day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12905 }
		secondary = { type = 10 id = 12906 }
		startdate = { year = 1173 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12908 }
		secondary = { type = 10 id = 12909 }
		startdate = { year = 1138 month = january day = 1 }
		enddate = { year = 1160 month = november day = 11 }
	}
	marrige = {
		primary = { type = 10 id = 12910 }
		secondary = { type = 10 id = 12911 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12915 }
		secondary = { type = 10 id = 12916 }
		startdate = { year = 1164 month = january day = 1 }
		enddate = { year = 1180 month = april day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12920 }
		secondary = { type = 10 id = 12921 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12925 }
		secondary = { type = 10 id = 12926 }
		startdate = { year = 1154 month = january day = 1 }
		enddate = { year = 1172 month = december day = 17 }
	}
	marrige = {
		primary = { type = 10 id = 12930 }
		secondary = { type = 10 id = 12931 }
		startdate = { year = 1144 month = january day = 1 }
		enddate = { year = 1174 month = december day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 12932 }
		secondary = { type = 10 id = 12937 }
		startdate = { year = 1166 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12935 }
		secondary = { type = 10 id = 12936 }
		startdate = { year = 1103 month = january day = 1 }
		enddate = { year = 1128 month = march day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 12938 }
		secondary = { type = 10 id = 12939 }
		startdate = { year = 1150 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12940 }
		secondary = { type = 10 id = 12934 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12947 }
		secondary = { type = 10 id = 12933 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12960 }
		secondary = { type = 10 id = 12970 }
		startdate = { year = 1172 month = january day = 1 }
		enddate = { year = 1183 month = july day = 11 }
	}
	marrige = {
		primary = { type = 10 id = 12962 }
		secondary = { type = 10 id = 12963 }
		startdate = { year = 1125 month = january day = 1 }
		enddate = { year = 1156 month = august day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 12964 }
		secondary = { type = 10 id = 12954 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12966 }
		secondary = { type = 10 id = 12967 }
		startdate = { year = 1140 month = january day = 1 }
		enddate = { year = 1161 month = september day = 20 }
	}
	marrige = {
		primary = { type = 10 id = 12971 }
		secondary = { type = 10 id = 12972 }
		startdate = { year = 1148 month = january day = 1 }
		enddate = { year = 1158 month = october day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12980 }
		secondary = { type = 10 id = 12953 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12995 }
		secondary = { type = 10 id = 12542 }
		startdate = { year = 1175 month = january day = 1 }
		enddate = { year = 1181 month = june day = 27 }
	}
	marrige = {
		primary = { type = 10 id = 13520 }
		secondary = { type = 10 id = 13527 }
		startdate = { year = 1136 month = january day = 1 }
		enddate = { year = 1168 month = april day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 13521 }
		secondary = { type = 10 id = 15502 }
		startdate = { year = 1186 month = january day = 1 }
		enddate = { year = 1189 month = april day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 13523 }
		secondary = { type = 10 id = 13540 }
		startdate = { year = 1169 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13550 }
		secondary = { type = 10 id = 13525 }
		startdate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13560 }
		secondary = { type = 10 id = 13561 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14550 }
		secondary = { type = 10 id = 14551 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1151 month = febuary day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 14560 }
		secondary = { type = 10 id = 14561 }
		startdate = { year = 1109 month = january day = 1 }
		enddate = { year = 1126 month = febuary day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 14580 }
		secondary = { type = 10 id = 14554 }
		startdate = { year = 1155 month = january day = 1 }
	}
#	marrige = {
#		primary = { type = 10 id = 14700 }
#		secondary = { type = 10 id = 4499 }
#		startdate = { year = 1173 month = january day = 1 }
#	}
#	marrige = {
#		primary = { type = 10 id = 14710 }
#		secondary = { type = 10 id = 14711 }
#		startdate = { year = 1130 month = january day = 1 }
#		enddate = { year = 1169 month = july day = 7 }
#	}
	marrige = {
		primary = { type = 10 id = 15500 }
		secondary = { type = 10 id = 19515 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15503 }
		secondary = { type = 10 id = 15535 }
		startdate = { year = 1169 month = january day = 1 }
		enddate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15504 }
		secondary = { type = 10 id = 15525 }
		startdate = { year = 1153 month = january day = 1 }
		enddate = { year = 1182 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15509 }
		secondary = { type = 10 id = 15555 }
		startdate = { year = 1120 month = january day = 1 }
		enddate = { year = 1166 month = june day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 15518 }
		secondary = { type = 10 id = 16510 }
		startdate = { year = 1187 month = january day = 1 }
		enddate = { year = 1185 month = april day = 30 }
	}
	marrige = {
		primary = { type = 10 id = 15545 }
		secondary = { type = 10 id = 15501 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15570 }
		secondary = { type = 10 id = 15561 }
		startdate = { year = 1152 month = january day = 1 }
		enddate = { year = 1161 month = febuary day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 15660 }
		secondary = { type = 10 id = 19519 }
		startdate = { year = 1180 month = january day = 1 }
		enddate = { year = 1182 month = may day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 16515 }
		secondary = { type = 10 id = 16540 }
		startdate = { year = 1155 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 18500 }
		secondary = { type = 10 id = 18501 }
		startdate = { year = 1172 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 18510 }
		secondary = { type = 10 id = 15523 }
		startdate = { year = 1107 month = january day = 1 }
		enddate = { year = 1123 month = march day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 19500 }
		secondary = { type = 10 id = 19521 }
		startdate = { year = 1164 month = january day = 1 }
		enddate = { year = 1169 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 19510 }
		secondary = { type = 10 id = 22573 }
		startdate = { year = 1146 month = january day = 1 }
		enddate = { year = 1162 month = may day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 19530 }
		secondary = { type = 10 id = 18511 }
		startdate = { year = 1128 month = january day = 1 }
		enddate = { year = 1141 month = febuary day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 19531 }
		secondary = { type = 10 id = 19532 }
		startdate = { year = 1107 month = january day = 1 }
		enddate = { year = 1139 month = april day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 19550 }
		secondary = { type = 10 id = 19519 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21515 }
		secondary = { type = 10 id = 22781 }
		startdate = { year = 1102 month = january day = 1 }
		enddate = { year = 1110 month = may day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 21516 }
		secondary = { type = 10 id = 30564 }
		startdate = { year = 1084 month = january day = 1 }
		enddate = { year = 1086 month = december day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 21520 }
		secondary = { type = 10 id = 21521 }
		startdate = { year = 1163 month = january day = 1 }
		enddate = { year = 1185 month = march day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 21530 }
		secondary = { type = 10 id = 22823 }
		startdate = { year = 1144 month = january day = 1 }
		enddate = { year = 1158 month = april day = 16 }
	}
	marrige = {
		primary = { type = 10 id = 21531 }
		secondary = { type = 10 id = 12545 }
		startdate = { year = 1123 month = january day = 1 }
		enddate = { year = 1157 month = november day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 21550 }
		secondary = { type = 10 id = 21551 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21560 }
		secondary = { type = 10 id = 19505 }
		startdate = { year = 1140 month = january day = 1 }
		enddate = { year = 1155 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21561 }
		secondary = { type = 10 id = 22509 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21700 }
		secondary = { type = 10 id = 21701 }
		startdate = { year = 1129 month = january day = 1 }
		enddate = { year = 1148 month = january day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 21710 }
		secondary = { type = 10 id = 21711 }
		startdate = { year = 1159 month = january day = 1 }
		enddate = { year = 1177 month = april day = 26 }
	}
	marrige = {
		primary = { type = 10 id = 21730 }
		secondary = { type = 10 id = 1512 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21755 }
		secondary = { type = 10 id = 21567 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 21760 }
		secondary = { type = 10 id = 21761 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1178 month = may day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 22502 }
		secondary = { type = 10 id = 19525 }
		startdate = { year = 1117 month = january day = 1 }
		enddate = { year = 1153 month = febuary day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22504 }
		secondary = { type = 10 id = 22505 }
		startdate = { year = 1166 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22520 }
		secondary = { type = 10 id = 22521 }
		startdate = { year = 1178 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22522 }
		secondary = { type = 10 id = 21514 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1170 month = august day = 19 }
	}
	marrige = {
		primary = { type = 10 id = 22542 }
		secondary = { type = 10 id = 22543 }
		startdate = { year = 1139 month = january day = 1 }
		enddate = { year = 1156 month = april day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 22552 }
		secondary = { type = 10 id = 22553 }
		startdate = { year = 1169 month = january day = 1 }
		enddate = { year = 1186 month = december day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 22574 }
		secondary = { type = 10 id = 22575 }
		startdate = { year = 1095 month = january day = 1 }
		enddate = { year = 1122 month = febuary day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 22577 }
		secondary = { type = 10 id = 22578 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1180 month = april day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 22579 }
		secondary = { type = 10 id = 22581 }
		startdate = { year = 1168 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22600 }
		secondary = { type = 10 id = 22601 }
		startdate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22602 }
		secondary = { type = 10 id = 22603 }
		startdate = { year = 1116 month = january day = 1 }
		enddate = { year = 1146 month = august day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22620 }
		secondary = { type = 10 id = 22621 }
		startdate = { year = 1166 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22622 }
		secondary = { type = 10 id = 22623 }
		startdate = { year = 1148 month = january day = 1 }
		enddate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22630 }
		secondary = { type = 10 id = 22631 }
		startdate = { year = 1169 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22632 }
		secondary = { type = 10 id = 22633 }
		startdate = { year = 1135 month = january day = 1 }
		enddate = { year = 1164 month = febuary day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 22640 }
		secondary = { type = 10 id = 22641 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22650 }
		secondary = { type = 10 id = 22651 }
		startdate = { year = 1143 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22652 }
		secondary = { type = 10 id = 21523 }
		startdate = { year = 1178 month = november day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22655 }
		secondary = { type = 10 id = 22656 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22658 }
		secondary = { type = 10 id = 22659 }
		startdate = { year = 1182 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22670 }
		secondary = { type = 10 id = 22671 }
		startdate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22672 }
		secondary = { type = 10 id = 22673 }
		startdate = { year = 1108 month = january day = 1 }
		enddate = { year = 1124 month = september day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 22676 }
		secondary = { type = 10 id = 22677 }
		startdate = { year = 1147 month = january day = 1 }
		enddate = { year = 1174 month = june day = 30 }
	}
	marrige = {
		primary = { type = 10 id = 22682 }
		secondary = { type = 10 id = 22683 }
		startdate = { year = 1175 month = january day = 1 }
		enddate = { year = 1176 month = june day = 20 }
	}
	marrige = {
		primary = { type = 10 id = 22740 }
		secondary = { type = 10 id = 22741 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22792 }
		secondary = { type = 10 id = 21578 }
		startdate = { year = 1137 month = january day = 1 }
		enddate = { year = 1143 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22795 }
		secondary = { type = 10 id = 22796 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1158 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 22828 }
		secondary = { type = 10 id = 16500 }
		startdate = { year = 1185 month = january day = 1 }
		enddate = { year = 1190 month = march day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 23500 }
		secondary = { type = 10 id = 23522 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23505 }
		secondary = { type = 10 id = 23582 }
		startdate = { year = 1175 month = october day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 23520 }
		secondary = { type = 10 id = 23521 }
		startdate = { year = 1149 month = january day = 1 }
		enddate = { year = 1174 month = march day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 13524 }
		secondary = { type = 10 id = 23522 }
		startdate = { year = 1168 month = january day = 1 }
		enddate = { year = 1177 month = april day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 23560 }
		secondary = { type = 10 id = 23524 }
		startdate = { year = 1183 month = january day = 1 }
		enddate = { year = 1190 month = april day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 23570 }
		secondary = { type = 10 id = 15560 }
		startdate = { year = 1175 month = december day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 23520 }
		secondary = { type = 10 id = 15560 }
		startdate = { year = 1167 month = january day = 1 }
		enddate = { year = 1174 month = april day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 23580 }
		secondary = { type = 10 id = 23581 }
		startdate = { year = 1129 month = january day = 1 }
		enddate = { year = 1160 month = march day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 23585 }
		secondary = { type = 10 id = 23586 }
		startdate = { year = 1158 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23590 }
		secondary = { type = 10 id = 23720 }
		startdate = { year = 1154 month = january day = 1 }
		enddate = { year = 1163 month = april day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 23600 }
		secondary = { type = 10 id = 23601 }
		startdate = { year = 1130 month = january day = 1 }
		enddate = { year = 1135 month = june day = 5 }
	}
	marrige = {
		primary = { type = 10 id = 23650 }
		secondary = { type = 10 id = 23685 }
		startdate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23660 }
		secondary = { type = 10 id = 23661 }
		startdate = { year = 1139 month = january day = 1 }
		enddate = { year = 1152 month = march day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 23670 }
		secondary = { type = 10 id = 5513 }
		startdate = { year = 114 month = january day = 1 }
		enddate = { year = 1137 month = july day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 23700 }
		secondary = { type = 10 id = 23532 }
		startdate = { year = 1126 month = january day = 1 }
		enddate = { year = 1130 month = july day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 23710 }
		secondary = { type = 10 id = 5511 }
		startdate = { year = 1107 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23740 }
		secondary = { type = 10 id = 23720 }
		startdate = { year = 1136 month = january day = 1 }
		enddate = { year = 1149 month = may day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 23750 }
		secondary = { type = 10 id = 23751 }
		startdate = { year = 1170 month = january day = 1 }
		enddate = { year = 1175 month = febuary day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 30001 }
		secondary = { type = 10 id = 30002 }
		startdate = { year = 1095 month = january day = 1 }
		enddate = { year = 1112 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30003 }
		secondary = { type = 10 id = 30004 }
		startdate = { year = 1125 month = january day = 1 }
		enddate = { year = 1148 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30005 }
		secondary = { type = 10 id = 30006 }
		startdate = { year = 1093 month = january day = 1 }
		enddate = { year = 1105 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30005 }
		secondary = { type = 10 id = 30007 }
		startdate = { year = 1060 month = january day = 1 }
		enddate = { year = 1080 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5530 }
		secondary = { type = 10 id = 21570 }
		startdate = { year = 1175 month = january day = 1 }
		enddate = { year = 1194 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23670 }
		secondary = { type = 10 id = 30010 }
		startdate = { year = 1115 month = january day = 1 }
		enddate = { year = 1137 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5532 }
		secondary = { type = 10 id = 5574 }
		startdate = { year = 1178 month = january day = 1 }
		enddate = { year = 1193 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30015 }
		secondary = { type = 10 id = 30018 }
		startdate = { year = 1181 month = january day = 1 }
		enddate = { year = 1218 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30012 }
		secondary = { type = 10 id = 30016 }
		startdate = { year = 1142 month = january day = 1 }
		enddate = { year = 1168 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30013 }
		secondary = { type = 10 id = 30017 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5820 }
		secondary = { type = 10 id = 4584 }
		startdate = { year = 1165 month = january day = 1 }
		enddate = { year = 1187 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5500 }
		secondary = { type = 10 id = 5505 }
		startdate = { year = 1160 month = january day = 1 }
		enddate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5500 }
		secondary = { type = 10 id = 7503 }
		startdate = { year = 1154 month = january day = 1 }
		enddate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30020 }
		secondary = { type = 10 id = 30021 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30023 }
		secondary = { type = 10 id = 30024 }
		startdate = { year = 1168 month = january day = 1 }
		enddate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30025 }
		secondary = { type = 10 id = 30026 }
		startdate = { year = 1120 month = january day = 1 }
		enddate = { year = 1148 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30027 }
		secondary = { type = 10 id = 30031 }
		startdate = { year = 1165 month = january day = 1 }
		enddate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4990 }
		secondary = { type = 10 id = 30032 }
		startdate = { year = 1116 month = january day = 1 }
		enddate = { year = 1130 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4985 }
		secondary = { type = 10 id = 30033 }
		startdate = { year = 1132 month = january day = 1 }
		enddate = { year = 1150 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4980 }
		secondary = { type = 10 id = 30034 }
		startdate = { year = 1174 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5652 }
		secondary = { type = 10 id = 30037 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30040 }
		secondary = { type = 10 id = 5962 }
		startdate = { year = 1145 month = january day = 1 }
		enddate = { year = 1162 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30042 }
		secondary = { type = 10 id = 30045 }
		startdate = { year = 1145 month = january day = 1 }
		enddate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30041 }
		secondary = { type = 10 id = 30046 }
		startdate = { year = 1133 month = january day = 1 }
		enddate = { year = 1140 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30047 }
		secondary = { type = 10 id = 30048 }
		startdate = { year = 1134 month = january day = 1 }
		enddate = { year = 1165 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30049 }
		secondary = { type = 10 id = 30050 }
		startdate = { year = 1169 month = january day = 1 }
		enddate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30051 }
		secondary = { type = 10 id = 30052 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30060 }
		secondary = { type = 10 id = 30061 }
		startdate = { year = 1153 month = january day = 1 }
		enddate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5930 }
		secondary = { type = 10 id = 30063 }
		startdate = { year = 1172 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30067 }
		secondary = { type = 10 id =30068 }
		startdate = { year = 1144 month = january day = 1 }
		enddate = { year = 1173 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5680 }
		secondary = { type = 10 id = 5685 }
		startdate = { year = 1158 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30070 }
		secondary = { type = 10 id = 30072 }
		startdate = { year = 1129 month = january day = 1 }
		enddate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5970 }
		secondary = { type = 10 id = 30074 }
		startdate = { year = 1155 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30077 }
		secondary = { type = 10 id = 30075 }
		startdate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30079 }
		secondary = { type = 10 id = 5692  }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30081 }
		secondary = { type = 10 id = 12582 }
		startdate = { year = 1170 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5670 }
		secondary = { type = 10 id = 30089 }
		startdate = { year = 1150 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5601 }
		secondary = { type = 10 id = 5556 }
		startdate = { year = 1150 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5701 }
		secondary = { type = 10 id = 5702 }
		startdate = { year = 1158 month = january day = 1 }
		enddate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30090 }
		secondary = { type = 10 id = 30092 }
		startdate = { year = 1152 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30091 }
		secondary = { type = 10 id = 30096 }
		startdate = { year = 1184 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5659 }
		secondary = { type = 10 id = 30044 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30097 }
		secondary = { type = 10 id = 5853 }
		startdate = { year = 1186 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30099 }
		secondary = { type = 10 id = 5617 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1165 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13006 }
		secondary = { type = 10 id = 30101 }
		startdate = { year = 1175 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30103 }
		secondary = { type = 10 id = 30104 }
		startdate = { year = 1120 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30105 }
		secondary = { type = 10 id = 30106 }
		startdate = { year = 1120 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 19500 }
		secondary = { type = 10 id = 5515 }
		startdate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13006 }
		secondary = { type = 10 id = 30108 }
		startdate = { year = 1164 month = january day = 1 }
		enddate = { year = 1173 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30110 }
		secondary = { type = 10 id = 30113 }
		startdate = { year = 1126 month = january day = 1 }
		enddate = { year = 1141 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30111 }
		secondary = { type = 10 id = 30114 }
		startdate = { year = 1137 month = january day = 1 }
		enddate = { year = 1181 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30112 }
		secondary = { type = 10 id = 30116 }
		startdate = { year = 1169 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5982 }
		secondary = { type = 10 id = 30120 }
		startdate = { year = 1178 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5984 }
		secondary = { type = 10 id = 30121 }
		startdate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30123 }
		secondary = { type = 10 id = 30122 }
		startdate = { year = 1164 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5961 }
		secondary = { type = 10 id = 6503 }
		startdate = { year = 1195 month = january day = 1 }
		enddate = { year = 1201 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23505 }
		secondary = { type = 10 id = 23524 }
		startdate = { year = 1198 month = january day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 5684 }
		secondary = { type = 10 id = 30130 }
		startdate = { year = 1187 month = january day = 1 }
		enddate = { year = 1204 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30131 }
		secondary = { type = 10 id = 5652 }
		startdate = { year = 1196 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id =  30086 }
		secondary = { type = 10 id = 5726 }
		startdate = { year = 1200 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id =  30078 }
		secondary = { type = 10 id = 30144 }
		startdate = { year = 1196 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id =  30146 }
		secondary = { type = 10 id = 12800 }
		startdate = { year = 1200 month = january day = 9 }
	}
	marrige = {
		primary = { type = 10 id =  5895 }
		secondary = { type = 10 id = 30147 }
		startdate = { year = 1184 month = january day = 9 }
	}
	marrige = {
		primary = { type = 10 id =  12782 }
		secondary = { type = 10 id = 30149 }
		startdate = { year = 1199 month = january day = 9 }
	}
	marrige = {
		primary = { type = 10 id =  5640 }
		secondary = { type = 10 id = 30153 }
		startdate = { year = 1187 month = january day = 9 }
	}
	marrige = {
		primary = { type = 10 id =  4514 }
		secondary = { type = 10 id = 30154 }
		startdate = { year = 1200 month = january day = 9 }
	}
	marrige = {
		primary = { type = 10 id =  30085 }
		secondary = { type = 10 id = 30156 }
		startdate = { year = 1203 month = january day = 9 }
	}
	marrige = {
		primary = { type = 10 id =  5533 }
		secondary = { type = 10 id = 30157 }
		startdate = { year = 1195 month = january day = 9 }
	}
	marrige = {
		primary = { type = 10 id =  5532 }
		secondary = { type = 10 id = 4513 }
		startdate = { year = 1196 month = january day = 9 }
		enddate = { year = 1199 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id =  6502 }
		secondary = { type = 10 id = 30161 }
		startdate = { year = 1195 month = january day = 9 }
		enddate = { year = 1203 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id =  5540 }
		secondary = { type = 10 id = 30164}
		startdate = { year = 1186 month = january day = 9 }
	}
	marrige = {
		primary = { type = 10 id =  10500 }
		secondary = { type = 10 id = 5582}
		startdate = { year = 1204 month = january day = 9 }
	}
	marrige = {
		primary = { type = 10 id = 5725 }
		secondary = { type = 10 id = 5526 }
		startdate = { year = 1193 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 4680 }
		secondary = { type = 10 id = 5740 }
		startdate = { year = 1187 month = february day = 9 }
		enddate = { year = 1199 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30069 }
		secondary = { type = 10 id = 5740 }
		startdate = { year = 1199 month = january day = 9 }
		enddate = { year = 1201 month = august day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 30133 }
		secondary = { type = 10 id = 30166 }
		startdate = { year = 1204 month = january day = 9 }
	}
	marrige = {
		primary = { type = 10 id = 5523 }
		secondary = { type = 10 id = 4513 }
		startdate = { year = 1199 month = january day = 20 }
		enddate = { year = 1199 month = september day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 30069 }
		secondary = { type = 10 id = 30167 }
		startdate = { year = 1203 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30066 }
		secondary = { type = 10 id = 30169 }
		startdate = { year = 1203 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30065 }
		secondary = { type = 10 id = 30170 }
		startdate = { year = 1203 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30064 }
		secondary = { type = 10 id = 30168 }
		startdate = { year = 1203 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30014 }
		secondary = { type = 10 id = 23573 }
		startdate = { year = 1200 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30109 }
		secondary = { type = 10 id = 30171 }
		startdate = { year = 1198 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30118 }
		secondary = { type = 10 id = 30178 }
		startdate = { year = 1198 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30115 }
		secondary = { type = 10 id = 30179 }
		startdate = { year = 1193 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30029 }
		secondary = { type = 10 id = 30182 }
		startdate = { year = 1196 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30185 }
		secondary = { type = 10 id = 30187 }
		startdate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30188 }
		secondary = { type = 10 id = 30189 }
		startdate = { year = 1121 month = january day = 1 }
		enddate = { year = 1151 month = september day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 30084 }
		secondary = { type = 10 id = 30191 }
		startdate = { year = 1160 month = january day = 1 }
		enddate = { year = 1189 month = september day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 30190 }
		secondary = { type = 10 id = 30192 }
		startdate = { year = 1150 month = january day = 1 }
		enddate = { year = 1160 month = september day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 30037 }
		secondary = { type = 10 id = 30194 }
		startdate = { year = 1200 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30062 }
		secondary = { type = 10 id = 30196 }
		startdate = { year = 1193 month = january day = 1 }
		enddate = { year = 1203 month = september day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 30055 }
		secondary = { type = 10 id = 30199 }
		startdate = { year = 1200 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30073 }
		secondary = { type = 10 id = 30076 }
		startdate = { year = 1200 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5960 }
		secondary = { type = 10 id = 23524 }
		startdate = { year = 1192 month = january day = 15 }
		enddate = { year = 1198 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13521 }
		secondary = { type = 10 id = 23524 }
		startdate = { year = 1190 month = january day = 31 }
		enddate = { year = 1192 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5554 }
		secondary = { type = 10 id = 30208 }
		startdate = { year = 1189 month = january day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 30209 }
		secondary = { type = 10 id = 30211 }
		startdate = { year = 1203 month = january day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 5506 }
		secondary = { type = 10 id = 30212 }
		startdate = { year = 1196 month = january day = 31 }
		enddate = { year = 1201 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 5507 }
		secondary = { type = 10 id = 30214 }
		startdate = { year = 1200 month = january day = 31 }
		enddate = { year = 1226 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30038 }
		secondary = { type = 10 id = 30223 }
		startdate = { year = 1140 month = january day = 31 }
		enddate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30224 }
		secondary = { type = 10 id = 30225 }
		startdate = { year = 1160 month = january day = 31 }
		enddate = { year = 1167 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30226 }
		secondary = { type = 10 id = 30227 }
		startdate = { year = 1200 month = january day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 3000 }
		secondary = { type = 10 id = 30231 }
		startdate = { year = 1186 month = january day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 30233 }
		secondary = { type = 10 id = 16500 }
		startdate = { year = 1191 month = january day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 8500 }
		secondary = { type = 10 id = 9501 }
		startdate = { year = 1165 month = january day = 31 }
		enddate = { year = 1179 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30235 }
		secondary = { type = 10 id = 7511 }
		startdate = { year = 1197 month = january day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 19501 }
		secondary = { type = 10 id = 30240 }
		startdate = { year = 1198 month = january day = 31 }
		enddate = { year = 1204 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 8500 }
		secondary = { type = 10 id = 7562 }
		startdate = { year = 1187 month = may day = 31 }
		enddate = { year = 1188 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30235 }
		secondary = { type = 10 id = 9504 }
		startdate = { year = 1191 month = may day = 31 }
		enddate = { year = 1197 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30243 }
		secondary = { type = 10 id = 30244 }
		startdate = { year = 1093 month = may day = 31 }
		enddate = { year = 1112 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12901 }
		secondary = { type = 10 id = 12534 }
		startdate = { year = 1204 month = may day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 12038 }
		secondary = { type = 10 id = 12433 }
		startdate = { year = 1200 month = may day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 30276 }
		secondary = { type = 10 id = 30280 }
		startdate = { year = 1095 month = may day = 31 }
		enddate = { year = 1125 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12390 }
		secondary = { type = 10 id = 30281 }
		startdate = { year = 1185 month = may day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 12376 }
		secondary = { type = 10 id = 12377 }
		startdate = { year = 1200 month = may day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 12374 }
		secondary = { type = 10 id = 12378 }
		startdate = { year = 1128 month = may day = 31 }
		enddate = { year = 1154 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12041 }
		secondary = { type = 10 id = 12042 }
		startdate = { year = 1118 month = may day = 31 }
		enddate = { year = 1150 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12040 }
		secondary = { type = 10 id = 12043 }
		startdate = { year = 1146 month = may day = 31 }
		enddate = { year = 1190 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12047 }
		secondary = { type = 10 id = 12048 }
		startdate = { year = 1150 month = may day = 31 }
		enddate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12050 }
		secondary = { type = 10 id = 12051 }
		startdate = { year = 1190 month = may day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 12052 }
		secondary = { type = 10 id = 12053 }
		startdate = { year = 1155 month = may day = 31 }
		enddate = { year = 1191 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12060 }
		secondary = { type = 10 id = 12061 }
		startdate = { year = 1187 month = may day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 17502 }
		secondary = { type = 10 id = 17505 }
		startdate = { year = 1187 month = may day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 30286 }
		secondary = { type = 10 id = 15511 }
		startdate = { year = 1200 month = may day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 12506 }
		secondary = { type = 10 id = 15506 }
		startdate = { year = 1190 month = may day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 18507 }
		secondary = { type = 10 id = 15512 }
		startdate = { year = 1204 month = may day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 15001 }
		secondary = { type = 10 id = 5519 }
		startdate = { year = 1204 month = may day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 30292 }
		secondary = { type = 10 id = 15510 }
		startdate = { year = 1190 month = may day = 31 }
	}
	marrige = {
		primary = { type = 10 id = 30299 }
		secondary = { type = 10 id = 5519 }
		startdate = { year = 1182 month = may day = 1 }
		enddate = { year = 1183 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30294 }
		secondary = { type = 10 id = 5519 }
		startdate = { year = 1183 month = may day = 31 }
		enddate = { year = 1185 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13526 }
		secondary = { type = 10 id = 30300 }
		startdate = { year = 1180 month = may day = 31 }
		enddate = { year = 1182 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30301 }
		secondary = { type = 10 id = 15512 }
		startdate = { year = 1200 month = may day = 31 }
		enddate = { year = 1204 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 15556 }
		secondary = { type = 10 id = 15557 }
		startdate = { year = 1082 month = may day = 31 }
		enddate = { year = 1137 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30296 }
		secondary = { type = 10 id = 15558 }
		startdate = { year = 1080 month = may day = 31 }
		enddate = { year = 1118 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30298 }
		secondary = { type = 10 id = 23743 }
		startdate = { year = 1161 month = may day = 31 }
		enddate = { year = 1180 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30298 }
		secondary = { type = 10 id = 15559 }
		startdate = { year = 1145 month = may day = 31 }
		enddate = { year = 1160 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23590 }
		secondary = { type = 10 id = 23592 }
		startdate = { year = 1182 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 23561 }
		secondary = { type = 10 id = 23592 }
		startdate = { year = 1163 month = january day = 1 }
		enddate = { year = 1173 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30580 }
		secondary = { type = 10 id = 21540 } 
		startdate = { year = 1160 month = january day = 1 }
		enddate = { year = 1189 month = august day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 21565 }
		secondary = { type = 10 id = 21714 }
		startdate = { year = 1189 month = january day = 1 }
		enddate = { year = 1195 month = january day = 1 } 
	}
	marrige = {
		primary = { type = 10 id = 30530 }
		secondary = { type = 10 id = 21732 }
		startdate = { year = 1194 month = april day = 26 }
	}
	marrige = {
		primary = { type = 10 id = 21537 }
		secondary = { type = 10 id = 12943 }
		startdate = { year = 1188 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30303 }
		secondary = { type = 10 id = 30204 }
		startdate = { year = 1204 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12431 }
		secondary = { type = 10 id = 12951 }
		startdate = { year = 1190 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 19502 }
		secondary = { type = 10 id = 12946 }
		startdate = { year = 1201 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 12855 }
		secondary = { type = 10 id = 19503 }
		startdate = { year = 1203 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 30306 }
		secondary = { type = 10 id = 30317 }
		startdate = { year = 1145 month = january day = 1 }
		enddate = { year = 1175 month = january day = 1 } 
	}
	marrige = {
		primary = { type = 10 id = 30307 }
		secondary = { type = 10 id = 30318 }
		startdate = { year = 1128 month = january day = 1 }
		enddate = { year = 1160 month = january day = 1 } 
	}
	marrige = {
		primary = { type = 10 id = 30308 }
		secondary = { type = 10 id = 30319 }
		startdate = { year = 1188 month = january day = 1 }
		enddate = { year = 1190 month = january day = 1 } 
	}
	marrige = {
		primary = { type = 10 id = 30305 }
		secondary = { type = 10 id = 30320 }
		startdate = { year = 1200 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 14714 }
		secondary = { type = 10 id = 30540 }
		startdate = { year = 1200 month = january day = 1 }
	}
	rival = { 
		primary = { type = 10 id = 14714 }
		secondary = { type = 10 id = 14724 }
		startdate = { year = 1336 month = january day = 1 }
	}
	rival = { 
		primary = { type = 10 id = 14804 }
		secondary = { type = 10 id = 14805 }
		startdate = { year = 1336 month = january day = 1 }
	}
}