relations = {
	alliance = { 
		primary = { type = 10 id = 55500 }
		secondary = { type = 10 id = 53500 }
		startdate = { year = 1332 month = december day = 27 }
	}
	alliance = { 
		primary = { type = 10 id = 71500 }
		secondary = { type = 10 id = 69500 }
		startdate = { year = 1335 month = december day = 27 }
	}
	alliance = { 
		primary = { type = 10 id = 73500 }
		secondary = { type = 10 id = 72840 }
		startdate = { year = 1335 month = december day = 27 }
	}
	alliance = { 
		primary = { type = 10 id = 67500 }
		secondary = { type = 10 id = 68500 }
		startdate = { year = 1335 month = december day = 27 }
	}
	marrige = {
		primary = { type = 10 id = 12070 }
		secondary = { type = 10 id = 12071 }
		startdate = { year = 1298 month = january day = 1 }
		enddate = { year = 1311 month = october day = 10 }
	}
	marrige = {
		primary = { type = 10 id = 12070 }
		secondary = { type = 10 id = 12085 }
		startdate = { year = 1311 month = december day = 1 }
		enddate = { year = 1320 month = october day = 10 }
	}
	marrige = { 
		primary = { type = 10 id = 12072 }
		secondary = { type = 10 id = 12073 }
		startdate = { year = 1312 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 12078 }
		secondary = { type = 10 id = 12079 }
		startdate = { year = 1328 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 13024 }
		secondary = { type = 10 id = 13025 }
		startdate = { year = 1290 month = january day = 1 }
		enddate = { year = 1318 month = october day = 10 }
	}
	marrige = { 
		primary = { type = 10 id = 13024 }
		secondary = { type = 10 id = 13026 }
		startdate = { year = 1319 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 20301 }
		secondary = { type = 10 id = 63144 }
		startdate = { year = 1329 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 20302 }
		secondary = { type = 10 id = 20303 }
		startdate = { year = 1301 month = january day = 1 }
		enddate = { year = 1330 month = october day = 10 }
	}
	marrige = { 
		primary = { type = 10 id = 20304 }
		secondary = { type = 10 id = 62698 }
		startdate = { year = 1333 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 63160 }
		secondary = { type = 10 id = 12086 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50500 }
		secondary = { type = 10 id = 55942 }
		startdate = { year = 1335 month = november day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50501 }
		secondary = { type = 10 id = 52505 }
		startdate = { year = 1312 month = january day = 1 }
		enddate = { year = 1318 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50502 }
		secondary = { type = 10 id = 50503 }
		startdate = { year = 1276 month = november day = 11 }
		enddate = { year = 1290 month = december day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 50504 }
		secondary = { type = 10 id = 51516 }
		startdate = { year = 1298 month = january day = 1 }
		enddate = { year = 1321 month = may day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 50506 }
		secondary = { type = 10 id = 51511 }
		startdate = { year = 1260 month = january day = 1 }
		enddate = { year = 1286 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50510 }
		secondary = { type = 10 id = 50511 }
		startdate = { year = 1235 month = january day = 1 }
		enddate = { year = 1254 month = june day = 17 }
	}
	marrige = { 
		primary = { type = 10 id = 50600 }
		secondary = { type = 10 id = 50603 }
		startdate = { year = 1318 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50601 }
		secondary = { type = 10 id = 50602 }
		startdate = { year = 1289 month = january day = 1 }
		enddate = { year = 1319 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50604 }
		secondary = { type = 10 id = 50605 }
		startdate = { year = 1265 month = january day = 1 }
		enddate = { year = 1294 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50611 }
		secondary = { type = 10 id = 50612 }
		startdate = { year = 1289 month = january day = 1 }
		enddate = { year = 1320 month = march day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 50613 }
		secondary = { type = 10 id = 50614 }
		startdate = { year = 1312 month = january day = 1 }
		enddate = { year = 1328 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50630 }
		secondary = { type = 10 id = 50633 }
		startdate = { year = 1304 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50631 }
		secondary = { type = 10 id = 50632 }
		startdate = { year = 1285 month = january day = 1 }
		enddate = { year = 1305 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50634 }
		secondary = { type = 10 id = 50635 }
		startdate = { year = 1275 month = january day = 1 }
		enddate = { year = 1295 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50647 }
		secondary = { type = 10 id = 50659 }
		startdate = { year = 1306 month = january day = 1 }
		enddate = { year = 1322 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50650 }
		secondary = { type = 10 id = 50653 }
		startdate = { year = 1319 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50651 }
		secondary = { type = 10 id = 50652 }
		startdate = { year = 1278 month = january day = 1 }
		enddate = { year = 1280 month = august day = 20 }
	}
	marrige = {
		primary = { type = 10 id = 50654 }
		secondary = { type = 10 id = 50655 }
		startdate = { year = 1250 month = january day = 1 }
		enddate = { year = 1261 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50660 }
		secondary = { type = 10 id = 50640 }
		startdate = { year = 1332 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50661 }
		secondary = { type = 10 id = 50662 }
		startdate = { year = 1310 month = january day = 1 }
		enddate = { year = 1319 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50681 }
		secondary = { type = 10 id = 50652 }
		startdate = { year = 1281 month = january day = 1 }
		enddate = { year = 1313 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50682 }
		secondary = { type = 10 id = 50615 }
		startdate = { year = 1334 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50690 }
		secondary = { type = 10 id = 50716 }
		startdate = { year = 1316 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50691 }
		secondary = { type = 10 id = 50833 }
		startdate = { year = 1291 month = january day = 1 }
		enddate = { year = 1313 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50693 }
		secondary = { type = 10 id = 50717 }
		startdate = { year = 1316 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50700 }
		secondary = { type = 10 id = 50703 }
		startdate = { year = 1320 month = january day = 1 }
		enddate = { year = 1325 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50701 }
		secondary = { type = 10 id = 50702 }
		startdate = { year = 1285 month = january day = 1 }
		enddate = { year = 1326 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50710 }
		secondary = { type = 10 id = 50713 }
		startdate = { year = 1337 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50711 }
		secondary = { type = 10 id = 50712 }
		startdate = { year = 1298 month = january day = 1 }
		enddate = { year = 1314 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50718 }
		secondary = { type = 10 id = 50705 }
		startdate = { year = 1307 month = january day = 1 }
		enddate = { year = 1335 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50720 }
		secondary = { type = 10 id = 50723 }
		startdate = { year = 1310 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50721 }
		secondary = { type = 10 id = 50722 }
		startdate = { year = 1270 month = january day = 1 }
		enddate = { year = 1307 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50724 }
		secondary = { type = 10 id = 50725 }
		startdate = { year = 1289 month = january day = 1 }
		enddate = { year = 1315 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50730 }
		secondary = { type = 10 id = 50750 }
		startdate = { year = 1310 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50731 }
		secondary = { type = 10 id = 50732 }
		startdate = { year = 1280 month = january day = 1 }
		enddate = { year = 1320 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50740 }
		secondary = { type = 10 id = 50741 }
		startdate = { year = 1310 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50751 }
		secondary = { type = 10 id = 50752 }
		startdate = { year = 1280 month = january day = 1 }
		enddate = { year = 1320 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50780 }
		secondary = { type = 10 id = 50783 }
		startdate = { year = 1310 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50781 }
		secondary = { type = 10 id = 50782 }
		startdate = { year = 1287 month = january day = 1 }
		enddate = { year = 1302 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50784 }
		secondary = { type = 10 id = 50785 }
		startdate = { year = 1295 month = january day = 1 }
		enddate = { year = 1317 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50800 }
		secondary = { type = 10 id = 50812 }
		startdate = { year = 1299 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50801 }
		secondary = { type = 10 id = 50802 }
		startdate = { year = 1270 month = january day = 1 }
		enddate = { year = 1290 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50805 }
		secondary = { type = 10 id = 50806 }
		startdate = { year = 1322 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50810 }
		secondary = { type = 10 id = 50811 }
		startdate = { year = 1279 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50820 }
		secondary = { type = 10 id = 50823 }
		startdate = { year = 1300 month = january day = 1 }
		enddate = { year = 1312 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 50820 }
		secondary = { type = 10 id = 50825 }
		startdate = { year = 1316 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50821 }
		secondary = { type = 10 id = 50822 }
		startdate = { year = 1269 month = january day = 1 }
		enddate = { year = 1305 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 50830 }
		secondary = { type = 10 id = 50832 }
		startdate = { year = 1247 month = january day = 1 }
		enddate = { year = 1250 month = january day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 50841 }
		secondary = { type = 10 id = 50648 }
		startdate = { year = 1329 month = january day = 1 }
		enddate = { year = 1334 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 51500 }
		secondary = { type = 10 id = 51501 }
		startdate = { year = 1337 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 51502 }
		secondary = { type = 10 id = 51503 }
		startdate = { year = 1310 month = january day = 1 }
		enddate = { year = 1325 month = march day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 51513 }
		secondary = { type = 10 id = 51519 }
		startdate = { year = 1248 month = january day = 1 }
		enddate = { year = 1259 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 51514 }
		secondary = { type = 10 id = 51517 }
		startdate = { year = 1273 month = january day = 1 }
		enddate = { year = 1286 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 51515 }
		secondary = { type = 10 id = 50505 }
		startdate = { year = 1297 month = january day = 1 }
		enddate = { year = 1319 month = august day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 51520 }
		secondary = { type = 10 id = 51521 }
		startdate = { year = 1300 month = january day = 1 }
		enddate = { year = 1330 month = july day = 26 }
	}
	marrige = {
		primary = { type = 10 id = 51529 }
		secondary = { type = 10 id = 51946 }
		startdate = { year = 1313 month = january day = 1 }
		enddate = { year = 1325 month = july day = 26 }
	}
	marrige = { 
		primary = { type = 10 id = 51530 }
		secondary = { type = 10 id = 51532 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 51801 }
		secondary = { type = 10 id = 52505 }
		startdate = { year = 1327 month = june day = 21 }
		enddate = { year = 1330 month = may day = 29 }
	}
	marrige = { 
		primary = { type = 10 id = 51940 }
		secondary = { type = 10 id = 51992 }
		startdate = { year = 1314 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 51950 }
		secondary = { type = 10 id = 51976 }
		startdate = { year = 1296 month = january day = 1 }
		enddate = { year = 1300 month = may day = 23 }
	}
	marrige = { 
		primary = { type = 10 id = 51960 }
		secondary = { type = 10 id = 51962 }
		startdate = { year = 1327 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 51972 }
		secondary = { type = 10 id = 50507 }
		startdate = { year = 1275 month = january day = 1 }
		enddate = { year = 1312 month = october day = 25 }
	}
	marrige = { 
		primary = { type = 10 id = 51980 }
		secondary = { type = 10 id = 50508 }
		startdate = { year = 1336 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 51981 }
		secondary = { type = 10 id = 51982 }
		startdate = { year = 1292 month = january day = 1 }
		enddate = { year = 1314 month = january day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 51981 }
		secondary = { type = 10 id = 62112 }
		startdate = { year = 1315 month = january day = 1 }
		enddate = { year = 1329 month = january day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 51990 }
		secondary = { type = 10 id = 51951 }
		startdate = { year = 1301 month = january day = 1 }
		enddate = { year = 1332 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 51990 }
		secondary = { type = 10 id = 51996 }
		startdate = { year = 1333 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 51991 }
		secondary = { type = 10 id = 51518 }
		startdate = { year = 1291 month = january day = 1 }
		enddate = { year = 1308 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 52000 }
		secondary = { type = 10 id = 71662 }
		startdate = { year = 1259 month = january day = 1 }
		enddate = { year = 1302 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 52510 }
		secondary = { type = 10 id = 52511 }
		startdate = { year = 1298 month = january day = 1 }
		enddate = { year = 1333 month = march day = 13 }
	}
	marrige = { 
		primary = { type = 10 id = 52600 }
		secondary = { type = 10 id = 52601 }
		startdate = { year = 1298 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 52610 }
		secondary = { type = 10 id = 52611 }
		startdate = { year = 1290 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 52612 }
		secondary = { type = 10 id = 52613 }
		startdate = { year = 1337 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 52620 }
		secondary = { type = 10 id = 52605 }
		startdate = { year = 1324 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 53003 }
		secondary = { type = 10 id = 53054 }
		startdate = { year = 1336 month = july day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 53004 }
		secondary = { type = 10 id = 53057 }
		startdate = { year = 1336 month = july day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 53005 }
		secondary = { type = 10 id = 53043 }
		startdate = { year = 1310 month = july day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 53009 }
		secondary = { type = 10 id = 53076 }
		startdate = { year = 1315 month = july day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 53010 }
		secondary = { type = 10 id = 53067 }
		startdate = { year = 1310 month = july day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 53014 }
		secondary = { type = 10 id = 53062 }
		startdate = { year = 1330 month = july day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53020 }
		secondary = { type = 10 id = 53021 }
		startdate = { year = 1329 month = january day = 1 }
		enddate = { year = 1332 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53022 }
		secondary = { type = 10 id = 53513 }
		startdate = { year = 1292 month = january day = 1 }
		enddate = { year = 1305 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53027 }
		secondary = { type = 10 id = 53031 }
		startdate = { year = 1328 month = october day = 24 }
		enddate = { year = 1331 month = november day = 24 }
	}
	marrige = {
		primary = { type = 10 id = 53030 }
		secondary = { type = 10 id = 53602 }
		startdate = { year = 1240 month = october day = 24 }
		enddate = { year = 1275 month = november day = 24 }
	}
	marrige = {
		primary = { type = 10 id = 53033 }
		secondary = { type = 10 id = 53504 }
		startdate = { year = 1315 month = october day = 24 }
		enddate = { year = 1316 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 53034 }
		secondary = { type = 10 id = 53035 }
		startdate = { year = 1330 month = october day = 24 }
	}
	marrige = {
		primary = { type = 10 id = 53037 }
		secondary = { type = 10 id = 53025 }
		startdate = { year = 1315 month = october day = 24 }
		enddate = { year = 1330 month = july day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53038 }
		secondary = { type = 10 id = 53025 }
		startdate = { year = 1290 month = january day = 1 }
		enddate = { year = 1307 month = july day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53039 }
		secondary = { type = 10 id = 53040 }
		startdate = { year = 1307 month = january day = 1 }
		enddate = { year = 1326 month = december day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53041 }
		secondary = { type = 10 id = 53042 }
		startdate = { year = 1330 month = january day = 1 }
		enddate = { year = 1335 month = december day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53044 }
		secondary = { type = 10 id = 53045 }
		startdate = { year = 1260 month = january day = 1 }
		enddate = { year = 1270 month = december day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 53046 }
		secondary = { type = 10 id = 54533 }
		startdate = { year = 1336 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53052 }
		secondary = { type = 10 id = 53514 }
		startdate = { year = 1308 month = january day = 1 }
		enddate = { year = 1329 month = december day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53052 }
		secondary = { type = 10 id = 53070 }
		startdate = { year = 1330 month = january day = 1 }
		enddate = { year = 1333 month = december day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53058 }
		secondary = { type = 10 id = 53059 }
		startdate = { year = 1308 month = january day = 1 }
		enddate = { year = 1332 month = december day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53060 }
		secondary = { type = 10 id = 53061 }
		startdate = { year = 1280 month = january day = 1 }
		enddate = { year = 1292 month = december day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53063 }
		secondary = { type = 10 id = 53064 }
		startdate = { year = 1280 month = january day = 1 }
		enddate = { year = 1308 month = october day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53065 }
		secondary = { type = 10 id = 53066 }
		startdate = { year = 1280 month = january day = 1 }
		enddate = { year = 1288 month = october day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53071 }
		secondary = { type = 10 id = 53072 }
		startdate = { year = 1306 month = january day = 1 }
		enddate = { year = 1312 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53071 }
		secondary = { type = 10 id = 53073 }
		startdate = { year = 1312 month = march day = 1 }
		enddate = { year = 1316 month = october day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53401 }
		secondary = { type = 10 id = 53402 }
		startdate = { year = 1317 month = march day = 1 }
		enddate = { year = 1325 month = october day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 53500 }
		secondary = { type = 10 id = 54506 }
		startdate = { year = 1328 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 53501 }
		secondary = { type = 10 id = 53502 }
		startdate = { year = 1302 month = march day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53501 }
		secondary = { type = 10 id = 53024 }
		startdate = { year = 1295 month = january day = 1 }
		enddate = { year = 1302 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53515 }
		secondary = { type = 10 id = 53516 }
		startdate = { year = 1300 month = january day = 1 }
		enddate = { year = 1316 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53517 }
		secondary = { type = 10 id = 53518 }
		startdate = { year = 1320 month = january day = 1 }
		enddate = { year = 1333 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 53520 }
		secondary = { type = 10 id = 53521 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53600 }
		secondary = { type = 10 id = 53601 }
		startdate = { year = 1275 month = january day = 1 }
		enddate = { year = 1288 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53600 }
		secondary = { type = 10 id = 53604 }
		startdate = { year = 1288 month = january day = 1 }
		enddate = { year = 1298 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 53608 }
		secondary = { type = 10 id = 53609 }
		startdate = { year = 1314 month = january day = 1 }
		enddate = { year = 1333 month = july day = 19 }
	}
	marrige = { 
		primary = { type = 10 id = 54023 }
		secondary = { type = 10 id = 54042 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54030 }
		secondary = { type = 10 id = 54031 }
		startdate = { year = 1315 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54040 }
		secondary = { type = 10 id = 54041 }
		startdate = { year = 1270 month = january day = 1 }
		enddate = { year = 1310 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54043 }
		secondary = { type = 10 id = 54044 }
		startdate = { year = 1247 month = january day = 1 }
		enddate = { year = 1257 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54045 }
		secondary = { type = 10 id = 54046 }
		startdate = { year = 1222 month = january day = 1 }
		enddate = { year = 1240 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54048 }
		secondary = { type = 10 id = 54047 }
		startdate = { year = 1237 month = january day = 1 }
		enddate = { year = 1262 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54049 }
		secondary = { type = 10 id = 54050 }
		startdate = { year = 1308 month = january day = 1 }
		enddate = { year = 1314 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54051 }
		secondary = { type = 10 id = 54054 }
		startdate = { year = 1316 month = january day = 1 }
		enddate = { year = 1325 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54051 }
		secondary = { type = 10 id = 54607 }
		startdate = { year = 1328 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54101 }
		secondary = { type = 10 id = 54102 }
		startdate = { year = 1310 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54104 }
		secondary = { type = 10 id = 54107 }
		startdate = { year = 1329 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54106 }
		secondary = { type = 10 id = 54108 }
		startdate = { year = 1275 month = january day = 1 }
		enddate = { year = 1304 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54110 }
		secondary = { type = 10 id = 54564 }
		startdate = { year = 1327 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54111 }
		secondary = { type = 10 id = 54112 }
		startdate = { year = 1302 month = january day = 1 }
		enddate = { year = 1321 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54121 }
		secondary = { type = 10 id = 54107 }
		startdate = { year = 1312 month = january day = 1 }
		enddate = { year = 1328 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54130 }
		secondary = { type = 10 id = 54131 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54160 }
		secondary = { type = 10 id = 54164 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54201 }
		secondary = { type = 10 id = 54202 }
		startdate = { year = 1336 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54205 }
		secondary = { type = 10 id = 54141 }
		startdate = { year = 1309 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54210 }
		secondary = { type = 10 id = 54211 }
		startdate = { year = 1315 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54500 }
		secondary = { type = 10 id = 55611 }
		startdate = { year = 1328 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54510 }
		secondary = { type = 10 id = 55525 }
		startdate = { year = 1310 month = january day = 1 }
		enddate = { year = 1327 month = july day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 54520 }
		secondary = { type = 10 id = 55527 }
		startdate = { year = 1299 month = january day = 1 }
		enddate = { year = 1307 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54523 }
		secondary = { type = 10 id = 54524 }
		startdate = { year = 1276 month = january day = 1 }
		enddate = { year = 1296 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54525 }
		secondary = { type = 10 id = 54526 }
		startdate = { year = 1297 month = january day = 1 }
		enddate = { year = 1317 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54525 }
		secondary = { type = 10 id = 54535 }
		startdate = { year = 1334 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54527 }
		secondary = { type = 10 id = 54528 }
		startdate = { year = 1334 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54550 }
		secondary = { type = 10 id = 54551 }
		startdate = { year = 1319 month = january day = 1 }
		enddate = { year = 1326 month = july day = 14 }
	}
	marrige = { 
		primary = { type = 10 id = 54550 }
		secondary = { type = 10 id = 54554 }
		startdate = { year = 1328 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54561 }
		secondary = { type = 10 id = 54516 }
		startdate = { year = 1302 month = january day = 1 }
		enddate = { year = 1316 month = july day = 14 }
	}
	marrige = { 
		primary = { type = 10 id = 54562 }
		secondary = { type = 10 id = 54563 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54571 }
		secondary = { type = 10 id = 54572 }
		startdate = { year = 1305 month = january day = 1 }
		enddate = { year = 1326 month = july day = 14 }
	}
	marrige = { 
		primary = { type = 10 id = 54570 }
		secondary = { type = 10 id = 54573 }
		startdate = { year = 1321 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54577 }
		secondary = { type = 10 id = 54578 }
		startdate = { year = 1308 month = january day = 1 }
		enddate = { year = 1328 month = july day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 54579 }
		secondary = { type = 10 id = 54580 }
		startdate = { year = 1280 month = january day = 1 }
		enddate = { year = 1286 month = july day = 14 }
	}
	marrige = { 
		primary = { type = 10 id = 54581 }
		secondary = { type = 10 id = 54582 }
		startdate = { year = 1306 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54584 }
		secondary = { type = 10 id = 54585 }
		startdate = { year = 1306 month = january day = 1 }
		enddate = { year = 1319 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54586 }
		secondary = { type = 10 id = 54587 }
		startdate = { year = 1336 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54590 }
		secondary = { type = 10 id = 54591 }
		startdate = { year = 1310 month = january day = 1 }
		enddate = { year = 1315 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54592 }
		secondary = { type = 10 id = 54593 }
		startdate = { year = 1336 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54594 }
		secondary = { type = 10 id = 54565 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54600 }
		secondary = { type = 10 id = 54601 }
		startdate = { year = 1300 month = january day = 1 }
		enddate = { year = 1314 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54606 }
		secondary = { type = 10 id = 54605 }
		startdate = { year = 1290 month = january day = 1 }
		enddate = { year = 1295 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54610 }
		secondary = { type = 10 id = 54608 }
		startdate = { year = 1317 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54612 }
		secondary = { type = 10 id = 54609 }
		startdate = { year = 1308 month = january day = 1 }
		enddate = { year = 1314 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 54613 }
		secondary = { type = 10 id = 54531 }
		startdate = { year = 1330 month = january day = 1 }
		enddate = { year = 1333 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 54980 }
		secondary = { type = 10 id = 62031 }
		startdate = { year = 1336 month = december day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 54990 }
		secondary = { type = 10 id = 55790 }
		startdate = { year = 1311 month = january day = 1 }
		enddate = { year = 1335 month = march day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 54991 }
		secondary = { type = 10 id = 54992 }
		startdate = { year = 1269 month = january day = 1 }
		enddate = { year = 1312 month = august day = 23 }
	}
	marrige = {
		primary = { type = 10 id = 54994 }
		secondary = { type = 10 id = 54993 }
		startdate = { year = 1288 month = january day = 1 }
		enddate = { year = 1304 month = december day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 54998 }
		secondary = { type = 10 id = 54999 }
		startdate = { year = 1323 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55009 }
		secondary = { type = 10 id = 55010 }
		startdate = { year = 1295 month = january day = 1 }
		enddate = { year = 1315 month = december day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 55006 }
		secondary = { type = 10 id = 55756 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55400 }
		secondary = { type = 10 id = 55401 }
		startdate = { year = 1180 month = january day = 1 }
		enddate = { year = 1190 month = december day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 55402 }
		secondary = { type = 10 id = 55403 }
		startdate = { year = 1200 month = january day = 1 }
		enddate = { year = 1226 month = december day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 55404 }
		secondary = { type = 10 id = 55409 }
		startdate = { year = 1234 month = january day = 1 }
		enddate = { year = 1270 month = december day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 55405 }
		secondary = { type = 10 id = 55408 }
		startdate = { year = 1237 month = january day = 1 }
		enddate = { year = 1250 month = december day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 55406 }
		secondary = { type = 10 id = 55407 }
		startdate = { year = 1246 month = january day = 1 }
		enddate = { year = 1267 month = december day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 55413 }
		secondary = { type = 10 id = 55411 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55414 }
		secondary = { type = 10 id = 55418 }
		startdate = { year = 1325 month = january day = 1 }
		enddate = { year = 1327 month = december day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 55432 }
		secondary = { type = 10 id = 55433 }
		startdate = { year = 1325 month = january day = 1 }
		enddate = { year = 1329 month = december day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 55432 }
		secondary = { type = 10 id = 55465 }
		startdate = { year = 1330 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55450 }
		secondary = { type = 10 id = 55451 }
		startdate = { year = 1321 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55455 }
		secondary = { type = 10 id = 55456 }
		startdate = { year = 1284 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55500 }
		secondary = { type = 10 id = 55532 }
		startdate = { year = 1329 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55502 }
		secondary = { type = 10 id = 62600 }
		startdate = { year = 1332 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55505 }
		secondary = { type = 10 id = 55533 }
		startdate = { year = 1278 month = january day = 1 }
		enddate = { year = 1310 month = december day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 55512 }
		secondary = { type = 10 id = 55805 }
		startdate = { year = 1290 month = january day = 1 }
		enddate = { year = 1325 month = december day = 14 }
	}
	marrige = { 
		primary = { type = 10 id = 55515 }
		secondary = { type = 10 id = 55501 }
		startdate = { year = 1317 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55516 }
		secondary = { type = 10 id = 55517 }
		startdate = { year = 1285 month = january day = 1 }
		enddate = { year = 1298 month = september day = 11 }
	}
	marrige = {
		primary = { type = 10 id = 55526 }
		secondary = { type = 10 id = 55531 }
		startdate = { year = 1284 month = january day = 1 }
		enddate = { year = 1305 month = june day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 55528 }
		secondary = { type = 10 id = 55529 }
		startdate = { year = 1262 month = january day = 1 }
		enddate = { year = 1271 month = june day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 55528 }
		secondary = { type = 10 id = 55530 }
		startdate = { year = 1274 month = january day = 1 }
		enddate = { year = 1285 month = june day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 55535 }
		secondary = { type = 10 id = 55830 }
		startdate = { year = 1287 month = january day = 1 }
		enddate = { year = 1306 month = june day = 8 }
	}
	marrige = { 
		primary = { type = 10 id = 55540 }
		secondary = { type = 10 id = 55551 }
		startdate = { year = 1331 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55544 }
		secondary = { type = 10 id = 55545 }
		startdate = { year = 1301 month = january day = 1 }
		enddate = { year = 1315 month = june day = 8 }
	}
	marrige = {
		primary = { type = 10 id = 55546 }
		secondary = { type = 10 id = 55547 }
		startdate = { year = 1260 month = january day = 1 }
		enddate = { year = 1275 month = june day = 8 }
	}
	marrige = { 
		primary = { type = 10 id = 55560 }
		secondary = { type = 10 id = 55562 }
		startdate = { year = 1337 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55561 }
		secondary = { type = 10 id = 55543 }
		startdate = { year = 1318 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55630 }
		secondary = { type = 10 id = 55605 }
		startdate = { year = 1311 month = january day = 1 }
		enddate = { year = 1320 month = december day = 12 }
	}
	marrige = { 
		primary = { type = 10 id = 55631 }
		secondary = { type = 10 id = 55632 }
		startdate = { year = 1294 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55640 }
		secondary = { type = 10 id = 55725 }
		startdate = { year = 1327 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55641 }
		secondary = { type = 10 id = 55715 }
		startdate = { year = 1301 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55650 }
		secondary = { type = 10 id = 55615 }
		startdate = { year = 1310 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55651 }
		secondary = { type = 10 id = 55506 }
		startdate = { year = 1336 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55656 }
		secondary = { type = 10 id = 55705 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55670 }
		secondary = { type = 10 id = 55652 }
		startdate = { year = 1324 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55680 }
		secondary = { type = 10 id = 55653 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55681 }
		secondary = { type = 10 id = 55011 }
		startdate = { year = 1309 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55710 }
		secondary = { type = 10 id = 55508 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55711 }
		secondary = { type = 10 id = 55720 }
		startdate = { year = 1303 month = january day = 1 }
		enddate = { year = 1322 month = march day = 12 }
	}
	marrige = { 
		primary = { type = 10 id = 55730 }
		secondary = { type = 10 id = 55732 }
		startdate = { year = 1316 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55740 }
		secondary = { type = 10 id = 55733 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55742 }
		secondary = { type = 10 id = 55737 }
		startdate = { year = 1334 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55750 }
		secondary = { type = 10 id = 55510 }
		startdate = { year = 1298 month = january day = 1 }
		enddate = { year = 1309 month = march day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 55750 }
		secondary = { type = 10 id = 57676 }
		startdate = { year = 1310 month = january day = 1 }
		enddate = { year = 1328 month = march day = 12 }
	}
	marrige = { 
		primary = { type = 10 id = 55750 }
		secondary = { type = 10 id = 62152 }
		startdate = { year = 1329 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55751 }
		secondary = { type = 10 id = 55590 }
		startdate = { year = 1285 month = january day = 1 }
		enddate = { year = 1291 month = may day = 25 }
	}
	marrige = { 
		primary = { type = 10 id = 55754 }
		secondary = { type = 10 id = 55770 }
		startdate = { year = 1318 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55755 }
		secondary = { type = 10 id = 55714 }
		startdate = { year = 1329 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55760 }
		secondary = { type = 10 id = 55766 }
		startdate = { year = 1334 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55761 }
		secondary = { type = 10 id = 55762 }
		startdate = { year = 1310 month = january day = 1 }
		enddate = { year = 1336 month = may day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 55763 }
		secondary = { type = 10 id = 55764 }
		startdate = { year = 1293 month = january day = 1 }
		enddate = { year = 1297 month = may day = 25 }
	}
	marrige = { 
		primary = { type = 10 id = 55777 }
		secondary = { type = 10 id = 55779 }
		startdate = { year = 1336 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55781 }
		secondary = { type = 10 id = 55511 }
		startdate = { year = 1311 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55782 }
		secondary = { type = 10 id = 55713 }
		startdate = { year = 1297 month = january day = 1 }
		enddate = { year = 1303 month = march day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 55787 }
		secondary = { type = 10 id = 55788 }
		startdate = { year = 1292 month = january day = 1 }
		enddate = { year = 1317 month = march day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 55789 }
		secondary = { type = 10 id = 55791 }
		startdate = { year = 1260 month = january day = 1 }
		enddate = { year = 1275 month = march day = 3 }
	}
	marrige = { 
		primary = { type = 10 id = 55810 }
		secondary = { type = 10 id = 55835 }
		startdate = { year = 1129 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55811 }
		secondary = { type = 10 id = 55825 }
		startdate = { year = 1300 month = january day = 1 }
		enddate = { year = 1311 month = september day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 55821 }
		secondary = { type = 10 id = 55822 }
		startdate = { year = 1320 month = january day = 1 }
		enddate = { year = 1132 month = june day = 15 }
	}
	marrige = {
		primary = { type = 10 id = 55836 }
		secondary = { type = 10 id = 55536 }
		startdate = { year = 1310 month = january day = 1 }
		enddate = { year = 1315 month = march day = 18 }
	}
	marrige = { 
		primary = { type = 10 id = 55850 }
		secondary = { type = 10 id = 55851 }
		startdate = { year = 1310 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 55910 }
		secondary = { type = 10 id = 555508 }
		startdate = { year = 1337 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55931 }
		secondary = { type = 10 id = 55932 }
		startdate = { year = 1306 month = january day = 1 }
		enddate = { year = 1327 month = january day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 55928 }
		secondary = { type = 10 id = 55929 }
		startdate = { year = 1280 month = january day = 1 }
		enddate = { year = 1308 month = january day = 28 }
	}
	marrige = { 
		primary = { type = 10 id = 55930 }
		secondary = { type = 10 id = 55933 }
		startdate = { year = 1329 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 55940 }
		secondary = { type = 10 id = 55941 }
		startdate = { year = 1314 month = january day = 1 }
		enddate = { year = 1321 month = january day = 28 }
	}
	marrige = { 
		primary = { type = 10 id = 56550 }
		secondary = { type = 10 id = 54505 }
		startdate = { year = 1332 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 56550 }
		secondary = { type = 10 id = 56558 }
		startdate = { year = 1311 month = january day = 1 }
		enddate = { year = 1329 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 56553 }
		secondary = { type = 10 id = 56554 }
		startdate = { year = 1286 month = january day = 1 }
		enddate = { year = 1326 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 57020 }
		secondary = { type = 10 id = 57021 }
		startdate = { year = 1306 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 57500 }
		secondary = { type = 10 id = 59502 }
		startdate = { year = 1328 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 57500 }
		secondary = { type = 10 id = 57631 }
		startdate = { year = 1325 month = january day = 1 }
		enddate = { year = 1327 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 57520 }
		secondary = { type = 10 id = 59511 }
		startdate = { year = 1302 month = january day = 1 }
		enddate = { year = 1312 month = september day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 57530 }
		secondary = { type = 10 id = 57666 }
		startdate = { year = 1281 month = january day = 1 }
		enddate = { year = 1295 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 57531 }
		secondary = { type = 10 id = 60563 }
		startdate = { year = 1311 month = december day = 17 }
		enddate = { year = 1319 month = june day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 57540 }
		secondary = { type = 10 id = 60611 }
		startdate = { year = 1248 month = january day = 1 }
		enddate = { year = 1284 month = april day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 57541 }
		secondary = { type = 10 id = 55422 }
		startdate = { year = 1268 month = january day = 1 }
		enddate = { year = 1275 month = april day = 4 }
	}
	marrige = { 
		primary = { type = 10 id = 57550 }
		secondary = { type = 10 id = 58009 }
		startdate = { year = 1306 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 57555 }
		secondary = { type = 10 id = 59515 }
		startdate = { year = 1318 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 57556 }
		secondary = { type = 10 id = 57557 }
		startdate = { year = 1325 month = january day = 1 }
		enddate = { year = 1327 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 57562 }
		secondary = { type = 10 id = 57683 }
		startdate = { year = 1303 month = january day = 1 }
		enddate = { year = 1313 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 57580 }
		secondary = { type = 10 id = 57680 }
		startdate = { year = 1308 month = january day = 1 }
		enddate = { year = 1322 month = june day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 57581 }
		secondary = { type = 10 id = 57610 }
		startdate = { year = 1331 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 57590 }
		secondary = { type = 10 id = 59504 }
		startdate = { year = 1336 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 57611 }
		secondary = { type = 10 id = 59524 }
		startdate = { year = 1318 month = january day = 1 }
		enddate = { year = 1326 month = december day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 57621 }
		secondary = { type = 10 id = 60612 }
		startdate = { year = 1260 month = january day = 1 }
		enddate = { year = 1269 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 57630 }
		secondary = { type = 10 id = 60609 }
		startdate = { year = 1299 month = january day = 1 }
		enddate = { year = 1301 month = october day = 10 }
	}
	marrige = { 
		primary = { type = 10 id = 57633 }
		secondary = { type = 10 id = 57634 }
		startdate = { year = 1315 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 57650 }
		secondary = { type = 10 id = 57651 }
		startdate = { year = 1197 month = january day = 1 }
		enddate = { year = 1204 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 57660 }
		secondary = { type = 10 id = 57661 }
		startdate = { year = 1246 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 57663 }
		secondary = { type = 10 id = 59525 }
		startdate = { year = 1337 month = january day = 1 }
		enddate = { year = 1315 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 57670 }
		secondary = { type = 10 id = 57671 }
		startdate = { year = 1337 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 57681 }
		secondary = { type = 10 id = 57682 }
		startdate = { year = 1337 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 58007 }
		secondary = { type = 10 id = 58008 }
		startdate = { year = 1286 month = january day = 1 }
		enddate = { year = 1335 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 58020 }
		secondary = { type = 10 id = 58010 }
		startdate = { year = 1309 month = january day = 1 }
		enddate = { year = 1331 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 58021 }
		secondary = { type = 10 id = 58024 }
		startdate = { year = 1325 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 59501 }
		secondary = { type = 10 id = 57532 }
		startdate = { year = 1325 month = january day = 1 }
		enddate = { year = 1330 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 59510 }
		secondary = { type = 10 id = 60591 }
		startdate = { year = 1282 month = june day = 24 }
		enddate = { year = 1325 month = january day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 59512 }
		secondary = { type = 10 id = 59513 }
		startdate = { year = 1304 month = january day = 1 }
		enddate = { year = 1329 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 59514 }
		secondary = { type = 10 id = 57665 }
		startdate = { year = 1319 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 59520 }
		secondary = { type = 10 id = 59521 }
		startdate = { year = 1235 month = january day = 1 }
		enddate = { year = 1253 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 59523 }
		secondary = { type = 10 id = 57622 }
		startdate = { year = 1287 month = january day = 1 }
		enddate = { year = 1312 month = january day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 59530 }
		secondary = { type = 10 id = 59531 }
		startdate = { year = 1278 month = january day = 1 }
		enddate = { year = 1310 month = april day = 24 }
	}
	marrige = { 
		primary = { type = 10 id = 59532 }
		secondary = { type = 10 id = 59533 }
		startdate = { year = 1330 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 59538 }
		secondary = { type = 10 id = 59539 }
		startdate = { year = 1328 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 59550 }
		secondary = { type = 10 id = 59551 }
		startdate = { year = 1270 month = january day = 1 }
		enddate = { year = 1299 month = november day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 59552 }
		secondary = { type = 10 id = 59553 }
		startdate = { year = 1315 month = january day = 1 }
		enddate = { year = 1323 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 59560 }
		secondary = { type = 10 id = 59561 }
		startdate = { year = 1206 month = january day = 1 }
		enddate = { year = 1220 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 60011 }
		secondary = { type = 10 id = 60012 }
		startdate = { year = 1331 month = november day = 10 }
	}
	marrige = { 
		primary = { type = 10 id = 60024 }
		secondary = { type = 10 id = 60030 }
		startdate = { year = 1322 month = november day = 10 }
	}
	marrige = {
		primary = { type = 10 id = 60510 }
		secondary = { type = 10 id = 60511 }
		startdate = { year = 1314 month = november day = 10 }
		enddate = { year = 1327 month = october day = 28 }
	}
	marrige = { 
		primary = { type = 10 id = 60520 }
		secondary = { type = 10 id = 55556 }
		startdate = { year = 1336 month = november day = 10 }
	}
	marrige = {
		primary = { type = 10 id = 60560 }
		secondary = { type = 10 id = 57533 }
		startdate = { year = 1291 month = december day = 1 }
		enddate = { year = 1295 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 60560 }
		secondary = { type = 10 id = 61727 }
		startdate = { year = 1295 month = october day = 29 }
		enddate = { year = 1310 month = october day = 14 }
	}
	marrige = { 
		primary = { type = 10 id = 60580 }
		secondary = { type = 10 id = 61715 }
		startdate = { year = 1327 month = october day = 29 }
	}
	marrige = {
		primary = { type = 10 id = 60590 }
		secondary = { type = 10 id = 62515 }
		startdate = { year = 1262 month = june day = 13 }
		enddate = { year = 1285 month = november day = 11 }
	}
	marrige = {
		primary = { type = 10 id = 60600 }
		secondary = { type = 10 id = 60614 }
		startdate = { year = 1221 month = june day = 6 }
		enddate = { year = 1029 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 60605 }
		secondary = { type = 10 id = 60606 }
		startdate = { year = 1314 month = january day = 17 }
		enddate = { year = 1315 month = may day = 7 }
	}
	marrige = { 
		primary = { type = 10 id = 60620 }
		secondary = { type = 10 id = 60550 }
		startdate = { year = 1336 month = september day = 24 }
	}
	marrige = { 
		primary = { type = 10 id = 61500 }
		secondary = { type = 10 id = 55806 }
		startdate = { year = 1300 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 61502 }
		secondary = { type = 10 id = 62715 }
		startdate = { year = 1337 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 61510 }
		secondary = { type = 10 id = 61511 }
		startdate = { year = 1135 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 61520 }
		secondary = { type = 10 id = 61521 }
		startdate = { year = 1337 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 61550 }
		secondary = { type = 10 id = 61571 }
		startdate = { year = 1317 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 61700 }
		secondary = { type = 10 id = 60592 }
		startdate = { year = 1297 month = march day = 23 }
		enddate = { year = 1302 month = august day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 61701 }
		secondary = { type = 10 id = 61702 }
		startdate = { year = 1324 month = january day = 11 }
		enddate = { year = 1328 month = november day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 61710 }
		secondary = { type = 10 id = 61711 }
		startdate = { year = 1270 month = january day = 1 }
		enddate = { year = 1309 month = may day = 6 }
	}
	marrige = {
		primary = { type = 10 id = 61712 }
		secondary = { type = 10 id = 61713 }
		startdate = { year = 1295 month = january day = 1 }
		enddate = { year = 1309 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 61712 }
		secondary = { type = 10 id = 61717 }
		startdate = { year = 1313 month = july day = 13 }
		enddate = { year = 1332 month = december day = 26 }
	}
	marrige = {
		primary = { type = 10 id = 61721 }
		secondary = { type = 10 id = 61722 }
		startdate = { year = 1321 month = january day = 1 }
		enddate = { year = 1336 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 61730 }
		secondary = { type = 10 id = 61714 }
		startdate = { year = 1325 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 61731 }
		secondary = { type = 10 id = 55778 }
		startdate = { year = 1305 month = january day = 1 }
		enddate = { year = 1311 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 61742 }
		secondary = { type = 10 id = 57652 }
		startdate = { year = 1224 month = january day = 1 }
		enddate = { year = 1237 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 61800 }
		secondary = { type = 10 id = 61798 }
		startdate = { year = 1321 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 61800 }
		secondary = { type = 10 id = 61509 }
		startdate = { year = 1333 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 61900 }
		secondary = { type = 10 id = 61901 }
		startdate = { year = 1307 month = january day = 1 }
		enddate = { year = 1318 month = may day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 61801 }
		secondary = { type = 10 id = 61914 }
		startdate = { year = 1288 month = june day = 18 }
		enddate = { year = 1296 month = march day = 24 }
	}
	marrige = { 
		primary = { type = 10 id = 61900 }
		secondary = { type = 10 id = 61902 }
		startdate = { year = 1318 month = june day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 61903 }
		secondary = { type = 10 id = 61904 }
		startdate = { year = 1291 month = december day = 7 }
		enddate = { year = 1303 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 61905 }
		secondary = { type = 10 id = 61906 }
		startdate = { year = 1255 month = december day = 7 }
		enddate = { year = 1284 month = march day = 24 }
	}
	marrige = { 
		primary = { type = 10 id = 61907 }
		secondary = { type = 10 id = 55654 }
		startdate = { year = 1328 month = january day = 7 }
	}
	marrige = {
		primary = { type = 10 id = 61916 }
		secondary = { type = 10 id = 61917 }
		startdate = { year = 1292 month = january day = 7 }
		enddate = { year = 1310 month = may day = 6 }
	}
	marrige = { 
		primary = { type = 10 id = 61918 }
		secondary = { type = 10 id = 61919 }
		startdate = { year = 1332 month = january day = 7 }
	}
	marrige = { 
		primary = { type = 10 id = 61921 }
		secondary = { type = 10 id = 61922 }
		startdate = { year = 1336 month = january day = 7 }
	}
	marrige = { 
		primary = { type = 10 id = 62020 }
		secondary = { type = 10 id = 62033 }
		startdate = { year = 1324 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62021 }
		secondary = { type = 10 id = 62022 }
		startdate = { year = 1245 month = january day = 1 }
		enddate = { year = 1281 month = march day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62023 }
		secondary = { type = 10 id = 62713 }
		startdate = { year = 1280 month = january day = 1 }
		enddate = { year = 1308 month = may day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62024 }
		secondary = { type = 10 id = 60565 }
		startdate = { year = 1315 month = january day = 1 }
		enddate = { year = 1330 month = january day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 62029 }
		secondary = { type = 10 id = 62030 }
		startdate = { year = 1319 month = january day = 1 }
		enddate = { year = 1326 month = february day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 62035 }
		secondary = { type = 10 id = 62036 }
		startdate = { year = 1325 month = january day = 1 }
		enddate = { year = 1330 month = march day = 25 }
	}
	marrige = { 
		primary = { type = 10 id = 62035 }
		secondary = { type = 10 id = 62617 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62048 }
		secondary = { type = 10 id = 62049 }
		startdate = { year = 1265 month = january day = 1 }
		enddate = { year = 1330 month = january day = 17 }
	}
	marrige = { 
		primary = { type = 10 id = 62050 }
		secondary = { type = 10 id = 62051 }
		startdate = { year = 1317 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62052 }
		secondary = { type = 10 id = 62053 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62090 }
		secondary = { type = 10 id = 62091 }
		startdate = { year = 1270 month = january day = 1 }
		enddate = { year = 1288 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62092 }
		secondary = { type = 10 id = 62093 }
		startdate = { year = 1294 month = january day = 1 }
		enddate = { year = 1335 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62094 }
		secondary = { type = 10 id = 62095 }
		startdate = { year = 1324 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62100 }
		secondary = { type = 10 id = 62102 }
		startdate = { year = 1298 month = january day = 1 }
		enddate = { year = 1328 month = may day = 9 }
	}
	marrige = {
		primary = { type = 10 id = 62100 }
		secondary = { type = 10 id = 71502 }
		startdate = { year = 1329 month = january day = 1 }
		enddate = { year = 1331 month = april day = 9 }
	}
	marrige = { 
		primary = { type = 10 id = 62100 }
		secondary = { type = 10 id = 62108 }
		startdate = { year = 1333 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62101 }
		secondary = { type = 10 id = 62062 }
		startdate = { year = 1273 month = january day = 1 }
		enddate = { year = 1298 month = august day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 62120 }
		secondary = { type = 10 id = 51526 }
		startdate = { year = 1258 month = january day = 1 }
		enddate = { year = 1284 month = august day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 62124 }
		secondary = { type = 10 id = 50509 }
		startdate = { year = 1259 month = january day = 1 }
		enddate = { year = 1300 month = august day = 25 }
	}
	marrige = { 
		primary = { type = 10 id = 62126 }
		secondary = { type = 10 id = 62106 }
		startdate = { year = 1336 month = december day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62130 }
		secondary = { type = 10 id = 62129 }
		startdate = { year = 1333 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62133 }
		secondary = { type = 10 id = 62134 }
		startdate = { year = 1327 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62140 }
		secondary = { type = 10 id = 62142 }
		startdate = { year = 1309 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62143 }
		secondary = { type = 10 id = 55743 }
		startdate = { year = 1329 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62150 }
		secondary = { type = 10 id = 62680 }
		startdate = { year = 1289 month = january day = 1 }
		enddate = { year = 1294 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62150 }
		secondary = { type = 10 id = 87055 }
		startdate = { year = 1297 month = january day = 1 }
		enddate = { year = 1323 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62153 }
		secondary = { type = 10 id = 55534 }
		startdate = { year = 1307 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62154 }
		secondary = { type = 10 id = 62670 }
		startdate = { year = 1332 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62159 }
		secondary = { type = 10 id = 62141 }
		startdate = { year = 1278 month = january day = 1 }
		enddate = { year = 1300 month = january day = 13 }
	}
	marrige = {
		primary = { type = 10 id = 62160 }
		secondary = { type = 10 id = 62161 }
		startdate = { year = 1299 month = january day = 1 }
		enddate = { year = 1331 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62162 }
		secondary = { type = 10 id = 62163 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62164 }
		secondary = { type = 10 id = 56560 }
		startdate = { year = 1336 month = november day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62165 }
		secondary = { type = 10 id = 62166 }
		startdate = { year = 1324 month = january day = 1 }
		enddate = { year = 1334 month = march day = 3 }
	}
	marrige = { 
		primary = { type = 10 id = 62171 }
		secondary = { type = 10 id = 62172 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62300 }
		secondary = { type = 10 id = 62301 }
		startdate = { year = 1295 month = january day = 1 }
		enddate = { year = 1320 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62302 }
		secondary = { type = 10 id = 62303 }
		startdate = { year = 1312 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62310 }
		secondary = { type = 10 id = 62311 }
		startdate = { year = 1326 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62322 }
		secondary = { type = 10 id = 62323 }
		startdate = { year = 1285 month = january day = 1 }
		enddate = { year = 1310 month = august day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 62324 }
		secondary = { type = 10 id = 62325 }
		startdate = { year = 1309 month = january day = 1 }
		enddate = { year = 1327 month = august day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 62324 }
		secondary = { type = 10 id = 62331 }
		startdate = { year = 1329 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62326 }
		secondary = { type = 10 id = 62327 }
		startdate = { year = 1327 month = january day = 1 }
		enddate = { year = 1331 month = august day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 62326 }
		secondary = { type = 10 id = 62329 }
		startdate = { year = 1334 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62335 }
		secondary = { type = 10 id = 62336 }
		startdate = { year = 1288 month = january day = 1 }
		enddate = { year = 1296 month = august day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 62337 }
		secondary = { type = 10 id = 62333 }
		startdate = { year = 1308 month = january day = 1 }
		enddate = { year = 1320 month = august day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 62352 }
		secondary = { type = 10 id = 62317 }
		startdate = { year = 1296 month = january day = 1 }
		enddate = { year = 1320 month = august day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 62360 }
		secondary = { type = 10 id = 62361 }
		startdate = { year = 1271 month = january day = 1 }
		enddate = { year = 1298 month = august day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 62362 }
		secondary = { type = 10 id = 62363 }
		startdate = { year = 1307 month = january day = 1 }
		enddate = { year = 1332 month = january day = 13 }
	}
	marrige = { 
		primary = { type = 10 id = 62362 }
		secondary = { type = 10 id = 62373 }
		startdate = { year = 1336 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62364 }
		secondary = { type = 10 id = 87027 }
		startdate = { year = 1332 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62366 }
		secondary = { type = 10 id = 62367 }
		startdate = { year = 1333 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62380 }
		secondary = { type = 10 id = 62381 }
		startdate = { year = 1310 month = january day = 1 }
		enddate = { year = 1319 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62380 }
		secondary = { type = 10 id = 62383 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62390 }
		secondary = { type = 10 id = 62391 }
		startdate = { year = 1324 month = january day = 1 }
		enddate = { year = 1336 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62390 }
		secondary = { type = 10 id = 62396 }
		startdate = { year = 1330 month = january day = 5 }
	}
	marrige = { 
		primary = { type = 10 id = 62400 }
		secondary = { type = 10 id = 62732 }
		startdate = { year = 1323 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62550 }
		secondary = { type = 10 id = 54521 }
		startdate = { year = 1329 month = january day = 1 }
		enddate = { year = 1332 month = june day = 23 }
	}
	marrige = {
		primary = { type = 10 id = 62550 }
		secondary = { type = 10 id = 55785 }
		startdate = { year = 1329 month = january day = 1 }
		enddate = { year = 1334 month = june day = 23 }
	}
	marrige = {
		primary = { type = 10 id = 62551 }
		secondary = { type = 10 id = 62560 }
		startdate = { year = 1319 month = january day = 1 }
		enddate = { year = 1329 month = august day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 62601 }
		secondary = { type = 10 id = 62602 }
		startdate = { year = 1330 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62610 }
		secondary = { type = 10 id = 62855 }
		startdate = { year = 1320 month = january day = 1 }
		enddate = { year = 1330 month = may day = 22 }
	}
	marrige = { 
		primary = { type = 10 id = 62610 }
		secondary = { type = 10 id = 55657 }
		startdate = { year = 1334 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62611 }
		secondary = { type = 10 id = 62620 }
		startdate = { year = 1292 month = june day = 9 }
		enddate = { year = 1311 month = november day = 14 }
	}
	marrige = { 
		primary = { type = 10 id = 62614 }
		secondary = { type = 10 id = 55537 }
		startdate = { year = 1329 month = june day = 9 }
	}
	marrige = { 
		primary = { type = 10 id = 62616 }
		secondary = { type = 10 id = 62710 }
		startdate = { year = 1330 month = june day = 9 }
	}
	marrige = {
		primary = { type = 10 id = 62631 }
		secondary = { type = 10 id = 62640 }
		startdate = { year = 1287 month = january day = 1 }
		enddate = { year = 1299 month = june day = 24 }
	}
	marrige = { 
		primary = { type = 10 id = 62650 }
		secondary = { type = 10 id = 62633 }
		startdate = { year = 1322 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62691 }
		secondary = { type = 10 id = 62700 }
		startdate = { year = 1314 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62711 }
		secondary = { type = 10 id = 62712 }
		startdate = { year = 1258 month = september day = 15 }
		enddate = { year = 1273 month = october day = 9 }
	}
	marrige = {
		primary = { type = 10 id = 62714 }
		secondary = { type = 10 id = 71729 }
		startdate = { year = 1300 month = september day = 15 }
		enddate = { year = 1310 month = june day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 62717 }
		secondary = { type = 10 id = 62718 }
		startdate = { year = 1295 month = september day = 15 }
		enddate = { year = 1335 month = april day = 4 }
	}
	marrige = {
		primary = { type = 10 id = 62720 }
		secondary = { type = 10 id = 62721 }
		startdate = { year = 1315 month = september day = 15 }
		enddate = { year = 1320 month = august day = 18 }
	}
	marrige = { 
		primary = { type = 10 id = 62730 }
		secondary = { type = 10 id = 61540 }
		startdate = { year = 1328 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62731 }
		secondary = { type = 10 id = 51522 }
		startdate = { year = 1324 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62736 }
		secondary = { type = 10 id = 62377 }
		startdate = { year = 1294 month = january day = 1 }
		enddate = { year = 1319 month = august day = 18 }
	}
	marrige = {
		primary = { type = 10 id = 62737 }
		secondary = { type = 10 id = 62738 }
		startdate = { year = 1320 month = january day = 1 }
		enddate = { year = 1327 month = august day = 18 }
	}
	marrige = { 
		primary = { type = 10 id = 62740 }
		secondary = { type = 10 id = 62741 }
		startdate = { year = 1324 month = january day = 26 }
	}
	marrige = { 
		primary = { type = 10 id = 62742 }
		secondary = { type = 10 id = 62743 }
		startdate = { year = 1305 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62749 }
		secondary = { type = 10 id = 62716 }
		startdate = { year = 1328 month = january day = 1 }
		enddate = { year = 1335 month = june day = 25 }
	}
	marrige = {
		primary = { type = 10 id = 62750 }
		secondary = { type = 10 id = 62751 }
		startdate = { year = 1273 month = january day = 1 }
		enddate = { year = 1294 month = february day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 62758 }
		secondary = { type = 10 id = 62759 }
		startdate = { year = 1299 month = january day = 1 }
		enddate = { year = 1310 month = april day = 25 }
	}
	marrige = { 
		primary = { type = 10 id = 62760 }
		secondary = { type = 10 id = 62612 }
		startdate = { year = 1328 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62803 }
		secondary = { type = 10 id = 62804 }
		startdate = { year = 1263 month = january day = 1 }
		enddate = { year = 1279 month = february day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 62805 }
		secondary = { type = 10 id = 62806 }
		startdate = { year = 1282 month = january day = 1 }
		enddate = { year = 1322 month = february day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 62808 }
		secondary = { type = 10 id = 62809 }
		startdate = { year = 1318 month = january day = 1 }
		enddate = { year = 1327 month = february day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 62808 }
		secondary = { type = 10 id = 62814 }
		startdate = { year = 1330 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 62816 }
		secondary = { type = 10 id = 62817 }
		startdate = { year = 1336 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62821 }
		secondary = { type = 10 id = 62822 }
		startdate = { year = 1284 month = january day = 1 }
		enddate = { year = 1318 month = february day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 62826 }
		secondary = { type = 10 id = 62827 }
		startdate = { year = 1327 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62832 }
		secondary = { type = 10 id = 62833 }
		startdate = { year = 1262 month = january day = 1 }
		enddate = { year = 1277 month = february day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 62834 }
		secondary = { type = 10 id = 62755 }
		startdate = { year = 1288 month = january day = 1 }
		enddate = { year = 1319 month = october day = 11 }
	}
	marrige = { 
		primary = { type = 10 id = 62835 }
		secondary = { type = 10 id = 51984 }
		startdate = { year = 1288 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62838 }
		secondary = { type = 10 id = 62839 }
		startdate = { year = 1328 month = january day = 1 }
		enddate = { year = 1336 month = march day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 62910 }
		secondary = { type = 10 id = 62911 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62912 }
		secondary = { type = 10 id = 62913 }
		startdate = { year = 1265 month = january day = 1 }
		enddate = { year = 1285 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62915 }
		secondary = { type = 10 id = 62846 }
		startdate = { year = 1294 month = january day = 1 }
		enddate = { year = 1314 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62915 }
		secondary = { type = 10 id = 62916 }
		startdate = { year = 1299 month = january day = 1 }
		enddate = { year = 1316 month = april day = 19 }
	}
	marrige = { 
		primary = { type = 10 id = 62917 }
		secondary = { type = 10 id = 62918 }
		startdate = { year = 1330 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62920 }
		secondary = { type = 10 id = 56555 }
		startdate = { year = 1320 month = january day = 1 }
		enddate = { year = 1333 month = september day = 17 }
	}
	marrige = {
		primary = { type = 10 id = 62925 }
		secondary = { type = 10 id = 62926 }
		startdate = { year = 1289 month = january day = 1 }
		enddate = { year = 1305 month = october day = 4 }
	}
	marrige = { 
		primary = { type = 10 id = 62930 }
		secondary = { type = 10 id = 62931 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 62940 }
		secondary = { type = 10 id = 62941 }
		startdate = { year = 1285 month = january day = 1 }
		enddate = { year = 1328 month = september day = 29 }
	}
	marrige = { 
		primary = { type = 10 id = 63140 }
		secondary = { type = 10 id = 63143 }
		startdate = { year = 1333 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 63141 }
		secondary = { type = 10 id = 63142 }
		startdate = { year = 1300 month = january day = 1 }
		enddate = { year = 1328 month = september day = 29 }
	}
	marrige = { 
		primary = { type = 10 id = 63148 }
		secondary = { type = 10 id = 63149 }
		startdate = { year = 1318 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 63200 }
		secondary = { type = 10 id = 63201 }
		startdate = { year = 1317 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 63462 }
		secondary = { type = 10 id = 63463 }
		startdate = { year = 1333 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 64006 }
		secondary = { type = 10 id = 64010 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 64007 }
		secondary = { type = 10 id = 64008 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 65500 }
		secondary = { type = 10 id = 62157 }
		startdate = { year = 1326 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 65501 }
		secondary = { type = 10 id = 65911 }
		startdate = { year = 1337 month = january day = 1 }
		enddate = { year = 1320 month = january day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 65516 }
		secondary = { type = 10 id = 65517 }
		startdate = { year = 1318 month = january day = 1 }
		enddate = { year = 1321 month = january day = 14 }
	}
	marrige = { 
		primary = { type = 10 id = 65520 }
		secondary = { type = 10 id = 63555 }
		startdate = { year = 1337 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 65521 }
		secondary = { type = 10 id = 65522 }
		startdate = { year = 1290 month = january day = 1 }
		enddate = { year = 1317 month = july day = 14 }
	}
	marrige = { 
		primary = { type = 10 id = 65530 }
		secondary = { type = 10 id = 65564 }
		startdate = { year = 1336 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 65551 }
		secondary = { type = 10 id = 65526 }
		startdate = { year = 1337 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 66501 }
		secondary = { type = 10 id = 66502 }
		startdate = { year = 1270 month = january day = 1 }
		enddate = { year = 1289 month = october day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 66511 }
		secondary = { type = 10 id = 77515 }
		startdate = { year = 1292 month = january day = 1 }
		enddate = { year = 1311 month = december day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 66516 }
		secondary = { type = 10 id = 66517 }
		startdate = { year = 1187 month = january day = 1 }
		enddate = { year = 1207 month = december day = 21 }
	}
	marrige = { 
		primary = { type = 10 id = 67500 }
		secondary = { type = 10 id = 75552 }
		startdate = { year = 1322 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 67505 }
		secondary = { type = 10 id = 67506 }
		startdate = { year = 1300 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 67520 }
		secondary = { type = 10 id = 68511 }
		startdate = { year = 1300 month = january day = 1 }
		enddate = { year = 1324 month = november day = 9 }
	}
	marrige = {
		primary = { type = 10 id = 67520 }
		secondary = { type = 10 id = 65515 }
		startdate = { year = 1324 month = january day = 1 }
		enddate = { year = 1330 month = november day = 9 }
	}
	marrige = { 
		primary = { type = 10 id = 67524 }
		secondary = { type = 10 id = 61729 }
		startdate = { year = 1336 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 68500 }
		secondary = { type = 10 id = 67501 }
		startdate = { year = 1322 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 68505 }
		secondary = { type = 10 id = 67531 }
		startdate = { year = 1278 month = january day = 1 }
		enddate = { year = 1299 month = december day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 68510 }
		secondary = { type = 10 id = 68503 }
		startdate = { year = 1326 month = january day = 1 }
		enddate = { year = 1331 month = december day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 68510 }
		secondary = { type = 10 id = 67541 }
		startdate = { year = 1293 month = january day = 1 }
		enddate = { year = 1322 month = april day = 21 }
	}
	marrige = {
		primary = { type = 10 id = 68555 }
		secondary = { type = 10 id = 67542 }
		startdate = { year = 1298 month = january day = 1 }
		enddate = { year = 1305 month = april day = 4 }
	}
	marrige = { 
		primary = { type = 10 id = 68800 }
		secondary = { type = 10 id = 71538 }
		startdate = { year = 1324 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 68810 }
		secondary = { type = 10 id = 68531 }
		startdate = { year = 1284 month = january day = 1 }
		enddate = { year = 1314 month = march day = 12 }
	}
	marrige = { 
		primary = { type = 10 id = 68850 }
		secondary = { type = 10 id = 68806 }
		startdate = { year = 1306 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 69520 }
		secondary = { type = 10 id = 69521 }
		startdate = { year = 1286 month = january day = 1 }
		enddate = { year = 1335 month = september day = 27 }
	}
	marrige = { 
		primary = { type = 10 id = 71500 }
		secondary = { type = 10 id = 71503 }
		startdate = { year = 1325 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70003 }
		secondary = { type = 10 id = 70023 }
		startdate = { year = 1326 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70004 }
		secondary = { type = 10 id = 70005 }
		startdate = { year = 1332 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70007 }
		secondary = { type = 10 id = 70006 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70009 }
		secondary = { type = 10 id = 68506 }
		startdate = { year = 1309 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70030 }
		secondary = { type = 10 id = 70032 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70021 }
		secondary = { type = 10 id = 70022 }
		startdate = { year = 1310 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 70040 }
		secondary = { type = 10 id = 70041 }
		startdate = { year = 1317 month = january day = 1 }
		enddate = { year = 1327 month = july day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 70040 }
		secondary = { type = 10 id = 70042 }
		startdate = { year = 1328 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70062 }
		secondary = { type = 10 id = 70063 }
		startdate = { year = 1330 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70070 }
		secondary = { type = 10 id = 70074 }
		startdate = { year = 1321 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70076 }
		secondary = { type = 10 id = 70078 }
		startdate = { year = 1326 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 70108 }
		secondary = { type = 10 id = 70109 }
		startdate = { year = 1270 month = january day = 1 }
		enddate = { year = 1310 month = july day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 70111 }
		secondary = { type = 10 id = 70128 }
		startdate = { year = 1330 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70112 }
		secondary = { type = 10 id = 70129 }
		startdate = { year = 1330 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 70118 }
		secondary = { type = 10 id = 70121 }
		startdate = { year = 1310 month = january day = 1 }
		enddate = { year = 1330 month = january day = 9 }
	}
	marrige = { 
		primary = { type = 10 id = 70135 }
		secondary = { type = 10 id = 70142 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70151 }
		secondary = { type = 10 id = 70152 }
		startdate = { year = 1336 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70160 }
		secondary = { type = 10 id = 70164 }
		startdate = { year = 1333 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 70161 }
		secondary = { type = 10 id = 70162 }
		startdate = { year = 1298 month = january day = 1 }
		enddate = { year = 1309 month = january day = 9 }
	}
	marrige = { 
		primary = { type = 10 id = 70181 }
		secondary = { type = 10 id = 70182 }
		startdate = { year = 1302 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70191 }
		secondary = { type = 10 id = 70194 }
		startdate = { year = 1327 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 70192 }
		secondary = { type = 10 id = 70187 }
		startdate = { year = 1330 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 71510 }
		secondary = { type = 10 id = 71555 }
		startdate = { year = 1287 month = january day = 1 }
		enddate = { year = 1333 month = july day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 71515 }
		secondary = { type = 10 id = 71516 }
		startdate = { year = 1310 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 71518 }
		secondary = { type = 10 id = 71525 }
		startdate = { year = 1135 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 71520 }
		secondary = { type = 10 id = 71540 }
		startdate = { year = 1158 month = january day = 1 }
		enddate = { year = 1267 month = april day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 71530 }
		secondary = { type = 10 id = 71531 }
		startdate = { year = 1268 month = january day = 1 }
		enddate = { year = 1287 month = december day = 2 }
	}
	marrige = { 
		primary = { type = 10 id = 71536 }
		secondary = { type = 10 id = 71537 }
		startdate = { year = 1334 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 71560 }
		secondary = { type = 10 id = 71605 }
		startdate = { year = 1317 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 71650 }
		secondary = { type = 10 id = 71651 }
		startdate = { year = 1315 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 71660 }
		secondary = { type = 10 id = 71661 }
		startdate = { year = 1278 month = january day = 1 }
		enddate = { year = 1309 month = january day = 12 }
	}
	marrige = {
		primary = { type = 10 id = 71710 }
		secondary = { type = 10 id = 71502 }
		startdate = { year = 1308 month = january day = 1 }
		enddate = { year = 1326 month = august day = 13 }
	}
	marrige = { 
		primary = { type = 10 id = 71720 }
		secondary = { type = 10 id = 71721 }
		startdate = { year = 1330 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 71722 }
		secondary = { type = 10 id = 71723 }
		startdate = { year = 1290 month = january day = 1 }
		enddate = { year = 1313 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 71730 }
		secondary = { type = 10 id = 71731 }
		startdate = { year = 1308 month = january day = 1 }
		enddate = { year = 1322 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 71730 }
		secondary = { type = 10 id = 70013 }
		startdate = { year = 1326 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 71732 }
		secondary = { type = 10 id = 71733 }
		startdate = { year = 1288 month = january day = 1 }
		enddate = { year = 1296 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 71740 }
		secondary = { type = 10 id = 71519 }
		startdate = { year = 1328 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 72794 }
		secondary = { type = 10 id = 72795 }
		startdate = { year = 1260 month = january day = 1 }
		enddate = { year = 1299 month = september day = 19 }
	}
	marrige = { 
		primary = { type = 10 id = 72800 }
		secondary = { type = 10 id = 72801 }
		startdate = { year = 1328 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 72806 }
		secondary = { type = 10 id = 72807 }
		startdate = { year = 1326 month = january day = 1 }
		enddate = { year = 1331 month = march day = 28 }
	}
	marrige = {
		primary = { type = 10 id = 72822 }
		secondary = { type = 10 id = 72823 }
		startdate = { year = 1278 month = january day = 1 }
		enddate = { year = 1293 month = march day = 3 }
	}
	marrige = {
		primary = { type = 10 id = 72824 }
		secondary = { type = 10 id = 72825 }
		startdate = { year = 1257 month = january day = 1 }
		enddate = { year = 1278 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 72834 }
		secondary = { type = 10 id = 72835 }
		startdate = { year = 1276 month = january day = 1 }
		enddate = { year = 1280 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 72840 }
		secondary = { type = 10 id = 72841 }
		startdate = { year = 1315 month = january day = 1 }
		enddate = { year = 1329 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 72844 }
		secondary = { type = 10 id = 72845 }
		startdate = { year = 1239 month = january day = 1 }
		enddate = { year = 1263 month = november day = 14 }
	}
	marrige = {
		primary = { type = 10 id = 72846 }
		secondary = { type = 10 id = 72847 }
		startdate = { year = 1294 month = january day = 1 }
		enddate = { year = 1304 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 72851 }
		secondary = { type = 10 id = 72852 }
		startdate = { year = 1333 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 72860 }
		secondary = { type = 10 id = 72861 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 72862 }
		secondary = { type = 10 id = 72863 }
		startdate = { year = 1294 month = january day = 1 }
		enddate = { year = 1318 month = november day = 22 }
	}
	marrige = {
		primary = { type = 10 id = 72864 }
		secondary = { type = 10 id = 72865 }
		startdate = { year = 1266 month = january day = 1 }
		enddate = { year = 1272 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 72866 }
		secondary = { type = 10 id = 72867 }
		startdate = { year = 1320 month = january day = 1 }
		enddate = { year = 1326 month = september day = 15 }
	}
	marrige = { 
		primary = { type = 10 id = 72868 }
		secondary = { type = 10 id = 72869 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 72871 }
		secondary = { type = 10 id = 72872 }
		startdate = { year = 1330 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 72900 }
		secondary = { type = 10 id = 72901 }
		startdate = { year = 1331 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 72910 }
		secondary = { type = 10 id = 72911 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 72912 }
		secondary = { type = 10 id = 72913 }
		startdate = { year = 1290 month = january day = 1 }
		enddate = { year = 1309 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 72914 }
		secondary = { type = 10 id = 72915 }
		startdate = { year = 1250 month = january day = 1 }
		enddate = { year = 1264 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 73500 }
		secondary = { type = 10 id = 73501 }
		startdate = { year = 1276 month = january day = 2 }
		enddate = { year = 1295 month = october day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 73500 }
		secondary = { type = 10 id = 73502 }
		startdate = { year = 1296 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 73504 }
		secondary = { type = 10 id = 73511 }
		startdate = { year = 1332 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 73506 }
		secondary = { type = 10 id = 73512 }
		startdate = { year = 1318 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 73510 }
		secondary = { type = 10 id = 73517 }
		startdate = { year = 1325 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 75550 }
		secondary = { type = 10 id = 75551 }
		startdate = { year = 1303 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 75553 }
		secondary = { type = 10 id = 75554 }
		startdate = { year = 1325 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 87011 }
		secondary = { type = 10 id = 87012 }
		startdate = { year = 1324 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 87020 }
		secondary = { type = 10 id = 62719 }
		startdate = { year = 1305 month = january day = 1 }
		enddate = { year = 1322 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 87021 }
		secondary = { type = 10 id = 87030 }
		startdate = { year = 1330 month = january day = 1 }
	}
	marrige = {
		primary = { type = 10 id = 87040 }
		secondary = { type = 10 id = 87041 }
		startdate = { year = 1273 month = january day = 1 }
		enddate = { year = 1285 month = april day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 87042 }
		secondary = { type = 10 id = 87043 }
		startdate = { year = 1290 month = january day = 1 }
		enddate = { year = 1312 month = december day = 2 }
	}
	marrige = {
		primary = { type = 10 id = 87044 }
		secondary = { type = 10 id = 87045 }
		startdate = { year = 1290 month = january day = 1 }
		enddate = { year = 1335 month = october day = 29 }
	}
	marrige = { 
		primary = { type = 10 id = 78040 }
		secondary = { type = 10 id = 78041 }
		startdate = { year = 1312 month = january day = 1 }
	}
	marrige = { 
		primary = { type = 10 id = 78006 }
		secondary = { type = 10 id = 78041 }
		startdate = { year = 1312 month = january day = 1 }
	}
	marrige = { #Basileios I Komnenos & Eirene Palaiologina (d.Andronikos III)
		primary = { type = 10 id = 65800 }
		secondary = { type = 10 id = 65514 }
		startdate = { year = 1335 month = january day = 1 }
	}
	marrige = { #Basileios I Komnenos & Eirene (of Trebizond)
		primary = { type = 10 id = 65800 }
		secondary = { type = 10 id = 65802 }
		startdate = { year = 1337 month = january day = 1 } 
	}
	marrige = { #Ioannes II Komnenos & Evdokia Palaiologos (d.Mikhael VIII)
		primary = { type = 10 id = 65805 }
		secondary = { type = 10 id = 65806 }
		startdate = { year = 1282 month = january day = 1 }
		enddate = { year = 1297 month = january day = 1 }
	}
	marrige = { #Mikhael I Komnenos & Anna Akropolites
		primary = { type = 10 id = 65807 }
		secondary = { type = 10 id = 65808 }
		startdate = { year = 1320 month = january day = 1 }
	}
	marrige = { #Alexios II Komnenos & Djiadjak Djakeli
		primary = { type = 10 id = 65810 }
		secondary = { type = 10 id = 66751 }
		startdate = { year = 1300 month = january day = 1 }
		enddate = { year = 1321 month = january day = 1 }
	}
	marrige = { #Adil Beg ibn Yakub Candaroglu & Eudokia Komnena
		primary = { type = 10 id = 76355 }
		secondary = { type = 10 id = 65812 }
		startdate = { year = 1337 month = january day = 1 } 
	}
	marrige = { #Liparit Orbeliani & Ana
		primary = { type = 10 id = 66757 }
		secondary = { type = 10 id = 66758 }
		startdate = { year = 1285 month = january day = 1 }
		enddate = { year = 1314 month = january day = 1 }
	}
	marrige = { #Chesar Orbeliani & Khorishah Senikariman
		primary = { type = 10 id = 66759 }
		secondary = { type = 10 id = 66760 }
		startdate = { year = 1315 month = january day = 1 }
	}
	marrige = { #Alexios Philanthropenos & Theodora Akropolitissa
		primary = { type = 10 id = 65210 }
		secondary = { type = 10 id = 65211 }
		startdate = { year = 1308 month = january day = 1 }
	}
	marrige = { #Mikhael Philanthropenos & Eirene Asanina
		primary = { type = 10 id = 65212 }
		secondary = { type = 10 id = 65564 }
		startdate = { year = 1336 month = january day = 1 } 
	}
	marrige = { 
		primary = { type = 10 id = 14714 }
		secondary = { type = 10 id = 4515 }
		startdate = { year = 1203 month = december day = 1 } 
		enddate = { year = 1240 month = april day = 11 }
	}
	friend = { 
		primary = { type = 10 id = 62740 }
		secondary = { type = 10 id = 62020 }
		startdate = { year = 1336 month = january day = 1 }
	}
	friend = { 
		primary = { type = 10 id = 68500 }
		secondary = { type = 10 id = 67500 }
		startdate = { year = 1336 month = january day = 1 }
	}
	friend = { 
		primary = { type = 10 id = 57510 }
		secondary = { type = 10 id = 57502 }
		startdate = { year = 1336 month = january day = 1 }
	}
	friend = { 
		primary = { type = 10 id = 57510 }
		secondary = { type = 10 id = 57503 }
		startdate = { year = 1336 month = january day = 1 }
	}
	friend = { 
		primary = { type = 10 id = 65530 } #Ioannes VI Kantakouzenos
		secondary = { type = 10 id = 65215 } #Nikolaos Kabasilas
		startdate = { year = 1336 month = january day = 1 }
	}
	friend = { 
		primary = { type = 10 id = 65530 } #Ioannes VI Kantakouzenos
		secondary = { type = 10 id = 65500 } #Andronikos III Palaiologos
		startdate = { year = 1336 month = january day = 1 }
	}
	rival = { 
		primary = { type = 10 id = 62740 }
		secondary = { type = 10 id = 62614 }
		startdate = { year = 1336 month = january day = 1 }
	}
	rival = { 
		primary = { type = 10 id = 50500 }
		secondary = { type = 10 id = 50780 }
		startdate = { year = 1336 month = january day = 1 }
	}
	rival = { 
		primary = { type = 10 id = 69500 }
		secondary = { type = 10 id = 75550 }
		startdate = { year = 1336 month = january day = 1 }
	}
	rival = { 
		primary = { type = 10 id = 57501 }
		secondary = { type = 10 id = 57510 }
		startdate = { year = 1336 month = january day = 1 }
	}
	rival = { 
		primary = { type = 10 id = 57501 }
		secondary = { type = 10 id = 57502 }
		startdate = { year = 1336 month = january day = 1 }
	}
	rival = { 
		primary = { type = 10 id = 57501 }
		secondary = { type = 10 id = 57503 }
		startdate = { year = 1336 month = january day = 1 }
	}
	rival = { 
		primary = { type = 10 id = 57500 }
		secondary = { type = 10 id = 59502 }
		startdate = { year = 1336 month = january day = 1 }
	}
	rival = { 
		primary = { type = 10 id = 78000 }
		secondary = { type = 10 id = 78040 }
		startdate = { year = 1336 month = january day = 1 }
	}
}