country = {
	tag = C332
	form_of_goverment = republican
	capital = 332
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 13016 }
	}
	controlledprovinces = {
		332
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C330
	form_of_goverment = republican
	capital = 330
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 13017 }
	}
	controlledprovinces = {
		330
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C350
	form_of_goverment = republican
	capital = 350
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 63470 }
	}
	controlledprovinces = {
		350
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C357
	form_of_goverment = republican
	capital = 357
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 13023 }
	}
	controlledprovinces = {
		357
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C354
	form_of_goverment = republican
	capital = 354
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 13024 }
	}
	controlledprovinces = {
		354
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = WEIS
	form_of_goverment = feudal
	capital = 035
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 20019 }
	}
	controlledprovinces = {
		035
	}
}
country = {
	tag = C054
	form_of_goverment = feudal
	capital = 054
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 20021 }
	}
	controlledprovinces = {
		054
	}
}
country = {
	tag = C313
	form_of_goverment = feudal
	capital = 313
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 20239 }
	}
	controlledprovinces = {
		313
	}
}
country = {
	tag = C995
	form_of_goverment = ecclestical
	capital = 995
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 20251 }
	}
	controlledprovinces = {
		995
		259
	}
}
country = {
	tag = C231
	form_of_goverment = feudal
	capital = 231
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 20301 }
	}
	controlledprovinces = {
		231
	}
}
country = {
	tag = BENE
	form_of_goverment = ecclestical
	capital = 997
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 20331 }
	}
	controlledprovinces = {
		997
	}
}
country = {
	tag = C898
	form_of_goverment = ecclestical
	capital = 898
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 20332 }
	}
	controlledprovinces = {
		898
	}
}
country = {
	tag = C848
	form_of_goverment = feudal
	capital = 848
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 20842 }
	}
	controlledprovinces = {
		848
	}
}
country = {
	tag = C650
	form_of_goverment = feudal
	capital = 650
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 27101 }
	}
	controlledprovinces = {
		650
	}
}
country = {
	tag = C651
	form_of_goverment = feudal
	capital = 651
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 27102 }
	}
	controlledprovinces = {
		651
	}
}
country = {
	tag = C652
	form_of_goverment = feudal
	capital = 652
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 27103 }
	}
	controlledprovinces = {
		652
	}
}
country = {
	tag = C653
	form_of_goverment = feudal
	capital = 653
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 27104 }
	}
	controlledprovinces = {
		653
	}
}
country = {
	tag = C654
	form_of_goverment = feudal
	capital = 654
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 27105 }
	}
	controlledprovinces = {
		654
	}
}
country = {
	tag = MORD
	form_of_goverment = feudal
	capital = 579
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 28070 }
	}
	controlledprovinces = {
		579
	}
	laws = {
		salic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = SWED
	form_of_goverment = feudal
	capital = 292
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50500 }
	}
	controlledprovinces = {
		292
		301
		303
		272
	}
	laws = {
		elective_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C006
	form_of_goverment = feudal
	capital = 006
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50600 }
	}
	controlledprovinces = {
		006
	}
}
country = {
	tag = C033
	form_of_goverment = feudal
	capital = 033
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87073 }
	}
	controlledprovinces = {
		033
	}
}
country = {
	tag = C034
	form_of_goverment = feudal
	capital = 034
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87074 }
	}
	controlledprovinces = {
		034
	}
}
country = {
	tag = C391
	form_of_goverment = feudal
	capital = 391
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50610 }
	}
	controlledprovinces = {
		391
		390
	}
}
country = {
	tag = C300
	form_of_goverment = feudal
	capital = 300
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50620 }
	}
	controlledprovinces = {
		300
		299
	}
}
country = {
	tag = C297
	form_of_goverment = feudal
	capital = 297
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50630 }
	}
	controlledprovinces = {
		297
	}
}
country = {
	tag = C295
	form_of_goverment = feudal
	capital = 295
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50640 }
	}
	controlledprovinces = {
		295
	}
}
country = {
	tag = C293
	form_of_goverment = feudal
	capital = 293
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50650 }
	}
	controlledprovinces = {
		293
		298
	}
}
country = {
	tag = C296
	form_of_goverment = feudal
	capital = 296
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50660 }
	}
	controlledprovinces = {
		296
	}
}
country = {
	tag = C276
	form_of_goverment = feudal
	capital = 276
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50670 }
	}
	controlledprovinces = {
		276
		273
	}
}
country = {
	tag = C288
	form_of_goverment = feudal
	capital = 288
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50680 }
	}
	controlledprovinces = {
		288
	}
}
country = {
	tag = C294
	form_of_goverment = feudal
	capital = 294
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50690 }
	}
	controlledprovinces = {
		294
	}
}
country = {
	tag = C289
	form_of_goverment = feudal
	capital = 289
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50700 }
	}
	controlledprovinces = {
		289
		287
	}
}
country = {
	tag = C290
	form_of_goverment = feudal
	capital = 290
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50710 }
	}
	controlledprovinces = {
		290
		286
		291
	}
}
country = {
	tag = C285
	form_of_goverment = feudal
	capital = 285
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50720 }
	}
	controlledprovinces = {
		285
	}
}
country = {
	tag = C280
	form_of_goverment = feudal
	capital = 280
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87070 }
	}
	controlledprovinces = {
		280
	}
}
country = {
	tag = C281
	form_of_goverment = feudal
	capital = 281
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87071 }
	}
	controlledprovinces = {
		281
	}
}
country = {
	tag = C283
	form_of_goverment = feudal
	capital = 283
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87072 }
	}
	controlledprovinces = {
		283
	}
}
country = {
	tag = C269
	form_of_goverment = feudal
	capital = 269
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50730 }
	}
	controlledprovinces = {
		269
	}
}
country = {
	tag = C270
	form_of_goverment = feudal
	capital = 270
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50740 }
	}
	controlledprovinces = {
		270
	}
}
country = {
	tag = C271
	form_of_goverment = feudal
	capital = 271
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50750 }
	}
	controlledprovinces = {
		271
	}
}
country = {
	tag = FINL
	form_of_goverment = feudal
	capital = 382
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50760 }
	}
	controlledprovinces = {
		382
		384
		385
	}
}
country = {
	tag = BERG
	form_of_goverment = feudal
	capital = 274
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50780 }
	}
	controlledprovinces = {
		274
		268
		278
	}
}
country = {
	tag = C275
	form_of_goverment = feudal
	capital = 275
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50790 }
	}
	controlledprovinces = {
		275
	}
}
country = {
	tag = JAMT
	form_of_goverment = feudal
	capital = 282
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50800 }
	}
	controlledprovinces = {
		282
		284
	}
}
country = {
	tag = C277
	form_of_goverment = feudal
	capital = 277
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50810 }
	}
	controlledprovinces = {
		277
	}
}
country = {
	tag = ORKN
	form_of_goverment = feudal
	capital = 036
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50820 }
	}
	controlledprovinces = {
		036
		037
	}
}
country = {
	tag = C383
	form_of_goverment = feudal
	capital = 383
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 50840 }
	}
	controlledprovinces = {
		383
		381
	}
}
country = {
	tag = DENM
	form_of_goverment = feudal
	capital = 267
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 51500 }
	}
	controlledprovinces = {
		267
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = ESTH
	form_of_goverment = feudal
	capital = 378
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 51523 }
	}
	controlledprovinces = {
		378
		380
	}
}
country = {
	tag = SKAN
	form_of_goverment = ecclestical
	capital = 305
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 51600 }
	}
	controlledprovinces = {
		305
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C302
	form_of_goverment = feudal
	capital = 302
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 51800 }
	}
	controlledprovinces = {
		302
	}
}
country = {
	tag = C263
	form_of_goverment = feudal
	capital = 263
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 51970 }
	}
	controlledprovinces = {
		263
	}
}
country = {
	tag = POMM
	form_of_goverment = feudal
	capital = 366
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 71655 }
	}
	controlledprovinces = {
		366
		367
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C304
	form_of_goverment = feudal
	capital = 304
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 71653 }
	}
	controlledprovinces = {
		304
	}
}
country = {
	tag = C266
	form_of_goverment = feudal
	capital = 266
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 51960 }
	}
	controlledprovinces = {
		266
	}
}
country = {
	tag = SVIG
	form_of_goverment = feudal
	capital = 264
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 51530 }
	}
	controlledprovinces = {
		264
	}
}
country = {
	tag = HOLS
	form_of_goverment = feudal
	capital = 261
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 51940 }
	}
	controlledprovinces = {
		261
		265
	}
}
country = {
	tag = MECK
	form_of_goverment = feudal
	capital = 260
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 51980 }
	}
	controlledprovinces = {
		260
		306
	}
}
country = {
	tag = C307
	form_of_goverment = feudal
	capital = 307
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 51990 }
	}
	controlledprovinces = {
		307
	}
}
country = {
	tag = C002
	form_of_goverment = feudal
	capital = 002
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 52600 }
	}
	controlledprovinces = {
		002
	}
}
country = {
	tag = C001
	form_of_goverment = feudal
	capital = 001
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 52610 }
	}
	controlledprovinces = {
		001
	}
}
country = {
	tag = C038
	form_of_goverment = feudal
	capital = 038
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 53002 }
	}
	controlledprovinces = {
		038
	}
}
country = {
	tag = C039
	form_of_goverment = feudal
	capital = 039
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 53003 }
	}
	controlledprovinces = {
		039
	}
}
country = {
	tag = C040
	form_of_goverment = feudal
	capital = 040
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 53004 }
	}
	controlledprovinces = {
		040
	}
}
country = {
	tag = C041
	form_of_goverment = feudal
	capital = 041
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 53005 }
	}
	controlledprovinces = {
		041
	}
}
country = {
	tag = C042
	form_of_goverment = feudal
	capital = 042
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 53006 }
	}
	controlledprovinces = {
		042
	}
}
country = {
	tag = C043
	form_of_goverment = feudal
	capital = 043
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 53007 }
	}
	controlledprovinces = {
		043
	}
}
country = {
	tag = C045
	form_of_goverment = feudal
	capital = 045
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 53009 }
	}
	controlledprovinces = {
		045
	}
}
country = {
	tag = C046
	form_of_goverment = feudal
	capital = 046
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 53010 }
	}
	controlledprovinces = {
		046
	}
}
country = {
	tag = C049
	form_of_goverment = feudal
	capital = 049
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 53518 }
	}
	controlledprovinces = {
		049
	}
}
country = {
	tag = C050
	form_of_goverment = feudal
	capital = 050
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 53611 }
	}
	controlledprovinces = {
		050		
	}
}
country = {
	tag = C051
	form_of_goverment = feudal
	capital = 051
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 53014 }
	}
	controlledprovinces = {
		051		
	}
}
country = {
	tag = SCOT
	form_of_goverment = feudal
	capital = 048
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 53500 }
	}
	controlledprovinces = {
		048
		044
		047		
	}
	laws = {
		semisalic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C018
	form_of_goverment = feudal
	capital = 018
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 53400 }
	}
	controlledprovinces = {
		018
	}
}
country = {
	tag = C021
	form_of_goverment = feudal
	capital = 021
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54610 }
	}
	controlledprovinces = {
		021
	}
}
country = {
	tag = C022
	form_of_goverment = feudal
	capital = 022
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54586 }
	}
	controlledprovinces = {
		022
	}
}
country = {
	tag = C024
	form_of_goverment = feudal
	capital = 024
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54581 }
	}
	controlledprovinces = {
		024
	}
}
country = {
	tag = C025
	form_of_goverment = feudal
	capital = 025
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54570 }
	}
	controlledprovinces = {
		025
		026
	}
}
country = {
	tag = C029
	form_of_goverment = feudal
	capital = 029
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54594 }
	}
	controlledprovinces = {
		029
		030
	}
}
country = {
	tag = C055
	form_of_goverment = feudal
	capital = 055
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54602 }
	}
	controlledprovinces = {
		055
		053
	}
}
country = {
	tag = C056
	form_of_goverment = ecclestical
	capital = 056
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54596 }
	}
	controlledprovinces = {
		056
		052
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C061
	form_of_goverment = feudal
	capital = 061
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54023 }
	}
	controlledprovinces = {
		061
		023
	}
}
country = {
	tag = C067
	form_of_goverment = feudal
	capital = 067
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54592 }
	}
	controlledprovinces = {
		067
	}
}
country = {
	tag = C068
	form_of_goverment = feudal
	capital = 068
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54562 }
	}
	controlledprovinces = {
		068
	}
}
country = {
	tag = C071
	form_of_goverment = feudal
	capital = 071
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54030 }
	}
	controlledprovinces = {
		071
	}
}
country = {
	tag = C073
	form_of_goverment = feudal
	capital = 073
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54576 }
	}
	controlledprovinces = {
		073
	}
}
country = {
	tag = MEAT
	form_of_goverment = feudal
	capital = 011
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54100 }
	}
	controlledprovinces = {
		011
		010			
	}
	laws = {
		elective_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C012
	form_of_goverment = feudal
	capital = 012
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54122 }
	}
	controlledprovinces = {
		012
	}
}
country = {
	tag = C014
	form_of_goverment = feudal
	capital = 014
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54130 }
	}
	controlledprovinces = {
		014
	}
}
country = {
	tag = C015
	form_of_goverment = feudal
	capital = 015
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54110 }
	}
	controlledprovinces = {
		015
	}
}
country = {
	tag = ULST
	form_of_goverment = feudal
	capital = 005
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54614 }
	}
	controlledprovinces = {
		005
	}
}
country = {
	tag = LEIN
	form_of_goverment = feudal
	capital = 016
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54201 }
	}
	controlledprovinces = {
		016
	}
	laws = {
		elective_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = CONN
	form_of_goverment = feudal
	capital = 009
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54150 }
	}
	controlledprovinces = {
		009
	}
}
country = {
	tag = C007
	form_of_goverment = feudal
	capital = 007
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54160 }
	}
	controlledprovinces = {
		007
	}
}
country = {
	tag = C008
	form_of_goverment = feudal
	capital = 008
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54204 }
	}
	controlledprovinces = {
		008
	}
}
country = {
	tag = C013
	form_of_goverment = feudal
	capital = 013
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54205 }
	}
	controlledprovinces = {
		013
	}
}
country = {
	tag = C065
	form_of_goverment = feudal
	capital = 065
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54211 }
	}
	controlledprovinces = {
		065
	}
}
country = {
	tag = ENGL
	form_of_goverment = feudal
	capital = 072
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54500 }
	}
	controlledprovinces = {
		072
		019
		020
		027
		028
		032
		059
		060
		064
		069
		143
		148
		149
		151
	}
	laws = {
		semisalic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = CORN
	form_of_goverment = feudal
	capital = 031
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54501 }
	}
	controlledprovinces = {
		031
	}
}
country = {
	tag = C058
	form_of_goverment = feudal
	capital = 058
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54525 }
	}
	controlledprovinces = {
		058
		062
	}
	laws = {
		semisalic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C063
	form_of_goverment = feudal
	capital = 063
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54527 }
	}
	controlledprovinces = {
		063
	}
}
country = {
	tag = C070
	form_of_goverment = feudal
	capital = 070
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54550 }
	}
	controlledprovinces = {
		070
	}
}
country = {
	tag = C017
	form_of_goverment = feudal
	capital = 017
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54560 }
	}
	controlledprovinces = {
		017
		066
	}
}
country = {
	tag = C095
	form_of_goverment = feudal
	capital = 095
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 54980 }
	}
	controlledprovinces = {
		095
	}
}
country = {
	tag = HAIN
	form_of_goverment = feudal
	capital = 094
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62742 }
	}
	controlledprovinces = {
		094
		079
		080
		081
	}
}
country = {
	tag = C109
	form_of_goverment = feudal
	capital = 109
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55006 }
	}
	controlledprovinces = {
		109
	}
}
country = {
	tag = C210
	form_of_goverment = feudal
	capital = 210
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55540 }
	}
	controlledprovinces = {
		210
	}
}
country = {
	tag = FRAN
	form_of_goverment = feudal
	capital = 112
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55500 }
	}
	controlledprovinces = {
		112
		113
		114
		130
		131
		138
		139
		141		
		213
		214
		215
		218
		219
		227		
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		monastic_supremacy = yes
	}
}
country = {
	tag = NORM
	form_of_goverment = feudal
	capital = 097
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55502 }
	}
	controlledprovinces = {
		097
		098
		100
		107
	}
}
country = {
	tag = C108
	form_of_goverment = feudal
	capital = 108
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55432 }
	}
	controlledprovinces = {
		108
	}
}
country = {
	tag = C212
	form_of_goverment = feudal
	capital = 212
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55620 }
	}
	controlledprovinces = {
		212
	}
}
country = {
	tag = C223
	form_of_goverment = feudal
	capital = 223
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55455 }
	}
	controlledprovinces = {
		223
	}
}
country = {
	tag = C111
	form_of_goverment = feudal
	capital = 111
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55513 }
	}
	controlledprovinces = {
		111
	}
}
country = {
	tag = C057
	form_of_goverment = feudal
	capital = 057
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55515 }
	}
	controlledprovinces = {
		057
	}
}
country = {
	tag = C129
	form_of_goverment = feudal
	capital = 129
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55760 }
	}
	controlledprovinces = {
		129
	}
}
country = {
	tag = C208
	form_of_goverment = feudal
	capital = 208
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55552 }
	}
	controlledprovinces = {
		208
	}
}
country = {
	tag = C216
	form_of_goverment = feudal
	capital = 216
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55560 }
	}
	controlledprovinces = {
		216
	}
}
country = {
	tag = C147
	form_of_goverment = feudal
	capital = 147
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55770 }
	}
	controlledprovinces = {
		147
	}
}
country = {
	tag = C150
	form_of_goverment = feudal
	capital = 150
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55630 }
	}
	controlledprovinces = {
		150
	}
}
country = {
	tag = C209
	form_of_goverment = feudal
	capital = 209
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55640 }
	}
	controlledprovinces = {
		209
	}
}
country = {
	tag = BOUR
	form_of_goverment = feudal
	capital = 146
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55650 }
	}
	controlledprovinces = {
		146
		145
		224
	}
}
country = {
	tag = C132
	form_of_goverment = feudal
	capital = 132
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55730 }
	}
	controlledprovinces = {
		132
	}
}
country = {
	tag = BRIT
	form_of_goverment = feudal
	capital = 106
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55750 }
	}
	controlledprovinces = {
		106
		101
		103
		104
		105
	}
}
country = {
	tag = C102
	form_of_goverment = feudal
	capital = 102
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55753 }
	}
	controlledprovinces = {
		102
	}
}
country = {
	tag = C110
	form_of_goverment = feudal
	capital = 110
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55781 }
	}
	controlledprovinces = {
		110
	}
}
country = {
	tag = NAVA
	form_of_goverment = feudal
	capital = 152
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55810 }
	}
	controlledprovinces = {
		152
		099
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C217
	form_of_goverment = feudal
	capital = 217
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55820 }
	}
	controlledprovinces = {
		217
		075
	}
}
country = {
	tag = C096
	form_of_goverment = feudal
	capital = 096
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55850 }
	}
	controlledprovinces = {
		096
		074
	}
}
country = {
	tag = BOUG
	form_of_goverment = feudal
	capital = 136
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55910 }
	}
	controlledprovinces = {
		136
		226
		135
		140
		225
		240
		077
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C142
	form_of_goverment = feudal
	capital = 142
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55930 }
	}
	controlledprovinces = {
		142
	}
}
country = {
	tag = FRIE
	form_of_goverment = feudal
	capital = 083
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 56550 }
	}
	controlledprovinces = {
		083		
	}
}
country = {
	tag = C085
	form_of_goverment = feudal
	capital = 085
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62171 }
	}
	controlledprovinces = {
		085
	}
	laws = {
		salic_primogeniture_law = yes
		popular_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C162
	form_of_goverment = feudal
	capital = 162
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57002 }
	}
	controlledprovinces = {
		162
	}
}
country = {
	tag = BADA
	form_of_goverment = ecclestical
	capital = 184
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57012 }
	}
	controlledprovinces = {
		184
	}
}
country = {
	tag = C185
	form_of_goverment = feudal
	capital = 185
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57013 }
	}
	controlledprovinces = {
		185
	}
}
country = {
	tag = C195
	form_of_goverment = feudal
	capital = 195
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57014 }
	}
	controlledprovinces = {
		195
	}
}
country = {
	tag = C196
	form_of_goverment = knight_order
	capital = 196
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57015 }
	}
	controlledprovinces = {
		196
		178
	}
}
country = {
	tag = CAST
	form_of_goverment = feudal
	capital = 197
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57500 }
	}
	controlledprovinces = {
		181
		190
		192
		197
		198
		200
	}
	laws = {
		semisalic_primogeniture_law = yes
		feudal_contract_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = MURC
	form_of_goverment = feudal
	capital = 169
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57630 }
	}
	controlledprovinces = {
		169
		179
	}
}
country = {
	tag = C144
	form_of_goverment = feudal
	capital = 144
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57570 }
	}
	controlledprovinces = {
		144
	}
}
country = {
	tag = C199
	form_of_goverment = feudal
	capital = 199
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57581 }
	}
	controlledprovinces = {
		199
	}
}
country = {
	tag = C201
	form_of_goverment = feudal
	capital = 201
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 56510 }
	}
	controlledprovinces = {
		201
	}
}
country = {
	tag = C153
	form_of_goverment = feudal
	capital = 153
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57610 }
	}
	controlledprovinces = {
		153
	}
}
country = {
	tag = ASTU
	form_of_goverment = feudal
	capital = 155
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57510 }
	}
	controlledprovinces = {
		155 154
	}
}
country = {
	tag = C156
	form_of_goverment = feudal
	capital = 156
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57670 }
	}
	controlledprovinces = {
		156
	}
}
country = {
	tag = C165
	form_of_goverment = feudal
	capital = 165
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 58011 }
	}
	controlledprovinces = {
		165
		164
	}
}
country = {
	tag = C176
	form_of_goverment = ecclestical
	capital = 176
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 58005 }
	}
	controlledprovinces = {
		176
	}
}
country = {
	tag = U000
	form_of_goverment = knight_order
	capital = 177
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 58004 }
	}
	controlledprovinces = {
		177
	}
}
country = {
	tag = C182
	form_of_goverment = ecclestical
	capital = 182
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 58002 }
	}
	controlledprovinces = {
		182
	}
}
country = {
	tag = C183
	form_of_goverment = feudal
	capital = 183
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 58021 }
	}
	controlledprovinces = {
		186
	}
}
country = {
	tag = GALC
	form_of_goverment = ecclestical
	capital = 157
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 58003 }
	}
	controlledprovinces = {
		157
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C189
	form_of_goverment = feudal
	capital = 189
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57590 }
	}
	controlledprovinces = {
		189
	}
}
country = {
	tag = C191
	form_of_goverment = ecclestical
	capital = 191
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57600 }
	}
	controlledprovinces = {
		191
	}
}
country = {
	tag = C193
	form_of_goverment = knight_order
	capital = 193
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 58006 }
	}
	controlledprovinces = {
		193
	}
}
country = {
	tag = C194
	form_of_goverment = feudal
	capital = 194
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 57020 }
	}
	controlledprovinces = {
		194
	}
}
country = {
	tag = C161
	form_of_goverment = feudal
	capital = 161
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 59001 }
	}
	controlledprovinces = {
		161
	}
}
country = {
	tag = C163
	form_of_goverment = feudal
	capital = 163
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 59002 }
	}
	controlledprovinces = {
		163
	}
}
country = {
	tag = C186
	form_of_goverment = feudal
	capital = 186
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 59004 }
	}
	controlledprovinces = {
		186
	}
}
country = {
	tag = C187
	form_of_goverment = feudal
	capital = 187
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 59005 }
	}
	controlledprovinces = {
		187
	}
}
country = {
	tag = C188
	form_of_goverment = feudal
	capital = 188
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 59006 }
	}
	controlledprovinces = {
		188
	}
}
country = {
	tag = PORT
	form_of_goverment = feudal
	capital = 159
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 59500 }
	}
	controlledprovinces = {
		159
		158
		160
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C172
	form_of_goverment = feudal
	capital = 172
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 60011 }
	}
	controlledprovinces = {
		172
	}
}
country = {
	tag = C203
	form_of_goverment = feudal
	capital = 203
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 60022 }
	}
	controlledprovinces = {
		203
	}
}
country = {
	tag = C205
	form_of_goverment = feudal
	capital = 205
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 60580 }
	}
	controlledprovinces = {
		205
	}
}
country = {
	tag = C206
	form_of_goverment = feudal
	capital = 206
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 60520  }
	}
	controlledprovinces = {
		206
	}
}
country = {
	tag = ARAG
	form_of_goverment = feudal
	capital = 171
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 60500 }
	}
	controlledprovinces = {
		171
		174
		175
		202
		204
	}
	laws = {
		semisalic_primogeniture_law = yes
		feudal_contract_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C173
	form_of_goverment = feudal
	capital = 173
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 60530 }
	}
	controlledprovinces = {
		173
	}
}
country = {
	tag = C170
	form_of_goverment = feudal
	capital = 170
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 60540 }
	}
	controlledprovinces = {
		170
	}
}
country = {
	tag = C207
	form_of_goverment = feudal
	capital = 207
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 60570 }
	}
	controlledprovinces = {
		207
	}
}
country = {
	tag = BALE
	form_of_goverment = feudal
	capital = 827
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 60620 }
	}
	controlledprovinces = {
		827		
		211
		220
		325
		826
	}
}
country = {
	tag = TRAN
	form_of_goverment = feudal
	capital = 339
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 61500 }
	}
	controlledprovinces = {
		339
		340
		341
		342
		343
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = HELL
	form_of_goverment = feudal
	capital = 482
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 61510 }
	}
	controlledprovinces = {
		482
		475
	}
}
country = {
	tag = C812
	form_of_goverment = feudal
	capital = 812
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 61550 }
	}
	controlledprovinces = {
		812
	}
}
country = {
	tag = AEGE
	form_of_goverment = feudal
	capital = 485
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 61570 }
	}
	controlledprovinces = {
		485
		484
	}
}
country = {
	tag = NAPL
	form_of_goverment = feudal
	capital = 334
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 61700 }
	}
	controlledprovinces = {
		221
		229
		334
		335
		336
		337
		338
		347
		348
		349
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = CALA
	form_of_goverment = feudal
	capital = 344
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 61718 }
	}
	controlledprovinces = {
		344
		346
		474
	}
}
country = {
	tag = C345
	form_of_goverment = feudal
	capital = 345
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 61730 }
	}
	controlledprovinces = {
		345
	}
}
country = {
	tag = CILI
	form_of_goverment = feudal
	capital = 735
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 61800 }
	}
	controlledprovinces = {
		735
		762
		763
	}
	laws = {
		semisalic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C761
	form_of_goverment = feudal
	capital = 761
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 61923 }
	}
	controlledprovinces = {
		761
	}
}
country = {
	tag = BASR
	form_of_goverment = feudal
	capital = 757
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 61900 }
	}
	controlledprovinces = {
		757
		756
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C084
	form_of_goverment = feudal
	capital = 084
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62001 }
	}
	controlledprovinces = {
		084
	}
	laws = {
		salic_primogeniture_law = yes
		popular_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = FLAN
	form_of_goverment = feudal
	capital = 093
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 55710 }
	}
	controlledprovinces = {
		093
		076
		078
		137
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C091
	form_of_goverment = feudal
	capital = 091
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62162 }
	}
	controlledprovinces = {
		091
	}
}
country = {
	tag = OSTE
	form_of_goverment = feudal
	capital = 449
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62020 }
	}
	controlledprovinces = {
		449
		134
		446
		456
		455
		457		
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C242
	form_of_goverment = feudal
	capital = 242
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62050 }
	}
	controlledprovinces = {
		242
		248
	}
}
country = {
	tag = SWIS
	form_of_goverment = republican
	capital = 245
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62085 }
	}
	controlledprovinces = {
		245
		244		
	}
	laws = {
		elective_law = yes
		popular_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = SAXO
	form_of_goverment = feudal
	capital = 311
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62100 }
	}
	controlledprovinces = {		
		311	
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C257
	form_of_goverment = feudal
	capital = 257
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62808 }
	}
	controlledprovinces = {
		257
	}
}
country = {
	tag = C258
	form_of_goverment = feudal
	capital = 258
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62835 }
	}
	controlledprovinces = {
		258
	}
}
country = {
	tag = BERW
	form_of_goverment = feudal
	capital = 120
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62823 }
	}
	controlledprovinces = {
		120
	}
}
country = {
	tag = C310
	form_of_goverment = feudal
	capital = 310
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62390 }
	}
	controlledprovinces = {
		310
	}
}
country = {
	tag = SAVO
	form_of_goverment = feudal
	capital = 237
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62154 }
	}
	controlledprovinces = {
		237
		228
		239
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C238
	form_of_goverment = feudal
	capital = 238
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62140 }
	}
	controlledprovinces = {
		238
	}
}
country = {
	tag = C241
	form_of_goverment = feudal
	capital = 241
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62092 }
	}
	controlledprovinces = {
		241
	}
}
country = {
	tag = BRAB
	form_of_goverment = feudal
	capital = 117
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87044 }
	}
	controlledprovinces = {
		117
		092
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = BRAN
	form_of_goverment = feudal
	capital = 365
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62731 }
	}
	controlledprovinces = {
		365
		309
		430
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = BAVA
	form_of_goverment = feudal
	capital = 361
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62760 }
	}
	controlledprovinces = {
		361
		447
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = MEIS
	form_of_goverment = feudal
	capital = 312
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62400 }
	}
	controlledprovinces = {
		312
		364
		255		
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = UPLO
	form_of_goverment = feudal
	capital = 127
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62550 }
	}
	controlledprovinces = {
		127
		128		
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C115
	form_of_goverment = feudal
	capital = 115
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62605 }
	}
	controlledprovinces = {
		115
	}
}
country = {
	tag = DBOH
	form_of_goverment = feudal
	capital = 437
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62610 }
	}
	controlledprovinces = {
		437
		362
		363
		436		
		439
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C433
	form_of_goverment = feudal
	capital = 433
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 71720 }
	}
	controlledprovinces = {
		433
	}
}
country = {
	tag = C434
	form_of_goverment = feudal
	capital = 434
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 71700 }
	}
	controlledprovinces = {
		434
	}
}
country = {
	tag = C435
	form_of_goverment = feudal
	capital = 435
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 71730 }
	}
	controlledprovinces = {
		435
	}
}
country = {
	tag = C526
	form_of_goverment = feudal
	capital = 526
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 71740 }
	}
	controlledprovinces = {
		526
	}
}
country = {
	tag = MORA
	form_of_goverment = feudal
	capital = 441
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62614 }
	}
	controlledprovinces = {
		441
		440
		438
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C133
	form_of_goverment = feudal
	capital = 133
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62630 }
	}
	controlledprovinces = {
		133
	}
}
country = {
	tag = C236
	form_of_goverment = feudal
	capital = 236
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62690 }
	}
	controlledprovinces = {
		236
	}
}
country = {
	tag = GERM
	form_of_goverment = feudal
	capital = 360
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62740 }
	}
	controlledprovinces = {
		360
		315
	}
	laws = {
		elective_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C082
	form_of_goverment = ecclestical
	capital = 082
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62006 }
	}
	controlledprovinces = {
		082
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C087
	form_of_goverment = ecclestical
	capital = 087
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62004 }
	}
	controlledprovinces = {
		087
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C088
	form_of_goverment = ecclestical
	capital = 088
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62003 }
	}
	controlledprovinces = {
		088
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C116
	form_of_goverment = ecclestical
	capital = 116
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62002 }
	}
	controlledprovinces = {
		116
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C119
	form_of_goverment = ecclestical
	capital = 119
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87032 }
	}
	controlledprovinces = {
		119
		118
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C121
	form_of_goverment = feudal
	capital = 121
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62362 }
	}
	controlledprovinces = {
		121
	}
}
country = {
	tag = C122
	form_of_goverment = feudal
	capital = 122
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62380 }
	}
	controlledprovinces = {
		122
	}
}
country = {
	tag = C123
	form_of_goverment = ecclestical
	capital = 123
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87017 }
	}
	controlledprovinces = {
		123
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C124
	form_of_goverment = feudal
	capital = 124
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62749 }
	}
	controlledprovinces = {
		124
	}
}
country = {
	tag = C125
	form_of_goverment = feudal
	capital = 125
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62310 }
	}
	controlledprovinces = {
		125
	}
}
country = {
	tag = C126
	form_of_goverment = ecclestical
	capital = 126
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62005 }
	}
	controlledprovinces = {
		126
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C249
	form_of_goverment = feudal
	capital = 249
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62350 }
	}
	controlledprovinces = {
		249
	}
}
country = {
	tag = C250
	form_of_goverment = feudal
	capital = 250
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62324 }
	}
	controlledprovinces = {
		250
	}
}
country = {
	tag = C251
	form_of_goverment = feudal
	capital = 251
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62337 }
	}
	controlledprovinces = {
		251
	}
}
country = {
	tag = C252
	form_of_goverment = republican
	capital = 252
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87016 }
	}
	controlledprovinces = {
		252
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C253
	form_of_goverment = feudal
	capital = 253
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62302 }
	}
	controlledprovinces = {
		253
	}
}
country = {
	tag = C254
	form_of_goverment = republican
	capital = 254
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62070 }
	}
	controlledprovinces = {
		254
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C256
	form_of_goverment = ecclestical
	capital = 256
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62824 }
	}
	controlledprovinces = {
		256
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C262
	form_of_goverment = republican
	capital = 262
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87019 }
	}
	controlledprovinces = {
		262
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C314
	form_of_goverment = feudal
	capital = 314
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87021 }
	}
	controlledprovinces = {
		314
	}
}
country = {
	tag = C317
	form_of_goverment = ecclestical
	capital = 317
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87014 }
	}
	controlledprovinces = {
		317
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C247
	form_of_goverment = ecclestical
	capital = 247
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87015 }
	}
	controlledprovinces = {
		247
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C448
	form_of_goverment = ecclestical
	capital = 448
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87010 }
	}
	controlledprovinces = {
		448
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C086
	form_of_goverment = feudal
	capital = 086
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62917 }
	}
	controlledprovinces = {
		086
	}
}
country = {
	tag = C316
	form_of_goverment = feudal
	capital = 316
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62710 }
	}
	controlledprovinces = {
		316
		359
	}
}
country = {
	tag = C089
	form_of_goverment = feudal
	capital = 089
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62920 }
	}
	controlledprovinces = {
		089
	}
}
country = {
	tag = C090
	form_of_goverment = feudal
	capital = 090
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 62930 }
	}
	controlledprovinces = {
		090
	}
}
country = {
	tag = C477
	form_of_goverment = feudal
	capital = 477
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 63120 }
	}
	controlledprovinces = {
		477
	}
}
country = {
	tag = KRET
	form_of_goverment = feudal
	capital = 480
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 63130 }
	}
	controlledprovinces = {
		480
		479
	}
}
country = {
	tag = MILA
	form_of_goverment = feudal
	capital = 234
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 63140 }
	}
	controlledprovinces = {
		234
		235
		246
		320
	}
	laws = {
		salic_primogeniture_law = yes
		popular_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = VERO
	form_of_goverment = feudal
	capital = 319
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 12078 }
	}
	controlledprovinces = {
		319
		318
		321		
	}
	laws = {
		salic_primogeniture_law = yes
		popular_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C355
	form_of_goverment = republican
	capital = 355
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 12072 }
	}
	controlledprovinces = {
		355
	}
}
country = {
	tag = C353
	form_of_goverment = republican
	capital = 353
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 63200 }
	}
	controlledprovinces = {
		353
		322
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C351
	form_of_goverment = ecclestical
	capital = 351
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 63210 }
	}
	controlledprovinces = {
		351
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C352
	form_of_goverment = republican
	capital = 352
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 63300 }
	}
	controlledprovinces = {
		352
	}
}
country = {
	tag = C358
	form_of_goverment = ecclestical
	capital = 358
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 13022 }
	}
	controlledprovinces = {
		358		
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = TOSC
	form_of_goverment = republican
	capital = 327
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 63320 }
	}
	controlledprovinces = {
		327
		328
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C329
	form_of_goverment = feudal
	capital = 329
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 63460 }
	}
	controlledprovinces = {
		329
	}
}
country = {
	tag = GENO
	form_of_goverment = republican
	capital = 233
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 63400 }
	}
	controlledprovinces = {
		233
		230
		324
		561
		486
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = LANG
	form_of_goverment = republican
	capital = 323
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 63450 }
	}
	controlledprovinces = {
		323		
		326
		331
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = VENI
	form_of_goverment = republican
	capital = 356
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 63600 }
	}
	controlledprovinces = {
		356
		458
		465
		467
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C003
	form_of_goverment = feudal
	capital = 003
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 64006 }
	}
	controlledprovinces = {
		003
	}
}
country = {
	tag = C004
	form_of_goverment = feudal
	capital = 004
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 64007 }
	}
	controlledprovinces = {
		004
	}
}
country = {
	tag = THES
	form_of_goverment = feudal
	capital = 490
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 65530 }
	}
	controlledprovinces = {
		490
		491		
		493
		494
		495
	}
}
country = {
	tag = C472
	form_of_goverment = feudal
	capital = 472
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 65517 }
	}
	controlledprovinces = {
		472
		473
	}
}
country = {
	tag = C488
	form_of_goverment = feudal
	capital = 488
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 65201 }
	}
	controlledprovinces = {
		488
	}
}
country = {
	tag = C489
	form_of_goverment = feudal
	capital = 489
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 65200 }
	}
	controlledprovinces = {
		489
	}
}
country = {
	tag = C487
	form_of_goverment = feudal
	capital = 487
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 65210 }
	}
	controlledprovinces = {
		487
	}
}
country = {
	tag = C481
	form_of_goverment = feudal
	capital = 481
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 65400 }
	}
	controlledprovinces = {
		481
		476
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = BYZA
	form_of_goverment = feudal
	capital = 496
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 65500 }
	}
	controlledprovinces = {
		496
		497
	}
	laws = {
		semisalic_primogeniture_law = yes
		royal_preorgatory_law = yes
		regal_supremacy = yes
	}
}
country = {
	tag = C232
	form_of_goverment = feudal
	capital = 232
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 65520 }
	}
	controlledprovinces = {
		232
	}
}
country = {
	tag = PELO
	form_of_goverment = feudal
	capital = 478
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 65550 }
	}
	controlledprovinces = {
		478
	}
}
country = {
	tag = TREB
	form_of_goverment = feudal
	capital = 678
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 65800 }
	}
	controlledprovinces = {
		678		
		562
		598
	}
	laws = {
		semisalic_primogeniture_law = yes
		royal_preorgatory_law = yes
		regal_supremacy = yes
	}
}
country = {
	tag = GEOR
	form_of_goverment = feudal
	capital = 676
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 66500 }
	}
	controlledprovinces = {
		676
		679
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		regal_supremacy = yes
	}
}
country = {
	tag = DGEO
	form_of_goverment = feudal
	capital = 677
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 66753 }
	}
	controlledprovinces = {
		677
	}
}
country = {
	tag = IMER
	form_of_goverment = feudal
	capital = 601
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 66520 }
	}
	controlledprovinces = {
		601
		600
	}
}
country = {
	tag = BULG
	form_of_goverment = feudal
	capital = 499
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 67500 }
	}
	controlledprovinces = {
		499
		506
		507
		508
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		regal_supremacy = yes
	}
}
country = {
	tag = C470
	form_of_goverment = feudal
	capital = 470
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 67502 }
	}
	controlledprovinces = {
		470
	}
}
country = {
	tag = C498
	form_of_goverment = feudal
	capital = 498
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 67503 }
	}
	controlledprovinces = {
		498
	}
}
country = {
	tag = C500
	form_of_goverment = feudal
	capital = 500
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 67505 }
	}
	controlledprovinces = {
		500
	}
}
country = {
	tag = VARN
	form_of_goverment = feudal
	capital = 509
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 67550 }
	}
	controlledprovinces = {
		509
		510
		511
	}
}
country = {
	tag = SERB
	form_of_goverment = feudal
	capital = 505
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 68500 }
	}
	controlledprovinces = {
		505
		502
		468
		469
		492
		503
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		regal_supremacy = yes
	}
}
country = {
	tag = C471
	form_of_goverment = feudal
	capital = 471
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 68550 }
	}
	controlledprovinces = {
		471
	}
}
country = {
	tag = C501
	form_of_goverment = feudal
	capital = 501
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 67523 }
	}
	controlledprovinces = {
		501
	}
}
country = {
	tag = NOSE
	form_of_goverment = feudal
	capital = 504
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 68800 }
	}
	controlledprovinces = {
		504
		
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		regal_supremacy = yes
	}
}
country = {
	tag = C463
	form_of_goverment = feudal
	capital = 463
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 68805 }
	}
	controlledprovinces = {
		463
	}
}
country = {
	tag = HUNG
	form_of_goverment = feudal
	capital = 522
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 69500 }
	}
	controlledprovinces = {
		522
		443
		445
		451
		452
		453
		525				
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C444
	form_of_goverment = ecclestical
	capital = 444
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70133 }
	}
	controlledprovinces = {
		444
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C523
	form_of_goverment = feudal
	capital = 523
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70212 }
	}
	controlledprovinces = {
		523
	}
}
country = {
	tag = C450
	form_of_goverment = feudal
	capital = 450
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70101 }
	}
	controlledprovinces = {
		450
	}
}
country = {
	tag = C524
	form_of_goverment = feudal
	capital = 524
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70181 }
	}
	controlledprovinces = {
		524
	}
}
country = {
	tag = C533
	form_of_goverment = feudal
	capital = 533
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70186 }
	}
	controlledprovinces = {
		533
	}
}
country = {
	tag = C537
	form_of_goverment = feudal
	capital = 537
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70191 }
	}
	controlledprovinces = {
		537
	}
}
country = {
	tag = C518
	form_of_goverment = feudal
	capital = 518
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70151 }
	}
	controlledprovinces = {
		518
	}
}
country = {
	tag = C521
	form_of_goverment = feudal
	capital = 521
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70135 }
	}
	controlledprovinces = {
		521
	}
}
country = {
	tag = C442
	form_of_goverment = feudal
	capital = 442
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70160 }
	}
	controlledprovinces = {
		442
	}
}
country = {
	tag = C462
	form_of_goverment = feudal
	capital = 462
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70112 }
	}
	controlledprovinces = {
		462
	}
}
country = {
	tag = C454
	form_of_goverment = feudal
	capital = 454
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70122 }
	}
	controlledprovinces = {
		454
	}
}
country = {
	tag = C464
	form_of_goverment = feudal
	capital = 464
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70000 }
	}
	controlledprovinces = {
		464
	}
}
country = {
	tag = DCRO
	form_of_goverment = feudal
	capital = 461
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70030 }
	}
	controlledprovinces = {
		461
	}
}
country = {
	tag = SZEK
	form_of_goverment = feudal
	capital = 540
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70040 }
	}
	controlledprovinces = {
		540
		517
		519
	}
}
country = {
	tag = C460
	form_of_goverment = feudal
	capital = 460
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70111 }
	}
	controlledprovinces = {
		460
	}
}
country = {
	tag = C520
	form_of_goverment = feudal
	capital = 520
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70062 }
	}
	controlledprovinces = {
		520
	}
}
country = {
	tag = C538
	form_of_goverment = feudal
	capital = 538
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70202 }
	}
	controlledprovinces = {
		538
	}
}
country = {
	tag = C539
	form_of_goverment = feudal
	capital = 539
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70070 }
	}
	controlledprovinces = {
		539
	}
}
country = {
	tag = C459
	form_of_goverment = feudal
	capital = 459
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 70021 }
	}
	controlledprovinces = {
		459
	}
}
country = {
	tag = C466
	form_of_goverment = feudal
	capital = 466
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 68850 }
	}
	controlledprovinces = {
		466
	}
}
country = {
	tag = POLA
	form_of_goverment = feudal
	capital = 527
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 71500 }
	}
	controlledprovinces = {
		429
		431
		531
		527
		432
		528
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = MAZO
	form_of_goverment = feudal
	capital = 529
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 71515 }
	}
	controlledprovinces = {
		529
	}
}
country = {
	tag = C530
	form_of_goverment = feudal
	capital = 530
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 71518 }
	}
	controlledprovinces = {
		530
	}
}
country = {
	tag = C428
	form_of_goverment = feudal
	capital = 428
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 71535 }
	}
	controlledprovinces = {
		428
	}
}
country = {
	tag = C532
	form_of_goverment = feudal
	capital = 532
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 71560 }
	}
	controlledprovinces = {
		532
	}
}
country = {
	tag = C308
	form_of_goverment = feudal
	capital = 308
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 51950 }
	}
	controlledprovinces = {
		308
	}
	laws = {
		salic_primogeniture_law = yes
		feudal_contract_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C404
	form_of_goverment = feudal
	capital = 404
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72000 }
	}
	controlledprovinces = {
		404
	}
}
country = {
	tag = C405
	form_of_goverment = feudal
	capital = 405
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72001 }
	}
	controlledprovinces = {
		405
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C406
	form_of_goverment = feudal
	capital = 406
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72002 }
	}
	controlledprovinces = {
		406
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C407
	form_of_goverment = feudal
	capital = 407
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72003 }
	}
	controlledprovinces = {
		407
	}
}
country = {
	tag = KIEV
	form_of_goverment = feudal
	capital = 547
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72100 }
	}
	controlledprovinces = {
		547
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C544
	form_of_goverment = feudal
	capital = 544
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72101 }
	}
	controlledprovinces = {
		544
	}
}
country = {
	tag = C546
	form_of_goverment = feudal
	capital = 546
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72102 }
	}
	controlledprovinces = {
		546
	}
}
country = {
	tag = SUZD
	form_of_goverment = feudal
	capital = 554
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72250 }
	}
	controlledprovinces = {
		554
		551
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = NOVG
	form_of_goverment = republican
	capital = 410
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72300 }
	}
	controlledprovinces = {
		410
	}
	laws = {
		elective_law = yes
		popular_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C411
	form_of_goverment = feudal
	capital = 411
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 73504 }
	}
	controlledprovinces = {
		411
		388
		392
	}
}
country = {
	tag = C387
	form_of_goverment = feudal
	capital = 387
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72301 }
	}
	controlledprovinces = {
		387
	}
}
country = {
	tag = C393
	form_of_goverment = feudal
	capital = 393
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72305 }
	}
	controlledprovinces = {
		393
	}
}
country = {
	tag = C394
	form_of_goverment = feudal
	capital = 394
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72306 }
	}
	controlledprovinces = {
		394
	}
}
country = {
	tag = C395
	form_of_goverment = feudal
	capital = 395
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72307 }
	}
	controlledprovinces = {
		395
	}
}
country = {
	tag = C396
	form_of_goverment = feudal
	capital = 396
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72308 }
	}
	controlledprovinces = {
		396
	}
}
country = {
	tag = C397
	form_of_goverment = feudal
	capital = 397
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72309 }
	}
	controlledprovinces = {
		397
	}
}
country = {
	tag = C398
	form_of_goverment = feudal
	capital = 398
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72310 }
	}
	controlledprovinces = {
		398
	}
}
country = {
	tag = C399
	form_of_goverment = feudal
	capital = 399
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72311 }
	}
	controlledprovinces = {
		399
	}
}
country = {
	tag = C403
	form_of_goverment = feudal
	capital = 403
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72312 }
	}
	controlledprovinces = {
		403
	}
}
country = {
	tag = C409
	form_of_goverment = feudal
	capital = 409
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72313 }
	}
	controlledprovinces = {
		409
	}
}
country = {
	tag = C412
	form_of_goverment = feudal
	capital = 412
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72315 }
	}
	controlledprovinces = {
		412
	}
}
country = {
	tag = C414
	form_of_goverment = feudal
	capital = 414
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72316 }
	}
	controlledprovinces = {
		414
	}
}
country = {
	tag = C415
	form_of_goverment = feudal
	capital = 415
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72317 }
	}
	controlledprovinces = {
		415
	}
}
country = {
	tag = C402
	form_of_goverment = feudal
	capital = 402
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72318 }
	}
	controlledprovinces = {
		402
	}
}
country = {
	tag = C400
	form_of_goverment = feudal
	capital = 400
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72319 }
	}
	controlledprovinces = {
		400
	}
}
country = {
	tag = C401
	form_of_goverment = feudal
	capital = 401
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72320 }
	}
	controlledprovinces = {
		401
	}
}
country = {
	tag = PRON
	form_of_goverment = feudal
	capital = 567
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72400 }
	}
	controlledprovinces = {
		567
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = PERE
	form_of_goverment = republican
	capital = 555
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72450 }
	}
	controlledprovinces = {
		555
		565
	}
	laws = {
		elective_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = SMOL
	form_of_goverment = feudal
	capital = 568
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72500 }
	}
	controlledprovinces = {
		568
		569
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C576
	form_of_goverment = feudal
	capital = 576
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72510 }
	}
	controlledprovinces = {
		576
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = RYAZ
	form_of_goverment = feudal
	capital = 580
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72520 }
	}
	controlledprovinces = {
		580
		581		
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C577
	form_of_goverment = feudal
	capital = 577
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72630 }
	}
	controlledprovinces = {
		577
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C573
	form_of_goverment = feudal
	capital = 573
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72640 }
	}
	controlledprovinces = {
		573
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C553
	form_of_goverment = feudal
	capital = 553
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72780 }
	}
	controlledprovinces = {
		553
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = YARO
	form_of_goverment = feudal
	capital = 572
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72790 }
	}
	controlledprovinces = {
		572
		571
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = ROST
	form_of_goverment = feudal
	capital = 574
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72800 }
	}
	controlledprovinces = {
		574
	}
}
country = {
	tag = BELO
	form_of_goverment = feudal
	capital = 408
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72820 }
	}
	controlledprovinces = {
		408
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C586
	form_of_goverment = feudal
	capital = 586
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72830 }
	}
	controlledprovinces = {
		586
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = MOSK
	form_of_goverment = feudal
	capital = 575
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72840 }
	}
	controlledprovinces = {
		575
		578
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C582
	form_of_goverment = feudal
	capital = 582
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72847 }
	}
	controlledprovinces = {
		582
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = TVER
	form_of_goverment = feudal
	capital = 570
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72860 }
	}
	controlledprovinces = {
		570
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C413
	form_of_goverment = feudal
	capital = 413
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72868 }
	}
	controlledprovinces = {
		413
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = GALI
	form_of_goverment = feudal
	capital = 536
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72900 }
	}
	controlledprovinces = {
		536
		534
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = VLAD
	form_of_goverment = feudal
	capital = 583
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72910 }
	}
	controlledprovinces = {
		583
		584
		585
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = LITH
	form_of_goverment = feudal
	capital = 423
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 73500 }
	}
	controlledprovinces = {
		423
		420
		424
		548
		549
		552
		550
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = SAMO
	form_of_goverment = feudal
	capital = 421
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 73508 }
	}
	controlledprovinces = {
		421
		374
		422
		425
		426
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = POLO
	form_of_goverment = feudal
	capital = 419
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 72350 }
	}
	controlledprovinces = {
		419
		416
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C535
	form_of_goverment = feudal
	capital = 535
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 73510 }
	}
	controlledprovinces = {
		535
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C417
	form_of_goverment = feudal
	capital = 417
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 73506 }
	}
	controlledprovinces = {
		417
		418
	}
}
country = {
	tag = TEUT
	form_of_goverment = knight_order
	capital = 370
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 74000 }
	}
	controlledprovinces = {
		370
		369	
		372	
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C368
	form_of_goverment = knight_order
	capital = 368
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 74020 }
	}
	controlledprovinces = {
		368
	}
}
country = {
	tag = C371
	form_of_goverment = ecclestical
	capital = 371
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 74040 }
	}
	controlledprovinces = {
		371
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C375
	form_of_goverment = ecclestical
	capital = 375
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 74070 }
	}
	controlledprovinces = {
		375
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C376
	form_of_goverment = knight_order
	capital = 376
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 74080 }
	}
	controlledprovinces = {
		376
	}
}
country = {
	tag = U001
	form_of_goverment = knight_order
	capital = 377
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 74090 }
	}
	controlledprovinces = {
		377
		373
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C379
	form_of_goverment = ecclestical
	capital = 379
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 74100 }
	}
	controlledprovinces = {
		379
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C427
	form_of_goverment = knight_order
	capital = 427
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 74130 }
	}
	controlledprovinces = {
		427
	}
}
country = {
	tag = C513
	form_of_goverment = feudal
	capital = 513
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 75100 }
	}
	controlledprovinces = {
		513
	}
}
country = {
	tag = C515
	form_of_goverment = feudal
	capital = 515
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 75200 }
	}
	controlledprovinces = {
		515
	}
}
country = {
	tag = C516
	form_of_goverment = feudal
	capital = 516
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 75300 }
	}
	controlledprovinces = {
		516
	}
}
country = {
	tag = MOLD
	form_of_goverment = feudal
	capital = 512
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 75400 }
	}
	controlledprovinces = {
		512
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C541
	form_of_goverment = feudal
	capital = 541
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 75410 }
	}
	controlledprovinces = {
		541
	}
}
country = {
	tag = C542
	form_of_goverment = feudal
	capital = 542
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 75420 }
	}
	controlledprovinces = {
		542
	}
}
country = {
	tag = C545
	form_of_goverment = feudal
	capital = 545
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 75430 }
	}
	controlledprovinces = {
		545
	}
}
country = {
	tag = WALL
	form_of_goverment = feudal
	capital = 514
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 75550 }
	}
	controlledprovinces = {
		514
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = MENT
	form_of_goverment = feudal
	capital = 747
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 76100 }
	}
	controlledprovinces = {
		747
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = SARU
	form_of_goverment = feudal
	capital = 745
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 76150 }
	}
	controlledprovinces = {
		745
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = AYDI
	form_of_goverment = feudal
	capital = 746
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 76200 }
	}
	controlledprovinces = {
		746
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = GERI
	form_of_goverment = feudal
	capital = 748
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 76250 }
	}
	controlledprovinces = {
		748
		749
		754
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = KARM
	form_of_goverment = feudal
	capital = 758
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 76300 }
	}
	controlledprovinces = {
		758
		759
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = CAND
	form_of_goverment = feudal
	capital = 704
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 76350 }
	}
	controlledprovinces = {
		704
		738
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = TEKK
	form_of_goverment = feudal
	capital = 755
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 76400 }
	}
	controlledprovinces = {
		755
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = ERET
	form_of_goverment = feudal
	capital = 753
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 76450 }
	}
	controlledprovinces = {
		753
		752
		760
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = DMES
	form_of_goverment = feudal
	capital = 705
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 76460 }
	}
	controlledprovinces = {
		705
		702
		703
	}
}
country = {
	tag = C737
	form_of_goverment = feudal
	capital = 737
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 76470 }
	}
	controlledprovinces = {
		736
		737
	}
}
country = {
	tag = SINO
	form_of_goverment = feudal
	capital = 739
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 76480 }
	}
	controlledprovinces = {
		739
		751
	}
}
country = {
	tag = OTTO
	form_of_goverment = feudal
	capital = 742
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 76500 }
	}
	controlledprovinces = {
		742
		741
		743
		740
		750
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C744
	form_of_goverment = feudal
	capital = 744
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 76510 }
	}
	controlledprovinces = {
		744
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = ILKH
	form_of_goverment = feudal
	capital = 667
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78030 }
	}
	controlledprovinces = {
		646
		658
		659
		667
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = SHIR
	form_of_goverment = feudal
	capital = 644
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78015 }
	}
	controlledprovinces = {
		640
		642
		643
		644
		645
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C657
	form_of_goverment = feudal
	capital = 657
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78020 }
	}
	controlledprovinces = {
		657
	}
}
country = {
	tag = C648
	form_of_goverment = feudal
	capital = 648
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78021 }
	}
	controlledprovinces = {
		647
		648
	}
}
country = {
	tag = HORM
	form_of_goverment = feudal
	capital = 641
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78022 }
	}
	controlledprovinces = {
		639
		641
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C638
	form_of_goverment = feudal
	capital = 638
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78024 }
	}
	controlledprovinces = {
		638
	}
}
country = {
	tag = MSIS
	form_of_goverment = feudal
	capital = 637
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78025 }
	}
	controlledprovinces = {
		637
	}
}
country = {
	tag = LUTA
	form_of_goverment = feudal
	capital = 636
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78026 }
	}
	controlledprovinces = {
		634
		636
	}
}
country = {
	tag = C632
	form_of_goverment = feudal
	capital = 632
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78027 }
	}
	controlledprovinces = {
		632
	}
}
country = {
	tag = C635
	form_of_goverment = feudal
	capital = 635
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78028 }
	}
	controlledprovinces = {
		635
	}
}
country = {
	tag = C667
	form_of_goverment = feudal
	capital = 667
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78030 }
	}
	controlledprovinces = {
		667
		666
		685
		686		
	}
}
country = {
	tag = AZER
	form_of_goverment = feudal
	capital = 670
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78031 }
	}
	controlledprovinces = {
		670
	}
}
country = {
	tag = QOMA
	form_of_goverment = feudal
	capital = 663
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78033 }
	}
	controlledprovinces = {
		660
		663
		665
	}
}
country = {
	tag = MBAG
	form_of_goverment = feudal
	capital = 693
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78040 }
	}
	controlledprovinces = {
		693
		664
		694
		649
		655
		656
		687
		688
		689
		690
		691
		692
		695
		696
		697
		684
		698
		711
		712
		715
		682
		671
		672
		680
		681
		683
		700
		701
	}
}
country = {
	tag = KARA
	form_of_goverment = feudal
	capital = 628
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78050 }
	}
	controlledprovinces = {
		628
		626
		629
		630
		631
	}
}
country = {
	tag = MEDE
	form_of_goverment = feudal
	capital = 683
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78070 }
	}
	controlledprovinces = {
		683
		699
		700
		701
		706
		707
		708
		734
	}
}
country = {
	tag = MAZA
	form_of_goverment = feudal
	capital = 633
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78080 }
	}
	controlledprovinces = {
		633
		661
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C669
	form_of_goverment = feudal
	capital = 669
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78090 }
	}
	controlledprovinces = {
		669
		668
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = GILA
	form_of_goverment = feudal
	capital = 662
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78100 }
	}
	controlledprovinces = {
		662
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = PAPA
	form_of_goverment = ecclestical
	capital = 222
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78501 }
	}
	controlledprovinces = {
		222
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = HOSP
	form_of_goverment = knight_order
	capital = 483
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78502 }
	}
	controlledprovinces = {
		483
	}
	laws = {
		elective_law = yes
		royal_preorgatory_law = yes
		church_supremacy = yes
	}
}
country = {
	tag = C333
	form_of_goverment = ecclestical
	capital = 333
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 78503 }
	}
	controlledprovinces = {
		333	
	}
}
country = {
	tag = CUMA
	form_of_goverment = feudal
	capital = 614
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79000 }
	}
	controlledprovinces = {
		614
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C615
	form_of_goverment = feudal
	capital = 615
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79010 }
	}
	controlledprovinces = {
		615
	}
}
country = {
	tag = C616
	form_of_goverment = feudal
	capital = 616
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79020 }
	}
	controlledprovinces = {
		616
	}
}
country = {
	tag = C607
	form_of_goverment = feudal
	capital = 607
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79040 }
	}
	controlledprovinces = {
		607
	}
}
country = {
	tag = C543
	form_of_goverment = feudal
	capital = 543
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79050 }
	}
	controlledprovinces = {
		543
	}
}
country = {
	tag = C556
	form_of_goverment = feudal
	capital = 556
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79060 }
	}
	controlledprovinces = {
		556
	}
}
country = {
	tag = C564
	form_of_goverment = feudal
	capital = 564
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79070 }
	}
	controlledprovinces = {
		564
	}
}
country = {
	tag = C566
	form_of_goverment = feudal
	capital = 566
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79080 }
	}
	controlledprovinces = {
		566
	}
}
country = {
	tag = C594
	form_of_goverment = feudal
	capital = 594
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79090 }
	}
	controlledprovinces = {
		594
	}
}
country = {
	tag = C595
	form_of_goverment = feudal
	capital = 595
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79100 }
	}
	controlledprovinces = {
		595
	}
}
country = {
	tag = C618
	form_of_goverment = feudal
	capital = 618
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79110 }
	}
	controlledprovinces = {
		618
	}
}
country = {
	tag = C619
	form_of_goverment = feudal
	capital = 619
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79120 }
	}
	controlledprovinces = {
		619
	}
}
country = {
	tag = C620
	form_of_goverment = feudal
	capital = 620
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79130 }
	}
	controlledprovinces = {
		620
	}
}
country = {
	tag = C621
	form_of_goverment = feudal
	capital = 621
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79140 }
	}
	controlledprovinces = {
		621
	}
}
country = {
	tag = C622
	form_of_goverment = feudal
	capital = 622
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79150 }
	}
	controlledprovinces = {
		622
	}
}
country = {
	tag = C623
	form_of_goverment = feudal
	capital = 623
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79160 }
	}
	controlledprovinces = {
		623
	}
}
country = {
	tag = C624
	form_of_goverment = feudal
	capital = 624
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79170 }
	}
	controlledprovinces = {
		624
	}
}
country = {
	tag = C625
	form_of_goverment = feudal
	capital = 625
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79180 }
	}
	controlledprovinces = {
		625
	}
}
country = {
	tag = C627
	form_of_goverment = feudal
	capital = 627
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79190 }
	}
	controlledprovinces = {
		627
	}
}
country = {
	tag = KHAZ
	form_of_goverment = feudal
	capital = 557
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79200 }
	}
	controlledprovinces = {
		557
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C558
	form_of_goverment = feudal
	capital = 558
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79210 }
	}
	controlledprovinces = {
		558
	}
}
country = {
	tag = C559
	form_of_goverment = feudal
	capital = 559
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79220 }
	}
	controlledprovinces = {
		559 560		
	}
}
country = {
	tag = C563
	form_of_goverment = feudal
	capital = 563
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79230 }
	}
	controlledprovinces = {
		563
	}
}
country = {
	tag = C596
	form_of_goverment = feudal
	capital = 596
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 79240 }
	}
	controlledprovinces = {
		596
	}
}
country = {
	tag = GOLD
	form_of_goverment = feudal
	capital = 608
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80000 }
	}
	controlledprovinces = {
		608
	}
	laws = {
		semisalic_consanguinity_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C609
	form_of_goverment = feudal
	capital = 609
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80010 }
	}
	controlledprovinces = {
		609
	}
}
country = {
	tag = C617
	form_of_goverment = feudal
	capital = 617
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80020 }
	}
	controlledprovinces = {
		617
	}
}
country = {
	tag = C612
	form_of_goverment = feudal
	capital = 612
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80040 }
	}
	controlledprovinces = {
		612
	}
}
country = {
	tag = C588
	form_of_goverment = feudal
	capital = 588
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80080 }
	}
	controlledprovinces = {
		588
	}
}
country = {
	tag = C590
	form_of_goverment = feudal
	capital = 590
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80090 }
	}
	controlledprovinces = {
		590
	}
}
country = {
	tag = C591
	form_of_goverment = feudal
	capital = 591
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80100 }
	}
	controlledprovinces = {
		591
	}
}
country = {
	tag = C592
	form_of_goverment = feudal
	capital = 592
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80110 }
	}
	controlledprovinces = {
		592
	}
}
country = {
	tag = C593
	form_of_goverment = feudal
	capital = 593
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80120 }
	}
	controlledprovinces = {
		593
	}
}
country = {
	tag = C610
	form_of_goverment = feudal
	capital = 610
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80130 }
	}
	controlledprovinces = {
		610
	}
}
country = {
	tag = ALAN
	form_of_goverment = feudal
	capital = 597
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80140 }
	}
	controlledprovinces = {
		597
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C599
	form_of_goverment = feudal
	capital = 599
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80150 }
	}
	controlledprovinces = {
		599
	}
}
country = {
	tag = C604
	form_of_goverment = feudal
	capital = 604
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80160 }
	}
	controlledprovinces = {
		604
	}
}
country = {
	tag = C605
	form_of_goverment = feudal
	capital = 605
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80170 }
	}
	controlledprovinces = {
		605
	}
}
country = {
	tag = C606
	form_of_goverment = feudal
	capital = 606
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80180 }
	}
	controlledprovinces = {
		606
	}
}
country = {
	tag = C602
	form_of_goverment = feudal
	capital = 602
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80200 }
	}
	controlledprovinces = {
		602
	}
}
country = {
	tag = C603
	form_of_goverment = feudal
	capital = 603
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80210 }
	}
	controlledprovinces = {
		603
	}
}
country = {
	tag = C673
	form_of_goverment = feudal
	capital = 673
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80220 }
	}
	controlledprovinces = {
		673
	}
}
country = {
	tag = C674
	form_of_goverment = feudal
	capital = 674
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80230 }
	}
	controlledprovinces = {
		674
	}
}
country = {
	tag = C675
	form_of_goverment = feudal
	capital = 675
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80240 }
	}
	controlledprovinces = {
		675
	}
}
country = {
	tag = VOLG
	form_of_goverment = feudal
	capital = 611
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80250 }
	}
	controlledprovinces = {
		611
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = C587
	form_of_goverment = feudal
	capital = 587
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80260 }
	}
	controlledprovinces = {
		587
	}
}
country = {
	tag = C589
	form_of_goverment = feudal
	capital = 589
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80270 }
	}
	controlledprovinces = {
		589
	}
}
country = {
	tag = C613
	form_of_goverment = feudal
	capital = 613
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 80280 }
	}
	controlledprovinces = {
		613
	}
}
country = {
	tag = MARI
	form_of_goverment = feudal
	capital = 843
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 82000 }
	}
	controlledprovinces = {
		843
		840
		842
		844
		845
		846
		847
	}
	laws = {
		semisalic_consanguinity_law = yes
		royal_preorgatory_law = yes
		regal_supremacy = yes
	}
}
country = {
	tag = C836
	form_of_goverment = feudal
	capital = 836
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 82010 }
	}
	controlledprovinces = {
		836
	}
}
country = {
	tag = C837
	form_of_goverment = feudal
	capital = 837
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 82020 }
	}
	controlledprovinces = {
		837
	}
}
country = {
	tag = C838
	form_of_goverment = feudal
	capital = 838
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 82030 }
	}
	controlledprovinces = {
		838
	}
}
country = {
	tag = C839
	form_of_goverment = feudal
	capital = 839
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 82040 }
	}
	controlledprovinces = {
		839
	}
}
country = {
	tag = C841
	form_of_goverment = feudal
	capital = 841
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 82050 }
	}
	controlledprovinces = {
		841
	}
}
country = {
	tag = KAFS
	form_of_goverment = feudal
	capital = 817
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 83000 }
	}
	controlledprovinces = {
		817
	}
	laws = {
		semisalic_consanguinity_law = yes
		royal_preorgatory_law = yes
		regal_supremacy = yes
	}
}
country = {
	tag = C809
	form_of_goverment = feudal
	capital = 809
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 83010 }
	}
	controlledprovinces = {
		809
	}
}
country = {
	tag = C810
	form_of_goverment = feudal
	capital = 810
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 83020 }
	}
	controlledprovinces = {
		810
	}
}
country = {
	tag = C811
	form_of_goverment = feudal
	capital = 811
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 83030 }
	}
	controlledprovinces = {
		811
	}
}
country = {
	tag = C813
	form_of_goverment = feudal
	capital = 813
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 83040 }
	}
	controlledprovinces = {
		813
	}
}
country = {
	tag = C814
	form_of_goverment = feudal
	capital = 814
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 83050 }
	}
	controlledprovinces = {
		814
	}
}
country = {
	tag = C815
	form_of_goverment = feudal
	capital = 815
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 83060 }
	}
	controlledprovinces = {
		815
	}
}
country = {
	tag = C816
	form_of_goverment = feudal
	capital = 816
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 83070 }
	}
	controlledprovinces = {
		816
	}
}
country = {
	tag = C818
	form_of_goverment = feudal
	capital = 818
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 83080 }
	}
	controlledprovinces = {
		818
	}
}
country = {
	tag = C819
	form_of_goverment = feudal
	capital = 819
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 83090 }
	}
	controlledprovinces = {
		819
	}
}
country = {
	tag = C820
	form_of_goverment = feudal
	capital = 820
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 83100 }
	}
	controlledprovinces = {
		820
	}
}
country = {
	tag = C821
	form_of_goverment = feudal
	capital = 821
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 83110 }
	}
	controlledprovinces = {
		821
	}
}
country = {
	tag = C822
	form_of_goverment = feudal
	capital = 822
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 83120 }
	}
	controlledprovinces = {
		822
	}
}
country = {
	tag = ZIYA
	form_of_goverment = feudal
	capital = 834
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 84000 }
	}
	controlledprovinces = {
		834
	}
	laws = {
		semisalic_consanguinity_law = yes
		royal_preorgatory_law = yes
		regal_supremacy = yes
	}
}
country = {
	tag = C835
	form_of_goverment = feudal
	capital = 835
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 84010 }
	}
	controlledprovinces = {
		835
	}
}
country = {
	tag = C823
	form_of_goverment = feudal
	capital = 823
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 84020 }
	}
	controlledprovinces = {
		823
	}
}
country = {
	tag = C825
	form_of_goverment = feudal
	capital = 825
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 84030 }
	}
	controlledprovinces = {
		825
	}
}
country = {
	tag = C824
	form_of_goverment = feudal
	capital = 824
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 84040 }
	}
	controlledprovinces = {
		824
	}
}
country = {
	tag = C828
	form_of_goverment = feudal
	capital = 828
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 84050 }
	}
	controlledprovinces = {
		828
	}
}
country = {
	tag = C829
	form_of_goverment = feudal
	capital = 829
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 84060 }
	}
	controlledprovinces = {
		829
	}
}
country = {
	tag = C830
	form_of_goverment = feudal
	capital = 830
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 84070 }
	}
	controlledprovinces = {
		830
	}
}
country = {
	tag = C831
	form_of_goverment = feudal
	capital = 831
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 84080 }
	}
	controlledprovinces = {
		831
	}
}
country = {
	tag = C832
	form_of_goverment = feudal
	capital = 832
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 84090 }
	}
	controlledprovinces = {
		832
	}
}
country = {
	tag = C833
	form_of_goverment = feudal
	capital = 833
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 84100 }
	}
	controlledprovinces = {
		833
	}
}
country = {
	tag = FATI
	form_of_goverment = feudal
	capital = 797
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85000 }
	}
	controlledprovinces = {
		797
		790
		791
		792
		793
		794
		795
		796
		789
		798
		799
		800
		801
		802
	}
	laws = {
		semisalic_consanguinity_law = yes
		royal_preorgatory_law = yes
		regal_supremacy = yes
	}
}
country = {
	tag = C786
	form_of_goverment = feudal
	capital = 786
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85010 }
	}
	controlledprovinces = {
		786
	}
}
country = {
	tag = C788
	form_of_goverment = feudal
	capital = 788
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85020 }
	}
	controlledprovinces = {
		788
	}
}
country = {
	tag = C719
	form_of_goverment = feudal
	capital = 719
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85030 }
	}
	controlledprovinces = {
		719
	}
}
country = {
	tag = C716
	form_of_goverment = feudal
	capital = 716
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85040 }
	}
	controlledprovinces = {
		716
	}
}
country = {
	tag = C717
	form_of_goverment = feudal
	capital = 717
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85050 }
	}
	controlledprovinces = {
		717
	}
}
country = {
	tag = MMED
	form_of_goverment = feudal
	capital = 718
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85060 }
	}
	controlledprovinces = {
		718
	}
}
country = {
	tag = C720
	form_of_goverment = feudal
	capital = 720
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85080 }
	}
	controlledprovinces = {
		720
	}
}
country = {
	tag = C721
	form_of_goverment = feudal
	capital = 721
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85090 }
	}
	controlledprovinces = {
		721
	}
}
country = {
	tag = MAMM
	form_of_goverment = feudal
	capital = 724
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85100 }
	}
	controlledprovinces = {
		724
		808
	}
}
country = {
	tag = C713
	form_of_goverment = feudal
	capital = 713
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85110 }
	}
	controlledprovinces = {
		713
		803
	}
}
country = {
	tag = C714
	form_of_goverment = feudal
	capital = 714
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85120 }
	}
	controlledprovinces = {
		714
		804
	}
}
country = {
	tag = C722
	form_of_goverment = feudal
	capital = 722
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85130 }
	}
	controlledprovinces = {
		722
		805
	}
}
country = {
	tag = C723
	form_of_goverment = feudal
	capital = 723
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85140 }
	}
	controlledprovinces = {
		723
		806
	}
}
country = {
	tag = C725
	form_of_goverment = feudal
	capital = 725
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85150 }
	}
	controlledprovinces = {
		725
		807
	}
}
country = {
	tag = C726
	form_of_goverment = feudal
	capital = 726
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85160 }
	}
	controlledprovinces = {
		726
	}
}
country = {
	tag = C777
	form_of_goverment = feudal
	capital = 777
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85170 }
	}
	controlledprovinces = {
		777
	}
}
country = {
	tag = C772
	form_of_goverment = feudal
	capital = 772
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85180 }
	}
	controlledprovinces = {
		772
	}
}
country = {
	tag = C769
	form_of_goverment = feudal
	capital = 769
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85190 }
	}
	controlledprovinces = {
		769
	}
}
country = {
	tag = C770
	form_of_goverment = feudal
	capital = 770
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85200 }
	}
	controlledprovinces = {
		770
	}
}
country = {
	tag = C771
	form_of_goverment = feudal
	capital = 771
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85210 }
	}
	controlledprovinces = {
		771
	}
}
country = {
	tag = C773
	form_of_goverment = feudal
	capital = 773
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85220 }
	}
	controlledprovinces = {
		773
	}
}
country = {
	tag = MJER
	form_of_goverment = feudal
	capital = 774
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85230 }
	}
	controlledprovinces = {
		774
	}
}
country = {
	tag = C775
	form_of_goverment = feudal
	capital = 775
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85240 }
	}
	controlledprovinces = {
		775
	}
}
country = {
	tag = C776
	form_of_goverment = feudal
	capital = 776
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85250 }
	}
	controlledprovinces = {
		776
	}
}
country = {
	tag = C778
	form_of_goverment = feudal
	capital = 778
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85260 }
	}
	controlledprovinces = {
		778
	}
}
country = {
	tag = C779
	form_of_goverment = feudal
	capital = 779
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85270 }
	}
	controlledprovinces = {
		779
	}
}
country = {
	tag = C780
	form_of_goverment = feudal
	capital = 780
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85280 }
	}
	controlledprovinces = {
		780
	}
}
country = {
	tag = MTRI
	form_of_goverment = feudal
	capital = 767
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85290 }
	}
	controlledprovinces = {
		767
	}
}
country = {
	tag = C733
	form_of_goverment = feudal
	capital = 733
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85300 }
	}
	controlledprovinces = {
		733
	}
}
country = {
	tag = C764
	form_of_goverment = feudal
	capital = 764
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85320 }
	}
	controlledprovinces = {
		764
	}
}
country = {
	tag = C765
	form_of_goverment = feudal
	capital = 765
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85330 }
	}
	controlledprovinces = {
		765
	}
}
country = {
	tag = C766
	form_of_goverment = feudal
	capital = 766
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85340 }
	}
	controlledprovinces = {
		766
	}
}
country = {
	tag = C768
	form_of_goverment = feudal
	capital = 768
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85350 }
	}
	controlledprovinces = {
		768
	}
}
country = {
	tag = MDAM
	form_of_goverment = feudal
	capital = 727
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85360 }
	}
	controlledprovinces = {
		727
	}
}
country = {
	tag = C709
	form_of_goverment = feudal
	capital = 709
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85370 }
	}
	controlledprovinces = {
		709
	}
}
country = {
	tag = C710
	form_of_goverment = feudal
	capital = 710
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85380 }
	}
	controlledprovinces = {
		710
	}
}
country = {
	tag = C728
	form_of_goverment = feudal
	capital = 728
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85390 }
	}
	controlledprovinces = {
		728
	}
}
country = {
	tag = C729
	form_of_goverment = feudal
	capital = 729
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85400 }
	}
	controlledprovinces = {
		729
	}
}
country = {
	tag = C730
	form_of_goverment = feudal
	capital = 730
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85410 }
	}
	controlledprovinces = {
		730
	}
}
country = {
	tag = C731
	form_of_goverment = feudal
	capital = 731
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85420 }
	}
	controlledprovinces = {
		731
	}
}
country = {
	tag = C732
	form_of_goverment = feudal
	capital = 732
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85430 }
	}
	controlledprovinces = {
		732
	}
}
country = {
	tag = MELA
	form_of_goverment = feudal
	capital = 787
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85440 }
	}
	controlledprovinces = {
		787
	}
}
country = {
	tag = C781
	form_of_goverment = feudal
	capital = 781
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85450 }
	}
	controlledprovinces = {
		781
	}
}
country = {
	tag = C782
	form_of_goverment = feudal
	capital = 782
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85460 }
	}
	controlledprovinces = {
		782
	}
}
country = {
	tag = C783
	form_of_goverment = feudal
	capital = 783
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85470 }
	}
	controlledprovinces = {
		783
	}
}
country = {
	tag = C784
	form_of_goverment = feudal
	capital = 784
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85480 }
	}
	controlledprovinces = {
		784
	}
}
country = {
	tag = C785
	form_of_goverment = feudal
	capital = 785
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 85490 }
	}
	controlledprovinces = {
		785
	}
}
country = {
	tag = WSAM
	form_of_goverment = feudal
	capital = 279
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 86000 }
	}
	controlledprovinces = {
		279
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = ESAM
	form_of_goverment = feudal
	capital = 386
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 86010 }
	}
	controlledprovinces = {
		386
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = KAJA
	form_of_goverment = feudal
	capital = 389
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 86030 }
	}
	controlledprovinces = {
		389
	}
	laws = {
		salic_gavelkind_law = yes
		traditional_custom_law = yes
		ecclesical_balance = yes
	}
}
country = {
	tag = GRAN
	form_of_goverment = feudal
	capital = 180
	ruler = {
		startdate = { year = 1337 month = january day = 1 }
		character = { type = 10 id = 87000 }
	}
	controlledprovinces = {
		180
		166
		167
		168
	}
	laws = {
		semisalic_consanguinity_law = yes
		royal_preorgatory_law = yes
		regal_supremacy = yes
	}
}