title = {
	tag = C001
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 52610 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C002
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 52600 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C003
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 64006 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C004
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 64007 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C005
	tier = county
	liege = ULST
	holder = { character = { type = 10 id = 54614 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C006
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50600 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C007
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 54160 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C008
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 54204 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C009
	tier = county
	liege = CONN
	holder = { character = { type = 10 id = 54150 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C010
	tier = county
	liege = MEAT
	holder = { character = { type = 10 id = 54100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C011
	tier = county
	liege = MEAT
	holder = { character = { type = 10 id = 54100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C012
	tier = county
	liege = MEAT
	holder = { character = { type = 10 id = 54122 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C013
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 54205 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C014
	tier = county
	liege = MEAT
	holder = { character = { type = 10 id = 54130 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C015
	tier = county
	liege = MEAT
	holder = { character = { type = 10 id = 54110 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C016
	tier = county
	liege = LEIN
	holder = { character = { type = 10 id = 54201 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C017
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54560 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C018
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 53400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C019
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C020
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C021
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54610 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C022
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54586 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C023
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54023 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C024
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54581 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C025
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54570 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C026
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54570 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C027
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C028
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C029
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54594 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C030
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54594 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C031
	tier = county
	liege = CORN
	holder = { character = { type = 10 id = 54501 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C032
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C033
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 87073 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C034
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 87074 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C035
	tier = county
	liege = WEIS
	holder = { character = { type = 10 id = 20019 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C036
	tier = county
	liege = ORKN
	holder = { character = { type = 10 id = 50820 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C037
	tier = county
	liege = ORKN
	holder = { character = { type = 10 id = 50820 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C038
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53002 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C039
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53003 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C040
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53004 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C041
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53005 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C042
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53006 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C043
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53007 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C044
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90031 } character = { type = 10 id = 53008 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C045
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53009 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C046
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53010 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C047
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C048
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C049
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53518 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C050
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53611 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C051
	tier = county
	liege = SCOT
	holder = { character = { type = 10 id = 53014 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C052
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54596 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C053
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54602 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C054
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 20021 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C055
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54602 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C056
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54596 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C057
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 55515 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C058
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54525 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C059
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C060
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 30002 } character = { type = 10 id = 20006 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C061
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54023 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C062
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54525 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C063
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54527 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C064
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 30001 } character = { type = 10 id = 20006 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C065
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54211 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C066
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54560 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C067
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54592 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C068
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54562 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C069
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C070
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C071
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C072
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C073
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54576 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C074
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55850 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C075
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55820 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C076
	tier = county
	liege = FLAN
	holder = { character = { type = 10 id = 55710 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C077
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 55910 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C078
	tier = county
	liege = FLAN
	holder = { character = { type = 10 id = 55710 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C079
	tier = county
	liege = HAIN
	holder = { character = { type = 10 id = 62742 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C080
	tier = county
	liege = HAIN
	holder = { character = { type = 10 id = 62742 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C081
	tier = county
	liege = HAIN
	holder = { character = { type = 10 id = 62742 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C082
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62006 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C083
	tier = county
	liege = FRIE
	holder = { character = { type = 10 id = 56550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C084
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62001 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C085
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62171 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C086
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62917 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C087
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62004 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C088
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62003 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C089
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62920 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C090
	tier = county
	liege = BRAB
	holder = { character = { type = 10 id = 62930 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C091
	tier = county
	liege = BRAB
	holder = { character = { type = 10 id = 62162 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C092
	tier = county
	liege = BRAB
	holder = { character = { type = 10 id = 87044 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C093
	tier = county
	liege = FLAN
	holder = { character = { type = 10 id = 55710 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C094
	tier = county
	liege = HAIN
	holder = { character = { type = 10 id = 62742 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C095
	tier = county
	liege = NORM
	holder = { character = { type = 10 id = 54980 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C096
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55850 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C097
	tier = county
	liege = NORM
	holder = { character = { type = 10 id = 55502 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C098
	tier = county
	liege = NORM
	holder = { character = { type = 10 id = 55502 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C099
	tier = county
	liege = NAVA
	holder = { character = { type = 10 id = 55810 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C100
	tier = county
	liege = NORM
	holder = { character = { type = 10 id = 55502 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C101
	tier = county
	liege = BRIT
	holder = { character = { type = 10 id = 55750 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C102
	tier = county
	liege = BRIT
	holder = { character = { type = 10 id = 55753 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C103
	tier = county
	liege = BRIT
	holder = { character = { type = 10 id = 55750 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C104
	tier = county
	liege = BRIT
	holder = { character = { type = 10 id = 55750 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C105
	tier = county
	liege = BRIT
	holder = { character = { type = 10 id = 55750 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C106
	tier = county
	liege = BRIT
	holder = { character = { type = 10 id = 55750 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C107
	tier = county
	liege = NORM
	holder = { character = { type = 10 id = 55502 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C108
	tier = county
	liege = NORM
	holder = { character = { type = 10 id = 55432 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C109
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55006 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C110
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55781 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C111
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55513 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C112
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C113
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C114
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C115
	tier = county
	liege = LUXE
	holder = { character = { type = 10 id = 62605 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C116
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62002 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C117
	tier = county
	liege = BRAB
	holder = { character = { type = 10 id = 87044 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C118
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 87032 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C119
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 87032 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C120
	tier = county
	liege = BERW
	holder = { character = { type = 10 id = 62823 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C121
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62362 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C122
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62380 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C123
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 87017 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C124
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62749 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C125
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62310 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C126
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62005 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C127
	tier = county
	liege = UPLO
	holder = { character = { type = 10 id = 62550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C128
	tier = county
	liege = UPLO
	holder = { character = { type = 10 id = 62550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C129
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55760 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C130
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C131
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C132
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55730 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C133
	tier = county
	liege = UPLO
	holder = { character = { type = 10 id = 62630 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C134
	tier = county
	liege = OSTE
	holder = { character = { type = 10 id = 62020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C135
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 55910 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C136
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 55910 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C137
	tier = county
	liege = FLAN
	holder = { character = { type = 10 id = 55710 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C138
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C139
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C140
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 55910 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C141
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90002 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C142
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55930 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90005 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C143
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90014 } character = { type = 10 id = 55500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C144
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 57570 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90003 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C145
	tier = county
	liege = BOUR
	holder = { character = { type = 10 id = 55650 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90009 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C146
	tier = county
	liege = BOUR
	holder = { character = { type = 10 id = 55650 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C147
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 55770 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90008 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C148
	tier = county
	liege = ENGL
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90028 } character = { type = 10 id = 55500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C149
	tier = county
	liege = BORD
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90011 } character = { type = 10 id = 55500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C150
	tier = county
	liege = BORD
	holder = { character = { type = 10 id = 55630 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90016 } character = { type = 10 id = 55500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C151
	tier = county
	liege = BORD
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90013 } character = { type = 10 id = 55500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C152
	tier = county
	liege = NAVA
	holder = { character = { type = 10 id = 55810 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C153
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57610 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C154
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57510 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C155
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57510 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C156
	tier = county
	liege = GALC
	holder = { character = { type = 10 id = 57670 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C157
	tier = county
	liege = GALC
	holder = { character = { type = 10 id = 58003 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C158
	tier = county
	liege = PORT
	holder = { character = { type = 10 id = 59500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C159
	tier = county
	liege = PORT
	holder = { character = { type = 10 id = 59500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C160
	tier = county
	liege = PORT
	holder = { character = { type = 10 id = 59500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C161
	tier = county
	liege = PORT
	holder = { character = { type = 10 id = 59001 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C162
	tier = county
	liege = PORT
	holder = { character = { type = 10 id = 57002 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C163
	tier = county
	liege = PORT
	holder = { character = { type = 10 id = 59002 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C164
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 58011 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C165
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 58011 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C166
	tier = county
	liege = GRAN
	holder = { character = { type = 10 id = 87000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C167
	tier = county
	liege = GRAN
	holder = { character = { type = 10 id = 87000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C168
	tier = county
	liege = GRAN
	holder = { character = { type = 10 id = 87000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C169
	tier = county
	liege = MURC
	holder = { character = { type = 10 id = 57630 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C170
	tier = county
	liege = ARAG
	holder = { character = { type = 10 id = 60540 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C171
	tier = county
	liege = ARAG
	holder = { character = { type = 10 id = 60500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C172
	tier = county
	liege = ARAG
	holder = { character = { type = 10 id = 60011 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C173
	tier = county
	liege = ARAG
	holder = { character = { type = 10 id = 60530 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C174
	tier = county
	liege = ARAG
	holder = { character = { type = 10 id = 60500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C175
	tier = county
	liege = ARAG
	holder = { character = { type = 10 id = 60500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C176
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 58005 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C177
	tier = county
	liege = U000
	holder = { character = { type = 10 id = 58004 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = U000
	tier = duchy
	liege = CAST
	holder = { character = { type = 10 id = 58004 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C178
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57015 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C179
	tier = county
	liege = MURC
	holder = { character = { type = 10 id = 57630 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C180
	tier = county
	liege = GRAN
	holder = { character = { type = 10 id = 87000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C181
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C182
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 58002 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C183
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 58021 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C184
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57012 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C185
	tier = county
	liege = PORT
	holder = { character = { type = 10 id = 57013 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C186
	tier = county
	liege = PORT
	holder = { character = { type = 10 id = 59004 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C187
	tier = county
	liege = PORT
	holder = { character = { type = 10 id = 59005 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C188
	tier = county
	liege = PORT
	holder = { character = { type = 10 id = 59006 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C189
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57590 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C190
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C191
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57600 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C192
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C193
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 58006 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C194
	tier = county
	liege = BADA
	holder = { character = { type = 10 id = 57020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C195
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57014 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C196
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57015 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C197
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C198
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C199
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57581 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C200
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 57500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C201
	tier = county
	liege = CAST
	holder = { character = { type = 10 id = 56510 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C202
	tier = county
	liege = ARAG
	holder = { character = { type = 10 id = 60500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C203
	tier = county
	liege = ARAG
	holder = { character = { type = 10 id = 60022 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C204
	tier = county
	liege = ARAG
	holder = { character = { type = 10 id = 60500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C205
	tier = county
	liege = ARAG
	holder = { character = { type = 10 id = 60580 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C206
	tier = county
	liege = ARAG
	holder = { character = { type = 10 id = 60520 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C207
	tier = county
	liege = ARAG
	holder = { character = { type = 10 id = 60570 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C208
	tier = county
	liege = TOUL
	holder = { character = { type = 10 id = 55552 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90019 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C209
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55640 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90006 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C210
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55540 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90007 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C211
	tier = county
	liege = BALE
	holder = { character = { type = 10 id = 60620 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C212
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55620 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C213
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90012 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C214
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90017 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C215
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90018 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C216
	tier = county
	liege = TOUL
	holder = { character = { type = 10 id = 55560 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90015 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C217
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55820 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C218
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90004 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C219
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C220
	tier = county
	liege = BALE
	holder = { character = { type = 10 id = 60620 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C221
	tier = county
	liege = NAPL
	holder = { character = { type = 10 id = 61700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C222
	tier = county
	liege = PAPA
	holder = { character = { type = 10 id = 78501 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C223
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55455 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C224
	tier = county
	liege = BOUR
	holder = { character = { type = 10 id = 55650 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C225
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 55910 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C226
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 55910 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C227
	tier = county
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C228
	tier = county
	liege = SAVO
	holder = { character = { type = 10 id = 62154 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C229
	tier = county
	liege = NAPL
	holder = { character = { type = 10 id = 61700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C230
	tier = county
	liege = GENO
	holder = { character = { type = 10 id = 63400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C231
	tier = county
	liege = SAVO
	holder = { character = { type = 10 id = 20301 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C232
	tier = county
	liege = NAPL
	holder = { character = { type = 10 id = 65520 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C233
	tier = county
	liege = GENO
	holder = { character = { type = 10 id = 63400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C234
	tier = county
	liege = MILA
	holder = { character = { type = 10 id = 63140 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C235
	tier = county
	liege = MILA
	holder = { character = { type = 10 id = 63140 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C236
	tier = county
	liege = SAVO
	holder = { character = { type = 10 id = 62690 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C237
	tier = county
	liege = SAVO
	holder = { character = { type = 10 id = 62154 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C238
	tier = county
	liege = SAVO
	holder = { character = { type = 10 id = 62140 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C239
	tier = county
	liege = SAVO
	holder = { character = { type = 10 id = 62154 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C240
	tier = county
	liege = BOUG
	holder = { character = { type = 10 id = 55910 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C241
	tier = county
	liege = SAVO
	holder = { character = { type = 10 id = 62092 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C242
	tier = county
	liege = OSTE
	holder = { character = { type = 10 id = 62050 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C244
	tier = county
	liege = SWIS
	holder = { character = { type = 10 id = 62085 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C245
	tier = county
	liege = SWIS
	holder = { character = { type = 10 id = 62085 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C246
	tier = county
	liege = MILA
	holder = { character = { type = 10 id = 63140 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C247
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 87015 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C248
	tier = county
	liege = OSTE
	holder = { character = { type = 10 id = 62050 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C249
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62350 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C250
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62324 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C251
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62337 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C252
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 87016 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C253
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62302 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C254
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C255
	tier = county
	liege = MEIS
	holder = { character = { type = 10 id = 62400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C256
	tier = county
	liege = BERW
	holder = { character = { type = 10 id = 62824 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C257
	tier = county
	liege = BERW
	holder = { character = { type = 10 id = 62808 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C258
	tier = county
	liege = BERW
	holder = { character = { type = 10 id = 62835 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C259
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 20251 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C260
	tier = county
	liege = MECK
	holder = { character = { type = 10 id = 51980 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C261
	tier = county
	liege = HOLS
	holder = { character = { type = 10 id = 51940 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C262
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 87019 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C263
	tier = county
	liege = HOLS
	holder = { character = { type = 10 id = 51970 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90020 } character = { type = 10 id = 51530 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C264
	tier = county
	liege = SVIG
	holder = { character = { type = 10 id = 51530 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C265
	tier = county
	liege = HOLS
	holder = { character = { type = 10 id = 51940 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90022 } character = { type = 10 id = 51500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C266
	tier = county
	liege = HOLS
	holder = { character = { type = 10 id = 51960 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90023 } character = { type = 10 id = 51500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C267
	tier = county
	liege = DENM
	holder = { character = { type = 10 id = 51500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C268
	tier = county
	liege = BERG
	holder = { character = { type = 10 id = 50780 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C269
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 50730 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C270
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 50740 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C271
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 50750 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C272
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C273
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 50670 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C274
	tier = county
	liege = BERG
	holder = { character = { type = 10 id = 50780 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C275
	tier = county
	liege = BERG
	holder = { character = { type = 10 id = 50790 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C276
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 50670 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C277
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 50810 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C278
	tier = county
	liege = BERG
	holder = { character = { type = 10 id = 50780 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C279
	tier = county
	liege = WSAM
	holder = { character = { type = 10 id = 86000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C280
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 87070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C281
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 87071 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C282
	tier = county
	liege = JAMT
	holder = { character = { type = 10 id = 50800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C283
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 87072 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C284
	tier = county
	liege = JAMT
	holder = { character = { type = 10 id = 50800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C285
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50720 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C286
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50710 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C287
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C288
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50680 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C289
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C290
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50710 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C291
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50710 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C292
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C293
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50650 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C294
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50690 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C295
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50640 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C296
	tier = county
	liege = NORW
	holder = { character = { type = 10 id = 50660 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C297
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50630 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C298
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50650 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C299
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50620 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C300
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50620 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C301
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C302
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 51800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C303
	tier = county
	liege = SWED
	holder = { character = { type = 10 id = 50500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C304
	tier = county
	liege = POMM
	holder = { character = { type = 10 id = 71653 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C305
	tier = county
	liege = SKAN
	holder = { character = { type = 10 id = 51600 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C306
	tier = county
	liege = MECK
	holder = { character = { type = 10 id = 51980 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C307
	tier = county
	liege = MECK
	holder = { character = { type = 10 id = 51990 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C308
	tier = county
	liege = POMM
	holder = { character = { type = 10 id = 51950 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C309
	tier = county
	liege = BRAN
	holder = { character = { type = 10 id = 62731 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C310
	tier = county
	liege = SAXO
	holder = { character = { type = 10 id = 62390 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C311
	tier = county
	liege = SAXO
	holder = { character = { type = 10 id = 62100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C312
	tier = county
	liege = MEIS
	holder = { character = { type = 10 id = 62400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C313
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 20239 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C314
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 87021 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C315
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62740 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C316
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62710 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C317
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 87014 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C318
	tier = county
	liege = VERO
	holder = { character = { type = 10 id = 12078 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C319
	tier = county
	liege = VERO
	holder = { character = { type = 10 id = 12078 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C320
	tier = county
	liege = MILA
	holder = { character = { type = 10 id = 63140 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C321
	tier = county
	liege = VERO
	holder = { character = { type = 10 id = 12078 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C322
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 63200 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C323
	tier = county
	liege = LANG
	holder = { character = { type = 10 id = 63450 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C324
	tier = county
	liege = GENO
	holder = { character = { type = 10 id = 63400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C325
	tier = county
	liege = BALE
	holder = { character = { type = 10 id = 60620 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C326
	tier = county
	liege = LANG
	holder = { character = { type = 10 id = 63450 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C327
	tier = county
	liege = TOSC
	holder = { character = { type = 10 id = 63320 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C328
	tier = county
	liege = TOSC
	holder = { character = { type = 10 id = 63320 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C329
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 63460 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C330
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 13017 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C331
	tier = county
	liege = LANG
	holder = { character = { type = 10 id = 63450 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C332
	tier = county
	liege = PAPA
	holder = { character = { type = 10 id = 13016 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C333
	tier = county
	liege = PAPA
	holder = { character = { type = 10 id = 78503 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C334
	tier = county
	liege = NAPL
	holder = { character = { type = 10 id = 61700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C335
	tier = county
	liege = NAPL
	holder = { character = { type = 10 id = 61700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C336
	tier = county
	liege = NAPL
	holder = { character = { type = 10 id = 61700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C337
	tier = county
	liege = NAPL
	holder = { character = { type = 10 id = 61700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C338
	tier = county
	liege = NAPL
	holder = { character = { type = 10 id = 61700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C339
	tier = county
	liege = TRAN
	holder = { character = { type = 10 id = 61500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C340
	tier = county
	liege = TRAN
	holder = { character = { type = 10 id = 61500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C341
	tier = county
	liege = TRAN
	holder = { character = { type = 10 id = 61500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C342
	tier = county
	liege = TRAN
	holder = { character = { type = 10 id = 61500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C343
	tier = county
	liege = TRAN
	holder = { character = { type = 10 id = 61500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C344
	tier = county
	liege = CALA
	holder = { character = { type = 10 id = 61718 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C345
	tier = county
	liege = CALA
	holder = { character = { type = 10 id = 61730 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C346
	tier = county
	liege = CALA
	holder = { character = { type = 10 id = 61718 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C347
	tier = county
	liege = NAPL
	holder = { character = { type = 10 id = 61700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C348
	tier = county
	liege = NAPL
	holder = { character = { type = 10 id = 61700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C349
	tier = county
	liege = NAPL
	holder = { character = { type = 10 id = 61700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C350
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 63470 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C351
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 63210 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C352
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 63300 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C353
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 63200 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C354
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 13024 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C355
	tier = county
	liege = VERO
	holder = { character = { type = 10 id = 12072 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C356
	tier = county
	liege = VENI
	holder = { character = { type = 10 id = 63600 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C357
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 13023 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C358
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 13022 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C359
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62710 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C360
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 62740 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C361
	tier = county
	liege = BAVA
	holder = { character = { type = 10 id = 62760 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C362
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 62610 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C363
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 62610 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C364
	tier = county
	liege = MEIS
	holder = { character = { type = 10 id = 62400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C365
	tier = county
	liege = BRAN
	holder = { character = { type = 10 id = 62731 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C366
	tier = county
	liege = POMM
	holder = { character = { type = 10 id = 71655 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C367
	tier = county
	liege = POMM
	holder = { character = { type = 10 id = 71655 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C368
	tier = county
	liege = TEUT
	holder = { character = { type = 10 id = 74020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C369
	tier = county
	liege = TEUT
	holder = { character = { type = 10 id = 74000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C370
	tier = county
	liege = TEUT
	holder = { character = { type = 10 id = 74000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C371
	tier = county
	liege = TEUT
	holder = { character = { type = 10 id = 74040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C372
	tier = county
	liege = TEUT
	holder = { character = { type = 10 id = 74000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C373
	tier = county
	liege = TEUT
	holder = { character = { type = 10 id = 74090 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C374
	tier = county
	liege = SAMO
	holder = { character = { type = 10 id = 73508 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C375
	tier = county
	liege = U001
	holder = { character = { type = 10 id = 74070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C376
	tier = county
	liege = U001
	holder = { character = { type = 10 id = 74080 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C377
	tier = county
	liege = U001
	holder = { character = { type = 10 id = 74090 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = U001
	tier = duchy
	liege = TEUT
	holder = { character = { type = 10 id = 74090 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C378
	tier = county
	liege = ESTH
	holder = { character = { type = 10 id = 51523 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C379
	tier = county
	liege = U001
	holder = { character = { type = 10 id = 74100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C380
	tier = county
	liege = ESTH
	holder = { character = { type = 10 id = 51523 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C381
	tier = county
	liege = FINL
	holder = { character = { type = 10 id = 50840 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C382
	tier = county
	liege = FINL
	holder = { character = { type = 10 id = 50760 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C383
	tier = county
	liege = FINL
	holder = { character = { type = 10 id = 50840 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C384
	tier = county
	liege = FINL
	holder = { character = { type = 10 id = 50760 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C385
	tier = county
	liege = FINL
	holder = { character = { type = 10 id = 50760 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C386
	tier = county
	liege = ESAM
	holder = { character = { type = 10 id = 86010 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C387
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72301 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C388
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 73504 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C389
	tier = county
	liege = KAJA
	holder = { character = { type = 10 id = 86030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C390
	tier = county
	liege = FINL
	holder = { character = { type = 10 id = 50610 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C391
	tier = county
	liege = FINL
	holder = { character = { type = 10 id = 50610 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C392
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 73504 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C393
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72305 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C394
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72306 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C395
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72307 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C396
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72308 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C397
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72309 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C398
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72310 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C399
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72311 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C400
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72319 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C401
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72320 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C402
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72318 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C403
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72312 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C404
	tier = county
	liege = BELO
	holder = { character = { type = 10 id = 72000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C405
	tier = county
	liege = BELO
	holder = { character = { type = 10 id = 72001 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C406
	tier = county
	liege = BELO
	holder = { character = { type = 10 id = 72002 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C407
	tier = county
	liege = YARO
	holder = { character = { type = 10 id = 72003 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C408
	tier = county
	liege = BELO
	holder = { character = { type = 10 id = 72820 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C409
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72313 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C410
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72300 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C411
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 73504 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C412
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72315 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C413
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72868 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C414
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72316 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C415
	tier = county
	liege = NOVG
	holder = { character = { type = 10 id = 72317 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C416
	tier = county
	liege = POLO
	holder = { character = { type = 10 id = 72350 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C417
	tier = county
	liege = LITH
	holder = { character = { type = 10 id = 73506 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C418
	tier = county
	liege = LITH
	holder = { character = { type = 10 id = 73506 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C419
	tier = county
	liege = POLO
	holder = { character = { type = 10 id = 72350 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C420
	tier = county
	liege = LITH
	holder = { character = { type = 10 id = 73500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C421
	tier = county
	liege = SAMO
	holder = { character = { type = 10 id = 73508 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C422
	tier = county
	liege = SAMO
	holder = { character = { type = 10 id = 73508 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C423
	tier = county
	liege = LITH
	holder = { character = { type = 10 id = 73500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C424
	tier = county
	liege = LITH
	holder = { character = { type = 10 id = 73500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C425
	tier = county
	liege = SAMO
	holder = { character = { type = 10 id = 73508 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C426
	tier = county
	liege = SAMO
	holder = { character = { type = 10 id = 73508 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C427
	tier = county
	liege = TEUT
	holder = { character = { type = 10 id = 74130 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C428
	tier = county
	liege = POLA
	holder = { character = { type = 10 id = 71535 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C429
	tier = county
	liege = POLA
	holder = { character = { type = 10 id = 71500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C430
	tier = county
	liege = BRAN
	holder = { character = { type = 10 id = 62731 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C431
	tier = county
	liege = POLA
	holder = { character = { type = 10 id = 71500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C432
	tier = county
	liege = POLA
	holder = { character = { type = 10 id = 71500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C433
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 71720 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C434
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 71700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C435
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 71730 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C436
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 62610 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C437
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 62610 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C438
	tier = county
	liege = MORA
	holder = { character = { type = 10 id = 62614 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C439
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 62610 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C440
	tier = county
	liege = MORA
	holder = { character = { type = 10 id = 62614 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C441
	tier = county
	liege = MORA
	holder = { character = { type = 10 id = 62614 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C442
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 70160 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C443
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 69500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C444
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 70133 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C445
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 69500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C446
	tier = county
	liege = OSTE
	holder = { character = { type = 10 id = 62020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C447
	tier = county
	liege = BAVA
	holder = { character = { type = 10 id = 62760 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C448
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 87010 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C449
	tier = county
	liege = OSTE
	holder = { character = { type = 10 id = 62020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C450
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 70101 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C451
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 69500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C452
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 69500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C453
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 69500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C454
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 70122 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C455
	tier = county
	liege = OSTE
	holder = { character = { type = 10 id = 62020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C456
	tier = county
	liege = OSTE
	holder = { character = { type = 10 id = 62020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C457
	tier = county
	liege = OSTE
	holder = { character = { type = 10 id = 62020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C458
	tier = county
	liege = VENI
	holder = { character = { type = 10 id = 63600 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C459
	tier = county
	liege = DCRO
	holder = { character = { type = 10 id = 70021 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C460
	tier = county
	liege = SLAV
	holder = { character = { type = 10 id = 70111 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C461
	tier = county
	liege = SLAV
	holder = { character = { type = 10 id = 70030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C462
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 70112 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C463
	tier = county
	liege = NOSE
	holder = { character = { type = 10 id = 68805 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C464
	tier = county
	liege = DCRO
	holder = { character = { type = 10 id = 70000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C465
	tier = county
	liege = VENI
	holder = { character = { type = 10 id = 63600 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C466
	tier = county
	liege = NOSE
	holder = { character = { type = 10 id = 68850 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C467
	tier = county
	liege = VENI
	holder = { character = { type = 10 id = 63600 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C468
	tier = county
	liege = SERB
	holder = { character = { type = 10 id = 68500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C469
	tier = county
	liege = SERB
	holder = { character = { type = 10 id = 68500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C470
	tier = county
	liege = SERB
	holder = { character = { type = 10 id = 67502 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90027 } character = { type = 10 id = 61723 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C471
	tier = county
	liege = SERB
	holder = { character = { type = 10 id = 68550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C472
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 65517 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90024 } character = { type = 10 id = 68500 } date = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90025 } character = { type = 10 id = 65500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C473
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 65517 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90026 } character = { type = 10 id = 65500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C474
	tier = county
	liege = CALA
	holder = { character = { type = 10 id = 61718 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C475
	tier = county
	liege = HELL
	holder = { character = { type = 10 id = 61510 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90033 } character = { type = 10 id = 61730 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C476
	tier = county
	liege = CALA
	holder = { character = { type = 10 id = 65400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C477
	tier = county
	liege = VENI
	holder = { character = { type = 10 id = 63120 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C478
	tier = county
	liege = ACHA
	holder = { character = { type = 10 id = 65550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C479
	tier = county
	liege = KRET
	holder = { character = { type = 10 id = 63130 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C480
	tier = county
	liege = KRET
	holder = { character = { type = 10 id = 63130 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C481
	tier = county
	liege = CALA
	holder = { character = { type = 10 id = 65400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C482
	tier = county
	liege = HELL
	holder = { character = { type = 10 id = 61510 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90032 } character = { type = 10 id = 61730 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C483
	tier = county
	liege = HOSP
	holder = { character = { type = 10 id = 78502 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C484
	tier = county
	liege = AEGE
	holder = { character = { type = 10 id = 61570 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C485
	tier = county
	liege = AEGE
	holder = { character = { type = 10 id = 61570 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C486
	tier = county
	liege = GENO
	holder = { character = { type = 10 id = 63400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C487
	tier = county
	liege = BYZA
	holder = { character = { type = 10 id = 65210 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C488
	tier = county
	liege = BYZA
	holder = { character = { type = 10 id = 65201 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C489
	tier = county
	liege = BYZA
	holder = { character = { type = 10 id = 65200 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C490
	tier = county
	liege = THES
	holder = { character = { type = 10 id = 65530 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C491
	tier = county
	liege = THES
	holder = { character = { type = 10 id = 65530 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C492
	tier = county
	liege = SERB
	holder = { character = { type = 10 id = 68500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C493
	tier = county
	liege = THES
	holder = { character = { type = 10 id = 65530 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C494
	tier = county
	liege = THES
	holder = { character = { type = 10 id = 65530 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C495
	tier = county
	liege = THES
	holder = { character = { type = 10 id = 65530 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C496
	tier = county
	liege = BYZA
	holder = { character = { type = 10 id = 65500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C497
	tier = county
	liege = BYZA
	holder = { character = { type = 10 id = 65500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C498
	tier = county
	liege = BULG
	holder = { character = { type = 10 id = 67503 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C499
	tier = county
	liege = BULG
	holder = { character = { type = 10 id = 67500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C500
	tier = county
	liege = BULG
	holder = { character = { type = 10 id = 67505 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C501
	tier = county
	liege = SERB
	holder = { character = { type = 10 id = 67523 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C502
	tier = county
	liege = SERB
	holder = { character = { type = 10 id = 68500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C503
	tier = county
	liege = SERB
	holder = { character = { type = 10 id = 68500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C504
	tier = county
	liege = NOSE
	holder = { character = { type = 10 id = 68800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C505
	tier = county
	liege = SERB
	holder = { character = { type = 10 id = 68500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C506
	tier = county
	liege = BULG
	holder = { character = { type = 10 id = 67500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C507
	tier = county
	liege = BULG
	holder = { character = { type = 10 id = 67500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C508
	tier = county
	liege = BULG
	holder = { character = { type = 10 id = 67500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C509
	tier = county
	liege = VARN
	holder = { character = { type = 10 id = 67550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C510
	tier = county
	liege = VARN
	holder = { character = { type = 10 id = 67550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C511
	tier = county
	liege = VARN
	holder = { character = { type = 10 id = 67550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C512
	tier = county
	liege = MOLD
	holder = { character = { type = 10 id = 75400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C513
	tier = county
	liege = WALL
	holder = { character = { type = 10 id = 75100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C514
	tier = county
	liege = WALL
	holder = { character = { type = 10 id = 75550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C515
	tier = county
	liege = WALL
	holder = { character = { type = 10 id = 75200 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C516
	tier = county
	liege = WALL
	holder = { character = { type = 10 id = 75300 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C517
	tier = county
	liege = SZEK
	holder = { character = { type = 10 id = 70040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C518
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 70151 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C519
	tier = county
	liege = SZEK
	holder = { character = { type = 10 id = 70040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C520
	tier = county
	liege = SZEK
	holder = { character = { type = 10 id = 70062 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C521
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 70135 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C522
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 69500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C523
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 70212 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C524
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 70181 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C525
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 69500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C526
	tier = county
	liege = DBOH
	holder = { character = { type = 10 id = 71740 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C527
	tier = county
	liege = POLA
	holder = { character = { type = 10 id = 71500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C528
	tier = county
	liege = POLA
	holder = { character = { type = 10 id = 71500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C529
	tier = county
	liege = MAZO
	holder = { character = { type = 10 id = 71515 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C530
	tier = county
	liege = MAZO
	holder = { character = { type = 10 id = 71518 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C531
	tier = county
	liege = POLA
	holder = { character = { type = 10 id = 71500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C532
	tier = county
	liege = POLA
	holder = { character = { type = 10 id = 71500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C533
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 70186 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C534
	tier = county
	liege = GALI
	holder = { character = { type = 10 id = 72900 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C535
	tier = county
	liege = LITH
	holder = { character = { type = 10 id = 73510 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C536
	tier = county
	liege = GALI
	holder = { character = { type = 10 id = 72900 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C537
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 70191 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C538
	tier = county
	liege = HUNG
	holder = { character = { type = 10 id = 70202 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C539
	tier = county
	liege = SZEK
	holder = { character = { type = 10 id = 70070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C540
	tier = county
	liege = SZEK
	holder = { character = { type = 10 id = 70040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C541
	tier = county
	liege = MOLD
	holder = { character = { type = 10 id = 75410 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C542
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 75420 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C543
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 79050 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C544
	tier = county
	liege = KIEV
	holder = { character = { type = 10 id = 72101 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C545
	tier = county
	liege = MOLD
	holder = { character = { type = 10 id = 75430 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C546
	tier = county
	liege = KIEV
	holder = { character = { type = 10 id = 72102 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C547
	tier = county
	liege = KIEV
	holder = { character = { type = 10 id = 72100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C548
	tier = county
	liege = LITH
	holder = { character = { type = 10 id = 73500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C549
	tier = county
	liege = LITH
	holder = { character = { type = 10 id = 73500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C550
	tier = county
	liege = LITH
	holder = { character = { type = 10 id = 73500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C551
	tier = county
	liege = SUZD
	holder = { character = { type = 10 id = 72250 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C552
	tier = county
	liege = LITH
	holder = { character = { type = 10 id = 73500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C553
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 72780 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C554
	tier = county
	liege = SUZD
	holder = { character = { type = 10 id = 72250 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C555
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 72450 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C556
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 79060 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C557
	tier = county
	liege = KHAZ
	holder = { character = { type = 10 id = 79200 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C558
	tier = county
	liege = KHAZ
	holder = { character = { type = 10 id = 79210 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C559
	tier = county
	liege = KHAZ
	holder = { character = { type = 10 id = 79220 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C560
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79220 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C561
	tier = county
	liege = GENO
	holder = { character = { type = 10 id = 63400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C562
	tier = county
	liege = TREB
	holder = { character = { type = 10 id = 65800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C563
	tier = county
	liege = KHAZ
	holder = { character = { type = 10 id = 79230 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C564
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 79070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C565
	tier = county
	liege = PERE
	holder = { character = { type = 10 id = 72450 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C566
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 79080 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C567
	tier = county
	liege = PRON
	holder = { character = { type = 10 id = 72400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C568
	tier = county
	liege = SMOL
	holder = { character = { type = 10 id = 72500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C569
	tier = county
	liege = SMOL
	holder = { character = { type = 10 id = 72500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C570
	tier = county
	liege = TVER
	holder = { character = { type = 10 id = 72860 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C571
	tier = county
	liege = YARO
	holder = { character = { type = 10 id = 72790 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C572
	tier = county
	liege = YARO
	holder = { character = { type = 10 id = 72790 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C573
	tier = county
	liege = MOSK
	holder = { character = { type = 10 id = 72640 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C574
	tier = county
	liege = ROST
	holder = { character = { type = 10 id = 72800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C575
	tier = county
	liege = MOSK
	holder = { character = { type = 10 id = 72840 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C576
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 72510 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C577
	tier = county
	liege = RYAZ
	holder = { character = { type = 10 id = 72630 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C578
	tier = county
	liege = MOSK
	holder = { character = { type = 10 id = 72840 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C579
	tier = county
	liege = MORD
	holder = { character = { type = 10 id = 28070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C580
	tier = county
	liege = RYAZ
	holder = { character = { type = 10 id = 72520 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C581
	tier = county
	liege = RYAZ
	holder = { character = { type = 10 id = 72520 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C582
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 72847 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C583
	tier = county
	liege = VLAD
	holder = { character = { type = 10 id = 72910 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C584
	tier = county
	liege = VLAD
	holder = { character = { type = 10 id = 72910 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C585
	tier = county
	liege = VLAD
	holder = { character = { type = 10 id = 72910 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C586
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 72830 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C587
	tier = county
	liege = VOLG
	holder = { character = { type = 10 id = 80260 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C588
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80080 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C589
	tier = county
	liege = VOLG
	holder = { character = { type = 10 id = 80270 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C590
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80090 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C591
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C592
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80110 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C593
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80120 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C594
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79090 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C595
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C596
	tier = county
	liege = KHAZ
	holder = { character = { type = 10 id = 79240 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C597
	tier = county
	liege = ALAN
	holder = { character = { type = 10 id = 80140 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C598
	tier = county
	liege = TREB
	holder = { character = { type = 10 id = 65800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C599
	tier = county
	liege = ALAN
	holder = { character = { type = 10 id = 80150 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C600
	tier = county
	liege = IMER
	holder = { character = { type = 10 id = 66520 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C601
	tier = county
	liege = IMER
	holder = { character = { type = 10 id = 66520 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C602
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80200 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C603
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80210 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C604
	tier = county
	liege = ALAN
	holder = { character = { type = 10 id = 80160 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C605
	tier = county
	liege = ALAN
	holder = { character = { type = 10 id = 80170 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C606
	tier = county
	liege = ALAN
	holder = { character = { type = 10 id = 80180 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C607
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 79040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C608
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C609
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80010 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C610
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80130 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C611
	tier = county
	liege = VOLG
	holder = { character = { type = 10 id = 80250 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C612
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C613
	tier = county
	liege = VOLG
	holder = { character = { type = 10 id = 80280 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C614
	tier = county
	liege = CUMA
	holder = { character = { type = 10 id = 79000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C615
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79010 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C616
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C617
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C618
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79110 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C619
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79120 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C620
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79130 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C621
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79140 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C622
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79150 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C623
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79160 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C624
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79170 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C625
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79180 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C626
	tier = county
	liege = KARA
	holder = { character = { type = 10 id = 78050 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C627
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 79190 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C628
	tier = county
	liege = KARA
	holder = { character = { type = 10 id = 78050 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C629
	tier = county
	liege = KARA
	holder = { character = { type = 10 id = 78050 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C630
	tier = county
	liege = KARA
	holder = { character = { type = 10 id = 78050 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C631
	tier = county
	liege = KARA
	holder = { character = { type = 10 id = 78050 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C632
	tier = county
	liege = LUTA
	holder = { character = { type = 10 id = 78027 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C633
	tier = county
	liege = MAZA
	holder = { character = { type = 10 id = 78080 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C634
	tier = county
	liege = LUTA
	holder = { character = { type = 10 id = 78026 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C635
	tier = county
	liege = LUTA
	holder = { character = { type = 10 id = 78028 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C636
	tier = county
	liege = LUTA
	holder = { character = { type = 10 id = 78026 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C637
	tier = county
	liege = MSIS
	holder = { character = { type = 10 id = 78025 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C638
	tier = county
	liege = HORM
	holder = { character = { type = 10 id = 78024 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C639
	tier = county
	liege = HORM
	holder = { character = { type = 10 id = 78022 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C640
	tier = county
	liege = SHIR
	holder = { character = { type = 10 id = 78015 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C641
	tier = county
	liege = HORM
	holder = { character = { type = 10 id = 78022 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C642
	tier = county
	liege = SHIR
	holder = { character = { type = 10 id = 78015 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C643
	tier = county
	liege = SHIR
	holder = { character = { type = 10 id = 78015 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C644
	tier = county
	liege = SHIR
	holder = { character = { type = 10 id = 78015 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90110 } character = { type = 10 id = 78013 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C645
	tier = county
	liege = SHIR
	holder = { character = { type = 10 id = 78015 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C646
	tier = county
	liege = ILKH
	holder = { character = { type = 10 id = 78030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C647
	tier = county
	liege = ILKH
	holder = { character = { type = 10 id = 78021 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C648
	tier = county
	liege = ILKH
	holder = { character = { type = 10 id = 78021 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C649
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C650
	tier = county
	liege = ILKH
	holder = { character = { type = 10 id = 27101 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C651
	tier = county
	liege = ILKH
	holder = { character = { type = 10 id = 27102 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C652
	tier = county
	liege = ILKH
	holder = { character = { type = 10 id = 27103 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C653
	tier = county
	liege = ILKH
	holder = { character = { type = 10 id = 27104 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C654
	tier = county
	liege = ILKH
	holder = { character = { type = 10 id = 27105 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C655
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C656
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C657
	tier = county
	liege = ILKH
	holder = { character = { type = 10 id = 78020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C658
	tier = county
	liege = ILKH
	holder = { character = { type = 10 id = 78030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C659
	tier = county
	liege = ILKH
	holder = { character = { type = 10 id = 78030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C660
	tier = county
	liege = QOMA
	holder = { character = { type = 10 id = 78033 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C661
	tier = county
	liege = MAZA
	holder = { character = { type = 10 id = 78080 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C662
	tier = county
	liege = GILA
	holder = { character = { type = 10 id = 78100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C663
	tier = county
	liege = QOMA
	holder = { character = { type = 10 id = 78033 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C664
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C665
	tier = county
	liege = QOMA
	holder = { character = { type = 10 id = 78033 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C666
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C667
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C668
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78090 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C669
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78090 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C670
	tier = county
	liege = AZER
	holder = { character = { type = 10 id = 78031 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C671
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90111 } character = { type = 10 id = 66759 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C672
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C673
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80220 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C674
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80230 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C675
	tier = county
	liege = GOLD
	holder = { character = { type = 10 id = 80240 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C676
	tier = county
	liege = GEOR
	holder = { character = { type = 10 id = 66500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C677
	tier = county
	liege = DGEO
	holder = { character = { type = 10 id = 66753 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C678
	tier = county
	liege = TREB
	holder = { character = { type = 10 id = 65800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C679
	tier = county
	liege = GEOR
	holder = { character = { type = 10 id = 66500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C680
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C681
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C682
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C683
	tier = county
	liege = MEDE
	holder = { character = { type = 10 id = 78070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C684
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C685
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C686
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C687
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C688
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C689
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C690
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C691
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C692
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C693
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C694
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C695
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C696
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C697
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C698
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C699
	tier = county
	liege = MEDE
	holder = { character = { type = 10 id = 78070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C700
	tier = county
	liege = MEDE
	holder = { character = { type = 10 id = 78070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C701
	tier = county
	liege = MEDE
	holder = { character = { type = 10 id = 78070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C702
	tier = county
	liege = DMES
	holder = { character = { type = 10 id = 76460 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C703
	tier = county
	liege = DMES
	holder = { character = { type = 10 id = 76460 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C704
	tier = county
	liege = CAND
	holder = { character = { type = 10 id = 76350 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C705
	tier = county
	liege = DMES
	holder = { character = { type = 10 id = 76460 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C706
	tier = county
	liege = MEDE
	holder = { character = { type = 10 id = 78070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C707
	tier = county
	liege = MEDE
	holder = { character = { type = 10 id = 78070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C708
	tier = county
	liege = MEDE
	holder = { character = { type = 10 id = 78070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C709
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 85370 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C710
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 85380 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C711
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C712
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C713
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 85110 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C714
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 85120 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C715
	tier = county
	liege = MBAG
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C716
	tier = county
	liege = MMED
	holder = { character = { type = 10 id = 85040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C717
	tier = county
	liege = MMED
	holder = { character = { type = 10 id = 85050 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C718
	tier = county
	liege = MMED
	holder = { character = { type = 10 id = 85060 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C719
	tier = county
	liege = MMED
	holder = { character = { type = 10 id = 85030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C720
	tier = county
	liege = MMED
	holder = { character = { type = 10 id = 85080 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C721
	tier = county
	liege = MMED
	holder = { character = { type = 10 id = 85090 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C722
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 85130 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C723
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 85140 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C724
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 85100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C725
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 85150 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C726
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 85160 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C727
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 85360 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C728
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 85390 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C729
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 85400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C730
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 85410 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C731
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 85420 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C732
	tier = county
	liege = MDAM
	holder = { character = { type = 10 id = 85430 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C733
	tier = county
	liege = MTRI
	holder = { character = { type = 10 id = 85300 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C734
	tier = county
	liege = MEDE
	holder = { character = { type = 10 id = 78070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C735
	tier = county
	liege = CILI
	holder = { character = { type = 10 id = 61800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C736
	tier = county
	liege = ERET
	holder = { character = { type = 10 id = 76470 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C737
	tier = county
	liege = ERET
	holder = { character = { type = 10 id = 76470 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C738
	tier = county
	liege = CAND
	holder = { character = { type = 10 id = 76350 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C739
	tier = county
	liege = SINO
	holder = { character = { type = 10 id = 76480 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C740
	tier = county
	liege = OTTO
	holder = { character = { type = 10 id = 76500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C741
	tier = county
	liege = OTTO
	holder = { character = { type = 10 id = 76500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C742
	tier = county
	liege = OTTO
	holder = { character = { type = 10 id = 76500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C743
	tier = county
	liege = OTTO
	holder = { character = { type = 10 id = 76500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C744
	tier = county
	liege = ----
	holder = { character = { type = 10 id = 76510 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C745
	tier = county
	liege = SARU
	holder = { character = { type = 10 id = 76150 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C746
	tier = county
	liege = AYDI
	holder = { character = { type = 10 id = 76200 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C747
	tier = county
	liege = MENT
	holder = { character = { type = 10 id = 76100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C748
	tier = county
	liege = GERI
	holder = { character = { type = 10 id = 76250 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C749
	tier = county
	liege = GERI
	holder = { character = { type = 10 id = 76250 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C750
	tier = county
	liege = OTTO
	holder = { character = { type = 10 id = 76500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C751
	tier = county
	liege = SINO
	holder = { character = { type = 10 id = 76480 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C752
	tier = county
	liege = ERET
	holder = { character = { type = 10 id = 76450 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C753
	tier = county
	liege = ERET
	holder = { character = { type = 10 id = 76450 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C754
	tier = county
	liege = GERI
	holder = { character = { type = 10 id = 76250 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C755
	tier = county
	liege = TEKK
	holder = { character = { type = 10 id = 76400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C756
	tier = county
	liege = BASR
	holder = { character = { type = 10 id = 61900 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C757
	tier = county
	liege = BASR
	holder = { character = { type = 10 id = 61900 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C758
	tier = county
	liege = KARM
	holder = { character = { type = 10 id = 76300 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C759
	tier = county
	liege = KARM
	holder = { character = { type = 10 id = 76300 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C760
	tier = county
	liege = ERET
	holder = { character = { type = 10 id = 76450 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C761
	tier = county
	liege = CILI
	holder = { character = { type = 10 id = 61923 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C762
	tier = county
	liege = CILI
	holder = { character = { type = 10 id = 61800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C763
	tier = county
	liege = CILI
	holder = { character = { type = 10 id = 61800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C764
	tier = county
	liege = MTRI
	holder = { character = { type = 10 id = 85320 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C765
	tier = county
	liege = MTRI
	holder = { character = { type = 10 id = 85330 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C766
	tier = county
	liege = MTRI
	holder = { character = { type = 10 id = 85340 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C767
	tier = county
	liege = MTRI
	holder = { character = { type = 10 id = 85290 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C768
	tier = county
	liege = MTRI
	holder = { character = { type = 10 id = 85350 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C769
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 85190 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C770
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 85200 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C771
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 85210 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C772
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 85180 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C773
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 85220 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C774
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 85230 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C775
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 85240 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C776
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 85250 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C777
	tier = county
	liege = MAMM
	holder = { character = { type = 10 id = 85170 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C778
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 85260 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C779
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 85270 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C780
	tier = county
	liege = MJER
	holder = { character = { type = 10 id = 85280 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C781
	tier = county
	liege = MELA
	holder = { character = { type = 10 id = 85450 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C782
	tier = county
	liege = MELA
	holder = { character = { type = 10 id = 85460 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C783
	tier = county
	liege = MELA
	holder = { character = { type = 10 id = 85470 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C784
	tier = county
	liege = MELA
	holder = { character = { type = 10 id = 85480 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C785
	tier = county
	liege = MELA
	holder = { character = { type = 10 id = 85490 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C786
	tier = county
	liege = MELA
	holder = { character = { type = 10 id = 85010 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C787
	tier = county
	liege = MELA
	holder = { character = { type = 10 id = 85440 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C788
	tier = county
	liege = MELA
	holder = { character = { type = 10 id = 85020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C789
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C790
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C791
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C792
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C793
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C794
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C795
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C796
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C797
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C798
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C799
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C800
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C801
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C802
	tier = county
	liege = FATI
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C803
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 85110 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C804
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 85120 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C805
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 85130 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C806
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 85140 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C807
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 85150 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C808
	tier = county
	liege = CYRE
	holder = { character = { type = 10 id = 85100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C809
	tier = county
	liege = KAFS
	holder = { character = { type = 10 id = 83010 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C810
	tier = county
	liege = KAFS
	holder = { character = { type = 10 id = 83020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C811
	tier = county
	liege = KAFS
	holder = { character = { type = 10 id = 83030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C812
	tier = county
	liege = TRAN
	holder = { character = { type = 10 id = 61550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C813
	tier = county
	liege = KAFS
	holder = { character = { type = 10 id = 83040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C814
	tier = county
	liege = KAFS
	holder = { character = { type = 10 id = 83050 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C815
	tier = county
	liege = KAFS
	holder = { character = { type = 10 id = 83060 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C816
	tier = county
	liege = KAFS
	holder = { character = { type = 10 id = 83070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C817
	tier = county
	liege = KAFS
	holder = { character = { type = 10 id = 83000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C818
	tier = county
	liege = KAFS
	holder = { character = { type = 10 id = 83080 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C819
	tier = county
	liege = KAFS
	holder = { character = { type = 10 id = 83090 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C820
	tier = county
	liege = KAFS
	holder = { character = { type = 10 id = 83100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C821
	tier = county
	liege = KAFS
	holder = { character = { type = 10 id = 83110 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C822
	tier = county
	liege = KAFS
	holder = { character = { type = 10 id = 83120 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C823
	tier = county
	liege = ZIYA
	holder = { character = { type = 10 id = 84020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C824
	tier = county
	liege = ZIYA
	holder = { character = { type = 10 id = 84040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C825
	tier = county
	liege = ZIYA
	holder = { character = { type = 10 id = 84030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C826
	tier = county
	liege = BALE
	holder = { character = { type = 10 id = 60620 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C827
	tier = county
	liege = BALE
	holder = { character = { type = 10 id = 60620 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C828
	tier = county
	liege = ZIYA
	holder = { character = { type = 10 id = 84050 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C829
	tier = county
	liege = ZIYA
	holder = { character = { type = 10 id = 84060 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C830
	tier = county
	liege = ZIYA
	holder = { character = { type = 10 id = 84070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C831
	tier = county
	liege = ZIYA
	holder = { character = { type = 10 id = 84080 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C832
	tier = county
	liege = ZIYA
	holder = { character = { type = 10 id = 84090 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C833
	tier = county
	liege = ZIYA
	holder = { character = { type = 10 id = 84100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C834
	tier = county
	liege = ZIYA
	holder = { character = { type = 10 id = 84000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C835
	tier = county
	liege = ZIYA
	holder = { character = { type = 10 id = 84010 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C836
	tier = county
	liege = MARI
	holder = { character = { type = 10 id = 82010 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C837
	tier = county
	liege = MARI
	holder = { character = { type = 10 id = 82020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C838
	tier = county
	liege = MARI
	holder = { character = { type = 10 id = 82030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C839
	tier = county
	liege = MARI
	holder = { character = { type = 10 id = 82040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C840
	tier = county
	liege = MARI
	holder = { character = { type = 10 id = 82000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C841
	tier = county
	liege = MARI
	holder = { character = { type = 10 id = 82050 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C842
	tier = county
	liege = MARI
	holder = { character = { type = 10 id = 82000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C843
	tier = county
	liege = MARI
	holder = { character = { type = 10 id = 82000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C844
	tier = county
	liege = MARI
	holder = { character = { type = 10 id = 82000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C845
	tier = county
	liege = MARI
	holder = { character = { type = 10 id = 82000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C846
	tier = county
	liege = MARI
	holder = { character = { type = 10 id = 82000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C847
	tier = county
	liege = MARI
	holder = { character = { type = 10 id = 82000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C848
	tier = county
	liege = MARI
	holder = { character = { type = 10 id = 20842 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C898
	tier = county
	liege = BENE
	holder = { character = { type = 10 id = 20332 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C995
	tier = county
	liege = GERM
	holder = { character = { type = 10 id = 20251 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = C997
	tier = county
	liege = BENE
	holder = { character = { type = 10 id = 20331 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = AEGE
	tier = duchy
	liege = VENI
	holder = { character = { type = 10 id = 61570 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ALAN
	tier = duchy
	liege = GOLD
	holder = { character = { type = 10 id = 80140 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = GRAN
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 87000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ANJO
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ARMA
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ASTU
	tier = duchy
	liege = CAST
	holder = { character = { type = 10 id = 57510 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = AUVE
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = AZER
	tier = duchy
	liege = ILKH
	holder = { character = { type = 10 id = 78031 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BADA
	tier = duchy
	liege = CAST
	holder = { character = { type = 10 id = 57012 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BAVA
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62760 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BELO
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 72820 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BENE
	tier = duchy
	liege = PAPA
	holder = { character = { type = 10 id = 20331 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BERG
	tier = duchy
	liege = NORW
	holder = { character = { type = 10 id = 50780 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BERW
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62823 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = DBOH
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62610 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BORD
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90010 } character = { type = 10 id = 55500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BOUG
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 55910 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BOUR
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 55650 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BRAB
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 87044 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BRAN
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62731 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BRIT
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 55750 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ELRI
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 55750 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = CALA
	tier = duchy
	liege = NAPL
	holder = { character = { type = 10 id = 61718 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = CATA
	tier = duchy
	liege = ARAG
	holder = { character = { type = 10 id = 60500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = CHAM
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = CONN
	tier = duchy
	liege = ENGL
	holder = { character = { type = 10 id = 54150 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = CORD
	tier = duchy
	liege = CAST
	holder = { character = { type = 10 id = 57500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = CORN
	tier = duchy
	liege = ENGL
	holder = { character = { type = 10 id = 54501 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = GWYN
	tier = duchy
	liege = ENGL
	holder = { character = { type = 10 id = 54501 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 30003 } character = { type = 10 id = 20006 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = DCRO
	tier = duchy
	liege = CROA
	holder = { character = { type = 10 id = 70030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = CYRE
	tier = duchy
	liege = FATI
	holder = { character = { type = 10 id = 85100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ESTH
	tier = duchy
	liege = DENM
	holder = { character = { type = 10 id = 51523 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = FINL
	tier = duchy
	liege = SWED
	holder = { character = { type = 10 id = 50760 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = FLAN
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 55710 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = FRIE
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 56550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = GALI
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 72900 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = GALC
	tier = duchy
	liege = CAST
	holder = { character = { type = 10 id = 58003 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = GENO
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 63400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = DGEO
	tier = duchy
	liege = GEOR
	holder = { character = { type = 10 id = 66753 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = HAIN
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62742 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = HELL
	tier = duchy
	liege = ARAG
	holder = { character = { type = 10 id = 61510 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = HOLS
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 51940 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = HORM
	tier = duchy
	liege = ILKH
	holder = { character = { type = 10 id = 78022 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = IMER
	tier = duchy
	liege = GEOR
	holder = { character = { type = 10 id = 66520 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = JAMT
	tier = duchy
	liege = NORW
	holder = { character = { type = 10 id = 50800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = KARA
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 78050 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = KIEV
	tier = duchy
	liege = LITH
	holder = { character = { type = 10 id = 72100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = KRET
	tier = duchy
	liege = VENI
	holder = { character = { type = 10 id = 63130 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = KARN
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = LANG
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 63450 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = LEIN
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 54201 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = LUTA
	tier = duchy
	liege = ILKH
	holder = { character = { type = 10 id = 78026 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = LUXE
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62610 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MAZA
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 78080 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MAZO
	tier = duchy
	liege = POLA
	holder = { character = { type = 10 id = 71515 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MEAT
	tier = duchy
	liege = ENGL
	holder = { character = { type = 10 id = 54100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MECK
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 51980 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MEIS
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = DMES
	tier = duchy
	liege = ERET
	holder = { character = { type = 10 id = 76460 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MILA
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 63140 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MOLD
	tier = duchy
	liege = HUNG
	holder = { character = { type = 10 id = 75400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MORA
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62614 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MOSK
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 72840 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = DNAV
	tier = duchy
	liege = NAVA
	holder = { character = { type = 10 id = 55810 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = NORM
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 55502 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = NOVG
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 72300 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ORKN
	tier = duchy
	liege = NORW
	holder = { character = { type = 10 id = 50820 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ORLE
	tier = duchy
	liege = FRAN
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ACHA
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 65550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = PERE
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 72450 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = POLO
	tier = duchy
	liege = LITH
	holder = { character = { type = 10 id = 72350 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = POMM
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 71655 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = PRON
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 72400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = QOMA
	tier = duchy
	liege = ILKH
	holder = { character = { type = 10 id = 78033 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ROST
	tier = duchy
	liege = GOLD
	holder = { character = { type = 10 id = 72800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = RYAZ
	tier = duchy
	liege = GOLD
	holder = { character = { type = 10 id = 72520 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SALA
	tier = duchy
	liege = CAST
	holder = { character = { type = 10 id = 57500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SAMO
	tier = duchy
	liege = LITH
	holder = { character = { type = 10 id = 73508 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SAND
	tier = duchy
	liege = POLA
	holder = { character = { type = 10 id = 71500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SAVO
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62154 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SAXO
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SHIR
	tier = duchy
	liege = ILKH
	holder = { character = { type = 10 id = 78015 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90109 } character = { type = 10 id = 78013 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SINO
	tier = duchy
	liege = ERET
	holder = { character = { type = 10 id = 76480 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SKAN
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 51600 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SMOL
	tier = duchy
	liege = LITH
	holder = { character = { type = 10 id = 72500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SUZD
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 72250 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SZEK
	tier = duchy
	liege = HUNG
	holder = { character = { type = 10 id = 70040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = THES
	tier = duchy
	liege = BYZA
	holder = { character = { type = 10 id = 65530 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = THUR
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = TOSC
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 63320 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = TOUL
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = TREB
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 65800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = TVER
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 72860 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ULST
	tier = duchy
	liege = ENGL
	holder = { character = { type = 10 id = 54614 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = UPLO
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = VALE
	tier = duchy
	liege = ARAG
	holder = { character = { type = 10 id = 60500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = WALL
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 75550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = VARN
	tier = duchy
	liege = BULG
	holder = { character = { type = 10 id = 67550 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = VERO
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 12078 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = WEIS
	tier = duchy
	liege = SCOT
	holder = { character = { type = 10 id = 20019 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = VIDI
	tier = duchy
	liege = BULG
	holder = { character = { type = 10 id = 67500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = WIEL
	tier = duchy
	liege = POLA
	holder = { character = { type = 10 id = 71500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = VLAD
	tier = duchy
	liege = GOLD
	holder = { character = { type = 10 id = 72910 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = VOLG
	tier = duchy
	liege = GOLD
	holder = { character = { type = 10 id = 80250 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = YARO
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 72790 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ZARA
	tier = duchy
	liege = ARAG
	holder = { character = { type = 10 id = 60500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = OSTE
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62020 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = DCAS
	tier = duchy
	liege = CAST
	holder = { character = { type = 10 id = 57500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MURC
	tier = duchy
	liege = CAST
	holder = { character = { type = 10 id = 57630 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SLAV
	tier = duchy
	liege = CROA
	holder = { character = { type = 10 id = 70030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SVIG
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 51530 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = TOLE
	tier = duchy
	liege = CAST
	holder = { character = { type = 10 id = 57500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ARAG
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 60500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BASR
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 61900 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BULG
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 67500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90029 } character = { type = 10 id = 67521 } date = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90030 } character = { type = 10 id = 67522 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BYZA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 65500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = CAST
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 57500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = CROA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 69500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = CUMA
	tier = duchy
	liege = GOLD
	holder = { character = { type = 10 id = 79000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = DENM
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 51500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90035 } character = { type = 10 id = 51530 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ENGL
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = WALE
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 54500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 30000 } character = { type = 10 id = 20006 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = FRAN
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 55500 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90000 } character = { type = 10 id = 54500 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = GEOR
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 66500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = GERM
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 62740 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = HUNG
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 69500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = JERU
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 61700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = LEON
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 57500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = LITH
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 73500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = NAPL
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 61700 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = NAVA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 55810 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = NORW
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 50500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = POLA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 71500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = PORT
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 59500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SCOT
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 53500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SERB
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 68500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SWED
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 50500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = TRAN
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 61500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MJER
	tier = duchy
	liege = FATI
	holder = { character = { type = 10 id = 85230 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MAMM
	tier = duchy
	liege = FATI
	holder = { character = { type = 10 id = 85100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MBAG
	tier = duchy
	liege = ILKH
	holder = { character = { type = 10 id = 78040 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MTRI
	tier = duchy
	liege = FATI
	holder = { character = { type = 10 id = 85290 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MDAM
	tier = duchy
	liege = FATI
	holder = { character = { type = 10 id = 85360 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MELA
	tier = duchy
	liege = FATI
	holder = { character = { type = 10 id = 85440 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MEDE
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 78070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MMED
	tier = duchy
	liege = FATI
	holder = { character = { type = 10 id = 85060 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MSIS
	tier = duchy
	liege = ILKH
	holder = { character = { type = 10 id = 78025 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = PAPA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 78501 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = VENI
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 63600 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = CILI
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 61800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = BALE
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 60620 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = NOSE
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 68800 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = AYDI
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 76200 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = CAND
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 76350 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ERET
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 76450 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = GERI
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 76250 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = GILA
	tier = duchy
	liege = ILKH
	holder = { character = { type = 10 id = 78100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = GOLD
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 80000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = HOSP
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 78502 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ILKH
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 78030 } startdate = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90100 } character = { type = 10 id = 78032 } date = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90101 } character = { type = 10 id = 78026 } date = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90102 } character = { type = 10 id = 78030 } date = { year = 1337 month = january day = 0 } }
	claim = { id = { type = 14712 id = 90103 } character = { type = 10 id = 78041 } date = { year = 1337 month = january day = 0 } }
}
title = {
	tag = KAFS
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 83000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MARI
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 82000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MENT
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 76100 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = OTTO
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 76500 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SARU
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 76150 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = SWIS
	tier = duchy
	liege = GERM
	holder = { character = { type = 10 id = 62085 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = TEKK
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 76400 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = TEUT
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 74000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ZIYA
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 84000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = ESAM
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 86010 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = KAJA
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 86030 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = KHAZ
	tier = duchy
	liege = GOLD
	holder = { character = { type = 10 id = 79200 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = MORD
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 28070 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = WSAM
	tier = duchy
	liege = ----
	holder = { character = { type = 10 id = 86000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = FATI
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 85000 } startdate = { year = 1337 month = january day = 0 } }
}
title = {
	tag = KARM
	tier = kingdom
	liege = ----
	holder = { character = { type = 10 id = 76300 } startdate = { year = 1337 month = january day = 0 } }
}